//
//  ExamStore2021.swift
//  HandGosi
//
//  Created by Sy Lee on 2022/08/22.
//

import Foundation

class ExamStore2021 {
    var exams2021: [ExamModel] = []
    
    init() {
        saveExam202111()
        saveExam202112()
        saveExam202113()
        saveExam202121()
        saveExam202122()
        saveExam202123()
    }
    
    //국가직
    func saveExam202111() {
        let questions
        = [
           QuestionModel(num: 1,
                         questionText: "맞춤법에 맞는 것만으로 묶은 것은?",
                         num1Text: "돌나물, 꼭지점, 페트병, 낚시꾼",
                         num2Text: "흡입량, 구름양, 정답란, 칼럼난",
                         num3Text: "오뚝이, 싸라기, 법석, 딱다구리",
                         num4Text: "찻간(車間), 홧병(火病), 셋방(貰房), 곳간(庫間)",
                         answer: 2),
           QuestionModel(num: 2,
                         questionText: "㉠의 단어와 의미가 같은 것은?",
                         reference: "친구에게 줄 선물을 예쁜 포장지에 ㉠" + "싼다.".underLined,
                         num1Text: "사람들이 안채를 겹겹이 " + "싸고".underLined + " 있다.",
                         num2Text: "사람들은 봇짐을 " + "싸고".underLined + " 산길로 향한다.",
                         num3Text: "아이는 몇 권의 책을 " + "싼".underLined + " 보퉁이를 들고 있다.",
                         num4Text: "내일 학교에 가려면 책가방을 미리 " + "싸".underLined + " 두어라.",
                         answer: 3),
           QuestionModel(num: 3,
                         questionText: "가장 자연스러운 문장은?",
                         num1Text: "날씨가 선선해지니 역시 책이 잘 읽힌다.",
                         num2Text: "이렇게 어려운 책을 속독으로 읽는 것은 하늘의 별 따기이다.",
                         num3Text: "내가 이 일의 책임자가 되기보다는 직접 찾기로 의견을 모았다.",
                         num4Text: "그는 시화전을 홍보하는 일과 시화전의 진행에 아주 열성적이다.",
                         answer: 1),
           QuestionModel(num: 4,
                         questionText: "다음 글의 설명 방식으로 적절하지 않은 것은?",
                         reference: "빛 공해란 인공조명의 과도한 빛이나 조명 영역 밖으로 누출되는 빛이 인간의 건강하고 쾌적한 생활을 방해하거나 환경에 피해를 주는 상태를 말한다. 국제 과학 저널인 〖사이언스 어드밴스〗의 ‘전 세계 빛 공해 지도’에 따르면, 우리나라는 빛 공해가 심각한 국가이다. 빛 공해는 멜라토닌 부족을 초래해 인간에게 수면 부족과 면역력 저하 등의 문제를 유발하고, 농작물의 생산량 저하, 생태계 교란 등의 문제를 일으킨다.",
                         num1Text: "빛 공해의 정의를 제시하고 있다.",
                         num2Text: "빛 공해의 주요 요인인 인공조명의 누출 원인을 제시하고 있다.",
                         num3Text: "자료를 인용하여 빛 공해가 심각한 국가로 우리나라를 제시하고 있다.",
                         num4Text: "사례를 들어 빛 공해의 악영향을 제시하고 있다.",
                         answer: 2),
           QuestionModel(num: 5,
                         questionText: "㉠,㉡의 사례로 옳은 것만을 짝 지은 것은?",
                         reference: "용언의 불규칙활용은 크게 ㉠어간만 불규칙하게 바뀌는 부류, ㉡어미만 불규칙하게 바뀌는 부류, 어간과 어미 둘 다 불규칙하게 바뀌는 부류로 나눌 수 있다.",
                         num1Text: "걸음이 " + "빠름".underLined + " - 꽃이 " + "노람".underLined,
                         num2Text: "잔치를 " + "치름".underLined + " - 공부를 " + "함".underLined,
                         num3Text: "라면이 " + "불음".underLined + " - 합격을 " + "바람".underLined,
                         num4Text: "우물물을 " + "품".underLined + " - 목적지에 " + "이름".underLined,
                         answer: 4),
           QuestionModel(num: 6,
                         questionText: "㉠~㉣의 의미로 적절하지 않은 것은?",
                         reference: "二月人 보로매 아으 노피 ㉠" + "현".underLined + " 燈ᄉ블 다호라\n萬人 비취실 즈샷​다 아으 動動다리\n三月 나며 開​ 아​으 滿春  욋​고​지여\n​ ​브롤 ㉡" + "즈".underLined + " ​디​녀 나샷다 아으 動動다리\n四月 아니 ㉢" + "니저".underLined + " 아으 오실셔  곳고리새여\n㉣" + "므슴다".underLined + " 錄事니​ 녯 ​나​ 닛​고신뎌 아으 動動다리\n\n-작자 미상, 〖動動〗에서-",
                         num1Text: "㉠은 ‘켠’을 의미한다.",
                         num2Text: "㉡은 ‘모습을’을 의미한다.",
                         num3Text: "㉢은 ‘잊어’를 의미한다.",
                         num4Text: "㉣은 ‘무심하구나’를 의미한다.",
                         answer: 4),
           QuestionModel(num: 7,
                         questionText: "한자 표기가 옳은 것은?",
                         num1Text: "그분은 냉혹한 현실(現室)을 잘 견뎌 냈다.",
                         num2Text: "첫 손님을 야박(野薄)하게 대해서는 안 된다.",
                         num3Text: "그에게서 타고난 승부 근성(謹性)이 느껴진다.",
                         num4Text: "그는 평소 희망했던 기관에 채용(債用)되었다.",
                         answer: 2),
           QuestionModel(num: 8,
                         questionText: "다음 토의에 대한 설명으로 적절하지 않은 것은?",
                         reference: "사회자: 오늘의 토의 주제는 ‘통일 시대의 남북한 언어가 나아갈 길’입니다. 먼저 최○○ 교수님께서 ‘남북한 언어 차이와 의사소통’이라는 제목으로 발표해 주시겠습니다.\n\n최 교수:남한과 북한의 말은 비슷하지만 다른 점이 있습니다. 남한과 북한의 어휘 차이가 대표적입니다. 남한과 북한의 어휘 차이를 분석한 결과, ...(중략)... 앞으로도 남북한 언어 차이에 대한 연구가 지속 되어야 합니다.\n\n사회자:이로써 최 교수님의 발표를 마치겠습니다. 다음은 정○○ 박사님의 ‘남북한 언어의 동질성 회복 방안’에 대한 발표가 있겠습니다.\n\n정 박사: 앞으로 통일을 대비해 남북한 언어의 다른 점을 줄여 나가는 노력이 필요합니다. 실제로도 남한과 북한의 학자들로 구성된 ‘겨레말큰사전 편찬위원회’ 에서는 남북한 공통의 사전인 〖겨레말큰사전〗을 만들며 서로의 차이를 이해하고 받아들이기 위한 노력을 하고 있습니다. ... (중략) ...\n\n사회자:그러면 질의응답이 있겠습니다. 시간상 간략하게 질문해 주시기 바랍니다.\n\n청중A: 두분의 말씀 잘 들었습니다. 남북한 언어의 차이와 이를 극복하는 방안을 말씀하셨는데요. 그렇다면 통일 시대에 대비한 언어 정책에는 무엇이 있을까요?",
                         num1Text: "학술적인 주제에 대해 발표 형식으로 진행되고 있다.",
                         num2Text: "사회자는 발표자 간의 이견을 조정하여 의사결정을 유도하고 있다.",
                         num3Text: "발표자는 주제에 대한 자신의 견해를 밝혀 청중에게 정보를 제공하고 있다.",
                         num4Text: "청중 A는 발표자의 발표 내용을 확인하고 주제와 관련된 질문을 하고 있다.",
                         answer: 2),
           QuestionModel(num: 9,
                         questionText: "㉠~㉣은 ‘공손하게 말하기’에 대한 설명이다. ᄀ~ᄅ을 적용한 B의 대답으로 적절하지 않은 것은?",
                         reference: "㉠자신을 상대방에게 낮추어 겸손하게 말해야 한다.\n㉡상대방의 처지를 고려하여 상대방이 부담을 갖지 않도록 말해야 한다.\n㉢상대방이 관용을 베풀 수 있도록 문제를 자신의 탓으로 돌려 말해야 한다.\n㉣상대방의 의견에서 동의하는 부분을 찾아 인정해 준 다음에 자신의 의견을 말해야 한다.",
                         num1Text: "㉠A: “이번에 제출한 디자인 시안 정말 멋있었어.”\n B: “아닙니다. 아직도 여러모로 부족한 부분이 많습니다.”",
                         num2Text: "㉡A: “미안해요. 생각보다 길이 많이 막혀서 늦었어요.”\n B: “괜찮아요. 쇼핑하면서 기다리니 시간 가는 줄 몰랐어요.”",
                         num3Text: "㉢A: “혹시 내가 설명한 내용이 이해 가니?”\n B: “네 목소리가 작아서 내용이 잘 안 들렸는데 다시 한 번 크게 말해 줄래?”",
                         num4Text: "㉣A: “가원아, 경희 생일 선물로 귀걸이를 사주는 것은 어때?”\n B: “그거 좋은 생각이네. 하지만 경희의 취향을 우리가 잘 모르니까 귀걸이 대신 책을 선물하는 게 어떨까?”",
                         answer: 3),
           QuestionModel(num: 10,
                         questionText: "하버마스의 주장에 부합하는 사례로 가장 적절한 것은?",
                         reference: " 하버마스는 18세기부터 현대까지 미디어의 등장 배경과 발전 과정을 분석하면서, 공공 영역의 부상과 쇠퇴를 추적했다. 하버마스에게 공공 영역은 일반적 쟁점에 대한 토론과 의견을 형성하는 공공 토론의 민주적 장으로서 역할을 한다.\n 하버마스는 17세기와 18세기 유럽 도시의 살롱에서 당시의 공공 영역을 찾았다. 비록 소수의 사람들만이 살롱 토론 문화에 참여했으나, 공공 토론을 통해 정치적 문제를 해결 하는 논리를 도입할 수 있었기 때문에 살롱이 초기 민주주의 발전에 중요한 역할을 했다고 그는 주장한다. 적어도 살롱 문화의 원칙에서 공개적 토론을 위한 공공 영역은 각각의 참석자들에게 동등한 자격을 부여했다.\n 그러나 하버마스에 따르면, 현대 사회에서 민주적 토론은 문화 산업의 발달과 함께 퇴보했다. 대중매체와 대중오락의 보급은 공공 영역이 공허해지는 원인으로 작용했다. 상업적 이해관계는 공공의 이해관계에 우선하게 되었다. 공공 여론은 개방적이고 합리적 토론을 통해서가 아니라 광고에서처럼 조작과 통제를 통해 형성되고 있다.\n 미디어가 점차 상업화되면서 하버마스가 주장한 대로 공공 영역이 침식당하고 있다. 상업화된 미디어는 광고 수입에 기대어 높은 시청률과 수익을 보장하는 콘텐츠 제작만을 선호하게 되었다. 그 결과 공적 주제에 대한 시민들의 논의와 소통의 장이 줄어들어 결과적으로 공공 영역이 축소되었다. 많은 것을 약속한 미디어는 이제 민주주의 문제의 일부로 변해 버린 것이다.",
                         num1Text: "살롱 문화에서 특정 사회 계층에 대한 비판적인 토론은 허용 되지 않았다.",
                         num2Text: "인터넷의 발달과 보급은 상업적 광고뿐만 아니라 공익 광고도 증가시켰다.",
                         num3Text: "글로벌 미디어가 발달하더라도 국제 사회의 공공 영역은 공허해지지 않는다.",
                         num4Text: "수익성 위주의 미디어 플랫폼과 콘텐츠가 더 많아지면서 민주적 토론이 감소되었다.",
                         answer: 4),
           QuestionModel(num: 11,
                         questionText: "㉠~㉤의 전개 순서로 가장 자연스러운 것은?",
                         reference: " 폭설, 즉 대설이란 많은 눈이 시간적, 공간적으로 집중되어 내리는 현상을 말한다.\n㉠그런데 눈은 한 시간 안에 5 cm 이상 쌓일 수 있어 순식간에 도심 교통을 마비시키는 위력을 가지고 있다.\n㉡또한, 경보는 24시간 신적설이 20 cm 이상 예상될 때이다.\n㉢다만, 산지는 24시간 신적설이 30cm 이상 예상될 때 발령된다.\n㉣이때 대설의 기준으로 주의보는 24시간 새로 쌓인 눈이 5 cm 이상이 예상될 때이다.\n㉤이뿐만 아니라 운송, 유통, 관광, 보험을 비롯한 서비스 업종과 사회 전반에 영향을 미친다.",
                         num1Text: "ᄀ-ᄆ-ᄂ-ᄃ-ᄅ",
                         num2Text: "ᄀ-ᄅ-ᄆ-ᄃ-ᄂ",
                         num3Text: "ᄅ-ᄂ-ᄃ-ᄀ-ᄆ",
                         num4Text: "ᄅ-ᄀ-ᄆ-ᄃ-ᄂ",
                         answer: 3),
           QuestionModel(num: 12,
                         questionText: "다음 글의 사례로 적절하지 않은 것은?",
                         reference: " 인간은 언어를 사용하며 언어는 인간의 사고, 사회, 문화를 반영한다. 인간의 지적 능력이 발달하게 된 것은 바로 언어를 사용하기 때문이다.\n 언어와 사고는 기본적으로 상호작용을 한다. 둘 중 어느 것이 먼저 발달하고 어떻게 영향을 주는지는 알 수 없다. 그러나 언어와 사고가 서로 깊은 관계를 맺고 있다는 사실은 여러 가지 근거를 통해서 뒷받침된다.",
                         num1Text: "영어의 ‘쌀(rice)’에 해당하는 우리말에는 ‘모’, ‘벼’, ‘쌀’, ‘밥’ 등이 있다.",
                         num2Text: "어떤 사람은 산도 파랗다고 하고, 물도 파랗다고 하고, 보행 신호의 녹색등도 파랗다고 한다.",
                         num3Text: "일상생활에서 어떠한 사물의 개념은 머릿속에서 맴도는데도 그 명칭을 떠올리지 못할 때가 있다.",
                         num4Text: "우리나라는 수박(watermelon)은 ‘박’의 일종으로 보지만 어떤 나라는 ‘멜론(melon)’에 가까운 것으로 파악한다.",
                         answer: 3),
           QuestionModel(num: 13,
                         questionText: "다음 글의 주된 서술 방식은?",
                         reference: " 변지의가 천리길을 마다하지 않고 나를 찾아왔다. 내가 그 뜻을 물었더니, 문장 공부를 하기 위해 나를 찾아왔다고 했다. 때마침 이날 우리 아이들이 나무를 심었기에 그 나무를 가리켜 이렇게 말해 주었다.\n “사람이 글을 쓰는 것은 나무에 꽃이 피는 것과 같다. 나무를 심는 사람은 가장 먼저 뿌리를 북돋우고 줄기를 바로잡는 일에 힘써야 한다. ...(중략) ... 나무의 뿌리를 북돋아 주듯 진실한 마음으로 온갖 정성을 쏟고, 줄기를 바로잡듯 부지런히 실천하며 수양하고, 진액이 오르듯 독서에 힘쓰고, 가지와 잎이 돋아나듯 널리 보고 들으며 두루 돌아다녀야 한다. 그렇게 해서 깨달은 것을 헤아려 표현한다면 그것이 바로 좋은 글이요, 사람들이 칭찬을 아끼지 않는 훌륭한 문장이 된다. 이것이야말로 참다운 문장이라고 할 수 있다.”",
                         num1Text: "서사",
                         num2Text: "분류",
                         num3Text: "비유",
                         num4Text: "대조",
                         answer: 3),
           QuestionModel(num: 14,
                         questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                         reference: " 언어마다 고유의 표기 체계가 있는데, 이는 읽기 과정에 영향을 미친다. 알파벳 언어는 표기 체계에 따라 철자 읽기의 명료성 수준이 달라진다. 철자 읽기가 명료하다는 것은 한 글자에 대응되는 소리가 규칙적이어서 글자와 소리의 대응이 거의 일대일이라는 것을 의미한다. 그 예로 이탈리아어와 스페인어가 있다. 이 두 언어의 사용자는 의미를 전혀 모르는 새로운 단어를 발견하더라도 보자마자 정확한발음을할수있다. 이에비해영어는철자읽기의 명료성이 낮은 언어이다. 영어는 발음이 아예 나지 않는 묵음과 같은 예외도 많은 편이고 글자에 대응하는 소리도 매우 다양하다.\n 한편 알파벳 언어를 읽을 때 사용하는 뇌의 부위는 유사 하지만 뇌의 부위에 의존하는 방식에는 차이가 있다. 영어와 이탈리아어를 읽는 사람은 동일하게 좌반구의 읽기 네트워크를 사용한다. 하지만 무의미한 단어를 읽을 때 영어를 읽는 사람은 암기된 단어의 인출과 연관된 뇌 부위에 더 의존하는 반면 이탈리아어를 읽는 사람은 음운 처리에 연관된 뇌 부위에 더 의존한다. 왜냐하면 무의미한 단어를 읽을 때 이탈리아어를 읽는 사람은 규칙적인 음운 처리 규칙을 적용하는 반면에, 영어를 읽는 사람은 암기해 둔 수많은 예외들을 떠올리기 때문이다.",
                         num1Text: "알파벳 언어의 철자 읽기는 소리와 표기의 대응과 관련되는데, 각 소리가 지닌 특성은 철자 읽기의 명료성을 판단하는 기준이 된다.",
                         num2Text: "영어 사용자는 무의미한 단어를 읽을 때 좌반구의 읽기 네트워크를 활용하면서 암기된 단어의 인출과 연관된 뇌 부위에 더욱 의존한다.",
                         num3Text: "이탈리아어는 소리와 글자의 대응이 규칙적이어서 낯선 단어를 발음할 때 영어에 비해 철자 읽기의 명료성이 높다.",
                         num4Text: "영어는 음운 처리 규칙에 적용되지 않는 예외들이 많아서 스페인어에 비해 소리와 글자의 대응이 덜 규칙적이다.",
                         answer: 1),
           QuestionModel(num: 15,
                         questionText: "(가)~(라)에 대한 이해로 적절하지 않은 것은?",
                         reference: "(가)\n반중(盤中) 조홍(早紅)감이 고아도 보이다​\n유자 안이라도 품엄즉도 다​마​​\n품어 가 반기리 업슬새 글노 설워​이​다\n\n(나)\n동짓​기​나긴 밤을 한 허리를 버혀 내여\n춘풍 니불 아래 서리서리 너헛다가\n어론 님 오신 날 밤이여든 구뷔구뷔 펴리라\n\n(다) 말 업슨 청산(靑山)이오 태(態) 업슨 유수(流水)로다\n 갑 업슨 청풍(淸風)이오 님​업슨 명월(明月)이로다\n이 중에 병 업슨 이 몸이 분별 업시 늘그리라\n\n(라)\n농암(籠巖)에 올라보니 노안(老眼)이 유명(猶明)이로다\n인사(人事)이 변들​​산천이​가​샐가\n암전(巖前)에 모수 모구(某水 某丘)이 어제 본 ​예​라",
                         num1Text: "(가)는 고사의 인용을 통해 돌아가신 부모님에 대한 그리움을 표현하고 있다.",
                         num2Text: "(나)는 의태적 심상을 통해 임에 대한 기다림을 표현하고 있다.",
                         num3Text: "(다)는 대구와 반복을 통해 자연에 귀의하려는 의지를 표현하고 있다.",
                         num4Text: "(라)는 자연과의 대조를 통해 허약해진 노년의 무력함을 표현하고 있다.",
                         answer: 4),
           QuestionModel(num: 16,
                         questionText: "다음 글에 대한 이해로 가장 적절한 것은?",
                         reference: " 암소의 뿔은 수소의 그것보다도 한층 더 겸허하다. 이 애상적인 뿔이 나를 받을 리 없으니 나는 마음 놓고 그 곁 풀밭에 가 누워도 좋다. 나는 누워서 우선 소를 본다.\n 소는 잠시 반추를 그치고 나를 응시한다.\n ‘이 사람의 얼굴이 왜 이리 창백하냐. 아마 병인인가 보다. 내 생명에 위해를 가하려는 거나 아닌지 나는 조심해야 되지.’\n 이렇게 소는 속으로 나를 심리하였으리라. 그러나 오 분 후에는 소는 다시 반추를 계속하였다. 소보다도 내가 마음을 놓는다.\n 소는 식욕의 즐거움조차를 냉대할 수 있는 지상 최대의 권태자다. 얼마나 권태에 지질렸길래 이미 위에 들어간 식물을 다시 게워 그 시큼털털한 반소화물의 미각을 역설적으로 향락하는 체해 보임이리오?\n 소의 체구가 크면 클수록 그의 권태도 크고 슬프다. 나는 소 앞에 누워 내 세균 같이 사소한 고독을 겸손하면서 나도 사색의 반추는 가능할는지 불가능할는지 몰래 좀 생각해 본다.\n\n -이상, 〖권태〗에서-",
                         num1Text: "대상의 행위를 통해 글쓴이의 심리가 투사되고 있다.",
                         num2Text: "과거의 삶을 회상하며 글쓴이의 처지를 후회하고 있다.",
                         num3Text: "공간의 이동을 통해 글쓴이의 무료함을 표현하고 있다.",
                         num4Text: "현실에 대한 글쓴이의 불만이 반성적 어조로 표출되고 있다.",
                         answer: 1),
           QuestionModel(num: 17,
                         questionText: "다음 글에서 ‘황거칠’이 처한 상황에 어울리는 한자 성어로 가장 적절한 것은?",
                         reference: "  황거칠 씨는 더 참을 수가 없었다. 그는 거의 발작적으로 일어섰다.\n  “이 개 같은 놈들아, 어쩌면 남이 먹는 식수까지 끊으려노?”\n  그는 미친 듯이 우르르 달려가서 한 인부의 괭이를 억지로 잡아서 저만큼 내동댕이쳤다. ... (중략) ...\n  경찰은 발포를-다행히 공포였지만-해서 겨우 군중을 해산시키고, 황거칠 씨와 청년 다섯 명을 연행해 갔다. 물론 강제집행도 일시 중단되었었다.\n  경찰에 끌려간 사람들은 밤에도 풀려나오지 못했다. 공무집행 방해에다, 산주의 권리행사 방해, 그리고 폭행죄 까지 뒤집어쓰게 되었던 것이다. 그래서 그 이튿날도 풀려 나오질 못했다. 쌍말로 썩어 갔다.\n  황거칠 씨는 모든 죄를 자기가 안아맡아서 처리하려고 했다. 그러나 그것이 뜻대로 되지 않았다. 면회를 오는 가족들의 걱정스런 얼굴을 보자, 황거칠 씨는 가슴이 아팠다. 그는 만부득이 담당 경사의 타협안에 도장을 찍기로 했다. 석방의 조건으로서, 다시는 강제집행을 방해하지 않겠다는 각서였다.\n  이리하여 황거칠 씨는 애써 만든 산수도를 포기하게 되고 ‘마삿등’은 한때 도로 물 없는 지대가 되고 말았다.\n\n -김정한, 〖산거족〗에서-",
                         num1Text: "同病相憐",
                         num2Text: "束手無策",
                         num3Text: "自家撞着",
                         num4Text: "輾轉反側",
                         answer: 2),
           QuestionModel(num: 18,
                         questionText: "다음 글의 특징으로 가장 적절한 것은?",
                         reference: "살아가노라면\n가슴 아픈 일 한두 가지겠는가\n\n깊은 곳에 뿌리를 감추고\n흔들리지 않는 자기를 사는 나무처럼\n그걸 사는 거다\n\n봄, 여름, 가을, 긴 겨울을\n높은 곳으로\n보다 높은 곳으로, 쉬임 없이\n한결같이\n\n사노라면\n가슴 상하는 일 한두 가지겠는가\n\n-조병화, 〖나무의 철학〗-",
                         num1Text: "문답법을 통해 과거의 삶을 반추하고 있다.",
                         num2Text: "반어적 표현을 활용하여 슬픔의 정서를 나타내고 있다.",
                         num3Text: "사물을 의인화하여 현실을 목가적으로 보여 주고 있다.",
                         num4Text: "설의적 표현을 활용하여 삶의 깨달음을 강조하고 있다.",
                         answer: 4),
           QuestionModel(num: 19,
                         questionText: "㉠에 들어갈 말로 가장 적절한 것은?",
                         reference: " 한 민족이 지닌 문화재는 그 민족 역사의 누적일 뿐 아니라 그 누적된 민족사의 정수로서 이루어진 혼의 상징이니, 진실로 살아 있는 민족적 신상(神像)은 이를 두고 달리 없을 것이다. 더구나 국보로 선정된 문화재는 우리 민족의 성력(誠力)과 정혼(精魂)의 결정으로 그 우수한 질과 희귀한 양에서 무비(無比)의 보(寶)가 된 자이다. 그러므로 국보 문화재는 곧 민족 전체의 것이요, 민족을 결속하는 정신적 유대로서 민족의 힘의 원천이라 할 것이다.\n 로마는 하루아침에 만들어지지 않는다는 말도 그 과거 문화의 존귀함을 말하는 것이요, ( ᄀ )는 말도 국보 문화재가 얼마나 힘 있는가를 밝힌 예증이 된다.",
                         num1Text: "구르는 돌에는 이끼가 끼지 않는다",
                         num2Text: "지식은 나눌 수 있지만 지혜는 나눌 수 없다",
                         num3Text: "사람은 겪어 보아야 알고 물은 건너 보아야 안다",
                         num4Text: "그 무엇을 내놓는다고 해도 셰익스피어와는 바꾸지 않는다",
                         answer: 4),
           QuestionModel(num: 20,
                         questionText: "다음 글에서 추론한 내용으로 적절하지 않은 것은?",
                         reference: " 과학의 개념은 분류 개념, 비교 개념, 정량 개념으로 구분할 수 있다. 식물학과 동물학의 종, 속, 목처럼 분명한 경계를 가지고 대상들을 분류하는 개념들이 분류 개념이다. 어린이들이 맨 처음에 배우는 단어인 ‘사과’, ‘개’, ‘나무’ 같은 것 역시 분류 개념인데, 하위 개념으로 분류할수록 그대상에대한정보가더많이전달된다. 또한, 현실세계에 적용대상이 하나도 없는 분류 개념도 있을 수 있다. 예를 들어 ‘유니콘’이라는 개념은 ‘이마에 뿔이 달린 말의 일종임’ 같은 분명한 정의가 있기에 ‘유니콘’은 분류 개념으로 인정되는 것이다.\n ‘더 무거움’, ‘더 짧음’ 등과 같은 비교 개념은 분류 개념보다 설명에 있어서 정보 전달에 더 효과적이다. 이것은 분류 개념처럼 자연의 사실에 적용되어야 하지만, 분류 개념과 달리 논리적 관계도 반드시 성립해야 한다. 예를 들면, 대상A의 무게가 대상B의 무게보다 더 무겁다면, 대상B의 무게가 대상 A의 무게보다 더 무겁다고 말할 수 없는 것처럼 ‘더 무거움’ 같은 비교 개념은 논리적 관계를 반드시 따라야 한다.\n 마지막으로 정량 개념은 비교 개념으로부터 발전된 것인데, 이것은 자연의 사실로부터 파악할 수 있는 물리량을 측정함 으로써 만들어진다. 물리량을 측정하기 위해서는 몇 가지 규칙이 필요한데, 그 규칙에는 두 물리량의 크기를 비교하는 경험적 규칙과 물리량의 측정 단위를 정하는 규칙 등이 포함된다. 이러한 정량 개념은 자연에 의해서 주어지는 것이 아니라 우리가 자연현상에 수를 적용하는 과정에서 생겨나는 것이다. 정량 개념은 과학의 언어를 수많은 비교 개념 대신 수를 사용할 수 있게 하여 과학 발전의 기초가 되었다.",
                         num1Text: "‘호랑나비’는 ‘나비’와 동일한 종에 속하지만, 나비에 비해 정보량이 적다.",
                         num2Text: "‘용(龍)’은 현실 세계에 적용할 수 있는 지시물이 없더라도 분류 개념으로 인정된다.",
                         num3Text: "‘꽃’이나 ‘고양이’와 같은 개념은 논리적 관계를 따라야 하는 것은 아니기 때문에 비교 개념에 포함되지 않는다.",
                         num4Text: "물리량을 측정할 수 있는 ‘cm’나 ‘kg’과 같은 측정 단위는 자연현상에 수를 적용할 수 있게 해 주었다.",
                         answer: 1),
           
        ]
        let exam = ExamModel(id: 202111, year: 2021, examTypeID: "국가직", subjectID: "국어", questions: questions)
        exams2021.append(exam)
    }
    func saveExam202112() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오. [1~3]",
                      reference: "Privacy as a social practice shapes individual behavior " + "in conjunction with".underLined + " other social practices and is therefore central to social life.",
                      num1Text: "in combination with",
                      num2Text: "in comparison with",
                      num3Text: "in place of",
                      num4Text: "in case of",
                      answer: 1),
        QuestionModel(num: 2,
                      questionText: "",
                      reference: "The influence of Jazz has been so " + "pervasive".underLined + " that most popular music owes its stylistic roots to jazz.",
                      num1Text: "deceptive",
                      num2Text: "ubiquitous",
                      num3Text: "persuasive",
                      num4Text: "disastrous",
                      answer: 2),
        QuestionModel(num: 3,
                      questionText: "",
                      reference: "This novel is about the " + "vexed".underLined + " parents of an unruly teenager who quits school to start a business.",
                      num1Text: "callous",
                      num2Text: "annoyed",
                      num3Text: "reputable",
                      num4Text: "confident",
                      answer: 2),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "A group of young demonstrators attempted to _________ the police station.",
                      num1Text: "line up",
                      num2Text: "give out",
                      num3Text: "carry on",
                      num4Text: "break into",
                      answer: 4),
        QuestionModel(num: 5,
                      questionText: "다음 글의 내용과 일치하는 것은?",
                      reference: "The most notorious case of imported labor is of course the Atlantic slave trade, which brought as many as ten million enslaved Africans to the New World to work the plantations. But although the Europeans may have practiced slavery on the largest scale, they were by no means the only people to bring slaves into their communities: earlier, the ancient Egyptians used slave labor to build their pyramids, early Arab explorers were often also slave traders, and Arabic slavery continued into the twentieth century and indeed still continues in a few places. In the Americas some native tribes enslaved members of other tribes, and slavery was also an institution in many African nations, especially before the colonial period.",
                      num1Text: "African laborers voluntarily moved to the New World.",
                      num2Text: "Europeans were the first people to use slave labor.",
                      num3Text: "Arabic slavery no longer exists in any form.",
                      num4Text: "Slavery existed even in African countries.",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "어법상 옳은 것은?",
                      num1Text: "This guide book tells you where should you visit in Hong Kong.",
                      num2Text: "I was born in Taiwan, but I have lived in Korea since I started work.",
                      num3Text: "The novel was so excited that I lost track of time and missed the bus.",
                      num4Text: "It’s not surprising that book stores don’t carry newspapers any more, doesn’t it?",
                      answer: 2),
        QuestionModel(num: 7,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "Warming temperatures and loss of oxygen in the sea will shrink hundreds of fish species―from tunas and groupers to salmon, thresher sharks, haddock and cod―even more than previously thought, a new study concludes. Because warmer seas speed up their metabolisms, fish, squid and other water- breathing creatures will need to draw more oxygen from the ocean. At the same time, warming seas are already reducing the availability of oxygen in many parts of the sea. A pair of University of British Columbia scientists argue that since the bodies of fish grow faster than their gills, these animals eventually will reach a point where they can’t get enough oxygen to sustain normal growth. “What we found was that the body size of fish decreases by 20 to 30 percent for every 1 degree Celsius increase in water temperature,” says author William Cheung.",
                      num1Text: "Fish Now Grow Faster than Ever",
                      num2Text: "Oxygen’s Impact on Ocean Temperatures",
                      num3Text: "Climate Change May Shrink the World’s Fish",
                      num4Text: "How Sea Creatures Survive with Low Metabolism",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "밑줄 친 부분 중 어법상 옳지 않은 것은?",
                      reference: "Urban agriculture (UA) has long been dismissed as a fringe activity that has no place in cities; however, its potential is beginning to ①" + "be realized".underLined + ". In fact, UA is about food self-reliance: it involves ②" + "creating".underLined + " work and is a reaction to food insecurity, particularly for the poor. Contrary to ③" + "which".underLined + " many believe, UA is found in every city, where it is sometimes hidden, sometimes obvious. If one looks carefully, few spaces in a major city are unused. Valuable vacant land rarely sits idle and is often taken over―either formally, or informally―and made ④" + "productive.".underLined,
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 3),
        QuestionModel(num: 9,
                      questionText: "주어진 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "For example, the state archives of New Jersey hold more than 30,000 cubic feet of paper and 25,000 reels of microfilm.",
                      reference2: "Archives are a treasure trove of material: from audio to video to newspapers, magazines and printed material―which makes them indispensable to any History Detective investigation. While libraries and archives may appear the same, the differences are important. ( 1 ) An archive collection is almost always made up of primary sources, while a library contains secondary sources. ( 2 ) To learn more about the Korean War, you’d go to a library for a history book. If you wanted to read the government papers, or letters written by Korean War soldiers, you’d go to an archive. ( 3 ) If you’re searching for information, chances are there’s an archive out there for you. Many state and local archives store public records―which are an amazing, diverse resource. ( 4 ) An online search of your state’s archives will quickly show you they contain much more than just the minutes of the legislature―there are detailed land grant information to be found, old town maps, criminal records and oddities such as peddler license applications.\n\n * treasure trove: 귀중한 발굴물(수집물)\n * land grant: (대학.철도 등을 위해) 정부가 주는 땅",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "다음 글의 흐름상 가장 어색한 문장은?",
                      reference: "The term burnout refers to a “wearing out” from the pressures of work. Burnout is a chronic condition that results as daily work stressors take their toll on employees. ①" + "The most widely adopted conceptualization of burnout has been developed by Maslach and her colleagues in their studies of human service workers.".underLined + " Maslach sees burnout as consisting of three interrelated dimensions. The first dimension―emotional exhaustion―is really the core of the burnout phenomenon. ②" + "Workers suffer from emotional exhaustion when they feel fatigued, frustrated, used up, or unable to face another day on the job.".underLined + " The second dimension of burnout is a lack of personal accomplishment. ③" + "This aspect of the burnout phenomenon refers to workers who see themselves as failures, incapable of effectively accomplishing job requirements.".underLined + " ④" + "Emotional labor workers enter their occupation highly motivated although they are physically exhausted.".underLined + " The third dimension of burnout is depersonalization. This dimension is relevant only to workers who must communicate interpersonally with others (e.g. clients, patients, students) as part of the job.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오. [11~12]",
                      reference: "A: Were you here last night?\n\nB: Yes. I worked the closing shift. Why?\n\nA: The kitchen was a mess this morning. There was foodspattered on the stove, and the ice trays were not in the freezer.\n\nB: I guess I forgot to go over the cleaning checklist.\n\nA: You know how important a clean kitchen is.\n\nB: I’m sorry. _________________________",
                      num1Text: "I won’t let it happen again.",
                      num2Text: "Would you like your bill now?",
                      num3Text: "That’s why I forgot it yesterday.",
                      num4Text: "I’ll make sure you get the right order.",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "",
                      reference: "A: Have you taken anything for your cold?\nB: No, I just blow my nose a lot.\nA: Have you tried nose spray?\nB: ____________________________\nA: It works great.\nB: No, thanks. I don’t like to put anything in my nose, so I’ve never used it.",
                      num1Text: "Yes, but it didn’t help.",
                      num2Text: "No, I don’t like nose spray.",
                      num3Text: "No, the pharmacy was closed.",
                      num4Text: "Yeah, how much should I use?",
                      answer: 2),
        QuestionModel(num: 13,
                      questionText: "다음 글의 내용과 일치하지 않는 것은?",
                      reference: "Deserts cover more than one-fifth of the Earth’s land area, and they are found on every continent. A place that receives less than 25 centimeters (10 inches) of rain per year is considered a desert. Deserts are part of a wider class of regions called drylands. These areas exist under a “moisture deficit,” which means they can frequently lose more moisture through evaporation than they receive from annual precipitation. Despite the common conceptions of deserts as hot, there are cold deserts as well. The largest hot desert in the world, northern Africa’s Sahara, reaches temperatures of up to 50 degrees Celsius (122 degrees Fahrenheit) during the day. But some deserts are always cold, like the Gobi Desert in Asia and the polar deserts of the Antarctic and Arctic, which are the world’s largest. Others are mountainous. Only about 20 percent of deserts are covered by sand. The driest deserts, such as Chile’s Atacama Desert, have parts that receive less than two millimeters (0.08 inches) of precipitation a year. Such environments are so harsh and otherworldly that scientists have even studied them for clues about life on Mars. On the other hand, every few years, an unusually rainy period can produce “super blooms,” where even the Atacama becomes blanketed in wildflowers.",
                      num1Text: "There is at least one desert on each continent.",
                      num2Text: "The Sahara is the world’s largest hot desert.",
                      num3Text: "The Gobi Desert is categorized as a cold desert.",
                      num4Text: "The Atacama Desert is one of the rainiest deserts.",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "우리말을 영어로 가장 잘 옮긴 것을 고르시오. [14~15]",
                      num1Text: "나는 너의 답장을 가능한 한 빨리받기를 고대한다.\n→ I look forward to receive your reply as soon as possible.",
                      num2Text: "그는 내가 일을 열심히 했기 때문에 월급을 올려 주겠다고 말했다.\n→ He said he would rise my salary because I worked hard.",
                      num3Text: "그의 스마트 도시 계획은 고려할 만했다.\n→ His plan for the smart city was worth considered.",
                      num4Text: "Cindy는 피아노 치는 것을 매우 좋아했고 그녀의 아들도 그랬다.\n→ Cindy loved playing the piano, and so did her son.",
                      answer: 4),
        QuestionModel(num: 15,
                      questionText: "",
                      num1Text: "당신이 부자일지라도 당신은 진실한 친구들을 살 수는 없다.\n→ Rich as if you may be, you can’t buy sincere friends.",
                      num2Text: "그것은 너무나 아름다운 유성 폭풍이어서 우리는 밤새 그것을 보았다.\n→ It was such a beautiful meteor storm that we watched it all night.",
                      num3Text: "학위가 없는 것이 그녀의 성공을 방해했다.\n→ Her lack of a degree kept her advancing.",
                      num4Text: "그는 사형이 폐지되어야 하는지 아닌지에 대한 에세이를 써야 한다.\n→ He has to write an essay on if or not the death penalty should be abolished.",
                      answer: 2),
        QuestionModel(num: 16,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오.[16~17]",
                      reference: "Social media, magazines and shop windows bombard people daily with things to buy, and British consumers are buying more clothes and shoes than ever before. Online shopping means it is easy for customers to buy without thinking, while major brands offer such cheap clothes that they can be treated like disposable items―worn two or three times and then thrown away. In Britain, the average person spends more than £1,000 on new clothes a year, which is around four percent of their income. That might not sound like much, but that figure hides two far more worrying trends for society and for the environment. First, a lot of that consumer spending is via credit cards. British people currently owe approximately £670 per adult to credit card companies. That’s 66 percent of the average wardrobe budget. Also, not only are people spending money they don’t have, they’re using it to buy things __________________. Britain throws away 300,000 tons of clothing a year, most of which goes into landfill sites.",
                      num1Text: "they don’t need",
                      num2Text: "that are daily necessities",
                      num3Text: "that will be soon recycled",
                      num4Text: "they can hand down to others",
                      answer: 1),
        QuestionModel(num: 17,
                      questionText: "",
                      reference: "Excellence is the absolute prerequisite in fine dining because the prices charged are necessarily high. An operator may do everything possible to make the restaurant efficient, but the guests still expect careful, personal service: food prepared to order by highly skilled chefs and delivered by expert servers. Because this service is, quite literally, manual labor, only marginal improvements in productivity are possible. For example, a cook, server, or bartender can move only so much faster before she or he reaches the limits of human performance. Thus, only moderate savings are possible through improved efficiency, which makes an escalation of prices _______. (It is an axiom of economics that as prices rise, consumers become more discriminating.) Thus, the clientele of the fine-dining restaurant expects, demands, and is willing to pay for excellence.",
                      num1Text: "ludicrous",
                      num2Text: "inevitable",
                      num3Text: "preposterous",
                      num4Text: "inconceivable",
                      answer: 2),
        QuestionModel(num: 18,
                      questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "To be sure, human language stands out from the decidedly restricted vocalizations of monkeys and apes. Moreover, it exhibits a degree of sophistication that far exceeds any other form of animal communication.",
                      reference2: "(A) That said, many species, while falling far short of human language, do nevertheless exhibit impressively complex communication systems in natural settings.\n\n(B) And they can be taught far more complex systems in artificial contexts, as when raised alongside humans.\n\n(C) Even our closest primate cousins seem incapable of acquiring anything more than a rudimentary communicative system, even after intensive training over several years. The complexity that is language is surely a species-specific trait.",
                      num1Text: "(A)-(B)-(C)",
                      num2Text: "(B)-(C)-(A)",
                      num3Text: "(C)-(A)-(B)",
                      num4Text: "(C)-(B)-(A)",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "다음 글의 주제로 가장 적절한 것은?",
                      reference: "During the late twentieth century socialism was on the retreat both in the West and in large areas of the developing world. During this new phase in the evolution of market capitalism, global trading patterns became increasingly interlinked, and advances in information technology meant that deregulated financial markets could shift massive flows of capital across national boundaries within seconds. ‘Globalization’ boosted trade, encouraged productivity gains and lowered prices, but critics alleged that it exploited the low-paid, was indifferent to environmental concerns and subjected the Third World to a monopolistic form of capitalism. Many radicals within Western societies who wished to protest against this process joined voluntary bodies, charities and other non-governmental organizations, rather than the marginalized political parties of the left. The environmental movement itself grew out of the recognition that the world was interconnected, and an angry, if diffuse, international coalition of interests emerged.",
                      num1Text: "The affirmative phenomena of globalization in the developing world in the past",
                      num2Text: "The decline of socialism and the emergence of capitalism in the twentieth century",
                      num3Text: "The conflict between the global capital market and the political organizations of the left",
                      num4Text: "The exploitative characteristics of global capitalism and diverse social reactions against it",
                      answer: 4),
        QuestionModel(num: 20,
                      questionText: "다음 글에 나타난 Johnbull의 심경으로 가장 적절한 것은?",
                      reference: "In the blazing midday sun, the yellow egg-shaped rock stood out from a pile of recently unearthed gravel. Out of curiosity, sixteen-year-old miner Komba Johnbull picked it up and fingered its flat, pyramidal planes. Johnbull had never seen a diamond before, but he knew enough to understand that even a big find would be no larger than his thumbnail. Still, the rock was unusual enough to merit a second opinion. Sheepishly, he brought it over to one of the more experienced miners working the muddy gash deep in the jungle. The pit boss’s eyes widened when he saw the stone. “Put it in your pocket,” he whispered. “Keep digging.” The older miner warned that it could be dangerous if anyone thought they had found something big. So Johnbull kept shoveling gravel until nightfall, pausing occasionally to grip the heavy stone in his fist. Could it be?",
                      num1Text: "thrilled and excited",
                      num2Text: "painful and distressed",
                      num3Text: "arrogant and convinced",
                      num4Text: "detached and indifferent",
                      answer: 1),
        ]
        let exam = ExamModel(id: 202112, year: 2021, examTypeID: "국가직", subjectID: "영어", questions: questions)
        exams2021.append(exam)
    }
    func saveExam202113() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "다음 시가를 지은 왕의 재위기간에 있었던 사실은?",
                      reference: "펄펄 나는 저 꾀꼬리\n암수 서로 정답구나\n외로울사 이 내 몸은\n뉘와 더불어 돌아가랴",
                      num1Text: "진대법을 시행하였다.",
                      num2Text: "낙랑군을 축출하였다.",
                      num3Text: "졸본에서 국내성으로 천도하였다.",
                      num4Text: "율령을 반포하여 중앙집권 체제를 강화하였다.",
                      answer: 3),
        QuestionModel(num: 2,
                      questionText: "밑줄 친‘유학자’에 대한 설명으로 옳은 것은?",
                      reference: "풍기군수 주세붕은 고려시대 " + "유학자".underLined + "의 고향인 경상도 순흥면 백운동에 회헌사(晦軒祠)를 세우고, 1543년에 교육시설을 더해서 백운동 서원을 건립하였다.",
                      num1Text: "해주향약을 보급하였다.",
                      num2Text: "원 간섭기에 성리학을 국내로 소개하였다.",
                      num3Text: "〖성학십도〗를 저술하여 경연에서 강의하였다.",
                      num4Text: "일본의 동정을 담은 〖해동제국기〗를 저술하였다.",
                      answer: 2),
        QuestionModel(num: 3,
                      questionText: "밑줄 친 ‘왕’에 대한 설명으로 옳은 것은?",
                      reference: "1919년 3월 1일 탑골 공원에서 민족대표 33인이 서명한 독립 선언서가 낭독되었다. 이 공원에 있는 탑은 " + "왕".underLined + "이 세운 것으로 경천사 10층 석탑의 영향을 받았다.",
                      num1Text: "우리나라 전쟁사를 정리한 〖동국병감〗을 편찬하였다.",
                      num2Text: "우리나라 역대 문장의 정수를 모은 〖동문선〗을 편찬하였다.",
                      num3Text: "6조 직계제를 실시하여 국왕 중심의 정치체제를 구축하였다.",
                      num4Text: "한양으로 다시 천도하면서 이궁인 창덕궁을 창건하였다.",
                      answer: 3),
        QuestionModel(num: 4,
                      questionText: "(가)인물에 대한 설명으로 옳은 것은?",
                      reference: "(가)이/가 올립니다. “지방의 경우에는 관찰사와 수령, 서울의 경우에는 홍문관과 육경(六卿), 그리고 대간(臺諫)들이 모두 능력있는 사람을 천거하게 하십시오. 그 후 대궐에 모아 놓고 친히 여러 정책과 관련된 대책 시험을 치르게 한다면 인물을 많이 얻을 수 있을 것입니다. 이는역대 선왕께서 하지 않으셨던 일이요, 한나라의 현량과와 방정과의 뜻을 이은 것입니다. 덕행은 여러 사람이 천거하는 바이므로 반드시 헛되거나 그릇되는 일이 없을 것입니다.”",
                      num1Text: "기묘사화로 탄압받았다.",
                      num2Text: "조의제문을 사초에 실었다.",
                      num3Text: "문정왕후의 수렴청정을 지지하였다.",
                      num4Text: "연산군의 생모 윤씨를 폐비하는 데 동조하였다.",
                      answer: 1),
        QuestionModel(num: 5,
                      questionText: "신석기시대 유적과 유물을 바르게 연결한 것만을 모두 고르면?",
                      reference: "ᄀ. 양양 오산리 유적-덧무늬토기\nᄂ. 서울 암사동 유적-빗살무늬토기\nᄃ. 공주 석장리 유적-미송리식토기\nᄅ. 부산 동삼동 유적-아슐리안형 주먹도끼",
                      num1Text: "ㄱ,ㄴ",
                      num2Text: "ㄱ,ㄹ",
                      num3Text: "ㄴ,ㄷ",
                      num4Text: "ㄷ,ㄹ",
                      answer: 1),
        QuestionModel(num: 6,
                      questionText: "(가) 시기에 신라에서 있었던 사실은?",
                      reference: "[ 고구려의 침입으로 한성이 함락되자, 수도를 웅진으로 옮겼다. ]\n\n   ⬇︎\n\n[   (가)   ]\n\n   ⬇︎\n\n[ 성왕은 사비로 도읍을 옮겼다. ]",
                      num1Text: "대가야를 정복하였다.",
                      num2Text: "황초령순수비를 세웠다.",
                      num3Text: "거칠부가 〖국사〗를 편찬하였다.",
                      num4Text: "이차돈의 순교를 계기로 불교가 공인되었다.",
                      answer: 4),
        QuestionModel(num: 7,
                      questionText: "시기별 대외 교류에 관한 설명으로 옳지 않은 것은?",
                      num1Text: "백제: 노리사치계가 일본에 불경과 불상을 전하였다.",
                      num2Text: "통일신라: 장보고가 청해진을 설치하여 해상권을 장악하였다.",
                      num3Text: "고려: 예성강 하구의 벽란도가 국제항으로 번성하였다.",
                      num4Text: "조선: 명과의 교류에서 중강개시와 책문후시가 전개되었다.",
                      answer: 4),
        QuestionModel(num: 8,
                      questionText: "우리나라 세계유산과 세계기록유산에 대한 설명으로 옳은 것만을 모두 고르면?",
                      reference: "ᄀ. 공주 송산리 고분군에는 전축분인 6호분과 무령왕릉이 있다.\n\nᄂ. 양산 통도사는 금강계단 불사리탑이 있는 삼보 사찰이다.\n\nᄃ. 남한산성은 병자호란 때 인조가 피난했던 산성이다.\n\nᄅ. 〖승정원일기〗는 역대 왕의 훌륭한 언행을 〖실록〗에서 뽑아 만든 사서이다.",
                      num1Text: "ᄀ, ᄂ",
                      num2Text: "ᄂ, ᄃ",
                      num3Text: "ᄀ, ᄂ, ᄃ",
                      num4Text: "ᄀ, ᄃ, ᄅ",
                      answer: 3),
        QuestionModel(num: 9,
                      questionText: "다음은 발해 수도에 대한 답사 계획이다. 각 수도에 소재하는 유적에 대한 탐구 내용으로 옳은 것만을 모두 고르면?",
                      imgModel: ImageModel(imageString: "202113-9", imgWidth: 330, imgHeight: 660),
                      num1Text: "㉠,㉡",
                      num2Text: "㉠,㉣",
                      num3Text: "㉡,㉢",
                      num4Text: "㉢,㉣",
                      answer: 3),
        QuestionModel(num: 10,
                      questionText: "다음 상소문을 올린 왕대에 있었던 사실은?",
                      reference: "석교(釋敎)를 행하는 것은 수신(修身)의 근본이요, 유교를 행하는 것은 이국(理國)의 근원입니다. 수신은 내생의 자(資)요, 이국은 금일의 요무(要務)로서, 금일은 지극히 가깝고 내생은 지극히 먼 것인데도 가까움을 버리고 먼 것을 구함은 또한 잘못이 아니겠습니까.",
                      num1Text: "양경과 12목에 상평창을 설치하였다.",
                      num2Text: "균여를 귀법사 주지로 삼아 불교를 정비하였다.",
                      num3Text: "국자감에 7재를 두어 관학을 부흥하고자 하였다.",
                      num4Text: "전지(田地)와 시지(柴地)를 지급하는 경정 전시과를 실시하였다",
                      answer: 1),
        QuestionModel(num: 11,
                      questionText: "이승만 정부의 경제 정책으로 옳지 않은 것은?",
                      num1Text: "한미 원조 협정을 체결하였다.",
                      num2Text: "농지개혁에 따른 지가증권을 발행하였다.",
                      num3Text: "제분, 제당, 면방직 등 삼백 산업을 적극 지원하였다.",
                      num4Text: "제1차 경제개발 5개년 계획을 추진하였다.",
                      answer: 4),
        QuestionModel(num: 12,
                      questionText: "중일전쟁 이후 조선총독부가 시행한 민족 말살 정책이 아닌 것은?",
                      num1Text: "아침마다 궁성요배를 강요하였다.",
                      num2Text: "일본에 충성하자는 황국 신민 서사를 암송하게 하였다.",
                      num3Text: "공업 자원의 확보를 위하여 남면북양 정책을 시행하였다.",
                      num4Text: "황국 신민 의식을 강화하고자 소학교를 국민학교로 개칭하였다.",
                      answer: 3),
        QuestionModel(num: 13,
                      questionText: "밑줄 친 ‘조약’에 대한 설명으로 옳지 않은 것은?",
                      reference: "1905년 8월 4일 오후 3시, 우리가 앉아있는 곳은 새거모어 힐의 대기실. 루스벨트의 저택이다. 새거모어 힐은 루스벨트의 여름용 대통령 관저로 3층짜리 저택이다. ...(중략) ... 대통령과 마주하자 나는 말했다. “감사합니다. 각하. 저는 대한제국 황제의 친필 밀서를 품고 지난 2월에 헤이 장관을 만난 사람입니다. 그 밀서에서 우리 황제는 1882년에 맺은 " + "조약".underLined + "의 거중조정 조항에 따른 귀국의 지원을 간곡히 부탁했습니다.”",
                      num1Text: "영사재판권이 인정되었다.",
                      num2Text: "임오군란을 계기로 체결되었다.",
                      num3Text: "최혜국 대우 조항이 포함되었다.",
                      num4Text: "〖조선책략〗의 영향을 받았다.",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "고려시대 향리에 대한 설명으로 옳은 것만을 모두 고르면?",
                      reference: "ᄀ. 부호장 이하의 향리는 사심관의 감독을 받았다.\nᄂ. 상층 향리는 과거로 중앙 관직에 진출할 수 있었다.\nᄃ. 일부 향리의 자제들은 기인으로 선발되어 개경으로 보내졌다.\nᄅ. 속현의 행정 실무는 향리가 담당하였다.",
                      num1Text: "ㄱ",
                      num2Text: "ㄱ,ㄴ",
                      num3Text: "ㄴ,ㄷ,ㄹ",
                      num4Text: "ㄱ,ㄴ,ㄷ,ㄹ",
                      answer: 4),
        QuestionModel(num: 15,
                      questionText: "밑줄 친 ‘이농법’에 대한 설명으로 옳은 것만을 모두 고르면?",
                      reference: "대개 " + "이 농법을".underLined + " 귀중하게 여기는 이유는 다음과 같다. 두 땅의 힘으로 하나의 모를 서로 기르는 것이고, ...(중략) ... 옛 흙을 떠나 새 흙으로 가서 고갱이를 씻어 내어 더러운 것을 제거하는 것이다. 무릇 벼를 심는 논에는 물을 끌어들일 수 있는 하천이나 물을 댈 수 있는 저수지가 꼭 필요하다. 이러한 것이 없다면 볏논이 아니다.\n-〖임원경제지〗-",
                      reference2: "ᄀ. 세종 때 편찬된 〖농사직설〗에도 등장한다.\nᄂ. 고랑에 작물을 심도록 하였다.\nᄃ. 〖경국대전〗의 수령칠사 항목에서도 강조되었다.\nᄅ. 직파법보다 풀 뽑는 노동력을 절약할 수 있었다.",
                      num1Text: "ㄱ,ㄴ",
                      num2Text: "ㄱ,ㄹ",
                      num3Text: "ㄴ,ㄷ",
                      num4Text: "ㄷ,ㄹ",
                      answer: 2),
        QuestionModel(num: 16,
                      questionText: "밑줄 친 ‘헌법’이 시행 중인 시기에 일어난 사건은?",
                      reference: "이 " + "헌법".underLined + "은 한 사람의 집권자가 긴급조치라는 형식적인 법 절차와 권력 남용으로 양보할 수 없는 국민의 기본 인권과 존엄성을 억압하였다. 그리고 이러한 권력 남용에 형식적인 합법성을 부여하고자 ...(중략)... 입법, 사법, 행정 3권을 한 사람의 집권자에게 집중시키고 있다.",
                      num1Text: "부.마 민주 항쟁이 일어났다.",
                      num2Text: "국민교육헌장을 선포하였다.",
                      num3Text: "7.4 남북공동성명이 발표되었다.",
                      num4Text: "한일 협정 체결을 반대하는 6.3 시위가 있었다.",
                      answer: 1),
        QuestionModel(num: 17,
                      questionText: "밑줄 친 ‘회의’에서 있었던 사실은?",
                      reference: "본 " + "회의".underLined + "는 2천만 민중의 공정한 뜻에 바탕을 둔 국민적 대화합으로 최고의 권위를 가지고 국민의 완전한 통일을 공고하게 하며, 광복 대업의 근본 방침을 수립하여 우리 민족의 자유를 만회하며 독립을 완성하기를 기도하고 이에 선언하노라. ...(중략)...본 대표 등은 국민이 위탁한 사명을 받들어 국민적 대단결에 힘쓰며 독립운동이 나아갈 방향을 확립하여 통일적 기관 아래에서 대업을 완성하고자 하노라.",
                      num1Text: "대한민국 건국 강령이 상정되었다.",
                      num2Text: "박은식이 임시대통령으로 선출되었다.",
                      num3Text: "민족유일당운동 차원에서 조선혁명당이 참가하였다.",
                      num4Text: "임시정부를 대체할 새로운 조직을 만들자는 주장이 나왔다.",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "다음 법령에 따라 시행된 사업에 대한 설명으로 옳은 것은?",
                      reference: "제1조 토지의 조사 및 측량은 본령에 따른다.\n제4조 토지 소유자는 조선 총독이 정한 기간 내에 주소, 성명 또는 명칭 및 소유지의 소재, 지목, 자번호, 사표, 등급, 지적, 결수를 임시토지조사국장에게 신고해야 한다. 단 국유지는 보관 관청이 임시토지조사국장에게 통지해야 한다.",
                      num1Text: "농상공부를 주무 기관으로 하였다.",
                      num2Text: "역둔토, 궁장토를 총독부 소유로 만들었다.",
                      num3Text: "토지약탈을 위해 동양척식회사를 설립하였다.",
                      num4Text: "춘궁 퇴치, 농가 부채 근절을 목표로 내세웠다.",
                      answer: 2),
        QuestionModel(num: 19,
                      questionText: "개항기 무역에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "개항장에서 조선인 객주가 중개 활동을 하였다.",
                      num2Text: "조.청 무역장정으로 청국에서의 수입액이 일본을 앞질렀다.",
                      num3Text: "일본 상인은 면제품을 팔고, 쇠가죽.쌀.콩 등을 구입하였다.",
                      num4Text: "조.일 통상장정의 개정으로 곡물 수출이 금지되기도 하였다.",
                      answer: 2),
        QuestionModel(num: 20,
                      questionText: "밑줄 친 ‘그’에 대한 설명으로 옳은 것은?",
                      reference: "군역에 뽑힌 장정에게 군포를 거두었는데, 그 폐단이 많아서 백성들이 뼈를 깎는 원한을 가졌다. 그런데 사족들은 한평생 한가하게 놀며 신역(身役)이 없었다. ...(중략)... 그러나 유속(流俗)에 끌려 이행되지 못하였으나 갑자년 초에 그가 강력히 나서서 귀천이 동일하게 장정 한 사람마다 세납전 (歲納錢) 2민(緡)을 바치게 하니, 이를 동포전(洞布錢)이라고 하였다.\n\n-〖매천야록〗-",
                      num1Text: "만동묘 건립을 주도하였다.",
                      num2Text: "군국기무처 총재를 역임하였다.",
                      num3Text: "통리기무아문을 폐지하고 5군영을 부활하였다.",
                      num4Text: "탕평 정치를 정리한 〖만기요람〗을 편찬하였다.",
                      answer: 3)
        
        ]
        let exam = ExamModel(id: 202113, year: 2021, examTypeID: "국가직", subjectID: "한국사", questions: questions)
        exams2021.append(exam)
    }
    //지방직
    func saveExam202121() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분이 바르게 쓰이지 않은 것은?",
                      num1Text: "바쁘다더니 여긴 " + "웬일".underLined + "이야?",
                      num2Text: "결혼식이 몇 월 " + "몇 일".underLined + "이야?",
                      num3Text: "굳은살이 " + "박인".underLined + " 오빠 손을 보니 안쓰럽다.",
                      num4Text: "그는 주말이면 " + "으레".underLined + " 친구들과 야구를 한다.",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "밑줄 친 조사의 쓰임이 옳은 것은?",
                      num1Text: "언니는 아버지의 딸" + "로써" + " 부족함이 없다.",
                      num2Text: "대화" + "로서".underLined + " 서로의 갈등을 풀 수 있을까?",
                      num3Text: "드디어 오늘" + "로써".underLined + " 그 일을 끝내고야 말았다.",
                      num4Text: "시험을 치는 것이 이" + "로서".underLined + " 세번째가 됩니다.",
                      answer: 3),
        QuestionModel(num: 3,
                      questionText: "단어의 뜻풀이가 옳지 않은 것은?",
                      num1Text: "반나절: 하루 낮의 반",
                      num2Text: "달포: 한 달이 조금 넘는 기간",
                      num3Text: "그끄저께: 오늘로부터 사흘 전의 날",
                      num4Text: "해거리: 한 해를 거른 간격",
                      answer: 0),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 부분과 바꿔 쓸 수 있는 관용 표현으로 적절하지 않은 것은?",
                      num1Text: "몹시 가난한 형편에 누구를 돕겠느냐? - 가랑이가 찢어질",
                      num2Text: "그가 중간에서 연결해 주어 물건을 쉽게 팔았다.-호흡을 맞춰",
                      num3Text: "그는 상대편을 보고는 속으로 깔보며 비웃었다. -코웃음을 쳤다",
                      num4Text: "주인의 말에 넘어가 실제보다 비싸게 이 물건을 샀다. -바가지를 쓰고",
                      answer: 2),
        QuestionModel(num: 5,
                      questionText: "㉠~㉣에 대한 설명으로 옳지 않은 것은?",
                      reference: " 이때는 오월 단옷날이렷다. 일 년 중 가장 아름다운 시절이라. ㉠" + "이때 월매 딸 춘향이도 또한 시서 음률이 능통하니 천중절을 모를쏘냐.".underLined + " 추천을 하려고 향단이 앞세우고 내려올제, 난초같이 고운머리 두귀를 눌러 곱게 땋아 봉황 새긴 비녀를 단정히 매었구나. ...(중략) ... 장림 속으로 들어가니 ㉡" + "녹음방초 우거져 금잔디 좌르르 깔린 곳에 황금 같은 꾀꼬리는 쌍쌍이 날아든다.".underLined + " 버드나무 높은 곳에서 그네 타려 할 때, 좋은 비단 초록 장옷, 남색 명주 홑치마 훨훨 벗어 걸어 두고, 자주색 비단 꽃신을 썩썩 벗어 던져두고, 흰 비단 새 속옷 턱밑에 훨씬 추켜올리고, 삼 껍질 그넷줄을 섬섬옥수 넌지시 들어 두손에 갈라잡고, 흰비단버선 두 발길로 훌쩍 올라 발 구른다. ...(중략)...㉢" + "한 번 굴러 힘을 주며 두 번 굴러 힘을 주니 발밑에 작은 티끌 바람 쫓아 펄펄, 앞뒤 점점 멀어가니 머리 위의 나뭇잎은 몸을 따라 흔들흔들.".underLined + " 오고갈 제 살펴보니 녹음 속의 붉은 치맛자락 바람결에 내비치니, 높고 넓은 흰 구름 사이에 번갯불이 쏘는 듯 잠깐 사이에 앞뒤가 바뀌는구나. ...(중략)...무수히 진퇴하며 한참 노닐 적에 시냇가 반석 위에 옥비녀 떨어져 쟁쟁하고, ‘비녀, 비녀’ 하는 소리는 산호채를 들어 옥그릇을 깨뜨리는 듯. ㉣" + "그 형용은 세상 인물이 아니로다.".underLined + "\n\n -작자미상, 〖춘향전〗에서-",
                      num1Text: "㉠: 설의적 표현을 통해 춘향이도 천중절을 당연히 알 것이라는 점을 서술하고 있다.",
                      num2Text: "㉡: 비유법을 사용하고 음양이 조화를 이룬 아름다운 봄날의 풍경을 서술하고 있다.",
                      num3Text: "㉢: 음성상징어를 사용하여 춘향의 그네 타는 모습을 시각적 으로 서술하고 있다.",
                      num4Text: "㉣: 서술자의 편집자적 논평을 통해 춘향이의 내면적 아름다움을 서술하고 있다.",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "다음 대화에 대한 설명으로 적절한 것은?",
                      reference: "A: 지난번 제안서 프레젠테이션을 마친 후 “검토하고 연락드리겠습니다.”라고 답변을 받았는데 아직 별다른 연락이 없어서 고민이에요.\n\nB:어떤 연락을 기다리신다는 거예요?\n\nA:해당 사업에 관하여 제 제안서를 승낙했다는 답변이잖아요. 그런데 후속 사업 진행을 위해 지금쯤 연락이 와야 할 텐데 싶어서요.\n\nB:글쎄요. 보통 그런 상황에서는 완곡하게 거절하는 의사 표현이라 볼 수 있어요. 그리고 해당 고객이 제안서 내용은 정리가 잘되었지만, 요즘 같은 코로나 시기에는 이전과 동일한 사업적 효과가 있을지 궁금하다고 말한 것을 보면 알 수 있죠.\n\nA:네, 기억납니다. 하지만 궁금하다고 말한 것이지 사업을 수용하지 않는다는 것은 아니지 않나요? 답변을 할 때도 굉장히 표정도 좋고 박수도 쳤는데 말이죠. 목소리도 부드러웠고요.",
                      num1Text: "A와 B는 고객의 답변에 대해 제안서 승낙이라는 의미로 동일하게 이해한다.",
                      num2Text: "A는 동일한 사업적 효과가 있을지 궁금하다는 표현을 제안한 사업에 대한 부정적 평가라고 판단한다.",
                      num3Text: "B는 고객이 제안서에 의문을 제기한 내용을 근거로 고객의 답변에 대해 판단한다.",
                      num4Text: "A는 비언어적 표현을 바탕으로 하여 고객의 답변을 제안서에 대한 완곡한 거절로 해석한다.",
                      answer: 3),
        QuestionModel(num: 7,
                      questionText: "다음 글의 내용과 부합하지 않는 것은?",
                      reference: " 무슈 리와 엄마는 재혼한 부부다. 내가 그를 아버지라고 부르기 어려운 것은 거의 그런 말을 발음해 본 적이 없는 습관의 탓이 크다.\n 나는 그를 좋아할뿐더러 할아버지 같은 이로부터 느끼던 것의 몇 갑절이나 강한 보호 감정―부친다움 같은 것도 느끼고 있다.\n 그러나 나는 그의 혈족은 아니다.\n 무슈 리의 아들인 현규와도 마찬가지다. 그와 나는 그런 의미에서는 순전한 타인이다. 스물두 살의 남성이고 열여덟 살의 계집아이라는 것이 진실의 전부이다. 왜 나는 이 일을 그대로 알아서는 안 되는가?\n 나는 그를 영원히 아무에게도 주기 싫다. 그리고 나 자신을 다른 누구에게 바치고 싶지도 않다. 그리고 우리를 비끄러매는 형식이 결코 ‘오누이’라는 것이어서는 안 될 것을 알고 있다.\n 나는 또 물론 그도 나와 마찬가지로 같은 일을 생각하고 있기를 바란다. 같은 일을―같은 즐거움일 수는 없으나 같은 이 괴로움을.\n 이 괴로움과 상관이 있을 듯한 어떤 조그만 기억, 어떤 조그만 표정, 어떤 조그만 암시도 내 뇌리에서 사라지는 일은 없다. 아아, 나는 행복해질 수는 없는 걸까? 행복이란, 사람이 그것을 위하여 태어나는 그 일을 말함이 아닌가?\n 초저녁의 불투명한 검은 장막에 싸여 짙은 꽃향기가 흘러든다. 침대 위에 엎드려서 나는 마침내 느껴 울고 만다.\n\n－강신재, ｢젊은 느티나무｣에서－",
                      num1Text: "‘나’는 ‘현규’도 ‘나’와 같은 감정을 갖고 있기를 기대하고 있다.",
                      num2Text: "나’와 ‘현규’는 혈연적으로는 아무런 관계가 없는 타인이며, 법률상의 ‘오누이’일 뿐이다.",
                      num3Text: "‘나’는 ‘현규’에 대한 감정 때문에 ‘무슈 리’를 아버지로 부르는 것에 거부감을 갖고 있다.",
                      num4Text: "‘나’는 사회적 인습이나 도덕률보다는 ‘현규’에 대한 ‘나’의 감정에 더 충실해지고 싶어 한다.",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "글쓴이의 견해에 부합하는 대응으로 가장 적절한 것은?",
                      reference: " 정중하고 단호한 태도를 보이는 것과, 수동적이거나 공격적인 반응을 하는 것은 엄청난 차이가 있다. 수동적인 사람들은 마음속에 있는 자신의 생각을 표현하면 분란이 일어날까 봐 두려워한다. 그러나 자신의 의견을 말하지 않는 한 자신이 원하는 것을 얻을 수는 없다. 이와 반대로 공격적인 태도는 자신의 권리를 앞세워 생각해서 남을 희생시켜서라도 자신이 원하는 것을 얻으려는 것이다. 공격적인 사람은 사람들이 싫어하는 행동을 하곤 한다. 그러나 단호한 반응은 공격적인 반응과 다르다. 단호한 반응은 다른 사람의 권리를 침해하지 않으면서 자신의 권리를 존중하고 지키겠다는 것이다. 이것은 상대방을 배려하는 태도를 보여 준다. 상대방을 존중하면서도 얼마든지 자신의 의견을 내세울 수 있다. 단호한 주장은 명쾌하고 직접적이며 요점을 찌른다.\n 그럼 실제로 연습해 보자. 어느 흡연자가 당신의 차 안에서 담배를 피워도 되는지 묻는다. 당신은 담배 연기를 싫어하고 건강에 해롭다는 것도 잘 알고 있어 달갑지 않다. 어떻게 대응하는 것이 좋을까?",
                      num1Text: "좀 그러긴 하지만, 괜찮아요. 창문 열고 피우세요.",
                      num2Text: "안 되죠. 흡연이 얼마나 해로운데요. 좀 참아 보시겠어요.",
                      num3Text: "안 피우시면 좋겠어요. 연기가 해롭잖아요. 피우고 싶으시면 차를 세워 드릴게요.",
                      num4Text: "물어봐 줘서 고마워요. 피워도 그렇고 안 피워도 좀 그러네요. 생각해 보시고서 좋은 대로 결정하세요.",
                      answer: 3),
        QuestionModel(num: 9,
                      questionText: "(가)에 들어갈 한자성어로 적절한 것은?",
                      reference: " “집안 내력을 알고 보믄 동기간이나 진배없고, 성환이도 이자는 대학생이 됐으니께 상의도 오빠겉이 그렇게 알아놔라.”하고 장씨 아저씨는 말하는 것이었다. 그러나 상의는 처음 만났을 때도 그랬지만 두 번째도 거부감을 느꼈다. 사람한테 거부감을 느꼈기보다 제복에 거부감을 느꼈는지 모른다. 학교규칙이나 사회의 눈이 두려웠는지 모른다. 어쨌거나 그들은 청춘남녀였으니까. 호야 할매 입에서도 성환의 이름이 나오기론 이번이 처음이 아니었다.\n“ (가) , 손주 때문에 눈물로 세월을 보내더니, 이자는 성환이도 대학생이 되었으니 할매가 원풀이 한풀이를 다 했을 긴데 아프기는 와 아프는고, 옛말 하고 살아야 하는 긴데.”\n\n－박경리, ｢토지｣에서－",
                      num1Text: "오매불망(寤寐不忘)",
                      num2Text: "망운지정(望雲之情)",
                      num3Text: "염화미소(拈華微笑)",
                      num4Text: "백아절현(伯牙絶絃)",
                      answer: 1),
        QuestionModel(num: 10,
                      questionText: "(가)와 (나)에 대한 설명으로 적절하지 않은 것은?",
                      reference: "(가) 오백년 도읍지를 필마로 돌아드니산천은 의구하되 인걸은 간 데 없네.어즈버 태평연월이 꿈이런가 하노라.\n\n(나) 벌레먹은 두리기둥 빛 낡은 단청(丹靑) 풍경 소리 날러간 추녀 끝에는 산새도 비둘기도 둥주리를 마구쳤다. 큰 나라 섬기다 거미줄 친 옥좌(玉座) 위엔 여의주(如意珠) 희롱하는 쌍룡(雙龍) 대신에 두 마리 봉황(鳳凰)새를 틀어올렸다. 어느 땐들 봉황이 울었으랴만 푸르른 하늘 밑 추석을 밟고 가는 나의 그림자. 패옥(佩玉) 소리도 없었다. 품석(品石) 옆에서 정일품(正一品) 종구품(從九品) 어느 줄에도 나의 몸둘 곳은 바이 없었다. 눈물이 속된 줄을 모를 양이면 봉황새야 구천(九泉)에 호곡(呼哭)하리라.",
                      num1Text: "(가)는 ‘산천’과 ‘인걸’을 대비함으로써 인생의 무상함을 드러내고 있다.",
                      num2Text: "(나)는 ‘쌍룡’과 ‘봉황’을 대비함으로써 사대주의적 역사에 대한 비판적 시각을 드러내고 있다.",
                      num3Text: "(가)와 (나) 모두 선경후정의 기법을 사용하고 있다.",
                      num4Text: "(가)와 (나) 모두 정해진 율격과 음보에 맞춰 시상을 전개하고 있다.",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "다음 글의 내용과 부합하는 것은?",
                      reference: " 미국의 어머니들은 자녀와 함께 놀이를 할 때 특정 사물에 초점을 맞추고 그 사물의 속성을 아이들에게 가르친다. 사물의 속성 자체에 관심을 기울이도록 훈련받은 아이들은 스스로 독립적인 행동을 하도록 교육받는다. 미국에서는 아이들에게 의사소통을 가르칠 때 자신의 생각을 분명하게 표현하고 말하는 사람의 입장에서 대화에 임해야 하며, 대화 과정에서 오해가 발생하면 그것은 말하는 사람의 잘못이라고 강조한다.\n 반면에 일본의 어머니들은 대상의 ‘감정’에 특별히 신경을 써서 가르친다. 특히 자녀가 말을 안 들을 때에 그러하다. 예를 들어 “네가 밥을 안 먹으면, 고생한 농부 아저씨가 얼마나 슬프겠니?”, “인형을 그렇게 던져 버리다니, 저 인형이 울잖아. 담장도 아파하잖아.” 같은 말들로 꾸중하는 모습을 자주 볼 수 있다. 다른 사람과의 관계에 초점을 맞춘 훈련을 받은 아이들은 자신의 생각을 드러내기보다는 행동에 영향을 받는 다른 사람들의 감정을 미리 예측하도록 교육받는다. 곧 일본에서는 아이들에게 듣는 사람의 입장에서 말할 것을 강조한다.",
                      num1Text: "미국의 어머니는 듣는 사람의 입장, 일본의 어머니는 말하는 사람의 입장을 강조한다.",
                      num2Text: "일본의 어머니는 사물의 속성을 아는 것이 관계를 아는 것보다 더 중요하다고 생각한다.",
                      num3Text: "미국의 어머니는 어떤 일을 있는 그대로 보지 말고 이면에 있는 감정을 읽어야 한다고 생각한다.",
                      num4Text: "미국의 어머니는 자녀가 독립적인 행동을 하도록 교육하며, 일본의 어머니는 자녀가 타인의 감정을 예측하도록 교육한다.",
                      answer: 4),
        QuestionModel(num: 12,
                      questionText: "다음 글의 결론으로 가장 적절한 것은?",
                      reference: " 인공지능(AI)은 비즈니스 패러다임을 획기적으로 바꾸고 있다. 인공지능은 생물학 분야에도 광범위하게 영향을 미칠 것이며, 애완동물이 인공지능(AI)으로 대체될 수도 있을 것이다. 인공지능(AI)은 스스로 수학도 풀고 글도 쓰고 바둑을 두며 사람을 이길 수도 있다. 어느 영화에서처럼 실제로 인간관계를 대신할 수도 있다. 인공지능(AI)은 배우면서 성장할 수도 있다. 인공지능(AI)이 사람보다 똑똑해질 수 있을지도 모른다.\n 인공지능(AI)이 사람보다 똑똑해질 수 있는지는 차치하고, 인공지능(AI)이 사람을 게으르게 만들 수도 있지 않을까? 이 게으름은 우리의 건강과 행복, 그리고 일상생활의 패턴을 바꿔 놓을 수도 있다.\n 인공지능(AI)이 앱을 통해 좀 더 편리한 삶을 제공하여 사람의 뇌를 어떻게 바꾸는지를 일상에서 보여 주는 대표적 사례가 바로 GPS다. 불과 몇 년 전만 해도 지도를 보고 스스로 거리를 가늠하고 도착 시간을 계산했던 운전자들은 이 내비게이션의 등장으로 어디에서 어떻게 가라는 기계 속 음성에 전적으로 의존하기 시작했다. 예전의 방식으로도 충분히 잘 찾아가던 길에서조차 습관적으로 내비게이션을 켠다. 이것이 없으면 자주 다니던 길도 제대로 찾지 못하고 멀쩡한 어른도 길을 잃는다.\n 이와 같이 기계에 의존해서 인간이 살아가는 사례는 오늘날 우리의 두뇌가 게을러진 것을 보여 주는 여러 사례 가운데 하나일 뿐이다. 삶을 더 편하게 해 준다며 지름길을 제시하는 도구들이 도리어 우리의 기억력과 창조력을 퇴보시키고 있다. 인간을 태만하고 나태하게 만들어 뇌의 가장 뛰어난 영역인 상상력을 활용하지 않도록 만드는 것이다.",
                      num1Text: "인간의 인공지능(AI)에 대한 독립성은 지속적으로 증가하게 될 것이다.",
                      num2Text: "인공지능(AI)으로 인해 인간의 두뇌가 게을러지는 부작용이 발생하게 될 것이다.",
                      num3Text: "인공지능(AI)은 인간을 능가하는 사고력을 가질 것이다.",
                      num4Text: "인공지능(AI)은 궁극적으로 상상력을 가지게 될 것이다.",
                      answer: 2),
        QuestionModel(num: 13,
                      questionText: "다음 글에 대한 이해로 적절한 것은?",
                      reference: " 국제기구인 유엔은 영어, 중국어, 러시아어, 프랑스어, 스페인어, 아랍어 등이 공용어로 사용되나 그곳에 근무하는 모든 외교관들이 이 공용어들을 전부 다 잘해야 하는 것은 아니다. 유럽연합에서의 공용어 개념도 유엔에서의 경우와 마찬가지로 여러 공용어 중 하나만 알아도 공식 업무상 불편이 없게끔 한다는 것이지 모든 유럽연합인들이 열 개가 넘는 공용어를 전부 다 배워야 하는 것은 아니다.\n 마찬가지 논리로 우리가 만일 한국어와 영어를 공용어로 지정한다면 이는 한국에서는 한국어와 영어 중 어느 하나를 알기만 하면 공식 업무상 불편이 없게끔 국가에서 보장한다는 뜻이지 모든 한국인들이 영어를 할 줄 알아야 된다는 뜻은 아니다. 따라서 우리가 영어를 한국어와 함께 공용어로 지정하기만 하면 모든 한국인이 영어를 잘할 수 있게 되리라는 믿음은 공용어의 개념을 제대로 이해하지 못한 데서 오는 망상에 불과하다.",
                      num1Text: "유엔에서 근무하는 외교관들은 유엔의 공용어를 다 구사하지 않으면 안 된다.",
                      num2Text: "유럽연합은 복수의 공용어를 지정하여 공무상 편의를 도모하였다.",
                      num3Text: "한국에서 영어를 공용어로 지정하면 한국인들은 영어를 다 잘할 수 있을 것이다.",
                      num4Text: "한국에서 머지않아 영어가 공용어로 지정될 것이다.",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "다음 글의 내용과 부합하지 않는 것은?",
                      reference: " 인터넷이 있는 곳이면 어디나 악플이 있기 마련이지만, 한국은 정도가 심하다. 악플러들 가운데는 피해의식과 열등감에 시달리는 이들이 많다고 한다. 그들에게 악플의 즐거움은 무엇인가. 자신이 올린 글 한 줄에 다른 사람들이 동요하는 모습을 보면서 자기 효능감(self-efficacy)을 맛볼 수 있다. 아무에게도 영향력을 행사하지 못하고 자신의 삶과 환경을 통제하지도 못하면서 무력감에 시달리는 사람일수록 공격적인 발설로 자기 효능감을 느끼려 한다.\n 그런데 자기 효능감은 상대방의 반응에 좌우된다. 마구 욕을 퍼부었는데 상대방이 별로 개의치 않는다면, 계속할 마음이 사라질 것이다. 무시당했다는 생각에 오히려 자괴감에 빠질 수도 있다. 개인주의가 안착된 사회에서는 자신을 향한 비판에 대해 ‘그건 너의 생각’이라면서 넘겨 버리는 사람들이 많다. 말도 안 되는 욕설이나 험담이 날아오면 제정신이 아닌 사람의 소행으로 웃어넘기거나 법적인 조치를 취할 것이다.\n 개인주의는 여러 속성을 지니고 있지만, 자신의 존재 가치를 스스로 매긴다는 긍정적 측면이 있다. 한국에는 그런 의미에서의 개인주의가 뿌리내리지 못했다. 남에 대해 신경을 너무 곤두세운다. 그것은 두 가지 차원으로 나뉘는데, 한편으로 타인에게 필요 이상의 관심을 보이면서 참견하고 타인의 영역을 침범한다. 다른 한편으로 자기에 대한 타인의 평가와 반응에 너무 예민하다. 이 두 가지 특성이 인터넷 공간에서 맞물려 악플을 양산한다. 우선 다른 사람들에게 너무 쉽게 험담을 늘어놓고 당사자에게 악담을 던진다. 그렇게 약을 올리면 상대방이 발끈하거나 움츠러든다. 이따금 일파만파로 사회가 요동을 치기도 한다. 악플러 입장에서는 재미가 쏠쏠하다. 예상했던 피드백을 즉각적으로 받으면서 자기 효능감을 맛볼 수 있기 때문이다.",
                      num1Text: "악플러는 자신의 말에 타인이 동요하는 것을 보면서 자기 효능감을 느낀다.",
                      num2Text: "개인주의자는 악플에 무반응함으로써 악플러를 자괴감에 빠지게 할 수 있다.",
                      num3Text: "자신의 삶을 잘 통제하는 악플러일수록 타인을 더욱 엄격한 잣대로 비판한다.",
                      num4Text: "한국에서 악플이 양산되는 것은 한국인들이 타인에 대해 신경을 많이 쓰는 것과 관계가 있다.",
                      answer: 3),
        QuestionModel(num: 15,
                      questionText: "다음 글의 밑줄 친 부분이 지시하는 대상이 다른 것은?",
                      reference: " 수박을 먹는 기쁨은 우선 식칼을 들고 이 검푸른 ㉠" + "구형".underLined + "의 과일을 두 쪽으로 가르는 데 있다. 잘 익은 수박은 터질 듯이 팽팽해서, 식칼을 반쯤만 밀어 넣어도 나머지는 저절로 열린다. 수박은 천지개벽하듯이 갈라진다. 수박이 두 쪽으로 벌어지는 순간, ‘앗!’ 소리를 지를 여유도 없이 초록은 ㉡" + "빨강".underLined + "으로 바뀐다. 한 번의 칼질로 이처럼 선명하게도 세계를 전환시키는 사물은 이 세상에 오직 수박뿐이다. 초록의 껍질 속에서, ㉢" + "새까만 씨앗들이 별처럼 박힌 선홍색의 바다".underLined + "가 펼쳐지고, 이 세상에 처음 퍼져나가는 비린 향기가 마루에 가득 찬다. 지금까지 존재하지 않던, ㉣" + "한바탕의 완연한 아름다움의 세계".underLined + "가 칼 지나간 자리에서 홀연 나타나고, 나타나서 먹히기를 기다리고 있다. 돈과 밥이 나오지 않았다 하더라도, 이것은 필시 흥부의 박이다.\n\n－김훈, ｢수박｣에서－",
                      num1Text: "㉠",
                      num2Text: "㉡",
                      num3Text: "㉢",
                      num4Text: "㉣",
                      answer: 1),
        QuestionModel(num: 16,
                      questionText: "(가)～(라)에 들어갈 말로 가장 적절한 것은?",
                      reference: " 정철, 윤선도, 황진이, 이황, 이조년 그리고 무명씨. 우리말로 시조나 가사를 썼던 이들이다. 황진이는 말할 것도 없고 무명씨도 대부분 양반이 아니었겠지만 정철, 윤선도, 이황은 양반 중에 양반이었다. [ (가) ] 그들이 우리말로 작품을 썼던 걸 보면 양반들도 한글 쓰는 것을 즐겨 했다는 것을 부정할 수는 없다. [ (나) ] 허균이나 김만중은 한글로 소설까지 쓰지 않았던가. [ (다) ]이들이 특별한 취향을 가진 소수의 양반이었다면 이야기는 달라진다. 우리말로 된 문학 작품을 만들겠다는 생각을 가진 특별한 양반들을 제외하고 대다수 양반들은 한문을 썼기 때문에 한글을 모를 수도 있었기 때문이다. 실학자 박지원이 당시 양반 사회를 풍자한 작품 ｢호질｣은 한문으로 쓰여 있다. [ (라) ] 한 가지 분명한 것은 양반 대부분이 한글을 이해하지 못하는 상황이었다면 정철도 이황도 윤선도도 한글로 작품을 쓰지는 않았을 것이란 사실이다.",
                      num1Text: "그런데 - 게다가 - 그렇지만 - 그러나",
                      num2Text: "그런데 - 그리고 - 그래서 - 또는",
                      num3Text: "그리고 - 그러나 - 하지만 - 즉",
                      num4Text: "그래서 - 더구나 - 따라서 - 하지만",
                      answer: 1),
        QuestionModel(num: 17,
                      questionText: "(가)～(라)의 고쳐 쓰기 방안으로 적절하지 않은 것은?",
                      reference: "(가)현재 우리 구청 조직도에는 기획실, 홍보실, 감사실, 행정국, 복지국, 안전국, 보건소가 있었다.\n\n(나)오늘은 우리 시청이 지양하는 ‘누구나 행복한 ○○시’를 실현하기 위한 추진 방안을 논의합니다.\n\n(다)지난달 수해로 인한 준비 기간이 짧았기 때문에 지역 축제는 예년보다 규모가 줄어들었다.\n\n(라)공과금을 기한 내에 지정 금융 기관에 납부하지 않으면 연체료를 내야 한다.",
                      num1Text: "(가):‘있었다’는 문맥상 시제 표현이 적절하지 않으므로 ‘있다’로 고쳐 쓴다.",
                      num2Text: "(나):‘지양’은 어떤 목표로 뜻이 쏠리어 향한다는 의미인 ‘지향’으로 고쳐 쓴다.",
                      num3Text: "(다):‘지난달 수해로 인한’은 ‘준비 기간’을 수식하는 절이 아니므로 ‘지난달 수해로 인하여’로 고쳐 쓴다.",
                      num4Text: "(라):‘납부’는 맥락상 금융 기관이 돈이나 물품 따위를 받아 거두어들인다는 ‘수납’으로 고쳐 쓴다.",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "다음 글을 잘못 이해한 것은?",
                      reference: "  서연:여보게, 동연이.\n  동연:왜?\n  서연:자네가 본뜨려는 부처님 형상은 누가 언제 그렸는지 몰라도 흔히 있는 것을 베껴 놓은 걸세. 그런데 자네는 그 형상을 또다시 베껴 만들 작정이군. 자넨 의심도 없는가? 심사숙고해 보게. 그런 형상이 진짜 부처님은 아닐세.\n동연:나에겐 전혀 의심이 없네.\n  서연:의심이 없다니……?\n  동연:무엇 때문에 의심해서 아까운 시간을 낭비해야 하는가?\n  서연:음…….\n  동연:공부를 하게, 괜히 의심 말고! (허공에 걸려 있는 탱화를 가리키며) 자넨 얼마나 형상 공부를 했는가? 이 십일면관세음보살의 머리 위에는 열한 개의 얼굴들이 있는데, 그 얼굴 하나하나를 살펴나 봤었는가? 귀고리, 목걸이, 손에 든 보병과 기현화란 꽃의 형태를 꼼꼼히 연구했었는가? 자네처럼 게으른 자들은 공부는 안 하고, 아무 의미 없다 의심만 하지!\n  서연:자넨 정말 열심히 공부했네. 그렇다면 그 형태 속에 부처님 마음은 어디 있는지 가르쳐 주게.\n\n－이강백, ｢느낌, 극락 같은｣에서－",
                      num1Text: "불상 제작에 대한 동연과 서연의 입장은 다르다.",
                      num2Text: "서연은 전해지는 부처님 형상을 의심하는 인물이다.",
                      num3Text: "동연은 부처님 형상을 독창적으로 제작하는 인물이다.",
                      num4Text: "동연과 서연의 대화는 예술에 있어서 형식과 내용의 논쟁을 연상시킨다.",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "글의 통일성을 고려할 때 (가)에 들어갈 말로 가장 적절한 것은?",
                      reference: " 혼정신성(昏定晨省)이란 저녁에는 부모님의 잠자리를 봐 드리고 아침에는 문안을 드린다는 뜻으로 자식이 아침저녁으로 부모의 안부를 물어 살핌을 뜻하는 말로 ‘예기(禮記)’의 ‘곡례편(曲禮篇)’에 나오는 말이다. 아랫목 요에 손을 넣어 방 안 온도를 살피면서 부모님께 문안을 드리던 우리의 옛 전통은 온돌을 통한 난방 방식과 관련 깊다. 온돌을 통한 난방 방식은 방바닥에 깔려 있는 돌이 열기로 인해 뜨거워지고, 뜨거워진 돌의 열기로 방바닥이 뜨거워지면 방 전체에 복사열이 전달되는 방법이다. 방바닥 쪽의 차가운 공기는 온돌에 의해 따뜻하게 데워지므로 위로 올라가고, 위로 올라간 공기가 다시 식으면 아래로 내려와 다시 데워져 위로 올라가는 대류 현상으로 인해 결국 방 전체가 따뜻해진다. 벽난로를 통한 서양식의 난방 방식은 복사열을 이용하여 상체와 위쪽 공기를 데우는 방식인데, 대류 현상으로 바닥 바로 위 공기까지는 따뜻해지지 않는다. 그 이유는 [ (가) ].",
                      num1Text: "벽난로에 의한 난방은 방바닥의 따뜻한 공기가 위로 올라가 식으면 복사열로 위쪽의 공기만을 따뜻하게 하기 때문이다",
                      num2Text: "벽난로에 의한 난방이 복사열에 의한 난방에서 대류 현상으로 인한 난방이라는 순서로 이루어졌기 때문이다",
                      num3Text: "대류 현상을 통한 난방 방식은 상체와 위쪽의 공기만 따뜻하게 하기 때문이다",
                      num4Text: "상체와 위쪽의 따뜻한 공기는 차가운 바닥으로 내려오지 않기 때문이다",
                      answer: 4),
        QuestionModel(num: 20,
                      questionText: "다음 글에서 추론할 수 있는 것은?",
                      reference: "포도주는 유럽 문명을 대표하는 술이자 동시에 음료수다. 우리는 대개 포도주를 취하기 위해 마시는 술로만 생각하기 쉬우나 유럽에서는 물 대신 마시는 ‘음료수’로서의 역할이 크다. 유럽의 많은 지역에서는 물이 워낙 안 좋아서 맨 물을 그냥 마시면 위험하기 때문에 제조 과정에서 안전성이 보장된 포도주나 맥주를 마시는 것이다. 이런 용도로 일상적으로 마시는 식사용 포도주로는 당연히 고급 포도주와는 다른 저렴한 포도주가 쓰이며, 술이 약한 사람들은 여기에 물을 섞어서 마시기도 한다.\n 소비의 확대와 함께, 포도주의 생산을 다른 지역으로 확산시키려는 노력도 계속되어 왔다. 포도주 생산의 확산에서 가장 큰 문제는 포도 재배가 추운 북쪽 지역으로 확대되기 힘들다는 점이다. 자연 상태에서는 포도가 자라는 북방 한계가 이탈리아 정도에서 멈춰야 했지만, 중세 유럽에서 수도원마다 온갖 노력을 기울인 결과 포도 재배가 상당히 북쪽까지 올라갔다. 대체로 대서양의 루아르강 하구로부터 크림반도와 조지아를 잇는 선이 상업적으로 포도를 재배할 수 있는 북방한계선이다.\n 적정한 기온은 포도주 생산 가능 여부뿐 아니라 생산된 포도주의 질을 결정하는 중요한 요인이다. 너무 추운 지역이나 너무 더운 지역에서는 포도주의 품질이 떨어질 수밖에 없다. 추운 지역에서는 포도에 당분이 너무 적어서 그것으로 포도주를 담그면 신맛이 강하게 된다. 반면 너무 더운 지역에서는 섬세한 맛이 부족해서 ‘흐물거리는’ 포도주가 생산된다(그 대신 이를 잘 활용하면 포르토나 셰리처럼 도수를 높인 고급 포도주를 만들 수 있다). 그러므로 고급 포도주 주요 생산지는 보르도나 부르고뉴처럼 너무 덥지도 않고 너무 춥지도 않은 곳이다. 다만 달콤한 백포도주의 경우는 샤토 디켐(Château d'Yquem)처럼 뜨거운 여름 날씨가 지속하는 곳에서 명품이 만들어진다.\n 포도주의 수요는 전 유럽적인 데 비해 생산은 이처럼 지리적으로 제한됐기 때문에 포도주는 일찍부터 원거리 무역 품목이 됐고, 언제나 고가품 취급을 받았다. 그런데 한 가지 기억해야 할 점은 이렇게 수출되는 고급 포도주는 오래된 포도주가 아니라 바로 그해에 만든 술이라는 점이다. 우리는 포도주는 오래될수록 좋아진다고 믿는 경향이 있지만, 대부분의 백포도주 혹은 중급 이하 적포도주는 시간이 지날수록 오히려 품질이 떨어진다. 시간이 흐를수록 품질이 개선되는 것은 일부 고급 적포도주에만 한정된 이야기이며, 그나마 포도주를 병에 담아 코르크 마개를 끼워 보관한 이후의 일이다.",
                      num1Text: "고급 포도주는 모두 너무 덥지도 춥지도 않은 곳에서 재배된 포도로 만들어졌다.",
                      num2Text: "루아르강 하구로부터 크림반도와 조지아를 잇는 선은 이탈리아보다 남쪽에 있을 것이다.",
                      num3Text: "유럽에서 일상적으로 마시는 식사용 포도주는 저렴한 포도주거나 고급 포도주에 물을 섞은 것이다.",
                      num4Text: "병에 담겨 코르크 마개를 끼운 고급 백포도주는 보관 기간에 비례하여 품질이 개선되지는 않을 것이다.",
                      answer: 4),


        
        ]
        let exam = ExamModel(id: 202121, year: 2021, examTypeID: "지방직", subjectID: "국어", questions: questions)
        exams2021.append(exam)
    }
    func saveExam202122() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것은?",
                      reference: "For many compulsive buyers, the act of purchasing, rather than what they buy, is what leads to " + "gratification.".underLined,
                      num1Text: "liveliness",
                      num2Text: "confidence",
                      num3Text: "tranquility",
                      num4Text: "satisfaction",
                      answer: 4),
        QuestionModel(num: 2,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오. [2~4]",
                      reference: "Globalization leads more countries to open their markets, allowing them to trade goods and services freely at a lower cost with greater ___________.",
                      num1Text: "extinction",
                      num2Text: "depression",
                      num3Text: "efficiency",
                      num4Text: "caution",
                      answer: 3),
        QuestionModel(num: 3,
                      questionText: "",
                      reference: "We’re familiar with the costs of burnout: Energy, motivation, productivity, engagement, and commitment can all take a hit, at work and at home. And many of the ___________ are fairly intuitive: Regularly unplug. Reduce unnecessary meetings. Exercise. Schedule small breaks during the day. Take vacations even if you think you can’t afford to be away from work, because you can’t afford not to be away now and then.",
                      num1Text: "fixes",
                      num2Text: "damages",
                      num3Text: "prizes",
                      num4Text: "complications",
                      answer: 1),
        QuestionModel(num: 4,
                      questionText: "",
                      reference: "The government is seeking ways to soothe salaried workers over their increased tax burdens arising from a new tax settlement system. During his meeting with the presidential aides last Monday, the President _____________ those present to open up more communication channels with the public.",
                      num1Text: "fell on",
                      num2Text: "called for",
                      num3Text: "picked up",
                      num4Text: "turned down",
                      answer: 2),
        QuestionModel(num: 5,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것은?",
                      reference: "In studying Chinese calligraphy, one must learn something of the origins of Chinese language and of how they were originally written. However, except for those brought up in the artistic traditions of the country, its aesthetic significance seems to be very difficult to " + "apprehend.".underLined,
                      num1Text: "encompass",
                      num2Text: "intrude",
                      num3Text: "inspect",
                      num4Text: "grasp",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "우리말을 영어로 잘못 옮긴 것을 고르시오. [6~7]",
                      num1Text: "그의 소설들은 읽기가 어렵다.\n→His novels are hard to read.",
                      num2Text: "학생들을 설득하려고 해 봐야 소용없다.\n→It is no use trying to persuade the students.",
                      num3Text: "나의 집은 5년마다 페인트칠된다.\n→My house is painted every five years.",
                      num4Text: "내가 출근할 때 한 가족이 위층에 이사 오는 것을 보았다.\n→As I went out for work, I saw a family moved in upstairs.",
                      answer: 4),
        QuestionModel(num: 7,
                      questionText: "",
                      num1Text: "경찰 당국은 자신의 이웃을 공격했기 때문에 그 여성을 체포하도록 했다.\n→The police authorities had the woman arrested for attacking her neighbor.",
                      num2Text: "네가 내는 소음 때문에 내 집중력을 잃게 하지 말아라.\n→Don’t let me distracted by the noise you make.",
                      num3Text: "가능한 한 빨리 제가 결과를 알도록 해 주세요.\n→Please let me know the result as soon as possible.",
                      num4Text: "그는 학생들에게 모르는 사람들에게 전화를 걸어 성금을 기부할 것을 부탁하도록 시켰다.\n→He had the students phone strangers and ask them to donate money.",
                      answer: 2),
        QuestionModel(num: 8,
                      questionText: "어법상 옳은 것은?",
                      num1Text: "My sweet-natured daughter suddenly became unpredictably.",
                      num2Text: "She attempted a new method, and needless to say had different results.",
                      num3Text: "Upon arrived, he took full advantage of the new environment.",
                      num4Text: "He felt enough comfortable to tell me about something he wanted to do.",
                      answer: 2),
        QuestionModel(num: 9,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "The definition of ‘turn’ casts the digital turn as an analytical strategy which enables us to focus on the role of digitalization within social reality. As an analytical perspective, the digital turn makes it possible to analyze and discuss the societal meaning of digitalization. The term ‘digital turn’ thus signifies an analytical approach which centers on the role of digitalization within a society. If the linguistic turn is defined by the epistemological assumption that reality is constructed through language, the digital turn is based on the assumption that social reality is increasingly defined by digitalization. Social media symbolize the digitalization of social relations. Individuals increasingly engage in identity management on social networking sites(SNS). SNS are polydirectional, meaning that users can connect to each other and share information.\n\n* epistemological: 인식론의",
                      num1Text: "Remaking Identities on SNS",
                      num2Text: "Linguistic Turn Versus Digital Turn",
                      num3Text: "How to Share Information in the Digital Age",
                      num4Text: "Digitalization Within the Context of Social Reality",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "Growing concern about global climate change has motivated activists to organize not only campaigns against fossil fuel extraction consumption, but also campaigns to support renewable energy.",
                      reference2: "(A)This solar cooperative produces enough energy to power 1,400 homes, making it the first large-scale solar farm cooperative in the country and, in the words of its members, a visible reminder that solar power represents “a new era of sustainable and ‘democratic’ energy supply that enables ordinary people to produce clean power, not only on their rooftops, but also at utility scale.”\n\n(B)Similarly, renewable energy enthusiasts from the United States have founded the Clean Energy Collective, a company that has pioneered “the model of delivering clean power-generation through medium-scale facilities that are collectively owned by participating utility customers.”\n\n(C)Environmental activists frustrated with the UK government’s inability to rapidly accelerate the growth of renewable energy industries have formed the Westmill Wind Farm Co-operative, a community-owned organization with more than 2,000 members who own an onshore wind farm estimated to produce as much electricity in a year as that used by 2,500 homes. The Westmill Wind Farm Co-operative has inspired local citizens to form the Westmill Solar Co-operative.",
                      num1Text: "(C)－(A)－(B)",
                      num2Text: "(A)－(C)－(B)",
                      num3Text: "(B)－(C)－(A)",
                      num4Text: "(C)－(B)－(A)",
                      answer: 1),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "A:Did you have a nice weekend?\nB:Yes, it was pretty good. We went to the movies.\nA:Oh! What did you see?\nB:Interstellar. It was really good.\nA:Really? ________________________\nB:The special effects. They were fantastic. I wouldn’t mind seeing it again.",
                      num1Text: "What did you like the most about it?",
                      num2Text: "What’s your favorite movie genre?",
                      num3Text: "Was the film promoted internationally?",
                      num4Text: "Was the movie very costly?",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "두 사람의 대화 중 가장 어색한 것은?",
                      num1Text: "A:I’m so nervous about this speech that I must give today.\nB:The most important thing is to stay cool.",
                      num2Text: "A:You know what? Minsu and Yujin are tying the knot!\nB:Good for them! When are they getting married?",
                      num3Text: "A:A two-month vacation just passed like one week. A new semester is around the corner.\nB:That’s the word. Vacation has dragged on for weeks.",
                      num4Text: "A:How do you say ‘water’ in French?\nB:It is right on the tip of my tongue, but I can’t remember it.",
                      answer: 3),
        QuestionModel(num: 13,
                      questionText: "다음 글의 내용과 일치하지 않는 것은?",
                      reference: "Women are experts at gossiping, and they always talk about trivial things, or at least that’s what men have always thought. However, some new research suggests that when women talk to women, their conversations are far from frivolous, and cover many more topics (up to 40 subjects) than when men talk to other men. Women’s conversations range from health to their houses, from politics to fashion, from movies to family, from education to relationship problems, but sports are notably absent. Men tend to have a more limited range of subjects, the most popular being work, sports, jokes, cars, and women. According to Professor Petra Boynton, a psychologist who interviewed over 1,000 women, women also tend to move quickly from one subject to another in conversation, while men usually stick to one subject for longer periods of time. At work, this difference can be an advantage for men, as they can put other matters aside and concentrate fully on the topic being discussed. On the other hand, it also means that they sometimes find it hard to concentrate when several things have to be discussed at the same time in a meeting.",
                      num1Text: "남성들은 여성들의 대화 주제가 항상 사소한 것들이라고 생각해 왔다.",
                      num2Text: "여성들의 대화 주제는 건강에서 스포츠에 이르기까지 매우 다양하다.",
                      num3Text: "여성들은 대화하는 중에 주제의 변환을 빨리한다.",
                      num4Text: "남성들은 회의 중 여러 주제가 논의될 때 집중하기 어렵다.",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "다음 글의 흐름상 적절하지 않은 문장은?",
                      reference: "There was no divide between science, philosophy, and magic in the 15th century. All three came under the general heading of ‘natural philosophy’. ①" + "Central to the development of natural philosophy was the recovery of classical authors, most importantly the work of Aristotle.".underLined + " ②" + "Humanists quickly realized the power of the printing press for spreading their knowledge.".underLined + " ③" + "At the beginning of the 15th century Aristotle remained the basis for all scholastic speculation on philosophy and science.".underLined + " ④" + "Kept alive in the Arabic translations and commentaries of Averroes and Avicenna, Aristotle provided a systematic perspective on mankind’s relationship with the natural world.".underLined + " Surviving texts like his Physics, Metaphysics, and Meteorology provided scholars with the logical tools to understand the forces that created the natural world.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 2),
        QuestionModel(num: 15,
                      questionText: "어법상 옳지 않은 것은?",
                      num1Text: "Fire following an earthquake is of special interest to the insurance industry.",
                      num2Text: "Word processors were considered to be the ultimate tool for a typist in the past.",
                      num3Text: "Elements of income in a cash forecast will be vary according to the company’s circumstances.",
                      num4Text: "The world’s first digital camera was created by Steve Sasson at Eastman Kodak in 1975.",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오. [16~17]",
                      reference: "The slowing of China’s economy from historically high rates of growth has long been expected to ___________ growth elsewhere. “The China that had been growing at 10 percent for 30 years was a powerful source of fuel for much of what drove the global economy forward”, said Stephen Roach at Yale. The growth rate has slowed to an official figure of around 7 percent. “That’s a concrete deceleration”, Mr. Roach added.",
                      num1Text: "speed up",
                      num2Text: "weigh on",
                      num3Text: "lead to",
                      num4Text: "result in",
                      answer: 2),
        QuestionModel(num: 17,
                      questionText: "",
                      reference: "As more and more leaders work remotely or with teams scattered around the nation or the globe, as well as with consultants and freelancers, you’ll have to give them more ___________. The more trust you bestow, the more others trust you. I am convinced that there is a direct correlation between job satisfaction and how empowered people are to fully execute their job without someone shadowing them every step of the way. Giving away responsibility to those you trust can not only make your organization run more smoothly but also free up more of your time so you can focus on larger issues.",
                      num1Text: "work",
                      num2Text: "rewards",
                      num3Text: "restrictions",
                      num4Text: "autonomy",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "다음 글의 요지로 가장 적절한 것은?",
                      reference: "“In Judaism, we’re largely defined by our actions,” says Lisa Grushcow, the senior rabbi at Temple Emanu-El-Beth Sholom in Montreal. “You can’t really be an armchair do-gooder.” This concept relates to the Jewish notion of tikkun olam, which translates as “to repair the world.” Our job as human beings, she says, “is to mend what’s been broken. It’s incumbent on us to not only take care of ourselves and each other but also to build a better world around us.” This philosophy conceptualizes goodness as something based in service. Instead of asking “Am I a good person?” you may want to ask “What good do I do in the world?” Grushcow’s temple puts these beliefs into action inside and outside their community. For instance,  they sponsored two refugee families from Vietnam to come to Canada in the 1970s.",
                      num1Text: "We should work to heal the world.",
                      num2Text: "Community should function as a shelter.",
                      num3Text: "We should conceptualize goodness as beliefs.",
                      num4Text: "Temples should contribute to the community.",
                      answer: 1),
        QuestionModel(num: 19,
                      questionText: "(A)와 (B)에 들어갈 말로 가장 적절한 것은?",
                      reference: "Ancient philosophers and spiritual teachers understood the need to balance the positive with the negative, optimism with pessimism, a striving for success and security with an openness to failure and uncertainty. The Stoics recommended “the premeditation of evils,” or deliberately visualizing the worst-case scenario. This tends to reduce anxiety about the future: when you soberly picture how badly things could go in reality, you usually conclude that you could cope. [ (A) ], they noted, imagining that you might lose the relationships and possessions you currently enjoy increases your gratitude for having them now. Positive thinking, [ (B) ], always leans into the future, ignoring present pleasures.",
                      num1Text: "Nevertheless - in addition",
                      num2Text: "Furthermore - for example",
                      num3Text: "Besides - by contrast",
                      num4Text: "However - in conclusion",
                      answer: 3),
        QuestionModel(num: 20,
                      questionText: "주어진 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "And working offers more than financial security.",
                      reference2: "Why do workaholics enjoy their jobs so much? Mostly because working offers some important advantages. (①) It provides people with paychecks―a way to earn a living. (②) It provides people with self-confidence; they have a feeling of satisfaction when they’ve produced a challenging piece of work and are able to say, “I made that”. (③) Psychologists claim that work also gives people an identity; they work so that they can get a sense of self and individualism. (④) In addition, most jobs provide people with a socially acceptable way to meet others. It could be said that working is a positive addiction; maybe workaholics are compulsive about their work, but their addiction seems to be a safe―even an advantageous―one.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 2),
        ]
        let exam = ExamModel(id: 202122, year: 2021, examTypeID: "지방직", subjectID: "영어", questions: questions)
        exams2021.append(exam)
    }
    func saveExam202123() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "다음에 해당하는 나라에 대한 설명으로 옳은 것은?",
                      reference: "○은력(殷曆) 정월에 지내는 제천행사는 나라에서 여는 대회로 날마다 먹고 마시고 노래하고 춤추는데, 이를 영고라 하였다. 이때 형옥을 중단하고 죄수를 풀어주었다.\n\n○국내에 있을 때의 의복은 흰색을 숭상하며, 흰 베로 만든 큰 소매 달린 도포와 바지를 입고 가죽신을 신는다. 외국에 나갈 때는 비단옷․수 놓은 옷․모직옷을 즐겨입는다.\n\n－〖삼국지〗 위서 동이전－",
                      num1Text: "사람이 죽으면 뼈만 추려 가족 공동 무덤인 목곽에 안치하였다.",
                      num2Text: "읍군이나 삼로라고 불린 군장이 자기 영역을 다스렸다.",
                      num3Text: "가축 이름을 딴 마가, 우가, 저가, 구가 등이 있었다.",
                      num4Text: "천신을 섬기는 제사장인 천군이 있었다.",
                      answer: 3),
        QuestionModel(num: 2,
                      questionText: "(가) 나라에 대한 설명으로 옳은 것은?",
                      reference: "북쪽 구지에서 이상한 소리로 부르는 것이 있었다. …(중략)… 구간(九干)들은 이 말을 따라 모두 기뻐하면서 노래하고 춤을 추었다. 자줏빛 줄이 하늘에서 드리워져서 땅에 닿았다. 그 줄이 내려온 곳을 따라가 붉은 보자기에 싸인 금으로 만든 상자를 발견하고 열어보니, 해처럼 둥근 황금알 여섯 개가 있었다. 알 여섯이 모두 변하여 어린아이가 되었다. …(중략)… 가장 큰 알에서 태어난 수로(首露)가 왕위에 올라 [ (가) ]를/을 세웠다.\n\n－〖삼국유사〗－",
                      num1Text: "해상 교역을 통해 우수한 철을 수출하였다.",
                      num2Text: "박, 석, 김씨가 교대로 왕위를 계승하였다.",
                      num3Text: "경당을 설치하여 학문과 무예를 가르쳤다.",
                      num4Text: "정사암 회의를 통해 재상을 선발하였다.",
                      answer: 1),
        QuestionModel(num: 3,
                      questionText: "(가)에 들어갈 기구로 옳은 것은?",
                      reference: "고려 시대 중서문하성과 중추원의 고위 관료들은 도병마사와 [ (가) ]에서 국가의 중요한 일을 논의하였다. 도병마사에서는 국방과 군사 문제를 다루었고, [ (가) ]에서는 제도와 격식을 만들었다.",
                      num1Text: "삼사",
                      num2Text: "상서성",
                      num3Text: "어사대",
                      num4Text: "식목도감",
                      answer: 4),
        QuestionModel(num: 4,
                      questionText: "(가)에 대한 설명으로 옳은 것은?",
                      reference: "건국 초부터 북진 정책을 추진한 고려는 발해를 멸망시킨 [ (가) ]를/을 견제하고 송과 친선 관계를 맺었다. 이에 송과 대립하던 [ (가) ]는/은 고려를 경계하여 여러 차례 고려에 침입하였다.",
                      num1Text: "강조의 정변을 구실로 고려를 침략하였다.",
                      num2Text: "고려에 동북 9성을 돌려달라고 요구하였다.",
                      num3Text: "다루가치를 배치하여 고려의 내정을 간섭하였다.",
                      num4Text: "쌍성총관부를 두어 철령 이북의 땅을 지배하였다.",
                      answer: 1),
        QuestionModel(num: 5,
                      questionText: "(가)에 들어갈 기구로 옳은 것은?",
                      reference: "○무릇 관직을 받은 자의 고신(임명장)은 5품 이하일 때는 [ (가) ]과/와 사간원의 서경(署經)을 고려하여 발급한다.\n\n○[ (가) ]는/은 시정(時政)을 논하고, 모든 관원을 규찰하며, 풍속을 바르게 하는 등의 일을 맡는다.",
                      num1Text: "사헌부",
                      num2Text: "교서관",
                      num3Text: "승문원",
                      num4Text: "승정원",
                      answer: 1),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 ‘그’에 대한 설명으로 옳은 것은?",
                      reference: "그가 왕에게 아뢰었다. “삼교는 솥의 발과 같아서 하나라도 없어서는 안 됩니다. 지금 유교와 불교는 모두 흥하는데 도교는 아직 번성하지 않으니, 소위 천하의 도술(道術)을 갖추었다고 할 수 없습니다. 엎드려 청하오니 당에 사신을 보내 도교를 구해 와서 나라 사람들을 가르치게 하소서.”\n\n－〖삼국사기〗－",
                      num1Text: "당나라와 동맹을 체결하였다.",
                      num2Text: "천리장성의 축조를 맡아 수행하였다.",
                      num3Text: "수나라의 군대를 살수에서 격퇴하였다.",
                      num4Text: "남진 정책을 추진하여 한성을 점령하였다.",
                      answer: 2),
        QuestionModel(num: 7,
                      questionText: "(가) 인물에 대한 설명으로 옳은 것은?",
                      reference: "[ (가) ]가/이 귀산 등에게 말하기를 “세속에도 5계가 있으니, 첫째는 충성으로써 임금을 섬기는 것, 둘째는 효도로써 어버이를 섬기는 것, 셋째는 신의로써 벗을 사귀는 것, 넷째는 싸움에 임하여 물러서지 않는 것, 다섯째는 생명 있는 것을 죽이되 가려서 한다는 것이다. 그대들은 이를 실행함에 소홀하지 말라.”라고 하였다.\n\n-〖삼국사기〗-",
                      num1Text: "모든 것이 한마음에서 나온다는 일심 사상을 제시하였다.",
                      num2Text: "화엄 사상을 연구하여 ｢화엄일승법계도｣를 작성하였다.",
                      num3Text: "왕에게 수나라에 군사를 청하는 글을 지어 바쳤다.",
                      num4Text: "인도를 여행하여 〖왕오천축국전〗을 썼다.",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "(가), (나)에 들어갈 이름을 바르게 연결한 것은?",
                      reference: "[ (가) ]는/은 〖북학의〗를 저술하여 청의 선진 기술을 적극적으로 수용할 것과 상공업 육성 등을 역설하였다. 한편, [ (나) ]는/은 중국 및 일본의 방대한 자료를 참고하여 〖해동역사〗를 편찬함으로써, 한․중․일 간의 문화 교류를 잘 보여주었다.",
                      num1Text: "박지원 - 한치윤",
                      num2Text: "박지원 - 안정복",
                      num3Text: "박제가 - 한치윤",
                      num4Text: "박제가 - 안정복",
                      answer: 3),
        QuestionModel(num: 9,
                      questionText: "다음 사건을 시기순으로 바르게 나열한 것은?",
                      reference: "(가)정중부와 이의방이 정변을 일으켰다.\n(나)최충헌이 이의민을 제거하고 권력을 잡았다.\n(다)충주성에서 천민들이 몽골군에 맞서 싸웠다.\n(라)이자겸이 척준경과 더불어 난을 일으켰다.",
                      num1Text: "(가)→(나)→(라)→(다)",
                      num2Text: "(가)→(다)→(나)→(라)",
                      num3Text: "(라)→(가)→(나)→(다)",
                      num4Text: "(라)→(가)→(다)→(나)",
                      answer: 3),
        QuestionModel(num: 10,
                      questionText: "(가) 지역에 대한 설명으로 옳은 것은?",
                      reference: "나는 삼한(三韓) 산천의 음덕을 입어 대업을 이루었다. [ (가) ]는/은 수덕(水德)이 순조로워 우리나라 지맥의 뿌리가 되니 대업을 만대에 전할 땅이다. 왕은 춘하추동 네 계절의 중간달에 그곳에 가 100일 이상 머물러서 나라를 안녕케 하라.\n\n-〖고려사〗-",
                      num1Text: "이곳에 대장도감을 설치하여 재조대장경을 만들었다.",
                      num2Text: "지눌이 이곳에서 수선사 결사 운동을 펼쳤다.",
                      num3Text: "망이․망소이가 이곳에서 봉기하였다.",
                      num4Text: "몽골이 이곳에 동녕부를 두었다.",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "다음 내용의 역사서에 대한 설명으로 옳은 것은?",
                      reference: "왕께서는 “우리나라 사람들은 유교 경전과 중국 역사에 대해서는 자세히 말하는 사람이 있으나 우리나라의 사실에 이르러서는 잘 알지 못하니 매우 유감이다. 중국 역사서에 우리 삼국의 열전이 있지만 상세하게 실리지 않았다. 또한, 삼국의 고기(古記)는 문체가 거칠고 졸렬하며 빠진 부분이 많으므로, 이런 까닭에 임금의 선과 악, 신하의 충과 사악, 국가의 안위 등에 관한 것을 다 드러내어 그로써 후세에 권계(勸戒)를 보이지 못했다. 마땅히 일관된 역사를 완성하고 만대에 물려주어 해와 별처럼 빛나도록 해야 하겠다.”라고 하셨습니다.",
                      num1Text: "불교를 중심으로 신화와 설화를 정리하였다.",
                      num2Text: "유교적인 합리주의 사관에 따라 기전체로 서술되었다.",
                      num3Text: "단군조선을 우리 역사의 시작으로 본 통사이다.",
                      num4Text: "진흥왕의 명을 받아 거칠부가 편찬하였다.",
                      answer: 2),
        QuestionModel(num: 12,
                      questionText: "밑줄 친 ‘이 왕’에 대한 설명으로 옳은 것은?",
                      reference: "문무왕이 왜병을 진압하고자 감은사를 처음 창건하려 했으나, 끝내지 못하고 죽어 바다의 용이 되었다. 뒤이어 즉위한 이 왕이 공사를 마무리하였다. 금당 돌계단 아래에 동쪽을 향하여 구멍을 하나 뚫어 두었으니, 용이 절에 들어와서 돌아다니게 하려고 마련한 것이다. 유언에 따라 유골을 간직해 둔 곳은 대왕암(大王岩)이라고 불렀다.\n\n－〖삼국유사〗－",
                      num1Text: "건원이라는 독자적인 연호를 사용하였다.",
                      num2Text: "국학을 설립하여 유학을 교육하였다.",
                      num3Text: "백성에게 처음으로 정전을 지급하였다.",
                      num4Text: "진골 출신으로서 처음 왕위에 올랐다.",
                      answer: 2),
        QuestionModel(num: 13,
                      questionText: "밑줄 친 ‘왕’의 재위 기간에 있었던 사실로 옳은 것은?",
                      reference: "왕".underLined + "은 노론과 소론, 남인을 두루 등용하였으며 젊은 관료들을 재교육하기 위해 초계문신제를 시행하였다. 또 서얼 출신의 유능한 인사를 규장각 검서관으로 등용하였다.",
                      num1Text: "동학이 창시되었다.",
                      num2Text: "〖대전회통〗이 편찬되었다.",
                      num3Text: "신해통공이 시행되었다.",
                      num4Text: "홍경래의 난이 발생하였다.",
                      answer: 3),
        QuestionModel(num: 14,
                      questionText: "(가) 인물에 대한 설명으로 옳은 것은?",
                      reference: "철종이 죽고 고종이 어린 나이로 왕이 되자, 고종의 아버지인 [ (가) ]가/이 실권을 장악하였다. [ 가) ]는/은 임진왜란 때 불탄 후 방치되어 있던 경복궁을 중건하였다. 이때 원납전이라는 기부금을 징수하는 일이 벌어졌으며 당백전이라는 화폐도 발행되었다.",
                      num1Text: "｢대한국국제｣를 만들어 공포하였다.",
                      num2Text: "서원을 대폭 줄이는 정책을 추진하였다.",
                      num3Text: "우정총국 개국 축하연을 이용해 정변을 일으켰다.",
                      num4Text: "황쭌셴의 〖조선책략〗을 가져와 널리 유포하였다.",
                      answer: 2),
        QuestionModel(num: 15,
                      questionText: "(가) 단체의 활동에 대한 설명으로 옳은 것은?",
                      reference: "탑골공원에 모인 수많은 학생과 시민이 독립 선언식을 거행하고 만세를 부르며 거리를 행진하였다. 이후 만세 시위는 전국으로 확산하였다. 이 운동을 계기로 독립운동가 사이에는 독립운동을 더욱 조직적으로 전개하자는 공감대가 형성되어 [ (가) ]가/이 만들어졌다. [ (가) ]는/은 구미 위원부를 설치하는 등 적극적으로 독립운동을 펼쳐 나갔다.",
                      num1Text: "｢대동단결선언｣을 발표하였다.",
                      num2Text: "국내와의 연락을 위해 교통국을 두었다.",
                      num3Text: "독립군을 양성하기 위해 신흥무관학교를 설립하였다.",
                      num4Text: "｢조선혁명선언｣을 강령으로 삼아 의열투쟁을 전개하였다.",
                      answer: 2),
        QuestionModel(num: 16,
                      questionText: "(가) 시기에 있었던 사실로 옳은 것은?",
                      reference: "[ 평양의 관민이 제너럴 셔먼호를 불태웠다. ]\n\n   ⬇︎\n\n[ (가) ]\n\n   ⬇︎\n\n[ 미군이 광성보를 공격해 점령하였다. ]",
                      num1Text: "고종이 홍범 14조를 발표하였다.",
                      num2Text: "일본의 운요호가 초지진을 포격하였다.",
                      num3Text: "오페르트가 남연군의 묘 도굴을 시도하였다.",
                      num4Text: "차별 대우에 불만을 품은 군인이 임오군란을 일으켰다.",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "밑줄 친 ‘이 단체’에 대한 설명으로 옳은 것은?",
                      reference: "1920년대 국내에서는 일본과 타협해 실익을 찾자는 자치 운동이 대두하였다. 비타협적인 민족주의자들은 이를 경계하면서 사회주의 세력과 연대하고자 하였다. 사회주의 세력도 정우회 선언을 발표해 비타협적 민족주의 세력과 제휴를 주장하였다. 그 결과 비타협적 민족주의 세력과 사회주의 세력은 1927년 2월에 " + "이 단체".underLined + "를 창립하고 이상재를 회장으로 추대하였다.",
                      num1Text: "조선물산장려회를 조직해 물산장려운동을 펼쳤다.",
                      num2Text: "고등 교육 기관을 설립하기 위해 민립대학설립운동을 시작하였다.",
                      num3Text: "문맹 퇴치와 미신 타파를 목적으로 브나로드 운동을 전개하였다.",
                      num4Text: "광주학생항일운동의 진상을 조사하고 이를 알리는 대회를 개최하고자 하였다.",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "다음과 같은 내용이 담긴 조약에 대한 설명으로 옳은 것은?",
                      reference: "일본 정부는 그 대표자로 한국 황제 밑에 1명의 통감을 두되, 통감은 전적으로 외교에 관한 사항을 관리하기 위하여 경성에 주재하고 친히 한국 황제를 만날 수 있는 권리를 가진다. 또한, 일본 정부는 한국의 개항장 및 일본 정부가 필요하다고 인정하는 지역에 이사관을 설치할 권리를 가지며, 이사관은 통감의 지휘하에 종래 재(在)한국 일본 영사에게 속하였던 모든 권리를 집행한다.",
                      num1Text: "조선총독부를 설치한다는 조항이 포함되어 있다.",
                      num2Text: "헤이그 특사 사건 직후 일제의 강요로 체결되었다.",
                      num3Text: "방곡령 시행 전에 미리 통보해야 한다는 합의가 실려 있다.",
                      num4Text: "일본의 중재 없이 국제적 성격을 가진 조약을 체결할 수 없다는 내용이 담겨 있다.",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "(가)에 대한 설명으로 옳은 것은?",
                      reference: "1945년 12월 모스크바에서 미국, 소련, 영국의 외무장관들은 한국 문제를 논의하였다. 이 회의에서 미국, 소련, 영국, 중국이 최장 5년간 신탁통치를 시행한다는 합의가 이루어졌다. 또 미국과 소련이 [ (가) ]를/을 개최해 민주주의 임시정부 수립 문제에 대해 논의하기로 했다. 이 합의에 따라 1946년 3월 서울에서 [ (가) ]가/이 시작되었다.",
                      num1Text: "미․소 양측의 의견 차이로 결렬되었다.",
                      num2Text: "조선건국준비위원회를 조직하는 성과를 냈다.",
                      num3Text: "민주 공화제를 핵심으로 한 제헌헌법을 만들었다.",
                      num4Text: "유엔 감시하의 총선거로 정부를 수립한다는 결정을 내렸다.",
                      answer: 1),
        QuestionModel(num: 20,
                      questionText: "(가) 시기에 있었던 사실로 옳은 것은?",
                      reference: "4.19혁명이 일어나다-(가)-유신헌법이 공포되다.",
                      num1Text: "｢반민족행위처벌법｣이 제정되다.",
                      num2Text: "7․4 남북 공동 성명이 발표되다.",
                      num3Text: "남북한이 유엔에 동시 가입하다.",
                      num4Text: "5․18 민주화 운동이 일어나다.",
                      answer: 2),

        ]
        let exam = ExamModel(id: 202123, year: 2021, examTypeID: "지방직", subjectID: "한국사", questions: questions)
        exams2021.append(exam)
    }
}
