//
//  ExamStore2020.swift
//  HandGosi
//
//  Created by Sy Lee on 2022/08/22.
//

import Foundation

class ExamStore2020 {
    var exams2020: [ExamModel] = []
    
    init() {
        saveExam202011()
        saveExam202012()
        saveExam202013()
        
        saveExam202021()
        saveExam202022()
        saveExam202023()
    }
    
    //국가직
    func saveExam202011() {
        let questions = [
        QuestionModel(num: 1,
                      questionText: "안긴문장이 없는 것은?",
                      num1Text: "나는 동생이 시험에 합격하기를 고대한다.",
                      num2Text: "착한 영호는 언제나 친구들을 잘 도와준다.",
                      num3Text: "해진이는 울산에 살고 초희는 광주에 산다.",
                      num4Text: "아버지께서는 나에게 내일 가족 여행을 가자고 말씀하셨다.",
                      answer: 3),
        QuestionModel(num: 2,
                      questionText: "밑줄 친 부분이 바르게 쓰이지 않은 것은?",
                      num1Text: "지금쯤 " + "골아떨어졌겠지?".underLined,
                      num2Text: "그 친구, 생각이 깊던데 책" + "깨나".underLined + " 읽었겠어",
                      num3Text: "갖은 " + "곤욕".underLined + "과 모멸과 박대는 각오한 바이다.",
                      num4Text: "김 과장은 "+"그러고 나서".underLined+" 서류를 보완해 달라고 했다.",
                      answer: 1),
        QuestionModel(num: 3,
                      questionText: "문장 성분의 호응이 자연스러운 것은?",
                      num1Text: "내가 강조하고 싶은 점은 우리가 고유 언어를 가졌다.",
                      num2Text: "좋은 사람과 대화하며 함께한 일은 즐거운 시간이었다.",
                      num3Text: "내 생각은 집을 사서 이사하는 것이 좋겠다고 결정했다.",
                      num4Text: "그는 내 생각이 옳지 않다고 여러 사람 앞에서 말을 하였다.",
                      answer: 4),
        QuestionModel(num: 4,
                      questionText: "㉠～㉣의 고쳐 쓰기 방안으로 적절하지 않은 것은?",
                      reference: "㉠공사하는 기간 동안 안전사고가 일어나지 않도록 유의해 주십시오.\n㉡오늘 오후에 팀 전체가 모여 회의를 갖겠습니다.\n㉢비상문이 열려져 있어 신속하게 대피할 수 있었다.\n㉣지난밤 검찰은 그를 뇌물 수수 혐의로 구속했다.",
                      num1Text: "㉠:‘기간’과 ‘동안’은 의미가 중복되므로 ‘공사하는 기간 동안’은 ‘공사하는 동안’으로 고쳐 쓴다.",
                      num2Text: "㉡: ‘회의를 갖겠습니다’는 번역 투이므로 ‘회의하겠습니다’로 고쳐 쓴다.",
                      num3Text: "㉢: ‘열려져’는 ‘－리－’와 ‘－어지다’가 결합한 이중 피동 표현이므로 ‘열려’로 고쳐 쓴다.",
                      num4Text: "㉣: 동작의 대상에게 행위의 효력이 미친다는 의미를 제시해야 하므로 ‘구속했다’는 ‘구속시켰다’로 고쳐 쓴다.",
                      answer: 4),
        QuestionModel(num: 5,
                      questionText: "㉠～㉣을 사전에 올릴 때 ‘한글 맞춤법 규정’에 따른 순서로 적절한 것은?",
                      reference: "㉠곬  ㉡규탄  ㉢곳간  ㉣광명",
                      num1Text: "㉠→㉢→㉡→㉣",
                      num2Text: "㉠→㉢→㉣→㉡",
                      num3Text: "㉢→㉠→㉡→㉣",
                      num4Text: "㉢→㉠→㉣→㉡",
                      answer: 2),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 말의 의미와 거리가 먼 것은?",
                      reference: "○넌 얼마나 "+"오지랖이 넓기에".underLined+" 남의 일에 그렇게 미주알고주알 캐는 거냐?\n\n○강쇠네는 입이 재고 무슨 일에나 "+"오지랖이 넓었지만".underLined+", 무작정 덤벙거리고만 다니는 새줄랑이는 아니었다.",
                      num1Text: "謁見",
                      num2Text: "干涉",
                      num3Text: "參見",
                      num4Text: "干與",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                      reference: "  천국에 사는 사람들은 지옥을 생각할 필요가 없다. 그러나 우리 다섯 식구는 지옥에 살면서 천국을 생각했다. 단 하루라도 천국을 생각해 보지 않은 날이 없다. 하루하루의 생활이 지겨웠기 때문이다. 우리의 생활은 전쟁과 같았다. 우리는 그 전쟁에서 날마다 지기만 했다.\n  아버지가 평생을 통해 해 온 일은 다섯 가지이다. 채권 매매, 칼 갈기, 고층 건물 유리 닦기, 펌프 설치하기, 수도 고치기이다. 이 일들만 해 온 아버지가 갑자기 다른 일을 하겠다고 했다. 서커스단의 일이었다. 아버지는 처음 보는 꼽추 한 사람을 데리고 와 여러 가지 이야기를 했다. 처음 얼마 동안은 그의 조수로 일하면 된다고 했다. 두 사람은 자기들이 무대 위에서 해야 할 연기에 대해 이야기했다. 그러자 어머니가 아버지에게 대들었다. 우리들도 아버지를 성토했다. 아버지는 힘없이 물러섰다. 꼽추는 멍하니 앉아 우리를 보았다. 꼽추는 눈물이 핑 돌아 돌아갔다. 그의 뒷모습은 아주 쓸쓸해 보였다. 아버지의 꿈은 깨어졌다. 아버지는 무거운 부대를 메고 다시 일을 찾아 나갔다.\n  …(중략)…\n  어머니가 울었다. 어머니는 인쇄소 제본 공장에 나가 접지 일을 했다. 고무 골무를 끼고 인쇄물을 접었다. 나는 겁이 났다. 나는 인쇄소 공무부 조역으로 출발했다. 땀을 흘리지 않고는 아무것도 얻을 수 없다는 것을 뒤늦게 알았다. 영호와 영희도 몇 달 간격을 두고 학교를 그만두었다. 마음이 차라리 편해졌다. 우리를 해치는 사람은 없었다. 우리는 보이지 않는 보호를 받고 있었다. 남아프리카의 어느 원주민들이 일정한 구역 안에서 보호를 받듯이 우리도 이질 집단으로서 보호를 받았다. 나는 우리가 이 구역 안에서 한 걸음도 밖으로 나갈 수 없다는 것을 깨달았다. 나는 조역, 공목, 약물, 해판의 과정을 거쳐 정판에서 일했다. 영호는 인쇄에서 일했다. 나는 우리가 한 공장에서 일하는 것이 싫었다. 영호도 마찬가지였다. 그래서 영호는 먼저 철공소 조수로 들어가 잔심부름을 했다. 가구 공장에서도 일했다. 그 공장에 가 일하는 영호를 보았다. 뽀얀 톱밥 먼지와 소음 속에 서 있는 작은 영호를 보고 나는 그만두라고 했다. 인쇄 공장의 소음도 무서운 것이었으나 그곳에는 톱밥 먼지가 없었다. 우리는 죽어라 하고 일했다. 우리의 팔목은 공장 안에서 굵어 갔다. 영희는 그때 큰길가 슈퍼마켓 한쪽에 자리 잡은 빵집에서 일했다. 우리가 고맙게 생각한 것은 환경이 깨끗하다는 것 하나뿐이었다.\n  우리는 무슨 일이 있든 공부는 해야 한다고 생각했다. 공부를 하지 않고는 우리 구역에서 벗어날 수가 없다고 생각했다. 세상은 공부를 한 자와 못 한 자로 너무나 엄격하게 나누어져 있었다. 끔찍할 정도로 미개한 사회였다. 우리가 학교 안에서 배운 것과는 정반대로 움직였다. 나는 무슨 책이든 손에 잡히는 대로 읽었다. 정판에서 식자로 올라간 다음에는 일을 하다 말고 원고를 읽는 버릇까지 생겼다. 동생들에게 필요하다고 느껴지는 것은 판을 들고 가 몇 벌씩 교정쇄를 내기도 했다. 영호와 영희는 나의 말을 잘 들었다. 내가 가져다준 교정쇄를 동생들은 열심히 읽었다. 실제로 우리가 이 노력으로 잃은 것은 하나도 없었다. 나는 고입 검정고시를 거쳐 방송 통신 고교에 입학했다.\n\n－조세희, ｢난장이가 쏘아 올린 작은 공｣－",
                      num1Text: "‘우리 다섯 식구’는 생존을 위해 애쓰지만 윤택한 삶을 누리기 어려운 처지에 있다.",
                      num2Text: "‘아버지’는 가족들의 바람을 수용하여, 평생 해 온 일을 그만두고 새로운 일을 시작하기로 결심한다.",
                      num3Text: "‘보이지 않는 보호’는 말 그대로의 보호라기보다는 벗어날 수 없는 계층적 한계를 의미한다고 할 수 있다.",
                      num4Text: "‘우리’는 자신들의 ‘구역’에서 벗어날 길을 ‘공부를 한 자’가 됨으로써 찾을 수 있다고 여긴다.",
                      answer: 2),
        QuestionModel(num: 8,
                      questionText: "글쓴이의 견해에 부합하지 않는 것은?",
                      reference: "  사물 인터넷(IoT, Internet of Things)의 정의로 ‘수십 억 개의 사물이 서로 연결되는 것’이라고 설명하는 것은 그리 유용하지 않다. 사물 인터넷이 무엇인지 이해하기 위해서는 ‘사물’에서 출발하기보다는 ‘인터넷’에서 출발하는 것이 좋다. 인터넷이 전 세계의 컴퓨터를 서로 소통하도록 만든다는 생각이 실현된 것이라면, 사물 인터넷은 이제 전 세계의 사물들을 ‘컴퓨터로 만들어’ 서로 소통하도록 만든다는 생각을 실현하는 것이다. 컴퓨터는 본래 전원이 있고 칩이 있고, 이것이 통신 장치와 프로토콜을 갖게 되어 연결된 것이다. 그렇다면 이제는 전원이 있었던 전자 기기나 기계 등은 그 자체로, 전원이 없었던 일반 사물들은 새롭게 센서와 배터리, 통신 모듈이 부착되면서 컴퓨터가 되고 이렇게 컴퓨터가 된 사물들이 그들 간에 또는 인간의 스마트 기기와 네트워크로 연결되는 것이다.\n  현재의 인터넷과 사물 인터넷의 차이를, 혹자는 사람이 개입되는 것은 사물 인터넷이 아니라고 이야기하면서 엄격한 M2M(Machine to Machine)이라는 개념에 근거해 설명한다. 또 혹자는 사물 인터넷이 실현되려면 사람만큼 사물이 판단할 수 있어야 한다고 주장하면서 사물의 지능성을 중요시하는 경우도 있는데, 두 가지 모두 그릇된 것이다. 사물 인터넷을 제대로 이해하려면 기존 인터넷과의 차이점에 주목하기보다는 오히려 공통점을 인식하는 것이 더 중요하다. 컴퓨터를 서로 연결하는 수준에서 출발한 것이 기존의 인터넷이라면, 이제는 사물 각각이 컴퓨터가 되고, 그 사물들이 사람과 손쉽게 닿는 스마트폰, 스마트 워치 등과 서로 소통하는 것이다.",
                      num1Text: "사물 인터넷의 개념을 파악하기 위해서는 기존 인터넷과의 공통점을 이해하는 것이 필요하다. ",
                      num2Text: "센서와 배터리, 통신 모듈 등을 갖춘 사물들이 네트워크로 연결되어 사물 인터넷으로 기능한다.",
                      num3Text: "사물 인터넷은 사람 수준의 지능을 가진 사물들이 네트워크상에서 인간의 개입 없이 서로 소통하는 것으로 정의된다.",
                      num4Text: "사물 인터넷은 컴퓨터가 아니었던 사물도 네트워크로 연결될 수 있다는 점에서 기존의 인터넷과 다르다.",
                      answer: 3),
        QuestionModel(num: 9,
                      questionText: "<보기>는 다음 한시에 대한 감상이다. ㉠～㉣ 중 적절하지 않은 것은?",
                      reference: "白犬前行黃犬隨\n흰둥이가 앞서고 누렁이는 따라가는데\n野田草際塚纍纍\n들밭머리 풀섶에는 무덤이 늘어서 있네\n老翁祭罷田間道\n늙은이가 제사를 끝내고 밭 사이 길로 들어서자\n日暮醉歸扶小兒\n해 저물어 취해 돌아오는 길을 아이가 부축하네\n\n－이달, ｢제총요(祭塚謠)｣－",
                      reference2: "  이달(李達, 1561～1618)이 살았던 시기를 고려할 때, 시인은 임진왜란을 겪었을 것이라 추정된다. ㉠"+"이 시는 해질 무렵 두 사람이 제사를 지낸 뒤 집으로 돌아오는 상황을 노래하고 있다.".underLined+" ㉡"+"이 시에서 무덤이 들밭머리에 늘어서 있다는 것은 전란을 겪은 마을에서 많은 이들이 갑작스러운 죽음을 맞이했음을 의미한다고 할 것이다.".underLined+" 여기 등장하는 늙은이와 아이는 할아버지와 손자의 관계로 파악할 수 있다. 아마도 이들은 아이의 부모이자 할아버지의 자식에 해당하는 이의 무덤에 다녀오는 길일 것이다. ㉢"+"할아버지가 취한 까닭도 죽은 이에 대한 안타까움과 속상함 때문일 것이다.".underLined+" ㉣"+"이 시는 전반부에서는 그림을 그리듯이 장면을 묘사하고 후반부에서는 정서를 표출하는 선경후정의 형식을 취하고 있다.".underLined,
                      num1Text: "㉠",
                      num2Text: "㉡",
                      num3Text: "㉢",
                      num4Text: "㉣",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "㉠～㉣의 한자 표기로 옳은 것은?",
                      reference: "  과학사를 들춰 보면 기존의 학문 체계에 ㉠"+"도전".underLined+"했다가 낭패를 본 인물들의 이야기를 자주 만날 수 있다. 대표적인 인물이 천동설을 부정하고 지동설을 주장한 갈릴레이이다. 천동설을 ㉡"+"지지".underLined+"하던 당시의 권력층은 그들의 막강한 힘을 이용하여 갈릴레이를 신의 권위에 도전하는 이단자로 욕하고 목숨까지 위협했다. 갈릴레이가 영원한 ㉢"+"침묵".underLined+"을 ㉣"+"맹세".underLined+"하지 않고 계속 지동설을 주장했더라면 그는 단두대의 이슬로 사라졌을지도 모른다.",
                      num1Text: "㉠逃戰",
                      num2Text: "㉡持地",
                      num3Text: "㉢浸黙",
                      num4Text: "㉣盟誓",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "다음 대화에서 ‘정민’의 의사소통 방식으로 가장 적절한 것은?",
                      reference: "상수:요즘 짝꿍이랑 사이가 별로야.\n\n정민:왜? 무슨 일이 있었어?\n\n상수:그 애가 내 일에 자꾸 끼어들어. 사물함 정리부터 내 걸음걸이까지 하나하나 지적하잖아.\n\n정민:그런 일이 있었구나. 짝꿍한테 그런 말을 해 보지 그랬어.\n\n상수:해 봤지. 하지만 그때뿐이야. 아마 나를 자기 동생처럼 여기나 봐.\n\n정민:나도 그런 적이 있어. 작년의 내 짝꿍도 나한테 무척이나 심했거든. 자꾸 끼어들어서 너무 힘들었어. 네 얘기를 들으니 그때가 다시 생각난다. 그런데 생각을 바꿔 보니 그게 관심이다 싶더라고. 그랬더니 마음이 좀 편해졌어. 그리고 짝꿍과 솔직하게 얘기를 해 봤더니, 그 애도 자신의 잘못된 점을 고치더라고.\n\n상수:너도 그랬구나. 나도 생각을 바꾸려고 노력해 보고, 짝꿍하고 진솔한 대화를 나눠 봐야겠어.",
                      num1Text: "상대방의 입장을 고려해 용서함으로써 갈등을 해결하고 있다.",
                      num2Text: "자신의 경험을 들어 상대방이 해결점을 찾을 수 있도록 돕고 있다.",
                      num3Text: "상대방의 약점을 비판하면서 자신의 장점을 최대한 부각하고 있다.",
                      num4Text: "상대방이 말하는 내용을 경청하면서 그 타당성을 평가하고 있다.",
                      answer: 2),
        QuestionModel(num: 12,
                      questionText: "다음에서 제시한 글의 전개 방식의 예로 가장 적절한 것은?",
                      reference: "  ‘인과’는 원인과 결과를 서술하는 전개 방식이다. 어떤 현상이나 결과가 나타나게 된 원인이나 힘을 제시하고 그로 말미암아 초래된 결과를 나타내는 서술 방식이다.",
                      num1Text: "온실 효과로 지구의 기온이 상승할 때 가장 심각한 영향은 해수면의 상승이다. 이러한 현상은 바다와 육지의 비율을 변화시켜 엄청난 기후 변화를 유발하며, 게다가 섬나라나 저지대는 온통 물에 잠기게 된다.",
                      num2Text: "이 사회의 경제는 모두가 제로섬 요소로 구성되어 있다. 제로섬(zero-sum)이란 어떤 수를 합해서 제로가 된다는 뜻이다. 어떤 운동 경기를 한다고 할 때 이기는 사람이 있으면 반드시 지는 사람이 있게 마련이다.",
                      num3Text: "다음날도 찬호는 학교 담을 따라 돌았다. 그리고 고무신을 벗어 한 손에 한 짝씩 쥐고는 고양이 걸음으로 보초의 뒤를 빠져 팽이처럼 교문 안으로 뛰어들었다.",
                      num4Text: "벼랑 아래는 빽빽한 소나무 숲에 가려 보이지 않았다. 새털구름이 흩어진 하늘 아래 저 멀리 논과 밭, 강을 선물 세트처럼 끼고 들어앉은 소읍의 전경은 적막해 보였다.",
                      answer: 1),
        QuestionModel(num: 13,
                      questionText: "다음 진행자 ‘A’의 대화 진행 전략으로 적절하지 않은 것은?",
                      reference: "A: 여러분, 안녕하세요? 한 지방 자치 단체가 의료 취약 계층을 위한 의약품 공급 정보망 구축 사업을 진행해 오고 있는데요. 오늘은 그 관계자 한 분을 모시고 말씀을 들어 보기로 하겠습니다. 과장님, 안녕하세요?\n\nB:네, 안녕하세요.\n\nA: 의약품 공급 정보망이라는 말이 다소 생소한데 이게 무슨 말인가요?\n\nB: 네, 약국이나 제약 회사가 의약품을 저희에게 기탁하면, 이 약품을 필요한 사회 복지 시설이나 국내외 의료 봉사 단체에 무상으로 줄 수 있도록 연결하는 사이버상의 네트워크입니다.\n\nA: 그렇군요. 그동안 이 사업에 성과가 있었다면 그럴 만한 이유가 있을 텐데요, 이에 대해 말씀해 주세요.\n\nB: 그렇습니다. 약국이나 제약 회사에서는 판매되지 않은 의약품을 기탁하고 세금 혜택을 받습니다. 그리고 복지 시설이나 봉사 단체에서는 필요한 의약품을 무상으로 지원받을 수 있습니다.\n\nA: 그렇군요. 혹시 이 사업에 걸림돌은 없나요?\n\nB: 의약품을 의사의 처방에 따라서 주는 것이 아니라 수요자가 요구하면 주는 방식이어서 전문 의약품을 제공하는 과정에 어려움이 있습니다. 처방전 발급을 부탁할 수도 없고…….\n\nA: 그러니까 앞으로 이런 문제를 해결하기 위한 제도 정비나 의료 전문가의 지원이 좀 더 필요하다는 말씀인 것 같군요. 끝으로 이 사업에 참여하려면 어떻게 해야 하나요?\n\nB: 그건 생각보다 쉽습니다. 저희 홈페이지에 접속하셔서 회원으로 가입하시면 기부하실 때나 받으실 때나 모두 쉽게 참여하실 수 있습니다.\n\nA: 네, 간편해서 좋군요. 모쪼록 이 의약품 공급 정보망 사업이 확대되어 국내외 의료 취약 계층에 많은 도움이 되기를 바랍니다. 감사합니다.",
                      num1Text: "상대방의 말을 들었다는 반응을 보인다. ",
                      num2Text: "상대방의 대답에서 모순점을 찾아 논리적으로 대응한다.",
                      num3Text: "대화의 화제가 된 일을 홍보할 수 있는 대답을 유도한다.",
                      num4Text: "상대방의 말을 대화의 흐름에 맞게 해석하여 상대방의 말을 보충한다.",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "다음 글에 대한 이해로 가장 적절한 것은?",
                      reference: "  용왕의 아들 이목(璃目)은 항상 절 옆의 작은 연못에 있으면서 남몰래 보양(寶壤) 스님의 법화(法化)를 도왔다. 문득 어느 해에 가뭄이 들어 밭의 곡식이 타들어 가자 보양 스님이 이목을 시켜 비를 내리게 하니 고을 사람들이 모두 흡족히 여겼다. 하늘의 옥황상제가 장차 하늘의 뜻을 모르고 비를 내렸다 하여 이목을 죽이려 하였다. 이목이 보양 스님에게 위급함을 아뢰자 보양 스님이 이목을 침상 밑에 숨겨 주었다. 잠시 후에 옥황상제가 보낸 천사(天使)가 뜰에 이르러 이목을 내놓으라고 하였다. 보양 스님이 뜰 앞의 배나무[梨木]를 가리키자 천사가 배나무에 벼락을 내리고 하늘로 올라갔다. 그 바람에 배나무가 꺾어졌는데 용이 쓰다듬자 곧 소생하였다(일설에는 보양 스님이 주문을 외워 살아났다고 한다). 그 나무가 근래에 땅에 쓰러지자 어떤 이가 빗장 막대기로 만들어 선법당(善法堂)과 식당에 두었다. 그 막대기에는 글귀가 새겨져 있다.\n\n－일연, 〖삼국유사〗－",
                      num1Text: "천사의 벼락을 맞은 배나무는 저절로 소생했다.",
                      num2Text: "천사는 이목을 죽이려다 실수로 배나무에 벼락을 내렸다.",
                      num3Text: "벼락 맞은 배나무로 만든 막대기가 글쓴이의 당대까지 전해졌다.",
                      num4Text: "제멋대로 비를 내린 보양 스님을 벌하려고 옥황상제가 천사를 보냈다.",
                      answer: 3),
        QuestionModel(num: 15,
                      questionText: "㉠에 들어갈 주장으로 가장 적절한 것은?",
                      reference: "  경상 지역 방언을 쓰는 사람들은 대체로 ‘ㅓ’와 ‘ㅡ’를 구별하지 못한다. 이들은 ‘증표(證票)’나 ‘정표(情表)’를 구별하여 듣지 못할 뿐만 아니라 구별하여 발음하지 못하기 십상이다. 또 이들은 ‘ㅅ’과 ‘ㅆ’을 구별하지 못하는 경우가 많다. 따라서 이들은 ‘살밥을 많이 먹어서 쌀이 많이 쪘다’고 말하든 ‘쌀밥을 많이 먹어서 살이 많이 쪘다’고 말하든 쉽게 그 차이를 알지 못한다. 한편 평안도 및 전라도와 경상도의 일부에서는 ‘ㅗ’와 ‘ㅓ’를 제대로 분별해서 발음하지 않는 경우가 종종 있다. 평안도 사람들의 ‘ㅈ’ 발음은 다른 지역의 ‘ㄷ’ 발음과 매우 비슷하다. 이처럼 (    ㉠    )",
                      num1Text: "우리말에는 지역마다 다양한 소리가 있다.",
                      num2Text: "우리말은 지역에 따라 다양한 표준 발음법이 있다.",
                      num3Text: "우리말에는 지역에 따라 구별되지 않는 소리가 있다.",
                      num4Text: "자음보다 모음을 변별하지 못하는 지역이 더 많이 있다.",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "글의 통일성을 고려할 때 ㉠에 들어갈 문장으로 가장 적절한 것은?",
                      reference: "  기술 혁신의 상징으로 화려하게 등장한 이후 글로벌 아이콘이 됐던 소위 스마트폰이 그 진화의 한계에 봉착한 듯하다. 게다가 최근 들어 중국 업체들의 성장세가 만만치 않은 상황이 펼쳐지고 있다. 이런 가운데 오랜 기간 스마트폰 생산량의 수위를 지켜 왔던 기업들의 호시절도 끝난 분위기다. (    ㉠    )\n  그렇다면 스마트폰 이후 글로벌 주도 산업은 무엇일까. 첫손가락에 꼽히는 것은 페이스북, 아마존, 넷플릭스, 구글을 뜻하는 ‘팡(FANG)’이다. 모바일 퍼스트 시대에서 소프트웨어, 플랫폼 사업에 눈뜬 기업들이다. 이들은 지난해 매출과 순이익이 크게 늘었으며 주가도 폭등했다. 하지만 이들이라고 영속 불멸하지는 않을 것이다.",
                      num1Text: "온 국민이 절치부심(切齒腐心)하여 반성하지 않으면 안 된다.",
                      num2Text: "정보 기술 업계의 권불십년(權不十年)이라 하지 않을 수 없다.",
                      num3Text: "다른 나라의 기업들을 보고 아전인수(我田引水)해야 할 때다.",
                      num4Text: "글로벌 위기의 내우외환(內憂外患)에 국가 간 협력이 절실하다.",
                      answer: 2),
        QuestionModel(num: 17,
                      questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                      reference: "  희극의 발생 조건에 대하여 베르그송은 집단, 지성, 한 개인의 존재 등을 꼽았다. 즉 집단으로 모인 사람들이 자신들의 감성을 침묵하게 하고 지성만을 행사하는 가운데 그들 중 한 개인에게 그들의 모든 주의가 집중되도록 할 때 희극이 발생한다고 보았다. 그러나 그가 말하는 세 가지 사항은 웃음을 유발하는 것이 아니라 그러한 것을 가능케 하는 조건들이다. 웃음을 유발하는 단순한 형태의 직접적인 장치는 대상의 신체적인 결함이나 성격적인 결함을 들 수 있다. 관객은 이러한 결함을 지닌 인물을 통하여 스스로 자기 우월성을 인식하고 즐거워질 수 있게 된다. 이와 관련해 “한 인물이 우리에게 희극적으로 보이는 것은 우리 자신과 비교해서 그 인물이 육체의 활동에는 많은 힘을 소비하면서 정신의 활동에는 힘을 쓰지 않는 경우이다. 어느 경우에나 우리의 웃음이 그 인물에 대하여 우리가 지니는 기분 좋은 우월감을 나타내는 것임은 부정할 수 없다.”라는 프로이트의 말은 시사적이다.",
                      num1Text: "베르그송에 의하면 희극은 관객의 감성이 집단적으로 표출된 결과이다.",
                      num2Text: "베르그송에 의하면 집단, 지성, 한 개인의 존재는 희극 발생의 조건이다.",
                      num3Text: "한 개인의 신체적․성격적 결함은 집단의 웃음을 유발하는 직접적인 장치이다.",
                      num4Text: "프로이트에 의하면 상대적으로 정신 활동보다 육체 활동에 힘을 쓰는 상대가 희극적인 존재이다.",
                      answer: 1),
        QuestionModel(num: 18,
                      questionText: "㉠과 가장 유사한 정서가 드러나는 것은?",
                      reference: "  다시 방수액을 부어 완벽을 기하고 이음새 부분은 손가락으로 몇 번씩 문대어 보고 나서야 임 씨는 허리를 일으켰다. 임 씨가 일에 몰두해 있는 동안 그는 숨소리조차 내지 않고 일하는 양을 지켜보았다. ㉠"+"저 열 손가락에 박힌 공이의 대가가 기껏 지하실 단칸방만큼의 생활뿐이라면 좀 너무하지 않나 하는 안타까움".underLined+"이 솟아오르기도 했다. 목욕탕 일도 그러했지만 이 사람의 손은 특별한 데가 있다는 느낌이었다. 자신이 주무르고 있는 일감에 한 치의 틈도 없이 밀착되어 날렵하게 움직이고 있는 임 씨의 열 손가락은 손가락 이상의 그 무엇이었다.\n\n－양귀자, ｢비 오는 날이면 가리봉동에 가야 한다｣－",
                      num1Text: "즐거운 지상의 잔치에/금으로 타는 태양의 즐거운 울림/아침이면,/세상은 개벽을 한다.",
                      num2Text: "산에/산에/피는 꽃은/저만치 혼자서 피어 있네.//산에서 우는 작은 새여./꽃이 좋아/산에서/사노라네.",
                      num3Text: "남편은 어디에 나가 있는지/아침에 소 끌고 산에 올랐는데/산 밭을 일구느라 고생을 하며/저물도록 돌아오지 못한다네.",
                      num4Text: "눈을 가만 감으면 굽이 잦은 풀밭 길이,/개울물 돌돌돌 길섶으로 흘러가고,/백양 숲 사립을 가린 초집들도 보이구요.",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "다음 글의 시사점으로 적절하지 않은 것은?",
                      reference: "  기존의 의학적 연구는 건장한 성인 남성의 몸을 표준으로 삼아 이루어지는 경우가 많았다. 예를 들어 농약과 같은 화학 물질이 몸에 들어와 어떠한 변화를 일으키는지 검토한 연구에서 생리 주기에 따라 변화하는 여성 호르몬이 그 물질과 어떤 상호 작용을 일으킬 수 있는지는 고려되지 않았다. 자동차 충돌 사고를 인체 공학적으로 시뮬레이션할 때도 특정 연령대 남성의 몸이 연구 대상으로 사용되었고, 여성의 신체 특성이나 다양한 연령대 남성의 신체적 특성은 고려되지 않았다.\n  특정 연령대 성인 남성의 몸을 표준화된 인체로 여겼던 사고방식은 여러 문제점을 낳고 있다. 예를 들어 대사율, 피부와 조직 두께 등을 감안한, 사람이 가장 효과적으로 일할 수 있는 사무실 온도는 21°C로 알려져 있다. 그런데 한 연구에서 남성과 여성 직장인에게 각각 선호하는 사무실 온도를 조사한 결과는 남성은 평균 22°C, 여성은 평균 25°C였다. 남성은 기존의 적정 실내 온도에 가까운 답을 했고, 여성은 더 따뜻한 사무실에서 일하기를 원했다.\n  이러한 차이의 이유는 무엇일까? 현재 적정 사무실 온도로 알려진 21°C는 1960년대 측정된 자료를 바탕으로 하는데, 당시 몸무게 70kg인 40세 성인 남성을 기준으로 측정된 것이다. 이러한 ‘표준화된 신체’를 가진 남성의 대사율은 여성이나 다른 연령대 남성들의 대사율과 다르고, 당연히 체내 열 생산의 양도 차이가 있다.",
                      num1Text: "표준으로 삼은 대상이 나머지 대상의 특성까지 대표하지 못하므로 앞으로 의학적 연구를 하려면 하나의 표준을 정하기보다 가능한 한 다양한 대상을 선정해서 하는 것이 바람직하다.",
                      num2Text: "현재 우리가 알고 있는 의학 지식 중에는 특정 표준 대상만을 연구한 결과인 것이 있으므로 앞으로 이런 의학 지식을 활용하려면 연구한 대상을 살펴봐서 그대로 활용할지를 결정하는 것이 바람직하다.",
                      num3Text: "성별이나 연령대 등에 따라 신체 조건이 같지 않으므로 근무 환경을 조성할 때 근무자들의 성별이나 연령대를 고려하는 것이 바람직하다.",
                      num4Text: "기존의 사무실 적정 실내 온도가 조사된 것보다 낮게 설정되어 있으므로 향후에 모든 공공 기관의 사무실 온도를 조정할 때 현재보다 설정 온도를 일률적으로 높이는 것이 바람직하다.",
                      answer: 4),
        QuestionModel(num: 20,
                      questionText: "다음 글을 바탕으로 ㉠을 이해할 때 가장 적절한 것은?",
                      reference: "  나는 ㉠"+"‘연극에서의 관객의 공감’".underLined+"에 대해 강연한 일이 있다. 나는 관객이 공감하는 것을 직접 보여 주려고 시도했다. 먼저 나는 자원자가 있으면 나와서 배우처럼 읽어 주기를 청했다. 그리고 청중에게는 연극의 관객이 되어 들어 달라고 했다. 한 사람이 앞으로 나왔다. 나는 그에게 아우슈비츠를 소재로 한 드라마의 한 장면이 적힌 종이를 건네주었다. 자원자가 종이를 받아들고 그것을 훑어볼 때 청중들은 어수선했다. 그런데 자원자의 입에서 떨어진 첫 대사는 끔찍한 내용이었다. 아우슈비츠에 관한 적나라한 증언은 너무나 충격적이어서 청중들은 완전히 압도되었다. 자원자는 청중들의 얼어붙은 듯한 침묵 속에서 낭독을 계속했다. 자원자의 낭독은 세련되지도 능숙하지도 않았다. 그러나 관객들의 열렬한 공감을 이끌어 냈다. 과거 역사가 현재의 관객들에게 생생하게 공감되었다.\n  이것이 끝나고 이번에는 강연장에 함께 갔던 전문 배우에게 셰익스피어의 희곡 ｢헨리 5세｣에서 발췌한 대사를 낭독해 달라고 부탁했다. 그 대본은 400년 전 아젱쿠르 전투(백년 전쟁 당시 벌어졌던 영국과 프랑스의 치열한 전투)에서 처참하게 사망한 자들의 명단과 그 숫자를 나열한 것이었다. 그는 셰익스피어의 위대한 희곡임을 알아보자 품위 있고 고풍스럽게 큰 목소리로 낭독했다. 그는 유려한 어조로 전쟁에서 희생된 이들의 이름을 읽어 내려갔다. 그러나 청중들은 듣는 둥 마는 둥 했다. 갈수록 청중들은 낭독자 따위는 안중에도 없다는 듯이 행동했다. 그들에게 아젱쿠르 전투는 공감할 수 없는 것으로 분리된 것 같아 보였다. 앞서의 경우와는 전혀 다른 반응이었다.",
                      num1Text: "배우의 연기력이 관객의 공감을 좌우한다.",
                      num2Text: "비참한 죽음을 다룬 비극적인 소재는 관객의 공감을 일으킨다.",
                      num3Text: "훌륭한 고전이라고 해서 항상 청중의 공감을 불러일으킬 수 있는 것은 아니다.",
                      num4Text: "현재와 가까운 역사적 사실을 극화했다고 해서 관객의 공감 가능성이 커지지는 않는다.",
                      answer: 3),
        
        
        ]
        let exam = ExamModel(id: 202011, year: 2020, examTypeID: "국가직", subjectID: "국어", questions: questions)
        exams2020.append(exam)
    }
    func saveExam202012() {
        let questions = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오. [1~4]",
                      reference: "Extensive lists of microwave oven models and styles along with "+"candid".underLined+" customer reviews and price ranges are available at appliance comparison websites.",
                      num1Text: "frank",
                      num2Text: "logical",
                      num3Text: "implicit",
                      num4Text: "passionate",
                      answer: 1),
        QuestionModel(num: 2,
                      questionText: "",
                      reference: "It had been known for a long time that Yellowstone was volcanic in nature and the one thing about volcanoes is that they are generally "+"conspicuous.".underLined,
                      num1Text: "passive",
                      num2Text: "vaporous",
                      num3Text: "dangerous",
                      num4Text: "noticeable",
                      answer: 4),
        QuestionModel(num: 3,
                      questionText: "",
                      reference: "He’s the best person to tell you how to get there because he knows the city "+"inside out.".underLined,
                      num1Text: "eventually",
                      num2Text: "culturally",
                      num3Text: "thoroughly",
                      num4Text: "tentatively",
                      answer: 3),
        QuestionModel(num: 4,
                      questionText: "",
                      reference: "All along the route were thousands of homespun attempts to "+"pay tribute to".underLined+" the team, including messages etched in cardboard, snow and construction paper.",
                      num1Text: "honor",
                      num2Text: "compose",
                      num3Text: "publicize",
                      num4Text: "join",
                      answer: 1),
        QuestionModel(num: 5,
                      questionText: "어법상 옳은 것은?",
                      num1Text: "The traffic of a big city is busier than those of a small city.",
                      num2Text: "I’ll think of you when I’ll be lying on the beach next week.",
                      num3Text: "Raisins were once an expensive food, and only the wealth ate them.",
                      num4Text: "The intensity of a color is related to how much gray the color contains.",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "우리말을 영어로 가장 잘 옮긴 것은?",
                      num1Text: "몇 가지 문제가 새로운 회원들 때문에 생겼다.\n→Several problems have raised due to the new members.",
                      num2Text: "그 위원회는 그 건물의 건설을 중단하라고 명했다.\n→The committee commanded that construction of the building cease.",
                      num3Text: "그들은 한 시간에 40마일이 넘는 바람과 싸워야 했다.\n→They had to fight against winds that will blow over 40 miles an hour.",
                      num4Text: "거의 모든 식물의 씨앗은 혹독한 날씨에도 살아남는다.\n→The seeds of most plants are survived by harsh weather.",
                      answer: 2),
        QuestionModel(num: 7,
                      questionText: "우리말을 영어로 잘못 옮긴 것은?",
                      num1Text: "인간은 환경에 자신을 빨리 적응시킨다.\n→Human beings quickly adapt themselves to the environment.",
                      num2Text: "그녀는 그 사고 때문에 그녀의 목표를 포기할 수밖에 없었다.\n→She had no choice but to give up her goal because of the accident.",
                      num3Text: "그 회사는 그가 부회장으로 승진하는 것을 금했다.\n→The company prohibited him from promoting to vice-president.",
                      num4Text: "그 장난감 자동차를 조립하고 분리하는 것은 쉽다.\n→It is easy to assemble and take apart the toy car.",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "다음 글의 요지로 가장 적절한 것은?",
                      reference: "Listening to somebody else’s ideas is the one way to know whether the story you believe about the world―as well as about yourself and your place in it―remains intact. We all need to examine our beliefs, air them out and let them breathe. Hearing what other people have to say, especially about concepts we regard as foundational, is like opening a window in our minds and in our hearts. Speaking up is important. Yet to speak up without listening is like banging pots and pans together: even if it gets you attention, it’s not going to get you respect. There are three prerequisites for conversation to be meaningful: 1. You have to know what you’re talking about, meaning that you have an original point and are not echoing a worn-out, hand-me-down or pre-fab argument; 2. You respect the people with whom you’re speaking and are authentically willing to treat them courteously even if you disagree with their positions; 3. You have to be both smart and informed enough to listen to what the opposition says while handling your own perspective on the topic with uninterrupted good humor and discernment.",
                      num1Text: "We should be more determined to persuade others.",
                      num2Text: "We need to listen and speak up in order to communicate well.",
                      num3Text: "We are reluctant to change our beliefs about the world we see.",
                      num4Text: "We hear only what we choose and attempt to ignore different opinions.",
                      answer: 2),
        QuestionModel(num: 9,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "The future may be uncertain, but some things are undeniable: climate change, shifting demographics, geopolitics. The only guarantee is that there will be changes, both wonderful and terrible. It’s worth considering how artists will respond to these changes, as well as what purpose art serves, now and in the future. Reports suggest that by 2040 the impacts of human-caused climate change will be inescapable, making it the big issue at the centre of art and life in 20 years’ time. Artists in the future will wrestle with the possibilities of the post-human and post-Anthropocene―artificial intelligence, human colonies in outer space and potential doom. The identity politics seen in art around the #MeToo and Black Lives Matter movements will grow as environmentalism, border politics and migration come even more sharply into focus. Art will become increasingly diverse and might not ‘look like art’ as we expect. In the future, once we’ve become weary of our lives being visible online for all to see and our privacy has been all but lost, anonymity may be more desirable than fame. Instead of thousands, or millions, of likes and followers, we will be starved for authenticity and connection. Art could, in turn, become more collective and experiential, rather than individual.",
                      num1Text: "What will art look like in the future?",
                      num2Text: "How will global warming affect our lives?",
                      num3Text: "How will artificial intelligence influence the environment?",
                      num4Text: "What changes will be made because of political movements?",
                      answer: 1),
        QuestionModel(num: 10,
                      questionText: "다음 글의 내용과 일치하지 않는 것은?",
                      reference: "The Second Amendment of the U.S. Constitution states: “A well-regulated Militia, being necessary to the security of a free State, the right of the people to keep and bear Arms, shall not be infringed.” Supreme Court rulings, citing this amendment, have upheld the right of states to regulate firearms. However, in a 2008 decision confirming an individual right to keep and bear arms, the court struck down Washington, D.C. laws that banned handguns and required those in the home to be locked or disassembled. A number of gun advocates consider ownership a birthright and an essential part of the nation’s heritage. The United States, with less than 5 percent of the world’s population, has about 35～50 percent of the world’s civilian-owned guns, according to a 2007 report by the Switzerland-based Small Arms Survey. It ranks number one in firearms per capita. The United States also has the highest homicide-by-firearm rate among the world’s most developed nations. But many gun-rights proponents say these statistics do not indicate a cause-and-effect relationship and note that the rates of gun homicide and other gun crimes in the United States have dropped since highs in the early 1990’s.",
                      num1Text: "In 2008, the U.S. Supreme Court overturned Washington, D.C. laws banning handguns",
                      num2Text: "Many gun advocates claim that owning guns is a natural-born right.",
                      num3Text: "Among the most developed nations, the U.S. has the highest rate of gun homicides.",
                      num4Text: "Gun crimes in the U.S. have steadily increased over the last three decades.",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "두 사람의 대화 중 가장 어색한 것은?",
                      num1Text: "A:When is the payment due?\nB:You have to pay by next week.",
                      num2Text: "A:Should I check this baggage in?\nB:No, it’s small enough to take on the plane.",
                      num3Text: "A:When and where shall we meet?\nB:I’ll pick you up at your office at 8:30.",
                      num4Text: "A:I won the prize in a cooking contest.\nB:I couldn’t have done it without you.",
                      answer: 4),
        QuestionModel(num: 12,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "A:Thank you for calling the Royal Point Hotel Reservations Department. My name is Sam. How may I help you?\n\nB:Hello, I’d like to book a room.\n\nA:We offer two room types: the deluxe room and the luxury suite.\n\nB:_________________________________?\n\nA:For one, the suite is very large. In addition to a bedroom, it has a kitchen, living room and dining room.\n\nB:It sounds expensive.\n\nA:Well, it’s $200 more per night.\n\nB:In that case, I’ll go with the deluxe room.",
                      num1Text: "Do you need anything else",
                      num2Text: "May I have the room number",
                      num3Text: "What’s the difference between them",
                      num4Text: "Are pets allowed in the rooms",
                      answer: 3),
        QuestionModel(num: 13,
                      questionText: "밑줄 친 (A), (B)에 들어갈 말로 가장 적절한 것은?",
                      reference: "Advocates of homeschooling believe that children learn better when they are in a secure, loving environment. Many psychologists see the home as the most natural learning environment, and originally the home was the classroom, long before schools were established. Parents who homeschool argue that they can monitor their children’s education and give them the attention that is lacking in a traditional school setting. Students can also pick and choose what to study and when to study, thus enabling them to learn at their own pace. [ (A) ], critics of homeschooling say that children who are not in the classroom miss out on learning important social skills because they have little interaction with their peers. Several studies, though, have shown that the home-educated children appear to do just as well in terms of social and emotional development as other students, having spent more time in the comfort and security of their home, with guidance from parents who care about their welfare. [ (B) ], many critics of homeschooling have raised concerns about the ability of parents to teach their kids effectively.",
                      num1Text: "Therefore - Nevertheless",
                      num2Text: "In contrast - In spite of this",
                      num3Text: "Therefore - Contrary to that",
                      num4Text: "In contrast - Furthermore",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "다음 글의 주제로 가장 적절한 것은?",
                      reference: "For many people, work has become an obsession. It has caused burnout, unhappiness and gender inequity, as people struggle to find time for children or passions or pets or any sort of life besides what they do for a paycheck. But increasingly, younger workers are pushing back. More of them expect and demand flexibility―paid leave for a new baby, say, and generous vacation time, along with daily things, like the ability to work remotely, come in late or leave early, or make time for exercise or meditation. The rest of their lives happens on their phones, not tied to a certain place or time―why should work be any different?",
                      num1Text: "ways to increase your paycheck",
                      num2Text: "obsession for reducing inequity",
                      num3Text: "increasing call for flexibility at work",
                      num4Text: "advantages of a life with long vacations",
                      answer: 3),
        QuestionModel(num: 15,
                      questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "Past research has shown that experiencing frequent psychological stress can be a significant risk factor for cardiovascular disease, a condition that affects almost half of those aged 20 years and older in the United States.\n(A)Does this mean, though, that people who drive on a daily basis are set to develop heart problems, or is there a simple way of easing the stress of driving?\n\n(B)According to a new study, there is. The researchers noted that listening to music while driving helps relieve the stress that affects heart health.\n\n(C)One source of frequent stress is driving, either due to the stressors associated with heavy traffic or the anxiety that often accompanies inexperienced drivers.",
                      num1Text: "(A)－(C)－(B)",
                      num2Text: "(B)－(A)－(C)",
                      num3Text: "(C)－(A)－(B)",
                      num4Text: "(C)－(B)－(A)",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "다음 글의 흐름상 가장 어색한 문장은?",
                      reference: "When the brain perceives a threat in the immediate surroundings, it initiates a complex string of events in the body. It sends electrical messages to various glands, organs that release chemical hormones into the bloodstream. Blood quickly carries these hormones to other organs that are then prompted to do various things. ①"+"The adrenal glands above the kidneys, for example, pump out adrenaline, the body’s stress hormone.".underLined+" ②"+"Adrenaline travels all over the body doing things such as widening the eyes to be on the lookout for signs of danger, pumping the heart faster to keep blood and extra hormones flowing, and tensing the skeletal muscles so they are ready to lash out at or run from the threat.".underLined+" ③"+"The whole process is called the fight-or-flight response, because it prepares the body to either battle or run for its life.".underLined+" ④"+"Humans consciously control their glands to regulate the release of various hormones.".underLined+" Once the response is initiated, ignoring it is impossible, because hormones cannot be reasoned with.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 17,
                      questionText: "주어진 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "It was then he remembered his experience with the glass flask, and just as quickly, he imagined that a special coating might be applied to a glass windshield to keep it from shattering.",
                      reference2: "In 1903 the French chemist, Edouard Benedictus, dropped a glass flask one day on a hard floor and broke it. (①) However, to the astonishment of the chemist, the flask did not shatter, but still retained most of its original shape. (②) When he examined the flask he found that it contained a film coating inside, a residue remaining from a solution of collodion that the flask had contained. (③) He made a note of this unusual phenomenon, but thought no more of it until several weeks later when he read stories in the newspapers about people in automobile accidents who were badly hurt by flying windshield glass. (④) Not long thereafter, he succeeded in producing the world’s first sheet of safety glass.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "다음 글의 내용과 일치하지 않는 것은?",
                      reference: "Dubrovnik, Croatia, is a mess. Because its main attraction is its seaside Old Town surrounded by 80-foot medieval walls, this Dalmatian Coast town does not absorb visitors very well. And when cruise ships are docked here, a legion of tourists turn Old Town into a miasma of tank-top-clad tourists marching down the town’s limestone-blanketed streets. Yes, the city of Dubrovnik has been proactive in trying to curb cruise ship tourism, but nothing will save Old Town from the perpetual swarm of tourists. To make matters worse, the lure of making extra money has inspired many homeowners in Old Town to turn over their places to Airbnb, making the walled portion of town one giant hotel. You want an “authentic” Dubrovnik experience in Old Town, just like a local? You’re not going to find it here. Ever.",
                      num1Text: "Old Town은 80피트 중세 시대 벽으로 둘러싸여 있다.",
                      num2Text: "크루즈 배가 정박할 때면 많은 여행객이 Old Town 거리를 활보한다.",
                      num3Text: "Dubrovnik 시는 크루즈 여행을 확대하려고 노력해 왔다.",
                      num4Text: "Old Town에서는 많은 집이 여행객 숙소로 바뀌었다.",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "밑줄 친 (A), (B)에 들어갈 말로 가장 적절한 것은?",
                      reference: "When an organism is alive, it takes in carbon dioxide from the air around it. Most of that carbon dioxide is made of carbon-12, but a tiny portion consists of carbon-14. So the living organism always contains a very small amount of radioactive carbon, carbon-14. A detector next to the living organism would record radiation given off by the carbon-14 in the organism. When the organism dies, it no longer takes in carbon dioxide. No new carbon-14 is added, and the old carbon-14 slowly decays into nitrogen. The amount of carbon-14 slowly [ (A) ] as time goes on. Over time, less and less radiation from carbon-14 is produced. The amount of carbon-14 radiation detected for an organism is a measure, therefore, of how long the organism has been [ (B) ]. This method of determining the age of an organism is called carbon-14 dating. The decay of carbon-14 allows archaeologists to find the age of once-living materials. Measuring the amount of radiation remaining indicates the approximate age.",
                      num1Text: "decreases - dead",
                      num2Text: "increases - alive",
                      num3Text: "decreases - productive",
                      num4Text: "increases - inactive",
                      answer: 1),
        QuestionModel(num: 20,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "All creatures, past and present, either have gone or will go extinct. Yet, as each species vanished over the past 3.8-billion-year history of life on Earth, new ones inevitably appeared to replace them or to exploit newly emerging resources. From only a few very simple organisms, a great number of complex, multicellular forms evolved over this immense period. The origin of new species, which the nineteenth-century English naturalist Charles Darwin once referred to as “the mystery of mysteries,” is the natural process of speciation responsible for generating this remarkable _________________ with whom humans share the planet. Although taxonomists presently recognize some 1.5 million living species, the actual number is possibly closer to 10 million. Recognizing the biological status of this multitude requires a clear understanding of what constitutes a species, which is no easy task given that evolutionary biologists have yet to agree on a universally acceptable definition.",
                      num1Text: "technique of biologists",
                      num2Text: "diversity of living creatures",
                      num3Text: "inventory of extinct organisms",
                      num4Text: "collection of endangered species",
                      answer: 2),
        
        ]
        let exam = ExamModel(id: 202012, year: 2020, examTypeID: "국가직", subjectID: "영어", questions: questions)
        exams2020.append(exam)
    }
    func saveExam202013() {
        let questions = [
        QuestionModel(num: 1,
                      questionText: "(가) 시기의 생활상에 대한 설명으로 옳은 것은?",
                      reference: "1935년 두만강 가의 함경북도 종성군 동관진에서 한반도 최초로 (가) 시대 유물인 석기와 골각기 등이 발견되었다. 발견 당시 일본에서는 (가)시대 유물이 출토되지 않은 상황이었다.",
                      num1Text: "반달 돌칼을 이용하여 벼를 수확하였다.",
                      num2Text: "넓적한 돌 갈판에 옥수수를 갈아서 먹었다.",
                      num3Text: "사냥이나 물고기잡이 등을 통해 식량을 얻었다.",
                      num4Text: "영혼 숭배 사상이 있어 사람이 죽으면 흙 그릇 안에 매장하였다.",
                      answer: 3),
        QuestionModel(num: 2,
                      questionText: "(가) 인물에 대한 설명으로 옳은 것은?",
                      reference: "신종 원년 사노비 만적 등이 북산에서 땔나무를 하다가 공사의 노비들을 모아 모의하기를, “우리가 성 안에서 봉기하여 먼저 [ (가) ]등을 죽인다. 이어서 각각 자신의 주인을 죽이고 천적(賤籍)을 불태워 삼한에서 천민을 없게 하자. 그러면 공경장상이라도 우리가 모두 할 수 있을 것이다.”라고 하였다.",
                      num1Text: "정방을 설치하여 인사권을 장악하였다.",
                      num2Text: "치안유지를 위해 야별초를 설립하였다.",
                      num3Text: "이의방을 제거하고 권력을 장악하였다.",
                      num4Text: "봉사십조를 올려 사회개혁안을 제시하였다.",
                      answer: 4),
        QuestionModel(num: 3,
                      questionText: "조선 전기 문화에 대한 설명으로 옳은 것은?",
                      num1Text: "〖어우야담〗을 비롯한 야담․잡기류가 성행하였다.",
                      num2Text: "유서(類書)로 불리는 백과사전이 널리 편찬되었다.",
                      num3Text: "〖동문선〗이 편찬되어 우리 문학의 독자성을 강조하였다.",
                      num4Text: "중인층을 중심으로 시사가 결성되어 문학 활동을 벌였다.",
                      answer: 3),
        QuestionModel(num: 4,
                      questionText: "다음 자료에 나타난 사상에 대한 설명으로 옳은 것은?",
                      reference: "군신, 부자, 부부, 붕우, 장유의 윤리는 인간의 본성에 부여된 것으로서 천지를 통하는 만고불변의 이치이고, 위에 존재하는 것으로서 도(道)가 됩니다. 이에 대해 배, 수레, 군사, 농사, 기계가 국민에게 편리하고 나라에 이롭게 하는 것은 외형적인 것으로서 기(器)가 됩니다. 신이 변혁을 꾀하고자 하는 것은 기(器)이지 도(道)가 아닙니다.",
                      num1Text: "왜양일체론(倭洋一體論)을 주장하였다.",
                      num2Text: "근대 문물 수용의 사상적 기반이 되었다.",
                      num3Text: "갑신정변 주도 세력의 견해를 대변하였다.",
                      num4Text: "우등한 사회가 열등한 사회를 지배하는 것이 당연하다고 보았다.",
                      answer: 2),
        QuestionModel(num: 5,
                      questionText: "(가)에 들어갈 기관으로 옳은 것은?",
                      reference: "5월에 조서를 내리기를 “개경 내의 사람들이 역질에 걸렸으니 마땅히 [ (가) ]을/를 설치하여 이들을 치료하고, 또한 시신과 유골은 거두어 묻어서 비바람에 드러나지 않게 할 것이며, 신하를 보내어 동북도와 서남도의 굶주린 백성을 진휼하라.”라고 하였다.\n\n－〖고려사〗－",
                      num1Text: "의창",
                      num2Text: "제위보",
                      num3Text: "혜민국",
                      num4Text: "구제도감",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 ‘이 지역’에 대한 설명으로 옳은 것은?",
                      reference: "장수왕은 군사 3만을 거느리고 백제를 침공하여 왕도인 "+"이 지역".underLined+"을 함락시켜, 개로왕을 살해하고 남녀 8천 명을 사로잡아 갔다.",
                      num1Text: "망이, 망소이가 반란을 일으켰다.",
                      num2Text: "고려 문종 대에 남경이 설치되었다.",
                      num3Text: "보조국사 지눌이 수선사 결사를 주도하였다.",
                      num4Text: "고려 태조가 북진 정책의 전진 기지로 삼았다.",
                      answer: 2),
        QuestionModel(num: 7,
                      questionText: "다음 사건이 일어난 왕의 재위 기간에 있었던 사실로 옳은 것은?",
                      reference: "그들 조선군은 비상한 용기를 가지고 응전하면서 성벽에 올라 미군에게 돌을 던졌다. 창칼로 상대하는데 창칼이 없는 병사들은 맨손으로 흙을 쥐어 적군 눈에 뿌렸다. 모든 것을 각오하고 한 걸음 한 걸음 다가드는 적군에게 죽기로 싸우다 마침내 총에 맞아 죽거나 물에 빠져 죽었다.",
                      num1Text: "군포에 대한 양반들의 면세특권이 폐지되었다.",
                      num2Text: "금난전권을 제한하려는 통공정책이 시작되었다.",
                      num3Text: "결작세가 신설되면서 지주들의 부담이 증가하였다.",
                      num4Text: "영정법이 제정되어 복잡한 전세 방식이 일원화되었다.",
                      answer: 1),
        QuestionModel(num: 8,
                      questionText: "(가)～(라)에 해당하는 사실로 옳지 않은 것은?",
                      imgModel: ImageModel(imageString: "202013-8", imgWidth: 330, imgHeight: 100),
                      num1Text: "(가)－백제 침류왕이 불교를 받아들였다.",
                      num2Text: "(나)－고구려 영양왕이 요서 지방을 선제공격하였다.",
                      num3Text: "(다)－백제가 신라 대야성을 공격하여 함락시켰다.",
                      num4Text: "(라)－신라가 매소성에서 당군을 격파하였다.",
                      answer: 4),
        QuestionModel(num: 9,
                      questionText: "밑줄 친 ‘이 책’에 대한 설명으로 옳은 것은?",
                      reference: "신(臣)이 "+"이 책".underLined+"을 편수하여 바치는 것은 …(중략)… 중국은 반고부터 금국에 이르기까지, 동국은 단군으로부터 본조(本朝)에 이르기까지 처음 일어나게 된 근원을 간책에서 다 찾아보아 같고 다른 것을 비교하여 요점을 취하고 읊조림에 따라 장을 이루었습니다.",
                      num1Text: "성리학적 유교 사관이 반영되어 대의명분을 강조하였다.",
                      num2Text: "국왕, 훈신, 사림이 서로 합의하여 통사체계를 구성하였다.",
                      num3Text: "원 간섭기에 중국과 구별되는 우리 역사의 독자성을 강조하였다.",
                      num4Text: "왕명으로 단군조선에서 고려 말까지의 역사를 노래 형식으로 정리하였다.",
                      answer: 3),
        QuestionModel(num: 10,
                      questionText: "다음 그래프에 표시된 시기에 일어난 사회 현상으로 옳지 않은 것은?",
                      imgModel: ImageModel(imageString: "202013-10", imgWidth: 330, imgHeight: 200),
                      num1Text: "해외로부터 귀환인이 급증하여 식량이 부족했다.",
                      num2Text: "38도선 분할 점령 이후 식료품 부문의 생산이 크게 위축되었다.",
                      num3Text: "미군정이 재정적자를 메우기 위해 화폐를 과도하게 발행했다.",
                      num4Text: "미곡수집제 폐지, 토지개혁 실시를 주장하는 대규모 시위가 일어났다.",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 ‘왕’의 재위 기간에 있었던 사실로 옳은 것은?",
                      reference: "나라 안의 여러 군현에서 공부(貢賦)를 바치지 않으니 창고가 비어 버리고 나라의 쓰임이 궁핍해졌다. 왕이 사신을 보내어 독촉하자, 이로 말미암아 곳곳에서 도적이 벌떼처럼 일어났다. 이때 원종과 애노 등이 사벌주에 웅거하여 반란을 일으켰다.",
                      num1Text: "발해가 멸망하였다.",
                      num2Text: "국학을 설치하였다.",
                      num3Text: "최치원이 시무책 10여 조를 건의하였다.",
                      num4Text: "장보고의 건의에 따라 청해진이 설치되었다.",
                      answer: 3),
        QuestionModel(num: 12,
                      questionText: "독도가 대한민국의 영토임을 알 수 있는 자료로 옳은 것만을 모두 고르면?",
                      reference: "ㄱ.일본의 은주시청합기(1667년)\nㄴ.일본의 삼국접양지도(1785년)\nㄷ.일본의 태정관 지령문(1877년)\nㄹ.일본의 시마네현 고시(1905년)",
                      num1Text: "ㄱ, ㄴ, ㄷ",
                      num2Text: "ㄱ, ㄴ, ㄹ",
                      num3Text: "ㄱ, ㄷ, ㄹ",
                      num4Text: "ㄴ, ㄷ, ㄹ",
                      answer: 1),
        QuestionModel(num: 13,
                      questionText: "(가)에 대한 설명으로 옳은 것은?",
                      reference: "문화통치의 일환으로 한글 신문의 발행이 허용되었다. 이에 따라 [ (가) ]이/가 창간되었다. [ (가) ]은/는 자치운동을 모색하던 이광수의 ｢민족적 경륜｣을 실어 비판받기도 하였으나, ‘일장기 말소사건’으로 일제로부터 정간 처분을 받기도 하였다.",
                      num1Text: "한글 보급 운동에 앞장서 〖한글원본〗을 만들었다.",
                      num2Text: "브나로드 운동이라는 농촌 계몽 운동을 전개하였다.",
                      num3Text: "〖개벽〗, 〖신여성〗, 〖어린이〗 등의 잡지를 발행하였다.",
                      num4Text: "신간회가 결성되자 신간회 본부와 같은 역할을 하게 되었다.",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "(가) 인물에 대한 설명으로 옳은 것은?",
                      reference: "김춘추가 당나라에 들어가 군사 20만을 요청해 얻고 돌아와서 [ (가) ]을/를 보며 말하기를, “죽고 사는 것이 하늘의 뜻에 달렸는데, 살아 돌아와 다시 공과 만나게 되니 얼마나 다행한 일입니까?”라고 하였다. 이에 [ (가) ]이/가 대답하기를, “저는 나라의 위엄과 신령함에 의지하여 두 차례 백제와 크게 싸워 20 성을 빼앗고 3만여 명을 죽이거나 사로잡았습니다. 그리고 품석 부부의 유골이 고향으로 되돌아왔으니 천행입니다.”라고 하였다.\n\n－〖삼국사기〗－",
                      num1Text: "황산벌에서 백제군을 물리쳤다.",
                      num2Text: "화랑이 지켜야 할 세속오계를 제시하였다.",
                      num3Text: "진덕여왕의 뒤를 이어 신라왕으로 즉위하였다.",
                      num4Text: "당에서 숙위 활동을 하다가 부대총관이 되어 신라로 돌아왔다.",
                      answer: 1),
        QuestionModel(num: 15,
                      questionText: "(가), (나) 신분층에 대한 설명으로 옳지 않은 것은?",
                      reference: "오래도록 막혀 있으면 반드시 터놓아야 하고, 원한은 쌓이면 반드시 풀어야 하는 것이 하늘의 이치다. [ (가) ]와/과 [ (나) ]에게 벼슬길이 막히게 된 것은 우리나라의 편벽된 일로 이제 몇백 년이 되었다. [ (가) ]은/는 다행히 조정의 큰 성덕을 입어 문관은 승문원, 무관은 선전관에 임명되고 있다. 그런데도 우리들 [ (나) ]은/는 홀로 이 은혜를 함께 입지 못하니 어찌 탄식조차 없겠는가?",
                      num1Text: "(가)의 신분 상승 운동은 (나)에게 자극을 주었다.",
                      num2Text: "(가)는 수차례에 걸친 집단 상소를 통해 관직 진출의 제한을 없애 줄 것을 요구하였다.",
                      num3Text: "(나)에 해당하는 인물로는 정조 때 규장각 검서관으로 등용된 유득공, 박제가, 이덕무 등이 있다.",
                      num4Text: "(나)는 주로 기술직에 종사하며 축적한 재산과 탄탄한 실무 경력을 바탕으로 신분 상승을 추구하였다.",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "다음 자료에 나타난 사상에 대한 설명으로 옳은 것은?",
                      reference: "사람이 곧 하늘이라. 그러므로 사람은 평등하며 차별이 없나니, 사람이 마음대로 귀천을 나눔은 하늘을 거스르는 것이다. 우리 도인은 차별을 없애고 선사의 뜻을 받들어 생활하기를 바라노라.",
                      num1Text: "이 사상에 대해 순조 즉위 이후 대탄압이 가해졌다.",
                      num2Text: "이 사상을 바탕으로 〖동경대전〗과 〖용담유사〗가 편찬되었다.",
                      num3Text: "이 사상을 근거로 몰락한 양반의 지휘 아래 평안도에서 난이 일어났다.",
                      num4Text: "이 사상을 근거로 단성에서 시작된 농민봉기는 진주로 이어졌다.",
                      answer: 2),
        QuestionModel(num: 17,
                      questionText: "다음은 우리나라 경제성장 과정을 시간순으로 나열한 것이다. (가)에 들어갈 내용으로 옳은 것은?",
                      reference: " 수출액 100억 달러를 돌파했다.\n   ⬇︎\n제2차 석유 파동으로 경제가 침체에 빠지다.\n   ⬇︎\n   (가)\n   ⬇︎\n경제 협력 기구에 가입하다.",
                      num1Text: "제3차 경제개발 5개년 계획이 실시되다.",
                      num2Text: "저금리, 저유가, 저달러의 3저 호황을 경험하다.",
                      num3Text: "베트남 파병을 시작하고 ｢브라운 각서｣를 체결하다.",
                      num4Text: "일본과 대일 청구권 문제에 합의하고 ｢한일 기본 조약｣을 체결하다.",
                      answer: 2),
        QuestionModel(num: 18,
                      questionText: "다음 법령이 실시된 기간에 있었던 사실로 옳은 것은?",
                      reference: "제1조 국체를 변혁 또는 사유재산제를 부인할 목적으로 결사를 조직하거나 그 정을 알고 이에 가입하는 자는 10년 이하의 징역 또는 금고에 처함\n\n제2조 전조의 제1항의 목적으로 그 목적한 사항의 실행에 관하여 협의한 자는 7년 이하의 징역 또는 금고에 처함",
                      num1Text: "｢조선 태형령｣이 공포되었다.",
                      num2Text: "경성 제국 대학이 설립되었다.",
                      num3Text: "물산 장려 운동이 시작되었다.",
                      num4Text: "학도 지원병 제도가 실시되었다.",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "다음 사실이 있었던 시기의 향촌사회에 대한 설명으로 옳지 않은 것은?",
                      reference: "황해도 봉산 사람 이극천이 향전(鄕戰) 때문에 투서하여 그와 알력이 있는 사람들을 무고하였는데, 내용이 감히 말할 수 없는 문제에 저촉되었다.",
                      num1Text: "향전의 전개 속에서 수령의 권한이 강화되었다.",
                      num2Text: "신향층은 수령과 그를 보좌하는 향리층과 결탁하였다.",
                      num3Text: "수령은 경재소와 유향소를 연결하여 지방통치를 강화하였다.",
                      num4Text: "재지사족은 동계와 동약을 통해 향촌사회에 대한 영향력을 유지하려 하였다.",
                      answer: 3),
        QuestionModel(num: 20,
                      questionText: "다음 자료가 발표된 이후의 사실에 해당하지 않는 것은?",
                      reference: "우리는 3천만 한국 인민과 정부를 대표하여 삼가 중․영․미․소․캐나다 기타 제국의 대일 선전이 일본을 격패케 하고 동아를 재건하는 가장 유효한 수단이 됨을 축하하여 이에 특히 다음과 같이 성명한다.\n1. 한국 전 인민은 현재 이미 반침략 전선에 참가하였으니 한 개의 전투 단위로서 추축국에 선전한다.\n\n2. 1910년의 합방 조약과 일체의 불평등 조약의 무효를 거듭 선포하며 아울러 반(反) 침략 국가인 한국에 있어서의 합리적 기득권익을 존중한다.\n…(중략)…\n5.루스벨트․처어칠 선언의 각조를 견결히 주장하며 한국 독립을 실현키 위하여 이것을 적용하여 민주 진영의 최후 승리를 축원한다.",
                      num1Text: "한국광복군은 김원봉이 이끌던 조선의용대의 병력을 통합하였다.",
                      num2Text: "영국군의 요청에 따라 인도, 미얀마 전선에 한국광복군이 파견되었다.",
                      num3Text: "조선독립동맹은 조선의용대 화북지대를 기반으로 조선의용군을 조직하였다.",
                      num4Text: "대한민국 임시 정부는 김구를 주석으로 하는 단일 지도 체제를 만들고 ｢대한민국 건국 강령｣을 제정하였다.",
                      answer: 4),
        ]
        let exam = ExamModel(id: 202013, year: 2020, examTypeID: "국가직", subjectID: "한국사", questions: questions)
        exams2020.append(exam)
    }
    //지방직
    func saveExam202021() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "다음에 해당하는 사례로 적절하지 않은 것은?",
                      reference: "  ‘역전앞’과 마찬가지로 ‘피해(被害)를 당하다’에도 의미의 중복이 나타난다. ‘피해’의 ‘피(被)’에 이미 ‘당하다’라는 의미가 포함되어 있기 때문이다.",
                      num1Text: "형"+"부터 먼저".underLined+" 해라.",
                      num2Text: "채훈이는 "+"오로지 빵만".underLined+" 좋아한다.",
                      num3Text: "발언자"+"마다 각각".underLined+" 다른 주장을 편다.",
                      num4Text: "그는 예의가 바를 "+"뿐더러 무척".underLined+" 부지런하다.",
                      answer: 4),
        QuestionModel(num: 2,
                      questionText: "다음 대화에서 밑줄 친 부분의 표현 효과에 대한 설명으로 적절한 것은?",
                      reference: "  김 대리: 늦어서 죄송합니다. 일이 좀 많았습니다.\n  이 부장: "+"괜찮아요. 오랜만에 최 대리하고 오붓하게 대화도 나누고 시간 가는 줄 몰랐네요. 허허허.".underLined+"\n  김 대리: 박 부장님은 오늘 못 나오신다고 전해 달라셨어요.\n  이 부장: 그럼, 우리끼리 출발합시다.",
                      num1Text: "자신과 상대방의 의견 차이를 최소화한다.",
                      num2Text: "상대방에게 부담이 되는 표현을 최소화한다.",
                      num3Text: "화자 자신에게 혜택을 주는 표현을 최소화한다.",
                      num4Text: "상대방에 대한 비방을 최소화하고 칭찬을 최대화한다.",
                      answer: 2),
        QuestionModel(num: 3,
                      questionText: "‘청소년 인터넷 중독의 현황과 문제 해결’에 대한 글을 작성하고자 한다. 글의 내용으로 포함하기에 적절하지 않은 것은?",
                      num1Text: "국내 최대 게임 업체의 고객 개인 정보가 유출되어 청소년들에게 성인 광고 문자가 대량 발송된 사건을 예로 제시한다.",
                      num2Text: "인터넷에 중독되는 청소년의 비율이 해마다 증가한다는 통계를 활용하여 해당 사안이 시급히 해결되어야 할 문제임을 강조한다.",
                      num3Text: "사회성 결여, 의사소통 장애, 집중력 저하 등 인터넷 중독이 야기할 수 있는 부정적 현상들을 열거하여 문제의 심각성을 환기한다.",
                      num4Text: "청소년 대상 인터넷 중독 상담 프로그램의 개발 및 운영을 위해 할당된 예산이 부족하다는 전문가의 의견을 인용하여 해당 문제에 대한 대처가 미온적임을 지적한다.",
                      answer: 1),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 단어의 쓰임이 옳은 것은?",
                      num1Text: "하노라고".underLined+" 한 것이 이 모양이다.",
                      num2Text: "물품 대금은 나중에 예치금에서 자동으로 "+"결재된다.".underLined,
                      num3Text: "예산을 대충 "+"걷잡아서".underLined+" 말하지 말고 잘 뽑아 보세요.",
                      num4Text: "행운이 가득하기를 기원하는 것으로 치사를 "+"가름합니다.".underLined,
                      answer: 1),
        QuestionModel(num: 5,
                      questionText: "다음 시에 대한 감상으로 적절하지 않은 것은?",
                      reference: "  네 집에서 그 샘으로 가는 길은 한 길이었습니다. 그래서 새벽이면 물 길러 가는 인기척을 들을 수 있었지요. 서로 짠 일도 아닌데 새벽 제일 맑게 고인 물은 네 집이 돌아가며 길어 먹었지요. 순번이 된 집에서 물 길어 간 후에야 똬리 끈 입에 물고 삽짝 들어서시는 어머니나 물지게 진 아버지 모습을 볼 수 있었지요. 집안에 일이 있으면 그 순번이 자연스럽게 양보되기도 했었구요. 넉넉하지 못한 물로 사람들 마음을 넉넉하게 만들던 그 샘가 미나리꽝에서는 미나리가 푸르고 앙금 내리는 감자는 잘도 썩어 구린내 훅 풍겼지요.\n\n－함민복, ｢그 샘｣－",
                      num1Text: "‘샘’을 매개로 공동체의 삶을 표현했다.",
                      num2Text: "과거 시제로 회상의 분위기를 표현했다.",
                      num3Text: "공감각적 이미지로 이웃 간의 배려를 표현했다.",
                      num4Text: "구어체로 이웃 간의 정감 어린 분위기를 표현했다.",
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "다음 글의 주장으로 가장 적절한 것은?",
                      reference: "  우리에게 친숙한 동물들의 사소한 행동을 살펴보면 그들이 자신의 환경을 개조한다는 것을 알 수 있다. 가장 단순한 생명체는 먹이가 그들에게 헤엄쳐 오게 만들고, 고등동물은 먹이를 구하기 위해 땅을 파거나 포획 대상을 추적하기도 한다. 이처럼 동물들은 자신의 목적을 위해 행동함으로써 환경을 변형시킨다. 이러한 생존 방식을 흔히 환경에 적응하는 것으로 설명한다. 그러나 이러한 설명은 생명체들이 그들의 환경 개변(改變)에 능동적으로 행동한다는 중요한 사실을 놓치고 있다.\n  가장 고등한 동물인 인간도 다른 생명체와 마찬가지로 생존이나 적응을 넘어서 환경에 대해 적극성을 보인다. 이는 인간의 세 가지 충동－사는 것, 잘 사는 것, 더 잘 사는 것－으로 인하여 가능하다. 잘 살기 위한 노력은 순응적이기보다는 능동적인 모습으로 나타나게 된다. 인간도 생명체이다. 더 잘 살기 위해서는 환경에 순응할 수만은 없다.",
                      num1Text: "인간은 환경에 적응해 왔다.",
                      num2Text: "삶의 기술은 생존을 위한 것이다.",
                      num3Text: "생명체는 환경을 능동적으로 변형한다.",
                      num4Text: "인간은 잘 사는 것을 삶의 목표로 한다.",
                      answer: 3),
        QuestionModel(num: 7,
                      questionText: "밑줄 친 부분의 활용형이 옳지 않은 것은?",
                      num1Text: "집에 오면 그는 항상 사랑채에 "+"머물었다.".underLined,
                      num2Text: "나는 고향 집에 한 사나흘 "+"머무르면서".underLined+" 쉴 생각이다.",
                      num3Text: "일에 "+"서툰".underLined+" 것은 연습이 부족한 까닭이다.",
                      num4Text: "그는 외국어가 "+"서투르므로".underLined+" 해외 출장을 꺼린다.",
                      answer: 1),
        QuestionModel(num: 8,
                      questionText: "다음에 서술된 A사의 상황을 가장 적절하게 표현한 한자성어는?",
                      reference: "  최근 출시된 A사의 신제품이 뜨거운 호응을 얻고 있다. 이번 신제품의 성공으로 A사는 B사에게 내주었던 업계 1위 자리를 탈환했다. ",
                      num1Text: "兎死狗烹",
                      num2Text: "捲土重來",
                      num3Text: "手不釋卷",
                      num4Text: "我田引水",
                      answer: 2),
        QuestionModel(num: 9,
                      questionText: "다음 글의 주장으로 가장 적절한 것은?",
                      reference: "  예술 작품의 복제 기술이 좋아지고 있음에도 불구하고 원본을 보러 가는 이유는 무엇인가? 예술 작품의 특성상 원본 고유의 예술적 속성을 복제본에서는 느낄 수 없다고 생각하는 경향이 강하기 때문이다. 사진은 원본인지 복제본인지 중요하지 않지만, 회화는 붓 자국 하나하나가 중요하기 때문에 복제본이 원본을 대체할 수 없다고 생각하는 사람들이 많다.\n  그러나 이러한 생각은 잘못이다. 회화와 달리 사진의 경우, 보통은 ‘그 작품’이라고 지칭되는 사례들이 여러 개 있을 수 있다. 20세기 위대한 사진작가 빌 브란트가 마음만 먹었다면, 런던에 전시한 인화본의 조도를 더 낮추는 방식으로 다른 곳에 전시한 것과 다른 예술적 속성을 갖게 할 수 있었을 것이다. 이것은 사진의 경우, 작가가 재현적 특질을 선택하고 변형할 수 있는 방법이 다양함을 의미한다.",
                      num1Text: "복제본의 예술적 가치는 원본을 뛰어넘을 수 없다.",
                      num2Text: "복제 기술 덕분에 예술의 매체적 특성이 비슷해졌다.",
                      num3Text: "복제본의 재현적 특질을 변형하는 방법은 제한적이다.",
                      num4Text: "복제본도 원본과는 다른 별개의 예술적 특성을 담보할 수 있다.",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "밑줄 친 단어와 바꿔 쓸 수 있는 한자어로 가장 적절한 것은?",
                      num1Text: "그는 가수가 되려는 꿈을 "+"버리고".underLined+" 직장을 구했다.\n→遺棄하고",
                      num2Text: "휴가철인 7～8월에 "+"버려지는".underLined+" 반려견들이 가장 많다.\n→根絶되는",
                      num3Text: "그는 집 앞에 몰래 쓰레기를 "+"버리고".underLined+" 간 사람을 찾고 있다.\n→投棄하고",
                      num4Text: "취직하려면 그녀는 우선 지각하는 습관을 "+"버려야".underLined+" 할 것이다.\n→抛棄해야",
                      answer: 3),
        QuestionModel(num: 11,
                      questionText: "다음 글의 ㉠～㉣에 대한 고쳐 쓰기 방안으로 적절하지 않은 것은?",
                      reference: "  현재 리셋 증후군이 인터넷 중독의 한 유형으로 ㉠"+"꼽혀지고".underLined+" 있다. 리셋 증후군 환자들은 현실에서 잘못을 하더라도 버튼만 누르면 해결될 수 있다고 생각해서 아무런 죄의식이나 책임감 없이 행동한다. ㉡"+"‘리셋 증후군’이라는 말은 1990년 일본에서 처음 생겨났는데, 국내에선 1990년대 말부터 쓰이기 시작했다.".underLined+" 리셋 증후군 환자들은 현실과 가상을 구분하지 못하여 게임에서 실행했던 일을 현실에서 저지르고 뒤늦게 후회하는 경우가 많다. 특히, 이러한 특성을 지닌 청소년들은 무슨 일이든지 쉽게 포기하고 책임감 없는 행동을 하며, 마음에 들지 않는 사람이 있으면 ㉢"+"막다른 골목으로 몰 듯".underLined+" 관계를 쉽게 끊기도 한다.\n  리셋 증후군은 행동 양상이 명확히 나타나지 않는 편이라 쉽게 판별하기 어렵고 진단도 쉽지 않다. ㉣"+"이와 같이".underLined+" 예방을 위해 지속적으로 주위 사람들과 대화를 나누고, 현실과 인터넷 공간을 구분하는 능력을 길러야 한다.",
                      num1Text: "불필요한 이중 피동 표현으로 어법에 맞게 ㉠을 ‘꼽고’로 수정한다.",
                      num2Text: "글의 맥락상 자연스럽지 않으므로 ㉡은 첫 번째 문장 뒤로 옮긴다.",
                      num3Text: "앞뒤 문맥을 고려할 때 ㉢은 ‘칼로 무를 자르듯’으로 수정한다.",
                      num4Text: "앞 문장과의 연결을 고려하여 ㉣을 ‘그러므로’로 수정한다.",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "다음 글에서 의인화하고 있는 사물은?",
                      reference: "  姓은 楮이요, 이름은 白이요, 字는 無玷이다. 회계 사람이고, 한나라 중상시 상방령 채륜의 후손이다. 태어날 때 난초탕에 목욕하여 흰 구슬을 희롱하고 흰 띠로 꾸렸으므로 빛이 새하얗다. … (중략) … 성질이 본시 정결하여 武人은 좋아하지 않고 文士와 더불어 노니는데, 毛學士가 그 벗으로 매양 친하게 어울려서 비록 그 얼굴에 점을 찍어 더럽혀도 씻지 않았다.",
                      num1Text: "대나무",
                      num2Text: "백옥",
                      num3Text: "엽전",
                      num4Text: "종이",
                      answer: 4),
        QuestionModel(num: 13,
                      questionText: "다음 보도 기사별 마무리 표현으로 적절하지 않은 것은?",
                      reference: "㉠ 소송이나 다툼에 관한 소식\n㉡ 어느 쪽이 옳다고 말하기 애매한 소식\n㉢ 사건이 터지고 결과가 드러나기 전 소식\n㉣ 연예 스캔들 소식",
                      num1Text: "㉠: 모쪼록 원만히 해결되기 바랍니다.",
                      num2Text: "㉡: 그 의미를 새삼 돌아보게 됩니다.",
                      num3Text: "㉢: 현재 귀추가 주목되고 있습니다.",
                      num4Text: "㉣: 호사가들의 입방아에 오르내리고 있습니다.",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                      reference: "말뚝이:(벙거지를 쓰고 채찍을 들었다. 굿거리장단에 맞추어 양반 삼 형제를 인도하여 등장.)\n\n양반 삼 형제:(말뚝이 뒤를 따라 굿거리장단에 맞추어 점잔을 피우나, 어색하게 춤을 추며 등장. 양반 삼 형제 맏이는 샌님[生員], 둘째는 서방님[書房], 끝은 도련님[道令]이다. 샌님과 서방님은 흰 창옷에 관을 썼다. 도련님은 남색 쾌자에 복건을 썼다. 샌님과 서방님은 언청이이며(샌님은 언청이 두 줄, 서방님은 한 줄이다.) 부채와 장죽을 가지고 있고, 도련님은 입이 삐뚤어졌고 부채만 가졌다. 도련님은 대사는 일절 없으며, 형들과 동작을 같이하면서 형들의 면상을 부채로 때리며 방정맞게 군다.)\n\n말뚝이:(가운데쯤에 나와서) 쉬이. (음악과 춤 멈춘다.) 양반 나오신다아! 양반이라고 하니까 노론, 소론, 호조, 병조, 옥당을 다 지내고 삼정승, 육판서를 다 지낸 퇴로 재상으로 계신 양반인 줄 알지 마시오. 개잘량이라는 ‘양’ 자에 개다리소반이라는 ‘반’ 자 쓰는 양반이 나오신단 말이오.\n\n양반들:야아, 이놈, 뭐야아!\n\n말뚝이:아, 이 양반들, 어찌 듣는지 모르갔소. 노론, 소론, 호조, 병조, 옥당을 다 지내고 삼정승, 육판서 다 지내고 퇴로 재상으로 계신 이 생원네 삼 형제 분이 나오신다고 그리 하였소.\n\n양반들:(합창) 이 생원이라네. (굿거리장단으로 모두 춤을 춘다. 도령은 때때로 형들의 면상을 치며 논다. 끝까지 그런 행동을 한다.)\n\n－작자 미상, ｢봉산탈춤｣에서－",
                      num1Text: "양반들이 자신들을 조롱하는 말뚝이에게 야단쳤군.",
                      num2Text: "샌님과 서방님이 부채와 장죽을 들고 춤을 추며 등장했군.",
                      num3Text: "말뚝이가 굿거리장단에 맞춰 양반을 풍자하는 사설을 늘어놓았군.",
                      num4Text: "도련님이 방정맞게 굴면서 샌님과 서방님의 얼굴을 부채로 때렸군.",
                      answer: 3),
        QuestionModel(num: 15,
                      questionText: "밑줄 친 부분의 띄어쓰기가 옳은 것은?",
                      num1Text: "해도해도".underLined+" 너무한다.",
                      num2Text: "빠른 "+"시일 내".underLined+" 지원해 줄 것이다.",
                      num3Text: "이 그릇은 귀한 거라 손님 "+"대접하는데나".underLined+" 쓴다.",
                      num4Text: "소비 절약을 호소하는 "+"정공법 밖에".underLined+" 달리 도리는 없다.",
                      answer: 2),
        QuestionModel(num: 16,
                      questionText: "다음 글의 공간에 대한 설명으로 적절하지 않은 것은?",
                      reference: " 시(市)를 남북으로 나누며 달리는 철도는 항만의 끝에 이르러서야 잘려졌다. 석탄을 싣고 온 화차(貨車)는 자칫 바다에 빠뜨릴 듯한 머리를 위태롭게 사리며 깜짝 놀라 멎고 그 서슬에 밑구멍으로 주르르 석탄 가루를 흘려보냈다.\n  집에 가 봐야 노루꼬리만큼 짧다는 겨울 해에 점심이 기다리고 있는 것도 아니어서 우리들은 학교가 파하는 대로 책가방만 던져둔 채 떼를 지어 선창을 지나 항만의 북쪽 끝에 있는 제분 공장에 갔다.\n  제분 공장 볕 잘 드는 마당 가득 깔린 멍석에는 늘 덜 건조된 밀이 널려 있었다. 우리는 수위가 잠깐 자리를 비운 틈을 타서 마당에 들어가 멍석의 귀퉁이를 밟으며 한 움큼씩 밀을 입 안에 털어 넣고는 다시 걸었다. 올올이 흩어져 대글대글 이빨에 부딪치던 밀알들이 달고 따뜻한 침에 의해 딱딱한 껍질을 불리고 속살을 풀어 입 안 가득 풀처럼 달라붙다가 제법 고무질의 질긴 맛을 낼 때쯤이면 철로에 닿게 마련이었다.\n  우리는 밀껌으로 푸우푸우 풍선을 만들거나 침목(枕木) 사이에 깔린 잔돌로 비사치기를 하거나 전날 자석을 만들기 위해 선로 위에 얹어 놓았던 못을 뒤지면서 화차가 닿기를 기다렸다.\n  드디어 화차가 오고 몇 번의 덜컹거림으로 완전히 숨을 놓으면 우리들은 재빨리 바퀴 사이로 기어 들어가 석탄가루를 훑고 이가 벌어진 문짝 틈에 갈퀴처럼 팔을 들이밀어 조개탄을 후벼내었다. 철도 건너 저탄장에서 밀차를 밀며 나오는 인부들이 시커멓게 모습을 나타낼 즈음이면 우리는 대개 신발주머니에, 보다 크고 몸놀림이 잽싼 아이들은 시멘트 부대에 가득 든 석탄을 팔에 안고 낮은 철조망을 깨금발로 뛰어넘었다.\n  선창의 간이음식점 문을 밀고 들어가 구석 자리의 테이블을 와글와글 점거하고 앉으면 그날의 노획량에 따라 가락국수, 만두, 찐빵 등이 날라져 왔다.\n  석탄은 때로 군고구마, 딱지, 사탕 따위가 되기도 했다. 어쨌든 석탄이 선창 주변에서는 무엇과도 바꿀 수 있는 현금과 마찬가지라는 것을 우리는 알고 있었고, 때문에 우리 동네 아이들은 사철 검정 강아지였다.\n\n－오정희, ｢중국인 거리｣에서－",
                      num1Text: "철길 때문에 도시가 남북으로 나뉘어 있다.",
                      num2Text: "항만 북쪽에는 제분 공장이 있고, 철도 건너에는 저탄장이 있다.",
                      num3Text: "선로 주변에 아이들이 넘을 수 없는 철조망이 있다.",
                      num4Text: "석탄을 먹을거리와 바꿀 수 있는 간이음식점이 있다.",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "다음 밑줄 친 부분의 의미를 풀어 쓴 것으로 적절한 것은?",
                      reference: "  2004년 1월 태국에서는 한 소년이 극심한 폐렴 증세로 사망했다. 소년의 폐는 완전히 망가져 흐물흐물해져 있었다. 분석 결과, 이전까지 인간이 감염된 적이 없는 인플루엔자 바이러스가 원인으로 밝혀졌다. 소년은 공식적으로 고병원성 조류 인플루엔자 바이러스, H5N1의 첫 사망자가 되었다. 계절 독감으로 익숙한 인플루엔자 바이러스가 이렇게 치명적일 수 있었던 것은 인간의 면역 반응 때문이다. 인류 역사상 단 한 번도 만나본 적이 없는 새로운 바이러스가 침입하자 면역계가 과민 반응을 일으켜 도리어 인체에 해를 끼친 것이다. 이런 현상을 ‘사이토카인 폭풍’이라 부른다. 사이토카인 폭풍은 면역 능력이 강한 젊은 층일수록 더 세게 일어난다.\n  만약 집에 ㉠"+"좀도둑".underLined+"이 들었다면 작은 손해를 각오하고 인기척을 내 도둑 스스로 도망가게 하는 것이 상책이다. 그런데 만약 ㉡"+"몽둥이".underLined+"를 들고 도둑과 싸우려 든다면 도둑은 ㉢"+"강도".underLined+"로 돌변한다. 인체가 H5N1에 감염되면 똑같은 일이 벌어진다. 처음으로 새가 아닌 다른 숙주 몸속에 들어온 바이러스는 과민 반응한 면역계와 죽기 살기로 싸운다. 그 결과 50%가 넘는 승률로 바이러스가 승리한다. 그러나 ㉣"+"승리의 대가".underLined+"는 비싸다. 숙주가 죽어 버렸기 때문에 바이러스 역시 함께 죽어야만 한다. 이것이 바로 악명을 떨치면서도 조류 독감의 사망 환자 수가 전 세계에서 400명을 넘기지 않는 이유다. 이 질병이 아직 사람 사이에서 감염되는 사례가 나타나지 않은 이유도 바이러스가 인체라는 새로운 숙주에 적응하지 못했기 때문으로 추정할 수 있다.",
                      num1Text: "㉠:면역계의 과민 반응",
                      num2Text: "㉡:계절 독감",
                      num3Text: "㉢:치명적 바이러스",
                      num4Text: "㉣:극심한 폐렴 증세",
                      answer: 3),
        QuestionModel(num: 18,
                      questionText: "다음 글의 전개 순서로 가장 자연스러운 것은?",
                      reference: "ㄱ.1700년대 중반에 이미 미국 이주민들의 평균 소득은 영국인들의 평균 소득을 넘어섰다.\n\nㄴ.그러나 미국은 사실 그러한 분야에서는 다른 산업 국가들에 비해 특별한 우위를 갖고 있지 않았다.\n\nㄷ.미국 이주민들의 평균 소득이 높아지게 된 배경에는 좋은 환경으로부터 비롯된 낙관성과 자신감이 있었다. 이후로도 다소 불안정하기는 했지만 미국인들의 소득은 계속해서 크게 증가했다.\n\nㄹ.대부분의 미국인들은 남북 전쟁 이후 급속히 경제가 성장한 이유를 농업적 환경뿐만 아니라 19세기의 과학적, 기술적 대전환, 기업가 정신과 규제가 없는 시장 경제 때문이라고 단순하게 생각하는 경향이 있다.\n\nㅁ.미국인들이 이처럼 초기 정착기에 풍요로움을 누릴 수 있었던 것은 비옥한 토지, 풍부한 천연자원, 흑인 노동력에 힘입은 농산물 수출 덕분이었다.",
                      num1Text: "ㄱ－ㄷ－ㅁ－ㄹ－ㄴ",
                      num2Text: "ㄱ－ㄹ－ㄷ－ㄴ－ㅁ",
                      num3Text: "ㄹ－ㄴ－ㅁ－ㄱ－ㄷ",
                      num4Text: "ㄹ－ㅁ－ㄴ－ㄷ－ㄱ",
                      answer: 1),
        QuestionModel(num: 19,
                      questionText: "다음 글을 통해 추론할 수 없는 것은?",
                      reference: "  자신의 신념과 일치하는 정보는 받아들이고 그렇지 않은 정보는 무시하는 경향을 확증 편향(confirmation bias)이라 한다. 자신의 믿음이나 견해와 일치하는 정보는 수용하고 그에 반대되는 정보는 무시하거나 부정하는 심리 경향이다. 사회 심리학자인 로버트 치알디니는 자신이 가진 기존의 견해와 일치하는 정보는 두 가지 이점을 가지고 있다고 한다. 첫째, 그러한 정보는 어떤 문제에 대해 더 이상 고민하지 않고 마음의 휴식을 취할 수 있게 해 준다. 둘째, 그러한 정보는 우리를 추론의 결과에서 자유롭게 해 준다. 즉 추론의 결과 때문에 행동을 바꿔야 할 필요가 없다. 첫째는 생각하지 않게 하고, 둘째는 행동하지 않게 함을 말한다.\n  일례로 특정 정치 성향을 가진 사람들을 대상으로 조사했을 때, 사람들은 반대당 후보의 주장에서는 모순을 거의 완벽하게 찾은 반면, 지지하는 당 후보의 주장에서는 모순을 절반 정도만 찾아냈다. 이 판단의 과정을 자기 공명 영상 장치로도 촬영했다. 그 결과, 자신이 동의하지 않는 정보를 접했을 때는 뇌 회로가 활성화되지 않았고, 자신이 동의하는 주장을 접했을 때는 긍정적인 반응을 보이면서 뇌 회로가 활성화되는 것을 확인할 수 있었다.",
                      num1Text: "사람에게는 자신의 신념이나 행동을 바꾸려 하지 않는 경향이 있다.",
                      num2Text: "사람에게는 정보를 객관적으로 판단하지 못하는 심리적 특성이 있다.",
                      num3Text: "사람에게는 지지자들의 말만을 듣고 자기 신념을 강화하는 경향이 있다.",
                      num4Text: "사람에게는 새로운 정보를 접했을 때 심리적 불안을 느끼는 특성이 있다.",
                      answer: 4),
        QuestionModel(num: 20,
                      questionText: "밑줄 친 부분에서 행위의 주체가 같은 것으로만 묶은 것은?",
                      reference: "  금와왕이 이상히 여겨 유화를 방 안에 가두어 두었더니 햇빛이 방 안을 비추는데 ㉠"+"몸을 피하면".underLined+" 다시 쫓아와서 비추었다. 이로 해서 태기가 있어 알[卵] 하나를 낳으니, 크기가 닷 되들이만 했다. 왕이 그것을 버려서 개와 돼지에게 주게 했으나 모두 먹지 않았다. 다시 길에 ㉡"+"내다 버리게 했더니".underLined+" 소와 말이 피해서 가고 들에 내다 버리니 새와 짐승들이 덮어 주었다. 왕이 쪼개 보려고 했으나 아무리 해도 쪼개지지 않아 그 어미에게 돌려주었다. 어미가 이 알을 천으로 싸서 따뜻한 곳에 놓아두었더니 한 아이가 ㉢"+"껍질을 깨고 나왔는데,".underLined+" 골격과 외모가 영특하고 기이했다. 겨우 일곱 살이 되었을 때, 이미 기골이 뛰어나서 범인(凡人)과 달랐다. 스스로 활과 화살을 만들어 쏘았는데 백발백중이었다. 나라 풍속에 ㉣"+"활 잘 쏘는".underLined+" 사람을 주몽이라고 하므로 그 아이를 ‘주몽’이라 했다.\n  금와왕에게는 일곱 아들이 있어 항상 주몽과 함께 놀았는데, 재주가 주몽을 따르지 못했다. 맏아들 대소가 왕에게 말했다. “주몽은 사람의 자식이 아닙니다. 일찍 ㉤"+"없애지 않는다면".underLined+" 후환이 있을까 두렵습니다.” 왕이 듣지 않고 주몽을 시켜 말을 기르게 하니 주몽은 좋은 말을 알아보고 적게 먹여서 여위게 기르고, 둔한 말을 ㉥"+"잘 먹여서 살찌게 했다.".underLined,
                      num1Text: "㉠, ㉡",
                      num2Text: "㉡, ㉣",
                      num3Text: "㉢, ㉥",
                      num4Text: "㉣, ㉤",
                      answer: 3),
        ]
        let exam = ExamModel(id: 202021, year: 2020, examTypeID: "지방직", subjectID: "국어", questions: questions)
        exams2020.append(exam)
    }
    func saveExam202022() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "The issue with plastic bottles is that they’re not ______, so when the temperatures begin to rise, your water will also heat up.",
                      num1Text: "sanitary",
                      num2Text: "insulated",
                      num3Text: "recyclable",
                      num4Text: "waterproof",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오. [2~4]",
                      reference: "Strategies that a writer adopts during the writing process may "+"alleviate".underLined+" the difficulty of attentional overload.",
                      num1Text: "complement",
                      num2Text: "accelerate",
                      num3Text: "calculate",
                      num4Text: "relieve",
                      answer: 4),
        QuestionModel(num: 3,
                      questionText: "",
                      reference: "The cruel sights "+"touched off".underLined+" thoughts that otherwise wouldn’t have entered her mind.",
                      num1Text: "looked after",
                      num2Text: "gave rise to",
                      num3Text: "made up for",
                      num4Text: "kept in contact with",
                      answer: 2),
        QuestionModel(num: 4,
                      questionText: "",
                      reference: "The school bully did not know what it was like to be "+"shunned".underLined+" by the other students in the class.",
                      num1Text: "avoided",
                      num2Text: "warned",
                      num3Text: "punished",
                      num4Text: "imitated",
                      answer: 1),
        QuestionModel(num: 5,
                      questionText: "어법상 옳은 것은?",
                      num1Text: "Of the billions of stars in the galaxy, how much are able to hatch life?",
                      num2Text: "The Christmas party was really excited and I totally lost track of time.",
                      num3Text: "I must leave right now because I am starting work at noon today.",
                      num4Text: "They used to loving books much more when they were younger.",
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것은?",
                      reference: "After Francesca "+"made a case for".underLined+" staying at home during the summer holidays, an uncomfortable silence fell on the dinner table. Robert was not sure if it was the right time for him to tell her about his grandiose plan.",
                      num1Text: "objected to",
                      num2Text: "dreamed about",
                      num3Text: "completely excluded",
                      num4Text: "strongly suggested",
                      answer: 4),
        QuestionModel(num: 7,
                      questionText: "밑줄 친 부분 중 어법상 옳지 않은 것은?",
                      reference: "Elizabeth Taylor had an eye for beautiful jewels and over the years amassed some amazing pieces, once ①"+"declaring".underLined+" “a girl can always have more diamonds.” In 2011, her finest jewels were sold by Christie’s at an evening auction ②"+"that".underLined+" brought in $115.9 million. Among her most prized possessions sold during the evening sale ③"+"were".underLined+" a 1961 bejeweled timepiece by Bulgari. Designed as a serpent to coil around the wrist, with its head and tail ④"+"covered".underLined+" with diamonds and having two hypnotic emerald eyes, a discreet mechanism opens its fierce jaws to reveal a tiny quartz watch.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "우리말을 영어로 잘못 옮긴 것은?",
                      num1Text: "보증이 만료되어서 수리는 무료가 아니었다.\n→Since the warranty had expired, the repairs were not free of charge.",
                      num2Text: "설문지를 완성하는 누구에게나 선물카드가 주어질 예정이다.\n→A gift card will be given to whomever completes the questionnaire.",
                      num3Text: "지난달 내가 휴가를 요청했더라면 지금 하와이에 있을 텐데.\n→If I had asked for a vacation last month, I would be in Hawaii now.",
                      num4Text: "그의 아버지가 갑자기 작년에 돌아가셨고, 설상가상으로 그의 어머니도 병에 걸리셨다.\n→His father suddenly passed away last year, and, what was worse, his mother became sick.",
                      answer: 2),
        QuestionModel(num: 9,
                      questionText: "밑줄 친 (A), (B)에 들어갈 말로 가장 적절한 것은?",
                      reference: "Assertive behavior involves standing up for your rights and expressing your thoughts and feelings in a direct, appropriate way that does not violate the rights of others. It is a matter of getting the other person to understand your viewpoint. People who exhibit assertive behavior skills are able to handle conflict situations with ease and assurance while maintaining good interpersonal relations.  (A) , aggressive behavior involves expressing your thoughts and feelings and defending your rights in a way that openly violates the rights of others. Those exhibiting aggressive behavior seem to believe that the rights of others must be subservient to theirs.   (B)  , they have a difficult time maintaining good interpersonal relations. They are likely to interrupt, talk fast, ignore others, and use sarcasm or other forms of verbal abuse to maintain control.",
                      num1Text: "In contrast - Thus",
                      num2Text: "Similarly - Moreover",
                      num3Text: "However - On one hand",
                      num4Text: "Accordingly - On the other hand",
                      answer: 1),
        QuestionModel(num: 10,
                      questionText: "다음 글의 주제로 가장 적절한 것은?",
                      reference: "The e-book applications available on tablet computers employ touchscreen technology. Some touchscreens feature a glass panel covering two electronically-charged metallic surfaces lying face-to-face. When the screen is touched, the two metallic surfaces feel the pressure and make contact. This pressure sends an electrical signal to the computer, which translates the touch into a command. This version of the touchscreen is known as a resistive screen because the screen reacts to pressure from the finger. Other tablet computers feature a single electrified metallic layer under the glass panel. When the user touches the screen, some of the current passes through the glass into the user’s finger. When the charge is transferred, the computer interprets the loss in power as a command and carries out the function the user desires. This type of screen is known as a capacitive screen.",
                      num1Text: "how users learn new technology",
                      num2Text: "how e-books work on tablet computers",
                      num3Text: "how touchscreen technology works",
                      num4Text: "how touchscreens have evolved",
                      answer: 3),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "A: Oh, another one! So many junk emails!\nB: I know. I receive more than ten junk emails a day.\nA: Can we stop them from coming in?\nB: I don’t think it’s possible to block them completely.\nA: ______________________________________?\nB: Well, you can set up a filter on the settings.\nA: A filter?\nB: Yeah. The filter can weed out some of the spam emails.",
                      num1Text: "Do you write emails often",
                      num2Text: "Isn’t there anything we can do",
                      num3Text: "How did you make this great filter",
                      num4Text: "Can you help me set up an email account",
                      answer: 2),
        QuestionModel(num: 12,
                      questionText: "우리말을 영어로 잘못 옮긴 것은?",
                      num1Text: "나는 네 열쇠를 잃어버렸다고 네게 말한 것을 후회한다.\n→I regret to tell you that I lost your key.",
                      num2Text: "그 병원에서의 그의 경험은 그녀의 경험보다 더 나빴다.\n→His experience at the hospital was worse than hers.",
                      num3Text: "그것은 내게 지난 24년의 기억을 상기시켜준다.\n→It reminds me of the memories of the past 24 years.",
                      num4Text: "나는 대화할 때 내 눈을 보는 사람들을 좋아한다.\n→I like people who look me in the eye when I have a conversation.",
                      answer: 1),
        QuestionModel(num: 13,
                      questionText: "두 사람의 대화 중 가장 자연스러운 것은?",
                      num1Text: "A: Do you know what time it is?\nB: Sorry, I’m busy these days.",
                      num2Text: "A: Hey, where are you headed?\nB: We are off to the grocery store.",
                      num3Text: "A: Can you give me a hand with this?\nB: OK. I’ll clap for you.",
                      num4Text: "A: Has anybody seen my purse?\nB: Long time no see.",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "Louis ⅩⅣ needed a palace worthy of his greatness, so he decided to build a huge new house at Versailles, where a tiny hunting lodge stood. After almost fifty years of labor, this tiny hunting lodge had been transformed into an enormous palace, a quarter of a mile long. Canals were dug to bring water from the river and to drain the marshland. Versailles was full of elaborate rooms like the famous Hall of Mirrors, where seventeen huge mirrors stood across from seventeen large windows, and the Salon of Apollo, where a solid silver throne stood. Hundreds of statues of Greek gods such as Apollo, Jupiter, and Neptune stood in the gardens; each god had Louis’s face!",
                      num1Text: "True Face of Greek Gods",
                      num2Text: "The Hall of Mirrors vs. the Salon of Apollo",
                      num3Text: "Did the Canal Bring More Than Just Water to Versailles?",
                      num4Text: "Versailles: From a Humble Lodge to a Great Palace",
                      answer: 4),
        QuestionModel(num: 15,
                      questionText: "글의 흐름상 가장 어색한 문장은?",
                      reference: "Philosophers have not been as concerned with anthropology as anthropologists have with philosophy. ①"+"Few influential contemporary philosophers take anthropological studies into account in their work.".underLined+" ②"+"Those who specialize in philosophy of social science may consider or analyze examples from anthropological research, but do this mostly to illustrate conceptual points or epistemological distinctions or to criticize epistemological or ethical implications.".underLined+" ③"+"In fact, the great philosophers of our time often drew inspiration from other fields such as anthropology and psychology.".underLined+" ④"+"Philosophy students seldom study or show serious interest in anthropology.".underLined+" They may learn about experimental methods in science, but rarely about anthropological fieldwork.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "All of us inherit something: in some cases, it may be money, property or some object―a family heirloom such as a grandmother’s wedding dress or a father’s set of tools. But beyond that, all of us inherit something else, something __________________________, something we may not even be fully aware of. It may be a way of doing a daily task, or the way we solve a particular problem or decide a moral issue for ourselves. It may be a special way of keeping a holiday or a tradition to have a picnic on a certain date. It may be something important or central to our thinking, or something minor that we have long accepted quite casually.",
                      num1Text: "quite unrelated to our everyday life",
                      num2Text: "against our moral standards",
                      num3Text: "much less concrete and tangible",
                      num4Text: "of great monetary value",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "다음 글의 요지로 가장 적절한 것은?",
                      reference: "Evolutionarily, any species that hopes to stay alive has to manage its resources carefully. That means that first call on food and other goodies goes to the breeders and warriors and hunters and planters and builders and, certainly, the children, with not much left over for the seniors, who may be seen as consuming more than they’re contributing. But even before modern medicine extended life expectancies, ordinary families were including grandparents and even great-grandparents. That’s because what old folk consume materially, they give back behaviorally―providing a leveling, reasoning center to the tumult that often swirls around them.",
                      num1Text: "Seniors have been making contributions to the family.",
                      num2Text: "Modern medicine has brought focus to the role of old folk.",
                      num3Text: "Allocating resources well in a family determines its prosperity.",
                      num4Text: "The extended family comes at a cost of limited resources.",
                      answer: 1),
        QuestionModel(num: 18,
                      questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "Nowadays the clock dominates our lives so much that it is hard to imagine life without it. Before industrialization, most societies used the sun or the moon to tell the time.",
                      reference2: "(A)For the growing network of railroads, the fact that there were no time standards was a disaster. Often, stations just some miles apart set their clocks at different times. There was a lot of confusion for travelers.\n\n(B)When mechanical clocks first appeared, they were immediately popular. It was fashionable to have a clock or a watch. People invented the expression “of the clock” or “o’clock” to refer to this new way to tell the time.\n\n(C)These clocks were decorative, but not always useful. This was because towns, provinces, and even neighboring villages had different ways to tell the time. Travelers had to reset their clocks repeatedly when they moved from one place to another. In the United States, there were about 70 different time zones in the 1860s.",
                      num1Text: "(A)－(B)－(C)",
                      num2Text: "(B)－(A)－(C)",
                      num3Text: "(B)－(C)－(A)",
                      num4Text: "(C)－(A)－(B)",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "주어진 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "But there is also clear evidence that millennials, born between 1981 and 1996, are saving more aggressively for retirement than Generation X did at the same ages, 22～37.",
                      reference2: "Millennials are often labeled the poorest, most financially burdened generation in modern times. Many of them graduated from college into one of the worst labor markets the United States has ever seen, with a staggering load of student debt to boot. ①Not surprisingly, millennials have accumulated less wealth than Generation X did at a similar stage in life, primarily because fewer of them own homes. ②But newly available data providing the most detailed picture to date about what Americans of different generations save complicates that assessment. ③Yes, Gen Xers, those born between 1965 and 1980, have a higher net worth. ④And that might put them in better financial shape than many assume.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 20,
                      questionText: "다음 글의 내용과 일치하지 않는 것은?",
                      reference: "Carbonate sands, which accumulate over thousands of years from the breakdown of coral and other reef organisms, are the building material for the frameworks of coral reefs. But these sands are sensitive to the chemical make-up of sea water. As oceans absorb carbon dioxide, they acidify―and at a certain point, carbonate sands simply start to dissolve. The world’s oceans have absorbed around one-third of human-emitted carbon dioxide. The rate at which the sands dissolve was strongly related to the acidity of the overlying seawater, and was ten times more sensitive than coral growth to ocean acidification. In other words, ocean acidification will impact the dissolution of coral reef sands more than the growth of corals. This probably reflects the corals’ ability to modify their environment and partially adjust to ocean acidification, whereas the dissolution of sands is a geochemical process that cannot adapt.",
                      num1Text: "The frameworks of coral reefs are made of carbonate sands.",
                      num2Text: "Corals are capable of partially adjusting to ocean acidification.",
                      num3Text: "Human-emitted carbon dioxide has contributed to the world’s ocean acidification.",
                      num4Text: "Ocean acidification affects the growth of corals more than the dissolution of coral reef sands.",
                      answer: 4),
        
        
        
        ]
        let exam = ExamModel(id: 202022, year: 2020, examTypeID: "지방직", subjectID: "영어", questions: questions)
        exams2020.append(exam)
    }
    func saveExam202023() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 ‘왕’의 재위 기간에 있었던 사실로 옳은 것은?",
                      reference: "이찬 이사부가 "+"왕".underLined+"에게 “국사라는 것은 임금과 신하들의 선악을 기록하여, 좋고 나쁜 것을 만대 후손들에게 보여 주는 것입니다. 이를 책으로 편찬해 놓지 않는다면 후손들이 무엇을 보고 알겠습니까?”라고 아뢰었다. "+"왕".underLined+"이 깊이 동감하고 대아찬 거칠부 등에게 명하여 선비들을 널리 모아 그들로 하여금 역사를 편찬하게 하였다.\n\n－〖삼국사기〗－",
                      num1Text: "정전 지급",
                      num2Text: "국학 설치",
                      num3Text: "첨성대 건립",
                      num4Text: "북한산 순수비 건립",
                      answer: 4),
        QuestionModel(num: 2,
                      questionText: "다음 정책을 시행한 국왕 대에 있었던 사실로 옳은 것은?",
                      reference: "○ 광덕, 준풍 등의 연호를 사용하였다.\n○ 개경을 고쳐 황도라 하고 서경을 서도라고 하였다.",
                      num1Text: "노비안검법을 시행하였다.",
                      num2Text: "전시과 제도를 시행하였다.",
                      num3Text: "개경에 국자감을 설립하였다.",
                      num4Text: "12목을 설치하고 지방관을 파견하였다.",
                      answer: 1),
        QuestionModel(num: 3,
                      questionText: "다음과 같은 활동을 펼친 인물에 대한 설명으로 옳은 것은?",
                      reference: "○ 대한매일신보에 애국적인 논설을 썼다.\n○ 유교 개혁의 뜻을 담은 ｢유교구신론｣을 집필하였다.",
                      num1Text: "적극적인 의열 활동을 위해 한인애국단을 만들었다.",
                      num2Text: "일본의 침략상을 폭로하는 〖한국통사〗를 저술하였다.",
                      num3Text: "실증사학의 입장에서 연구하는 진단학회를 조직하였다.",
                      num4Text: "김원봉의 요청을 받아들여 ｢조선혁명선언｣을 작성하였다.",
                      answer: 2),
        QuestionModel(num: 4,
                      questionText: "(가) 단체로 옳은 것은?",
                      reference: "[ (가) ] 발기취지(發起趣旨)\n인간 사회는 많은 불합리를 산출한 동시에 그 해결을 우리에게 요구하고 있다. 여성 문제는 그중의 하나이다. …… 과거의 조선 여성운동은 분산되어 있었다. 그것에는 통일된 조직이 없었고 통일된 지도 정신도 없었고 통일된 항쟁이 없었다. …… 우리는 우선 조선 자매 전체의 역량을 공고히 단결하여 운동을 전반적으로 전개하지 아니하면 아니 된다.\n\n－〖동아일보〗, 1927. 5. 11.－",
                      num1Text: "근우회",
                      num2Text: "신간회",
                      num3Text: "신민회",
                      num4Text: "정우회",
                      answer: 1),
        QuestionModel(num: 5,
                      questionText: "다음 글에서 설명하고 있는 문화유산은?",
                      reference: "이곳은 원래 성종의 형인 월산대군(月山大君)의 집이 있던 곳으로, 선조가 임진왜란 뒤 임시거처로 사용하면서 정릉동 행궁으로 불리었고, 광해군 때는 경운궁이라 하였다. 아관파천 후 고종이 이곳에 머물렀다. 주요 건물로는 중화전, 함녕전, 석조전 등이 있다.",
                      num1Text: "경복궁",
                      num2Text: "경희궁",
                      num3Text: "창덕궁",
                      num4Text: "덕수궁",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 ‘이 나라’에서 볼 수 있는 모습으로 적절한 것은?",
                      reference: "이 나라".underLined+"는 대군왕이 없으며, 읍락에는 각각 대를 잇는 장수(長帥)가 있다. …… "+"이 나라".underLined+"의 토질은 비옥하며, 산을 등지고 바다를 향해 있어 오곡이 잘 자라며 농사짓기에 적합하다. 사람들의 성질은 질박하고, 정직하며 굳세고 용감하다. 소나 말이 적고, 창을 잘 다루며 보전(步戰)을 잘한다. 음식, 주거, 의복, 예절은 고구려와 흡사하다. 그들은 장사를 지낼 적에는 큰 나무 곽(槨)을 만드는데 길이가 십여 장(丈)이나 되며 한쪽 머리를 열어 놓아 문을 만든다.\n\n－〖삼국지〗 위서 동이전－",
                      num1Text: "민며느리를 받아들이는 읍군",
                      num2Text: "위만에게 한나라의 침입을 알리는 장군",
                      num3Text: "5월에 씨를 뿌리고 하늘에 제사를 지내는 천군",
                      num4Text: "국가의 중요한 일을 논의하고 있는 마가와 우가",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "다음 사건이 일어난 왕의 재위 기간에 대한 설명으로 옳은 것은?",
                      reference: "임꺽정은 양주 백정으로, 성품이 교활하고 날래고 용맹스러웠다. 그 무리 수십 명이 함께 다 날래고 빨랐는데, 도적이 되어 민가를 불사르고 소와 말을 빼앗고, 만약 항거하면 몹시 잔혹하게 사람을 죽였다. 경기도와 황해도의 아전과 백성들이 임꺽정 무리와 은밀히 결탁하여, 관에서 잡으려 하면 번번이 먼저 알려주었다.",
                      num1Text: "동인과 서인의 붕당이 형성되었다.",
                      num2Text: "문정왕후가 수렴청정하며 불교를 옹호하였다.",
                      num3Text: "삼포에서 4～5천 명의 일본인이 난을 일으켰다.",
                      num4Text: "조광조가 내수사 장리의 폐지, 소격서 폐지 등을 주장하였다.",
                      answer: 2),
        QuestionModel(num: 8,
                      questionText: "밑줄 친 ‘이 부대’에 대한 설명으로 옳은 것은?",
                      reference: "윤관이 아뢰기를, “신이 적의 기세를 보건대 예측하기 어려울 정도로 굳세니, 마땅히 군사를 쉬게 하고 군관을 길러서 후일을 기다려야 할 것입니다. 또 신이 싸움에서 진 것은 적은 기병(騎兵)인데 우리는 보병(步兵)이라 대적할 수가 없었기 때문입니다.”라 하였다. 이에 그가 건의하여 처음으로 "+"이 부대".underLined+"를 만들었다.",
                      num1Text: "정종 2년에 설치되었다.",
                      num2Text: "귀주대첩에서 큰 활약을 하였다.",
                      num3Text: "여진족에 대처하기 위해 조직되었다.",
                      num4Text: "응양군, 용호군, 신호위 등의 2군과 6위로 편성되었다.",
                      answer: 3),
        QuestionModel(num: 9,
                      questionText: "밑줄 친 ‘이 나라’에 대한 설명으로 옳은 것은?",
                      reference: "이 나라".underLined+"는 삼한의 종족이며, 지금의 고령에 있었다. 건원 원년(479)에 그 국왕 하지(荷知)는 사신을 보내 남제에 공물을 바쳤다. 남제에서는 국왕 하지에게 “보국장군 본국왕”을 제수하였다.",
                      num1Text: "관산성 전투에서 국왕이 전사하였다.",
                      num2Text: "울릉도를 정복해서 영토로 편입하였다.",
                      num3Text: "호남 동부 지역까지 세력을 확장하였다.",
                      num4Text: "신라를 도와 낙동강 유역에 진출한 왜를 격파하였다.",
                      answer: 3),
        QuestionModel(num: 10,
                      questionText: "다음 설명에 해당하는 발해 왕의 재위 기간에 통일 신라에서 일어난 상황으로 옳은 것은?",
                      reference: "○ 대흥이란 독자적인 연호를 사용하였다.\n○ 수도를 중경→상경→동경으로 옮겼다.\n○ 일본에 보낸 외교문서에 천손(하늘의 자손)이라 표현하였다.\n○ 당과 친선 관계를 맺으며 당의 문물을 도입하여 체제를 정비하였다.",
                      num1Text: "녹읍 폐지",
                      num2Text: "청해진 설치",
                      num3Text: "〖삼대목〗 편찬",
                      num4Text: "독서삼품과 설치",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 ‘그’의 저술로 옳은 것은?",
                      reference: "서울의 노론 집안에서 태어난 "+"그".underLined+"는 〖양반전〗을 지어 양반사회의 허위를 고발하였다. "+"그".underLined+"는 또한 한전론을 주장하였으며, 상공업 진흥에도 관심을 기울여 수레와 선박의 이용 등에 대해서도 주목하였다.",
                      num1Text: "〖북학의〗",
                      num2Text: "〖과농소초〗",
                      num3Text: "〖의산문답〗",
                      num4Text: "〖지봉유설〗",
                      answer: 2),
        QuestionModel(num: 12,
                      questionText: "(가) 시기에 있었던 일로 옳은 것은?",
                      reference: "이종무의 대마도정벌\n    ⬇︎\n   (가)\n    ⬇︎\n전분6등법과 연분9등법 시행",
                      num1Text: "과전법 공포",
                      num2Text: "이시애의 반란",
                      num3Text: "〖농사직설〗 편찬",
                      num4Text: "정도전의 요동정벌 추진",
                      answer: 3),
        QuestionModel(num: 13,
                      questionText: "(가) 시기에 있었던 일로 옳은 것은?",
                      reference: "강화도조약을 체결하였다.\n    ⬇︎\n   (가)\n    ⬇︎\n청에 영선사를 파견하였다.",
                      num1Text: "군국기무처를 두고 여러 건의 개혁안을 처리하였다.",
                      num2Text: "개화 정책을 추진할 기구로 통리기무아문을 설치하였다.",
                      num3Text: "국정 개혁의 기본 방향을 담은 홍범 14조를 공포하였다.",
                      num4Text: "구본신참의 개혁 원칙을 정하고 대한국국제를 선포하였다.",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "세계유산으로 등재된 것이 아닌 것은? (2019년 12월 31일 기준)",
                      num1Text: "종묘",
                      num2Text: "화성",
                      num3Text: "한양도성",
                      num4Text: "남한산성",
                      answer: 3),
        QuestionModel(num: 15,
                      questionText: "다음과 같은 주제로 토론회를 개최한 단체에 대한 설명으로 옳은 것은?",
                      imgModel: ImageModel(imageString: "202023-10", imgWidth: 330, imgHeight: 170),
                      num1Text: "헌정연구회의 활동을 계승하여 월보를 간행하고 지회를 설치하였다.",
                      num2Text: "국민 계몽을 위해 회보를 발간하고 만민공동회 등 대규모 집회를 열었다.",
                      num3Text: "보부상 중심의 단체로 황권 강화를 통한 부국강병을 행동지침으로 삼았다.",
                      num4Text: "일본이 황무지 개간을 구실로 토지를 약탈하려 하자 대중적 반대 운동을 벌였다.",
                      answer: 2),
        QuestionModel(num: 16,
                      questionText: "밑줄 친 ‘그’의 활동으로 옳은 것은?",
                      reference: "경술년(1910)에 여러 형제들이 모여서 같이 만주로 갈 준비를 하였다. …… "+"그".underLined+"(1867～1932)는 1만여 석의 재산과 가옥을 모두 팔고 큰집, 작은 집이 함께 압록강을 건너 떠났다. "+"그".underLined+"는 만주에서 독립군 양성 기관인 신흥 강습소를 설립하였다.",
                      num1Text: "조선어학회 사건으로 옥고를 치렀다.",
                      num2Text: "독립운동 단체인 경학사를 조직하였다.",
                      num3Text: "3․1운동 민족대표 33인 중 한 명이었다.",
                      num4Text: "‘삼균주의’에 입각한 한국국민당을 결성하였다.",
                      answer: 2),
        QuestionModel(num: 17,
                      questionText: "밑줄 친 ‘새 헌법’에 대한 설명으로 옳은 것은?",
                      reference: "정부에서는 6월 15일 국회에서 통과된 개헌안을 이송받자 이날 긴급 국무회의를 소집하고 정식으로 이를 공포하였다. 이로써 개정된 "+"새 헌법".underLined+"은 16일 0시를 기해 효력을 발생케 되었다. "+"새 헌법".underLined+"이 공포됨으로써 16일부터는 실질적인 내각책임체제의 정부를 갖게 되었으며 허정 수석국무위원은 자동으로 국무총리가 된다.\n\n－〖경향신문〗, 1960. 6. 16.－",
                      num1Text: "임시수도 부산에서 개정되었다.",
                      num2Text: "‘사사오입’의 논리로 통과되었다.",
                      num3Text: "통일주체국민회의 설치를 규정한 조항이 있다.",
                      num4Text: "민의원과 참의원으로 구성된 국회 조항이 있다.",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "다음 사건 이후에 일어난 일로 옳은 것은?",
                      reference: "개경을 떠나 피난 중인 왕이 안성현을 안성군으로 승격시켰다. 홍건적이 양광도를 침입하자 수원은 항복하였는데, 작은 고을인 안성만이 홀로 싸워 승리함으로써 홍건적이 남쪽으로 내려오지 못하게 하였기 때문이다.",
                      num1Text: "화약 무기를 사용해 진포해전에서 승리하였다.",
                      num2Text: "처인성 전투에서 적의 장수 살리타를 사살하였다.",
                      num3Text: "기철 일파를 제거하고 쌍성총관부의 관할 지역을 수복하였다.",
                      num4Text: "적의 침략을 물리치기 위한 염원에서 팔만대장경을 만들었다.",
                      answer: 1),
        QuestionModel(num: 19,
                      questionText: "(가)와 (나) 사이의 시기에 있었던 일로 옳은 것은?",
                      reference: "(가)남인들이 대거 관직에서 쫓겨나고 허적과 윤휴 등이 처형되었다.\n\n(나)인현왕후가 복위되고 노론과 소론이 정계에 복귀하였다.",
                      num1Text: "송시열과 김수항 등이 처형당하였다.",
                      num2Text: "서인과 남인이 두 차례에 걸쳐 예송을 전개하였다.",
                      num3Text: "서인 정치에 한계를 느낀 정여립이 모반을 일으켰다.",
                      num4Text: "청의 요구에 따라 조총부대를 영고탑으로 파견하였다.",
                      answer: 1),
        QuestionModel(num: 20,
                      questionText: "다음의 사건을 시기순으로 바르게 나열한 것은?",
                      reference: "(가)제헌국회가 구성되어 헌법을 제정하였다.\n(나)여운형과 김규식은 좌우합작위원회를 조직하였다.\n(다)조선건국동맹을 기반으로 조선건국준비위원회가 조직되었다.\n(라)민주주의 임시정부 수립을 논의하기 위해 제1차 미․소공동위원회가 열렸다.",
                      num1Text: "(가)－(다)－(나)－(라)",
                      num2Text: "(나)－(다)－(라)－(가)",
                      num3Text: "(다)－(라)－(나)－(가)",
                      num4Text: "(라)－(나)－(가)－(다)",
                      answer: 3),
        
        ]
        let exam = ExamModel(id: 202023, year: 2020, examTypeID: "지방직", subjectID: "한국사", questions: questions)
        exams2020.append(exam)
    }
}
