//
//  ExamStore2015.swift
//  HandGosi
//
//  Created by Sy Lee on 2022/08/26.
//
/*
 let questions =
 [
 QuestionModel(num: <#T##Int#>,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 2,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 3,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 4,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 5,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 6,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 7,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 8,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 9,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 10,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 11,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 12,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 13,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 14,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 15,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 16,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 17,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 18,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 19,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 20,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>)
 ]
 
 let exam = ExamModel(id: 201511, year: 2015, examTypeID: "국가직", subjectID: "국어", questions: questions)
 
 exam2015.append(exam)
 */
import Foundation

class ExamStore2015 {
    var exam2015: [ExamModel] = []
    
    init() {
        saveExam201511()
        saveExam201512()
        saveExam201513()
        
        
        
    }
    
    func saveExam201511() {
        let questions =
        [
            QuestionModel(num: 1,
                          questionText: "어법에 맞게 쓰인 것은?",
                          num1Text: "내일 야유회 간데요?",
                          num2Text: "그이가 말을 아주 잘하대.",
                          num3Text: "연예인을 보니 그렇게 좋던?",
                          num4Text: "제가 직접 봤는데 너무 크대요.",
                          answer: 3),
            QuestionModel(num: 2,
                          questionText: "띄어쓰기가 바른 것은?",
                          num1Text: "그 사고는 여러 가지 규칙을 도외시 하였기 때문이야.",
                          num2Text: "사실상 여자 대 남자의 대리전으로 밖에는 보이지 않아.",
                          num3Text: "반드시 거기에 가겠다면 내키는 대로 행동해서는 안 돼.",
                          num4Text: "금연을 한 만큼 네 건강이 어느 정도까지 회복될 지 궁금해.",
                          answer: 3),
            QuestionModel(num: 3,
                          questionText: "밑줄 친 조사의 쓰임이 옳지 않은 것은?",
                          num1Text: "건축 면적은 설계도"+"에서".underLined+" 정한 기준에 따라 산정한다.",
                          num2Text: "제안서 및 과업 지시서는 참가 신청자"+"에게".underLined+" 한하여 교부한다.",
                          num3Text: "관계 조서 사본을 관리 사무소"+"에".underLined+" 비치하고 일반인에게 보인다.",
                          num4Text: "제5조 제1항의 규정"+"에도".underLined+" 불구하고 다음 각 목의 평가는 1년 유예를 둔다.",
                          answer: 2),
            QuestionModel(num: 4,
                          questionText: "다음 글에서 경계하고자 하는 태도와 유사한 것은?",
                          reference: "  비판적 사고는 지엽적이고 시시콜콜한 문제를 트집 잡아 물고 늘어지는 것이 아니라 문제의 핵심을 중요한 대상으로 삼는다. 비판적 사고는 제기된 주장에 어떤 오류나 잘못이 있는가를 찾아내기 위해 지엽적인 사항을 확대하여 문제로 삼는 태도나 사고방식과는 거리가 멀다.",
                          num1Text: "격물치지(格物致知)",
                          num2Text: "본말전도(本末顚倒)",
                          num3Text: "유명무실(有名無實)",
                          num4Text: "돈오점수(頓悟漸修)",
                          answer: 2),
            QuestionModel(num: 5,
                          questionText: "다음을 논리적 순서로 배열한 것은?",
                          reference: "  ㄱ. 그 덕분에 인류의 문명은 발달될 수 있었다.\n  ㄴ. 그 대신 사람들은 잠을 빼앗겼고 생물들은 생체 리듬을 잃었다.\n  ㄷ. 인간은 오랜 세월 태양의 움직임에 따라 신체 조건을 맞추어 왔다.\n  ㄹ. 그러나 밤에도 빛을 이용해 보겠다는 욕구가 관솔불, 등잔불, 전등을 만들어 냈고, 이에 따라 밤에 이루어지는 인간의 활동이 점점 많아졌다.",
                          num1Text: "ㄱ － ㄴ － ㄷ － ㄹ",
                          num2Text: "ㄴ － ㄱ － ㄹ － ㄷ",
                          num3Text: "ㄷ － ㄹ － ㄱ － ㄴ",
                          num4Text: "ㄹ － ㄷ － ㄴ － ㄱ",
                          answer: 3),
            QuestionModel(num: 6,
                          questionText: "리더십 부재와 잘못된 정책을 ‘등산’에 빗대어 설명한 것으로 가장 적절한 것은?",
                          num1Text: "사공이 많으면 배가 산으로 간다는 속담처럼 말이 많으면 어느 산을 오를 것인지 결정할 수 없습니다.",
                          num2Text: "등산로를 잘 알지 못하더라도 길잡이가 용기 있는 결단을 내리면 많은 사람들이 등산에 성공할 수 있습니다.",
                          num3Text: "길잡이가 방향을 잘못 가리키고 혼자 가 버리면 많은 사람들이 산 정상에 오를 수 없어 등산의 기쁨을 맛볼 수 없습니다.",
                          num4Text: "등산의 목적은 다른 사람들보다 먼저 봉우리에 올랐다는 기쁨 그 자체이므로 길잡이는 항상 등산하는 사람들이 경쟁할 수 있도록 도와야 합니다.",
                          answer: 3),
            QuestionModel(num: 7,
                          questionText: "다음 글에서 알 수 있는 내용이 아닌 것은?",
                          reference: "  사물놀이는 사물(四物), 즉 꽹과리, 징, 장구, 북의 네 가지 타악기만으로 연주하는 음악을 말한다. 사물놀이는 풍물놀이와는 좀 다르다. 풍물놀이를 무대 공연에 맞게 변형한 것이 사물놀이인데, 풍물놀이가 대체로 자기 지역의 가락만을 연주하는 데 비해 사물놀이는 거의 전 지역의 가락을 모아 재구성해서 연주한다.\n  사물놀이 연주자들은 흔히 쟁쟁거리는 꽹과리를 천둥이나 번개에, 잦게 몰아가는 장구를 비에, 둥실대는 북을 구름에, 여운을 남기며 울리는 징을 바람에 비유한다. 천둥이나 번개, 비, 구름, 바람이 어우러지며 토해 내는 소리가 사물놀이 소리라는 것이다. 사물놀이는 앉아서 연주하는 사물놀이와 서서 연주하는 사물놀이의 두 가지 형태로 나뉘어 있는데, 전자를 ‘앉은반’, 후자를 ‘선반’이라고 한다.",
                          num1Text: "사물놀이의 가치",
                          num2Text: "사물놀이의 소리",
                          num3Text: "사물놀이의 악기 종류",
                          num4Text: "사물놀이의 연주 형태",
                          answer: 1),
            QuestionModel(num: 8,
                          questionText: "다음 글의 내용과 부합하지 않는 것은?",
                          reference: "  글의 기본 단위가 문장이라면 구어를 통한 의사소통의 기본 단위는 발화이다. 담화에서 화자는 발화를 통해 ‘명령’, ‘요청’, ‘질문’, ‘제안’, ‘약속’, ‘경고’, ‘축하’, ‘위로’, ‘협박’, ‘칭찬’, ‘비난’ 등의 의도를 전달한다. 이때 화자의 의도가 직접적으로 표현된 발화를 직접 발화, 암시적으로 혹은 간접적으로 표현된 발화를 간접 발화라고 한다.\n  일상 대화에서도 간접 발화는 많이 사용되는데, 그 의미는 맥락에 의존하여 파악된다. ‘아, 덥다.’라는 발화가 ‘창문을 열어라.’라는 의미로 파악되는 것이 대표적인 예이다. 방 안이 시원하지 않다는 상황을 고려하여 청자는 창문을 열게 되는 것이다. 이처럼 화자는 상대방이 충분히 그 의미를 파악할 수 있다고 판단될 때 간접 발화를 전략적으로 사용함으로써 의사소통을 원활하게 하기도 한다.\n  공손하게 표현하고자 할 때도 간접 발화는 유용하다. 남에게 무언가를 요구하려는 경우 직접 발화보다 청유 형식이나 의문 형식의 간접 발화를 사용하면 공손함이 잘 드러나기도 한다.",
                          num1Text: "발화는 구어를 통한 의사소통의 기본 단위이다.",
                          num2Text: "간접 발화의 의미는 언어 사용 맥락에 기대어 파악된다.",
                          num3Text: "간접 발화가 직접 발화보다 화자의 의도를 더 잘 전달한다.",
                          num4Text: "요청할 때 청유문이나 의문문을 사용하면 더 공손해 보이기도 한다.",
                          answer: 3),
            QuestionModel(num: 9,
                          questionText: "다음 글에 대한 설명으로 적절하지 않은 것은?",
                          reference: "  나는 집이 가난하여 말이 없어서 간혹 남의 말을 빌려 탄다. 노둔하고 여윈 말을 얻게 되면 일이 비록 급하더라도 감히 채찍을 대지 못하고 조심조심 금방 넘어질 듯 여겨서 개울이나 구렁을 지날 때는 말에서 내려 걸어가므로 후회할 일이 적었다. 발굽이 높고 귀가 쫑긋하여 날래고 빠른 말을 얻게 되면 의기양양 마음대로 채찍질하고 고삐를 늦추어 달리니 언덕과 골짜기가 평지처럼 보여 매우 장쾌하지만 말에서 위험하게 떨어지는 근심을 면치 못할 때가 있었다. 아! 사람의 마음이 옮겨지고 바뀌는 것이 이와 같을까? 남의 물건을 빌려서 하루아침의 소용에 쓰는 것도 이와 같은데, 하물며 참으로 자기가 가지고 있는 것이야 어떻겠는가?\n\n-이곡, ‘차마설(借馬說)’-",
                          num1Text: "경험을 통한 통찰력이 돋보인다.",
                          num2Text: "우의적 기법을 적절히 활용하고 있다.",
                          num3Text: "대상들 사이의 유사점을 통해 대상의 특성을 설명하고 있다.",
                          num4Text: "일상사와 관련지어 글쓴이의 주장을 설득력 있게 드러내고 있다.",
                          answer: 3),
            QuestionModel(num: 10,
                          questionText: "다음 글과 같은 방식으로 논리를 전개한 것은?",
                          reference: "  진리가 사상의 체계에 있어 제일의 덕이듯이 정의는 사회적 제도에 있어 제일의 덕이다. 하나의 이론은 그것이 아무리 멋지고 간명한 것이라 하더라도 만약 참되지 않다면 거부되거나 수정되어야 한다. 이와 마찬가지로 법과 제도는 그것이 아무리 효율적으로 잘 정비되어 있다고 하더라도 만약 정의롭지 않다면 개혁되거나 폐기되어야 한다.",
                          num1Text: "의지의 자유가 없는 사람에게는 책임을 물을 수 없다. 그런데 인간에게는 책임을 물을 수 있다. 그러므로 인간의 의지는 자유롭다고 보아야 한다.",
                          num2Text: "여자는 생각하는 것이 남자와 다른 데가 있다. 남자는 미래를 생각하지만 여자는 현재의 상태를 더 소중하게 여긴다. 남자가 모험, 사업, 성 문제를 중심으로 생각한다면 여자는 가정, 사랑, 안정성에 비중을 두어 생각한다.",
                          num3Text: "우리 강아지는 배를 문질러 주면 등을 바닥에 대고 누워 버려. 그리고 정말 기분 좋은 듯한 표정을 짓지. 그런데 내 친구 강아지도 그렇더라고. 아마 모든 강아지가 그런 속성을 가지고 있는 것 같아.",
                          num4Text: "인생은 여행과 같다. 간혹 험난한 길을 만나기도 하고, 예상치 않은 일을 당하기도 한다. 우연히 누군가를 만나고 그들과 관계를 맺기도 한다. 여행을 끝내고 집으로 돌아왔을 때 편안함을 느끼는 것처럼 생을 끝내고 죽음을 맞이할 때 우리는 더없이 편안해질 것이다.",
                          answer: 4),
            QuestionModel(num: 11,
                          questionText: "밑줄 친 부분이 맞춤법에 맞지 않는 것은?",
                          num1Text: "하나에 백 원씩 "+"처주마.".underLined,
                          num2Text: "여름이 되니 몸이 축축 "+"처지네.".underLined,
                          num3Text: "아궁이에서 쓰레기를 "+"처대고".underLined+" 있지.",
                          num4Text: "오는 길에 "+"처박힌".underLined+" 자전거를 보았어.",
                          answer: 1),
            QuestionModel(num: 12,
                          questionText: "밑줄 친 부분 중 보조 용언이 결합되지 않은 것은?",
                          num1Text: "창문 너머로 날이 "+"밝아 온다.".underLined,
                          num2Text: "동생이 내 과자를 "+"먹어 버렸다.".underLined,
                          num3Text: "우체국에 들러 선배의 편지를 "+"부쳐 주었다.".underLined,
                          num4Text: "그는 환갑이 지났지만 40대처럼 "+"젊어 보인다.".underLined,
                          answer: 4),
            QuestionModel(num: 13,
                          questionText: "밑줄 친 부분의 의미 관계가 나머지 셋과 다른 것은?",
                          num1Text: "세 시간이 흐르도록 "+"분분".underLined+"했던 의견들이 마침내 하나로 "+"합치".underLined+" 하였다.",
                          num2Text: "아무리 논리적 "+"사고".underLined+"라 하더라도 거기에는 "+"비판".underLined+"이 따르게 마련이다.",
                          num3Text: "사회적 지위가 높은 사람이 보여주는 "+"겸손".underLined+"은 가끔 "+"오만".underLined+"으로 비칠 수도 있다.",
                          num4Text: "결미".underLined+"에 제시된 결론이 "+"모두".underLined+"에서 진술한 내용과 관련을 맺는다면 좀 더 긴밀한 구성이 될 것이다.",
                          answer: 2),
            QuestionModel(num: 14,
                          questionText: "밑줄 친 사자성어의 쓰임이 적절하지 않은 것은?",
                          num1Text: "그는 결단력이 없어 "+"좌고우면(左顧右眄)".underLined+"하다가 적절한 대응 시기를 놓쳐 버렸다.",
                          num2Text: "다수의 기업이 새로운 투자보다 변화에 대한 "+"암중모색(暗中 摸索)".underLined+"을 시도하고 있다.",
                          num3Text: "그 친구는 "+"침소봉대(針小棒大)".underLined+"하는 경향이 있어서 하는 말을 곧이곧대로 믿기 어렵다.",
                          num4Text: "그 사람이 경제적으로 매우 어려운 상황에서 성공한 것은 "+"연목구어(緣木求魚)".underLined+"나 마찬가지이다.",
                          answer: 4),
            QuestionModel(num: 15,
                          questionText: "㉠～ ㉣에 대한 설명으로 적절하지 않은 것은?",
                          reference: "삼동(三冬)에 ㉠"+"베옷".underLined+" 입고 암혈(巖穴)에 ㉡"+"눈비".underLined+" 맞아\n 구름 낀 볕뉘도 쬔 적이 없건마는\n㉢"+"서산".underLined+"에 해 지다 하니 ㉣"+"눈물겨워".underLined+" 하노라.",
                          num1Text: "㉠ : 화자의 처지나 생활을 추측할 수 있게 한다.",
                          num2Text: "㉡ : 화자와 중심 대상 사이를 연결하는 매개체이다.",
                          num3Text: "㉢ : 화자가 머물고 있는 공간과 구별되는 공간이다.",
                          num4Text: "㉣ : 상황에 대한 화자의 감정이 직접 표출되고 있다.",
                          answer: 2),
            QuestionModel(num: 16,
                          questionText: "(  ) 안에 들어갈 말로 적절한 것은?",
                          reference: "  ‘개살구’, ‘잠’, ‘새파랗다’ 등은 어휘 형태소인 ‘살구’, ‘자－’, ‘파랗－’에 ‘개－’, ‘－ㅁ’, ‘새－’와 같은 접사가 덧붙어서 파생된 단어들이다. 이처럼 직접 구성 요소 중 접사가 확인되는 단어들을 ‘파생어’라고 한다. 반면, (    ) 등은 각각 실질적 의미를 지닌 두 요소가 결합하여 한 단어가 된 경우인데, 이를 ‘파생어’와 구분하여 ‘합성어’라고 한다.",
                          num1Text: "고추장, 놀이터, 손짓, 장군감",
                          num2Text: "면도칼, 서릿발, 쉰둥이, 장난기",
                          num3Text: "깍두기, 선생님, 작은형, 핫바지",
                          num4Text: "김치찌개, 돌다리, 시나브로, 암탉",
                          answer: 1),
            QuestionModel(num: 17,
                          questionText: "다음 글을 읽은 독자의 반응으로 적절한 것은?",
                          reference: "  인문학은 세상에 대한 종합적이고 비판적인 해석과 시각을 제공한다. 인문학이 해석하는 세상은 지금 우리가 살고 있는 세상이다. 현대 사회는 사회의 복잡성이 비교할 수 없을 정도로 증가함에 따라 위험과 불확실성이 커졌으며, 다양한 정보 통신 기술이 정보와 지식의 생산, 유통, 소비를 혁신적으로 바꾸면서 사람들 사이의 새로운 상호 의존 관계를 만들어 낸다는 점에서 과거와는 다른 차별성을 지니고 있다. 이것은 현대 사회가 불확실하고 복잡하며 매일 매일 바쁘게 돌아가는 세상이 되었다는 것, 나아가 지구 구석구석에 존재하는 타인과의 상호 관계가 내 삶에 예기치 못한 영향을 미치는 세상이 되었다는 것을 의미한다. 이러한 세상을 살아가는 데에 인문학은 실질적인 지침을 제공해야 한다.",
                          num1Text: "현대 사회에서 인문학이 담당해야 할 역할에 대해 말하고 있어.",
                          num2Text: "현대 사회의 문제점을 부각시키면서 바람직한 해결 방안을 제시하고 있어.",
                          num3Text: "과거와 현대 사회의 모습을 구체적으로 대조하면서 현대 사회의 특징을 드러내고 있어.",
                          num4Text: "사회의 복잡성으로 인해 타인과의 소통에 장애가 생긴다는 점을 현대 사회의 주요한 특징으로 말하고 있어.",
                          answer: 1),
            QuestionModel(num: 18,
                          questionText: "다음 자료를 활용하여 글을 쓰려고 할 때, 적절하지 않은 것은? (단위 : %, 중복 응답)",
                          imgModel: ImageModel(imageString: "201511-18", imgWidth: 330, imgHeight: 240),
                          num1Text: "인터넷을 이용하면 필요한 정보를 다양하게 얻을 수 있음을 서술한다.",
                          num2Text: "자신의 권리가 침해되지 않도록 보안 강화 방안을 적극적으로 제안한다.",
                          num3Text: "타인의 권리를 침해하지 않도록 인터넷 윤리 교육의 필요성을 강조한다.",
                          num4Text: "인터넷이 잘못된 여론을 형성할 수 있으므로 인터넷 사용을 금지할 것을 주장한다.",
                          answer: 4),
            QuestionModel(num: 19,
                          questionText: "<보기>를 참고하여 ㉠∼ ㉣을 이해한 내용으로 적절하지 않은 것은?",
                          reference: "<보기>\n\n  이용악은 1945년 해방이 되자 고향인 함경북도 경성에 가족을 두고 홀로 상경한다. ‘그리움’은 몹시 추웠던 그해 겨울밤 고향에 두고 온 가족을 그리워하며 쓴 시이다.",
                          reference2: "눈이 오는가 ㉠"+"북쪽".underLined+"엔\n함박눈 쏟아져 내리는가.\n\n험한 벼랑을 굽이굽이 돌아간\n백무선 철길 위에\n느릿느릿 밤새워 달리는\n화물차의 검은 지붕에\n\n연달린 산과 산 사이\n㉡"+"너".underLined+"를 남기고 온\n작은 마을에도 복된 눈 내리는가.\n\n잉크병 얼어드는 ㉢"+"이러한 밤".underLined+"에\n 어쩌자고 ㉣"+"잠".underLined+"을 깨어\n그리운 곳 차마 그리운 곳.\n\n눈이 오는가 북쪽엔\n함박눈 쏟아져 내리는가.\n\n-이용악, ‘그리움’-",
                          num1Text: "㉠은 자신이 떠나온 공간인 고향을 가리키는 것이겠군.",
                          num2Text: "㉡은 고향에 남겨 두고 온 가족을 의미하는 표현이겠군.",
                          num3Text: "㉢은 극심한 추위 속에서도 가족을 떠올리는 시간이겠군.",
                          num4Text: "㉣은 그리운 이를 볼 수 없는 화자의 절망적 심정을 투영한 대상물이겠군.",
                          answer: 4),
            QuestionModel(num: 20,
                          questionText: "다음 글에 나타난 ‘그림 : 액자’의 관계와 가장 비슷한 것은",
                          reference: "  2000년이 된 기념으로 ○○화랑에서 화가 200인의 작품 전시회를 개최하였다. 큐레이터가 보내 준 카탈로그를 보고 전화로 김○○ 화백의 그림을 바로 예약했다. 큐레이터는 “작품이 작은데 병 속에 세 명이 들어가 있어 답답한 느낌이 들지 않느냐?”라고 했지만, 나는 내가 설정한 ‘가족’ 이라는 주제에 어울린다고 생각하여 구입하기로 하였다.\n  전시회가 끝난 뒤 작품을 받아 보니 액자가 그림보다 훨씬 컸다. 이렇게 액자가 크니, 큐레이터의 걱정과는 달리 그림이 답답해 보이지는 않았다. 이것이 바로 ‘액자의 힘’이다. 내가 아는 어떤 애호가는 좋은 액자를 꾸준히 모은다. 갖고 있는 그림의 액자를 바꾸기 위해.",
                          num1Text: "유명 인사들의 사회적 성공은 어디에서 비롯되었을까. 그들은 그 요인으로 하나같이 좋은 습관을 든다. － ‘성공 : 습관’",
                          num2Text: "나는 가끔 책을 장난감 블록처럼 다양하게 쌓아 본다. 책의 무거움, 진부함, 지루함을 해소하고, 즐겁고 유쾌하게 책을 재발견하고자 하는 것이다. － ‘책 : 장난감 블록’",
                          num3Text: "로댕은 돌을 바라봅니다. 그 안에서 손을 발견합니다. 그리고 자신의 손을 움직여 돌 속의 손을 끄집어내려고 합니다. 그러다 실패하지요. 실패했다고 포기하지 않고 로댕은 다시 새 돌을 꺼내 바라봅니다. － ‘돌 : 손’",
                          num4Text: "인간은 단 몇 초 만에 상대방에 대한 호감도를 결정한다고 한다. 몇 초 만에 자신의 내면을 드러내기가 쉽지 않다는 것을 고려하면, 내면을 돋보이게 할 수 있는 옷차림은 분명 무시할 수 없는 요인이다. － ‘내면 : 옷차림’",
                          answer: 4)
        ]
        
        let exam = ExamModel(id: 201511, year: 2015, examTypeID: "국가직", subjectID: "국어", questions: questions)
        exam2015.append(exam)
    }
    
    func saveExam201512() {
        let questions =
        [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분에 가장 적절한 것을 고르시오. [1～2]",
                      reference: "The young knight was so ________ at being called a coward that he charged forward with his sword in hand.",
                      num1Text: "aloof",
                      num2Text: "incensed",
                      num3Text: "unbiased",
                      num4Text: "unpretentious",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "",
                      reference: "Back in the mid-1970s, an American computer scientist called John Holland _________ the idea of using the theory of evolution to solve notoriously difficult problems in science.",
                      num1Text: "took on",
                      num2Text: "got on",
                      num3Text: "put upon",
                      num4Text: "hit upon",
                      answer: 4),
        QuestionModel(num: 3,
                      questionText: "내용의 흐름상 적절하지 못한 문장은?",
                      reference: "Of equal importance in wars of conquest were the germs that evolved in human societies with domestic animals. ①"+"Infectious diseases like smallpox, measles, and flu arose as specialized germs of humans, derived by mutations of very similar ancestral germs that had infected animals.".underLined+" ②"+"The most direct contribution of plant and animal domestication to wars of conquest was from Eurasia's horses, whose military role made them the jeeps and Sherman tanks of ancient warfare on that continent.".underLined+" ③"+"The humans who domesticated animals were the first to fall victim to the newly evolved germs, but those humans then evolved substantial resistance to the new disease.".underLined+" ④"+"When such partly immune people came into contact with others who had had no previous exposure to the germs, epidemics resulted in which up to 99 percent of the previously unexposed population was killed.".underLined+" Germs thus acquired ultimately from domestic animals played decisive roles in the European conquests of Native Americans, Australians, South Africans, and Pacific islanders.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 2),
        QuestionModel(num: 4,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "Everyone knows what the Mona Lisa and Michelangelo's David look like-or do we? They are reproduced so often that we may feel we know them even if we have never been to Paris or Florence. Each has countless spoofs -David in boxer shorts or the Mona Lisa with a mustache. Art reproductions are ubiquitous. We can now sit in our pajamas while enjoying virtual tours of galleries and museums around the world via the Web and CD-ROM. We can explore genres and painters and zoom in to scrutinize details. The Louvre's Website offers spectacular 360-degree panoramas of artworks like the Venus de Milo. Such tours may become ever more multi-sensory by drawing on virtual reality technology, which includes things like goggles and gloves. Lighting and stage set designers, like architects, already use this technology in their work.",
                      num1Text: "Should We Ban Art Reproductions?",
                      num2Text: "Why Are Virtual Artworks So Popular?",
                      num3Text: "Art : More Widely Accessible Than Ever!",
                      num4Text: "Secrets of Vanished Galleries and Museums",
                      answer: 3),
        QuestionModel(num: 5,
                      questionText: "어법상 옳지 않은 것은?",
                      num1Text: "The main reason I stopped smoking was that all my friends had already stopped smoking.",
                      num2Text: "That a husband understands a wife does not mean they are necessarily compatible.",
                      num3Text: "The package, having wrong addressed, reached him late and damaged.",
                      num4Text: "She wants her husband to buy two dozen of eggs on his way home.",
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "어법상 옳은 것은?",
                      num1Text: "China's imports of Russian oil skyrocketed by 36 percent in 2014.",
                      num2Text: "Sleeping has long been tied to improve memory among humans.",
                      num3Text: "Last night, she nearly escaped from running over by a car.",
                      num4Text: "The failure is reminiscent of the problems surrounded the causes of the fatal space shuttle disasters.",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "밑줄 친 부분에 가장 적절한 것을 고르시오. [7～8]",
                      reference: "  A:What business is on your mind?\n  B:Do you think that owning a flower shop has good prospects nowadays?\n  A:It could. But have you prepared yourself mentally and financially?\n  B : ______________________________.\n  A:Good! Then you should choose a strategic place and the right segment too. You must do a thorough research to have a good result.\n  B : I know that. It’s much easier to start a business than to run it well.",
                      num1Text: "I plan to go to the hospital tomorrow",
                      num2Text: "I can't be like that! I must strive to get a job",
                      num3Text: "I'm ready to start with what I have and take a chance",
                      num4Text: "I don't want to think about starting my own business",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "",
                      reference: "  M: What's that noise?\n  W: Noise? I don't hear anything.\n  M:Listen closely. I hear some noise. _________________.\n  W: Oh, let's stop and see.\n  M:Look! A piece of glass is in the right front wheel.\n  W:Really? Umm... You're right. What are we going to do?\n  M:Don't worry. I got some experience in changing tires.",
                      num1Text: "I gave my customers sound advice",
                      num2Text: "Maybe air is escaping from the tire",
                      num3Text: "I think the mechanic has an appointment",
                      num4Text: "Oh! Your phone is ringing in vibration mode",
                      answer: 2),
        QuestionModel(num: 9,
                      questionText: "다음 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "We can in consequence establish relations with almost all sorts of them.",
                      reference2: "Reptiles and fish may no doubt be found in swarms and shoals; they have been hatched in quantities and similar conditions have kept them together. In the case of social and gregarious mammals, the association arises not simply from a community of external forces but is sustained by an inner impulse. They are not merely like one another and so found in the same places at the same times; they like one another and so they keep together. This difference between the reptile world and the world of our human minds is one our sympathies seem unable to pass. (  A  ) We cannot conceive in ourselves the swift uncomplicated urgency of a reptile's instinctive motives, its appetites, fears and hates. (  B  ) We cannot understand them in their simplicity because all our motives are complicated; ours are balances and resultants and not simply urgencies. (  C  ) But the mammals and birds have self-restraint and consideration for other individuals, a social appeal, a self-control that is, at its lower level, after our own fashion. (  D  ) When they suffer they utter cries and make movements that rouse our feelings. We can make pets of them with a mutual recognition. They can be tamed to self-restraint towards us, domesticated and taught.",
                      num1Text: "A",
                      num2Text: "B",
                      num3Text: "C",
                      num4Text: "D",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "Thunderstorms are extremely common in many parts of the world, for example, throughout most of North America. Updrafts of warm air set off these storms.",
                      reference2: "(A) This more buoyant air then rises and carries water vapor to higher altitudes. The air cools as it rises, and the water vapor condenses and starts to drop as rain. As the rain falls, it pulls air along with it and turns part of the draft downward.\n\n(B) An updraft may start over ground that is more intensely heated by the sun than the land surrounding the area. Bare, rocky, or paved areas, for example, usually have updrafts above them. The air in contact with the ground heats up and thus becomes lighter, more buoyant, than the air surrounding it.\n\n(C) The draft may turn upward again and send the rain churning around in the cloud. Some of it may freeze to hail. Sooner or later, the water droplets grow heavy enough to resist the updrafts and fall to the ground, pulling air in the form of downdrafts with them.",
                      num1Text: "(A)-(C)-(B)",
                      num2Text: "(B)-(A)-(C)",
                      num3Text: "(B)-(C)-(A)",
                      num4Text: "(C)-(A)-(B)",
                      answer: 2),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 부분과 의미가 가장 가까운 것을 고르시오. [11～12]",
                      reference: "He took out a picture from his drawer and kissed it with deep reverence, folded it "+"meticulously".underLined+" in a white silk kerchief, and placed it inside his shirt next to his heart.",
                      num1Text: "carefully",
                      num2Text: "hurriedly",
                      num3Text: "decisively",
                      num4Text: "delightfully",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "",
                      reference: " The company cannot expect me to move my home and family "+"at the drop of a hat.".underLined,
                      num1Text: "immediately",
                      num2Text: "punctually",
                      num3Text: "hesitantly",
                      num4Text: "periodically",
                      answer: 1),
        QuestionModel(num: 13,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "America gets 97 % of its limes from Mexico, and a combination of bad weather and disease has sent that supply plummeting and prices skyrocketing. A 40-lb. (18 kg) box of limes that cost the local restaurateurs about $20 late last year now goes for $ 120. In April, the average retail price for a lime hit 56 cents, more than double the price last year. Across the U.S., bars and restaurants are rationing their supply or, like Alaska Airlines, eliminating limes altogether. In Mexico, the value spike is attracting criminals, forcing growers to guard their limited supply of “green gold” from drug cartels. Business owners who depend on citrus are hoping that spring growth will soon bring costs back to normal.",
                      num1Text: "An Irreversible Change in Wholesale Price of Lime",
                      num2Text: "Mexican Lime Cartel Spreading to the U.S.",
                      num3Text: "Americans Eat More Limes than Ever",
                      num4Text: "A Costly Lime Shortage",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "다음 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "Print, however, with its standard format and type, introduced exact mass reproduction.",
                      reference2: "Print transformed how knowledge itself was understood and transmitted. A manuscript is a unique and unreproducible object. (  A  ) This meant that two readers separated by distance could discuss and compare identical books, right down to a specific word on a particular page. (  B  ) With the introduction of consistent pagination, indexes, alphabetic ordering, and bibliographies (all unthinkable in manuscript), knowledge itself was slowly repackaged. (  C  ) Textual scholarship became a cumulative science, as scholars could now gather manuscripts of, say, Aristotle's Politics and print a standard authoritative edition based on a comparison of all available copies. (  D  ) This also led to the phenomenon of new and revised editions.",
                      num1Text: "A",
                      num2Text: "B",
                      num3Text: "C",
                      num4Text: "D",
                      answer: 1),
        QuestionModel(num: 15,
                      questionText: "다음 글의 내용과 일치하는 것은?",
                      reference: "The WAIS-R is made up of eleven subtests, or scales. The subtests of the WAIS-R are arranged by the type of ability or skill being tested. The subtests are organized into two categories. Six subtests define the verbal scale, and five subtests constitute a performance scale. We can compute three scores: a verbal score, a performance score, and a total (or full-scale) score. The total score can be taken as an approximation of general intellectual ability. To administer the WAIS-R, you present each of the eleven subtests to your subject. The items within each subtest are arranged in order of difficulty. You start with relatively easy items, and then you progress to more difficult ones. You stop administering any one subtest when your subject fails a specified number of items in a row. You alternate between verbal and performance subtests. The whole process takes up to an hour and a half.",
                      num1Text: "The WAIS-R has eleven subtests, each of which has two main parts.",
                      num2Text: "Several subtests with higher scores among the eleven ones should be presented.",
                      num3Text: "The items of each subtest in the WAIS-R begin from easy and continue on to more difficult ones.",
                      num4Text: "Subjects take all of the verbal subtests first and then all of the performance subtests.",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "밑줄 친 부분에 가장 적절한 것은?",
                      reference: "Language is saturated with implicit metaphors like “Events are objects and time is space.” Indeed, space turns out to be a conceptual vehicle not just for time but for many kinds of states and circumstances. Just as a meeting can be moved from 3:00 to 4:00, a traffic light can go from green to red, a person can go from flipping burgers to running a corporation, and the economy can go from bad to worse. Metaphor is so widespread in language that it's hard to find expressions for abstract ideas that are not metaphorical. Does it imply that even our wispiest concepts are represented in the mind as hunks of matter that we move around on a mental stage? Does it say that rival claims about the world can never be true or false but can only be _____________________? Few things in life cannot be characterized in terms of variables and the causation of changes in them.",
                      num1Text: "proven to be always true in all circumstances",
                      num2Text: "irreversible and established truths that cannot be disputed",
                      num3Text: "subject to scientific testings for their authenticity and clarity",
                      num4Text: "alternative metaphors that frame a situation in different ways",
                      answer: 4),
        QuestionModel(num: 17,
                      questionText: "우리말을 영어로 잘못 옮긴 것을 고르시오. [17～18]",
                      num1Text: "가능한 모든 일자리를 알아보았음에도 불구하고, 그는 적당한 일자리를 찾지 못했다.\n→ Despite searching for every job opening possible, he could not find a suitable job.",
                      num2Text: "당신이 누군가를 믿을 수 있는지 알아보는 최선책은 그 사람을 믿는 것이다.\n→ The best way to find out if you can trust somebody is to trust that person.",
                      num3Text: "미각의 민감성은 개인의 음식 섭취와 체중에 크게 영향을 미친다.\n→ Taste sensitivity is largely influenced by food intake and body weight of individuals.",
                      num4Text: "부모는 그들의 자녀가 성장하고 학습하는 데 알맞은 환경을 제공할 책임이 있다.\n→ Parents are responsible for providing the right environment for their children to grow and learn in.",
                      answer: 3),
        QuestionModel(num: 18,
                      questionText: "",
                      num1Text: "그는 자신의 정적들을 투옥시켰다.\n→ He had his political enemies imprisoned.",
                      num2Text: "경제적 자유가 없다면 진정한 자유가 있을 수 없다.\n→ There can be no true liberty unless there is economic liberty.",
                      num3Text: "나는 가능하면 빨리 당신과 거래할 수 있기를 바란다.\n→ I look forward to doing business with you as soon as possible.",
                      num4Text: "30년 전 고향을 떠날 때, 그는 다시는 고향을 못 볼 거라고 꿈에도 생각지 않았다.\n→ When he left his hometown thirty years ago, little does he dream that he could never see it again.",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "다음 글의 ㉠, ㉡에 들어갈 가장 적절한 것은?",
                      reference: "The chimpanzee － who puts two sticks together in order to get at a banana because no one of the two is long enough to do the job － uses intelligence. So do we all when we go about our business, “figuring out” how to do things. Intelligence, in this sense, is taking things for granted as they are, making combinations which have the purpose of facilitating their manipulation; intelligence is thought in the service of biological survival. Reason,  ㉠  , aims at understanding; it tries to find out what is beneath the surface, to recognize the kernel, the essence of the reality which surrounds us. Reason is not without a function, but its function is not to further physical as much as mental and spiritual existence.  ㉡  , often in individual and social life, reason is required in order to predict (considering that prediction often depends on recognition of forces which operate underneath the surface), and prediction sometimes is necessary even for physical survival.",
                      num1Text: "for example - Therefore",
                      num2Text: "in the same way - Likewise",
                      num3Text: "consequently - As a result",
                      num4Text: "on the other hand - However",
                      answer: 4),
        QuestionModel(num: 20,
                      questionText: "다음 글의 내용과 일치하지 않는 것은?",
                      reference: "East of the Mississippi, the land rises slowly into the foothills of the Appalachian Mountains. At the edge of the Canadian plains, the Canadian Shield, a giant core of rock centered on the Hudson and James Bays, anchors the continent. The stony land of the Shield makes up the eastern half of Canada and the northeastern United States. In northern Quebec, the Canadian Shield descends to the Hudson Bay. The heavily eroded Appalachian Mountains are North America's oldest mountains and the continent's second-longest mountain range. They extend about 1,500 miles from Quebec to central Alabama. Coastal lowlands lie east and south of the Appalachians. Between the mountains and the coastal lowlands lies a wide area of rolling hills. Many rivers cut through the Piedmont and flow across to the Atlantic Coastal Plain in the Carolinas.",
                      num1Text: "Centered on the Hudson and James Bays is a giant core of rock, the Canadian Shield.",
                      num2Text: "The Appalachian Mountains are North America's longest mountain range.",
                      num3Text: "From Quebec to central Alabama, the Appalachian Mountains stretch.",
                      num4Text: "The Piedmont is traversed by many rivers that flow toward the Plain.",
                      answer: 2)
        ]
        
        let exam = ExamModel(id: 201512, year: 2015, examTypeID: "국가직", subjectID: "영어", questions: questions)
        
        exam2015.append(exam)
    }
    
    func saveExam201513() {
        let questions =
        [
        QuestionModel(num: 1,
                      questionText: "고려 사회의 모습으로 옳지 않은 것은?",
                      num1Text: "천민 출신인 이의민이 무신 정권의 최고 권력자가 되었다.",
                      num2Text: "외거 노비가 재산을 늘려, 그 처지가 양인과 유사해질 수 있었다.",
                      num3Text: "지방 향리의 자제가 과거(科擧)를 통해 귀족의 대열에 진입할 수 있었다.",
                      num4Text: "향․부곡․소의 백성도 일반 군현민과 동일한 수준의 조세․ 공납․역을 부담하였다.",
                      answer: 4),
        QuestionModel(num: 2,
                      questionText: "조선 전기(15 ～ 16세기) 사림의 향촌을 주도하기 위한 동향으로 옳지 않은 것은?",
                      num1Text: "도덕과 의례의 기본 서적인 〖소학〗을 보급하였다.",
                      num2Text: "향사례(鄕射禮), 향음주례(鄕飮酒禮)의 실시를 주장하였다.",
                      num3Text: "향회를 통해서 자신들의 결속을 다지고, 향촌을 교화하였다",
                      num4Text: "촌락 단위의 동약을 실시하고, 문중 중심으로 서원과 사우를 많이 세웠다.",
                      answer: 4),
        QuestionModel(num: 3,
                      questionText: "과전법과 그 변화에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "수신전, 휼양전을 죽은 관료의 가족에게 지급하였다.",
                      num2Text: "공음전을 5품 이상의 관료에게 주어 세습을 허용하였다.",
                      num3Text: "세조대에 직전법으로 바꾸어 현직 관리에게만 수조권을 지급 하였다.",
                      num4Text: "성종대에는 관수관급제를 실시하여 전주의 직접 수조를 지양 하였다.",
                      answer: 2),
        QuestionModel(num: 4,
                      questionText: "다음은 동학농민운동과 관련한 연표이다. (가) ～(라) 시기에 있었던 사실로 옳은 것은?",
                      imgModel: ImageModel(imageString: "201513-4", imgWidth: 330, imgHeight: 170),
                      num1Text: "(가) － 황토현 전투",
                      num2Text: "(나) － 청․일 전쟁의 발발",
                      num3Text: "(다) － 남․북접군의 논산 집결",
                      num4Text: "(라) － 일본군의 경복궁 점령",
                      answer: 4),
        QuestionModel(num: 5,
                      questionText: "다음 자료에 대한 해석으로 가장 적절한 것은?",
                      reference: "○ 신라 지증왕 3년의 순장 금지 사료(史料)\n\n○ 신라 무덤에서 출토한 순장 대용(代用) 흙인형",
                      num1Text: "전쟁 노비의 소멸로 순장할 대상이 없어졌다.",
                      num2Text: "농업생산력의 상승에 따라 노동력을 중시하였다.",
                      num3Text: "죽음에 대한 의식(儀式)에 도교 사상이 반영되었다.",
                      num4Text: "왕실은 귀족층의 사치와 허례허식을 막기 위해 노력하였다.",
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 ‘이 시대’의 사회 모습으로 옳은 것은?",
                      reference: "이 시대".underLined+"의 황해도 봉산 지탑리와 평양 남경 유적에서 탄화된 좁쌀이 발견되는 것으로 보아 잡곡류 경작이 이루어 졌음을 알 수 있다. 농경의 발달로 수렵과 어로가 경제 생활에서 차지하는 비중이 줄어들기 시작하였지만, 여전히 식량을 얻는 중요한 수단이었다. 한편 가락바퀴나 뼈바늘을 이용하여 옷이나 그물을 만드는 등 원시적인 수공업 생산이 이루어지기 시작하였다.",
                      num1Text: "생산물의 분배 과정에서 사유 재산 제도가 등장하였다.",
                      num2Text: "마을 주변에 방어 및 의례 목적으로 환호(도랑)를 두르기도 하였다.",
                      num3Text: "흑요석의 출토 사례로 보아 원거리 교류나 교역이 있었음을 알 수 있다.",
                      num4Text: "집자리는 주거용 외에 창고, 작업장, 집회소, 공공 의식 장소 등도 확인되었다.",
                      answer: 2),
        QuestionModel(num: 7,
                      questionText: "조선 전기(15∼16세기) 중앙 정치에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "붕당은 정치적 이념과 학문적 경향에 따라 결집되었다.",
                      num2Text: "삼사는 권력의 독점과 부정을 방지하는 데 기여하였다.",
                      num3Text: "사화로 갈등이 격화되면서, 정국이 급격하게 전환되는 환국정치가 시작되었다.",
                      num4Text: "합리적인 인사 행정 제도가 갖추어져 이전 시기보다 관료제적 성격이 강해졌다.",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "다음 건의를 받아들인 왕이 실시한 정책으로 옳은 것은",
                      reference: "임금이 백성을 다스릴 때 집집마다 가서 날마다 그들을 살펴보는 것이 아닙니다. 그래서 수령을 나누어 파견하여, (현지에) 가서 백성의 이해(利害)를 살피게 하는 것입니다. 우리 태조께서도 통일한 뒤에 외관(外官)을 두고자 하셨으나, 대개 (건국) 초창기였기 때문에 일이 번잡하여 미처 그럴 겨를이 없었습니다. 이제 제가 살펴보건대, 지방 토호들이 늘 공무를 빙자하여 백성들을 침해하며 포악하게 굴어, 백성들이 명령을 견뎌내지 못합니다. 외관을 두시기 바랍니다.",
                      num1Text: "서경 천도를 추진하였다.",
                      num2Text: "5도 양계의 지방 제도를 확립하였다.",
                      num3Text: "지방 교육을 위해 경학박사를 파견하였다.",
                      num4Text: "유교 이념과는 별도로 연등회, 팔관회 행사를 장려하였다.",
                      answer: 3),
        QuestionModel(num: 9,
                      questionText: "신라 승려 ㉠과 ㉡에 대한 설명으로 옳지 않은 것은?",
                      reference: "(  ㉠  )은(는) 불교 서적을 폭넓게 이해하고, 일심(一心) 사상을 바탕으로 여러 종파들의 사상적 대립을 조화시키며, 분파 의식을 극복하려고 노력하였다. 한편 (  ㉡  )은(는) 모든 존재가 상호 의존적인 관계에 있으면서 서로 조화를 이룬다는 화엄 사상을 정립하고, 교단을 형성하여 많은 제자를 양성하였다.",
                      num1Text: "㉠은 미륵 신앙을 전파하며 불교 대중화의 길을 열었다.",
                      num2Text: "㉠은 무애가라는 노래를 유포하며 일반 백성을 교화하였다.",
                      num3Text: "㉡은 관음 신앙과 함께 아미타 신앙을 화엄 교단의 주요 신앙으로 삼았다.",
                      num4Text: "㉡은 국왕이 큰 공사를 일으켜 도성을 새로이 정비하려 할 때 백성을 위해 이를 만류하였다.",
                      answer: 1),
        QuestionModel(num: 10,
                      questionText: "밑줄 친 ㉠, ㉡에 대한 설명으로 옳은 것은?",
                      reference: "일제의 가혹한 탄압으로 독립 운동은 큰 제약을 받게 되었다. 그러나 그러한 제약 속에서도 비밀 결사의 형태로 독립 운동 단체가 결성되었다. ㉠"+"독립의군부".underLined+"와 ㉡"+"대한광복회".underLined+"는 모두 이러한 비밀 결사 단체였다.",
                      num1Text: "㉠은 공화국의 건설을 목표로 하였다.",
                      num2Text: "㉡은 고종의 비밀 지령을 받아 조직되었다.",
                      num3Text: "㉠과 ㉡은 모두 1910년대 국내에서 결성된 단체이다.",
                      num4Text: "㉠은 박상진을 중심으로, ㉡은 임병찬을 중심으로 한 조직 이었다.",
                      answer: 3),
        QuestionModel(num: 11,
                      questionText: "통일신라의 지방 행정 조직에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "신문왕 대에 9주 5소경 체제로 정비하였다.",
                      num2Text: "주(州)에는 지방 감찰관으로 보이는 외사정이 배치되었다.",
                      num3Text: "5소경을 전략적 요충지에 두고, 도독이 행정을 관할토록 하였다.",
                      num4Text: "촌주가 관할하는 촌 이외에, 향․부곡이라는 행정 구역도 있었다.",
                      answer: 3),
        QuestionModel(num: 12,
                      questionText: "고려의 농민을 위한 정책으로 옳지 않은 것은?",
                      num1Text: "농민 자제의 과거를 위한 기금으로 광학보를 설치하였다.",
                      num2Text: "개간지는 일정 기간 면세하여 줌으로써 농민의 부담을 경감해 주었다.",
                      num3Text: "재해를 당했을 때에는 세금을 감면해 농민 생활의 안정을 꾀하였다.",
                      num4Text: "농번기에는 잡역 동원을 금지하여 농사에 지장을 주지 않으려 하였다.",
                      answer: 1),
        QuestionModel(num: 13,
                      questionText: "다음의 자료에 보이는 시기의 경제 동향에 대한 설명으로 옳지 않은 것은?",
                      reference: "배에 물건을 싣고 오가면서 장사하는 장사꾼은 반드시 강과 바다가 이어지는 곳에서 이득을 얻는다. 전라도 나주의 영산포, 영광의 법성포, 흥덕의 사진포, 전주의 사탄은 비록 작은 강이나 모두 바닷물이 통하므로 장삿배가 모인다. … (중략) … 그리하여 큰 배와 작은 배가 밤낮으로 포구에 줄을 서고 있다.\n\n － 〖비변사등록〗 -",
                      num1Text: "강경, 원산 등이 상업 중심지로 성장하였다.",
                      num2Text: "선상은 선박을 이용해서 각 지방의 물품을 거래하였다.",
                      num3Text: "객주나 여각은 상품의 매매를 중개하고, 숙박, 금융 등의 영업도 하였다.",
                      num4Text: "상업 활동이 활발해지면서 삼한통보 등의 동전을 만들어 유통 하였다.",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "다음 중 ‘대한국 국제’의 내용에 해당되는 것은?",
                      num1Text: "내시부를 없애고 그 중에 우수한 인재를 등용한다.",
                      num2Text: "조세의 부과와 징수, 경비의 지출은 모두 탁지아문이 관할한다.",
                      num3Text: "칙임관은 황제가 정부에 자문하여 그 과반수의 의견에 따라 임명한다.",
                      num4Text: "대한국 대황제는 각 조약 체결 국가에 사신을 파견하고, 선전 강화(宣戰講和) 및 제반 조약을 체결한다.",
                      answer: 4),
        QuestionModel(num: 15,
                      questionText: "연표의 (가), (나) 시기에 있었던 사실로 옳은 것은?",
                      imgModel: ImageModel(imageString: "201513-15", imgWidth: 330, imgHeight: 160),
                      num1Text: "(가) － 인천상륙작전이 실시되었다.",
                      num2Text: "(가) － 중국군의 참전으로 인해 한국군은 서울에서 후퇴하게 되었다.",
                      num3Text: "(나) － 애치슨 선언이 발표되었다.",
                      num4Text: "(나) － 유엔 안전보장이사회에서 유엔군 파병이 결정되었다.",
                      answer: 1),
        QuestionModel(num: 16,
                      questionText: "다음 두 사건이 일어난 이후의 사실로 옳은 것만을 <보기>에서 모두 고른 것은?",
                      reference: "○ 고종 황제의 강제 퇴위\n○ 일제에 의한 군대 해산",
                      reference2: "<보기>\n\n  ㄱ. 안중근이 만주 하얼빈에서 이토 히로부미를 사살하였다.\n  ㄴ. 민영환이 일제에 대한 저항을 강력하게 표현한 유서를 남기고 자결하였다.\n  ㄷ. 장지연이 민족의식을 고취하는 ‘시일야방성대곡’을 황성신문에 발표하였다.\n  ㄹ. 이인영을 총대장으로 하는 13도 연합 의병 부대(창의군)가 서울진공작전을 시도하였다.",
                      num1Text: "ㄱ, ㄴ",
                      num2Text: "ㄱ, ㄹ",
                      num3Text: "ᄂ, ᄃ",
                      num4Text: "ᄃ,ᄅ",
                      answer: 2),
        QuestionModel(num: 17,
                      questionText: "우리나라 농서에 대한 설명으로 옳은 것은?",
                      num1Text: "〖농가집성〗은 고려 말 이암이 원에서 들여온 것이다.",
                      num2Text: "〖농사직설〗은 정초 등이 왕명을 받아 편찬한 것이다.",
                      num3Text: "〖산림경제〗는 박세당이 과수, 축산 등을 소개한 것이다.",
                      num4Text: "〖과농소초〗는 홍만선이 화초재배법에 대해 저술한 것이다.",
                      answer: 2),
        QuestionModel(num: 18,
                      questionText: "다음의 기록이 보이는 왕대의 정치 변화를 바르게 설명한 것은?",
                      reference: "(왕이) 양역을 절반으로 줄이라고 명하셨다. 왕이 말하였다. “호포나 결포는 모두 문제점이 있다. 이제는 1필로 줄이는 것으로 온전히 돌아갈 것이니 경들은 대책을 강구하라.”",
                      num1Text: "특정 붕당이 정권을 독점하는 일당 전제화의 추세가 대두되었다.",
                      num2Text: "왕위 계승에 대한 정통성과 관련하여 두 차례의 예송이 발생 하였다.",
                      num3Text: "정치 집단은 소수의 가문 출신으로 좁아지면서 그 기반이 축소 되었다.",
                      num4Text: "붕당을 없애자는 논리에 동의하는 관료들을 중심으로 탕평 정국을 운영하였다.",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "밑줄 친 ‘우리’에 해당하는 계층의 활동으로 옳은 것은?",
                      reference: "아! "+"우리".underLined+"는 본시 모두 사대부였는데 혹은 의(醫)에 들어가고 혹은 역(譯)에 들어가 7, 8대 또는 10여 대를 대대로 전하니 … (중략) … 문장과 덕(德)은 비록 사대부에 비길 수 없으나, 명공(名公) 거실(巨室) 외에 "+"우리".underLined+"보다 나은 자는 없다.",
                      num1Text: "집단으로 상소하여 청요직(淸要職) 허통(許通)을 요구하였다.",
                      num2Text: "형평사를 창립하고, 평등한 대우를 요구하는 형평운동을 펼쳤다.",
                      num3Text: "관권과 결탁하고 향회를 장악하여, 향촌 사회에서 영향력을 키우려 하였다.",
                      num4Text: "유향소를 복립하여 향리를 감찰하고 향촌 사회의 풍속을 바로 잡으려 하였다.",
                      answer: 1),
        QuestionModel(num: 20,
                      questionText: "(가) ～ (라)는 광복을 전후해 일어난 사건을 시기순으로 나열한 것이다. (다)에 들어갈 수 있는 내용으로 적절하지 않은 것은?",
                      reference: "  (가) 삼균주의를 바탕으로 대한민국 임시 정부가 ‘대한민국 건국 강령’을 발표하였다.\n  (나) 이승만을 중심으로 독립촉성중앙협의회가 발족되었다.\n  (다)\n  (라) 제헌 국회에서 대한민국의 헌법이 제정, 공포되었다.",
                      num1Text: "좌우합작위원회의 ‘좌우합작 7원칙’이 선포되었다.",
                      num2Text: "김구의 ‘삼천만 동포에게 읍고함’이라는 글이 발표되었다.",
                      num3Text: "여운형, 안재홍 등을 중심으로 조선건국준비위원회가 조직되었다.",
                      num4Text: "유엔 총회에서 유엔 감시 하에 인구 비례에 의한 남북한 총선거의 실시가 결의되었다.",
                      answer: 3)
        ]
        
        let exam = ExamModel(id: 201513, year: 2015, examTypeID: "국가직", subjectID: "한국사", questions: questions)
        
        exam2015.append(exam)
    }
}
