//
//  ExamStore2017.swift
//  HandGosi
//
//  Created by Sy Lee on 2022/08/22.
//

import Foundation

class ExamStore2017 {
    var exam2017: [ExamModel] = []
    
    init() {
        saveExam201711()
        saveExam201712()
        saveExam201713()
        
        saveExam201721()
        saveExam201722()
        saveExam201723()
    }
    
    //국가직
    func saveExam201711() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "다음 시가의 전개 방식으로 옳은 것은?",
                      reference: "龜何龜何\n首其現也\n若不現也\n燔灼而喫也\n\n－ 〖구지가〗 －",
                      num1Text: "요구 － 위협 － 환기 － 조건",
                      num2Text: "환기 － 요구 － 조건 － 위협",
                      num3Text: "위협 － 조건 － 환기 － 요구",
                      num4Text: "조건 － 요구 － 위협 － 환기",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "화자의 처지나 행위에 대한 분석으로 옳지 않은 것은?",
                      reference: "흐르는 것이 물뿐이랴\n우리가 저와 같아서\n강변에 나가 삽을 씻으며\n거기 슬픔도 퍼다 버린다\n일이 끝나 저물어\n스스로 깊어 가는 강을 보며\n쭈그려 앉아 담배나 피우고\n나는 돌아갈 뿐이다.\n삽자루에 맡긴 한 생애가\n이렇게 저물고, 저물어서\n샛강 바닥 썩은 물에\n달이 뜨는구나\n우리가 저와 같아서\n흐르는 물에 삽을 씻고\n먹을 것 없는 사람들의 마을로\n다시 어두워 돌아가야 한다.\n\n－ 정희성, 〖저문 강에 삽을 씻고〗 －",
                      num1Text: "화자는 일을 마치고, 해 지는 강변에 나와 삽을 씻는다.",
                      num2Text: "화자는 강물에 슬픔을 퍼다 버리고, ‘먹을 것 없는 사람들의 마을’로 돌아가야 한다.",
                      num3Text: "화자는 ‘삽자루에 맡긴 한 생애’라는 표현을 통해 자신의 삶을 압축적으로 드러낸다.",
                      num4Text: "화자는 주관적인 감정을 배제하고, 해 지는 강가의 풍경을 객관적으로 전달하려 한다.",
                      answer: 4),
        QuestionModel(num: 3,
                      questionText: "밑줄 친 부분과 관련된 사자 성어로 가장 적절한 것은?",
                      reference: "  전국 시대 말, 진나라의 공격을 받은 조나라 혜문왕은 동생인 평원군을 초나라에 보내어 구원군을 청하기로 했다. 이십 명의 수행원이 필요한 평원군은 그의 삼천여 식객 중에서 십구 명은 쉽게 뽑았으나, 나머지 한 명을 뽑지 못한 채 고심했다. 이때에 모수라는 식객이 나섰다. 평원군은 어이없어하며 자신의 집에 언제부터 있었는지 물었다. 모수가 삼 년이 되었다고 대답하자 평원군은 재능이 뛰어난 사람은 숨어 있어도 저절로 사람들에게 알려지게 되는 법인데, 모수의 이름을 들어본 적이 없다고 답했다. 그러자 모수는 "+"“나리께서 이제까지 저를 단 한 번도 주머니 속에 넣어 주시지 않았기 때문입니다. 하지만 이번에 주머니 속에 넣어 주신다면 끝뿐이 아니라 자루까지 드러날 것입니다.”".underLined+" 하고 재치 있는 답변을 했다. 만족한 평원군은 모수를 수행원으로 뽑았고, 초나라에 도착한 평원군은 모수가 활약한 덕분에 국빈으로 환대받고, 구원군도 얻을 수 있었다.",
                      num1Text: "吳越同舟",
                      num2Text: "囊中之錐",
                      num3Text: "馬耳東風",
                      num4Text: "近墨者黑",
                      answer: 2),
        QuestionModel(num: 4,
                      questionText: "다음 글을 읽고 추론한 내용으로 적절하지 않은 것은?",
                      reference: "  사방이 어두워지자 그들도 얘기를 그쳤다. 어디에나 눈이 덮여 있어서 길을 잘 분간할 수가 없었다. 뒤에 처졌던 백화가 눈 덮인 길의 고랑에 빠져 버렸다. 발이라도 삐었는지 백화는 꼼짝 못하고 주저앉아 신음을 했다. 영달이가 달려들어 싫다고 뿌리치는 백화를 업었다. 백화는 영달이의 등에 업히면서 말했다.\n  “무겁죠?”\n  영달이는 대꾸하지 않았다. 백화가 어린애처럼 가벼웠다. 등이 불편하지도 않았고 어쩐지 가뿐한 느낌이었다. 아마 쇠약해진 탓이리라 생각하니, 영달이는 어쩐지 대전에서의 옥자가 생각나서 눈시울이 화끈했다. 백화가 말했다. “어깨가 참 넓으네요. 한 세 사람쯤 업겠어.”\n  “댁이 근수가 모자라니 그렇다구.”\n\n－ 황석영, 〖삼포 가는 길〗 중에서 －",
                      num1Text: "‘눈 덮인 길의 고랑’은 백화가 신음하는 계기로 작용하기도 한다.",
                      num2Text: "등에 업힌 백화는 영달이가 ‘옥자’를 떠올리는 계기로 작용 하기도 한다.",
                      num3Text: "영달이는 ‘대전에서의 옥자’를, 어린애처럼 생각이 깊지 않은 존재로 인식하고 있다.",
                      num4Text: "백화는 처음에는 영달이의 등에 업히기를 싫어했으나, 영달이의 등에 업힌 이후 싫어하는 내색이 없어 보인다.",
                      answer: 3),
        QuestionModel(num: 5,
                      questionText: "밑줄 친 말의 문맥적 의미가 같은 것은?",
                      reference: "고장 난 시계를 "+"고치다.".underLined,
                      num1Text: "부엌을 입식으로 "+"고치다.".underLined,
                      num2Text: "상호를 순 우리말로 "+"고치다.".underLined,
                      num3Text: "정비소에서 자동차를 "+"고치다.".underLined,
                      num4Text: "국민 생활에 불편을 주는 낡은 법을 "+"고치다.".underLined,
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 말의 사전적 의미로 가장 적절한 것은?",
                      reference: "아이들이야 학교 가는 시간을 빼고는 내내 밖에서만 노는데, 놀아도 여간 시망스럽게 놀지 않았다.\n\n－ 최일남, 〖노새 두 마리〗 중에서 －",
                      num1Text: "몹시 짓궂은 데가 있다.",
                      num2Text: "생기 있고 힘차며 시원스럽다.",
                      num3Text: "어수선하여 질서나 통일성이 없다.",
                      num4Text: "보기에 태도나 행동이 가벼운 데가 있다.",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "밑줄 친 접두사가 한자에서 온 말이 아닌 것은?",
                      num1Text: "강".underLined+"염기",
                      num2Text: "강".underLined+"타자",
                      num3Text: "강".underLined+"기침",
                      num4Text: "강".underLined+"행군",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "밑줄 친 말의 기본형이 옳지 않은 것은?",
                      num1Text: "무를 강판에 "+"가니".underLined+" 즙이 나온다. (기본형 : 갈다)",
                      num2Text: "오래되어 "+"불은".underLined+" 국수는 맛이 없다. (기본형 : 불다)",
                      num3Text: "아이들에게 위험한 데서 놀지 말라고 "+"일렀다.".underLined+" (기본형 : 이르다)",
                      num4Text: "퇴근하는 길에 포장마차에 "+"들렀다".underLined+"가 친구를 만났다. (기본형 : 들르다)",
                      answer: 2),
        QuestionModel(num: 9,
                      questionText: "다음 글에서 드러나지 않는 것은?",
                      reference: "  일주일에 한 번쯤 돼지고기를 반 근, 혹은 반의 반 근 사러 가는 푸줏간이었다. 어머니는 돈을 들려 보내며 매양 같은 주의를 잊지 않았다.\n  적게 주거든, 애라고 조금 주느냐고 말해라, 그리고 또 비계는 말고 살로 주세요, 해라.\n  푸줏간에서는 한쪽 볼에 힘껏 쥐어질린 듯 여문 밤톨만한 혹이 달리고 그 혹부리에, 상기도 보이지 않는 손에 의해 끄들리고 있는 듯 길게 뻗힌 수염을 기른 홀아비 중국인이 고기를 팔았다.\n  애라고 조금 주세요?\n  키가 작아 발돋움질로 간신히 진열대에 턱을 올려놓고 돈을 밀어 넣는 것과 동시에 나는 총알처럼 내뱉었다. 고기를 자르기 위해 벽에 매단 가죽 끈에 칼을 문질러 날을 세우던 중국인은 미처 무슨 말인지 몰라 뚱한 얼굴로 나를 바라보았다. 나는 비계는 말고 살로 달래라 하던 어머니가 일러준 말을 하기 전 중국인이 고기를 자를까 봐 허겁지겁 내쏘았다.\n  고기로 달래요.\n  중국인은 꾸룩꾸룩 웃으며 그때야 비로소 고기를 덥석 베어 내었다.\n  왜 고기만 주니, 털도 주고 가죽도 주지.\n\n － 오정희, 〖중국인 거리〗 중에서 －",
                      num1Text: "어머니의 주의에 대한 ‘나’의 수용",
                      num2Text: "‘나’에게 심부름을 시키는 어머니의 태도",
                      num3Text: "시간적 배경의 특성과 공간적 배경의 역할",
                      num4Text: "‘나’의 말에 대해 푸줏간의 ‘중국인’이 보여 주는 정서",
                      answer: 3),
        QuestionModel(num: 10,
                      questionText: "필자의 견해로 볼 수 없는 것은?",
                      reference: "  우리는 우리가 생각한 것을 말로 나타낸다. 또 다른 사람의 말을 듣고, 그 사람이 무슨 생각을 가지고 있는가를 짐작한다. 그러므로 생각과 말은 서로 떨어질 수 없는 깊은 관계를 가지고 있다.\n  그러면 말과 생각이 얼마만큼 깊은 관계를 가지고 있을까? 이 문제를 놓고 사람들은 오랫동안 여러 가지 생각을 하였다. 그 가운데 가장 두드러진 것이 두 가지 있다. 그 하나는 말과 생각이 서로 꼭 달라붙은 쌍둥이인데 한 놈은 생각이 되어 속에 감추어져 있고 다른 한 놈은 말이 되어 사람 귀에 들리는 것이라는 생각이다. 다른 하나는 생각이 큰 그릇이고 말은 생각 속에 들어가는 작은 그릇이어서 생각에는 말 이외에도 다른 것이 더 있다는 생각이다.\n  이 두 가지 생각 가운데서 앞의 것은 조금만 깊이 생각해 보면 틀렸다는 것을 즉시 깨달을 수 있다. 우리가 생각한 것은 거의 대부분 말로 나타낼 수 있지만, 누구든지 가슴 속에 응어리진 어떤 생각이 분명히 있기는 한데 그것을 어떻게 말로 표현해야 할지 애태운 경험을 가지고 있을 것이다. 이것 한 가지만 보더라도 말과 생각이 서로 안팎을 이루는 쌍둥이가 아님은 쉽게 판명된다.\n  인간의 생각이라는 것은 매우 넓고 큰 것이며 말이란 결국 생각의 일부분을 주워 담는 작은 그릇에 지나지 않는다. 그러나 아무리 인간의 생각이 말보다 범위가 넓고 큰 것이라고 하여도 그것을 가능한 한 말로 바꾸어 놓지 않으면 그 생각의 위대함이나 오묘함이 다른 사람에게 전달되지 않기 때문에 생각이 형님이요, 말이 동생이라고 할지라도 생각은 동생의 신세를 지지 않을 수가 없게 되어 있다. 그러니 말을 통하지 않고는 생각을 전달할 수가 없는 것이다.",
                      num1Text: "말은 생각보다 범위가 좁다.",
                      num2Text: "말은 생각을 나타내는 매개체이다.",
                      num3Text: "말과 생각은 불가분의 관계에 놓여 있다.",
                      num4Text: "말을 통하지 않고도 얼마든지 생각을 전달할 수 있다.",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "다음 시에 대한 감상으로 적절하지 않은 것은?",
                      reference: "아무도 그에게 수심(水深)을 일러준 일이 없기에\n흰나비는 도무지 바다가 무섭지 않다.\n\n청(靑)무우밭인가 해서 내려갔다가는\n어린 날개가 물결에 절어서\n공주처럼 지쳐서 돌아온다.\n\n삼월(三月)달 바다가 꽃이 피지 않아서 서글픈\n나비 허리에 새파란 초생달이 시리다.\n\n － 김기림, 〖바다와 나비〗 －",
                      num1Text: "‘청(靑)무우밭’은 ‘바다’와 대립되는 이미지로 쓰였다.",
                      num2Text: "‘흰나비’는 ‘바다’의 실체에 대해 정확하게 모르고 있었다.",
                      num3Text: "화자는 ‘공주처럼’ 나약한 나비의 의지 부족과 방관적 태도를 비판한다.",
                      num4Text: "‘삼월(三月)달 바다’와 ‘새파란 초생달’은 모두 차가운 이미지로 사용되었다.",
                      answer: 3),
        QuestionModel(num: 12,
                      questionText: "<보기>를 참고할 때, ㉠～㉣에 대한 분석으로 적절하지 않은 것은?",
                      reference: "<보기>\n  어떤 특정한 시기의 풍속이나 세태의 한 단면을 그리는 소설 양식을 세태 소설이라 한다. 세태 소설은 당대 사회의 모순이나 부조리 등을 있는 그대로 묘사하여 그 사회에 대한 비판 의식을 드러낸다. 그 대표적인 소설로 박태원의 ‘소설가 구보 씨의 일일’이 있다.",
                      reference2: "  ㉠"+"개찰구".underLined+" 앞에 두 명의 사내가 서 있었다. 낡은 파나마에 모시 두루마기 노랑 구두를 신고, 그리고 손에 조그만 보따리 하나도 들지 않은 그들을, 구보는, 확신을 가져 무직자라고 단정한다. 그리고 이 시대의 무직자들은, 거의 다 ㉡"+"금광 브로커".underLined+"에 틀림없었다. 구보는 새삼스러이 대합실 안팎을 둘러본다. 그러한 인물들은, 이곳에도 저곳에도 눈에 띄었다.\n  ㉢"+"황금광 시대(黃金狂時代).".underLined+" 저도 모를 사이에 구보의 입술에서는 무거운 한숨이 새어 나왔다. 황금을 찾아, 황금을 찾아, 그것도 역시 숨김없는 인생의, 분명히, 일면이다. 그것은 적어도, 한 손에 단장과 또 한 손에 공책을 들고, 목적 없이 거리로 나온 자기보다는 좀 더 진실한 인생이었을지도 모른다. 시내에 산재한 무수한 광무소(鑛務所). 인지대 백 원. 열람비 오 원. 수수료 십 원. 지도대 십팔 전……. 출원 등록된 광구, 조선 전토(全土)의 칠 할. 시시각각으로 사람들은 졸부가 되고, 또 몰락해 갔다. 황금광 시대. 그들 중에는 평론가와 시인, 이러한 문인들 조차 끼어 있었다. 구보는 일찍이 창작을 위해 그의 벗의 광산에 가 보고 싶다 생각하였다. 사람들의 사행심, 황금의 매력, 그러한 것들을 구보는 보고, 느끼고, 하고 싶었다. 그러나 고도의 금광열은, 오히려, ㉣"+"총독부 청사, 동측 최고층, 광무과 열람실".underLined+"에서 볼 수 있었다…….\n\n－ 박태원, 〖소설가 구보 씨의 일일〗 중에서 －",
                      num1Text: "㉠: 세태의 단면이 드러나는 공간적 배경이다.",
                      num2Text: "㉡: 적극성을 지닌 존재들로 서술자의 예찬 대상이다.",
                      num3Text: "㉢: ‘무거운 한숨’을 유발하는 부조리한 현실로 서술자의 비판 대상이다.",
                      num4Text: "㉣: 서술자가 ‘금광열’이 고조되어 있는 것으로 설정한 대상이나 공간이다.",
                      answer: 2),
        QuestionModel(num: 13,
                      questionText: "㉠～ ㉣에 대한 풀이로 옳지 않은 것?",
                      reference: "  빌기를 다 함에 지성이면 감천이라 황천인들 무심할까. 단상의 오색구름이 사면에 옹위하고 산중에 ㉠"+"백발 신령이 일제히 하강하여 정결케 지은 제물 모두 다 흠향한다.".underLined+" 길조 (吉兆)가 여차(如此)하니 귀자(貴子)가 없을쏘냐. 빌기를 다한 후에 만심 고대하던 차에 일일은 한 꿈을 얻으니, ㉡"+"천상 으로서 오운(五雲)이 영롱하고, 일원(一員) 선관(仙官)이 청룡(靑龍)을 타고 내려와".underLined+" 말하되,\n  “나는 청룡을 다스리던 선관이더니 익성(翼星)이 무도 (無道)한 고로 상제께 아뢰되 익성을 치죄하야 다른 방으로 귀양을 보냈더니 익성이 이걸로 함심(含心)하야 ㉢"+"백옥루 잔치 시에 익성과 대전(對戰)".underLined+"한 후로 상제전에 득죄하여 인간에 내치심에 갈 바를 모르더니 남악산 신령들이 부인 댁으로 지시하기로 왔사오니 부인은 애휼(愛恤)하옵소서.” 하고 타고 온 청룡을 오운 간(五雲間)에 방송(放送)하며 왈, “㉣"+"일후 풍진(風塵) 중에 너를 다시 찾으리라.”".underLined+" 하고 부인 품에 달려들거늘 놀래 깨달으니 일장춘몽이 황홀하다.\n  정신을 진정하야 정언주부를 청입(請入)하야 몽사를 설화 (說話)한대 정언주부가 즐거운 마음 비할 데 없어 부인을 위로하야 춘정(春情)을 부쳐 두고 생남(生男)하기를 만심 고대하더니 과연 그달부터 태기 있어 십 삭이 찬 연후에 옥동자를 탄생할 제, 방 안에 향취 있고 문 밖에 서기(瑞氣)가 뻗질러 생광(生光)은 만지(滿地)하고 서채(瑞彩)는 충천하였다.\n   … (중략) … \n  이때에 조정에 두 신하가 있으니 하나는 도총대장 정한담 이요, 또 하나는 병부상서 최일귀라. 본대 천상 익성으로 자미원 대장성과 백옥루 잔치에 대전한 죄로 상제께 득죄 하여 인간 세상에 적강(謫降)하여 대명국 황제의 신하가 되었는지라 본시 천상지인(天上之人)으로 지략이 유여하고 술법이 신묘한 중에 금산사 옥관도사를 데려다가 별당에 거처하게 하고 술법을 배웠으니 만부부당지용(萬夫不當之勇)이 있고 백만군중대장지재(百萬軍中大將之才)라 벼슬이 일품 이요 포악이 무쌍이라 일상 마음이 천자를 도모코자 하되 다만 정언주부인 유심의 직간을 꺼려하고 또한 퇴재상 (退宰相) 강희주의 상소를 꺼려 주저한 지 오래라.\n\n－ 〖유충렬전〗 중에서 －",
                      num1Text: "㉠: 길조(吉兆)가 일어날 것임을 암시한다.",
                      num2Text: "㉡: ‘부인’이 꾼 꿈의 상황이다.",
                      num3Text: "㉢: ‘선관’이 인간 세상에 귀양을 오게 되는 계기이다.",
                      num4Text: "㉣: ‘남악산 신령’이 후일 청룡을 타고 천상 세계로 복귀할 것임을 암시한다.",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "㉠～㉣의 한자가 모두 바르게 표기된 것은?",
                      reference: "글의 진술 방식에는 ㉠설명, ㉡묘사, ㉢서사, ㉣논증 등 네 가지 방식이 있다.",
                      num1Text: "說明 - 描寫 - 敍事 - 論證",
                      num2Text: "設明 - 描寫 - 敍事 - 論症",
                      num3Text: "說明 - 猫鯊 - 徐事 - 論症",
                      num4Text: "說明 - 猫鯊 - 徐事 - 論證",
                      answer: 1),
        QuestionModel(num: 15,
                      questionText: "밑줄 친 부분이 어문 규정에 맞는 것은?",
                      num1Text: "병이 씻은 듯이 "+"낳았다.".underLined,
                      num2Text: "넉넉치".underLined+" 못한 선물이나 받아 주세요.",
                      num3Text: "그는 자물쇠로 책상 서랍을 "+"잠갔다.".underLined,
                      num4Text: "옷가지를 "+"이여서".underLined+" 밧줄처럼 만들었다.",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "훈민정음의 28 자모(字母) 체계에 들지 않는 것은",
                      num1Text: "ㆆ",
                      num2Text: "ㅿ",
                      num3Text: "ㅠ",
                      num4Text: "ㅸ",
                      answer: 4),
        QuestionModel(num: 17,
                      questionText: "밑줄 친 부분의 띄어쓰기가 옳은 것",
                      num1Text: "한밤중".underLined+"에 전화가 왔다.",
                      num2Text: "그는 일도 "+"잘할 뿐더러".underLined+" 성격도 좋다.",
                      num3Text: "친구가 도착한 지 두 "+"시간만에".underLined+" 떠났다.",
                      num4Text: "요즘 경기가 안 좋아서 장사가 잘 "+"안 된다.".underLined,
                      answer: 1),
        QuestionModel(num: 18,
                      questionText: "독음이 모두 바른 것은?",
                      num1Text: "探險(탐험) － 矛盾(모순) － 貨幣(화폐)",
                      num2Text: "詐欺(사기) － 惹起(야기) － 灼熱(치열)",
                      num3Text: "荊棘(형자) － 破綻(파탄) － 洞察(통찰)",
                      num4Text: "箴言(잠언) － 惡寒(악한) － 奢侈(사치)",
                      answer: 1),
        QuestionModel(num: 19,
                      questionText: "설명이 옳지 않은 것은?",
                      num1Text: "‘ㄴ, ㅁ, ㅇ’은 유음이다.",
                      num2Text: "‘ㅅ, ㅆ, ㅎ’은 마찰음이다.",
                      num3Text: "‘ㅡ, ㅓ, ㅏ’는 후설 모음이다.",
                      num4Text: "‘ㅟ, ㅚ, ㅗ, ㅜ’는 원순 모음이다.",
                      answer: 1),
        QuestionModel(num: 20,
                      questionText: "내용의 전개에 따라 바르게 배열한 것은?",
                      reference: "(가) 사물은 저것 아닌 것이 없고, 또 이것 아닌 것이 없다. 이쪽에서 보면 모두가 저것, 저쪽에서 보면 모두가 이것이다.\n\n(나) 그러므로 저것은 이것에서 생겨나고, 이것 또한 저것 에서 비롯된다고 한다. 이것과 저것은 저 혜시(惠施)가 말하는 방생(方生)의 설이다.\n\n(다) 그래서 성인(聖人)은 이런 상대적인 방법에 의하지 않고, 그것을 절대적인 자연의 조명(照明)에 비추어 본다. 그리고 커다란 긍정에 의존한다. 거기서는 이것이 저것이고 저것 또한 이것이다. 또 저것도 하나의 시비 (是非)이고 이것도 하나의 시비이다. 과연 저것과 이것이 있다는 말인가. 과연 저것과 이것이 없다는 말인가.\n\n(라) 그러나 그, 즉 혜시(惠施)도 말하듯이 삶이 있으면 반드시 죽음이 있고, 죽음이 있으면 반드시 삶이 있다. 역시 된다가 있으면 안 된다가 있고, 안 된다가 있으면 된다가 있다. 옳다에 의거하면 옳지 않다에 기대는 셈이 되고, 옳지 않다에 의거하면 옳다에 의지하는 셈이 된다.",
                      num1Text: "(가) － (나) － (다) － (라)",
                      num2Text: "(가) － (나) － (라) － (다)",
                      num3Text: "(가) － (다) － (나) － (라)",
                      num4Text: "(가) － (라) － (나) － (다)",
                      answer: 2),
        ]
        let exam = ExamModel(id: 201711, year: 2017, examTypeID: "국가직", subjectID: "국어", questions: questions)
        exam2017.append(exam)
    }
    func saveExam201712() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분과 의미가 가장 가까운 것을 고르시오. [1~2]",
                      reference: "I absolutely "+"detested".underLined+" the idea of staying up late at night.",
                      num1Text: "defended",
                      num2Text: "abhorred",
                      num3Text: "confirmed",
                      num4Text: "abandoned",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "",
                      reference: "I had an "+"uncanny".underLined+" feeling that I had seen this scene somewhere before.",
                      num1Text: "odd",
                      num2Text: "ongoing",
                      num3Text: "obvious",
                      num4Text: "offensive",
                      answer: 1),
        QuestionModel(num: 3,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오. [3～4]",
                      reference: "  A : May I help you?\n  B : I bought this dress two days ago, but it's a bit big for me.\n  A : ____________________________________ \n  B : Then I'd like to get a refund.\n  A : May I see your receipt, please?\n  B : Here you are.",
                      num1Text: "I'm sorry, but there's no smaller size.",
                      num2Text: "I feel like it fits you perfectly, though.",
                      num3Text: "That dress sells really well in our store.",
                      num4Text: "I'm sorry, but this purchase can't be refunded.",
                      answer: 1),
        QuestionModel(num: 4,
                      questionText: "",
                      reference: "  A: Every time I use this home blood pressure monitor, I get a different reading. I think I'm doing it wrong. Can you show me how to use it correctly?\n  B: Yes, of course. First, you have to put the strap around your arm.\n  A: Like this? Am I doing this correctly?\n  B:That looks a little too tight.\n  A:Oh, how about now?\n  B: Now it looks a bit too loose. If it's too tight or too loose, you'll get an incorrect reading.\n  A : __________________________________\n  B: Press the button now. You shouldn't move or speak.\n  A: I get it.\n  B: You should see your blood pressure on the screen in a few moments.",
                      num1Text: "I didn't see anything today.",
                      num2Text: "Oh, okay. What do I do next?",
                      num3Text: "Right, I need to read the book.",
                      num4Text: "Should I check out their website?",
                      answer: 2),
        QuestionModel(num: 5,
                      questionText: "어법상 옳은 것은?",
                      num1Text: "They didn't believe his story, and neither did I.",
                      num2Text: "The sport in that I am most interested is soccer.",
                      num3Text: "Jamie learned from the book that World War I had broken out in 1914.",
                      num4Text: "Two factors have made scientists difficult to determine the number of species on Earth.",
                      answer: 1),
        QuestionModel(num: 6,
                      questionText: "어법상 옳지 않은 것은?",
                      num1Text: "A few words caught in passing set me thinking.",
                      num2Text: "Hardly did she enter the house when someone turned on the light.",
                      num3Text: "We drove on to the hotel, from whose balcony we could look down at the town.",
                      num4Text: "The homeless usually have great difficulty getting a job, so they are losing their hope.",
                      answer: 2),
        QuestionModel(num: 7,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오. [7~9]",
                      reference: "Why might people hovering near the poverty line be more likely to help their fellow humans? Part of it, Keltner thinks, is that poor people must often band together to make it through tough times―a process that probably makes them more socially astute. He says, “When you face uncertainty, it makes you orient to other people. You build up these strong social networks.” When a poor young mother has a new baby, for instance, she may need help securing food, supplies, and childcare, and if she has healthy social times, members of her community will pitch in. But limited income is hardly a prerequisite for developing this kind of empathy and social responsiveness. Regardless of the size of our bank accounts, suffering becomes a conduit to altruism or heroism when our own pain compels us to be ____________________ other people's needs and to intervene when we see someone in the clutches of the kind of suffering we know so well.",
                      num1Text: "less involved in",
                      num2Text: "less preoccupied with",
                      num3Text: "more attentive to",
                      num4Text: "more indifferent to",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "",
                      reference: "The Soleil department store outlet in Shanghai would seem to have all the amenities necessary to succeed in modern Chinese retail: luxury brands and an exclusive location. Despite these advantages, however, the store's management thought it was still missing something to attract customers. So next week they're unveiling a gigantic, twisting, dragon-shaped slide that shoppers can use to drop from fifth-floor luxury boutiques to first-floor luxury boutiques in death-defying seconds. Social media users are wondering, half-jokingly, whether the slide will kill anyone. But Soleil has a different concern that Chinese shopping malls will go away completely. Chinese shoppers, once seemingly in endless supply, are no longer turning up at brick-and-mortar outlets because of the growing online shopping, and they still go abroad to buy luxury goods. So, repurposing these massive spaces for consumers who have other ways to spend their time and money is likely to require a lot of creativity. _________________________________.",
                      num1Text: "Luxury brands are thriving at Soleil",
                      num2Text: "Soleil has decided against making bold moves",
                      num3Text: "Increasing the online customer base may be the last hope",
                      num4Text: "A five-story dragon slide may not be a bad place to start",
                      answer: 4),
        QuestionModel(num: 9,
                      questionText: "",
                      reference: "It is easy to devise numerous possible scenarios of future developments, each one, on the face of it, equally likely. The difficult task is to know which will actually take place. In hindsight, it usually seems obvious. When we look back in time, each event seems clearly and logically to follow from previous events. Before the event occurs, however, the number of possibilities seems endless. There are no methods for successful prediction, especially in areas involving complex social and technological changes, where many of the determining factors are not known and, in any event, are certainly not under any single group's control. Nonetheless, it is essential to _________________________________________. We do know that new technologies will bring both dividends and problems, especially human, social problems. The more we try to anticipate these problems, the better we can control them.",
                      num1Text: "work out reasonable scenarios for the future",
                      num2Text: "legitimize possible dividends from future changes",
                      num3Text: "leave out various aspects of technological problems",
                      num4Text: "consider what it would be like to focus on the present",
                      answer: 1),
        QuestionModel(num: 10,
                      questionText: "다음 글의 내용과 일치하는 것은?",
                      reference: "Taste buds got their name from the nineteenth-century German scientists Georg Meissner and Rudolf Wagner, who discovered mounds made up of taste cells that overlap like petals. Taste buds wear out every week to ten days, and we replace them, although not as frequently over the age of forty-five: our palates really do become jaded as we get older. It takes a more intense taste to produce the same level of sensation, and children have the keenest sense of taste. A baby's mouth has many more taste buds than an adult's, with some even dotting the cheeks. Children adore sweets partly because the tips of their tongues, more sensitive to sugar, haven't yet been blunted by trying to eat hot soup before it cools.",
                      num1Text: "Taste buds were invented in the nineteenth century.",
                      num2Text: "Replacement of taste buds does not slow down with age.",
                      num3Text: "Children have more sensitive palates than adults.",
                      num4Text: "The sense of taste declines by eating cold soup.",
                      answer: 3),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 부분과 의미가 가장 가까운 것은?",
                      reference: "  At this company, we will not "+"put up with".underLined+" such behavior.",
                      num1Text: "modify",
                      num2Text: "record",
                      num3Text: "tolerate",
                      num4Text: "evaluate",
                      answer: 3),
        QuestionModel(num: 12,
                      questionText: "밑줄 친 부분 중 의미상 옳지 않은 것은?",
                      num1Text: "I'm going to "+"take over".underLined+" his former position.",
                      num2Text: "I can't "+"take on".underLined+" any more work at the moment.",
                      num3Text: "The plane couldn't "+"take off".underLined+" because of the heavy fog.",
                      num4Text: "I can't go out because I have to "+"take after".underLined+" my baby sister.",
                      answer: 4),
        QuestionModel(num: 13,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "Drama is doing. Drama is being. Drama is such a normal thing. It is something that we all engage in every day when faced with difficult situations. You get up in the morning with a bad headache or an attack of depression, yet you face the day and cope with other people, pretending that nothing is wrong. You have an important meeting or an interview coming up, so you talk through the issues with yourself beforehand and decide how to present a confident, cheerful face, what to wear, what to do with your hands, and so on. You've spilt coffee over a colleague's papers, and immediately you prepare an elaborate excuse. Your partner has just run off with your best friend, yet you cannot avoid going in to teach a class of inquisitive students. Getting on with our day-to-day lives requires a series of civilized masks if we are to maintain our dignity and live in harmony with others.",
                      num1Text: "Dysfunctions of Drama",
                      num2Text: "Drama in Our Daily Lives",
                      num3Text: "Drama as a Theatrical Art",
                      num4Text: "Dramatic Changes in Emotions",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "다음 글의 요지로 가장 적절한 것은?",
                      reference: "How on earth will it help the poor if governments try to strangle globalization by stemming the flow of trade, information, and capital―the three components of the global economy? That disparities between rich and poor are still too great is undeniable. But it is just not true that economic growth benefits only the rich and leaves out the poor, as the opponents of globalization and the market economy would have us believe. A recent World Bank study entitled “Growth Is Good for the Poor” reveals a one-for-one relationship between income of the bottom fifth of the population and per capita GDP. In other words, incomes of all sectors grow proportionately at the same rate. The study notes that openness to foreign trade benefits the poor to the same extent that it benefits the whole economy.",
                      num1Text: "Globalization deepens conflicts between rich and poor.",
                      num2Text: "The global economy grows at the expense of the poor.",
                      num3Text: "Globalization can be beneficial regardless of one's economic status.",
                      num4Text: "Governments must control the flow of trade to revive the economy.",
                      answer: 3),
        QuestionModel(num: 15,
                      questionText: "우리말을 영어로 잘못 옮긴 것을 고르시오. [15~16]",
                      num1Text: "이 편지를 받는 대로 곧 본사로 와 주십시오.\n→ Please come to the headquarters as soon as you receive this letter.",
                      num2Text: "나는 소년 시절에 독서하는 버릇을 길러 놓았어야만 했다.\n→ I ought to have formed a habit of reading in my boyhood.",
                      num3Text: "그는 10년 동안 외국에 있었기 때문에 영어를 매우 유창하게 말할 수 있다.\n→ Having been abroad for ten years, he can speak English very fluently.",
                      num4Text: "내가 그때 그 계획을 포기했었다면 이렇게 훌륭한 성과를 얻지 못했을 것이다.\n→ Had I given up the project at that time, I should have achieved such a splendid result.",
                      answer: 4),
        QuestionModel(num: 16,
                      questionText: "",
                      num1Text: "그 회의 후에야 그는 금융 위기의 심각성을 알아차렸다.\n→ Only after the meeting did he recognize the seriousness of the financial crisis.",
                      num2Text: "장관은 교통문제를 해결하기 위해 강 위에 다리를 건설해야 한다고 주장했다.\n→ The minister insisted that a bridge be constructed over the river to solve the traffic problem.",
                      num3Text: "비록 그 일이 어려운 것이었지만, Linda는 그것을 끝내기 위해 최선을 다했다.\n→ As difficult a task as it was, Linda did her best to complete it.",
                      num4Text: "그는 문자 메시지에 너무 정신이 팔려서 제한속도보다 빠르게 달리고 있다는 것을 몰랐다.\n→ He was so distracted by a text message to know that he was going over the speed limit.",
                      answer: 4),
        QuestionModel(num: 17,
                      questionText: "빈칸 (A), (B)에 들어갈 말로 가장 적절한 것은?",
                      reference: "The amount of information gathered by the eyes as contrasted with the ears has not been precisely calculated. Such a calculation not only involves a translation process, but scientists have been handicapped by lack of knowledge of what to count. A general notion, however, of the relative complexities of the two systems can be obtained by  (A)  the size of the nerves connecting the eyes and the ears to the centers of the brain. Since the optic nerve contains roughly eighteen times as many neurons as the cochlear nerve, we assume it transmits at least that much more information. Actually, in normally alert subjects, it is probable that the eyes may be as much as a thousand times as effective as the ears in  (B)  information.\n\n* cochlear : 달팽이관의",
                      num1Text: "adding - clearing up",
                      num2Text: "adding - disseminating",
                      num3Text: "comparing - reducing",
                      num4Text: "comparing - sweeping up",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "글의 흐름상 가장 어색한 문장은?",
                      reference: "Children's book awards have proliferated in recent years; today, there are well over 100 different awards and prizes by a variety of organizations. ①"+"The awards may be given for books of a specific genre or simply for the best of all children's books published within a given time period.".underLined+" An award may honor a particular book or an author for a lifetime contribution to the world of children's literature. ②"+"Most children's book awards are chosen by adults, but now a growing number of children's choice book awards exist.".underLined+" The larger national awards given in most countries are the most influential and have helped considerably to raise public awareness about the fine books being published for young readers. ③"+"An award ceremony for outstanding services to the publishing industry is put on hold.".underLined+" ④"+"Of course, readers are wise not to put too much faith in award-winning books.".underLined+" An award doesn't necessarily mean a good reading experience, but it does provide a starting place when choosing books.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "주어진 문장이 들어갈 위치로 가장 적절한 곳은?",
                      reference: "This inequality is corrected by their getting in their turn better portions from kills by other people.",
                      reference2: "Let us examine a situation of simple distribution such as occurs when an animal is killed in a hunt. One might expect to find the animal portioned out according to the amount of work done by each hunter to obtain it. ( ① ) To some extent this principle is followed, but other people have their rights as well. ( ② ) Each person in the camp gets a share depending upon his or her relation to the hunters. ( ③ ) When a kangaroo is killed, for example, the hunters have to give its main parts to their kinfolk and the worst parts may even be kept by the hunters themselves. ( ④ ) The net result in the long run is substantially the same to each person, but through this system the principles of kinship obligation and the morality of sharing food have been emphasized.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 20,
                      questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "The most innovative of the group therapy approaches was psychodrama, the brainchild of Jacob L. Moreno. Psychodrama as a form of group therapy started with premises that were quite alien to the Freudian worldview that mental illness essentially occurs within the psyche or mind.",
                      reference2: "(A) But he also believed that creativity is rarely a solitary process but something brought out by social interactions. He relied heavily on theatrical techniques, including role-playing and improvisation, as a means to promote creativity and general social trust.\n\n(B) Despite his theoretical difference from the mainstream viewpoint, Moreno's influence in shaping psychological consciousness in the twentieth century was considerable. He believed that the nature of human beings is to be creative and that living a creative life is the key to human health and well-being.\n\n(C) His most important theatrical tool was what he called role reversal―asking participants to take on another's persona. The act of pretending “as if” one were in another's skin was designed to help bring out the empathic impulse and to develop it to higher levels of expression.",
                      num1Text: "(A)-(C)-(B)",
                      num2Text: "(B)-(A)-(C)",
                      num3Text: "(B)-(C)-(A)",
                      num4Text: "(C)-(B)-(A)",
                      answer: 2),
        ]
        let exam = ExamModel(id: 201712, year: 2017, examTypeID: "국가직", subjectID: "영어", questions: questions)
        exam2017.append(exam)
    }
    func saveExam201713() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "㉠과 ㉡ 두 인물의 공통된 신분상의 특징으로 옳은 것은?",
                      reference: "○  ㉠ 은(는) 신문왕에게 화왕계를 통하여 조언 하였다.\n○  ㉡ 은(는) 진성여왕에게 시무책 10여 조를 올렸다.",
                      num1Text: "왕이 될 수 있는 신분이었다.",
                      num2Text: "자색(紫色)의 공복을 착용하였다.",
                      num3Text: "중앙 관부의 최고 책임자를 독점하였다.",
                      num4Text: "관등 승진에서 중위제(重位制)를 적용받았다.",
                      answer: 4),
        QuestionModel(num: 2,
                      questionText: "(가) ～ (다)는 고구려의 발전 과정을 시기 순으로 나열한 것이다. (나)에 들어갈 내용으로 옳은 것만을 <보기>에서 모두 고른 것은?",
                      reference: "(가) 낙랑군을 차지하여 한반도로 진출하는 발판을 마련 하였다.\n(나) [              ]\n(다) 평양으로 도읍을 옮기고, 백제의 수도인 한성을 함락하였다.",
                      reference2: "ᄀ. 태학을 설립하였다.\nᄂ. 진대법을 도입하였다.\nᄃ. 천리장성을 축조하였다.\nᄅ. 신라를 도와 왜를 격퇴하였다.",
                      num1Text: "ᄀ, ᄂ",
                      num2Text: "ᄀ, ᄅ",
                      num3Text: "ᄂ, ᄃ",
                      num4Text: "ᄃ, ᄅ",
                      answer: 2),
        QuestionModel(num: 3,
                      questionText: "다음 제도를 시행한 목적에 해당하는 것만을 <보기>에서 모두 고른 것은?",
                      reference: "○ 무릇 민호(民戶)는 그 이웃과 더불어 모으되, 가족 숫자의 다과(多寡)와 재산의 빈부에 관계없이 다섯 집마다 한 통(統)을 만들고, 통 안에 한 사람을 골라서 통수(統帥)로 삼아 통 안의 일을 맡게 한다.\n\n○ 1리(里) 마다 5통 이상에서 10통까지는 소리(小里)를 삼고, … (중략) … 리(里) 안에서 또 이정(里正)을 임명한다.\n\n- 〖비변사등록〗 -",
                      reference2: "ᄀ. 농민들의 도망과 이탈 방지\nᄂ. 부세와 군역의 안정적인 확보\nᄃ. 재지사족 중심의 향촌 자치 활성화\nᄅ. 향권을 둘러싼 구향과 신향 간의 향전 억제",
                      num1Text: "ᄀ, ᄂ",
                      num2Text: "ᄀ, ᄅ",
                      num3Text: "ᄂ, ᄃ",
                      num4Text: "ᄃ, ᄅ",
                      answer: 1),
        QuestionModel(num: 4,
                      questionText: "다음 발의로 개최된 ㉠에 대한 설명으로 옳은 것은?",
                      reference: "베이징 방면의 인사는 분열을 통탄하며 통일을 촉진하는 단체를 출현시키고 상하이 일대의 인사는 이를 고려하여 개혁을 제창하고 있다. ...(중략)... 근본적 대해결로써 통일적 재조를 꾀하여 독립운동의 신국면을 타개하려고 함에는 다만 민의뿐이므로 이에  ㉠  의 소집을 제창한다.",
                      num1Text: "창조파와 개조파 등의 주장이 대립되었다.",
                      num2Text: "한국국민당을 통한 정당정치 실시가 결정되었다.",
                      num3Text: "삼균주의를 바탕으로 한 건국강령이 채택되었다.",
                      num4Text: "파리강화회의에 김규식을 파견하는 것이 논의되었다.",
                      answer: 1),
        QuestionModel(num: 5,
                      questionText: "(가)∼(라) 시기에 있었던 사실로 옳은 것은?",
                      imgModel: ImageModel(imageString: "201713-5", imgWidth: 330, imgHeight: 80),
                      num1Text: "(가) - 현량과를 실시하였다.",
                      num2Text: "(나) - 무오사화와 갑자사화가 일어났다.",
                      num3Text: "(다) - 두 차례에 걸친 예송이 일어났다.",
                      num4Text: "(라) - 신해통공으로 금난전권을 폐지하였다.",
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "다음 자료에 나타난 나라에 대한 설명으로 옳은 것은?",
                      reference: "해마다 10월이면 하늘에 제사를 지내는데, 밤낮으로 술을 마시고 노래부르며 춤을 추니 이를 무천이라 한다. 또 호랑이를 신(神)으로 여겨 제사지낸다. 읍락을 함부로 침범하면 노비와 소, 말로 변상하는데, 이를 책화라 한다.",
                      num1Text: "후․읍군․삼로 등이 하호를 통치하였다.",
                      num2Text: "국읍마다 천신에 대한 제사를 주관하는 천군이 있었다.",
                      num3Text: "사람이 죽으면 가매장한 다음 뼈만 추려 목곽에 안치하였다.",
                      num4Text: "아이가 출생하면 돌로 머리를 눌러 납작하게 하는 풍습이 있었다.",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "다음 건의문이 결의된 이후에 일어난 사실로 옳은 것은?",
                      reference: "  1. 외국인에게 의지하지 말고, 관.민이 힘을 합하여 전제 황권을 견고하게 할 것\n  2. 외국과의 이권에 관한 조약은 각 대신과 중추원 의장이 합동 날인하여 시행할 것\n  3. 국가 재정은 탁지부에서 전관하고, 예산과 결산을 국민에게 공포할 것\n  4. 중대 범죄를 공판하되, 피고의 인권을 존중할 것\n  5. 칙임관을 임명할 때에는 정부의 자문을 받아 다수의 의견에 따를 것\n  6. 정해진 규정을 실천할 것",
                      num1Text: "군국기무처를 중심으로 개혁이 추진되었다.",
                      num2Text: "황제권 강화 작업의 일환으로 원수부가 설치되었다.",
                      num3Text: "고종이 러시아 공사관으로 거처를 옮기게 되었다.",
                      num4Text: "서재필을 중심으로 민중 계몽을 위한 독립신문이 창간되었다.",
                      answer: 2),
        QuestionModel(num: 8,
                      questionText: "밑줄 친 ‘이 기구’가 설치된 왕 대에 있었던 사실로 옳은 것은?",
                      reference: "조정은 중국의 화약 제조 기술을 터득하여 "+"이 기구".underLined+"를 두고, 대장군포를 비롯한 20여 종의 화기를 생산하였으며, 화약과 화포를 제작하였다.",
                      num1Text: "복원궁을 건립하여 도교를 부흥시켰다.",
                      num2Text: "흥덕사에서 직지심체요절을 간행하였다",
                      num3Text: "교장도감을 설치하여 속장경을 간행하였다.",
                      num4Text: "시무 28조를 수용하여 유교정치를 구현하였다.",
                      answer: 2),
        QuestionModel(num: 9,
                      questionText: "갑신정변 이후 국내외 정세로 옳지 않은 것은?",
                      num1Text: "독일 부영사 부들러는 조선의 영세 중립국화를 건의하였다.",
                      num2Text: "러시아의 남하정책에 대응하여 영국 함대가 거문도를 불법 점령하였다.",
                      num3Text: "조․청 상민수륙무역장정을 체결하여 청나라 상인에게 통상 특혜를 허용하였다.",
                      num4Text: "청․일 양국 군대가 조선에서 철수하는 것 등을 내용으로 하는 톈진조약이 체결되었다.",
                      answer: 3),
        QuestionModel(num: 10,
                      questionText: "독도가 우리나라 영토임을 입증하는 근거로만 옳게 짝지어진 것은?",
                      num1Text: "이범윤의 보고문 － 은주시청합기",
                      num2Text: "대한제국 칙령 제41호 － 삼국접양지도",
                      num3Text: "미쓰야 협정 － 시마네 현 고시 제40호",
                      num4Text: "조선국교제시말내탐서 － 어윤중의 서북경략사 임명장",
                      answer: 2),
        QuestionModel(num: 11,
                      questionText: "다음에서 설명하는 화폐가 사용된 시기의 경제 상황으로 옳은 것은?",
                      reference: "초기에는 은 1근으로 우리나라 지형을 본떠 만들었는데 그 가치는 포목 100필에 해당하는 고액이었다. 주로 외국과의 교역에 사용되었으며 후에 은의 조달이 힘들어지고 동을 혼합한 위조가 성행하자, 크기를 축소한 소은병을 만들었다.",
                      num1Text: "이앙법이 전국적으로 보급되었다.",
                      num2Text: "책, 차 등을 파는 관영상점을 두었다.",
                      num3Text: "동시전이 설치되어 시장을 감독하였다.",
                      num4Text: "청해진이 설치되어 무역권을 장악하였다.",
                      answer: 2),
        QuestionModel(num: 12,
                      questionText: "밑줄 친 ‘그’에 대한 설명으로 옳은 것은?",
                      reference: "그".underLined+"는 이성계를 추대하여 조선 왕조를 개창한 공으로 개국 1등 공신이 되었으며, 의정부를 중심으로 하는 재상 중심의 관료정치를 주창하였다. 그리고 〖불씨잡변〗을 저술하여 불교의 사회적 폐단을 비판하였다.",
                      num1Text: "왜구의 소굴인 쓰시마 섬을 정벌하였다.",
                      num2Text: "백성들의 윤리서인 〖삼강행실도〗를 편찬하였다.",
                      num3Text: "여진족을 두만강 밖으로 몰아내고 6진을 개척하였다.",
                      num4Text: "〖조선경국전〗을 편찬하여 왕조의 통치 규범을 마련하였다.",
                      answer: 4),
        QuestionModel(num: 13,
                      questionText: "밑줄 친 ‘이곳’에서 전개된 민족운동으로 옳은 것은?",
                      reference: "1903년에 우리나라 공식 이민단이 "+"이곳".underLined+"에 도착하였다. 이주 노동자들은 사탕수수 농장, 개간 사업장, 철도 공사장 등에서 일하며 한인 사회를 형성하여 갔다. 노동 이민과 함께 사진 결혼에 의한 부녀자들의 이민도 이루어졌다. 또한 한인합성협회 등과 같은 한인 단체가 결성되었다.",
                      num1Text: "독립운동 기지인 한흥동이 건설되었다.",
                      num2Text: "독립운동 단체인 권업회가 조직되었다.",
                      num3Text: "자치 기관인 경학사와 부민단이 만들어졌다.",
                      num4Text: "군사 양성 기관인 대조선 국민군단이 창설되었다.",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "다음과 같이 주장한 조선후기의 실학자에 대한 설명으로 옳은 것은?",
                      reference: "천체가 운행하는 것이나 지구가 자전하는 것은 그 세가 동일하니, 분리해서 설명할 필요가 없다. 생각건대 9만 리의 둘레를 한 바퀴 도는 데 이처럼 빠르며, 저 별들과 지구와의 거리는 겨우 반경(半徑)밖에 되지 않는데도 오히려 몇 천만 억의 별들이 있는지 알 수가 없다. 하물며 은하계 밖에도 또 다른 별들이 있지 않겠는가!",
                      num1Text: "〖북학의〗에서 소비를 권장하여 생산을 촉진하자고 주장하였다.",
                      num2Text: "〖임하경륜〗에서 성인 남자에게 2결의 토지를 나누어 주자고 주장하였다.",
                      num3Text: "〖반계수록〗에서 신분에 따라 토지를 차등 있게 재분배하자고 주장하였다.",
                      num4Text: "〖우서〗에서 상업적 경영을 통해 농업 생산성을 높여야 한다고 주장하였다.",
                      answer: 2),
        QuestionModel(num: 15,
                      questionText: "다음 조칙이 발표된 이후의 상황에 대한 설명으로 옳은 것만을 <보기>에서 모두 고른 것은?",
                      reference: "   ≪관보≫ 호외\n짐이 생각건대 쓸데없는 비용을 절약하여 이용후생에 응용함이 급무라. 현재 군대는 용병으로서 상하의 일치와 국가 안전을 지키는 방위에 부족한지라. 훗날 징병법을 발표하여 공고한 병력을 구비할 때까지 황실시위에 필요한 자를 빼고 모두 일시에 해산하노라.",
                      reference2: "ᄀ. 신돌석과 같은 평민 출신의 의병장이 처음으로 등장하였다.\nᄂ. 단발령의 실시로 위정척사 사상에 바탕을 둔 의병 운동이 시작되었다.\nᄃ. 연합 의병 부대인 13도 창의군이 결성되어 서울 진공 작전을 계획하였다.\nᄅ. 일본군의 ‘남한 대토벌 작전’으로 의병 부대의 근거지가 초토화되었다.",
                      num1Text: "ᄀ, ᄂ",
                      num2Text: "ᄀ, ᄅ",
                      num3Text: "ᄂ, ᄃ",
                      num4Text: "ᄃ, ᄅ",
                      answer: 4),
        QuestionModel(num: 16,
                      questionText: "국권이 침탈되기까지의 과정을 시기 순으로 바르게 나열한 것은?",
                      reference: "ㄱ. 헤이그 특사 파견을 문제 삼아 고종 황제를 강제로 퇴위시켰다.\nㄴ. 일본인 메가타를 재정 고문으로, 미국인 스티븐스를 외교 고문으로 임명하도록 하였다.\nㄷ. 대한제국의 사법권을 빼앗고 감옥 사무를 장악하였다.\nㄹ. 통감이 추천한 일본인을 대한제국의 관리로 임명하도록 하였다.",
                      num1Text: "ᄀ→ᄂ→ᄃ→ᄅ",
                      num2Text: "ᄂ→ᄀ→ᄅ→ᄃ",
                      num3Text: "ᄂ→ᄃ→ᄀ→ᄅ",
                      num4Text: "ᄅ→ᄂ→ᄀ→ᄃ",
                      answer: 2),
        QuestionModel(num: 17,
                      questionText: "다음의 자료에 보이는 시기의 경제 상황에 대한 설명으로 옳지 않은 것은?",
                      reference: "황해도 관찰사의 보고에 따르면, 수안군에는 본래 금광이 다섯 곳이 있었다. 올해 여름에 새로 39개소의 금혈을 뚫었는데, 550여 명의 광꾼들이 모여들었다. 도내의 무뢰배들이 농사를 짓지 않고 다투어 모여들 뿐만 아니라 다른 지방에서 이익을 좇는 무리들도 소문을 듣고 몰려온다. ...(중략)... 금점을 설치한 지 이미 여러 해가 된 곳에는 촌락이 즐비하고 상인들이 물품을 유통시켜 큰 도회지를 이루고 있다.",
                      num1Text: "밭농사에서는 견종법이 보급되었다.",
                      num2Text: "면화, 담배 등 상품 작물을 재배하였다.",
                      num3Text: "일부 지방에서 도조법으로 지대를 납부하였다.",
                      num4Text: "개간을 장려하기 위해 사패전을 부농층에 분급하였다.",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "다음에 나타난 사상에 대한 설명으로 옳지 않은 것은?",
                      reference: "신(臣)들이 서경의 임원역 지세를 관찰하니, 이곳이 곧 음양가들이 말하는 매우 좋은 터입니다. 만약 궁궐을 지어서 거처하면 천하를 병합할 수 있고, 금나라가 폐백을 가지고 와 스스로 항복할 것이며, 36국이 모두 신하가 될 것입니다.",
                      num1Text: "서경 천도 운동의 배경이 되었다.",
                      num2Text: "문종 때 남경 설치의 배경이 되었다.",
                      num3Text: "하늘에 제사 지내는 초제의 사상적 근거가 되었다.",
                      num4Text: "공민왕과 우왕 때 한양 천도 주장의 근거가 되었다.",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "다음 주장을 한 인물에 대한 설명으로 옳은 것은?",
                      reference: "계급투쟁은 민족의 내부 분열을 초래할 것이며, 민족의 내쟁은 필연적으로 민족의 약화에 따르는 다른 민족으로 부터의 수모를 초래할 것이다. 계급투쟁의 길은 우리가 반드시 취해야 할 필요는 없고, 민족 균등이 실현되는 날 그것은 자연 해소되는 문제다. … (중략) … 이 세계적 기운과 민족적 요청에서 민족사관은 출발하는 것이며, 민족사는 그 향로와 방법을 명백하게 과학적으로 지시하여야 할 것이다.\n\n-〖조선민족사 개론〗-",
                      num1Text: "〖조선상고사〗와 〖조선사연구초〗를 저술하였다.",
                      num2Text: "대동사상을 수용한 유교 구신론을 주장하였다.",
                      num3Text: "〖진단학보〗를 발간한 진단학회의 발기인으로 활동하였다.",
                      num4Text: "〖5천년간 조선의 얼〗이라는 글을 동아일보에 연재하였다.",
                      answer: 3),
        QuestionModel(num: 20,
                      questionText: "고려시대 의주에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "청천강변에 위치하며 도호부가 설치된 곳이다.",
                      num2Text: "강동 6주 가운데 하나인 흥화진이 있던 곳이다.",
                      num3Text: "요(遼)와 물품을 거래하던 각장이 설치된 곳이다.",
                      num4Text: "요(遼)와 금(金)의 분쟁을 이용하여 회복하려고 시도한 곳이다.",
                      answer: 1),
        ]
        let exam = ExamModel(id: 201713, year: 2017, examTypeID: "국가직", subjectID: "한국사", questions: questions)
        exam2017.append(exam)
    }
    
    //지방직
    func saveExam201721() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 말이 어법에 맞는 것은?",
                      num1Text: "바닷물이 "+"퍼레서".underLined+" 무서운 느낌이 든다.",
                      num2Text: "또아리".underLined+" 튼 뱀은 쳐다보지 마라.",
                      num3Text: "머릿말".underLined+"에 쓸 내용을 생각해 둬라.",
                      num4Text: "문을 잘 "+"잠궈야".underLined+" 한다.",
                      answer: 1),
        QuestionModel(num: 2,
                      questionText: "밑줄 친 말의 의미는?",
                      reference: "몇 달 만에야 "+"말길이 되어".underLined+" 겨우 상대편을 만나 보았다.",
                      num1Text: "남의 말이 끝나자마자 이어 말하다.",
                      num2Text: "자신을 소개하는 길이 트이다.",
                      num3Text: "어떤 말이 상정되거나 토론이 되다.",
                      num4Text: "마음에 당겨 재미를 붙이다.",
                      answer: 2),
        QuestionModel(num: 3,
                      questionText: "괄호에 들어갈 숫자의 합은?",
                      reference: "쌈 : 바늘 (    ) 개를 묶어 세는 단위\n제(劑) : 한약의 분량을 나타내는 단위. 한 제는 탕약(湯藥) (    ) 첩\n거리 : 한 거리는 오이나 가지 (    ) 개",
                      num1Text: "80",
                      num2Text: "82",
                      num3Text: "90",
                      num4Text: "94",
                      answer: 4),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 시어에서 ‘외롭고 쓸쓸한 화자의 심정’을 나타내기 위해 동원된 객관적 상관물로서 화자 자신과 동일시되는 소재는?",
                      reference: "㉠"+"春雨".underLined+"暗西池\n봄비 내리니 서쪽 못은 어둑한데\n輕寒襲㉡"+"羅幕".underLined+"\n찬바람은 비단 장막으로 스며드네.\n愁依小㉢"+"屛風".underLined+"\n시름에 겨워 작은 병풍에 기대니\n墻頭㉣"+"杏花".underLined+"落\n담장 위에 살구꽃이 떨어지네.",
                      num1Text: "㉠",
                      num2Text: "㉡",
                      num3Text: "㉢",
                      num4Text: "㉣",
                      answer: 4),
        QuestionModel(num: 5,
                      questionText: "다음 시조에 대한 설명으로 적절하지 않은 것은?",
                      reference: "재 너머 셩권농(成勸農) 집의 술 닉닷 말 어제 듯고\n누은 쇼 발로 박차 언치 노하 지즐고\n아야 네 권농 겨시냐 뎡좌슈(鄭座首) 왓다 여라",
                      num1Text: "화자는 소박한 풍류를 즐기며 살고 있다.",
                      num2Text: "‘박차’라는 표현에서 역동성과 생동감을 느낄 수 있다.",
                      num3Text: "‘언치 노하’는 엄격한 격식을 갖추려는 태도를 드러낸다.",
                      num4Text: "‘아’는 화자의 의사를 간접적으로 전달하는 존재이면서도, 대화체로 이끄는 영탄적 어구이다.",
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 말을 한자로 바르게 표기한 것은?",
                      reference: "○ 지루한 ㉠"+"장광설".underLined+"로 인해 관중들은 하나씩 자리를 뜨기 시작했다.\n○ 정보화 사회일수록 ㉡"+"유언비어".underLined+"가 떠돌 수 있는 가능성도 높다.\n○ 잘못을 저질렀다면 궁색한 ㉢"+"변명".underLined+"보다 정직한 시인이 현명한 대응이다.",
                      num1Text: "長廣舌 - 流言蜚語 - 辨明",
                      num2Text: "長廣舌 - 流言非語 - 辯明",
                      num3Text: "長廣說 - 流言蜚語 - 辯明",
                      num4Text: "長廣說 - 流言非語 - 辨明",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "다음 시에 대한 설명으로 적절하지 않은 것은?",
                      reference: "老主人의 腸壁에\n無時로 忍冬 삼긴 물이 나린다.\n\n자작나무 덩그럭 불이\n도로 피여 붉고,\n\n구석에 그늘 지여\n무가 순 돋아 파릇하고,\n\n흙냄새 훈훈히 김도 사리다가\n바깥 風雪 소리에 잠착하다.\n\n山中에 冊曆도 없이\n三冬이 하이얗다.\n\n－ 정지용, 〖忍冬茶〗 －",
                      num1Text: "산중의 고적한 공간이 배경이다.",
                      num2Text: "시각적 대조의 방법이 사용되었다.",
                      num3Text: "한 폭의 그림과 같은 인상을 준다.",
                      num4Text: "‘잠착하다’는 ‘여러모로 고려하다’의 의미다.",
                      answer: 4),
        QuestionModel(num: 8,
                      questionText: "“숙희야, 내가 선생님께 꽃다발을 드렸다.”의 문장을 다음 규칙에 따라 옳게 표시한 것은?",
                      reference: "우리말에는 주체 높임, 객체 높임, 상대 높임 등이 있다. 주체 높임과 객체 높임의 경우 높임은 ＋로, 높임이 아닌 것은 －로 표시하고 상대 높임의 경우 반말체를 －로, 해요체를 ＋로 표시한다.",
                      num1Text: "[주체－], [객체＋], [상대－]",
                      num2Text: "[주체＋], [객체－], [상대＋]",
                      num3Text: "[주체－], [객체＋], [상대＋]",
                      num4Text: "[주체＋], [객체－], [상대－]",
                      answer: 1),
        QuestionModel(num: 9,
                      questionText: "‘시’에 대한 견해 중에서 밑줄 친 칸트의 입장과 부합하는 것은?",
                      reference: "  미적인 것이란 내재적이고 선험적인 예술 작품의 특성을 밝히는 데서 더 나아가 삶의 풍부하고 생동적인 양상과 가치, 목표를 예술 형식으로 변환한 것이다. 미(美)는 어떤 맥락으로부터도 자율적이기도 하지만 타율적이다. 미에 대한 자율적 견해를 지닌 칸트도 일견 타당하지만, 미를 도덕이나 목적론과 연관시킨 톨스토이나 마르크스도 타당하다. 우리가 길을 지나다 이름 모를 곡을 듣고서 아름답다고 느끼는 것처럼 순수미의 영역이 없는 것은 아니다. 하지만 그 곡이 독재자를 열렬히 지지하기 위한 선전곡이었음을 안 다음부터 그 곡을 혐오하듯 미(美) 또한 사회 경제적, 문화적 맥락의 영향을 받기도 한다.",
                      num1Text: "시는 정제된 시어와 운율을 통하여 감상해야 한다.",
                      num2Text: "시는 사회의 모순을 고발할 수 있고, 개혁의 전망도 제시할 수 있다.",
                      num3Text: "시를 읽으면 시인과의 대화를 통해 정서적 성장을 도모할 수 있다.",
                      num4Text: "시를 감상하기 위해서는 당시의 사회 상황을 알아야 한다.",
                      answer: 1),
        QuestionModel(num: 10,
                      questionText: "밑줄 친 말의 뜻이 옳지 않은 것은?",
                      reference: "  때는 한창 바쁠 추수 때이다. 농군치고 송이 ㉠"+"파적".underLined+" 나올 놈은 생겨나도 않았으리라. 하나 그는 꼭 해야만 할 일이 없었다. 싶으면 하고 말면 말고 그저 그뿐. 그러함에는 먹을 것이 더러 있느냐면 있기는커녕 부쳐 먹을 농토조차 없는, 계집도 없고 자식도 없고. 방은 있대야 남의 곁방이요 잠은 ㉡"+"새우잠".underLined+"이요. 하지만 오늘 아침만 해도 한 친구가 찾아와서 벼를 털 텐데 일 좀 와 해달라는 걸 마다하였다. 몇 푼 바람에 그까짓 걸 누가 하느냐보다는 송이가 좋았다. 왜냐면 이 땅 삼천리강산에 늘여 놓인 곡식이 말짱 뉘 것이람. 먼저 먹는 놈이 임자 아니냐. 먹다 걸릴 만치 그토록 양식을 쌓아 두고 일이 다 무슨 ㉢"+"난장".underLined+" 맞을 일이람. 걸리지 않도록 먹을 궁리나 할 게지. 하기는 그도 한 세 번이나 걸려서 구메밥으로 ㉣"+"사관".underLined+"을 틀었다마는 결국 제 밥상 위에 올라앉은 제 몫도 자칫하면 먹다 걸리긴 매일반.......\n\n- 김유정, 〖만무방〗 중에서-",
                      num1Text: "㉠: 심심풀이",
                      num2Text: "㉡: 안잠",
                      num3Text: "㉢: 몰매",
                      num4Text: "㉣: 양쪽 팔꿈치와 무릎 관절",
                      answer: 2),
        QuestionModel(num: 11,
                      questionText: "다음 시조의 주제로 적절한 것은?",
                      reference: "내 죠타 고  슬흔 일 지 말며\n이 다 고 義 아니면 좃지 말니\n우리 天性을 직희여 삼긴 대로 리라",
                      num1Text: "率性",
                      num2Text: "善交",
                      num3Text: "遵法",
                      num4Text: "篤學",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "밑줄 친 말이 표준어인 것은?",
                      num1Text: "큰 죄를 짓고도 그는 "+"뉘연히".underLined+" 대중 앞에 나섰다.",
                      num2Text: "아주머니는 부엌에서 갖가지 양념을 "+"뒤어내고".underLined+" 있었다.",
                      num3Text: "사업에 실패했던 원인을 이제야 "+"깨단하게".underLined+" 되었다.",
                      num4Text: "그 사람은 "+"허구헌".underLined+" 날 팔자 한탄만 한다.",
                      answer: 3),
        QuestionModel(num: 13,
                      questionText: "밑줄 친 말의 한자 표기가 옳지 않은 것은?",
                      reference: "  지조란 것은 순일한 정신을 지키기 위한 불타는 신념이요, 눈물겨운 정성이며, 냉철한 ㉠"+"확집(確執)".underLined+"이요, 고귀한 투쟁이기까지 하다. 지조가 교양인의 ㉡"+"위의(威儀)".underLined+"를 위하여 얼마나 값지고 그것이 국민의 교화에 미치는 힘이 얼마나 크며, 따라서 지조를 지키기 위한 괴로움이 얼마나 가혹한가를 헤아리는 사람들은 한 나라의 지도자를 평가하는 기준으로서 먼저 그 지조의 ㉢"+"강도(强度)".underLined+"를 살피려 한다. 지조가 없는 지도자는 믿을 수가 없고 믿을 수 없는 지도자는 따를 수가 없기 때문이다. 자기의 명리만을 위하여 그 동지와 지지자와 추종자를 ㉣"+"일조(日照)".underLined+"에 함정에 빠뜨리고 달아나는 지조 없는 지도자의 무절제와 배신 앞에 우리는 얼마나 많이 실망하였는가.\n\n- 조지훈, 〖지조론〗 중에서 -",
                      num1Text: "㉠",
                      num2Text: "㉡",
                      num3Text: "㉢",
                      num4Text: "㉣",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "밑줄 친 말의 품사가 같은 것으로만 묶은 것은?",
                      reference: "개나리꽃이 ㉠"+"흐드러지게".underLined+" 핀 교정에서 친구들과 ㉡"+"찍은".underLined+" 사진은, 그때 느꼈던 ㉢"+"설레는".underLined+" 행복감은 물론, 대기 중에 ㉣"+"충만".underLined+"한 봄의 기운, 친구들과의 악의 ㉤"+"없는".underLined+" 농지거리, 벌들의 잉잉거림까지 현장에 있는 것과 다름없이 느끼게 해 준다.",
                      num1Text: "㉠, ㉢, ㉣",
                      num2Text: "㉠, ㉣, ㉤",
                      num3Text: "㉡, ㉢, ㉤",
                      num4Text: "㉢, ㉣, ㉤",
                      answer: 2),
        QuestionModel(num: 15,
                      questionText: "밑줄 친 말에 대한 설명으로 적합한 것은?",
                      reference: "  하나의 패러다임의 형성은 당초에는 불완전하며, 다만 이후 연구의 방향을 제시하고 소수 특정 부분의 성공적인 결과를 약속할 수 있을 뿐이다. 그러나 패러다임의 정착은 연구의 정밀화, 집중화 등을 통하여 자기 지식을 확장해 가며 차츰 폭 넓은 이론 체계를 구축한다.\n  이처럼 과학자들이 패러다임을 기반으로 하여 연구를 진척시키는 것을 쿤은 ‘정상 과학’이라고 부른다. 기초적인 전제가 확립되었으므로 과학자들은 이 시기에 상당히 심오한 문제의 작은 영역들에 집중함으로써, 그렇지 않았더라면 상상조차 못했을 자연의 어느 부분을 깊이 있게 탐구하게 된다. 그에 따라 각종 실험 장치들도 정밀해지고 다양해지며, 문제를 해결해 가는 특정 기법과 규칙들이 만들어진다. 연구는 이제 혼란으로서의 다양성이 아니라, 이론과 자연 현상을 일치시켜 가는 지식의 확장으로서의 다양성을 이루게 된다.\n  그러나 정상 과학은 완성된 과학이 아니다. 과학적 사고방식과 관습, 기법 등이 하나의 기반으로 통일돼 있다는 것일 뿐 해결해야 할 과제는 무수하다. 패러다임이란 과학자들 사이의 세계관의 통일이지 세계에 대한 해석의 끝은 아닌 것이다.\n  그렇다면 "+"정상 과학의 시기".underLined+"에는 어떤 연구가 어떻게 이루어지는가? 정상 과학의 시기에는 이미 이론의 핵심 부분들은 정립돼 있다. 따라서 과학자들의 연구는 근본적인 새로움을 좇아가지는 않으며, 다만 연구의 세부 내용이 좀 더 깊어지거나 넓어질 뿐이다. 이러한 시기에 과학자들의 열정과 헌신성은 무엇으로 유지될 수 있을까? 연구가 고작 예측된 결과를 좇아갈 뿐이고, 예측된 결과가 나오지 않으면 실패라고 규정되는 상태에서 과학의 발전은 어떻게 이루어지는가?\n  쿤은 이 물음에 대하여 ‘수수께끼 풀이’라는 대답을 준비한다. 어떤 현상의 결과가 충분히 예측된다 할지라도 정작 그 예측이 달성되는 세세한 과정은 대개 의문 속에 있게 마련이다. 자연 현상의 전 과정을 우리가 일목요연하게 알고 있는 것은 아니기 때문이다. 이론으로서의 예측 결과와 실제의 현상을 일치시켜 보기 위해서는 여러 복합적인 기기적, 개념적, 수학적인 방법이 필요하다. 이것이 수수께끼 풀이이다.",
                      num1Text: "여러 가지 상반된 시각의 학설이 등장하여 이론이 다양해지고 풍성해진다.",
                      num2Text: "과학적 패러다임의 정착으로 이론의 핵심 부분들이 정립되어 있다.",
                      num3Text: "이 시기의 패러다임의 형성은 처음에는 불완전하나 후속 연구를 통해 세계를 완전히 해석할 수 있는 과학으로 발전된다.",
                      num4Text: "예측된 결과만을 좇을 수밖에 없기 때문에 과학자들의 열정과 헌신성이 낮아진다.",
                      answer: 2),
        QuestionModel(num: 16,
                      questionText: "‘잡다’의 유의어에 해당하는 예문으로 적절하지 않은 것은?",
                      imgModel: ImageModel(imageString: "201721-16", imgWidth: 330, imgHeight: 150),
                      num1Text: "㉠: 할아버지는 돼지를 "+"잡아".underLined+" 잔치를 베푸셨다.",
                      num2Text: "㉡: 그들은 멱살을 "+"잡고".underLined+" 싸우고 있다.",
                      num3Text: "㉢: 술집 주인은 손님의 시계를 술값으로 "+"잡았다.".underLined,
                      num4Text: "㉣: 산불이 난 지 열 시간 만에 불길을 "+"잡았다.".underLined,
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "다음 글을 통해서 답을 찾을 수 없는 질문은?",
                      reference: "  해안에서 밀물에 의해 해수가 해안선에 제일 높게 들어온 곳과 썰물에 의해 제일 낮게 빠진 곳의 사이에 해당하는 부분을 조간대라고 한다. 지구상에서 생물이 살기에 열악한 환경 중 한 곳이 바로 이 조간대이다. 이곳의 생물들은 물에 잠겨 있을 때와 공기 중에 노출될 때라는 상반된 환경에삶을 맞춰야 한다. 또한 갯바위에 부서지는 파도의 파괴력도 견뎌내야 한다. 또한 빗물이라도 고이면 민물이라는 환경 에도 적응해야 하며, 강한 햇볕으로 바닷물이 증발하고 난 다음에는 염분으로 범벅된 몸을 추슬러야 한다. 이러한 극단적이고 변화무쌍한 환경에 적응할 수 있는 생물만이 조간대에서 살 수 있다.\n  조간대는 높이에 따라 상부, 중부, 하부로 나뉜다. 바다 로부터 가장 높은 곳인 상부는 파도가 강해야만 물이 겨우 닿는 곳이다. 그래서 조간대 상부에 사는 생명체는 뜨거운 태양열을 견뎌내야 한다. 중부는 만조 때에는 물에 잠기지만 간조 때에는 공기 중에 노출되는 곳이다. 그런데 물이 빠져 공기 중에 노출되었다 해도 파도에 의해 어느 정도의 수분은 공급된다. 가장 아래에 위치한 하부는 간조시를 제외하고는 항상 물에 잠겨 있다. 땅위 환경의 영향을 적게 받는다는 점에선 다소 안정적이긴 해도 파도의 파괴력을 이겨내기 위해 강한 부착력을 지녀야 한다는 점에서 생존이 쉽지 않은 곳이다.\n  조간대에 사는 생물들은 불안정하고 척박한 바다 환경에 적응하기 위해 높이에 따라 수직으로 종이 분포한다. 조간대를 찾았을 때 총알고둥류와 따개비들을 발견했다면 그곳이 조간대에서 물이 가장 높이 올라오는 지점인 것이다. 이들은 상당 시간 물 밖에 노출되어도 수분 손실을 막기 위해 패각과 덮개 판을 꼭 닫은 채 물이 밀려올 때까지 버텨낼 수 있다.",
                      num1Text: "조간대에서 총알고둥류가 사는 곳은 어느 지점인가?",
                      num2Text: "조간대의 중부에 사는 생물에는 어떠한 것이 있는가?",
                      num3Text: "조간대에서 높이에 따라 생물의 종이 수직으로 분포하는 이유는 무엇인가?",
                      num4Text: "조간대에 사는 생물들이 견뎌야 하는 환경적 조건에는 어떠한 것이 있는가?",
                      answer: 2),
        QuestionModel(num: 18,
                      questionText: "다음의 개요를 기초로 하여 글을 쓸 때, 주제문으로 가장 적절한 것은?",
                      reference: "서론 : 최근의 수출 실적 부진 현상\n본론 : 수출 경쟁력의 실태 분석\n  1. 가격 경쟁력 요인\n   ㄱ. 제조 원가 상승\n   ㄴ. 고금리\n   ㄷ. 환율 불안정\n  2. 비가격 경쟁력 요인\n   ㄱ. 기업의 연구 개발 소홀\n   ㄴ. 품질 개선 부족\n   ㄷ. 판매 후 서비스 부족 ㄹ. 납기의 지연\n결론 : 분석 결과의 요약 및 수출 경쟁력 향상 방안 제시",
                      num1Text: "정부가 수출 분야 산업을 적극 지원해야 한다.",
                      num2Text: "내수 시장의 기반을 강화하는 데 역량을 모아야 한다.",
                      num3Text: "기업이 연구 개발비 투자를 늘리고 품질 향상에 많은 노력을 기울여야 한다.",
                      num4Text: "수출 경쟁력을 좌우하는 요인을 분석한 후 그에 맞는 방안을 마련해야 한다.",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "㉠~㉦에 대한 설명으로 옳은 것은?",
                      reference: "  ㉠"+"그쪽".underLined+"에서 물건 하나를 맡아 주었으면 해요. 그건 ㉡"+"우리".underLined+" 할머니의 유품이에요. ㉢"+"저".underLined+"는 할머니의 유지에 따라 당신에게 그것을 전해야 할 책임을 느껴요. ㉣"+"할머니".underLined+"께서는 ㉤"+"본인".underLined+"의 생각을 저에게 누차 말씀하신 바 있기 때문이죠. 부디 ㉥당신이 할머니가 품었던 호의를 거절하지 않기를 바랍니다. 아시다시피 할머니는 결코 말씀이 많으신 분은 아니었지요. ㉦"+"당신".underLined+"께서 생전에 표현하지 못했던 심정이 거기에 절실히 아로새겨져 있을 거예요.",
                      num1Text: "㉠과 ㉢은 1인칭 대명사이다.",
                      num2Text: "㉡은 ㉢과 ㉣을 아우르는 말이다.",
                      num3Text: "㉣과 ㉦은 같은 사람을 가리키는 말이다.",
                      num4Text: "㉤과 ㉥은 같은 사람을 가리키는 말이다.",
                      answer: 3),
        QuestionModel(num: 20,
                      questionText: "다음 글의 논증 구조를 옳게 파악한 것은?",
                      reference: "  ㉠동물들의 행동을 잘 살펴보면 동물들도 우리가 사용하는 말 못지않은 의사소통 수단을 가지고 있는 듯이 보인다. ㉡즉, 동물들도 여러 가지 소리를 내거나 몸짓을 함으로써 자신들의 감정과 기분을 나타낼 뿐 아니라 경우에 따라서는 인간과 다를 바 없이 의사를 교환하고 있는 듯하다. ㉢그러나 그것은 단지 겉모습의 유사성에 지나지 않을 뿐이고 사람의 말과 동물의 소리에는 아주 근본적인 차이가 존재한다는 점을 잊어서는 안 된다. ㉣동물들이 사용하는 소리는 단지 배고픔이나 고통 같은 생물학적인 조건에 대한 반응이거나, 두려움이나 분노 같은 본능적인 감정들을 표현하기 위한 것에 지나지 않는다. ㉤따라서, 동물들이 내는 소리가 때때로 의사소통의 수단으로 이용된다고 해서 그것을 대화나 토론이나 회의와 같은 언어활동이라고 할 수는 없다.",
                      num1Text: "㉠은 논증의 결론으로 주제문이다.",
                      num2Text: "㉡은 ㉠의 논리적 결함을 지적한 것이다.",
                      num3Text: "㉢은 ㉠, ㉡을 부정하고 새로운 논점을 제시한 것이다.",
                      num4Text: "㉤은 ㉢, ㉣에 대한 근거이다.",
                      answer: 3),
        ]
        let exam = ExamModel(id: 201721, year: 2017, examTypeID: "지방직", subjectID: "국어", questions: questions)
        exam2017.append(exam)
    }
    func saveExam201722() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오. [1~2]",
                      reference: "  A: I just received a letter from one of my old high school buddies.\n  B: That's nice!\nA:Well, actually it's been a long time since I heard from him.\n  B:To be honest, I've been out of touch with most of my old friends.\n  A: I know. It's really hard to maintain contact when people move around so much.\n  B: You're right. ____________________________________. But you're lucky to be back in touch with your buddy  again.",
                      num1Text: "The days are getting longer",
                      num2Text: "People just drift apart",
                      num3Text: "That's the funniest thing I've ever heard of",
                      num4Text: "I start fuming whenever I hear his name",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "",
                      reference: "  A: What are you getting Ted for his birthday? I'm getting him a couple of baseball caps.\n  B: I've been _____________________ trying to think of just the right gift. I don't have an inkling of what he needs.\n  A: Why don't you get him an album? He has a lot of photos.\n  B: That sounds perfect! Why didn't I think of that? Thanks for the suggestion!",
                      num1Text: "contacted by him",
                      num2Text: "sleeping all day",
                      num3Text: "racking my brain",
                      num4Text: "collecting photo albums",
                      answer: 3),
        QuestionModel(num: 3,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오. [3~5]",
                      reference: "Some of the newest laws authorize people to appoint a "+"surrogate".underLined+" who can make medical decisions for them when necessary.",
                      num1Text: "proxy",
                      num2Text: "sentry",
                      num3Text: "predecessor",
                      num4Text: "plunderer",
                      answer: 1),
        QuestionModel(num: 4,
                      questionText: "",
                      reference: "  A: He thinks he can achieve anything.\n  B: Yes, he needs to keep his feet on the ground.",
                      num1Text: "live in a world of his own",
                      num2Text: "relax and enjoy himself",
                      num3Text: "be brave and confident",
                      num4Text: "remain sensible and realistic about life",
                      answer: 4),
        QuestionModel(num: 5,
                      questionText: "",
                      reference: "She is "+"on the fence".underLined+" about going to see the Mona Lisa at the Louvre Museum.",
                      num1Text: "anguished",
                      num2Text: "enthusiastic",
                      num3Text: "apprehensive",
                      num4Text: "undecided",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "어법상 옳지 않은 것은?",
                      num1Text: "You might think that just eating a lot of vegetables will keep you perfectly healthy.",
                      num2Text: "Academic knowledge isn't always that leads you to make right decisions.",
                      num3Text: "The fear of getting hurt didn't prevent him from engaging in reckless behaviors.",
                      num4Text: "Julie's doctor told her to stop eating so many processed foods.",
                      answer: 2),
        QuestionModel(num: 7,
                      questionText: "어법상 옳은 것은?",
                      num1Text: "The oceans contain many forms of life that has not yet been discovered.",
                      num2Text: "The rings of Saturn are so distant to be seen from Earth without a telescope.",
                      num3Text: "The Aswan High Dam has been protected Egypt from the famines of its neighboring countries.",
                      num4Text: "Included in this series is “The Enchanted Horse,” among other famous children's stories.",
                      answer: 4),
        QuestionModel(num: 8,
                      questionText: "다음 글의 내용과 일치하는 것은?",
                      reference: "Soils of farmlands used for growing crops are being carried away by water and wind erosion at rates between 10 and 40 times the rates of soil formation, and between 500 and 10,000 times soil erosion rates on forested land. Because those soil erosion rates are so much higher than soil formation rates, that means a net loss of soil. For instance, about half of the top soil of Iowa, the state whose agriculture productivity is among the highest in the U.S., has been eroded in the last 150 years. On my most recent visit to Iowa, my hosts showed me a churchyard offering a dramatically visible example of those soil losses. A church was built there in the middle of farmland during the 19th century and has been maintained continuously as a church ever since, while the land around it was being farmed. As a result of soil being eroded much more rapidly from fields than from the churchyard, the yard now stands like a little island raised 10 feet above the surrounding sea of farmland.",
                      num1Text: "A churchyard in Iowa is higher than the surrounding farmland.",
                      num2Text: "Iowa's agricultural productivity has accelerated its soil formation",
                      num3Text: "The rate of soil formation in farmlands is faster than that of soil erosion.",
                      num4Text: "Iowa has maintained its top soil in the last 150 years.",
                      answer: 1),
        QuestionModel(num: 9,
                      questionText: "다음 글의 흐름상 가장 어색한 문장은?",
                      reference: "Whether you've been traveling, focusing on your family, or going through a busy season at work, 14 days out of the gym takes its toll―not just on your muscles, but your performance, brain, and sleep, too. ①"+"Most experts agree that after two weeks, you're in trouble if you don't get back in the gym.".underLined+" “At the two week point without exercising, there are a multitude of physiological markers that naturally reveal a reduction of fitness level,” says Scott Weiss, a New York-based exercise physiologist and trainer who works with elite athletes. ②"+"After all, despite all of its abilities, the human body (even the fit human body) is a very sensitive system and physiological changes (muscle strength or a greater aerobic base) that come about through training will simply disappear if your training load dwindles, he notes.".underLined+" Since the demand of training isn't present, your body simply slinks back toward baseline. ③"+"More protein is required to build more muscles at a rapid pace in your body.".underLined+" ④"+"Of course, how much and how quickly you'll decondition depends on a slew of factors like how fit you are, your age, and how long sweating has been a habit.".underLined+" “Two to eight months of not exercising at all will reduce your fitness level to as if you never exercised before,” Weiss notes.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 3),
        QuestionModel(num: 10,
                      questionText: "다음 글의 내용과 일치하지 않는 것은?",
                      reference: "Before the fifteenth century, all four characteristics of the witch (night flying, secret meetings, harmful magic, and the devil's pact) were ascribed individually or in limited combination by the church to its adversaries, including Templars, heretics, learned magicians, and other dissident groups. Folk beliefs about the supernatural emerged in peasant confessions during witch trials. The most striking difference between popular and learned notions of witchcraft lay in the folk belief that the witch had innate supernatural powers not derived from the devil. For learned men, this bordered on heresy. Supernatural powers were never human in origin, nor could witches derive their craft from the tradition of learned magic, which required a scholarly training at the university, a masculine preserve at the time. A witch's power necessarily came from the pact she made with the devil.",
                      num1Text: "The folk and learned men had different views on the source of the witch's supernatural powers.",
                      num2Text: "According to the folk belief, supernatural powers belonged to the essential nature of the witch.",
                      num3Text: "Four characteristics of the witch were attributed by the church to its dissident groups.",
                      num4Text: "Learned men believed that the witch's power came from a scholarly training at the university.",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "주어진 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "Fortunately, however, the heavy supper she had eaten caused her to become tired and ready to fall asleep.",
                      reference2: "Various duties awaited me on my arrival. I had to sit with the girls during their hour of study. ( ① ) Then it was my turn to read prayers; to see them to bed. Afterwards I ate with the other teachers. ( ② ) Even when we finally retired for the night, the inevitable Miss Gryce was still my companion. We had only a short end of candle in our candlestick, and I dreaded lest she should talk till it was all burnt out. ( ③ ) She was already snoring before I had finished undressing. There still remained an inch of candle. ( ④ ) I now took out my letter; the seal was an initial F. I broke it; the contents were brief.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 3),
        QuestionModel(num: 12,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "Fear and its companion pain are two of the most useful things that men and animals possess, if they are properly used. If fire did not hurt when it burnt, children would play with it until their hands were burnt away. Similarly, if pain existed but fear did not, a child would burn himself again and again, because fear would not warn him to keep away from the fire that had burnt him before. A really fearless soldier―and some do exist―is not a good soldier, because he is soon killed; and a dead soldier is of no use to his army. Fear and pain are therefore two guards without which human beings and animals might soon die out.",
                      num1Text: "Obscurity of Fear and Pain in Soldiers",
                      num2Text: "Indispensability of Fear and Pain",
                      num3Text: "Disapproval of Fear and Pain",
                      num4Text: "Children's Association with Fear and Pain",
                      answer: 2),
        QuestionModel(num: 13,
                      questionText: "우리말을 영어로 잘못 옮긴 것을 고르시오. [13~14]",
                      num1Text: "나는 매달 두세 번 그에게 전화하기로 규칙을 세웠다.\n→ I made it a rule to call him two or three times a month.",
                      num2Text: "그는 나의 팔을 붙잡고 도움을 요청했다.\n→ He grabbed me by the arm and asked for help.",
                      num3Text: "폭우로 인해 그 강은 120cm 상승했다.\n→ Owing to the heavy rain, the river has risen by 120cm.",
                      num4Text: "나는 눈 오는 날 밖에 나가는 것보다 집에 있는 것을 더 좋아한다.\n→ I prefer to staying home than to going out on a snowy day.",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "",
                      num1Text: "그를 당황하게 한 것은 그녀의 거절이 아니라 그녀의 무례함 이었다.\n→ It was not her refusal but her rudeness that perplexed him.",
                      num2Text: "부모는 아이들 앞에서 그들의 말과 행동에 대해 아무리 신중 해도 지나치지 않다.\n→ Parents cannot be too careful about their words and actions before their children.",
                      num3Text: "환자들과 부상자들을 돌보기 위해 더 많은 의사가 필요했다.\n→ More doctors were required to tend sick and wounded.",
                      num4Text: "설상가상으로, 또 다른 태풍이 곧 올 것이라는 보도가 있다.\n→ To make matters worse, there is a report that another typhoon will arrive soon.",
                      answer: 3),
        QuestionModel(num: 15,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오. [15~16]",
                      reference: "Our main dish did not have much flavor, but I made it more ____________ by adding condiments.",
                      num1Text: "palatable",
                      num2Text: "dissolvable",
                      num3Text: "potable",
                      num4Text: "susceptible",
                      answer: 1),
        QuestionModel(num: 16,
                      questionText: "",
                      reference: "London taxi drivers have to undertake years of intense training known as “the knowledge” to gain their operating license, including learning the layout of over twenty-five thousand of the city's streets. A researcher and her team investigated the taxi drivers and the ordinary people. The two groups were asked to watch videos of routes unfamiliar to them through a town in Ireland. They were then asked to take a test about the video that included sketching out routes, identifying landmarks, and estimating distances between places. Both groups did well on much of the test, but the taxi drivers did significantly better on identifying new routes. This result suggests that the taxi drivers' mastery can be _____________ to new and unknown areas. Their years of training and learning through deliberate practice prepare them to take on similar challenges even in places they do not know well or at all.",
                      num1Text: "confined",
                      num2Text: "devoted",
                      num3Text: "generalized",
                      num4Text: "contributed",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "I remember the day Lewis discovered the falls. They left their camp at sunrise and a few hours later they came upon a beautiful plain and on the plain were more buffalo than they had ever seen before in one place.",
                      reference2: "(A) A nice thing happened that afternoon, they went fishing below the falls and caught half a dozen trout, good ones, too, from sixteen to twenty-three inches long.\n\n(B) After a while the sound was tremendous and they were at the great falls of the Missouri River. It was about noon when they got there.\n\n(C) They kept on going until they heard the faraway sound of a waterfall and saw a distant column of spray rising and disappearing. They followed the sound as it got louder and louder.",
                      num1Text: "(A)-(B)-(C)",
                      num2Text: "(B)-(C)-(A)",
                      num3Text: "(C)-(A)-(B)",
                      num4Text: "(C) -(B) -(A)",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "다음 글의 요지로 가장 적절한 것은?",
                      reference: "Novelty-induced time expansion is a well-characterized phenomenon which can be investigated under laboratory conditions. Simply asking people to estimate the length of time they are exposed to a train of stimuli shows that novel stimuli simply seem to last longer than repetitive or unremarkable ones. In fact, just being the first stimulus in a moderately repetitive series appears to be sufficient to induce subjective time expansion. Of course, it is easy to think of reasons why our brain has evolved to work like this—presumably novel and exotic stimuli require more thought and consideration than familiar ones, so it makes sense for the brain to allocate them more subjective time.",
                      num1Text: "Response to stimuli is an important by-product of brain training.",
                      num2Text: "The intensity of stimuli increases with their repetition.",
                      num3Text: "Our physical response to stimuli influences our thoughts.",
                      num4Text: "New stimuli give rise to subjective time expansion.",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오. [19~20]",
                      reference: "One of the tricks our mind plays is to highlight evidence which confirms what we already believe. If we hear gossip about a rival, we tend to think “I knew he was a nasty piece of work”; if we hear the same about our best friend, we're more likely to say “that's just a rumour.” Once you learn about this mental habit―called confirmation bias―you start seeing it everywhere. This matters when we want to make better decisions. Confirmation bias is OK as long as we're right, but all too often we're wrong, and we only pay attention to the deciding evidence when it's too late. How ________________________________________________ depends on our awareness of why, psychologically, confirmation bias happens. There are two possible reasons. One is that we have a blind spot in our imagination and the other is we fail to ask questions about new information.",
                      num1Text: "we make our rivals believe us",
                      num2Text: "our blind spot helps us make better decisions",
                      num3Text: "we can protect our decisions from confirmation bias",
                      num4Text: "we develop exactly the same bias",
                      answer: 3),
        QuestionModel(num: 20,
                      questionText: "",
                      reference: "For many big names in consumer product brands, exporting and producing overseas with local labor and for local tastes have been the right thing to do. In doing so, the companies found a way to improve their cost structure, to grow in the rapidly expanding consumer markets in emerging countries. But, Sweets Co. remains stuck in the domestic market. Even though its products are loaded with preservatives, which means they can endure long travel to distant markets, Sweets Co. ___________________________________, let alone produce overseas. The unwillingness or inability to update its business strategy and products for a changing world is clearly damaging to the company.",
                      num1Text: "is intent on importing",
                      num2Text: "does very little exporting",
                      num3Text: "has decided to streamline operations",
                      num4Text: "is expanding into emerging markets",
                      answer: 2),
        ]
        let exam = ExamModel(id: 201722, year: 2017, examTypeID: "지방직", subjectID: "영어", questions: questions)
        exam2017.append(exam)
    }
    func saveExam201723() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "한반도 선사시대에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "구석기시대 전기에는 주먹도끼와 슴베찌르개 등이 사용되었다.",
                      num2Text: "신석기시대 집터는 대부분 움집으로 바닥은 원형이나 모서리가 둥근 사각형이다.",
                      num3Text: "신석기시대 사람들은 조개류를 많이 먹었으며, 때로는 장식 으로 이용하기도 하였다.",
                      num4Text: "청동기시대의 전형적인 유물로는 비파형동검․붉은간토기․반달돌칼․홈자귀 등이 있다.",
                      answer: 1),
        QuestionModel(num: 2,
                      questionText: "다음 자료를 쓴 역사가의 활동으로 옳은 것은?",
                      reference: "역사란 무엇이뇨. 인류 사회의 아와 비아의 투쟁이 시간부터 발전하며 공간부터 확대하는 심적 활동의 상태의 기록이니, 세계사라 하면 세계 인류의 그리되어 온 상태의 기록이며, 조선사라 하면 조선 민족의 그리되어 온 상태의 기록이니라.",
                      num1Text: "〖여유당전서〗를 발간하여 조선후기 실학자들을 재평가하였다",
                      num2Text: "을지문덕, 최영, 이순신 등 애국명장의 전기를 써서 애국심을 고취하였다.",
                      num3Text: "〖조선사회경제사〗를 저술하여 세계사적 보편성 속에서 한국사를 해석하였다.",
                      num4Text: "‘5천 년간 조선의 얼’이라는 글을 동아일보에 연재하여 민족 정신을 고취하였다.",
                      answer: 2),
        QuestionModel(num: 3,
                      questionText: "군사제도가 실시된 시기순으로 바르게 나열한 것은?",
                      imgModel: ImageModel(imageString: "201723-3", imgWidth: 330, imgHeight: 180),
                      num1Text: "ㄱ → ㄴ → ㄷ → ㄹ",
                      num2Text: "ㄱ → ㄹ → ㄴ → ㄷ",
                      num3Text: "ㄴ → ㄱ → ㄷ → ㄹ",
                      num4Text: "ㄴ → ㄹ → ㄱ → ㄷ",
                      answer: 2),
        QuestionModel(num: 4,
                      questionText: "(가), (나)의 특징을 가진 국가에 대한 설명으로 옳은 것은?",
                      reference: "(가) 옷은 흰색을 숭상하며, 흰 베로 만든 큰 소매 달린 도포와 바지를 입고 가죽신을 신는다.\n\n(나) 부여의 별종(別種)이라 하는데, 말이나 풍속 따위는 부여와 많이 같지만 기질이나 옷차림이 다르다.\n\n－ 〖삼국지〗 위서 동이전 －",
                      num1Text: "(가) － 혼인풍속으로 민며느리제가 있었다.",
                      num2Text: "(나) － 제사장인 천군이 다스리는 소도가 있었다.",
                      num3Text: "(가) － 남의 물건을 훔쳤을 때는 12배로 배상하게 하였다.",
                      num4Text: "(나) － 단궁이라는 활과 과하마․반어피 등이 유명하였다.",
                      answer: 3),
        QuestionModel(num: 5,
                      questionText: "다음 글을 지은 사람들의 공통점으로 옳은 것은?",
                      reference: "(가) 낭혜화상백월보광탑비문(朗慧和尙白月葆光塔碑文)\n(나) 대견훤기고려왕서(代甄萱寄高麗王書)\n(다) 낭원대사오진탑비명(郎圓大師悟眞塔碑銘)",
                      num1Text: "골품제를 비판하고 호족 억압을 주장하였다.",
                      num2Text: "국립 교육기관인 태학(太學)에서 공부하였다.",
                      num3Text: "신라뿐만 아니라 고려왕조에서도 벼슬하였다.",
                      num4Text: "당나라에 유학하여 빈공과(賓貢科)에 급제하였다.",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "다음 밑줄 친 ‘대사’에 대한 내용으로 옳지 않은 것은?",
                      reference: "이 엔닌은 "+"대사".underLined+"의 어진 덕을 입었기에 삼가 우러러 뵙지 않을 수 없습니다. 저는 이미 뜻한 바를 이루기 위해 당나라에 머물러 왔습니다. 부족한 이 사람은 다행히도 "+"대사".underLined+"께서 발원하신 적산원(赤山院)에 머물 수 있었던 것에 대해 감경(感慶)한 마음을 달리 비교해 말씀드리기가 어렵습니다.\n\n－ 〖입당구법순례행기〗 －",
                      num1Text: "법화원을 건립하고 이를 지원하였다.",
                      num2Text: "당나라에 가서 서주 무령군 소장이 되었다.",
                      num3Text: "회역사, 견당매물사 등의 교역 사절을 파견하였다.",
                      num4Text: "웅주를 근거지로 반란을 일으켜 장안(長安)이라는 나라를 세웠다.",
                      answer: 4),
        QuestionModel(num: 7,
                      questionText: "다음 (가)에서 이루어진 합의제도를 시행한 국가의 통치체제로 옳은 것은?",
                      reference: "호암사에는  (가)  (이)라는 바위가 있다. 나라에서 장차 재상을 뽑을 때에 후보 3, 4명의 이름을 써서 상자에 넣고 봉해 바위 위에 두었다가 얼마 후에 가지고 와서 열어 보고 그 이름 위에 도장이 찍혀 있는 사람을 재상으로 삼았다.\n\n－ 〖삼국유사〗 -",
                      reference2: "  ㄱ. 중앙정치는 대대로를 비롯하여 10여 등급의 관리들이 나누어 맡았다.\n  ㄴ. 중앙관청을 22개로 확대하고 수도는 5부, 지방은 5방 으로 정비하였다.\n  ㄷ. 16품의 관등제를 시행하고, 품계에 따라 옷의 색을 구별 하여 입도록 하였다.\n  ㄹ. 지방 행정 조직을 9주 5소경 체제로 정비하였다.\n  ㅁ. 중앙에 3성 6부를 두고, 정당성을 관장하는 대내상이 국정을 총괄하도록 하였다.",
                      num1Text: "ㄱ, ㄴ",
                      num2Text: "ㄴ, ㄷ",
                      num3Text: "ㄷ, ㄹ",
                      num4Text: "ㄹ, ㅁ",
                      answer: 2),
        QuestionModel(num: 8,
                      questionText: "다음 글을 쓴 사람에 대한 설명으로 옳은 것은?",
                      reference: "오늘날 백성을 다스리는 자는 백성에게서 걷어들이는 데만 급급하고 백성을 부양하는 방법은 알지 못한다. …… ‘심서 (心書)’라고 이름 붙인 까닭은 무엇인가? 백성을 다스릴 마음은 있지만 몸소 실행할 수 없기 때문에 그렇게 이름 붙인 것이다.",
                      num1Text: "우리나라에서 처음으로 지전설을 주장하였다.",
                      num2Text: "〖농가집성〗을 펴내 이앙법 보급에 공헌하였다.",
                      num3Text: "홍역 관련 의서를 종합해 마과회통 을 저술하였다.",
                      num4Text: "조선시대의 역사를 서술한 열조통기 를 편찬하였다.",
                      answer: 3),
        QuestionModel(num: 9,
                      questionText: "(가)와 (나)의 인물에 대한 <보기>의 설명으로 옳은 것은?",
                      reference: "  (가)는 “교(敎)를 배우는 이는 대개 안의 마음을 버리고 외면에서 구하고, 선(禪)을 익히는 이는 인연을 잊고 안의 마음을 밝히기를 좋아하니, 모두 한쪽에 치우친 것으로 두 극단에 모두 막힌 것이다.”라고 주장하였다.\n  (나)는 “정(定)은 본체이고 혜(慧)는 작용이다. 작용은 본체를 바탕으로 존재하므로 혜가 정을 떠나지 않고, 본체가 작용을 가져오게 하므로 정은 혜를 떠나지 않는다.”라고 주장하였다.",
                      reference2: "  ㄱ. (가)와 (나)는 서로 다른 방법으로 교종과 선종의 통합을 시도하였다.\n  ㄴ. (가)와 (나)는 지방 호족과 연합하여 신라 정부의 권위를 약화시켰다.\n  ㄷ. (가)는 불교와 유교 모두 도를 추구한다는 점에서 같다는 유․불 일치설을 주장하였다.\n  ㄹ. (나)는 수선사 결성을 제창하여 불교계의 개혁을 추진 하였다.",
                      num1Text: "ㄱ, ㄴ",
                      num2Text: "ㄱ, ㄹ",
                      num3Text: "ㄴ, ㄷ",
                      num4Text: "ㄴ, ㄹ",
                      answer: 2),
        QuestionModel(num: 10,
                      questionText: "다음 상황이 나타난 시기에 볼 수 있는 모습으로 옳은 것은?",
                      reference: "대외 무역이 발전하면서 예성강 어귀의 벽란도가 국제 무역항으로 번성했으며, 대식국(大食國)으로 불리던 아라비아 상인들도 들어와 수은․향료․산호 등을 팔았다.",
                      num1Text: "해동통보와 은병(銀甁) 같은 화폐를 만들어 사용하였다.",
                      num2Text: "인구․토지면적 등을 기록한 장적(帳籍, 촌락문서)이 작성되었다.",
                      num3Text: "개성의 송상은 전국에 송방(松房)이라는 지점을 개설해서 활동 하였다.",
                      num4Text: "지방 장시의 객주와 여각은 상품의 매매뿐 아니라 숙박․ 창고․운송 업무까지 운영하였다.",
                      answer: 1),
        QuestionModel(num: 11,
                      questionText: "조선시대 도성 한양에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "경복궁 근정전의 이름은 정도전이 지었다.",
                      num2Text: "경복궁의 동쪽에 사직이, 서쪽에 종묘가 각각 배치되었다.",
                      num3Text: "유교사상인 인․의․예․지 덕목을 담아 도성 4대문의 이름을 지었다.",
                      num4Text: "도성 밖 10리 안에는 개인의 무덤을 쓰거나 벌채를 하지 못하도록 규제하였다.",
                      answer: 2),
        QuestionModel(num: 12,
                      questionText: "밑줄 친 제도에 대한 설명으로 옳은 것은?",
                      reference: "국왕이 말했다. “나는 일찍부터 이 제도를 시행해 여러 해의 평균을 파악하고 답험(踏驗)의 폐단을 영원히 없애려고 해왔다. 신하들부터 백성까지 두루 물어보니 반대하는 사람은 적고 찬성하는 사람이 많았으므로 백성의 뜻도 알 수 있다.”",
                      num1Text: "토지의 비옥도에 따라 조세를 차등 징수하였다.",
                      num2Text: "풍흉에 상관없이 1결당 4 ～ 6두를 조세로 징수하였다.",
                      num3Text: "토지 소유자에게 1결당 미곡 12두를 조세로 징수하였다.",
                      num4Text: "토지 소유자에게 수확량의 10분의 1을 조세로 징수하였다.",
                      answer: 1),
        QuestionModel(num: 13,
                      questionText: "다음 지시에 따라 실시된 제도로 옳은 것은? [정답없음]",
                      reference: "왕이 양역을 절반으로 줄이라고 명령했다. “…… 호포 (戶布)나 결포(結布) 모두 문제가 있다. 이제 1필을 줄이는 것으로 온전히 돌아갈 것이니 경들은 1필을 줄였을 때 생기는 세입 감소분을 보충할 방법을 강구하라.”",
                      num1Text: "지조법을 시행하고 호조로 재정을 일원화하였다.",
                      num2Text: "토산물로 징수하던 공물을 쌀이나 무명, 동전 등으로 통일 하였다.",
                      num3Text: "황폐해진 농지를 개간하도록 권장하고 전국적인 양전 사업을 시행하였다.",
                      num4Text: "일부 양반층에게 선무군관이라는 칭호를 주고 군포 1필을 납부하게 하였다.",
                      answer: 0),
        QuestionModel(num: 14,
                      questionText: "임진왜란의 전개 과정에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "휴전협상이 진행되는 동안 조선은 훈련도감을 설치해 군대의 편제를 바꾸었다.",
                      num2Text: "조선군은 명나라 지원군과 연합하여 일본군에게 뺏긴 평양성을 탈환하였다.",
                      num3Text: "전세가 불리해지고 도요토미 히데요시가 죽자 일본군이 철수 함으로써 전란이 끝났다.",
                      num4Text: "첨사 정발은 부산포에서, 도순변사 신립은 상주에서 일본군과 맞서 싸웠지만 패배하였다.",
                      answer: 4),
        QuestionModel(num: 15,
                      questionText: "우리나라 족보에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "조선후기에 부유한 농민들은 족보를 사거나 위조하기도 하였다.",
                      num2Text: "조선초기의 족보는 친손과 외손을 구별하지 않고 모두 수록 하였다.",
                      num3Text: "현존하는 가장 오래된 족보는 성종 7년에 간행된 〖문화류씨가정보〗이다.",
                      num4Text: "조선시대에는 족보가 배우자를 구하거나 붕당을 구별하는 데 중요한 자료로 활용되기도 하였다.",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "다음 (가) ～ (라)를 내용으로 하는 헌법이 적용되던 시기에 일어난 사건으로 바르게 연결한 것은?",
                      reference: "(가) 대통령의 임기는 7년이며 중임할 수 없다.\n(나) 대통령과 부통령은 국회에서 무기명 투표로 각각 선거 한다.\n(다) 대통령과 부통령의 임기는 4년으로 하며, 1차 중임할 수 있다. 단, 이 헌법 공포 당시의 대통령에 대하여 중임 제한을 적용하지 아니한다.\n(라) 6년 임기의 대통령은 통일 주체 국민회의에서 선출된다.",
                      num1Text: "(가) － 남한과 북한은 함께 유엔에 가입하였다.",
                      num2Text: "(나) － 판문점에서 휴전 협정이 체결되었다.",
                      num3Text: "(다) － 평화통일론을 주장한 진보당의 정당등록이 취소되었다.",
                      num4Text: "(라) － 민족 통일을 위한 남북 공동 성명이 발표되었다.",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "다음 자료가 조선 조정에 소개된 이후에 일어난 사건으로 옳지 않은 것은?",
                      reference: "러시아를 막을 수 있는 조선의 책략은 무엇인가? 중국과 친하고〔親中〕 일본과 맺고〔結日〕 미국과 연합해〔聯美〕 자강을 도모하는 길 뿐이다.",
                      num1Text: "육영공원(育英公院)을 설립해 서양의 새 학문을 교육했다.",
                      num2Text: "임오군란이 일어나고 제물포조약이 체결되어 일본에 배상금을 지불하였다.",
                      num3Text: "개화파가 우정총국 개국 축하연을 이용해 정변을 일으켜 정권을 장악하였다.",
                      num4Text: "최익현은 일본과 통상을 반대하는 오불가소(五不可疏) 를 올렸다.",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "다음 자료에 나타난 사상을 정립한 인물에 대한 설명으로 옳지 않은 것은?",
                      reference: "우리나라의 건국정신은 삼균제도(三均制度)의 역사적 근거를 두었으니 선조들이 분명히 명한 바 수미균평위(首尾均平位) 하야 흥방보태평(興邦保泰平)하리라 하였다. 이는 사회 각층 각급의 지력과 권력과 부력의 향유를 균평하게 하야 국가를 진흥하며 태평을 보유(保維)하려 함이니 홍익인간(弘益人間)과 이화세계(理化世界)하자는 우리 민족의 지킬 바 최고 공리 (公理)임",
                      num1Text: "한국독립당을 창당하였다.",
                      num2Text: "임시정부의 국무위원이었다.",
                      num3Text: "제헌 국회의원에 당선되었다.",
                      num4Text: "정치․경제․교육의 균등을 주장하였다.",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "시대별 교육문화의 변화에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "미군정기 : 미국식 민주주의 교육과 6-3-3학제가 도입되었다.",
                      num2Text: "1950년대 : 경제적 어려움 속에서도 초등학교 의무교육제가 시행되었다.",
                      num3Text: "1960년대 : 입시과열을 막기 위해 중학교 무시험 추첨제가 도입 되었다.",
                      num4Text: "1970년대 : 국가주의 이념을 강조한 국민교육헌장이 제정되었다.",
                      answer: 4),
        QuestionModel(num: 20,
                      questionText: "다음 법령에 대한 설명으로 옳지 않은 것은?",
                      reference: "제1조 일본 정부와 통모하여 한․일 합병에 적극 협력한 자, 한국의 주권을 침해하는 조약 또는 문서에 조인한 자와 모의한 자는 사형 또는 무기 징역에 처하고, 그 재산과 유산의 전부 혹은 2분의 1 이상을 몰수 한다.\n\n제2조 일본 정부로부터 작위를 받은 자 또는 일본 제국 의회의 의원이 되었던 자는 무기 또는 5년 이상의 징역에 처하고 그 재산과 유산의 전부 혹은 2분의 1 이상을 몰수한다.\n\n제3조 일본 치하 독립운동자나 그 가족을 악의로 살상․ 박해한 자 또는 이를 지휘한 자는 사형, 무기 또는 5년 이상의 징역에 처하고 그 재산의 전부 혹은 일부를 몰수한다.",
                      num1Text: "이 법령에 따라 특별 재판부가 설치되었다.",
                      num2Text: "이 법령의 제정은 제헌헌법에 명시된 사항이었다.",
                      num3Text: "이 법령에 따라 반민족행위자들이 실형을 선고받았다.",
                      num4Text: "이 법령은 여수․순천 10․19 사건 직후에 국회에서 통과되었다.",
                      answer: 4),
        ]
        let exam = ExamModel(id: 201723, year: 2017, examTypeID: "지방직", subjectID: "한국사", questions: questions)
        exam2017.append(exam)
    }
}
