//
//  ExamStore2015.swift
//  HandGosi
//
//  Created by Sy Lee on 2022/08/26.
//
/*
 let questions =
 [
 QuestionModel(num: <#T##Int#>,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 2,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 3,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 4,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 5,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 6,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 7,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 8,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 9,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 10,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 11,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 12,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 13,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 14,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 15,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 16,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 17,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 18,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 19,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 20,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>)
 ]
 
 let exam = ExamModel(id: 201511, year: 2015, examTypeID: "국가직", subjectID: "국어", questions: questions)
 
 exam2015.append(exam)
 */
import Foundation

class ExamStore2015 {
    var exam2015: [ExamModel] = []
    
    init() {
        saveExam201511()
        saveExam201512()
        saveExam201513()
        
        saveExam201521()
        saveExam201522()
        saveExam201523()
    }
    
    func saveExam201511() {
        let questions =
        [
            QuestionModel(num: 1,
                          questionText: "어법에 맞게 쓰인 것은?",
                          num1Text: "내일 야유회 간데요?",
                          num2Text: "그이가 말을 아주 잘하대.",
                          num3Text: "연예인을 보니 그렇게 좋던?",
                          num4Text: "제가 직접 봤는데 너무 크대요.",
                          answer: 3),
            QuestionModel(num: 2,
                          questionText: "띄어쓰기가 바른 것은?",
                          num1Text: "그 사고는 여러 가지 규칙을 도외시 하였기 때문이야.",
                          num2Text: "사실상 여자 대 남자의 대리전으로 밖에는 보이지 않아.",
                          num3Text: "반드시 거기에 가겠다면 내키는 대로 행동해서는 안 돼.",
                          num4Text: "금연을 한 만큼 네 건강이 어느 정도까지 회복될 지 궁금해.",
                          answer: 3),
            QuestionModel(num: 3,
                          questionText: "밑줄 친 조사의 쓰임이 옳지 않은 것은?",
                          num1Text: "건축 면적은 설계도"+"에서".underLined+" 정한 기준에 따라 산정한다.",
                          num2Text: "제안서 및 과업 지시서는 참가 신청자"+"에게".underLined+" 한하여 교부한다.",
                          num3Text: "관계 조서 사본을 관리 사무소"+"에".underLined+" 비치하고 일반인에게 보인다.",
                          num4Text: "제5조 제1항의 규정"+"에도".underLined+" 불구하고 다음 각 목의 평가는 1년 유예를 둔다.",
                          answer: 2),
            QuestionModel(num: 4,
                          questionText: "다음 글에서 경계하고자 하는 태도와 유사한 것은?",
                          reference: "  비판적 사고는 지엽적이고 시시콜콜한 문제를 트집 잡아 물고 늘어지는 것이 아니라 문제의 핵심을 중요한 대상으로 삼는다. 비판적 사고는 제기된 주장에 어떤 오류나 잘못이 있는가를 찾아내기 위해 지엽적인 사항을 확대하여 문제로 삼는 태도나 사고방식과는 거리가 멀다.",
                          num1Text: "격물치지(格物致知)",
                          num2Text: "본말전도(本末顚倒)",
                          num3Text: "유명무실(有名無實)",
                          num4Text: "돈오점수(頓悟漸修)",
                          answer: 2),
            QuestionModel(num: 5,
                          questionText: "다음을 논리적 순서로 배열한 것은?",
                          reference: "  ㄱ. 그 덕분에 인류의 문명은 발달될 수 있었다.\n  ㄴ. 그 대신 사람들은 잠을 빼앗겼고 생물들은 생체 리듬을 잃었다.\n  ㄷ. 인간은 오랜 세월 태양의 움직임에 따라 신체 조건을 맞추어 왔다.\n  ㄹ. 그러나 밤에도 빛을 이용해 보겠다는 욕구가 관솔불, 등잔불, 전등을 만들어 냈고, 이에 따라 밤에 이루어지는 인간의 활동이 점점 많아졌다.",
                          num1Text: "ㄱ － ㄴ － ㄷ － ㄹ",
                          num2Text: "ㄴ － ㄱ － ㄹ － ㄷ",
                          num3Text: "ㄷ － ㄹ － ㄱ － ㄴ",
                          num4Text: "ㄹ － ㄷ － ㄴ － ㄱ",
                          answer: 3),
            QuestionModel(num: 6,
                          questionText: "리더십 부재와 잘못된 정책을 ‘등산’에 빗대어 설명한 것으로 가장 적절한 것은?",
                          num1Text: "사공이 많으면 배가 산으로 간다는 속담처럼 말이 많으면 어느 산을 오를 것인지 결정할 수 없습니다.",
                          num2Text: "등산로를 잘 알지 못하더라도 길잡이가 용기 있는 결단을 내리면 많은 사람들이 등산에 성공할 수 있습니다.",
                          num3Text: "길잡이가 방향을 잘못 가리키고 혼자 가 버리면 많은 사람들이 산 정상에 오를 수 없어 등산의 기쁨을 맛볼 수 없습니다.",
                          num4Text: "등산의 목적은 다른 사람들보다 먼저 봉우리에 올랐다는 기쁨 그 자체이므로 길잡이는 항상 등산하는 사람들이 경쟁할 수 있도록 도와야 합니다.",
                          answer: 3),
            QuestionModel(num: 7,
                          questionText: "다음 글에서 알 수 있는 내용이 아닌 것은?",
                          reference: "  사물놀이는 사물(四物), 즉 꽹과리, 징, 장구, 북의 네 가지 타악기만으로 연주하는 음악을 말한다. 사물놀이는 풍물놀이와는 좀 다르다. 풍물놀이를 무대 공연에 맞게 변형한 것이 사물놀이인데, 풍물놀이가 대체로 자기 지역의 가락만을 연주하는 데 비해 사물놀이는 거의 전 지역의 가락을 모아 재구성해서 연주한다.\n  사물놀이 연주자들은 흔히 쟁쟁거리는 꽹과리를 천둥이나 번개에, 잦게 몰아가는 장구를 비에, 둥실대는 북을 구름에, 여운을 남기며 울리는 징을 바람에 비유한다. 천둥이나 번개, 비, 구름, 바람이 어우러지며 토해 내는 소리가 사물놀이 소리라는 것이다. 사물놀이는 앉아서 연주하는 사물놀이와 서서 연주하는 사물놀이의 두 가지 형태로 나뉘어 있는데, 전자를 ‘앉은반’, 후자를 ‘선반’이라고 한다.",
                          num1Text: "사물놀이의 가치",
                          num2Text: "사물놀이의 소리",
                          num3Text: "사물놀이의 악기 종류",
                          num4Text: "사물놀이의 연주 형태",
                          answer: 1),
            QuestionModel(num: 8,
                          questionText: "다음 글의 내용과 부합하지 않는 것은?",
                          reference: "  글의 기본 단위가 문장이라면 구어를 통한 의사소통의 기본 단위는 발화이다. 담화에서 화자는 발화를 통해 ‘명령’, ‘요청’, ‘질문’, ‘제안’, ‘약속’, ‘경고’, ‘축하’, ‘위로’, ‘협박’, ‘칭찬’, ‘비난’ 등의 의도를 전달한다. 이때 화자의 의도가 직접적으로 표현된 발화를 직접 발화, 암시적으로 혹은 간접적으로 표현된 발화를 간접 발화라고 한다.\n  일상 대화에서도 간접 발화는 많이 사용되는데, 그 의미는 맥락에 의존하여 파악된다. ‘아, 덥다.’라는 발화가 ‘창문을 열어라.’라는 의미로 파악되는 것이 대표적인 예이다. 방 안이 시원하지 않다는 상황을 고려하여 청자는 창문을 열게 되는 것이다. 이처럼 화자는 상대방이 충분히 그 의미를 파악할 수 있다고 판단될 때 간접 발화를 전략적으로 사용함으로써 의사소통을 원활하게 하기도 한다.\n  공손하게 표현하고자 할 때도 간접 발화는 유용하다. 남에게 무언가를 요구하려는 경우 직접 발화보다 청유 형식이나 의문 형식의 간접 발화를 사용하면 공손함이 잘 드러나기도 한다.",
                          num1Text: "발화는 구어를 통한 의사소통의 기본 단위이다.",
                          num2Text: "간접 발화의 의미는 언어 사용 맥락에 기대어 파악된다.",
                          num3Text: "간접 발화가 직접 발화보다 화자의 의도를 더 잘 전달한다.",
                          num4Text: "요청할 때 청유문이나 의문문을 사용하면 더 공손해 보이기도 한다.",
                          answer: 3),
            QuestionModel(num: 9,
                          questionText: "다음 글에 대한 설명으로 적절하지 않은 것은?",
                          reference: "  나는 집이 가난하여 말이 없어서 간혹 남의 말을 빌려 탄다. 노둔하고 여윈 말을 얻게 되면 일이 비록 급하더라도 감히 채찍을 대지 못하고 조심조심 금방 넘어질 듯 여겨서 개울이나 구렁을 지날 때는 말에서 내려 걸어가므로 후회할 일이 적었다. 발굽이 높고 귀가 쫑긋하여 날래고 빠른 말을 얻게 되면 의기양양 마음대로 채찍질하고 고삐를 늦추어 달리니 언덕과 골짜기가 평지처럼 보여 매우 장쾌하지만 말에서 위험하게 떨어지는 근심을 면치 못할 때가 있었다. 아! 사람의 마음이 옮겨지고 바뀌는 것이 이와 같을까? 남의 물건을 빌려서 하루아침의 소용에 쓰는 것도 이와 같은데, 하물며 참으로 자기가 가지고 있는 것이야 어떻겠는가?\n\n-이곡, ‘차마설(借馬說)’-",
                          num1Text: "경험을 통한 통찰력이 돋보인다.",
                          num2Text: "우의적 기법을 적절히 활용하고 있다.",
                          num3Text: "대상들 사이의 유사점을 통해 대상의 특성을 설명하고 있다.",
                          num4Text: "일상사와 관련지어 글쓴이의 주장을 설득력 있게 드러내고 있다.",
                          answer: 3),
            QuestionModel(num: 10,
                          questionText: "다음 글과 같은 방식으로 논리를 전개한 것은?",
                          reference: "  진리가 사상의 체계에 있어 제일의 덕이듯이 정의는 사회적 제도에 있어 제일의 덕이다. 하나의 이론은 그것이 아무리 멋지고 간명한 것이라 하더라도 만약 참되지 않다면 거부되거나 수정되어야 한다. 이와 마찬가지로 법과 제도는 그것이 아무리 효율적으로 잘 정비되어 있다고 하더라도 만약 정의롭지 않다면 개혁되거나 폐기되어야 한다.",
                          num1Text: "의지의 자유가 없는 사람에게는 책임을 물을 수 없다. 그런데 인간에게는 책임을 물을 수 있다. 그러므로 인간의 의지는 자유롭다고 보아야 한다.",
                          num2Text: "여자는 생각하는 것이 남자와 다른 데가 있다. 남자는 미래를 생각하지만 여자는 현재의 상태를 더 소중하게 여긴다. 남자가 모험, 사업, 성 문제를 중심으로 생각한다면 여자는 가정, 사랑, 안정성에 비중을 두어 생각한다.",
                          num3Text: "우리 강아지는 배를 문질러 주면 등을 바닥에 대고 누워 버려. 그리고 정말 기분 좋은 듯한 표정을 짓지. 그런데 내 친구 강아지도 그렇더라고. 아마 모든 강아지가 그런 속성을 가지고 있는 것 같아.",
                          num4Text: "인생은 여행과 같다. 간혹 험난한 길을 만나기도 하고, 예상치 않은 일을 당하기도 한다. 우연히 누군가를 만나고 그들과 관계를 맺기도 한다. 여행을 끝내고 집으로 돌아왔을 때 편안함을 느끼는 것처럼 생을 끝내고 죽음을 맞이할 때 우리는 더없이 편안해질 것이다.",
                          answer: 4),
            QuestionModel(num: 11,
                          questionText: "밑줄 친 부분이 맞춤법에 맞지 않는 것은?",
                          num1Text: "하나에 백 원씩 "+"처주마.".underLined,
                          num2Text: "여름이 되니 몸이 축축 "+"처지네.".underLined,
                          num3Text: "아궁이에서 쓰레기를 "+"처대고".underLined+" 있지.",
                          num4Text: "오는 길에 "+"처박힌".underLined+" 자전거를 보았어.",
                          answer: 1),
            QuestionModel(num: 12,
                          questionText: "밑줄 친 부분 중 보조 용언이 결합되지 않은 것은?",
                          num1Text: "창문 너머로 날이 "+"밝아 온다.".underLined,
                          num2Text: "동생이 내 과자를 "+"먹어 버렸다.".underLined,
                          num3Text: "우체국에 들러 선배의 편지를 "+"부쳐 주었다.".underLined,
                          num4Text: "그는 환갑이 지났지만 40대처럼 "+"젊어 보인다.".underLined,
                          answer: 4),
            QuestionModel(num: 13,
                          questionText: "밑줄 친 부분의 의미 관계가 나머지 셋과 다른 것은?",
                          num1Text: "세 시간이 흐르도록 "+"분분".underLined+"했던 의견들이 마침내 하나로 "+"합치".underLined+" 하였다.",
                          num2Text: "아무리 논리적 "+"사고".underLined+"라 하더라도 거기에는 "+"비판".underLined+"이 따르게 마련이다.",
                          num3Text: "사회적 지위가 높은 사람이 보여주는 "+"겸손".underLined+"은 가끔 "+"오만".underLined+"으로 비칠 수도 있다.",
                          num4Text: "결미".underLined+"에 제시된 결론이 "+"모두".underLined+"에서 진술한 내용과 관련을 맺는다면 좀 더 긴밀한 구성이 될 것이다.",
                          answer: 2),
            QuestionModel(num: 14,
                          questionText: "밑줄 친 사자성어의 쓰임이 적절하지 않은 것은?",
                          num1Text: "그는 결단력이 없어 "+"좌고우면(左顧右眄)".underLined+"하다가 적절한 대응 시기를 놓쳐 버렸다.",
                          num2Text: "다수의 기업이 새로운 투자보다 변화에 대한 "+"암중모색(暗中 摸索)".underLined+"을 시도하고 있다.",
                          num3Text: "그 친구는 "+"침소봉대(針小棒大)".underLined+"하는 경향이 있어서 하는 말을 곧이곧대로 믿기 어렵다.",
                          num4Text: "그 사람이 경제적으로 매우 어려운 상황에서 성공한 것은 "+"연목구어(緣木求魚)".underLined+"나 마찬가지이다.",
                          answer: 4),
            QuestionModel(num: 15,
                          questionText: "㉠～ ㉣에 대한 설명으로 적절하지 않은 것은?",
                          reference: "삼동(三冬)에 ㉠"+"베옷".underLined+" 입고 암혈(巖穴)에 ㉡"+"눈비".underLined+" 맞아\n 구름 낀 볕뉘도 쬔 적이 없건마는\n㉢"+"서산".underLined+"에 해 지다 하니 ㉣"+"눈물겨워".underLined+" 하노라.",
                          num1Text: "㉠ : 화자의 처지나 생활을 추측할 수 있게 한다.",
                          num2Text: "㉡ : 화자와 중심 대상 사이를 연결하는 매개체이다.",
                          num3Text: "㉢ : 화자가 머물고 있는 공간과 구별되는 공간이다.",
                          num4Text: "㉣ : 상황에 대한 화자의 감정이 직접 표출되고 있다.",
                          answer: 2),
            QuestionModel(num: 16,
                          questionText: "(  ) 안에 들어갈 말로 적절한 것은?",
                          reference: "  ‘개살구’, ‘잠’, ‘새파랗다’ 등은 어휘 형태소인 ‘살구’, ‘자－’, ‘파랗－’에 ‘개－’, ‘－ㅁ’, ‘새－’와 같은 접사가 덧붙어서 파생된 단어들이다. 이처럼 직접 구성 요소 중 접사가 확인되는 단어들을 ‘파생어’라고 한다. 반면, (    ) 등은 각각 실질적 의미를 지닌 두 요소가 결합하여 한 단어가 된 경우인데, 이를 ‘파생어’와 구분하여 ‘합성어’라고 한다.",
                          num1Text: "고추장, 놀이터, 손짓, 장군감",
                          num2Text: "면도칼, 서릿발, 쉰둥이, 장난기",
                          num3Text: "깍두기, 선생님, 작은형, 핫바지",
                          num4Text: "김치찌개, 돌다리, 시나브로, 암탉",
                          answer: 1),
            QuestionModel(num: 17,
                          questionText: "다음 글을 읽은 독자의 반응으로 적절한 것은?",
                          reference: "  인문학은 세상에 대한 종합적이고 비판적인 해석과 시각을 제공한다. 인문학이 해석하는 세상은 지금 우리가 살고 있는 세상이다. 현대 사회는 사회의 복잡성이 비교할 수 없을 정도로 증가함에 따라 위험과 불확실성이 커졌으며, 다양한 정보 통신 기술이 정보와 지식의 생산, 유통, 소비를 혁신적으로 바꾸면서 사람들 사이의 새로운 상호 의존 관계를 만들어 낸다는 점에서 과거와는 다른 차별성을 지니고 있다. 이것은 현대 사회가 불확실하고 복잡하며 매일 매일 바쁘게 돌아가는 세상이 되었다는 것, 나아가 지구 구석구석에 존재하는 타인과의 상호 관계가 내 삶에 예기치 못한 영향을 미치는 세상이 되었다는 것을 의미한다. 이러한 세상을 살아가는 데에 인문학은 실질적인 지침을 제공해야 한다.",
                          num1Text: "현대 사회에서 인문학이 담당해야 할 역할에 대해 말하고 있어.",
                          num2Text: "현대 사회의 문제점을 부각시키면서 바람직한 해결 방안을 제시하고 있어.",
                          num3Text: "과거와 현대 사회의 모습을 구체적으로 대조하면서 현대 사회의 특징을 드러내고 있어.",
                          num4Text: "사회의 복잡성으로 인해 타인과의 소통에 장애가 생긴다는 점을 현대 사회의 주요한 특징으로 말하고 있어.",
                          answer: 1),
            QuestionModel(num: 18,
                          questionText: "다음 자료를 활용하여 글을 쓰려고 할 때, 적절하지 않은 것은? (단위 : %, 중복 응답)",
                          imgModel: ImageModel(imageString: "201511-18", imgWidth: 330, imgHeight: 240),
                          num1Text: "인터넷을 이용하면 필요한 정보를 다양하게 얻을 수 있음을 서술한다.",
                          num2Text: "자신의 권리가 침해되지 않도록 보안 강화 방안을 적극적으로 제안한다.",
                          num3Text: "타인의 권리를 침해하지 않도록 인터넷 윤리 교육의 필요성을 강조한다.",
                          num4Text: "인터넷이 잘못된 여론을 형성할 수 있으므로 인터넷 사용을 금지할 것을 주장한다.",
                          answer: 4),
            QuestionModel(num: 19,
                          questionText: "<보기>를 참고하여 ㉠∼ ㉣을 이해한 내용으로 적절하지 않은 것은?",
                          reference: "<보기>\n\n  이용악은 1945년 해방이 되자 고향인 함경북도 경성에 가족을 두고 홀로 상경한다. ‘그리움’은 몹시 추웠던 그해 겨울밤 고향에 두고 온 가족을 그리워하며 쓴 시이다.",
                          reference2: "눈이 오는가 ㉠"+"북쪽".underLined+"엔\n함박눈 쏟아져 내리는가.\n\n험한 벼랑을 굽이굽이 돌아간\n백무선 철길 위에\n느릿느릿 밤새워 달리는\n화물차의 검은 지붕에\n\n연달린 산과 산 사이\n㉡"+"너".underLined+"를 남기고 온\n작은 마을에도 복된 눈 내리는가.\n\n잉크병 얼어드는 ㉢"+"이러한 밤".underLined+"에\n 어쩌자고 ㉣"+"잠".underLined+"을 깨어\n그리운 곳 차마 그리운 곳.\n\n눈이 오는가 북쪽엔\n함박눈 쏟아져 내리는가.\n\n-이용악, ‘그리움’-",
                          num1Text: "㉠은 자신이 떠나온 공간인 고향을 가리키는 것이겠군.",
                          num2Text: "㉡은 고향에 남겨 두고 온 가족을 의미하는 표현이겠군.",
                          num3Text: "㉢은 극심한 추위 속에서도 가족을 떠올리는 시간이겠군.",
                          num4Text: "㉣은 그리운 이를 볼 수 없는 화자의 절망적 심정을 투영한 대상물이겠군.",
                          answer: 4),
            QuestionModel(num: 20,
                          questionText: "다음 글에 나타난 ‘그림 : 액자’의 관계와 가장 비슷한 것은",
                          reference: "  2000년이 된 기념으로 ○○화랑에서 화가 200인의 작품 전시회를 개최하였다. 큐레이터가 보내 준 카탈로그를 보고 전화로 김○○ 화백의 그림을 바로 예약했다. 큐레이터는 “작품이 작은데 병 속에 세 명이 들어가 있어 답답한 느낌이 들지 않느냐?”라고 했지만, 나는 내가 설정한 ‘가족’ 이라는 주제에 어울린다고 생각하여 구입하기로 하였다.\n  전시회가 끝난 뒤 작품을 받아 보니 액자가 그림보다 훨씬 컸다. 이렇게 액자가 크니, 큐레이터의 걱정과는 달리 그림이 답답해 보이지는 않았다. 이것이 바로 ‘액자의 힘’이다. 내가 아는 어떤 애호가는 좋은 액자를 꾸준히 모은다. 갖고 있는 그림의 액자를 바꾸기 위해.",
                          num1Text: "유명 인사들의 사회적 성공은 어디에서 비롯되었을까. 그들은 그 요인으로 하나같이 좋은 습관을 든다. － ‘성공 : 습관’",
                          num2Text: "나는 가끔 책을 장난감 블록처럼 다양하게 쌓아 본다. 책의 무거움, 진부함, 지루함을 해소하고, 즐겁고 유쾌하게 책을 재발견하고자 하는 것이다. － ‘책 : 장난감 블록’",
                          num3Text: "로댕은 돌을 바라봅니다. 그 안에서 손을 발견합니다. 그리고 자신의 손을 움직여 돌 속의 손을 끄집어내려고 합니다. 그러다 실패하지요. 실패했다고 포기하지 않고 로댕은 다시 새 돌을 꺼내 바라봅니다. － ‘돌 : 손’",
                          num4Text: "인간은 단 몇 초 만에 상대방에 대한 호감도를 결정한다고 한다. 몇 초 만에 자신의 내면을 드러내기가 쉽지 않다는 것을 고려하면, 내면을 돋보이게 할 수 있는 옷차림은 분명 무시할 수 없는 요인이다. － ‘내면 : 옷차림’",
                          answer: 4)
        ]
        
        let exam = ExamModel(id: 201511, year: 2015, examTypeID: "국가직", subjectID: "국어", questions: questions)
        exam2015.append(exam)
    }
    func saveExam201512() {
        let questions =
        [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분에 가장 적절한 것을 고르시오. [1～2]",
                      reference: "The young knight was so ________ at being called a coward that he charged forward with his sword in hand.",
                      num1Text: "aloof",
                      num2Text: "incensed",
                      num3Text: "unbiased",
                      num4Text: "unpretentious",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "",
                      reference: "Back in the mid-1970s, an American computer scientist called John Holland _________ the idea of using the theory of evolution to solve notoriously difficult problems in science.",
                      num1Text: "took on",
                      num2Text: "got on",
                      num3Text: "put upon",
                      num4Text: "hit upon",
                      answer: 4),
        QuestionModel(num: 3,
                      questionText: "내용의 흐름상 적절하지 못한 문장은?",
                      reference: "Of equal importance in wars of conquest were the germs that evolved in human societies with domestic animals. ①"+"Infectious diseases like smallpox, measles, and flu arose as specialized germs of humans, derived by mutations of very similar ancestral germs that had infected animals.".underLined+" ②"+"The most direct contribution of plant and animal domestication to wars of conquest was from Eurasia's horses, whose military role made them the jeeps and Sherman tanks of ancient warfare on that continent.".underLined+" ③"+"The humans who domesticated animals were the first to fall victim to the newly evolved germs, but those humans then evolved substantial resistance to the new disease.".underLined+" ④"+"When such partly immune people came into contact with others who had had no previous exposure to the germs, epidemics resulted in which up to 99 percent of the previously unexposed population was killed.".underLined+" Germs thus acquired ultimately from domestic animals played decisive roles in the European conquests of Native Americans, Australians, South Africans, and Pacific islanders.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 2),
        QuestionModel(num: 4,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "Everyone knows what the Mona Lisa and Michelangelo's David look like-or do we? They are reproduced so often that we may feel we know them even if we have never been to Paris or Florence. Each has countless spoofs -David in boxer shorts or the Mona Lisa with a mustache. Art reproductions are ubiquitous. We can now sit in our pajamas while enjoying virtual tours of galleries and museums around the world via the Web and CD-ROM. We can explore genres and painters and zoom in to scrutinize details. The Louvre's Website offers spectacular 360-degree panoramas of artworks like the Venus de Milo. Such tours may become ever more multi-sensory by drawing on virtual reality technology, which includes things like goggles and gloves. Lighting and stage set designers, like architects, already use this technology in their work.",
                      num1Text: "Should We Ban Art Reproductions?",
                      num2Text: "Why Are Virtual Artworks So Popular?",
                      num3Text: "Art : More Widely Accessible Than Ever!",
                      num4Text: "Secrets of Vanished Galleries and Museums",
                      answer: 3),
        QuestionModel(num: 5,
                      questionText: "어법상 옳지 않은 것은?",
                      num1Text: "The main reason I stopped smoking was that all my friends had already stopped smoking.",
                      num2Text: "That a husband understands a wife does not mean they are necessarily compatible.",
                      num3Text: "The package, having wrong addressed, reached him late and damaged.",
                      num4Text: "She wants her husband to buy two dozen of eggs on his way home.",
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "어법상 옳은 것은?",
                      num1Text: "China's imports of Russian oil skyrocketed by 36 percent in 2014.",
                      num2Text: "Sleeping has long been tied to improve memory among humans.",
                      num3Text: "Last night, she nearly escaped from running over by a car.",
                      num4Text: "The failure is reminiscent of the problems surrounded the causes of the fatal space shuttle disasters.",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "밑줄 친 부분에 가장 적절한 것을 고르시오. [7～8]",
                      reference: "  A:What business is on your mind?\n  B:Do you think that owning a flower shop has good prospects nowadays?\n  A:It could. But have you prepared yourself mentally and financially?\n  B : ______________________________.\n  A:Good! Then you should choose a strategic place and the right segment too. You must do a thorough research to have a good result.\n  B : I know that. It’s much easier to start a business than to run it well.",
                      num1Text: "I plan to go to the hospital tomorrow",
                      num2Text: "I can't be like that! I must strive to get a job",
                      num3Text: "I'm ready to start with what I have and take a chance",
                      num4Text: "I don't want to think about starting my own business",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "",
                      reference: "  M: What's that noise?\n  W: Noise? I don't hear anything.\n  M:Listen closely. I hear some noise. _________________.\n  W: Oh, let's stop and see.\n  M:Look! A piece of glass is in the right front wheel.\n  W:Really? Umm... You're right. What are we going to do?\n  M:Don't worry. I got some experience in changing tires.",
                      num1Text: "I gave my customers sound advice",
                      num2Text: "Maybe air is escaping from the tire",
                      num3Text: "I think the mechanic has an appointment",
                      num4Text: "Oh! Your phone is ringing in vibration mode",
                      answer: 2),
        QuestionModel(num: 9,
                      questionText: "다음 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "We can in consequence establish relations with almost all sorts of them.",
                      reference2: "Reptiles and fish may no doubt be found in swarms and shoals; they have been hatched in quantities and similar conditions have kept them together. In the case of social and gregarious mammals, the association arises not simply from a community of external forces but is sustained by an inner impulse. They are not merely like one another and so found in the same places at the same times; they like one another and so they keep together. This difference between the reptile world and the world of our human minds is one our sympathies seem unable to pass. (  A  ) We cannot conceive in ourselves the swift uncomplicated urgency of a reptile's instinctive motives, its appetites, fears and hates. (  B  ) We cannot understand them in their simplicity because all our motives are complicated; ours are balances and resultants and not simply urgencies. (  C  ) But the mammals and birds have self-restraint and consideration for other individuals, a social appeal, a self-control that is, at its lower level, after our own fashion. (  D  ) When they suffer they utter cries and make movements that rouse our feelings. We can make pets of them with a mutual recognition. They can be tamed to self-restraint towards us, domesticated and taught.",
                      num1Text: "A",
                      num2Text: "B",
                      num3Text: "C",
                      num4Text: "D",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "Thunderstorms are extremely common in many parts of the world, for example, throughout most of North America. Updrafts of warm air set off these storms.",
                      reference2: "(A) This more buoyant air then rises and carries water vapor to higher altitudes. The air cools as it rises, and the water vapor condenses and starts to drop as rain. As the rain falls, it pulls air along with it and turns part of the draft downward.\n\n(B) An updraft may start over ground that is more intensely heated by the sun than the land surrounding the area. Bare, rocky, or paved areas, for example, usually have updrafts above them. The air in contact with the ground heats up and thus becomes lighter, more buoyant, than the air surrounding it.\n\n(C) The draft may turn upward again and send the rain churning around in the cloud. Some of it may freeze to hail. Sooner or later, the water droplets grow heavy enough to resist the updrafts and fall to the ground, pulling air in the form of downdrafts with them.",
                      num1Text: "(A)-(C)-(B)",
                      num2Text: "(B)-(A)-(C)",
                      num3Text: "(B)-(C)-(A)",
                      num4Text: "(C)-(A)-(B)",
                      answer: 2),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 부분과 의미가 가장 가까운 것을 고르시오. [11～12]",
                      reference: "He took out a picture from his drawer and kissed it with deep reverence, folded it "+"meticulously".underLined+" in a white silk kerchief, and placed it inside his shirt next to his heart.",
                      num1Text: "carefully",
                      num2Text: "hurriedly",
                      num3Text: "decisively",
                      num4Text: "delightfully",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "",
                      reference: " The company cannot expect me to move my home and family "+"at the drop of a hat.".underLined,
                      num1Text: "immediately",
                      num2Text: "punctually",
                      num3Text: "hesitantly",
                      num4Text: "periodically",
                      answer: 1),
        QuestionModel(num: 13,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "America gets 97 % of its limes from Mexico, and a combination of bad weather and disease has sent that supply plummeting and prices skyrocketing. A 40-lb. (18 kg) box of limes that cost the local restaurateurs about $20 late last year now goes for $ 120. In April, the average retail price for a lime hit 56 cents, more than double the price last year. Across the U.S., bars and restaurants are rationing their supply or, like Alaska Airlines, eliminating limes altogether. In Mexico, the value spike is attracting criminals, forcing growers to guard their limited supply of “green gold” from drug cartels. Business owners who depend on citrus are hoping that spring growth will soon bring costs back to normal.",
                      num1Text: "An Irreversible Change in Wholesale Price of Lime",
                      num2Text: "Mexican Lime Cartel Spreading to the U.S.",
                      num3Text: "Americans Eat More Limes than Ever",
                      num4Text: "A Costly Lime Shortage",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "다음 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "Print, however, with its standard format and type, introduced exact mass reproduction.",
                      reference2: "Print transformed how knowledge itself was understood and transmitted. A manuscript is a unique and unreproducible object. (  A  ) This meant that two readers separated by distance could discuss and compare identical books, right down to a specific word on a particular page. (  B  ) With the introduction of consistent pagination, indexes, alphabetic ordering, and bibliographies (all unthinkable in manuscript), knowledge itself was slowly repackaged. (  C  ) Textual scholarship became a cumulative science, as scholars could now gather manuscripts of, say, Aristotle's Politics and print a standard authoritative edition based on a comparison of all available copies. (  D  ) This also led to the phenomenon of new and revised editions.",
                      num1Text: "A",
                      num2Text: "B",
                      num3Text: "C",
                      num4Text: "D",
                      answer: 1),
        QuestionModel(num: 15,
                      questionText: "다음 글의 내용과 일치하는 것은?",
                      reference: "The WAIS-R is made up of eleven subtests, or scales. The subtests of the WAIS-R are arranged by the type of ability or skill being tested. The subtests are organized into two categories. Six subtests define the verbal scale, and five subtests constitute a performance scale. We can compute three scores: a verbal score, a performance score, and a total (or full-scale) score. The total score can be taken as an approximation of general intellectual ability. To administer the WAIS-R, you present each of the eleven subtests to your subject. The items within each subtest are arranged in order of difficulty. You start with relatively easy items, and then you progress to more difficult ones. You stop administering any one subtest when your subject fails a specified number of items in a row. You alternate between verbal and performance subtests. The whole process takes up to an hour and a half.",
                      num1Text: "The WAIS-R has eleven subtests, each of which has two main parts.",
                      num2Text: "Several subtests with higher scores among the eleven ones should be presented.",
                      num3Text: "The items of each subtest in the WAIS-R begin from easy and continue on to more difficult ones.",
                      num4Text: "Subjects take all of the verbal subtests first and then all of the performance subtests.",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "밑줄 친 부분에 가장 적절한 것은?",
                      reference: "Language is saturated with implicit metaphors like “Events are objects and time is space.” Indeed, space turns out to be a conceptual vehicle not just for time but for many kinds of states and circumstances. Just as a meeting can be moved from 3:00 to 4:00, a traffic light can go from green to red, a person can go from flipping burgers to running a corporation, and the economy can go from bad to worse. Metaphor is so widespread in language that it's hard to find expressions for abstract ideas that are not metaphorical. Does it imply that even our wispiest concepts are represented in the mind as hunks of matter that we move around on a mental stage? Does it say that rival claims about the world can never be true or false but can only be _____________________? Few things in life cannot be characterized in terms of variables and the causation of changes in them.",
                      num1Text: "proven to be always true in all circumstances",
                      num2Text: "irreversible and established truths that cannot be disputed",
                      num3Text: "subject to scientific testings for their authenticity and clarity",
                      num4Text: "alternative metaphors that frame a situation in different ways",
                      answer: 4),
        QuestionModel(num: 17,
                      questionText: "우리말을 영어로 잘못 옮긴 것을 고르시오. [17～18]",
                      num1Text: "가능한 모든 일자리를 알아보았음에도 불구하고, 그는 적당한 일자리를 찾지 못했다.\n→ Despite searching for every job opening possible, he could not find a suitable job.",
                      num2Text: "당신이 누군가를 믿을 수 있는지 알아보는 최선책은 그 사람을 믿는 것이다.\n→ The best way to find out if you can trust somebody is to trust that person.",
                      num3Text: "미각의 민감성은 개인의 음식 섭취와 체중에 크게 영향을 미친다.\n→ Taste sensitivity is largely influenced by food intake and body weight of individuals.",
                      num4Text: "부모는 그들의 자녀가 성장하고 학습하는 데 알맞은 환경을 제공할 책임이 있다.\n→ Parents are responsible for providing the right environment for their children to grow and learn in.",
                      answer: 3),
        QuestionModel(num: 18,
                      questionText: "",
                      num1Text: "그는 자신의 정적들을 투옥시켰다.\n→ He had his political enemies imprisoned.",
                      num2Text: "경제적 자유가 없다면 진정한 자유가 있을 수 없다.\n→ There can be no true liberty unless there is economic liberty.",
                      num3Text: "나는 가능하면 빨리 당신과 거래할 수 있기를 바란다.\n→ I look forward to doing business with you as soon as possible.",
                      num4Text: "30년 전 고향을 떠날 때, 그는 다시는 고향을 못 볼 거라고 꿈에도 생각지 않았다.\n→ When he left his hometown thirty years ago, little does he dream that he could never see it again.",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "다음 글의 ㉠, ㉡에 들어갈 가장 적절한 것은?",
                      reference: "The chimpanzee － who puts two sticks together in order to get at a banana because no one of the two is long enough to do the job － uses intelligence. So do we all when we go about our business, “figuring out” how to do things. Intelligence, in this sense, is taking things for granted as they are, making combinations which have the purpose of facilitating their manipulation; intelligence is thought in the service of biological survival. Reason,  ㉠  , aims at understanding; it tries to find out what is beneath the surface, to recognize the kernel, the essence of the reality which surrounds us. Reason is not without a function, but its function is not to further physical as much as mental and spiritual existence.  ㉡  , often in individual and social life, reason is required in order to predict (considering that prediction often depends on recognition of forces which operate underneath the surface), and prediction sometimes is necessary even for physical survival.",
                      num1Text: "for example - Therefore",
                      num2Text: "in the same way - Likewise",
                      num3Text: "consequently - As a result",
                      num4Text: "on the other hand - However",
                      answer: 4),
        QuestionModel(num: 20,
                      questionText: "다음 글의 내용과 일치하지 않는 것은?",
                      reference: "East of the Mississippi, the land rises slowly into the foothills of the Appalachian Mountains. At the edge of the Canadian plains, the Canadian Shield, a giant core of rock centered on the Hudson and James Bays, anchors the continent. The stony land of the Shield makes up the eastern half of Canada and the northeastern United States. In northern Quebec, the Canadian Shield descends to the Hudson Bay. The heavily eroded Appalachian Mountains are North America's oldest mountains and the continent's second-longest mountain range. They extend about 1,500 miles from Quebec to central Alabama. Coastal lowlands lie east and south of the Appalachians. Between the mountains and the coastal lowlands lies a wide area of rolling hills. Many rivers cut through the Piedmont and flow across to the Atlantic Coastal Plain in the Carolinas.",
                      num1Text: "Centered on the Hudson and James Bays is a giant core of rock, the Canadian Shield.",
                      num2Text: "The Appalachian Mountains are North America's longest mountain range.",
                      num3Text: "From Quebec to central Alabama, the Appalachian Mountains stretch.",
                      num4Text: "The Piedmont is traversed by many rivers that flow toward the Plain.",
                      answer: 2)
        ]
        
        let exam = ExamModel(id: 201512, year: 2015, examTypeID: "국가직", subjectID: "영어", questions: questions)
        
        exam2015.append(exam)
    }
    func saveExam201513() {
        let questions =
        [
        QuestionModel(num: 1,
                      questionText: "고려 사회의 모습으로 옳지 않은 것은?",
                      num1Text: "천민 출신인 이의민이 무신 정권의 최고 권력자가 되었다.",
                      num2Text: "외거 노비가 재산을 늘려, 그 처지가 양인과 유사해질 수 있었다.",
                      num3Text: "지방 향리의 자제가 과거(科擧)를 통해 귀족의 대열에 진입할 수 있었다.",
                      num4Text: "향․부곡․소의 백성도 일반 군현민과 동일한 수준의 조세․ 공납․역을 부담하였다.",
                      answer: 4),
        QuestionModel(num: 2,
                      questionText: "조선 전기(15 ～ 16세기) 사림의 향촌을 주도하기 위한 동향으로 옳지 않은 것은?",
                      num1Text: "도덕과 의례의 기본 서적인 〖소학〗을 보급하였다.",
                      num2Text: "향사례(鄕射禮), 향음주례(鄕飮酒禮)의 실시를 주장하였다.",
                      num3Text: "향회를 통해서 자신들의 결속을 다지고, 향촌을 교화하였다",
                      num4Text: "촌락 단위의 동약을 실시하고, 문중 중심으로 서원과 사우를 많이 세웠다.",
                      answer: 4),
        QuestionModel(num: 3,
                      questionText: "과전법과 그 변화에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "수신전, 휼양전을 죽은 관료의 가족에게 지급하였다.",
                      num2Text: "공음전을 5품 이상의 관료에게 주어 세습을 허용하였다.",
                      num3Text: "세조대에 직전법으로 바꾸어 현직 관리에게만 수조권을 지급 하였다.",
                      num4Text: "성종대에는 관수관급제를 실시하여 전주의 직접 수조를 지양 하였다.",
                      answer: 2),
        QuestionModel(num: 4,
                      questionText: "다음은 동학농민운동과 관련한 연표이다. (가) ～(라) 시기에 있었던 사실로 옳은 것은?",
                      imgModel: ImageModel(imageString: "201513-4", imgWidth: 330, imgHeight: 170),
                      num1Text: "(가) － 황토현 전투",
                      num2Text: "(나) － 청․일 전쟁의 발발",
                      num3Text: "(다) － 남․북접군의 논산 집결",
                      num4Text: "(라) － 일본군의 경복궁 점령",
                      answer: 4),
        QuestionModel(num: 5,
                      questionText: "다음 자료에 대한 해석으로 가장 적절한 것은?",
                      reference: "○ 신라 지증왕 3년의 순장 금지 사료(史料)\n\n○ 신라 무덤에서 출토한 순장 대용(代用) 흙인형",
                      num1Text: "전쟁 노비의 소멸로 순장할 대상이 없어졌다.",
                      num2Text: "농업생산력의 상승에 따라 노동력을 중시하였다.",
                      num3Text: "죽음에 대한 의식(儀式)에 도교 사상이 반영되었다.",
                      num4Text: "왕실은 귀족층의 사치와 허례허식을 막기 위해 노력하였다.",
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 ‘이 시대’의 사회 모습으로 옳은 것은?",
                      reference: "이 시대".underLined+"의 황해도 봉산 지탑리와 평양 남경 유적에서 탄화된 좁쌀이 발견되는 것으로 보아 잡곡류 경작이 이루어 졌음을 알 수 있다. 농경의 발달로 수렵과 어로가 경제 생활에서 차지하는 비중이 줄어들기 시작하였지만, 여전히 식량을 얻는 중요한 수단이었다. 한편 가락바퀴나 뼈바늘을 이용하여 옷이나 그물을 만드는 등 원시적인 수공업 생산이 이루어지기 시작하였다.",
                      num1Text: "생산물의 분배 과정에서 사유 재산 제도가 등장하였다.",
                      num2Text: "마을 주변에 방어 및 의례 목적으로 환호(도랑)를 두르기도 하였다.",
                      num3Text: "흑요석의 출토 사례로 보아 원거리 교류나 교역이 있었음을 알 수 있다.",
                      num4Text: "집자리는 주거용 외에 창고, 작업장, 집회소, 공공 의식 장소 등도 확인되었다.",
                      answer: 2),
        QuestionModel(num: 7,
                      questionText: "조선 전기(15∼16세기) 중앙 정치에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "붕당은 정치적 이념과 학문적 경향에 따라 결집되었다.",
                      num2Text: "삼사는 권력의 독점과 부정을 방지하는 데 기여하였다.",
                      num3Text: "사화로 갈등이 격화되면서, 정국이 급격하게 전환되는 환국정치가 시작되었다.",
                      num4Text: "합리적인 인사 행정 제도가 갖추어져 이전 시기보다 관료제적 성격이 강해졌다.",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "다음 건의를 받아들인 왕이 실시한 정책으로 옳은 것은",
                      reference: "임금이 백성을 다스릴 때 집집마다 가서 날마다 그들을 살펴보는 것이 아닙니다. 그래서 수령을 나누어 파견하여, (현지에) 가서 백성의 이해(利害)를 살피게 하는 것입니다. 우리 태조께서도 통일한 뒤에 외관(外官)을 두고자 하셨으나, 대개 (건국) 초창기였기 때문에 일이 번잡하여 미처 그럴 겨를이 없었습니다. 이제 제가 살펴보건대, 지방 토호들이 늘 공무를 빙자하여 백성들을 침해하며 포악하게 굴어, 백성들이 명령을 견뎌내지 못합니다. 외관을 두시기 바랍니다.",
                      num1Text: "서경 천도를 추진하였다.",
                      num2Text: "5도 양계의 지방 제도를 확립하였다.",
                      num3Text: "지방 교육을 위해 경학박사를 파견하였다.",
                      num4Text: "유교 이념과는 별도로 연등회, 팔관회 행사를 장려하였다.",
                      answer: 3),
        QuestionModel(num: 9,
                      questionText: "신라 승려 ㉠과 ㉡에 대한 설명으로 옳지 않은 것은?",
                      reference: "(  ㉠  )은(는) 불교 서적을 폭넓게 이해하고, 일심(一心) 사상을 바탕으로 여러 종파들의 사상적 대립을 조화시키며, 분파 의식을 극복하려고 노력하였다. 한편 (  ㉡  )은(는) 모든 존재가 상호 의존적인 관계에 있으면서 서로 조화를 이룬다는 화엄 사상을 정립하고, 교단을 형성하여 많은 제자를 양성하였다.",
                      num1Text: "㉠은 미륵 신앙을 전파하며 불교 대중화의 길을 열었다.",
                      num2Text: "㉠은 무애가라는 노래를 유포하며 일반 백성을 교화하였다.",
                      num3Text: "㉡은 관음 신앙과 함께 아미타 신앙을 화엄 교단의 주요 신앙으로 삼았다.",
                      num4Text: "㉡은 국왕이 큰 공사를 일으켜 도성을 새로이 정비하려 할 때 백성을 위해 이를 만류하였다.",
                      answer: 1),
        QuestionModel(num: 10,
                      questionText: "밑줄 친 ㉠, ㉡에 대한 설명으로 옳은 것은?",
                      reference: "일제의 가혹한 탄압으로 독립 운동은 큰 제약을 받게 되었다. 그러나 그러한 제약 속에서도 비밀 결사의 형태로 독립 운동 단체가 결성되었다. ㉠"+"독립의군부".underLined+"와 ㉡"+"대한광복회".underLined+"는 모두 이러한 비밀 결사 단체였다.",
                      num1Text: "㉠은 공화국의 건설을 목표로 하였다.",
                      num2Text: "㉡은 고종의 비밀 지령을 받아 조직되었다.",
                      num3Text: "㉠과 ㉡은 모두 1910년대 국내에서 결성된 단체이다.",
                      num4Text: "㉠은 박상진을 중심으로, ㉡은 임병찬을 중심으로 한 조직 이었다.",
                      answer: 3),
        QuestionModel(num: 11,
                      questionText: "통일신라의 지방 행정 조직에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "신문왕 대에 9주 5소경 체제로 정비하였다.",
                      num2Text: "주(州)에는 지방 감찰관으로 보이는 외사정이 배치되었다.",
                      num3Text: "5소경을 전략적 요충지에 두고, 도독이 행정을 관할토록 하였다.",
                      num4Text: "촌주가 관할하는 촌 이외에, 향․부곡이라는 행정 구역도 있었다.",
                      answer: 3),
        QuestionModel(num: 12,
                      questionText: "고려의 농민을 위한 정책으로 옳지 않은 것은?",
                      num1Text: "농민 자제의 과거를 위한 기금으로 광학보를 설치하였다.",
                      num2Text: "개간지는 일정 기간 면세하여 줌으로써 농민의 부담을 경감해 주었다.",
                      num3Text: "재해를 당했을 때에는 세금을 감면해 농민 생활의 안정을 꾀하였다.",
                      num4Text: "농번기에는 잡역 동원을 금지하여 농사에 지장을 주지 않으려 하였다.",
                      answer: 1),
        QuestionModel(num: 13,
                      questionText: "다음의 자료에 보이는 시기의 경제 동향에 대한 설명으로 옳지 않은 것은?",
                      reference: "배에 물건을 싣고 오가면서 장사하는 장사꾼은 반드시 강과 바다가 이어지는 곳에서 이득을 얻는다. 전라도 나주의 영산포, 영광의 법성포, 흥덕의 사진포, 전주의 사탄은 비록 작은 강이나 모두 바닷물이 통하므로 장삿배가 모인다. … (중략) … 그리하여 큰 배와 작은 배가 밤낮으로 포구에 줄을 서고 있다.\n\n － 〖비변사등록〗 -",
                      num1Text: "강경, 원산 등이 상업 중심지로 성장하였다.",
                      num2Text: "선상은 선박을 이용해서 각 지방의 물품을 거래하였다.",
                      num3Text: "객주나 여각은 상품의 매매를 중개하고, 숙박, 금융 등의 영업도 하였다.",
                      num4Text: "상업 활동이 활발해지면서 삼한통보 등의 동전을 만들어 유통 하였다.",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "다음 중 ‘대한국 국제’의 내용에 해당되는 것은?",
                      num1Text: "내시부를 없애고 그 중에 우수한 인재를 등용한다.",
                      num2Text: "조세의 부과와 징수, 경비의 지출은 모두 탁지아문이 관할한다.",
                      num3Text: "칙임관은 황제가 정부에 자문하여 그 과반수의 의견에 따라 임명한다.",
                      num4Text: "대한국 대황제는 각 조약 체결 국가에 사신을 파견하고, 선전 강화(宣戰講和) 및 제반 조약을 체결한다.",
                      answer: 4),
        QuestionModel(num: 15,
                      questionText: "연표의 (가), (나) 시기에 있었던 사실로 옳은 것은?",
                      imgModel: ImageModel(imageString: "201513-15", imgWidth: 330, imgHeight: 160),
                      num1Text: "(가) － 인천상륙작전이 실시되었다.",
                      num2Text: "(가) － 중국군의 참전으로 인해 한국군은 서울에서 후퇴하게 되었다.",
                      num3Text: "(나) － 애치슨 선언이 발표되었다.",
                      num4Text: "(나) － 유엔 안전보장이사회에서 유엔군 파병이 결정되었다.",
                      answer: 1),
        QuestionModel(num: 16,
                      questionText: "다음 두 사건이 일어난 이후의 사실로 옳은 것만을 <보기>에서 모두 고른 것은?",
                      reference: "○ 고종 황제의 강제 퇴위\n○ 일제에 의한 군대 해산",
                      reference2: "<보기>\n\n  ㄱ. 안중근이 만주 하얼빈에서 이토 히로부미를 사살하였다.\n  ㄴ. 민영환이 일제에 대한 저항을 강력하게 표현한 유서를 남기고 자결하였다.\n  ㄷ. 장지연이 민족의식을 고취하는 ‘시일야방성대곡’을 황성신문에 발표하였다.\n  ㄹ. 이인영을 총대장으로 하는 13도 연합 의병 부대(창의군)가 서울진공작전을 시도하였다.",
                      num1Text: "ㄱ, ㄴ",
                      num2Text: "ㄱ, ㄹ",
                      num3Text: "ᄂ, ᄃ",
                      num4Text: "ᄃ,ᄅ",
                      answer: 2),
        QuestionModel(num: 17,
                      questionText: "우리나라 농서에 대한 설명으로 옳은 것은?",
                      num1Text: "〖농가집성〗은 고려 말 이암이 원에서 들여온 것이다.",
                      num2Text: "〖농사직설〗은 정초 등이 왕명을 받아 편찬한 것이다.",
                      num3Text: "〖산림경제〗는 박세당이 과수, 축산 등을 소개한 것이다.",
                      num4Text: "〖과농소초〗는 홍만선이 화초재배법에 대해 저술한 것이다.",
                      answer: 2),
        QuestionModel(num: 18,
                      questionText: "다음의 기록이 보이는 왕대의 정치 변화를 바르게 설명한 것은?",
                      reference: "(왕이) 양역을 절반으로 줄이라고 명하셨다. 왕이 말하였다. “호포나 결포는 모두 문제점이 있다. 이제는 1필로 줄이는 것으로 온전히 돌아갈 것이니 경들은 대책을 강구하라.”",
                      num1Text: "특정 붕당이 정권을 독점하는 일당 전제화의 추세가 대두되었다.",
                      num2Text: "왕위 계승에 대한 정통성과 관련하여 두 차례의 예송이 발생 하였다.",
                      num3Text: "정치 집단은 소수의 가문 출신으로 좁아지면서 그 기반이 축소 되었다.",
                      num4Text: "붕당을 없애자는 논리에 동의하는 관료들을 중심으로 탕평 정국을 운영하였다.",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "밑줄 친 ‘우리’에 해당하는 계층의 활동으로 옳은 것은?",
                      reference: "아! "+"우리".underLined+"는 본시 모두 사대부였는데 혹은 의(醫)에 들어가고 혹은 역(譯)에 들어가 7, 8대 또는 10여 대를 대대로 전하니 … (중략) … 문장과 덕(德)은 비록 사대부에 비길 수 없으나, 명공(名公) 거실(巨室) 외에 "+"우리".underLined+"보다 나은 자는 없다.",
                      num1Text: "집단으로 상소하여 청요직(淸要職) 허통(許通)을 요구하였다.",
                      num2Text: "형평사를 창립하고, 평등한 대우를 요구하는 형평운동을 펼쳤다.",
                      num3Text: "관권과 결탁하고 향회를 장악하여, 향촌 사회에서 영향력을 키우려 하였다.",
                      num4Text: "유향소를 복립하여 향리를 감찰하고 향촌 사회의 풍속을 바로 잡으려 하였다.",
                      answer: 1),
        QuestionModel(num: 20,
                      questionText: "(가) ～ (라)는 광복을 전후해 일어난 사건을 시기순으로 나열한 것이다. (다)에 들어갈 수 있는 내용으로 적절하지 않은 것은?",
                      reference: "  (가) 삼균주의를 바탕으로 대한민국 임시 정부가 ‘대한민국 건국 강령’을 발표하였다.\n  (나) 이승만을 중심으로 독립촉성중앙협의회가 발족되었다.\n  (다)\n  (라) 제헌 국회에서 대한민국의 헌법이 제정, 공포되었다.",
                      num1Text: "좌우합작위원회의 ‘좌우합작 7원칙’이 선포되었다.",
                      num2Text: "김구의 ‘삼천만 동포에게 읍고함’이라는 글이 발표되었다.",
                      num3Text: "여운형, 안재홍 등을 중심으로 조선건국준비위원회가 조직되었다.",
                      num4Text: "유엔 총회에서 유엔 감시 하에 인구 비례에 의한 남북한 총선거의 실시가 결의되었다.",
                      answer: 3)
        ]
        
        let exam = ExamModel(id: 201513, year: 2015, examTypeID: "국가직", subjectID: "한국사", questions: questions)
        
        exam2015.append(exam)
    }
    
    func saveExam201521() {
        let questions =
        [
        QuestionModel(num: 1,
                      questionText: "나머지 셋과 의미가 다른 사자성어는?",
                      num1Text: "갑남을녀(甲男乙女)",
                      num2Text: "초동급부(樵童汲婦)",
                      num3Text: "장삼이사(張三李四)",
                      num4Text: "부창부수(夫唱婦隨)",
                      answer: 4),
        QuestionModel(num: 2,
                      questionText: "다음 내용에 부합하는 사자성어는?",
                      reference: "  다양한 의견을 지닌 사회의 주체들이 서로 어우러지면서도 개개인의 의견을 굽혀 야합하지 않는 열린 토론의 장을 만들자.",
                      num1Text: "동기상구(同氣相求)",
                      num2Text: "화이부동(和而不同)",
                      num3Text: "동성이속(同聲異俗)",
                      num4Text: "오월동주(吳越同舟)",
                      answer: 2),
        QuestionModel(num: 3,
                      questionText: "㉠～ ㉢에 들어갈 단어로 가장 적절한 것은?",
                      reference: "○ 리포트 자료를 종류별로 ( ㉠ )해 두어라.\n○ 재활용할 쓰레기를 제대로 ( ㉡ )해야 한다.\n○ 그는 언제나 옳고 그른 일을 정확하게 ( ㉢ )할 줄 안다.",
                      num1Text: "分類 - 分離 - 區分",
                      num2Text: "分類 - 區分 - 分離",
                      num3Text: "分離 - 區分 - 分類",
                      num4Text: "分離 - 分類 - 區分",
                      answer: 1),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 단어의 뜻풀이로 바르지 않은 것은?",
                      num1Text: "나이도 먹을 만큼 먹었는데 어쩌면 저렇게 "+"숫저울까?".underLined+"\n－ 숫접다 : 순박하고 진실하다.",
                      num2Text: "그녀는 그가 떠날까 "+"저어하였다.".underLined+"\n－ 저어하다 : 염려하거나 두려워하다.",
                      num3Text: "나는 "+"곰살궂게".underLined+" 이모의 팔다리를 주물렀다.\n－ 곰살궂다 : 일이나 행동이 적당하다.",
                      num4Text: "아이들이 놀이방에서 "+"새살거렸다.".underLined+"\n－ 새살거리다 : 샐샐 웃으면서 재미있게 자꾸 지껄이다.",
                      answer: 3),
        QuestionModel(num: 5,
                      questionText: "다음과 같은 뜻의 속담은?",
                      reference: "  임시변통은 될지 모르나 그 효력이 오래가지 못할 뿐만 아니라 결국에는 사태가 더 나빠진다는 것을 말한다.",
                      num1Text: "빈대 잡으려다 초가삼간 태운다.",
                      num2Text: "언 발에 오줌 누기",
                      num3Text: "여름 불도 쬐다 나면 서운하다.",
                      num4Text: "밑 빠진 독에 물 붓기",
                      answer: 2),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 부분의 표기가 잘못된 것은?",
                      num1Text: "나는 그 일을 "+"시답지".underLined+" 않게 생각한다.",
                      num2Text: "그에게는 "+"다섯 살배기".underLined+" 딸이 있다.",
                      num3Text: "밖에 있던 그가 "+"금세".underLined+" 뛰어왔다.",
                      num4Text: "건물이 "+"부숴진".underLined+" 지 오래되었다.",
                      answer: 4),
        QuestionModel(num: 7,
                      questionText: "묶음표의 쓰임이 잘못된 것은?",
                      num1Text: "나는 3․1 운동(1919) 당시 중학생이었다.",
                      num2Text: "그녀의 나이(年歲)가 60세일 때 그 일이 터졌다.",
                      num3Text: "젊음[희망(希望)의 다른 이름]은 가장 아름다운 꽃이다.",
                      num4Text: "국가의 성립 요소\n  국토\n{ 국민 }\n  주권",
                      answer: 2),
        QuestionModel(num: 8,
                      questionText: "다음 글에 대한 설명으로 적절하지 않은 것은?",
                      reference: "  몽타주는 두 개 이상의 상관성이 없는 장면을 배치함 으로써 새로운 의미를 도출하는 것이다. 에이젠슈테인은 몽타주의 개념을 설명하기 위해 상형문자가 합해져서 회의문자가 만들어지는 과정에서 아이디어를 빌려 왔다. 그는 두 개의 묘사 가능한 것을 병치하여 시각적으로 묘사 불가능한 것을 재현하려 했다. 가령 사람의 ‘눈’과 ‘물’의 이미지를 충돌시켜 ‘슬픔’의 의미를 드러내며, ‘문’ 그림 옆에 ‘귀’ 그림을 놓아 ‘도청’의 이미지를 나타내는 식이다. 의미에 있어서 단일하고, 내용에 있어서 중립적이고 묘사적인 장면을 연결시켜 지적인 의미를 만들어 내는 것이 그가 구현하려 했던 몽타주의 개념이다.",
                      num1Text: "몽타주는 상형문자의 형성 원리를 바탕으로 만들어진 기법이다.",
                      num2Text: "몽타주는 묘사 가능한 대상을 병치하여 묘사 불가능한 것을 재현한다.",
                      num3Text: "‘눈’과 ‘물’의 이미지가 한 장면에 배치되어 ‘슬픔’이 표현된다.",
                      num4Text: "④ ‘문’과 ‘귀’의 이미지가 결합하여 ‘도청’이라는 의미를 나타낸다.",
                      answer: 1),
        QuestionModel(num: 9,
                      questionText: "다음 글에 대한 설명으로 가장 적절한 것은?",
                      reference: "  노동 시장은 생산물 시장과 본질적으로 유사하지만, 생산물 시장이나 타 생산요소 시장과 다른 특징을 지니고 있다. 그중 가장 중요한 특징은 인간이 상품의 일부라는 점이다. 생산물 시장에서 일반 재화는 구매자와 판매자 간에 완전한 이전이 가능하고, 수요자와 공급자는 상대방이 누구인가에 대해 전혀 신경 쓸 필요 없이 오로지 재화 그 자체의 가격과 품질을 고려하여 수요․공급 의사를 결정 한다. 그러나 노동 시장에서 노동이라는 상품은 공급자 자신과 분리될 수 없기 때문에 노동의 수요자와 공급자는 단순히 물건을 사고파는 것 이상의 인간적 관계를 맺게 되고, 수요․공급에 있어서 봉급, 부가 급여, 직업의 사회적 명예, 근무 환경, 직장의 평판 등 가격 이외의 비경제적 요소가 많은 영향을 미친다. 따라서 노동 시장은 가격의 변화에 따라 수요․공급이 유연성 있게 변화하지 않는 동시에 수요.공급의 불균형이 발생해도 가격의 조절 기능이 즉각적으로 작동하지 않는다.",
                      num1Text: "여러 이론을 토대로 노동 시장에 대한 다양한 관점을 소개하고 있다.",
                      num2Text: "여러 사례를 근거로 삼아 노동 시장에 대한 통념을 비판하고 있다.",
                      num3Text: "대비의 방식을 사용하여 노동 시장이 가지는 특징을 설명하고 있다.",
                      num4Text: "노동 시장에 관한 기존의 논의를 분석하여 새로운 주장을 제시하고 있다.",
                      answer: 3),
        QuestionModel(num: 10,
                      questionText: "다음 글에 대한 설명으로 적절하지 않은 것은?",
                      reference: "  소장은 혼자서 빙긋 웃었다. 감독조를 짐짓 3공사장으로 보내길 잘했다고 그는 생각했다. 사실은 그들이 없으면 인부들을 통솔하기가 매우 어려운 실정이었다. 원하는 대로 모두 수걱수걱 들어주고 나면 길 잘못 들인 강아지 새끼처럼 또 무엇을 달라고 보챌지 몰라 불안할수록, 더욱 감독조는 필요했다. 그래서 잠잠해질 때까지 당분간 보냈다가 인부들 과는 낯선 다른 패들로 교대시킬 뿐이었다. 현재 노임도 올렸고 시간 노동제도 실시하고 있는 척할 수밖에 없지만, 우선 내일의 행사를 위해 숨 좀 돌려보자는 게 그의 속셈 이었다. 그 다음엔 주동자들을 먼저 아무도 모르게 경찰에 데려다가 책임을 물어 따끔하게 본때를 보인 후, 여비나 두둑이 주어 구슬리며 딴 지방으로 쫓아 보낼 작정이었다. 그의 손에는 쟁의에 참가했던 인부들의 명단이 저절로 들어와 있는 셈이었다. 그들 불평분자의 절반쯤은 3공사장 인부들과 교대시키고, 나머지는 남겨 두되 각 함바에 뿔뿔이 흩어지게 배당할 거였다. 점차로 시간을 보내면서 하나둘씩 해고해 나갈 것이었다. 차츰차츰 작업량을 늘리고 작업장을 줄여 가면 남는 인부가 많게 될 테니 열흘도 못 가서 감원할 구실이 생길 거였다. 따라서 인상되었던 노임을 차츰 낮추며 도급을 계속시키면서 인부들이 모르는 사이에 전과 같이 나가면 어항에 물 갈아 넣는 것처럼 인부들은 모두 새 사람으로 바뀔 것이었다. 소장은 이 모든 일들을 열흘 안으로 해치우고 원상 복구를 해 놓을 자신이 있었다.\n\n－ 황석영, 〖객지〗중에서 －",
                      num1Text: "소장은 내일의 행사를 원만하게 치르려고 한다.",
                      num2Text: "소장은 쟁의를 해결할 수 있다는 강한 자신감을 갖고 있다.",
                      num3Text: "소장은 쟁의의 주동자들을 해고할 생각을 갖고 있다.",
                      num4Text: "소장은 감독조를 해체하여 상황을 원상 복구할 계획이다.",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 용언의 활용이 잘못된 것은?",
                      num1Text: "그는 "+"허구헌".underLined+" 날 술만 마신다.",
                      num2Text: "네가 시험에 합격했으니 동네 어른들과 잔치라도 "+"벌여야겠구나.".underLined,
                      num3Text: "무슨 말을 해도 괜찮으니 내게 "+"서슴지".underLined+" 말고 말해 보아라.",
                      num4Text: "담당자의 "+"서투른".underLined+" 일 처리 때문에 창구에서 큰 혼란이 있었다.",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "밑줄 친 단어의 품사가 나머지 셋과 다른 것은?",
                      num1Text: "비 온 뒤에 땅이 "+"굳는".underLined+" 법이다.",
                      num2Text: "성격이 "+"다른".underLined+" 사람끼리는 함께 살기 어렵다.",
                      num3Text: "새해에는 으레 "+"새로운".underLined+" 마음이 생기기 마련이다.",
                      num4Text: "몸이 "+"아픈".underLined+" 사람은 교실에 남아 있었다.",
                      answer: 1),
        QuestionModel(num: 13,
                      questionText: "다음 중 고친 문장이 적절하지 않은 것은?",
                      num1Text: "그는 창작 활동과 전시회를 열었다.\n→ 그는 창작 활동을 하고 전시회를 열었다.",
                      num2Text: "그는 천재로 불려졌다.\n→ 그는 천재로 불렸다.",
                      num3Text: "그는 마음씨 좋은 할머니의 손자이다.\n→ 그는 마음씨가 좋은 할머니의 손자이다.",
                      num4Text: "나는 오늘 아침 나무에게 물을 주었다.\n→ 나는 오늘 아침 나무에 물을 주었다.",
                      answer: 3),
        QuestionModel(num: 14,
                      questionText: "밑줄 친 부분을 고친 것 중 가장 적절한 것은?",
                      reference: "  사업자는".underLined+" 절전형 기기 보급 제도가 "+"에너지를".underLined+" 합리적이고 효율적인 이용을 증진하여 에너지 소비로 인한 환경 피해를 "+"줄임으로써".underLined+" 국민 경제의 건전한 "+"발전과".underLined+" 국민 복지의 증진에 이바지한다는 것에 동의한다.",
                      num1Text: "사업자는 → 사업자의",
                      num2Text: "에너지를 → 에너지의",
                      num3Text: "줄임으로써 → 줄임으로서",
                      num4Text: "발전과 → 발전보다",
                      answer: 2),
        QuestionModel(num: 15,
                      questionText: "다음 중 올바른 우리말 표현은?",
                      num1Text: "(초청장 문안에서) 귀하를 이번 행사에 꼭 모시고자 하오니 많이 참석해 주시기 바랍니다.",
                      num2Text: "(전화 통화에서) 과장님은 지금 자리에 안 계십니다. 뭐라고 전해 드릴까요?",
                      num3Text: "(직원이 고객에게) 주문하신 상품은 현재 품절이십니다.",
                      num4Text: "(방송에 출연해서) 저희나라가 이번에 우승한 것은 국민 여러분의 뜨거운 성원 덕택입니다.",
                      answer: 2),
        QuestionModel(num: 16,
                      questionText: "다음 글의 내용과 가장 가까운 것은?",
                      reference: "  정보의 가장 기본적인 원천은 인간이 체험하는 감각이다. 돌이 단단하고 물이 부드럽다는 것은 감각을 통해서 알 수 있다. 그러나 감각이 체계적인 지식으로 발전하는 데는 문제가 있다. 그것은 바로 감각이 주관적이어서 사람과 시기에 따라 동일하지 않기 때문이다. 그래서 예로부터 철학자들은 감각을 중시하지 않았지만, 존 로크와 같은 경험론자들은 감각의 기능을 포기하지 않았다. 왜냐하면 감각을 통하지 않고서는 어떤 구체적인 것도 얻을 수 없다고 생각했기 때문이다.",
                      num1Text: "나는 생각한다. 그러므로 나는 존재한다.",
                      num2Text: "마음을 다하면 인간의 본성을 알게 되고, 인간의 본성을 알게 되면 천명을 알게 될 것이다.",
                      num3Text: "종 치는 것을 보지 못했다면 종을 치면 소리가 난다는 것을 모를 것이다.",
                      num4Text: "세계의 역사는 다름이 아니라 바로 자유 의식의 진보이다.",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "다음 글의 등장인물에 대한 설명으로 적절하지 않은 것은?",
                      reference: "  양반이라는 말은 선비 족속의 존칭이다. 강원도 정선군에 한 양반이 있었는데, 그는 어질면서도 글 읽기를 좋아하였다. 군수가 새로 부임하면 반드시 그 집에 몸소 나아가서 경의를 표하였다. 그러나 그는 집안이 가난해서 해마다 관가에서 환곡을 빌려 먹다 보니 그 빚이 쌓여서 천 석에 이르렀다. 관찰사가 각 고을을 돌아다니다가 이곳의 환곡 출납을 검열하고는 매우 노하여, “어떤 놈의 양반이 군량을 이렇게 축내었느냐?”라고 하였다. 그리고는 명령을 내려 그 양반을 잡아 가두라고 하였다. 군수는 마음속으로 그 양반이 가난해서 갚을 길이 없는 것을 불쌍히 여겼지만 그렇다고 해서 가두지 않을 수도 없었다.\n  그 양반은 밤낮으로 훌쩍거리며 울었지만 별다른 대책도 생각해 낼 수 없었다. 그런 상황에서 그의 아내가 몰아 세우기를, “당신은 한평생 글 읽기를 좋아했지만 관가의 환곡을 갚는 데 아무런 도움이 못 되는구려. 양반 양반 하더니 양반은 한 푼 가치도 못 되는구려.”라고 하였다.\n\n － 박지원, 〖양반전〗중에서 －",
                      num1Text: "양반은 자구책을 마련하지 못하고 있다.",
                      num2Text: "군수는 양반에게 측은지심을 느끼고",
                      num3Text: "관찰사는 공평무사하게 일을 처리하고 있다.",
                      num4Text: "아내는 남편에 대해 외경하는 마음을 지니고 있다.",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "다음 글에 대한 설명으로 적절하지 않은 것은?",
                      reference: "  “심청은 시각이 급하니 어서 바삐 물에 들라.”\n  심청이 거동 보소. 두 손을 합장하고 일어나서 하느님 전에 비는 말이,\n  “비나이다, 비나이다. 하느님 전에 비나이다. 심청이 죽는 일은 추호라도 섧지 아니하되, 병든 아비 깊은 한을 생전에 풀려 하고 이 죽음을 당하오니 명천(明天)은 감동하사 어두운 아비 눈을 밝게 띄워 주옵소서.”\n  눈물지며 하는 말이,\n  “여러 선인네 평안히 가옵시고, 억십만금 이문 남겨 이 물가를 지나거든 나의 혼백 불러내어 물밥이나 주시오.” 하며 안색을 변치 않고 뱃전에 나서 보니 티 없이 푸른 물은 월러렁 콸넝 뒤둥구리 굽이쳐서 물거품 북적찌데한데, 심청이 기가 막혀 뒤로 벌떡 주저앉아 뱃전을 다시 잡고 기절하여 엎딘 양은 차마 보지 못할 지경이었다.\n\n－ 〖심청가〗중에서 －",
                      num1Text: "사건에 대한 서술자의 주관적 서술이 나타나 있다.",
                      num2Text: "등장인물들의 발화를 통해 사건의 상황을 보여준다.",
                      num3Text: "죽음을 초월한 심청의 면모와 효심이 드러나 있다.",
                      num4Text: "대상을 나열하여 장면을 다양하게 제시하고 있다.",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "다음 글의 내용과 시적 상황이 가장 유사한 것은?",
                      reference: "  이때는 추구월망간(秋九月望間)이라. 월색이 명랑하여 남창에 비치고, 공중에 외기러기 응응한 긴 소리로 짝을 찾아 날아가고, 동산의 송림 사이에 두견이 슬피 울어 불여귀를 화답하니, 무심한 사람도 마음이 상하거든 독수 공방에 눈물로 세월을 보내는 송이야 오죽할까. 송이가 모든 심사를 저버리고 책상머리에 의지하여 잠깐 졸다가 기러기 소리에 놀라 눈을 뜨고 보니, 남창에 밝은 달 허리에 가득 하고 쓸쓸한 낙엽송은 심회를 돕는지라, 잊었던 심사가 다시 가슴에 가득해지며 눈물이 무심히 떨어진다. 송이가 남창을 가만히 열고 달빛을 내다보며 위연탄식하는데,\n  “달아, 너는 내 심사를 알리라. 작년 이때 뒷동산 명월 아래 우리 임을 만났더니, 달은 다시 보건마는 임을 어찌 보지 못하는고. 심양강의 탄금녀는 만고문장 백낙천을 달 아래 만날 적에, 설진심중무한사(說盡心中無限事)를 세세히 하였건마는, 나는 어찌 박명하여 명랑한 저 달 아래서 부득설진심중사(不得說盡心中事)하니 가련하지 아니할까. 사람은 없어 말하지 못하나, 차라리 심중사를 종이 위에나 그리리라.”\n하고, 연상을 내어 먹을 흠씬 갈고 청황모 무심필을 듬뿍 풀어 백능화주지를 책상에 펼쳐 놓고, 섬섬옥수로 붓대를 곱게 쥐고 탄식하면서 맥맥이 앉았다가, 고개를 돌려 벽공의 높은 달을 두세 번 우러러보더니, 서두에 ‘추풍감별곡 (秋風感別曲)’ 다섯 자를 쓰고, 상사가 생각 되고, 생각이 노래 되고, 노래가 글이 되어 붓끝을 따라오니, 붓대가 쉴 새 없이 쓴다.\n\n － 〖채봉감별곡〗중에서 －",
                      num1Text: "임이여 물을 건너지 마오 / 임은 기어이 물을 건너갔네 / 물에 빠져 돌아가시니 / 이제 임이여 어이할꼬.",
                      num2Text: "가위로 싹둑싹둑 옷 마르노라 / 추운 밤 열 손가락 모두 굳었네 / 남 위해 시집갈 옷 항상 짓건만 / 해마다 이내 몸은 홀로 잔다네.",
                      num3Text: "펄펄 나는 저 꾀꼬리 / 암수 서로 정다운데 / 외로울사 이내 몸은 / 누구와 함께 돌아갈꼬.",
                      num4Text: "비 개인 긴 언덕에 풀빛 짙은데 / 님 보내는 남포에는 서러운 노래 퍼지네 / 대동강 물은 언제나 마를까 / 이별의 눈물 해마다 푸른 물결 더하니.",
                      answer: 3),
        QuestionModel(num: 20,
                      questionText: "다음 글의 전개 순서로 가장 자연스러운 것은?",
                      reference: "(가) 21세기 인류의 운명은 과학 기술 체계에 부여된 힘이 어떻게 사용되는가에 따라서 좌우될 것이다. 기술 공학에 의해 새로운 유토피아가 도래할 것이라는 소박하고 성급한 희망과, 기술이 인간을 대신해서 역사의 주체로 등극하리라는 허무주의적인 전망이 서로 엇갈리는 기로에 우리는 서 있다. 기술 공학적 질서의 본질과 영향력을 고려하지 않은 모든 문화론은 공허할 수밖에 없다.\n\n(나) 그러나 모든 생산 체제가 중앙 집중적인 기업 문화를 포기할 수는 없으며, 기업 문화의 전환은 어디까지나 조직의 자기 보존, 생산의 효율성, 이윤의 극대화 등을 달성하기 위한 것이다. 또 무엇보다 기업 내부의 문화적 전환을 떠나서 환경이나 자원, 에너지 등의 범사회적인 문제들이 심각해질수록 사람들은 기술 공학의 마술적 힘에 매달리고, 그러한 위기들을 중앙 집중적 권력에 의해 효과적으로 통제ㆍ관리하는 기술 사회에 대한 유혹을 강하게 느낄 것이다.\n\n(다) 기술적 질서는 자연은 물론 인간들의 삶의 방식에도 심층적인 변화를 초래했다. 관리 사회로의 이행이나 노동 과정의 자동화 등은 사회 공학적 기술이 정치 부문과 생산에 적용된 대표적인 사례들이다. 물론 기술 사회가 반드시 획일화된 관리 사회나 중앙 집권적 기업 문화로만 대표되지는 않는다. 소프트웨어 중심의 컴퓨터 산업이나 초전도체 산업 등 고도 기술 사회의 일부 산업 분야는 중앙 집권적 기업 문화를 지양하고 자율성과 개방성을 특징으로 지니는 유연한 체제를 채택할 것이라는 견해가 상당히 유력하다.\n\n(라) 생활 세계의 질서를 좌우하고 경제적 행위의 목적으로 자리 잡은 기술은 더 이상 상품의 부가 가치를 높여 주는 생산 수단만으로 이해되지 않는다. 기술의 체계는 이제 여러 연관된 기술들과 기술적 지식들에 의해서 구성된 유기적인 앙상블로 기능하는 것이다. 기술은 그 자체의 질서와 역동성을 지니는 체계이며 유사 주체로서의 양상을 보이기 때문이다.",
                      num1Text: "(가) － (나) － (다) － (라)",
                      num2Text: "(가) － (나) － (라) － (다",
                      num3Text: "(가) － (다) － (나) － (라)",
                      num4Text: "(가) － (라) － (다) － (나)",
                      answer: 3)
        ]
        
        let exam = ExamModel(id: 201521, year: 2015, examTypeID: "지방직", subjectID: "국어", questions: questions)
        
        exam2015.append(exam)
        
    }
    func saveExam201522() {
        let questions =
        [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분과 의미가 가장 가까운 것은?",
                      reference: "There are some diseases your doctor will "+"rule out".underLined+" before making a diagnosis.",
                      num1Text: "trace",
                      num2Text: "exclude",
                      num3Text: "instruct",
                      num4Text: "examine",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "다음 중 어법상 옳은 것은?",
                      num1Text: "She supposed to phone me last night, but she didn't.",
                      num2Text: "I have been knowing Jose until I was seven.",
                      num3Text: "You'd better to go now or you'll be late.",
                      num4Text: "Sarah would be offended if I didn't go to her party.",
                      answer: 4),
        QuestionModel(num: 3,
                      questionText: "우리말을 영어로 옮긴 것 중 가장 어색한 것은?",
                      num1Text: "제인은 보기만큼 젊지 않다.\n→ Jane is not as young as she looks.",
                      num2Text: "전화하는 것이 편지 쓰는 것보다 더 쉽다.\n→ It's easier to make a phone call than to write a letter.",
                      num3Text: "너는 나보다 돈이 많다.\n→ You have more money than I.",
                      num4Text: "당신 아들 머리는 당신 머리와 같은 색깔이다.\n→ Your son's hair is the same color as yo",
                      answer: 4),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 부분에 들어갈 표현으로 가장 적절한 것은?",
                      reference: "  M : Would you like to go out for dinner, Mary?\n  W : Oh, I'd love to. Where are we going?\n  M : How about the new pizza restaurant in town?\n  W : Do we need a reservation?\n  M : I don't think it is necessary.\n  W : But we may have to wait in line because it's Friday night.\n  M : You are absolutely right. Then, I'll ____________ right now.\n  W : Great.",
                      num1Text: "cancel the reservation",
                      num2Text: "give you the check",
                      num3Text: "eat some breakfast",
                      num4Text: "book a table",
                      answer: 4),
        QuestionModel(num: 5,
                      questionText: "다음 글의 (A), (B), (C)에서 어법상 옳은 것을 모두 고른 것은?",
                      reference: "Pattern books contain stories that make use of repeated phrases, refrains, and sometimes rhymes. In addition, pattern books frequently contain pictures (A)[that/what] may facilitate story comprehension. The predictable patterns allow beginning second language readers to become involved (B)[immediate/immediately] in a literacy event in their second language. Moreover, the use of pattern books (C)[meet/meets] the criteria for literacy scaffolds by modeling reading, by challenging students' current level of linguistic competence, and by assisting comprehension through the repetition of a simple sentence pattern.",
                      num1Text: "that - immediate - meet",
                      num2Text: "what - immediately - meets",
                      num3Text: "that - immediately - meets",
                      num4Text: "what - immediate - meet",
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 부분에 들어갈 가장 적절한 것은?",
                      reference: "Culture travels, like people. There are Chinese and Zen gardens in cities from Sydney to Edinburgh to San Francisco. 'World Music' is enormously popular: the latest disco style breezily combines flamenco with jazz and Gaelic traditions. Dance troupes from Africa and South America routinely perform overseas. It would be impossible to disentangle strands of influence in the spaghetti western, samurai film, Hollywood action flick, Indian adventure story, and Hong Kong cinema. In the modern world, no culture, however 'primitive' and remote, remains ___________. The Huichol Indians, who live in mountain villages of Mexico, make their masks and bowls using glass beads imported from Japan and Czechoslovakia",
                      num1Text: "isolated",
                      num2Text: "interconnected",
                      num3Text: "multicultural",
                      num4Text: "complex",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "주어진 글의 제목으로 가장 적절한 것을 고르시오. [7～8]",
                      reference: "Depending on your values, different kinds of numbers may be important to you. To some, it's cholesterol count and blood pressure figures; to others, it's the number of years they've been married. To many, the sum total in the retirement account is the number-one number, and some people zero in on the amount left on their mortgage. But I contend that your per-hour worth should be among the top-of-mind numbers that are important to you ― no matter what your values or priorities are ― even if you don't earn your living on a per-hour rate. Knowing the value of your time enables you to make wise decisions about where and how you spend it so you can make the most of this limited resource according to your circumstances, goals, and interests. Obviously, the higher you raise your per-hour worth while upholding your priorities, the more you can propel your efforts toward meeting your goals, because you have more resources at your disposal ― you have either more money or more time, whichever you need most.",
                      num1Text: "Your Time Is Money",
                      num2Text: "Maintaining High Motivation",
                      num3Text: "Part-time Jobs Are Better",
                      num4Text: "Living Within Your Income",
                      answer: 1),
        QuestionModel(num: 8,
                      questionText: "",
                      reference: "Making mistakes is central to the education of budding scientists and artists of all kinds, who must have the freedom to experiment, try this idea, flop, try another idea, take a risk, be willing to get the wrong answer. One classic example is Thomas Edison's reply to a reporter who was lamenting Edison's ten thousand experimental failures in his effort to create the first incandescent light bulb. “I have not failed,” he told the reporter. “I successfully discovered 10,000 elements that don't work.” Most children, however, are denied the freedom to noodle around, experiment, and be wrong in ten ways, let alone ten thousand. The focus on constant testing to measure and standardize children's accomplishments has intensified their fear of failure. It is certainly important for children to learn to succeed; but it is just as important for them to learn not to fear failure.",
                      num1Text: "Getting It Right the First Time",
                      num2Text: "The Secret Inventions of Edison",
                      num3Text: "Road to Creativity: Avoid Risks",
                      num4Text: "Failure: Nothing to Be Afraid Of",
                      answer: 4),
        QuestionModel(num: 9,
                      questionText: "우리말을 영어로 옮긴 것 중 가장 어색한 것은?",
                      num1Text: "그녀는 젊었을 때 더 열심히 일하지 않았던 것을 후회한다.\n→ She regrets not having worked harder in her youth.",
                      num2Text: "그는 경험과 지식을 둘 다 겸비한 사람이다.\n→ He is a man of both experience and knowledge.",
                      num3Text: "분노는 정상적이고 건강한 감정이다.\n→ Anger is a normal and healthy emotion.",
                      num4Text: "어떤 상황에서도 너는 이곳을 떠나면 안 된다.\n→ Under no circumstances you should not leave here.",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "밑줄 친 부분에 들어갈 표현으로 가장 적절한 것은?",
                      reference: "  M : Excuse me. How can I get to Seoul Station? W: You can take the subway.\n  M: How long does it take?\n  W: It takes approximately an hour.\n  M : How often does the subway run?\n  W: _______________________.",
                      num1Text: "It is too far to walk",
                      num2Text: "Every five minutes or so",
                      num3Text: "You should wait in line",
                      num4Text: "It takes about half an hour",
                      answer: 2),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 부분과 의미가 가장 가까운 것을 고르시오. [11～13]",
                      reference: "Bringing presents for his children "+"alleviated".underLined+" some of the guilt he felt for not spending enough time with them.",
                      num1Text: "relieved",
                      num2Text: "accumulated",
                      num3Text: "provoked",
                      num4Text: "accelerated",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "",
                      reference: "I am not "+"made of money,".underLined+" you know!",
                      num1Text: "needy",
                      num2Text: "thrifty",
                      num3Text: "wealthy",
                      num4Text: "stingy",
                      answer: 3),
        QuestionModel(num: 13,
                      questionText: "",
                      reference: "Experienced salespeople claim there is a difference between being assertive and being "+"pushy.".underLined,
                      num1Text: "thrilled",
                      num2Text: "brave",
                      num3Text: "timid",
                      num4Text: "aggressive",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "주어진 부분에 들어갈 가장 적절한 것을 고르시오. [14～15]",
                      reference: "A growing number of people are seeking medical attention for vitamin D deficiency, a common condition among those who spend a lot of time indoors. It is well known that vitamin D deficiency can affect one's muscles, bones and immunity and is even associated with cancer. Vitamin D is produced by the body in response to skin being exposed to sunlight. A lot of women, however, wear sunscreen before they go out, and this often makes it more difficult for their body to produce vitamin D as ________________________.",
                      num1Text: "many types of sunscreen may contain beneficial substances",
                      num2Text: "sunscreen can block vitamin D-producing ultraviolet rays",
                      num3Text: "their sunscreen is professionally prescribed",
                      num4Text: "they exercise on a regular basis",
                      answer: 2),
        QuestionModel(num: 15,
                      questionText: "",
                      reference: "Muzafer Sherif's research on the autokinetic effect is a good example of the role of ____________ in perception. People in his experiments were told that a spot of light projected on the wall would move and were instructed to estimate the amount of movement. Although the spot of light never actually moved, the people inevitably reported movement. When told that the spot of light would even trace out letters and words, participants began reporting words and sentences. Clearly what they thought would happen resulted in the addition of a considerable amount of information to their sensations.",
                      num1Text: "unification",
                      num2Text: "expectation",
                      num3Text: "competition",
                      num4Text: "quantification",
                      answer: 2),
        QuestionModel(num: 16,
                      questionText: "다음 글의 (A)와 (B)에 들어갈 가장 적절한 것은?",
                      reference: "Mythology was an integral part of Egyptian culture for much of its timespan. Characters and events from myth permeate Egyptian art, architecture, and literature. Myths  (A)  many of the rituals performed by kings and priests. Educated Egyptians believed that a knowledge of myth was an essential weapon in the fight to survive the dangers of life and the afterlife. There is disagreement among Egyptologists about when mythical narratives first developed in Egypt. This dispute is partly due to the difficulty of deciding what should be counted as a myth. Today, the term myth is often used in an unfavorable way to refer to something that is exaggerated or untrue. In ancient cultures, myth did not have this  (B)  connotation; myths could be regarded as stories that contained poetic rather than literal truths. Some scholars separate myths from other types of traditional tale by classifying them as stories featuring deities. This simple definition might work quite well for Egypt, but not for all cultures.",
                      num1Text: "extinguished - immoral",
                      num2Text: "bolstered - literal",
                      num3Text: "underpinned - negative",
                      num4Text: "corroborated - political",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "주어진 부분에 들어갈 가장 적절한 것을 고르시오. [17～18]",
                      reference: "We rarely get tired when ______________. For example, I recently took a vacation in the Canadian Rockies up around Lake Louise. I spent several days trout fishing along Coral Creek, fighting my way through brush higher than my head, stumbling over logs, struggling through fallen timber ― yet after eight hours of this, I was not exhausted. Why? Because I was excited, exhilarated. I had a sense of high achievement: six cutthroat trout. But suppose I had been bored by fishing, then how do you think I would have felt? I would have been worn out by such strenuous work at an altitude of seven thousand feet.",
                      num1Text: "we are doing something interesting and exciting",
                      num2Text: "we get a good night's sleep and a hearty meal",
                      num3Text: "we do household chores for our family",
                      num4Text: "we are elevated to high altitudes",
                      answer: 1),
        QuestionModel(num: 18,
                      questionText: "",
                      reference: "The 'ten-thousand-hour rule' states that expertise requires at least ten thousand hours of practice. Clearly, though, time is not the only requirement. Years of one's life spent practicing the wrong things will not lead to expertise any more than spending the same amount of time watching television. Time is a basic prerequisite, but not ______________________________. Layered upon time are a slew of other ingredients, life focus, precision, discipline, and desire.",
                      num1Text: "a sufficient one in itself",
                      num2Text: "a requisite for time",
                      num3Text: "a tolerant one of others",
                      num4Text: "a predictor of longevity",
                      answer: 1),
        QuestionModel(num: 19,
                      questionText: "George Stephenson에 관한 다음 글의 내용과 일치하지 않는 것은?",
                      reference: "George Stephenson gained a reputation for working with the primitive steam engines employed in mines in the northeast of England and in Scotland. In 1814, Stephenson made his first locomotive, 'Blucher.' In 1821, Stephenson was appointed engineer for the construction of the Stockton and Darlington railway. It opened in 1825 and was the first public railway. In October 1829, the railway's owners staged a competition to find the best kind of locomotive to pull heavy loads over long distances. Stephenson's locomotive 'Rocket' was the winner, achieving a record speed of 36 miles per hour. The opening of the Stockton and Darlington railway and the success of 'Rocket' stimulated the laying of railway lines and the construction of locomotives all over the country. Stephenson became engineer on a number of these projects and also participated in the development of railways in Belgium and Spain.",
                      num1Text: "탄광에 사용된 초기 증기 기관과 관련된 일을 하여 명성을 얻었다.",
                      num2Text: "1814년에 그의 첫 번째 기관차를 만들었다.",
                      num3Text: "시속 36마일의 기관차를 개발하여 기관차 대회에서 준우승했다.",
                      num4Text: "벨기에와 스페인의 철도 개발에도 참여했다.",
                      answer: 3),
        QuestionModel(num: 20,
                      questionText: "밑줄 친 부분에 들어갈 가장 적절한 것은?",
                      reference: "There are many instances in our society in which it is entirely appropriate for people to play a power role over others. __________________, teachers, coaches, police, and parents all play this role. Any leader of a group of people has to have some kind of authority. Still, the right to wield power and the extent to which an authority should wield power must be questioned and negotiated lest the power be abusive and lead to injustice and unfairness.",
                      num1Text: "However",
                      num2Text: "Otherwise",
                      num3Text: "For example",
                      num4Text: "Nevertheless",
                      answer: 3)
        ]
        
        let exam = ExamModel(id: 201511, year: 2015, examTypeID: "지방직", subjectID: "영어", questions: questions)
        
        exam2015.append(exam)
    }
    func saveExam201523() {
        let questions =
        [
        QuestionModel(num: 1,
                      questionText: "㉠ 국가에 대한 설명으로 옳은 것은?",
                      reference: "( ㉠ )에서는 백성들에게 금하는 법 8조가 있었다. 그것은 대개 사람을 죽인 자는 즉시 죽이고, 남에게 상처를 입히는 자는 곡식으로 갚는다. 도둑질을 한 자는 노비로 삼는다. 용서받고자 하는 자는 한 사람마다 50만 전을 내야 한다. 비록 용서를 받아 보통 백성이 되어도 사람들이 이를 부끄럽게 여겨 혼인을 하고자 해도 짝을 구할 수 없다.",
                      num1Text: "옥저와 동예를 정복하였다.",
                      num2Text: "족외혼과 책화의 풍습이 있었다.",
                      num3Text: "별도의 행정구역인 사출도가 있었다.",
                      num4Text: "중국의 한과 대립할 정도로 성장하였다.",
                      answer: 4),
        QuestionModel(num: 2,
                      questionText: "다음 고구려에서 일어난 사건을 시기 순으로 바르게 나열한 것은?",
                      reference: "  ㄱ. 불교를 수용하고, 율령을 반포하였다.\n  ㄴ. 고국원왕이 평양성전투에서 전사하였다.\n  ㄷ. 을파소를 등용하여 진대법을 실시하였다.\n  ㄹ. 한성을 공격하여 함락시키고 개로왕을 죽였다.",
                      num1Text: "ㄴ → ㄷ → ㄱ → ㄹ",
                      num2Text: "ㄴ → ㄷ → ㄹ → ㄱ",
                      num3Text: "ㄷ → ㄴ → ㄱ → ㄹ",
                      num4Text: "ㄷ → ㄴ → ㄹ → ㄱ",
                      answer: 3),
        QuestionModel(num: 3,
                      questionText: "(가), (나) 사이의 시기에 있었던 사실로 옳은 것은?",
                      reference: "(가) 국호를 신라로 바꾸고, 왕의 칭호도 마립간에서 왕으로 고쳤다. 대외적으로는 우산국을 복속시켰다.\n\n(나) 한강 유역을 빼앗고, 고령 지역의 대가야를 정복하였다. 북쪽으로는 함경도 지역까지 진출하였다.",
                      num1Text: "백제 동성왕과 혼인 동맹을 맺었다.",
                      num2Text: "김씨에 의한 왕위 계승권이 확립되었다.",
                      num3Text: "진골 귀족 세력의 반발로 녹읍이 부활되었다.",
                      num4Text: "병부를 설치하고, 백관의 공복을 제정하였다.",
                      answer: 4),
        QuestionModel(num: 4,
                      questionText: "1970년대 시행된 정책이 아닌 것은?",
                      num1Text: "금융실명제의 실시",
                      num2Text: "새마을운동의 추진",
                      num3Text: "통일벼의 전국적 보급",
                      num4Text: "수출 주도형 중화학 공업화",
                      answer: 1),
        QuestionModel(num: 5,
                      questionText: "다음과 같은 현상이 일어나게 된 배경으로 옳지 않은 것은?",
                      reference: "향회라는 것이 한 마을 사민(士民)의 공론에 따른 것이 아니고, 수령의 손 아래 놀아나는 좌수ㆍ별감들이 통문을 돌려 불러 모은 것에 불과합니다. 그 향회에서는 관의 비용이 부족 하다는 핑계로 제멋대로 돈을 거두고 법을 만드니, 일의 원통함이 이보다 심한 것이 없습니다.",
                      num1Text: "사족의 향촌 지배력이 약화되었다.",
                      num2Text: "수령과 향리의 영향력이 약해졌다.",
                      num3Text: "향회는 수령의 부세 자문 기구로 전락하였다.",
                      num4Text: "양반 사족과 부농층이 향촌의 주도권 다툼을 벌였다.",
                      answer: 2),
        QuestionModel(num: 6,
                      questionText: "8․15 광복 직후 일어난 역사적 사실로 옳은 것은?",
                      num1Text: "여운형은 조선건국동맹을 조직하였다.",
                      num2Text: "대한민국임시정부는 건국강령을 발표하였다.",
                      num3Text: "조선어학회는 우리말 큰사전 편찬을 시작하였다.",
                      num4Text: "모스크바 3상 회의에서 한반도 문제가 논의되었다.",
                      answer: 4),
        QuestionModel(num: 7,
                      questionText: "다음 사건으로 인하여 발생한 역사적 사실은?",
                      reference: "심충겸이 장원 급제를 하자 전랑으로 천거하려고 하였다. 김효원이 “외척은 쓸 수 없다.” 하며 막으니, 심의겸이 “외척이 원흉의 문객보다는 낫지 않으냐.” 하였다. 이때 김효원 편을 드는 사람들은 “효원의 말은 공론에서 나온 것이다. 그런데 의겸이 사사로운 혐의로 좋은 선비를 배척하니 매우 옳지 못하다.” 하였다.",
                      num1Text: "동인과 서인으로의 분화",
                      num2Text: "남인과 북인으로의 분화",
                      num3Text: "노론과 소론으로의 분화",
                      num4Text: "서인과 남인 간의 예송논쟁",
                      answer: 1),
        QuestionModel(num: 8,
                      questionText: "다음에서 설명하는 밑줄 친 ‘청(廳)’에 해당하는 것은?",
                      reference: "영의정 이원익이 의논하기를, “각 고을에서 진상하는 공물이 각 사의 방납인들에 의해 중간에서 막혀 물건 하나의 가격이 몇 배 또는 몇십 배, 몇백 배가 되어 그 폐단이 이미 고질화 되었는데, 기전(畿甸)의 경우는 더욱 심합니다. 그러니 지금 마땅히 별도로 하나의 "+"청(廳)".underLined+"을 설치하여 매년 봄․가을에 백성들에게서 쌀을 거두되, 1결당 매번 8말씩 거두어 본"+"청(廳)".underLined+"에 보내면 본청에서는 당시의 물가를 보아 가격을 넉넉하게 헤아려 정해 거두어들인 쌀로 방납인에게 주어 필요한 때에 사들이도록 함으로써 간사한 꾀를 써 물가가 오르게 하는 길을 끊으셔야 합니다. ... (후략) ...”",
                      num1Text: "어영청",
                      num2Text: "상평청",
                      num3Text: "선혜청",
                      num4Text: "균역청",
                      answer: 3),
        QuestionModel(num: 9,
                      questionText: "다음은 조선 후기 집필된 역사서의 일부이다. 이 책에 대한 설명 으로 옳은 것은?",
                      reference: "삼국사에서 신라를 으뜸으로 한 것은 신라가 가장 먼저 건국했고, 뒤에 고구려와 백제를 통합하였으며, 또 고려는 신라를 계승하였으므로 편찬한 것이 모두 신라의 남은 문적(文籍)을 근거로 했기 때문이다. … (중략) … 고구려의 강대하고 현저함은 백제에 비할 바가 아니며, 신라가 차지한 땅은 남쪽의 일부에 불과할 뿐이다. 그러므로 김씨는 신라사에 쓰여진 고구려 땅을 근거로 했을 뿐이다.",
                      num1Text: "우리 역사의 독자적 정통론을 세워 이를 체계화하였다.",
                      num2Text: "단군－부여－고구려의 흐름에 중점을 두어 만주 수복을 희구 하였다.",
                      num3Text: "중국 및 일본의 자료를 망라한 기전체 사서로 민족사 인식의 폭을 넓혔다.",
                      num4Text: "여러 영역을 항목별로 나눈 백과사전적 서술로 문화 인식의 폭을 확대하였다.",
                      answer: 1),
        QuestionModel(num: 10,
                      questionText: "다음 취지서를 발표한 단체의 활동에 대한 설명으로 옳은 것은?",
                      reference: "무릇 나라의 독립은 오직 자강(自强)의 여하에 달려 있는 것이다. … (중략) … 그러나 자강의 방도를 강구하려 할 것 같으면 다른 곳에 있지 않고 교육을 진작하고 산업을 일으키는 데 있으니 무릇 교육이 일어나지 않으면 민지(民智)가 열리지 않고 산업이 일어나지 않으면 국부가 증가하지 못하는 것이다. 교육과 산업의 발달이 곧 자강의 방도임을 알 수 있는 것이다.",
                      num1Text: "만민공동회를 개최하여 러시아의 침략 정책을 강력하게 규탄 하였다.",
                      num2Text: "고종의 강제 퇴위 반대 운동을 전개하다가 일본의 탄압으로 해산되었다.",
                      num3Text: "방직, 고무, 메리야스 공장을 육성하여 경제 자립을 이루자는 운동을 전개하였다.",
                      num4Text: "일본의 황무지 개간에 대한 대중적인 반대운동을 일으켜 이를 철회시키는데 성공하였다.",
                      answer: 2),
        QuestionModel(num: 11,
                      questionText: "다음에서 설명하는 인물의 업적으로 옳은 것은?",
                      reference: "성은 김씨이다. 29세에 황복사에서 머리를 깎고 승려가 되었다. 얼마 후 중국으로 가서 부처의 교화를 보고자 하여 원효 (元曉)와 함께 구도의 길을 떠났다. … (중략) … 처음 양주에 머무를 때 주장(州將) 유지인이 초청하여 그를 관아에 머물게 하고 성대하게 대접하였다. 얼마 후 종남산 지상사에 가서 지엄(智儼)을 뵈었다.\n\n- 〖삼국유사〗 -",
                      num1Text: "〖화엄일승법계도〗를 저술하여 화엄사상을 정리하였다.",
                      num2Text: "중국에서 풍수지리설을 들여와 지세의 중요성을 일깨웠다.",
                      num3Text: "〖십문화쟁론〗을 지어 종파 간의 대립을 해소하고자 하였다.",
                      num4Text: "인도와 중앙아시아 지역을 여행하고 돌아와 〖왕오천축국전〗을 저술하였다.",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "밑줄 친 ‘북국(北國)’에 대한 설명으로 옳지 않은 것은?",
                      reference: "원성왕 6년 3월 "+"북국(北國)".underLined+"에 사신을 보내 빙문(聘問)하였다. … (중략) … 요동 땅에서 일어나 고구려의 북쪽 땅을 병합 하고 신라와 서로 경계를 맞대었지만, 교빙한 일이 역사에 전하는 것이 없었다. 이때 와서 일길찬 백어(伯魚)를 보내 교빙하였다.",
                      num1Text: "감찰 기관으로 중정대가 있었다.",
                      num2Text: "최고 교육 기관으로 태학감을 두었다.",
                      num3Text: "중앙의 정치 조직으로 3성 6부를 두었다.",
                      num4Text: "지방의 행정 조직으로 5경 15부 62주가 있었다.",
                      answer: 2),
        QuestionModel(num: 13,
                      questionText: "다음 왕의 재위 기간에 있었던 사실로 옳은 것은?",
                      reference: "왕은 중국에 36명의 승려를 파견하여 법안종을 배우도록 하였다. 또한 제관과 의통을 파견하여 천태학에 대한 관심을 보였다.",
                      num1Text: "승과 제도를 시행하였다.",
                      num2Text: "요세가 세운 백련사를 후원하였다.",
                      num3Text: "의천이 국청사를 창건하는 것을 후원하였다.",
                      num4Text: "거란과의 전쟁을 물리치기 위해 초조대장경을 조성하였다",
                      answer: 1),
        QuestionModel(num: 14,
                      questionText: "밑줄 친 ‘그’에 대한 설명으로 옳은 것은?",
                      reference: "그".underLined+"는 송악산 아래의 자하동에 학당을 마련하여 낙성(樂聖), 대중(大中), 성명(誠明), 경업(敬業), 조도(造道), 솔성(率性), 진덕(進德), 대화(大和), 대빙(待聘) 등의 9재(齋)로 나누고 각각 전문 강좌를 개설토록 하였다. 그리하여 당시 과거 보려는 자제들은 반드시 먼저 "+"그".underLined+"의 학도로 입학하여 공부하는 것이 상례로 되었다.",
                      num1Text: "9경과 3사를 중심으로 교육하였다.",
                      num2Text: "유교적 합리주의 사관에 기초하여 〖삼국사기〗를 편찬하였다.",
                      num3Text: "유교 사상을 치국의 근본으로 삼아 시무 28조의 개혁안을 올렸다.",
                      num4Text: "〖소학〗과 〖주자가례〗를 중시하고 권문세족과 불교의 폐단을 비판하였다.",
                      answer: 1),
        QuestionModel(num: 15,
                      questionText: "다음 설명과 관련된 사건으로 옳은 것은?",
                      reference: "1975년 서지학자 박병선 박사는 이곳 도서관에서 조선시대 도서가 보관되어 있음을 발견하고 목록을 정리하여 그 존재를 알렸다. 그 후 1990년대 초 한국 정부가 반환을 공식 요청 하기에 이르렀다. 그 결과 2011년에 ‘5년마다 갱신이 가능한 대여 방식’으로 반환되었다.",
                      num1Text: "어재연이 광성보에서 결사 항전하였다.",
                      num2Text: "제너럴 셔먼호 사건을 빌미로 일어났다.",
                      num3Text: "프랑스가 강화도 외규장각 도서를 약탈하였다.",
                      num4Text: "조선이 처음으로 서양 국가와 외교 관계를 맺었다.",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "동학농민운동에 관한 설명으로 옳지 않은 것은?",
                      num1Text: "전주화약 이후 조선 정부는 청·일 군대의 철수를 요청하였다.",
                      num2Text: "조선 정부는 농민들의 요구에 대응하여 삼정이정청을 설치 하였다.",
                      num3Text: "청․일전쟁 발발 직후에도 전라도 지역을 중심으로 집강소가 운영되었다.",
                      num4Text: "일본군이 경복궁을 점령한 후 전라도와 충청도 지역의 농민군이 연합하였다.",
                      answer: 2),
        QuestionModel(num: 17,
                      questionText: "1920년대 산미 증식 계획에 대한 설명으로 옳은 것은?",
                      num1Text: "춘궁 퇴치․자력갱생 등을 내세웠다.",
                      num2Text: "쌀․잡곡에 대한 배급제도와 공출제도가 실시되었다.",
                      num3Text: "소작농을 보호한다는 명목으로 소작조정령을 발표하였다.",
                      num4Text: "공업화로 인한 일본의 식량 부족 문제를 해결하고자 실시 하였다.",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "다음 법이 공포된 이후 나타난 일제의 지배 정책에 대한 설명으로 옳지 않은 것은?",
                      reference: "제4조 정부는 전시에 국가 총동원 상 필요할 때에는 칙령이 정하는 바에 따라 제국 신민을 징용하여 총동원 업무에 종사하게 할 수 있다.",
                      num1Text: "마을에 애국반을 편성하여 일상생활을 통제하였다.",
                      num2Text: "일본식 성과 이름으로 고치는 창씨개명을 시행하였다.",
                      num3Text: "여성에게 작업복인 ‘몸뻬’라는 바지의 착용을 강요하였다.",
                      num4Text: "토지 현황 파악을 위해 전국적으로 토지 소유권을 조사하였다.",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "다음 괄호 안에 들어갈 사항으로 옳은 것만을 <보기>에서 모두 고른 것은?",
                      reference: "2000년 12월에 유네스코 세계 유산으로 지정된 경주 역사 유적 지구는 남산 지구, 월성 지구, 대릉원 지구, 황룡사 지구, 산성 지구로 세분된다. 이 중에 남산 지구에 해당하는 문화유산으로는 (     ) 등이 있다.",
                      reference2: "<보기>\nㄱ.계림  ㄴ.나정(蘿井)  ㄷ.포석정\nㄹ.분황사  ㅁ.첨성대  ㅂ.배리 석불 입상",
                      num1Text: "ㄱ, ㄴ, ㄷ",
                      num2Text: "ㄱ, ㄹ, ㅁ",
                      num3Text: "ㄴ, ㄷ, ㅂ",
                      num4Text: "ㄹ, ㅁ, ㅂ",
                      answer: 3),
        QuestionModel(num: 20,
                      questionText: "(가) ～ (다) 전시과에 대한 설명으로 옳은 것을 <보기>에서 모두 고른 것은?",
                      reference: "ㄱ.(가) － 관품과 함께 인품도 고려되었다.\nㄴ.(나) － 한외과가 소멸되었다.\nㄷ.(다) － 승인과 지리업에게 별사전이 지급되었다.\nㄹ.(가) ～ (다) － 경기 8현에 한하여 지급되었다.",
                      imgModel: ImageModel(imageString: "201523-20", imgWidth: 330, imgHeight: 330),
                      num1Text: "ㄱ, ㄴ",
                      num2Text: "ㄱ, ㄷ",
                      num3Text: "ㄴ, ㄷ",
                      num4Text: "ㄷ, ㄹ",
                      answer: 2)
        ]
        
        let exam = ExamModel(id: 201523, year: 2015, examTypeID: "지방직", subjectID: "한국사", questions: questions)
        
        exam2015.append(exam)
    }
}
