//
//  ExamStore2019.swift
//  HandGosi
//
//  Created by Sy Lee on 2022/08/22.
//

import Foundation

class ExamStore2019 {
    var exam2019: [ExamModel] = []
    
    init() {
        saveExam201911()
        saveExam201912()
        saveExam201913()
        
        saveExam201921()
        saveExam201922()
        saveExam201923()
    }
    
    //국가직
    func saveExam201911() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 단어의 품사를 같은 것끼리 묶은 것은?",
                      reference: "○ 쌍둥이도 서로 성격이 ㉠"+"다른".underLined+" 법이다.\n○ 날씨가 건조하면 나무가 잘 ㉡"+"크지".underLined+" 못한다.\n○ 남부 지방에 홍수가 ㉢"+"나서".underLined+" 많은 수재민이 생겼다.\n○ 그 사람이 농담은 하지만 ㉣"+"허튼".underLined+" 말은 하지 않는다.\n○ 상대에게 자유를 주는 것이 진정한 사랑이 ㉤"+"아닐까?".underLined,
                      num1Text: "㉠, ㉡",
                      num2Text: "㉡, ㉢",
                      num3Text: "㉢, ㉣",
                      num4Text: "㉣, ㉤",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "다음의 여러 조건에 가장 잘 맞는 토론 논제는?",
                      reference: "○ 긍정 평서문으로 제시되어야 한다.\n○ 찬성과 반대의 대립이 분명하게 나타나야 한다.\n○ 쟁점이 하나여야 한다.\n○ 찬성이나 반대 어느 한 편에 유리하게 작용하는 정서적 표현을 사용해서는 안 된다.",
                      num1Text: "징병제도는 유지해야 한다.",
                      num2Text: "정보통신망법을 개선할 수는 없다.",
                      num3Text: "야만적인 두발 제한을 폐지해야 한다.",
                      num4Text: "내신 제도와 논술 시험을 개혁해야 한다.",
                      answer: 1),
        QuestionModel(num: 3,
                      questionText: "다음 글에 대한 설명으로 옳지 않은 것은?",
                      reference: "해설자: (관객들에게 무대와 등장인물을 설명한다.) 이곳은 황야입니다. 이리 떼의 내습을 알리는 망루가 세워져 있죠. 드높이 솟은 이 망루는 하늘로 둘러싸여 있습니다. 하늘은 연극의 진행에 따라 황혼, 초승달이 뜬 밤, 그리고 아침으로 변할 겁니다. 저기 위를 바라보십시오. 파수꾼이 앉아 있습니다. 높은 곳에서 하늘을 등지고 있기 때문에 그는 언제나 시커먼 그림자로만 보입니다. 그는 내가 태어나기 전부터 파수꾼이었습니다. 나의 늙으신 아버지께서도 어린 시절에 저 유명한 파수꾼의 이야기를 들으셨다 합니다.\n\n－이강백, ｢파수꾼｣에서－",
                      num1Text: "공간적 배경은 망루가 세워져 있는 황야이다.",
                      num2Text: "시간적 배경은 연극의 진행에 따라 변한다.",
                      num3Text: "해설자는 무대 위의 아버지를 소개한다.",
                      num4Text: "파수꾼의 얼굴은 분명하게 알 수 없다.",
                      answer: 3),
        QuestionModel(num: 4,
                      questionText: "두 사람의 대화에 적용된 공감적 듣기의 방법이 아닌 것은?",
                      reference: "“수빈 씨, 나 처음 한 프레젠테이션인데 엉망이었어.”\n“정말? 무슨 일이 있었는지 자세히 말해 봐.”\n“너무 긴장해서 팀장님 질문에 대답을 못했어.”\n“팀장님 질문에 대답을 못했구나. 처음 하는 프레젠테이션이라 정아 씨가 긴장을 많이 했나 보다.”",
                      num1Text: "수빈은 정아의 말에 자신이 주의 집중하고 있음을 보여 주고 있다.",
                      num2Text: "수빈은 정아가 계속 말을 할 수 있도록 격려하고 있다.",
                      num3Text: "수빈은 정아의 혼란스러운 감정을 정아 스스로 정리하게끔 도와주고 있다.",
                      num4Text: "수빈은 정아의 말을 자신의 처지로 바꾸어 의미를 재구성하고 있다.",
                      answer: 4),
        QuestionModel(num: 5,
                      questionText: "국어의 주요한 음운 변동을 다음과 같이 유형화할 때, ‘부엌일’에 일어나는 음운 변동 유형으로 옳은 것은?",
                      reference: "㉠ XaY → XbY(교체)\n㉡ XY → XaY(첨가)\n㉢ XabY → XcY(축약)\n㉣ XaY → XY(탈락)",
                      num1Text: "㉠, ㉡",
                      num2Text: "㉠, ㉣",
                      num3Text: "㉡, ㉢",
                      num4Text: "㉡, ㉣",
                      answer: 1),
        QuestionModel(num: 6,
                      questionText: "토론자들의 말하기 방식에 대한 설명으로 적절한 것은?",
                      reference: "사회자:학교 폭력 문제가 나날이 심각해지고 있습니다. 이와 관련해 오늘은 ‘학교 폭력을 방관한 학생에게도 책임을 물어야 한다’를 주제로 토론을 해 보도록 하겠습니다. 먼저 찬성 측 말씀해 주시죠.\n\n찬성측:친구가 학교 폭력에 의해 희생되고 있는데도 자신에게 피해가 올까 두려워 아무런 조치를 취하지 않는 학생들이 많다고 합니다. 이러한 행동으로 인해 학교 폭력은 점점 확산되고 있습니다. 학교 폭력을 행하는 것을 목격했음에도 어떤 조치도 취하지 않은 것은 폭력에 대해 묵시적으로 동의한 것과 같습니다. 폭력을 직접 행사하는 행위뿐 아니라, 불의에 저항하지 않는 정의롭지 못한 행위에 대해서도 합당한 책임을 물어야 할 것입니다.\n\n사회자:다음으로 반대 측 의견 말씀해 주시죠.\n\n반대측:특정 학생에게 폭력을 직접 행사해서 피해를 준 사실이 명백할 때에만 책임을 물을 수 있을 것입니다. 또한 사건에 대한 개입과 방관은 개인의 자율적 의지에 달린 문제이므로 외부에서 규제할 성질의 문제가 아닙니다.\n\n사회자:그럼 이번에는 반대 측부터 찬성 측에 대해 반론해 주시지요.\n\n반대측:과연 누구까지를 학교 폭력의 방관자라고 규정지을 수 있을까요? 집에 가는 길에 우연히 폭력을 목격했을 경우, 자신의 친구로부터 폭력에 관련된 소문을 접했을 경우 등 방관자라고 규정하기에는 애매한 경우가 많습니다. 어떠한 행위를 처벌하려면 확고한 기준이 필요한데, 방관자의 범위부터 규정하기가 불명확하다고 볼 수 있습니다.\n\n찬성측:불의를 방관한 행위에 대해 사회가 책임을 묻지 않는다면 이후로도 사람들은 아무런 죄책감 없이 불의를 모른 체하고 방관할 것입니다. 결국 이는 사회 전체의 건전성과 도덕성을 떨어뜨릴 것이고, 정의에 근거한 시민의 고발정신까지 약화시킬 것입니다.",
                      num1Text: "찬성 측은 친숙한 상황을 빗대어 자신의 견해를 펼치고 있다.",
                      num2Text: "찬성 측은 자신의 경험을 제시하여 논지를 보충하고 있다.",
                      num3Text: "반대 측은 윤리적 방법으로 해결책을 제시하고 있다.",
                      num4Text: "반대 측은 논제에 의문을 제기하여 주장을 강화하고 있다.",
                      answer: 4),
        QuestionModel(num: 7,
                      questionText: "괄호 안에 들어갈 단어를 순서대로 바르게 나열한 것은?",
                      reference: "  한국 문학의 미적 범주에서 눈에 띄는 전통으로 풍자와 해학이 있다. 풍자와 해학은 주어진 상황에 순종하기보다 그것을 극복하고자 하는 건강한 삶의 의지에서 나온 ( ㉠ )을(를) 통해 드러난다. ( ㉠ )은(는) ‘있어야 할 것’으로 행세해 온 관념을 부정하고, 현실적인 삶인 ‘있는 것’을 그대로 긍정한다. 이때 있어야 할 것을 깨뜨리는 것에 관심을 집중한 것이 ( ㉡ )이고, 있는 것이 지닌 긍정에 관심을 집중하는 것이 ( ㉢ )이다.",
                      num1Text: "골계(滑稽) - 해학(諧謔) - 풍자(諷刺)",
                      num2Text: "해학(諧謔) - 풍자(諷刺) - 골계(滑稽)",
                      num3Text: "풍자(諷刺) - 해학(諧謔) - 골계(滑稽)",
                      num4Text: "골계(滑稽) - 풍자(諷刺) - 해학(諧謔)",
                      answer: 4),
        QuestionModel(num: 8,
                      questionText: "다음 글에서 <보기>가 들어가기에 가장 적절한 곳은?",
                      reference: "  아침기도는 간략한 아침 뉴스로, 저녁기도는 저녁 종합 뉴스로 바뀌었다.",
                      reference2: "  철학자 헤겔이 주장했듯이, 삶을 인도하는 원천이자 권위의 시금석으로서의 종교를 뉴스가 대체할 때 사회는 근대화된다. 선진 경제에서 뉴스는 이제 최소한 예전에 신앙이 누리던 것과 동등한 권력의 지위를 차지한다. 뉴스 타전은 소름이 돋을 정도로 정확하게 교회의 시간 규범을 따른다. ( ㉠ ) 뉴스는 우리가 한때 신앙심을 품었을 때와 똑같은 공손한 마음을 간직하고 접근하기를 요구하기도 한다. ( ㉡ ) 우리 역시 뉴스에서 계시를 얻기 바란다. ( ㉢ ) 누가 착하고 누가 악한지 알기를 바라고, 고통을 헤아려 볼 수 있기를 바라며, 존재의 이치가 펼쳐지는 광경을 이해하길 희망한다. ( ㉣ ) 그리고 이 의식에 참여하길 거부하는 경우 이단이라는 비난을 받기도 한다.",
                      num1Text: "㉠",
                      num2Text: "㉡",
                      num3Text: "㉢",
                      num4Text: "㉣",
                      answer: 1),
        QuestionModel(num: 9,
                      questionText: "㉠과 ㉡에 대한 설명으로 적절한 것은?",
                      reference: "헌 먼덕1) 숙여 쓰고 축 없는 짚신에 설피설피 물러오니\n풍채 적은 형용에 ㉠"+"개".underLined+" 짖을 뿐이로다\n와실(蝸室)에 들어간들 잠이 와서 누었으랴\n북창(北窓)을 비겨 앉아 새벽을 기다리니\n무정한 ㉡"+"대승(戴勝)2)".underLined+"은 이내 한을 돋우도다\n종조(終朝) 추창(惆悵)3)하며 먼 들을 바라보니\n즐기는 농가(農歌)도 흥 없이 들리나다\n세정(世情) 모르는 한숨은 그칠 줄을 모르도다\n\n－박인로, ｢누항사(陋巷詞)｣에서－\n\n1)먼덕: 짚으로 만든 모자\n2)대승(戴勝): 오디새\n3)추창(惆悵): 슬퍼하는 모습",
                      num1Text: "㉠은 실재하는 존재물이고, ㉡은 상상적 허구물이다.",
                      num2Text: "㉠은 화자의 절망을 나타내고, ㉡은 화자의 희망을 나타낸다.",
                      num3Text: "㉠은 화자의 내면을 상징하고, ㉡은 화자의 외양을 상징한다.",
                      num4Text: "㉠은 화자의 초라함을 부각시키고, ㉡은 화자의 수심을 깊게 한다.",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "화자의 상황을 적절하게 표현한 한자 성어는?",
                      reference: "미인이 잠에서 깨어 새 단장을 하는데\n향기로운 비단, 보배 띠에 원앙이 수놓였네\n겹발을 비스듬히 걷으니 비취새가 보이는데\n게으르게 은 아쟁을 안고 봉황곡을 연주하네\n금 재갈, 꾸민 안장은 어디로 떠났는가?\n다정한 앵무새는 창가에서 지저귀네\n풀섶에 놀던 나비는 뜰 밖으로 사라지고\n꽃잎에 가리운 거미줄은 난간 너머에서 춤추네\n뉘 집의 연못가에서 풍악 소리 울리는가?\n달빛은 금 술잔에 담긴 좋은 술을 비추네\n시름겨운 이는 외로운 밤에 잠 못 이루는데\n새벽에 일어나니 비단 수건에 눈물이 흥건하네\n\n－허난설헌, ｢사시사(四時詞)｣에서－",
                      num1Text: "琴瑟之樂",
                      num2Text: "輾轉不寐",
                      num3Text: "錦衣夜行",
                      num4Text: "麥秀之嘆",
                      answer: 2),
        QuestionModel(num: 11,
                      questionText: "다음 글의 괄호 안에 들어갈 문장으로 적절한 것은?",
                      reference: "  국어의 높임법에는 말하는 이가 듣는 이에 대하여 높이거나 낮추어 말하는 상대 높임법, 서술어의 주체를 높이는 주체 높임법, 서술어의 객체를 높이는 객체 높임법 등이 있다. 이러한 높임 표현은 한 문장에서 복합적으로 실현되기도 하는데, (                    )의 경우 대화의 상대, 서술어의 주체, 서술어의 객체를 모두 높인 표현이다.",
                      num1Text: "아버지께서 할머니를 모시고 댁에 들어가셨다.",
                      num2Text: "제가 어머니께 그렇게 말씀을 드리면 될까요?",
                      num3Text: "어머니께서 아주머니께 이 김치를 드리라고 하셨습니다.",
                      num4Text: "주민 여러분께서는 잠시만 제 이야기에 귀를 기울여 주시기 바랍니다.",
                      answer: 3),
        QuestionModel(num: 12,
                      questionText: "다음 글의 특징으로 적절하지 않은 것은?",
                      reference: "가리워진 안개를 걷게 하라,\n국경이며 탑이며 어용학(御用學)의 울타리며\n죽 가래 밀어 바다로 몰아 넣라.\n\n하여 하늘을 흐르는 날새처럼\n한 세상 한 바람 한 햇빛 속에,\n만 가지와 만 노래를 한 가지로 흐르게 하라.\n\n보다 큰 집단은 보다 큰 체계를 건축하고,\n보다 큰 체계는 보다 큰 악을 양조(釀造)한다.\n\n조직은 형식을 강요하고\n형식은 위조품을 모집한다.\n\n하여, 전통은 궁궐안의 상전이 되고\n조작된 권위는 주위를 침식한다.\n\n국경이며 탑이며 일만년 울타리며\n죽 가래 밀어 바다로 몰아 넣라.\n\n－신동엽, ｢이야기하는 쟁기꾼의 대지｣에서－",
                      num1Text: "직설적인 어조로써 메시지를 전달하고 있다.",
                      num2Text: "고전적인 질서를 통해 새로운 희망을 추구하고 있다.",
                      num3Text: "인위적인 것과 자연적인 것이 대조적으로 제시되고 있다.",
                      num4Text: "농기구의 상징을 통해 체제 개혁을 역설하고 있다.",
                      answer: 2),
        QuestionModel(num: 13,
                      questionText: "㉠～㉣ 중 서술자가 개입되어 있지 않은 것은?",
                      reference: "이때 춘향이는 사령이 오는지 군노가 오는지 모르고 주야로 도련님을 생각하여 우는데, ㉠"+"생각지 못할 우환을 당하려 하니 소리가 화평할 수 있겠는가.".underLined+" 한때나마 빈방살이 할 계집아이라 목소리에 청승이 끼어 자연히 슬픈 애원성이 되니 ㉡"+"보고 듣는 사람의 심장인들 아니 상할 것인가.".underLined+" 임 그리워 서러운 마음 밥맛없어 밥 못 먹고 불안한 잠자리에 잠 못 자고 도련님 생각으로 상처가 쌓여 피골이 상접하고 양기가 쇠진하여 진양조 울음이 되어 노래를 부른다. 갈까 보다 갈까 보다, 임을 따라 갈까 보다. 천 리라도 갈까 보다. 만 리라도 갈까 보다. 바람도 쉬어 넘고 수진이 날진이 해동청 보라매도 쉬어 넘는 높은 고개 동선령 고개라도 임이 와 날 찾으면 신발 벗어 손에 들고 아니 쉬고 달려가리. ㉢"+"한양 계신 우리 낭군 나와 같이 그리워하는가, 무정하여 아주 잊고 나의 사랑 옮겨다가 다른 임을 사랑하는가?".underLined+" ㉣"+"이렇게 한참을 서럽게 울 때 사령 등이 춘향의 슬픈 목소리를 들으니 목석이라도 어찌 감동을 받지 않겠는가?".underLined+" 봄눈 녹듯 온몸에 맥이 탁 풀렸다.\n\n－작자 미상, ｢춘향전｣에서－",
                      num1Text: "㉠",
                      num2Text: "㉡",
                      num3Text: "㉢",
                      num4Text: "㉣",
                      answer: 3),
        QuestionModel(num: 14,
                      questionText: "다음 글에 대한 설명으로 옳지 않은 것은?",
                      reference: "  동네 사람들이 방앗간의 터진 두 면을 둘러쌌다. 그리고 방앗간 속을 들여다보았다. 과연 어둠 속에 움직이는 게 있었다. 그리고 그게 어둠 속에서도 흰 짐승이라는 걸 알 수 있었다. 분명히 그놈의 신둥이개다. 동네 사람들은 한 걸음 한 걸음 죄어들었다. 점점 뒤로 움직여 쫓기는 짐승의 어느 한 부분에 불이 켜졌다. 저게 산개의 눈이다. 동네 사람들은 몽둥이 잡은 손에 힘을 주었다. 이 속에서 간난이 할아버지도 몽둥이 잡은 손에 힘을 주었다. 한 걸음 더 죄어들었다. 눈앞의 새파란 불이 빠져나갈 틈을 엿보듯이 휙 한 바퀴 돌았다. 별나게 새파란 불이었다. 문득 간난이 할아버지는 이런 새파란 불이란 눈앞에 있는 신둥이개 한 마리의 몸에서 나오는 것이 아니고 여럿의 몸에서 나오는 것이 합쳐진 것이라는 생각이 들었다. 말하자면 지금 이 신둥이개의 뱃속에 든 새끼의 몫까지 합쳐진 것이라는. 그러자 간난이 할아버지의 가슴속을 흘러 지나가는 게 있었다. 짐승이라도 새끼 밴 것을 차마?\n  이때에 누구의 입에선가, 때레라! 하는 고함 소리가 나왔다. 다음 순간 간난이 할아버지의 양옆 사람들이 욱 개를 향해 달려들며 몽둥이를 내리쳤다. 그와 동시에 간난이 할아버지는 푸른 불꽃이 자기 다리 곁을 빠져나가는 것을 느꼈다.\n  뒤이어 누구의 입에선가, 누가 빈틈을 냈어? 하는 흥분에 찬 목소리가 들렸다. 그리고 저마다, 거 누구야? 거 누구야? 하고 못마땅해 하는 말소리 속에 간난이 할아버지 턱밑으로 디미는 얼굴이 있어,\n “아즈반이웨다레”\n  하는 것은 동장네 절가였다.\n\n－황순원, ｢목넘이 마을의 개｣에서－",
                      num1Text: "토속적이면서도 억센 삶의 현장을 그리고 있다.",
                      num2Text: "신둥이의 새파란 불은 생의 욕구를 암시한다.",
                      num3Text: "간난이 할아버지에게서 생명에 대한 외경을 느낄 수 있다.",
                      num4Text: "동장네 절가는 간난이 할아버지의 행동에 동조하고 있다.",
                      answer: 4),
        QuestionModel(num: 15,
                      questionText: "(가)와 (나)를 통해서 추정하기 어려운 내용은?",
                      reference: "(가)찬성공 형제께서 정경부인의 상(喪)을 당하였다. 부윤공의 부인 이 씨가 우연히 언문 소설을 읽다가 그 소리가 밖으로 들렸다. 찬성공이 기뻐하지 않으며 제수를 계단 아래에 서게 하고, “부녀자의 무식을 심하게 책망할 필요는 없지만, 어찌 상중(喪中)에 있으면서 예의에 어긋난 책을 소리 내어 읽어서 스스로 평민과 같아지려 할 수 있는가?” 하고 꾸짖었다.\n\n(나)전기수: 늙은이가 동문 밖에 살면서 입으로 언문 소설을 읽었는데, ｢숙향전｣, ｢소대성전｣, ｢심청전｣, ｢설인귀전｣과 같은 전기소설이었다.…잘 읽었기 때문에 옆에서 구경하는 사람들이 빙 둘러섰다. 가장 재미있고 긴요하여 매우 들을 만한 구절에 이르면 갑자기 침묵하고 소리를 내지 않았다. 사람들이 다음 이야기를 듣고 싶어서 다투어 돈을 던졌다. 이를 바로 ‘요전법(돈을 요구하는 법)’이라 한다.",
                      num1Text: "상층 남성들은 상중의 예법에 대해 매우 엄격하였다.",
                      num2Text: "혼자 소설을 보면서 소리 내어 읽기도 하였다.",
                      num3Text: "하층에서도 소설을 창작하는 사람이 많았다.",
                      num4Text: "상층이 아닌 하층에서도 소설을 즐겼다.",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "다음 글의 글쓰기 전략으로 볼 수 없는 것은?",
                      reference: "  고전파 음악은 어떤 음악인가? 서양 음악의 뿌리는 종교 음악에서 비롯되었다. 바로크 시대까지는 음악이 종교에 예속되어 있었으며, 음악가들 또한 종교에 예속되어 있었다. 고전파는 이렇게 종교에 예속되었던 음악을, 음악을 위한 음악으로 정립하려는 예술 운동에서 출발하였다. 따라서 종래의 신을 위한 음악에서 탈피해 형식과 내용의 일체화를 꾀하고 균형 잡힌 절대 음악을 추구하였다. 즉 ‘신’보다는 ‘사람’을 위한 음악, ‘음악’을 위한 음악을 이루어 나가겠다는 굳은 결의를 보여 준 것이다.\n  또한 고전파 음악은 음악적 형식과 내용의 완숙을 이룬 음악이기도 하다. 이 시기에는 하이든, 모차르트, 베토벤 등 음악의 역사에서 가장 위대한 작곡가들이 배출되기도 하였다. 이때에는 성악이 아닌 기악만으로도 음악이 가능하게 되었으며, 교향곡의 기본을 이루는 소나타 형식이 완성되었다. 특히 옛 그리스나 로마 때처럼 보다 정돈된 형식을 가진 음악을 해 보자고 주장하였기에 ‘옛것에서 배우자는 의미의 고전’과 ‘청정하고 우아하며 흐림 없음, 최고의 예술적 경지에 다다름으로서의 고전’을 모두 지향하게 되었다.\n  이렇듯 역사적으로 고전파 음악은 종교의 영역에서 음악 자체의 영역을 확보하였으며 최고 수준의 음악적 내용과 형식을 수립하였다. 고전파 음악이 서양 전통 음악 전체를 대표하게 된 것은 고전파 음악이 이룩한 역사적인 성과에서 비롯된 것일지도 모른다. 따라서 고전 음악의 개념을 이해하기 위해서는 고전파 음악의 성격과 특질에 대한 이해가 선행되어야 할 것이다.",
                      num1Text: "고전파 음악이 지닌 음악사적 의의를 밝힌다.",
                      num2Text: "고전파 음악의 음악가를 예시하여 이해를 돕는다.",
                      num3Text: "고전파 음악의 특징이 형식과 내용의 분리에 있음을 강조한다.",
                      num4Text: "질문을 통해 화제를 제시함으로써 호기심을 유발한다.",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "(가)를 바탕으로 (나)에 담긴 글쓴이의 생각을 적절히 추론한 것은?",
                      reference: "(가)철학사에서 합리론의 전통은 감각에 대해 매우 비판적이었다. 예컨대 플라톤은 감각이 보여 주는 세계를 끊임없이 변화하는, 전적으로 불안정한 세계로 간주하고 이에 근거하여 지식을 얻는 것은 불가능하다고 생각했다. 반대로 경험론자들은 우리의 모든 관념과 판단은 감각 경험에서 출발한다고 주장하면서 어떤 지식도 절대적으로 확실할 수는 없다고 결론짓는다.\n\n(나)모든 사람은 착시 현상 등을 경험해 본 적이 있기에 감각이 우리를 속일 수 있다는 것을 분명히 알고 있고 감각에 대한 어느 정도의 경계심을 지니고 있다. 하지만 그렇다고 해서 일상생활에서 자신의 감각을 신뢰하고 이에 따라 행동하는 것은 잘못이 아니다. 모든 감각적 정보를 검증 절차를 거친 후 받아들이다가는 정상적 생활을 영위하는 것 자체가 불가능해질 것이기 때문이다. 반대로, 실용적 기술 개발이나 평범한 일상적 행동과는 달리 과학적 연구는 상당한 정도의 정확성을 요구하므로 경험적 자료에 대해 어느 정도의 경계심을 유지하는 것도 당연하다.",
                      num1Text: "실용적 기술을 개발하는 것은 일차적으로 경험론적 사고에 토대를 둔다.",
                      num2Text: "세계는 끊임없이 변화하므로 일상생활에서는 합리론적 사고를 우선하여야 한다.",
                      num3Text: "과학 연구는 합리론을 버리고 철저히 경험론을 바탕으로 이루어져야 한다.",
                      num4Text: "감각에 대한 신뢰는 어느 분야에나 전적으로 차별 없이 요구된다.",
                      answer: 1),
        QuestionModel(num: 18,
                      questionText: "다음 글에 대한 설명으로 적절하지 않은 것은?",
                      reference: "  믿기 어렵겠지만 자장면 문화와 미국의 피자 문화는 닮은 점이 많다. 젊은 청년들이 오토바이를 타고 배달한다는 점에서 참으로 닮은꼴이다. 이사한다고 짐을 내려놓게 되면 주방 기구들이 부족하게 되고 이때 자장면은 참으로 편리한 해결책이다. 미국에서의 피자도 마찬가지다. 갑자기 아이들의 친구들이 많이 몰려왔을 때 피자는 참으로 편리한 음식이다.\n  남자들이 군에 가 훈련을 받을 때 비라도 추적추적 오게 되면 자장면 생각이 제일 많이 난다고 한다. 비가 오는 바깥을 보며 따뜻한 방에서 입에 자장을 묻히는 장면은 정겨울 수밖에 없다. 프로 농구 원년에 수입된 미국 선수들은 하루도 빠지지 않고 피자를 시켜 먹었다고 한다. 음식이 맞지 않는 탓도 있겠지만 향수를 달래고자 함이 아닐까?\n  싸게 먹을 수 있는 이국 음식이란 점에서 자장면과 피자는 특별한 의미를 갖는다. 외식을 하기엔 부담되고 한번쯤 식단을 바꾸어 보고 싶을 즈음이면 중국식 자장면이나 이탈리아식 피자는 한국이나 미국의 서민에겐 안성맞춤이다. 그런데 한국에서나 미국에서나 변화가 생기기 시작했다. 한국에서는 피자 배달이 보편화되기 시작했다. 피자를 간식이 아닌 주식으로 삼고자 하는 아이들도 생겼다. 졸업식을 마치고 중국집으로 향하던 발걸음들이 이제 피자집으로 돌려졌다. 피자보다 자장면을 좋아하는 아이들을 찾아보기가 힘들어졌다.",
                      num1Text: "피자는 쉽게 배달시켜 먹을 수 있는 편리한 음식이다.",
                      num2Text: "자장면과 피자는 이국적인 음식이다.",
                      num3Text: "자장면과 피자는 값이 싸면서도 기분 전환이 되는 음식이다.",
                      num4Text: "자장면은 특별한 날에 어린이들에게 여전히 가장 사랑받는 음식이다.",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "글의 내용을 구체적으로 설명하기 위한 예로 적절하지 않은 것은?",
                      reference: "  하나의 개념에 두 개 이상의 단어가 필요한 것은 아니다. 따라서 동의어는 서로 경쟁을 통해 하나가 없어지거나 각기 다른 의미 영역을 확보하는 등의 다양한 양상을 보인다. 현실 언어에서 동의어로 공존하면서 경쟁을 계속하는 경우가 있으며, 한쪽은 살아남고 다른 쪽은 소멸하는 경우가 있다. 동의 충돌의 결과 의미 영역이 바뀌는 경우도 있다. 이는 의미 축소, 의미 확대, 의미 교체 등으로 구분된다.",
                      num1Text: "‘가을걷이’와 ‘추수’는 공존하며 경쟁하고 있다.",
                      num2Text: "‘말미’는 쓰지 않고 ‘휴가’라는 말을 사용하고 있다.",
                      num3Text: "‘얼굴’은 ‘형체’의 뜻에서 ‘안면’의 뜻으로 의미가 축소되었다.",
                      num4Text: "‘겨레’는 ‘친척’의 뜻에서 ‘민족’의 뜻으로 의미가 확대되었다.",
                      answer: 2),
        QuestionModel(num: 20,
                      questionText: "다음 글에 대한 설명으로 적절하지 않은 것은?",
                      reference: "(가)20세기 들어서 생태학자들은 지속성 농약이 자연 생태계에 어떤 악영향을 미치는지를 밝힐 수 있었다. 예컨대 제2차 세계대전 이후 전 세계에서 해충 구제용으로 널리 사용됨으로써 농업 생산량 향상에 커다란 기여를 한 디디티(DDT)는 유기 염소계 살충제의 대명사이다.\n\n(나)그렇지만 이 유기 염소계 살충제는 물에 잘 녹지 않고 자연에서 햇빛에 의한 광분해나 미생물에 의한 생물학적 분해가 거의 이루어지지 않는다. 그래서 디디티는 토양이나 물속의 퇴적물 속에 수십 년간 축적된다. 게다가 디디티는 지방에는 잘 녹아서 먹이사슬을 거치는 동안 지방 함량이 높은 동물 체내에 그 농도가 높아진다. 이렇듯 많은 양의 유기 염소계 살충제를 체내에 축적하게 된 맹금류는 물질대사에 장애를 일으켜서 껍질이 매우 얇은 알을 낳기 때문에, 포란 중 대부분의 알이 깨져 버려 멸종의 길을 걷게 된다.\n\n(다)디디티는 쉽게 분해되지 않기 때문에 한번 뿌려진 디디티는 물과 공기, 생물체 등을 매개로 세계 전역으로 퍼질 수 있다. 그래서 디디티에 한 번도 노출된 적이 없는 알래스카 지방의 에스키모 산모의 젖에서도 디디티가 검출되었고, 남극 지방의 펭귄 몸속에서도 디디티가 발견되었다. 이러한 생물 농축과 잔존성의 특성이 밝혀짐으로써 미국에서는 1972년부터 디디티 생산이 전면 중단되었고, 1980년대에 이르러서는 유기 염소계 농약의 사용이 대부분 금지되었다.\n\n(라)이와 같이 디디티의 생물 농축 현상에서처럼 생태학자들은 한 생물 종에 미치는 오염의 영향이 오랫동안 누적되면 전체 생태계를 훼손시킬 수 있다는 사실을 발견하였다. 그래서인지 최근 우리나라에서도 사소한 환경오염 행위가 장차 어떠한 재앙을 몰고 올 수 있는지에 대한 연구가 활발히 이루어지고 있다.",
                      num1Text: "(가)는 중심 화제를 소개하고, 핵심어를 제시함으로써 전개될 내용을 암시하고 있다.",
                      num2Text: "(나)는 디디티가 끼칠 생태계의 영향을 인과 분석의 방법으로 설명하고 있다.",
                      num3Text: "(다)는 디디티의 악영향을 제시하고, 그것의 사용 금지를 주장하고 있다.",
                      num4Text: "(라)는 환경오염에 대한 경각심을 암시적으로 드러내고 있다.",
                      answer: 3),
        ]
        let exam = ExamModel(id: 201911, year: 2019, examTypeID: "국가직", subjectID: "국어", questions: questions)
        exam2019.append(exam)
    }
    func saveExam201912() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오. [1~2]",
                      reference: "Natural Gas World subscribers will receive accurate and reliable key facts and figures about what is going on in the industry, so they are fully able to "+"discern".underLined+" what concerns their business.",
                      num1Text: "distinguish",
                      num2Text: "strengthen",
                      num3Text: "undermine",
                      num4Text: "abandon",
                      answer: 1),
        QuestionModel(num: 2,
                      questionText: "",
                      reference: "Ms. West, the winner of the silver in the women's 1,500m event, "+"stood out".underLined+" through the race.",
                      num1Text: "was overwhelmed",
                      num2Text: "was impressive",
                      num3Text: "was depressed",
                      num4Text: "was optimistic",
                      answer: 2),
        QuestionModel(num: 3,
                      questionText: "두 사람의 대화 중 가장 어색한 것은?",
                      num1Text: "A: I'm traveling abroad, but I'm not used to staying in another country.\nB: Don't worry. You'll get accustomed to it in no time.",
                      num2Text: "A: I want to get a prize in the photo contest.\nB: I'm sure you will. I'll keep my fingers crossed!",
                      num3Text: "A: My best friend moved to Sejong City. I miss her so much.\nB: Yeah. I know how you feel.",
                      num4Text: "A: Do you mind if I talk to you for a moment?\nB: Never mind. I'm very busy right now.",
                      answer: 4),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "A: Would you like to try some dim sum?\nB: Yes, thank you. They look delicious. What's inside?\nA: These have pork and chopped vegetables, and those have shrimps.\nB: And, um, ________________________?\nA: You pick one up with your chopsticks like this and dip it into the sauce. It's easy.\nB: Okay. I'll give it a try.",
                      num1Text: "how much are they",
                      num2Text: "how do I eat them",
                      num3Text: "how spicy are they",
                      num4Text: "how do you cook them",
                      answer: 2),
        QuestionModel(num: 5,
                      questionText: "우리말을 영어로 잘못 옮긴 것을 고르시오. [5~6]",
                      num1Text: "제가 당신께 말씀드렸던 새로운 선생님은 원래 페루 출신입니다.\n→ The new teacher I told you about is originally from Peru.",
                      num2Text: "나는 긴급한 일로 자정이 5분이나 지난 후 그에게 전화했다.\n→ I called him five minutes shy of midnight on an urgent matter.",
                      num3Text: "상어로 보이는 것이 산호 뒤에 숨어 있었다.\n→ What appeared to be a shark was lurking behind the coral reef.",
                      num4Text: "그녀는 일요일에 16세의 친구와 함께 산 정상에 올랐다.\n→ She reached the mountain summit with her 16-year-old friend on Sunday.",
                      answer: 2),
        QuestionModel(num: 6,
                      questionText: "",
                      num1Text: "개인용 컴퓨터를 가장 많이 가지고 있는 나라는 종종 바뀐다.\n→ The country with the most computers per person changes from time to time.",
                      num2Text: "지난여름 나의 사랑스러운 손자에게 일어난 일은 놀라웠다.\n→ What happened to my lovely grandson last summer was amazing",
                      num3Text: "나무 숟가락은 아이들에게 매우 좋은 장난감이고 플라스틱 병 또한 그렇다.\n→ Wooden spoons are excellent toys for children, and so are plastic bottles.",
                      num4Text: "나는 은퇴 후부터 내내 이 일을 해 오고 있다.\n→ I have been doing this work ever since I retired.",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "밑줄 친 부분 중 어법상 옳지 않은 것을 고르시오. [7~8]",
                      reference: "Domesticated animals are the earliest and most effective 'machines' ①"+"available".underLined+" to humans. They take the strain off the human back and arms. ②"+"Utilizing".underLined+" with other techniques, animals can raise human living standards very considerably, both as supplementary foodstuffs (protein in meat and milk) and as machines ③"+"to carry".underLined+" burdens, lift water, and grind grain. Since they are so obviously ④"+"of".underLined+" great benefit, we might expect to find that over the centuries humans would increase the number and quality of the animals they kept. Surprisingly, this has not usually been the case.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 2),
        QuestionModel(num: 8,
                      questionText: "",
                      reference: "A myth is a narrative that embodies―and in some cases ①"+"helps to explain".underLined+"―the religious, philosophical, moral, and political values of a culture. Through tales of gods and supernatural beings, myths ②"+"try to make".underLined+" sense of occurrences in the natural world. Contrary to popular usage, myth does not mean “falsehood.” In the broadest sense, myths are stories―usually whole groups of stories―③"+"that can be".underLined+" true or partly true as well as false; regardless of their degree of accuracy, however, myths frequently express the deepest beliefs of a culture. According to this definition, the Iliad and the Odyssey, the Koran, and the Old and New Testaments can all ④"+"refer to as".underLined+" myths.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 9,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "Mapping technologies are being used in many new applications. Biological researchers are exploring the molecular structure of DNA (“mapping the genome”), geophysicists are mapping the structure of the Earth's core, and oceanographers are mapping the ocean floor. Computer games have various imaginary “lands” or levels where rules, hazards, and rewards change. Computerization now challenges reality with “virtual reality,” artificial environments that stimulate special situations, which may be useful in training and entertainment. Mapping techniques are being used also in the realm of ideas. For example, relationships between ideas can be shown using what are called concept maps. Starting from a general or “central” idea, related ideas can be connected, building a web around the main concept. This is not a map by any traditional definition, but the tools and techniques of cartography are employed to produce it, and in some ways it resembles a map.",
                      num1Text: "Computerized Maps vs. Traditional Maps",
                      num2Text: "Where Does Cartography Begin?",
                      num3Text: "Finding Ways to DNA Secrets",
                      num4Text: "Mapping New Frontiers",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "다음 글의 요지로 가장 적절한 것은?",
                      reference: "When giving performance feedback, you should consider the recipient's past performance and your estimate of his or her future potential in designing its frequency, amount, and content. For high performers with potential for growth, feedback should be frequent enough to prod them into taking corrective action, but not so frequent that it is experienced as controlling and saps their initiative. For adequate performers who have settled into their jobs and have limited potential for advancement, very little feedback is needed because they have displayed reliable and steady behavior in the past, knowing their tasks and realizing what needs to be done. For poor performers―that is, people who will need to be removed from their jobs if their performance doesn't improve―feedback should be frequent and very specific, and the connection between acting on the feedback and negative sanctions such as being laid off or fired should be made explicit.",
                      num1Text: "Time your feedback well.",
                      num2Text: "Customize negative feedback.",
                      num3Text: "Tailor feedback to the person.",
                      num4Text: "Avoid goal-oriented feedback.",
                      answer: 3),
        QuestionModel(num: 11,
                      questionText: "다음 글의 내용과 일치하지 않는 것은?",
                      reference: "Langston Hughes was born in Joplin, Missouri, and graduated from Lincoln University, in which many African-American students have pursued their academic disciplines. At the age of eighteen, Hughes published one of his most well-known poems, “Negro Speaks of Rivers.” Creative and experimental, Hughes incorporated authentic dialect in his work, adapted traditional poetic forms to embrace the cadences and moods of blues and jazz, and created characters and themes that reflected elements of lower-class black culture. With his ability to fuse serious content with humorous style, Hughes attacked racial prejudice in a way that was natural and witty.",
                      num1Text: "Hughes는 많은 미국 흑인들이 다녔던 대학교를 졸업하였다.",
                      num2Text: "Hughes는 실제 사투리를 그의 작품에 반영하였다.",
                      num3Text: "Hughes는 하층 계급 흑인들의 문화적 요소를 반영한 인물을 만들었다.",
                      num4Text: "Hughes는 인종편견을 엄숙한 문체로 공격하였다.",
                      answer: 4),
        QuestionModel(num: 12,
                      questionText: "밑줄 친 부분 중 글의 흐름상 가장 어색한 것은?",
                      reference: "In 2007, our biggest concern was too “big to fail.” Wall Street banks had grown to such staggering sizes, and had become so central to the health of the financial system, that no rational government could ever let them fail. ①"+"Aware of their protected status, banks made excessively risky bets on housing markets and invented ever more complicated derivatives.".underLined+" ②"+"New virtual currencies such as bitcoin and ethereum have radically changed our understanding of how money can and should work.".underLined+" ③"+"The result was the worst financial crisis since the breakdown of our economy in 1929.".underLined+" ④"+"In the years since 2007, we have made great progress in addressing the too-big-to-fail dilemma.".underLined+" Our banks are better capitalized than ever. Our regulators conduct regular stress tests of large institutions.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 2),
        QuestionModel(num: 13,
                      questionText: "다음 글의 주제로 가장 적절한 것은?",
                      reference: "Imagine that two people are starting work at a law firm on the same day. One person has a very simple name. The other person has a very complex name. We've got pretty good evidence that over the course of their next 16 plus years of their career, the person with the simpler name will rise up the legal hierarchy more quickly. They will attain partnership more quickly in the middle parts of their career. And by about the eighth or ninth year after graduating from law school the people with simpler names are about seven to ten percent more likely to be partners―which is a striking effect. We try to eliminate all sorts of other alternative explanations. For example, we try to show that it's not about foreignness because foreign names tend to be harder to pronounce. But even if you look at just white males with Anglo-American names―so really the true in-group, you find that among those white males with Anglo names they are more likely to rise up if their names happen to be simpler. So simplicity is one key feature in names that determines various outcomes.",
                      num1Text: "the development of legal names",
                      num2Text: "the concept of attractive names",
                      num3Text: "the benefit of simple names",
                      num4Text: "the roots of foreign names",
                      answer: 3),
        QuestionModel(num: 14,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오. [14~15]",
                      reference: "Schooling is "+"compulsory".underLined+" for all children in the United States, but the age range for which school attendance is required varies from state to state.",
                      num1Text: "complementary",
                      num2Text: "systematic",
                      num3Text: "mandatory",
                      num4Text: "innovative",
                      answer: 3),
        QuestionModel(num: 15,
                      questionText: "",
                      reference: "Although the actress experienced much turmoil in her career, she never "+"disclosed".underLined+" to anyone that she was unhappy.",
                      num1Text: "let on",
                      num2Text: "let off",
                      num3Text: "let up",
                      num4Text: "let down",
                      answer: 1),
        QuestionModel(num: 16,
                      questionText: "밑줄 친 (A), (B)에 들어갈 말로 가장 적절한 것은?",
                      reference: "Visionaries are the first people in their industry segment to see the potential of new technologies. Fundamentally, they see themselves as smarter than their opposite numbers in competitive companies―and, quite often, they are. Indeed, it is their ability to see things first that they want to leverage into a competitive advantage. That advantage can only come about if no one else has discovered it. They do not expect,    (A)   , to be buying a well-tested product with an extensive list of industry references. Indeed, if such a reference base exists, it may actually turn them off, indicating that for this technology, at any rate, they are already too late. Pragmatists,    (B)   , deeply value the experience of their colleagues in other companies. When they buy, they expect extensive references, and they want a good number to come from companies in their own industry segment.",
                      num1Text: "therefore  -  on the other hand",
                      num2Text: "howeverin  -  addition",
                      num3Text: "nonethelessat  -  the same time",
                      num4Text: "furthermore  -  in conclusion",
                      answer: 1),
        QuestionModel(num: 17,
                      questionText: "주어진 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "Some of these ailments are short-lived; others may be long-lasting.",
                      reference2: "For centuries, humans have looked up at the sky and wondered what exists beyond the realm of our planet. ( ① ) Ancient astronomers examined the night sky hoping to learn more about the universe. More recently, some movies explored the possibility of sustaining human life in outer space, while other films have questioned whether extraterrestrial life forms may have visited our planet. ( ② ) Since astronaut Yuri Gagarin became the first man to travel in space in 1961, scientists have researched what conditions are like beyond the Earth's atmosphere, and what effects space travel has on the human body. ( ③ ) Although most astronauts do not spend more than a few months in space, many experience physiological and psychological problems when they return to the Earth. ( ④ ) More than two-thirds of all astronauts suffer from motion sickness while traveling in space. In the gravity-free environment, the body cannot differentiate up from down. The body's internal balance system sends confusing signals to the brain, which can result in nausea lasting as long as a few days.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "Why bother with the history of everything? _______________________________________. In literature classes you don't learn about genes; in physics classes you don't learn about human evolution. So you get a partial view of the world. That makes it hard to find meaning in education. The French sociologist Emile Durkheim called this sense of disorientation and meaninglessness anomie, and he argued that it could lead to despair and even suicide. The German sociologist Max Weber talked of the “disenchantment” of the world. In the past, people had a unified vision of their world, a vision usually provided by the origin stories of their own religious traditions. That unified vision gave a sense of purpose, of meaning, even of enchantment to the world and to life. Today, though, many writers have argued that a sense of meaninglessness is inevitable in a world of science and rationality. Modernity, it seems, means meaninglessness.",
                      num1Text: "In the past, the study of history required disenchantment from science",
                      num2Text: "Recently, science has given us lots of clever tricks and meanings",
                      num3Text: "Today, we teach and learn about our world in fragments",
                      num4Text: "Lately, history has been divided into several categories",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "다음 글의 내용과 일치하지 않는 것은?",
                      reference: "The earliest government food service programs began around 1900 in Europe. Programs in the United States date from the Great Depression, when the need to use surplus agricultural commodities was joined to concern for feeding the children of poor families. During and after World War II, the explosion in the number of working women fueled the need for a broader program. What was once a function of the family―providing lunch―was shifted to the school food service system. The National School Lunch Program is the result of these efforts. The program is designed to provide federally assisted meals to children of school age. From the end of World War II to the early 1980s, funding for school food service expanded steadily. Today it helps to feed children in almost 100,000 schools across the United States. Its first function is to provide a nutritious lunch to all students; the second is to provide nutritious food at both breakfast and lunch to underprivileged children. If anything, the role of school food service as a replacement for what was once a family function has been expanded.",
                      num1Text: "The increase in the number of working women boosted the expansion of food service programs.",
                      num2Text: "The US government began to feed poor children during the Great Depression despite the food shortage.",
                      num3Text: "The US school food service system presently helps to feed children of poor families.",
                      num4Text: "The function of providing lunch has been shifted from the family to schools.",
                      answer: 2),
        QuestionModel(num: 20,
                      questionText: "주어진 문장 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "South Korea boasts of being the most wired nation on earth.",
                      reference2: "(A) This addiction has become a national issue in Korea in recent years, as users started dropping dead from exhaustion after playing online games for days on end. A growing number of students have skipped school to stay online, shockingly self-destructive behavior in this intensely competitive society.\n\n(B) In fact, perhaps no other country has so fully embraced the Internet.\n\n(C) But such ready access to the Web has come at a price as legions of obsessed users find that they cannot tear themselves away from their computer screens.",
                      num1Text: "(A)－(B)－(C)",
                      num2Text: "(A)－(C)－(B)",
                      num3Text: "(B)－(A)－(C)",
                      num4Text: "(B)－(C)－(A)",
                      answer: 4),
        
        ]
        let exam = ExamModel(id: 201912, year: 2019, examTypeID: "국가직", subjectID: "영어", questions: questions)
        exam2019.append(exam)
    }
    func saveExam201913() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "청동기시대의 유적과 유물에 대한 설명으로 옳은 것은?",
                      num1Text: "연천 전곡리에서는 사냥도구인 주먹도끼가 출토되었다.",
                      num2Text: "창원 다호리에서는 문자를 적는 붓이 출토되었다.",
                      num3Text: "강화 부근리에서는 탁자식 고인돌이 발견되었다.",
                      num4Text: "서울 암사동에서는 곡물을 담는 빗살무늬토기가 나왔다.",
                      answer: 3),
        QuestionModel(num: 2,
                      questionText: "(가), (나)의 나라에 대한 설명으로 옳은 것은?",
                      reference: "(가)음력 12월에 지내는 제천행사가 있는데, 이를 영고라고 한다. 이때에는 형옥을 중단하고 죄수를 풀어 주었다.\n\n(나)해마다 10월 하늘에 제사를 지내는데, 밤낮으로 술마시며 노래부르고 춤추니 이를 무천이라고 한다.\n\n－〖삼국지〗－",
                      num1Text: "(가)－5부가 있었으며, 계루부에서 왕위를 차지하였다.",
                      num2Text: "(가)－정치적 지배자로 신지, 읍차 등이 있었다.",
                      num3Text: "(나)－죄를 지은 사람이 소도에 들어가면 잡아가지 못하였다.",
                      num4Text: "(나)－다른 부족의 영역을 침범하면 책화라 하여 노비나 소, 말로 변상하였다.",
                      answer: 4),
        QuestionModel(num: 3,
                      questionText: "(가) 왕의 시기에 일어난 사실로 옳은 것은?",
                      reference: "이자겸, 척준경이 말하기를 “금이 예전에는 작은 나라여서 요와 우리나라를 섬겼으나, 지금은 갑자기 흥성하여 요와 송을 멸망시켰다. …(중략)… 작은 나라로서 큰 나라를 섬기는 것은 선왕의 도이니, 마땅히 우선 사절을 보내야 합니다.”라고 하니  (가)  이/가 그 의견을 따랐다.\n\n－〖고려사〗－",
                      num1Text: "도평의사사를 중심으로 정치를 주도하였다.",
                      num2Text: "성리학을 수용하면서 〖주자가례〗를 보급하였다.",
                      num3Text: "서경에 대화궁을 짓게 하고 칭제건원을 주장하였다.",
                      num4Text: "몽골의 침략에 대응하기 위해 강화도로 도읍을 옮겼다.",
                      answer: 3),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 ㉠ 이후에 일어난 사실로 옳지 않은 것은?",
                      reference: "상쾌한 아침의 나라라는 뜻을 지닌 조선은 일본의 총칼 아래 민족정신을 무참하게 유린당했다. …(중략)… 조선민족은 독립항쟁을 줄기차게 계속하였다. 그 중에서도 중요한 것은 ㉠"+"1919년의 독립만세운동".underLined+"이었다.\n\n－네루, 〖세계사 편력〗－",
                      num1Text: "‘암태도 소작쟁의’가 일어났다.",
                      num2Text: "‘정우회 선언’이 발표되었다.",
                      num3Text: "임병찬이 독립의군부를 조직하였다.",
                      num4Text: "조선 민립대학 기성회가 창립되었다.",
                      answer: 3),
        QuestionModel(num: 5,
                      questionText: "밑줄 친 ‘성상(聖上)’대에 편찬된 서적에 대한 설명으로 옳은 것은?",
                      reference: "세조가 신하들에게 말씀하시기를, “법의 과목(科目)이 너무 번잡하고 앞뒤가 맞지 않았기 때문에 상세히 살펴 다듬어 자손만대의 성법(成法)을 만들고자 한다.”라고 하셨다. ｢형전(刑典)｣과 ｢호전(戶典)｣은 이미 반포되어 시행하고 있으나 나머지 네 법전은 미처 교정을 마치지 못했다. 이에 "+"성상(聖上)".underLined+"께서 세조의 뜻을 받들어 여섯 권의 법전을 완성하게 하여 중외에 반포하셨다.",
                      num1Text: "〖동국병감〗은 고조선에서 고려말까지의 전쟁을 정리한 병서이다.",
                      num2Text: "〖동몽선습〗은 중국과 우리나라의 역사를 담은 아동교육서이다.",
                      num3Text: "〖삼강행실도〗는 모범적인 효자․충신․열녀를 다룬 윤리서이다",
                      num4Text: "〖국조오례의〗는 국가의 여러 행사에 필요한 의례를 정비한 의례서이다.",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "(가) 토지제도에 대한 설명으로 옳은 것은?",
                      reference: "비로소 직관(職官)․산관(散官) 각 품(品)의  (가) 을/를 제정하였는데, 관품의 높고 낮은 것은 논하지 않고 다만 인품만 가지고 그 등급을 결정하였다.\n\n－〖고려사〗－",
                      num1Text: "4색 공복을 기준으로 문반, 무반, 잡업으로 나누어 지급 결수를 정하였다.",
                      num2Text: "산관이 지급 대상에서 제외되었으며 무반의 차별 대우가 개선되었다.",
                      num3Text: "전임 관료와 현임 관료를 대상으로 경기지방에 한하여 지급하였다.",
                      num4Text: "고려의 건국과정에서 충성도와 공로에 따라 차등 지급되었다.",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "(가), (나) 시기에 있었던 사실로 옳은 것은?",
                      reference: "을미사변 발발\n    ⬇︎\n   (가)\n    ⬇︎\n을사조약 강제 체결\n    ⬇︎\n   (나)\n    ⬇︎\n13도 창의군 서울진공작전 전개",
                      num1Text: "(가)－시전상인을 중심으로 황국중앙총상회가 조직되었다.",
                      num2Text: "(가)－신민회는 일제가 날조한 105인 사건으로 와해되었다.",
                      num3Text: "(나)－함경도 관찰사 조병식이 곡물 수출을 막는 방곡령을 내렸다.",
                      num4Text: "(나)－일제의 황무지 개간권 요구를 반대하기 위해 보안회가 창설되었다.",
                      answer: 1),
        QuestionModel(num: 8,
                      questionText: "(가) 왕대의 사실에 대한 설명으로 옳은 것은?",
                      reference: "(가) 은/는 흑수말갈이 당과 통하려고 하자 군사를 동원하여 흑수말갈을 치게 하였다. 또한 일본에 사신 고제덕 등을 보내 “여러 나라를 관장하고 여러 번(蕃)을 거느리며, 고구려의 옛 땅을 회복하고 부여의 옛 습속을 지니고 있다.”라고 하여 강국임을 자부하였다.",
                      num1Text: "국호를 진국에서 발해로 바꾸었다.",
                      num2Text: "신라는 급찬 숭정을 발해에 사신으로 보냈다.",
                      num3Text: "대흥이라는 독자적인 연호를 사용하였다.",
                      num4Text: "장문휴가 당의 등주를 공격하였다.",
                      answer: 4),
        QuestionModel(num: 9,
                      questionText: "다음 전투를 이끈 한국인 부대에 대한 설명으로 옳은 것은?",
                      reference: "아군은 사도하자에 주둔 병력을 증강시키면서 훈련에 여념이 없었다. 새벽에 적군은 황가둔에서 이도하 방면을 거쳐 사도하로 진격하여 왔다. 그런데 적군은 아군이 세운 작전대로 함정에 들어왔고, 이에 일제히 포문을 열어 급습함으로써 적군은 응전할 사이도 없이 격파되었다.",
                      num1Text: "양세봉이 총사령관이었다.",
                      num2Text: "미쓰야 협정이 체결되기 직전까지 활약하였다.",
                      num3Text: "한국독립당의 산하부대로 동경성 전투도 수행하였다.",
                      num4Text: "조선민족전선연맹이 중국 국민당의 지원을 받아 창설하였다.",
                      answer: 3),
        QuestionModel(num: 10,
                      questionText: "밑줄 친 ㉠～㉣과 관련된 임란 이후 경제에 대한 설명으로 옳지 않은 것은?",
                      reference: "○ ㉠"+"서울".underLined+" 안팎과 번화한 큰 도시에 파․마늘․배추․오이 밭 따위는 10묘의 땅에서 얻은 수확이 돈 수만을 헤아리게 된다. 서도 지방의 ㉡"+"담배".underLined+" 밭, 북도 지방의 삼밭, 한산의 모시밭, 전주의 생강 밭, 강진의 ㉢"+"고구마".underLined+" 밭, 황주의 지황 밭에서의 수확은 모두 상상등전(上上等田)의 논에서 나는 수확보다 그 이익이 10배에 이른다.\n\n○ 작은 보습으로 이랑에다 고랑을 내는데, 너비 1척, 깊이 1척이다. 이렇게 한 이랑, 즉 1묘 마다 고랑 3개와 두둑 3개를 만들면, 두둑의 높이와 너비는 고랑의 깊이와 너비와 같아진다. 그 뒤 ㉣"+"고랑에 거름 재를 두껍게 펴고, 구멍 뚫린 박에 조를 담고서 파종한다.".underLined,
                      num1Text: "㉠－신해통공을 반포하여 육의전의 금난전권을 폐지하였다.",
                      num2Text: "㉡－인삼과 더불어 대표적인 상업작물로 재배되었다.",
                      num3Text: "㉢－〖감저보〗, 〖감저신보〗에서 재배법을 기술하였다.",
                      num4Text: "㉣－밭농사에서 농업 생산력의 발전을 가져온 농법이었다.",
                      answer: 1),
        QuestionModel(num: 11,
                      questionText: "단군에 대한 인식을 설명한 것으로 옳지 않은 것은?",
                      num1Text: "이승휴의 〖제왕운기〗에서는 우리 역사를 단군부터 서술하였다.",
                      num2Text: "홍만종의 〖동국역대총목〗은 단군 정통론의 입장에서 기술하였다.",
                      num3Text: "이규보의 ｢동명왕편｣은 단군의 건국 과정을 다루고 있다.",
                      num4Text: "｢기미독립선언서｣에는 ‘조선건국 4252년’으로 연도를 표기하였다.",
                      answer: 3),
        QuestionModel(num: 12,
                      questionText: "다음 내용이 실린 사서에 대한 설명으로 옳은 것은?",
                      reference: "제왕이 장차 일어날 때는 하늘의 명령과 상서로운 기운을 받아서 반드시 보통 사람과는 다른 점이 있으니, 그런 뒤에야 능히 큰 변화를 타서 제왕의 지위를 얻고 대업을 이루었다. …(중략)… 삼국의 시조들이 모두 신이(神異)한 일로 탄생했음이 어찌 괴이하겠는가. 이것이 책 첫머리에 ｢기이(紀異)｣편이 실린 까닭이며, 그 의도도 여기에 있는 것이다.",
                      num1Text: "불교 승려의 전기를 수록한 고승전이다.",
                      num2Text: "불교 중심의 고대 민간 설화를 수록하였다.",
                      num3Text: "고조선부터 고려 말까지의 역사를 정리하였다.",
                      num4Text: "유교적 사관에 기초하여 기전체로 서술하였다.",
                      answer: 2),
        QuestionModel(num: 13,
                      questionText: "(가)의 체결 이후에 일어난 사실로 옳은 것은?",
                      reference: "청군과 일본군의 개입으로 사태가 악화되자 농민군은 폐정개혁을 제시하며 정부와 (가) 을/를 맺었다. 이에 따라 농민군은 해산하였다.",
                      num1Text: "농민군이 황토현에서 감영군을 격파하였다.",
                      num2Text: "고부군수 조병갑이 만석보를 쌓아 수세를 강제로 거두었다.",
                      num3Text: "안핵사 이용태가 농민을 동학도로 몰아 처벌하였다.",
                      num4Text: "남접군과 북접군이 논산에서 합류하여 연합군을 형성하였다.",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "(가) 시기의 경제 상황에 대한 설명으로 옳은 것은?",
                      imgModel: ImageModel(imageString: "201913-14", imgWidth: 330, imgHeight: 130),
                      num1Text: "백성에게 정전을 처음으로 지급하였다.",
                      num2Text: "시장을 감독하는 관청인 동시전을 신설하였다.",
                      num3Text: "백성의 구휼을 위하여 진대법을 제정하였다.",
                      num4Text: "청주(菁州)의 거로현을 국학생의 녹읍으로 삼았다.",
                      answer: 1),
        QuestionModel(num: 15,
                      questionText: "우리나라 문화유산에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "개성 경천사지 10층 석탑은 원의 석탑을 본떠 만들어졌다.",
                      num2Text: "영주 부석사 무량수전은 주심포식 목조 건물이다.",
                      num3Text: "부여 정림사지 5층 석탑에서는 백제 무왕의 왕후가 넣은 사리기가 발견되었다.",
                      num4Text: "김제 금산사 미륵전은 다층 건물이나 내부가 하나로 통한다.",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "(가) 교육기관에 대한 설명으로 옳은 것은?",
                      reference: "주세붕이 비로소  (가) 을/를 창건할 적에 세상에서 자못 의심했으나, 그의 뜻은 더욱 독실해져 무리들의 비웃음을 무릅쓰고 비방을 극복하여 전례 없던 장한 일을 이루었습니다. …(중략)… 최충, 우탁, 정몽주, 길재, 김종직, 김굉필 같은 이가 살던 곳에   (가)  을/를 건립하게 될 것입니다.\n\n－〖퇴계집〗－",
                      num1Text: "지방의 군현에 있던 유일한 관학이다.",
                      num2Text: "선비와 평민의 자제에게 〖천자문〗 등을 가르쳤다.",
                      num3Text: "성적 우수자는 문과의 초시를 면제해 주었다.",
                      num4Text: "학문 연구와 선현의 제사를 위해 설립된 사설 교육기관이다.",
                      answer: 4),
        QuestionModel(num: 17,
                      questionText: "(가), (나)가 설명하는 조약을 옳게 짝 지은 것은?",
                      reference: "(가) 강화도 조약에 이어 몇 달 뒤 체결되었다. 양곡의 무제한 유출을 가능하게 한 규정과 일본정부에 소속된 선박은 항세를 납부하지 않는다는 규정이 들어 있었다.\n\n(나) 김홍집이 일본에서 황준헌의 〖조선책략〗을 가져 오면서 그 내용의 영향으로 체결되었으며, 청의 적극적인 알선이 있었다. 거중조정 조항과 최혜국 대우의 규정이 포함되어 있었다.",
                      num1Text: "조․일무역규칙 - 조․미수호통상조약",
                      num2Text: "조․일무역규칙 - 조․러수호통상조약",
                      num3Text: "조․일수호조규부록 - 조․미수호통상조약",
                      num4Text: "조․일수호조규부록 - 조․러수호통상조약",
                      answer: 1),
        QuestionModel(num: 18,
                      questionText: "다음은 어떤 인물에 대한 연보이다. 밑줄 친 ㉠～㉣의 설명으로 옳은 것은?",
                      reference: "1566년(31세)  ㉠"+"사간원".underLined+" 정언에 제수되다.\n\n1568년(33세)  ㉡"+"이조좌랑".underLined+"이 되었으나 외할머니 이씨의 병환 소식을 듣고 사퇴하다.\n\n1569년(34세)  동호독서당에 머물면서 〖동호문답〗을 찬진하다.\n\n1574년(39세)  ㉢"+"승정원".underLined+" 우부승지에 제수되어 ｢만언봉사｣를 올리다.\n\n1575년(40세)  ㉣"+"홍문관".underLined+" 부제학에서 사퇴하고 〖성학집요〗를 편찬하다.",
                      num1Text: "㉠－왕명을 출납하면서 왕의 비서기관의 업무를 하였다.",
                      num2Text: "㉡－삼사의 관리를 추천하는 권한이 있었다.",
                      num3Text: "㉢－왕의 정책을 간쟁하고 관원의 비행을 감찰하였다.",
                      num4Text: "㉣－서적 출판 및 간행의 업무를 전담하였다.",
                      answer: 2),
        QuestionModel(num: 19,
                      questionText: "다음 글의 저자에 대한 설명으로 옳은 것은?",
                      reference: "무릇 동양의 수천 년 교화계(敎化界)에서 바르고 순수하며 광대 정밀하여 많은 성현들이 전해주고 밝혀 준 유교가 끝내 인도의 불교와 서양의 기독교와 같이 세계에 큰 발전을 하지 못함은 어째서이며 …(중략)… 유교계에 3대 문제가 있는지라. 그 3대 문제에 대하여 개량하고 구신(求新)을 하지 않으면 우리 유교는 흥왕할 수가 없을 것이다.",
                      num1Text: "‘조선얼’을 강조하며 ‘조선학 운동’을 펼쳤다.",
                      num2Text: "‘나라는 형(形)이고 역사는 신(神)’이라고 주장하였다.",
                      num3Text: "주석․부주석 체제하의 대한민국 임시정부에서 주석을 역임하였다.",
                      num4Text: "｢독사신론｣에서 민족을 역사서술의 주체로 설정하고 사대주의를 비판하였다.",
                      answer: 2),
        QuestionModel(num: 20,
                      questionText: "(가)～(라)를 시기순으로 바르게 나열한 것은?",
                      reference: "(가)좌우합작 7원칙이 발표되었다.\n(나)조선 건국 준비 위원회가 결성되었다.\n(다)모스크바 3국 외상 회의가 개최되었다.\n(라)김구와 김규식이 남북협상을 제의하였다.",
                      num1Text: "(나)→(가)→(라)→(다)",
                      num2Text: "(나)→(다)→(가)→(라)",
                      num3Text: "(다)→(가)→(나)→(라)",
                      num4Text: "(다)→(나)→(가)→(라)",
                      answer: 2)
        
        ]
        let exam = ExamModel(id: 201913, year: 2019, examTypeID: "국가직", subjectID: "한국사", questions: questions)
        exam2019.append(exam)
    }
    //지방직
    func saveExam201921() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "다음에 해당하는 사례로 적절하지 않은 것은?",
                      reference: "대립쌍을 이루는 단어들이 일정한 방향성을 이루고 있다.",
                      num1Text: "성공(成功):실패(失敗)",
                      num2Text: "시상(施賞):수상(受賞)",
                      num3Text: "판매(販賣):구매(購買)",
                      num4Text: "공격(攻擊):방어(防禦)",
                      answer: 1),
        QuestionModel(num: 2,
                      questionText: "토론에서 사회자가 하는 역할에 대한 설명으로 가장 적절한 것은?",
                      num1Text: "토론을 시작하면서 논제가 타당한지 토론자들의 의견을 묻는다.",
                      num2Text: "토론자들에게 토론의 전반적인 방향과 유의점에 대해 안내한다.",
                      num3Text: "청중의 의견을 수렴하여 대안을 제시함으로써 쟁점을 약화시킨다.",
                      num4Text: "토론자의 주장과 논거를 비판하는 견해를 개진하여 논쟁의 확산을 꾀한다.",
                      answer: 2),
        QuestionModel(num: 3,
                      questionText: "다음 글의 글쓰기 방식에 대한 설명으로 적절한 것은?",
                      reference: "  멕시코의 환경 운동가로 유명한 가브리엘 과드리는 1960년대 이후 중앙아메리카 숲의 25% 이상이 목초지 조성을 위해 벌채되었으며 1970년대 말에는 중앙아메리카 전체 농토의 2/3가 축산 단지로 점유되었다고 주장했다. 실제로 1987년 이후로도 멕시코에만 1,497만 3,900ha의 열대 우림이 파괴되었는데, 이렇게 중앙아메리카의 열대림을 희생하면서까지 생산된 소고기는 주로 유럽과 미국으로 수출되었다. 그렇지만 이 소고기들은 지방분이 적고 미국인의 입맛에 그다지 맞지 않아 대부분 햄버거의 재료로 사용되었다.",
                      num1Text: "통계 수치를 활용하여 논거의 타당성을 높이고 있다.",
                      num2Text: "이론적 근거를 나열하여 주장의 전문성을 강화하고 있다.",
                      num3Text: "전문 용어의 뜻을 쉽게 풀이하여 독자의 이해를 돕고 있다.",
                      num4Text: "예측할 수 없는 결과를 나열하여 사태의 심각성을 알리고 있다.",
                      answer: 1),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 부분이 어법에 맞는 것은?",
                      num1Text: "이 가곡의 "+"노래말".underLined+"은 아름답다.",
                      num2Text: "그 집의 "+"순대국".underLined+"은 아주 맛있다.",
                      num3Text: "하교길".underLined+"은 늘 아이들로 북적인다.",
                      num4Text: "선생님은 간단한 "+"인사말".underLined+"을 건넸다.",
                      answer: 4),
        QuestionModel(num: 5,
                      questionText: "(가)의 관점에서 (나)를 감상할 때 가장 적절한 것은?",
                      reference: "(가)\n반영론은 문학 작품이 사회를 반영하여 현실의 문제를 비판적으로 성찰할 수 있게 하는 매개체라는 관점을 취한 비평적 입장이다.\n\n(나)\n강나루 건너서\n밀밭 길을\n\n구름에 달 가듯이\n가는 나그네\n\n길은 외줄기\n남도 삼백리\n\n술 익는 마을마다\n타는 저녁 놀\n\n구름에 달 가듯이\n가는 나그네\n\n－박목월, ｢나그네｣－",
                      num1Text: "전통적 민요의 율격을 바탕으로 한 정형적 형식을 통해 정제된 시상이 효과적으로 드러났군.",
                      num2Text: "삶의 고통스러운 단면을 외면한 채 유유자적한 삶만을 그린 것은 아닌지 비판할 여지가 있군.",
                      num3Text: "낭만적 감성을 불러일으키는 시적 분위기가 시조에서 보이는 선경후정과 비슷한 양상을 띠는군.",
                      num4Text: "해질 무렵 강가를 거닐며 조망한 풍경의 이미지가 한 폭의 그림을 보는 듯한 감각을 자아내는군.",
                      answer: 2),
        QuestionModel(num: 6,
                      questionText: "다음 글에 대한 이해로 가장 적절한 것은?",
                      reference: "  책은 벗입니다. 먼 곳에서 찾아온 반가운 벗입니다. 배움과 벗에 관한 이야기는 〖논어〗의 첫 구절에도 있습니다. ‘배우고 때때로 익히니 어찌 기쁘지 않으랴. 벗이 먼 곳에서 찾아오니 어찌 즐겁지 않으랴.’가 그런 뜻입니다.\n  그러나 오늘 우리의 현실은 그렇지 못합니다. 인생의 가장 빛나는 시절을 수험 공부로 보내야 하는 학생들에게 독서는 결코 반가운 벗이 아닙니다. 가능하면 빨리 헤어지고 싶은 불행한 만남일 뿐입니다. 밑줄 그어 암기해야 하는 독서는 진정한 의미의 독서가 못 됩니다.\n  독서는 모름지기 자신을 열고, 자신을 확장하고, 자신을 뛰어넘는 비약이어야 합니다. 그렇기 때문에 독서는 삼독(三讀)입니다. 먼저 글을 읽고 다음으로 그 글을 집필한 필자를 읽어야 합니다. 그 글이 제기하고 있는 문제뿐만 아니라 필자가 어떤 시대, 어떤 사회에 발 딛고 있는지를 읽어야 합니다. 그리고 최종적으로 그것을 읽고 있는 독자 자신을 읽어야 합니다. 그렇게 함으로써 자신의 처지와 우리 시대의 문맥을 깨달아야 합니다.",
                      num1Text: "독서는 타인의 경험이나 생각 등을 자기화(自己化)하는 과정이다.",
                      num2Text: "반가운 벗과의 독서야말로 진정한 독자로 거듭날 수 있는 첩경(捷徑)이다.",
                      num3Text: "시대와 불화(不和)한 독자일수록 독서를 통해 자신의 위치를 발견하기 쉽다.",
                      num4Text: "자신이 배운 것을 제때에 적용하기 위해서는 친밀한 교우(交友) 관계가 중요하다.",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "밑줄 친 부분의 띄어쓰기가 옳은 것은?",
                      num1Text: "그 중에".underLined+" 깨끗한 옷만 골라 입으세요.",
                      num2Text: "어제는 밤이 늦도록 "+"옛 책을".underLined+" 뒤적였다.",
                      num3Text: "시간 날 때 낚시나 "+"한 번".underLined+" 같이 갑시다.",
                      num4Text: "사람들은 황급히 "+"굴 속으로".underLined+" 모여들었다.",
                      answer: 2),
        QuestionModel(num: 8,
                      questionText: "다음에 대한 설명으로 적절한 것은?",
                      reference: "㉠가을일[가을릴]   ㉡텃마당[턴마당]\n㉢입학생[이팍쌩]   ㉣흙먼지[흥먼지]",
                      num1Text: "㉠: 한 가지 유형의 음운 변동이 나타난다.",
                      num2Text: "㉡: 인접한 음의 영향을 받아 조음 위치가 같아지는 동화 현상이 나타난다.",
                      num3Text: "㉢: 음운 변동 전의 음운 개수와 음운 변동 후의 음운 개수가 서로 다르다.",
                      num4Text: "㉣: 음절 끝에 ‘ㄱ, ㄴ, ㄷ, ㄹ, ㅁ, ㅂ, ㅇ’ 이외의 자음이 오면 이 7개의 자음 중 하나로 바뀌는 규칙이 적용된다.",
                      answer: 3),
        QuestionModel(num: 9,
                      questionText: "어법에 어긋난 문장을 수정하고 설명한 예로 적절하지 않은 것은?",
                      num1Text: "유사한 내용의 제안이 접수되었을 때에는 먼저 접수된 것이 우선한다.\n→ ‘접수되었을 때에는’은 사건이나 행위가 완료된 상황을 나타내므로 ‘접수될 때에는’으로 바꾼다.",
                      num2Text: "안내서 및 과업 지시서 교부는 참가 신청자에게만 교부한다.\n→ ‘과업 지시서 교부’와 서술어 ‘교부하다’는 의미상 중복되며 호응하지 않으므로 앞의 ‘교부’를 삭제한다.",
                      num3Text: "해안선에서 200미터 이내의 수역을 제외된 상태에서 논의를 진행하겠습니다.\n→ 목적어 ‘수역을’과 서술어 ‘제외되다’는 호응하지 않으므로 ‘제외된’은 ‘제외한’으로 바꾼다.",
                      num4Text: "관련 도서는 해당 부서에 비치하고 관계자에게 열람한다.\n→ 서술어 ‘열람하다’는 부사어 ‘관계자에게’와 호응하지 않으므로 ‘열람하게 한다.’와 같이 바꾼다.",
                      answer: 1),
        QuestionModel(num: 10,
                      questionText: "(가)～(라)에 대한 설명으로 적절하지 않은 것은?",
                      reference: "(가) 고인(古人)도 날 몯 보고 나도 고인(古人) 몯 뵈\n고인(古人)을 몯 뵈도 녀던 길 알ᄑᆡ 잇ᄂᆡ\n녀던 길 알ᄑᆡ 잇거든 아니 녀고 엇뎔고\n\n(나) 술은 어이야 됴니 누룩 섯글 타시러라\n국은 어이야 됴니 염매(鹽梅)  타시러라\n이 음식 이 뜯을 알면 만수무강(萬壽無疆)리라\n\n(다) 우레치 소나 님을 번치 번뜻 만나\n비치 오락락 구름치 헤여지니\n흉중(胸中)에 튼 슘이 안 피듯 여라\n\n(라) 하하 허허 들 내 우음이 졍 우움가\n하 어쳑 업서셔 늣기다가 그리 되게\n벗님 웃디들 말구려 아귀 여디리라",
                      num1Text: "(가): 연쇄법을 활용하여 고인의 길을 따르겠다는 의지를 드러내고 있다.",
                      num2Text: "(나): 문답법과 대조법을 활용하여 임의 만수무강을 기원하고 있다.",
                      num3Text: "(다): ‘ᄀᆞᆺ치’를 반복적으로 표현하여 운율감을 더하고 있다.",
                      num4Text: "(라): 냉소적 어조를 통해 상대에 대한 불편한 심기를 표출하고 있다.",
                      answer: 2),
        QuestionModel(num: 11,
                      questionText: "다음에 제시된 단어의 의미에 맞게 쓴 문장으로 적절하지 않은 것은?",
                      imgModel: ImageModel(imageString: "201921-11", imgWidth: 330, imgHeight: 150),
                      num1Text: "㉠: 장기에서 포는 죽고 차만 살아 있다.",
                      num2Text: "㉡: 그는 벼슬을 살기 싫어 속세를 버렸다.",
                      num3Text: "㉢: 옷에 풀기가 아직 살아 있다.",
                      num4Text: "㉣: 그렇게 세게 부딪혔는데도 시계가 살아 있다.",
                      answer: 3),
        QuestionModel(num: 12,
                      questionText: "진행자의 말하기 방식에 대한 설명으로 적절하지 않은 것은?",
                      reference: "진행자:안녕하십니까? 오늘은 고령자의 운전면허 자진 반납 제도에 대해 홍○○ 교수님 모시고 말씀 들어 보겠습니다.\n\n홍교수:네, 반갑습니다.\n\n진행자:나와 주셔서 감사합니다. 우선 이 제도가 어떤 제도인가요?\n\n홍교수:지자체마다 조금씩 다르기는 하지만 고령 운전자들이 운전면허를 자발적으로 반납하게 유도하여 고령 운전자에 의한 교통사고를 줄이고자 하는 제도입니다.\n\n진행자:고령 운전자에 의한 교통사고가 심각한가요? 뒷받침할 만한 자료가 있나요?\n\n홍교수:네. 도로교통공단의 통계에 따르면, 전체 교통사고 대비 고령 운전자에 의한 교통사고 비율이 2014년에는 9.0%였으나 매년 조금씩 증가하여 2017년에는 12.3%를 차지하고 있습니다.\n\n진행자:그렇군요. 아무래도 고령화 사회로 진입하다 보니 전체 운전자 중에서 고령 운전자에 해당하는 비율이 늘었기 때문인 것 같은데요.\n\n홍 교수:네, 그렇습니다. 이전보다 차량 성능이 월등히 좋아진 점도 하나의 요인이 될 것입니다.\n\n진행자:그렇다고 해도 무작정 운전면허를 반납하라고만 할 수는 없을 테고, 뭔가 보완책이 있나요?\n\n홍교수:네. 지자체마다 차이가 있지만 소정의 교통비를 지급함으로써 대중교통 이용을 권장하고 있습니다.\n\n진행자:취지 자체만으로는 긍정적으로 평가할 수 있을 것 같은데, 혹시 제도 시행상의 문제점은 없나요?\n\n홍교수:일회성이 문제라고 생각합니다.\n\n진행자:아, 운전면허를 반납한 당시에만 교통비가 한 차례 지원된다는 말씀이군요.\n\n홍교수:네. 이분들이 더 이상 운전을 하지 않아도 이동권을 확보할 수 있도록 지속적인 지원이 이루어져야 이 제도가 효과를 얻을 수 있습니다.\n\n진행자:그에 더해 장기적으로는 고령자 친화적인 대중교통 인프라를 구축하는 일도 필요할 듯합니다. 교수님, 오늘 말씀 감사합니다.",
                      num1Text: "상대방의 의견이 합리적이지 않음을 지적하며 인터뷰를 마무리 짓는다.",
                      num2Text: "상대방이 인용한 통계 자료에 대해 자기 나름대로의 해석을 제시한다.",
                      num3Text: "상대방이 제시한 정보 이외에 추가적인 정보를 요구한다.",
                      num4Text: "상대방에게 해당 제도의 시행 배경에 대한 객관적인 근거를 요구한다.",
                      answer: 1),
        QuestionModel(num: 13,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "  계몽주의 사상가들은 명백히 모순되는 두 개의 견해를 취했다. 그들은 인간의 위치를 자연계 안에서 해명하려고 애썼다. 역사의 법칙이란 것을 자연의 법칙과 동일한 것으로 여겼다. 다른 한편, 그들은 진보를 믿었다. 그렇다면 그들이 자연을 진보하는 것으로, 다시 말해 끊임없이 어떤 목적을 향해서 전진하는 것으로 받아들인 데에는 어떤 근거가 있었던가? 헤겔은 역사는 진보하는 것이고 자연은 진보하지 않는 것이라고 뚜렷이 구분했다. 반면, 다윈은 진화와 진보를 동일한 것으로 주장함으로써 모든 혼란을 정리한 듯했다. 자연도 역사와 마찬가지로 진보하는 것으로 본 것이다. 그러나 이것은 진화의 원천인 생물학적인 유전(biological inheritance)을 역사에서의 진보의 원천인 사회적인 획득(social acquisition)과 혼동함으로써 훨씬 더 심각한 오해에 이를 수 있는 길을 열어 놓았다. 오늘날 그 둘이 분명히 구별된다는 것은 익히 알려진 것이다.",
                      num1Text: "자연의 진보에 대한 증거",
                      num2Text: "인간 유전의 사회적 의미",
                      num3Text: "역사의 법칙과 자연의 법칙",
                      num4Text: "진보와 진화에 관한 견해들",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "다음 글에 대한 이해로 가장 적절한 것은?",
                      reference: "  유 소사가 말하기를, “신부(新婦)가 이제 내 집에 들어왔으니 어떻게 남편을 도울꼬?”\n  사씨 대답하여 말하기를, “첩(妾)이 일찍 아비를 여의고 자모(慈母)의 사랑을 입사와 본래 배운 것이 없으니 물으시는 말씀에 대답치 못하옵거니와 어미 첩을 보낼 제 중문(中門)에 임(臨)하여 경계하여 말씀하시기를 ‘반드시 공경(恭敬)하며 반드시 경계(警戒)하여 남편을 어기오지 말라.’ 하시니 이 말씀이 경경(耿耿)하여 귓가에 있나이다.”\n  유 소사가 말하기를, “남편의 뜻을 어기오지 말면 장부(丈夫) 비록 그른 일이 있을지라도 순종(順從)하랴?”\n  사씨 대 왈, “그런 말이 아니오라 부부(夫婦)의 도(道) 오륜(五倫)을 겸(兼)하였으니 아비에게 간(諫)하는 자식이 있고 나라에 간하는 신하 있고 형제(兄弟) 서로 권하고 붕우(朋友) 서로 책(責)하나니 어찌 부부라고 간쟁(諫諍)치 않으리이까? 그러하나 자고로 장부(丈夫) 부인(婦人)의 말을 편청(偏聽)하면 해로움이 있삽고 유익(有益)함이 없으니 어찌 경계 아니 하리이까?”\n  유 소사가 모든 손님을 돌아보며 말하기를, “나의 며느리는 가히 조대가*에 비할 것이니 어찌 시속(時俗) 여자가 미칠 바리오.”라고 하였다.\n\n－김만중, 〖사씨남정기〗에서－\n\n*조대가: 〖한서(漢書)〗를 지은 반고(班固)의 누이동생인 반소(班昭). 학식이 뛰어나고 덕망이 높아 왕실 여성의 스승으로 칭송이 자자했다.",
                      num1Text: "사씨의 어머니는 딸이 남편에게 맞섰던 일을 비판하고 있다.",
                      num2Text: "사씨는 홀어머니를 모시느라 제대로 배우지 못한 것을 안타까워하고 있다.",
                      num3Text: "사씨는 부부의 예에 따라, 남편이 잘못하면 이를 지적해야 한다고 생각한다.",
                      num4Text: "유 소사는 며느리와의 대화를 통해, 효성이 지극한 사씨의 모습에 흡족해 하고 있다.",
                      answer: 3),
        QuestionModel(num: 15,
                      questionText: "다음 글에서 ‘소리’에 대한 이해로 적절하지 않은 것은?",
                      reference: "  바깥은 어둡고 뜰 변두리의 늙은 나무들은 바람에 불려 서늘한 소리를 내었다. 처마 끝 저편에 퍼진 하늘에는 별이 총총하게 박혀 있으나, 아스무레한 초여름 기운에 잠겨 있었다. 집은 전체로 조용하고 썰렁했다.\n  꽝 당 꽝 당.\n  먼 어느 곳에서는 이따금 여운이 긴 쇠붙이 두드리는 소리가 들려왔다. 밑 거리의 철공소나 대장간에서 벌겋게 단 쇠를 쇠망치로 뚜드리는 소리 같았다.\n  근처에는 그런 곳은 없을 것이었다. 그렇다면 굉장히 먼 곳일 것이었다. 굉장히 굉장히 먼 곳일 것이었다.\n  꽝 당 꽝 당.\n  단조로운 소리이면서 송곳처럼 쑤시는 구석이 있는, 밤중에 간헐적으로 들려오는 그 소리는 이상하게 신경을 자극했다.\n “참, 저거 무슨 소리유?”\n  영희가 미간을 찌푸리면서 말했다.\n “글쎄, 무슨 소릴까…….”\n  정애가 심드렁하게 대답했다.\n“이 근처에 철공소는 없을 텐데.”\n “…….”\n  정애는 표정으로만 수긍을 했다.\n  꽝 당 꽝 당.\n  그 쇠붙이에 쇠망치 부딪치는 소리는 여전히 간헐적으로 이어지고 있었다. 밤내 이어질 모양이었다. 자세히 그 소리만 듣고 있으려니까 바깥의 선들대는 늙은 나무들도 초여름 밤의 바람에 불려서 그런 것이 아니라 저 소리의 여운에 울려 흔들리고 있었다. 저 소리는 이 방안의 벽 틈서리를 쪼개고도 있었다. 형광등 바로 위의 천장에 비수가 잠겨 있을 것이었다.\n\n－이호철, ｢닳아지는 살들｣에서－",
                      num1Text: "‘서늘한 소리’는 예사롭지 않은 분위기를 조성하기 시작한다.",
                      num2Text: "‘꽝 당 꽝 당’ 소리는 인물의 심리적 상태의 변화를 촉발한다.",
                      num3Text: "‘단조로운 소리’는 반복적으로 드러남으로써 모종의 의미가 부여된다.",
                      num4Text: "‘소리의 여운’은 단선적 구성에 변화를 주어 갈등 해소의 기미를 강화한다.",
                      answer: 4),
        QuestionModel(num: 16,
                      questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                      reference: "  그동안 나는 <일 포스티노>를 세 번쯤 빌려 보았다. 그 이유는 이 아름다운 영화 속에 아스라이 문학이 똬리를 틀고 앉아 있기 때문이다. 특히 시란 무엇인가에 대한 해답을 이처럼 쉽고도 절실하게 설명해 놓은 문학 교과서를 나는 아직까지 보지 못했다. 그래서 학생들에게 시를 가르칠 때 나는 종종 영화 <일 포스티노>를 활용한다. 수백 마디의 말보다 <일 포스티노>를 함께 보고 토론하는 것이 시의 본질에 훨씬 깊숙이, 훨씬 빨리 가 닿을 수 있다는 것을 경험하기도 했다.\n  시를 공부하면서 은유에 시달려 본 사람이라면 이 영화를 보고 수차례 무릎을 쳤을 것이다. 마리오 루폴로가 네루다에게 보내기 위해 고향의 여러 가지 소리를 녹음하는 인상적인 장면이 있다. 여기서 해변의 파도 소리를 녹음하는 것이 은유의 출발이라면 어부들이 그물을 걷어 올리는 소리를 담고자 하는 모습은 은유의 확장이라고 할 수 있다. 더 나아가 밤하늘의 별빛을 녹음하는 기막히게 아름다운 장면에 이르면 은유는 절정에 달한다. 더 이상의 구차한 설명이 필요하지 않다.",
                      num1Text: "영화 <일 포스티노>는 시를 이해하는 데 도움이 되는 교과서와도 같다.",
                      num2Text: "영화 <일 포스티노>의 인물들은 문학적 은유의 본질과 의미를 잘 알고 있다.",
                      num3Text: "시의 본질에 대해 질문하고 답을 얻기 위해 영화 <일 포스티노>를 참고할 만하다.",
                      num4Text: "문학의 미적 자질과 영화 <일 포스티노>의 미적 자질 사이에서 공통점을 찾을 수 있다.",
                      answer: 2),
        QuestionModel(num: 17,
                      questionText: "다음 (    ) 속에 들어갈 말로 가장 적절한 것은?",
                      reference: "  방랑시인 김삿갓의 시는 해학과 풍자로 가득 차 있는데, 무슨 시든 단숨에 써 내리는 一筆揮之인데다 가히 (    )의 상태라서 일부러 꾸미지 않았는데도 자연스럽고 아름답다.",
                      num1Text: "花朝月夕",
                      num2Text: "韋編三絶",
                      num3Text: "天衣無縫",
                      num4Text: "莫無可奈",
                      answer: 3),
        QuestionModel(num: 18,
                      questionText: "밑줄 친 부분의 한자 표기가 잘못된 것은?",
                      num1Text: "그는 여러 차례 TV 출연으로 "+"유명세(有名勢)".underLined+"를 치렀다.",
                      num2Text: "누가 먼저 할 것인지 "+"복불복(福不福)".underLined+"으로 정하기로 했다.",
                      num3Text: "긴박한 상황이라 "+"대증요법(對症療法)".underLined+"을 쓸 수밖에 없었다.",
                      num4Text: "사건의 "+"경위(經緯)".underLined+"는 알 수 없지만, 결과만 본다면 우리에게 유리하다.",
                      answer: 1),
        QuestionModel(num: 19,
                      questionText: "다음 글에서 추론한 바로 적절하지 않은 것은?",
                      reference: "  우리는 도시화, 산업화, 고도성장 과정에서 우리 경제의 뒷방살이 신세로 전락한 한국 농업의 새로운 가치에 주목해야 한다. 농업은 경제적 효율성이 뒤처져서 사라져야 할 사양 산업이 아니다. 전 지구적인 기후 변화와 식량 및 에너지 등 자원 위기에 대응하여 나라와 생명을 살릴 미래 산업으로서 농업의 전략적 가치가 크게 부각되고 있다. 농본주의의 기치를 앞세우고 농업 르네상스 시대의 재연을 통해 우리 경제가 당면한 불확실성의 터널을 벗어나야 한다.\n  우리는 왜 이런 주장을 하는가? 농업은 자원 순환적이고 환경 친화적인 산업이기 때문이다. 땅의 생산력에 기초해서 한계적 노동력을 고용하는 지연(地緣) 산업인 동시에 식량과 에너지를 생산하는 원천적인 생명 산업이기 때문이다. 물질적인 부의 극대화를 위해서 한 지역의 자원을 개발하여 이용한 뒤에 효용 가치가 떨어지면 다른 곳으로 이동하는 유목민적 태도가 오늘날 위기를 낳고 키워 왔는지 모른다. 급변하는 시대의 흐름에 부응하지 못하는 구시대의 경제 패러다임으로는 오늘날의 역사에 동승하기 어렵다. 이런 맥락에서, 지키고 가꾸어 후손에게 넘겨주는 정주민의 문화적 지속성을 존중하는 농업의 가치가 새롭게 조명 받는 이유에 주목할 만하다. 과학 기술의 눈부신 발전 성과를 수용하여 새로운 상품과 시장을 창출할 수 있는 녹색 성장 산업으로서 농업의 잠재적 가치가 중시되고 있는 것이다.",
                      num1Text: "고도성장을 도모하는 경제 정책을 추진하는 과정에서 농업 중심의 경제 패러다임을 지양하였다.",
                      num2Text: "효율성을 중요한 가치로 내세우는 경제 시스템은 미래 사회를 대비하는 데 한계가 있다.",
                      num3Text: "유목 생활을 하는 민족에 비해 정주 생활을 하는 민족이 농업의 가치 증진에 더 기여할 수 있다.",
                      num4Text: "녹색 성장 산업으로서 농업의 효용성을 드높이기 위해서 과학 기술의 부작용을 성찰할 필요가 있다.",
                      answer: 4),
        QuestionModel(num: 20,
                      questionText: "다음 글쓴이의 입장에 부합하는 것은?",
                      reference: "  효(孝)가 개인과 가족, 곧 일차적인 인간관계에서 일어나는 행위를 규정한 것이라면, 충(忠)은 가족이 아닌 사람들과의 관계, 곧 이차적인 인간관계에서 일어나는 사회적 행위를 규정한 것이었다. 그런데 언제부터인가 우리는 효를 순응적 가치관을 주입하는 봉건 가부장제 사회의 유습이라고 오해하는가 하면, 충과 효를 동일시하는 오류를 저지르는 경향이 많아졌다. 다음을 보자.\n\n  “부모에게 효도하고 형제를 사랑하는 사람은 윗사람의 명령을 거역하는 경우가 드물다. 또 윗사람의 명령을 어기지 않는 사람은 난동을 일으키는 경우도 드물다. 군자는 근본에 힘쓴다. 근본이 확립되면 도가 생기기 때문이다. 효도와 우애는 인(仁)의 근본이다.”\n\n  위 구절에 담긴 입장을 기준으로 보면 효는 윗사람에 대한 절대 복종으로 연결된다. 곧 종족 윤리의 기본이 되는 연장자에 대한 예우는 물론이고 신분 사회의 엄격한 상하 관계까지 포괄적으로 인정하는 것이다. 하지만 이 구절만을 근거로 효를 복종의 윤리라고 보는 것은 성급한 판단이다. 왜냐하면 원래부터 효란 가족 윤리 또는 종족 윤리로서 사회 윤리였던 충보다 우선시되었을 뿐만 아니라, 유교의 기본 입장은 설사 부모의 명령이라 하더라도 옳고 그름을 가리지 않는 맹목적인 복종은 그 자체가 불효라고 보았기 때문이다.\n  유교에서는 부모와 자식의 관계가 자연에 의해서 결정된다고 한다. 이 때문에 부모와 자식의 관계는 인위적으로 끊을 수 없다고 본다. 이에 비해 임금과 신하의 관계는 공동의 목표를 위한 관계로서 의리에 의해서 맺어진 관계로 본다. 의리가 맞지 않는다면 언제라도 끊을 수 있다고 생각하는 것이다.",
                      num1Text: "효는 봉건 가부장제 사회에서 비롯한 일차적 인간관계이다.",
                      num2Text: "효는 부모와 자식 간의 관계이므로 조건 없는 신뢰에 기초한 덕목이다.",
                      num3Text: "윗사람에 대한 복종을 절대시하지 않는 것이 유교적 윤리의 한 바탕이다.",
                      num4Text: "충의 도리를 다함으로써 효의 도리에 도달할 수 있다는 것이 인의 이치다.",
                      answer: 3),
        
        ]
        let exam = ExamModel(id: 201921, year: 2019, examTypeID: "지방직", subjectID: "국어", questions: questions)
        exam2019.append(exam)
    }
    func saveExam201922() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오. [1~2]",
                      reference: "I came to see these documents as relics of a sensibility now dead and buried, which needed to be "+"excavated.".underLined,
                      num1Text: "exhumed",
                      num2Text: "packed",
                      num3Text: "erased",
                      num4Text: "celebrated",
                      answer: 1),
        QuestionModel(num: 2,
                      questionText: "",
                      reference: "Riding a roller coaster can be a joy ride of emotions: the nervous anticipation as you’re strapped into your seat, the questioning and regret that comes as you go up, up, up, and the "+"sheer".underLined+" adrenaline rush as the car takes that first dive.",
                      num1Text: "utter",
                      num2Text: "scary",
                      num3Text: "occasional",
                      num4Text: "manageable",
                      answer: 1),
        QuestionModel(num: 3,
                      questionText: "두 사람의 대화 중 가장 어색한 것은?",
                      num1Text: "A:What time are we having lunch?\nB:It’ll be ready before noon.",
                      num2Text: "A:I called you several times. Why didn’t you answer?\nB:Oh, I think my cell phone was turned off.",
                      num3Text: "A:Are you going to take a vacation this winter?\nB:I might. I haven’t decided yet.",
                      num4Text: "A:Hello. Sorry I missed your call.\nB:Would you like to leave a message?",
                      answer: 4),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "A:Hello. I need to exchange some money.\nB:Okay. What currency do you need?\nA:I need to convert dollars into pounds. What’s the exchange rate?\nB:The exchange rate is 0.73 pounds for every dollar.\nA:Fine. Do you take a commission?\nB:Yes, we take a small commission of 4 dollars.\nA:______________________________?\nB:We convert your currency back for free. Just bring your receipt with you.",
                      num1Text: "How much does this cost",
                      num2Text: "How should I pay for that",
                      num3Text: "What’s your buy-back policy",
                      num4Text: "Do you take credit cards",
                      answer: 3),
        QuestionModel(num: 5,
                      questionText: "밑줄 친 부분 중 어법상 옳지 않은 것은?",
                      reference: "Each year, more than 270,000 pedestrians ①"+"lose".underLined+" their lives on the world’s roads. Many leave their homes as they would on any given day never ②"+"to return".underLined+". Globally, pedestrians constitute 22% of all road traffic fatalities, and in some countries this proportion is ③"+"as high as".underLined+" two thirds of all road traffic deaths. Millions of pedestrians are non-fatally ④"+"injuring".underLined+"―some of whom are left with permanent disabilities. These incidents cause much suffering and grief as well as economic hardship.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "어법상 옳은 것은?",
                      num1Text: "The paper charged her with use the company’s money for her own purposes.",
                      num2Text: "The investigation had to be handled with the utmost care lest suspicion be aroused.",
                      num3Text: "Another way to speed up the process would be made the shift to a new system.",
                      num4Text: "Burning fossil fuels is one of the lead cause of climate change.",
                      answer: 2),
        QuestionModel(num: 7,
                      questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "There is a thought that can haunt us: since everything probably affects everything else, how can we ever make sense of the social world? If we are weighed down by that worry, though, we won’t ever make progress.",
                      reference2: "(A)Every discipline that I am familiar with draws caricatures of the world in order to make sense of it. The modern economist does this by building models, which are deliberately stripped down representations of the phenomena out there.\n\n(B)The economist John Maynard Keynes described our subject thus: “Economics is a science of thinking in terms of models joined to the art of choosing models which are relevant to the contemporary world.”\n\n(C)When I say “stripped down,” I really mean stripped down. It isn’t uncommon among us economists to focus on one or two causal factors, exclude everything else, hoping that this will enable us to understand how just those aspects of reality work and interact.",
                      num1Text: "(A)－(B)－(C)",
                      num2Text: "(A)－(C)－(B)",
                      num3Text: "(B)－(C)－(A)",
                      num4Text: "(B)－(A)－(C)",
                      answer: 2),
        QuestionModel(num: 8,
                      questionText: "다음 글의 내용과 일치하는 것은?",
                      reference: "Prehistoric societies some half a million years ago did not distinguish sharply between mental and physical disorders. Abnormal behaviors, from simple headaches to convulsive attacks, were attributed to evil spirits that inhabited or controlled the afflicted person’s body. According to historians, these ancient peoples attributed many forms of illness to demonic possession, sorcery, or the behest of an offended ancestral spirit. Within this system of belief, called demonology, the victim was usually held at least partly responsible for the misfortune. It has been suggested that Stone Age cave dwellers may have treated behavior disorders with a surgical method called trephining, in which part of the skull was chipped away to provide an opening through which the evil spirit could escape. People may have believed that when the evil spirit left, the person would return to his or her normal state. Surprisingly, trephined skulls have been found to have healed over, indicating that some patients survived this extremely crude operation.\n\n※convulsive: 경련의\n※behest: 명령",
                      num1Text: "Mental disorders were clearly differentiated from physical disorders.",
                      num2Text: "Abnormal behaviors were believed to result from evil spirits affecting a person.",
                      num3Text: "An opening was made in the skull for an evil spirit to enter a person’s body.",
                      num4Text: "No cave dwellers survived trephining.",
                      answer: 2),
        QuestionModel(num: 9,
                      questionText: "다음 글의 주제로 가장 적절한 것은?",
                      reference: "As the digital revolution upends newsrooms across the country, here’s my advice for all the reporters. I’ve been a reporter for more than 25 years, so I have lived through a half dozen technological life cycles. The most dramatic transformations have come in the last half dozen years. That means I am, with increasing frequency, making stuff up as I go along. Much of the time in the news business, we have no idea what we are doing. We show up in the morning and someone says, “Can you write a story about (pick one) tax policy/immigration/climate change?” When newspapers had once-a-day deadlines, we said a reporter would learn in the morning and teach at night―write a story that could inform tomorrow’s readers on a topic the reporter knew nothing about 24 hours earlier. Now it is more like learning at the top of the hour and teaching at the bottom of the same hour. I’m also running a political podcast, for example, and during the presidential conventions, we should be able to use it to do real-time interviews anywhere. I am just increasingly working without a script.",
                      num1Text: "a reporter as a teacher",
                      num2Text: "a reporter and improvisation",
                      num3Text: "technology in politics",
                      num4Text: "fields of journalism and technology",
                      answer: 2),
        QuestionModel(num: 10,
                      questionText: "글의 흐름상 가장 어색한 문장은?",
                      reference: "Children’s playgrounds throughout history were the wilderness, fields, streams, and hills of the country and the roads, streets, and vacant places of villages, towns, and cities. ①"+"The term playground refers to all those places where children gather to play their free, spontaneous games.".underLined+" ②"+"Only during the past few decades have children vacated these natural playgrounds for their growing love affair with video games, texting, and social networking.".underLined+" ③"+"Even in rural America few children are still roaming in a free-ranging manner, unaccompanied by adults.".underLined+" ④"+"When out of school, they are commonly found in neighborhoods digging in sand, building forts, playing traditional games, climbing, or playing ball games.".underLined+" They are rapidly disappearing from the natural terrain of creeks, hills, and fields, and like their urban counterparts, are turning to their indoor, sedentary cyber toys for entertainment.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오. [11~12]",
                      reference: "Time does seem to slow to a trickle during a boring afternoon lecture and race when the brain is "+"engrossed in".underLined+" something highly entertaining.",
                      num1Text: "enhanced by",
                      num2Text: "apathetic to",
                      num3Text: "stabilized by",
                      num4Text: "preoccupied with",
                      answer: 4),
        QuestionModel(num: 12,
                      questionText: "",
                      reference: "These daily updates were designed to help readers "+"keep abreast of".underLined+" the markets as the government attempted to keep them under control.",
                      num1Text: "be acquainted with",
                      num2Text: "get inspired by",
                      num3Text: "have faith in",
                      num4Text: "keep away from",
                      answer: 1),
        QuestionModel(num: 13,
                      questionText: "밑줄 친 (A), (B)에 들어갈 말로 가장 적절한 것을 고르시오. [13~14]",
                      reference: "In the 1840s, the island of Ireland suffered famine. Because Ireland could not produce enough food to feed its population, about a million people died of     (A)    ; they simply didn’t have enough to eat to stay alive. The famine caused another 1.25 million people to     (B)    ; many left their island home for the United States; the rest went to Canada, Australia, Chile, and other countries. Before the famine, the population of Ireland was approximately 6 million. After the great food shortage, it was about 4 million.",
                      num1Text: "dehydrationbe - deported",
                      num2Text: "trauma - immigrate",
                      num3Text: "starvation - emigrate",
                      num4Text: "fatiguebe - detained",
                      answer: 3),
        QuestionModel(num: 14,
                      questionText: "",
                      reference: "Today the technology to create the visual component of virtual-reality (VR) experiences is well on its way to becoming widely accessible and affordable. But to work powerfully, virtual reality needs to be about more than visuals.      (A)      what you are hearing convincingly matches the visuals, the virtual experience breaks apart. Take a basketball game. If the players, the coaches, the announcers, and the crowd all sound like they’re sitting midcourt, you may as well watch the game on television―you’ll get just as much of a sense that you are “there.”      (B)     , today’s audio equipment and our widely used recording and reproduction formats are simply inadequate to the task of re-creating convincingly the sound of a battlefield on a distant planet, a basketball game at courtside, or a symphony as heard from the first row of a great concert hall.",
                      num1Text: "If - By contrast",
                      num2Text: "Unless - Consequently",
                      num3Text: "If - Similarly",
                      num4Text: "Unless - Unfortunately",
                      answer: 4),
        QuestionModel(num: 15,
                      questionText: "주어진 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "The same thinking can be applied to any number of goals, like improving performance at work.",
                      reference2: "The happy brain tends to focus on the short term. ( ① ) That being the case, it’s a good idea to consider what short-term goals we can accomplish that will eventually lead to accomplishing long-term goals. ( ② ) For instance, if you want to lose thirty pounds in six months, what short-term goals can you associate with losing the smaller increments of weight that will get you there? ( ③ ) Maybe it’s something as simple as rewarding yourself each week that you lose two pounds. ( ④ ) By breaking the overall goal into smaller, shorter-term parts, we can focus on incremental accomplishments instead of being overwhelmed by the enormity of the goal in our profession.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 16,
                      questionText: "우리말을 영어로 잘못 옮긴 것은?",
                      num1Text: "혹시 내게 전화하고 싶은 경우에 이게 내 번호야.\n→ This is my number just in case you would like to call me.",
                      num2Text: "나는 유럽 여행을 준비하느라 바쁘다.\n→ I am busy preparing for a trip to Europe.",
                      num3Text: "그녀는 남편과 결혼한 지 20년 이상 되었다.\n→ She has married to her husband for more than two decades.",
                      num4Text: "나는 내 아들이 읽을 책을 한 권 사야 한다.\n→ I should buy a book for my son to read.",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "다음 글의 내용과 일치하지 않는 것을 고르시오. [17~18]",
                      reference: "In the nineteenth century, the most respected health and medical experts all insisted that diseases were caused by “miasma,” a fancy term for bad air. Western society’s system of health was based on this assumption: to prevent diseases, windows were kept open or closed, depending on whether there was more miasma inside or outside the room; it was believed that doctors could not pass along disease because gentlemen did not inhabit quarters with bad air. Then the idea of germs came along. One day, everyone believed that bad air makes you sick. Then, almost overnight, people started realizing there were invisible things called microbes and bacteria that were the real cause of diseases. This new view of disease brought sweeping changes to medicine, as surgeons adopted antiseptics and scientists invented vaccines and antibiotics. But, just as momentously, the idea of germs gave ordinary people the power to influence their own lives. Now, if you wanted to stay healthy, you could wash your hands, boil your water, cook your food thoroughly, and clean cuts and scrapes with iodine.",
                      num1Text: "In the nineteenth century, opening windows was irrelevant to the density of miasma.",
                      num2Text: "In the nineteenth century, it was believed that gentlemen did not live in places with bad air.",
                      num3Text: "Vaccines were invented after people realized that microbes and bacteria were the real cause of diseases.",
                      num4Text: "Cleaning cuts and scrapes could help people to stay healthy.",
                      answer: 1),
        QuestionModel(num: 18,
                      questionText: "",
                      reference: "Followers are a critical part of the leadership equation, but their role has not always been appreciated. For a long time, in fact, “the common view of leadership was that leaders actively led and subordinates, later called followers, passively and obediently followed.” Over time, especially in the last century, social change shaped people’s views of followers, and leadership theories gradually recognized the active and important role that followers play in the leadership process. Today it seems natural to accept the important role followers play. One aspect of leadership is particularly worth noting in this regard: Leadership is a social influence process shared among all members of a group. Leadership is not restricted to the influence exerted by someone in a particular position or role; followers are part of the leadership process, too.",
                      num1Text: "For a length of time, it was understood that leaders actively led and followers passively followed.",
                      num2Text: "People’s views of subordinates were influenced by social change.",
                      num3Text: "The important role of followers is still denied today.",
                      num4Text: "Both leaders and followers participate in the leadership process.",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오. [19~20]",
                      reference: "Language proper is itself double-layered. Single noises are only occasionally meaningful: mostly, the various speech sounds convey coherent messages only when combined into an overlapping chain, like different colors of ice-cream melting into one another. In birdsong also, ___________________________________: the sequence is what matters. In both humans and birds, control of this specialized sound-system is exercised by one half of the brain, normally the left half, and the system is learned relatively early in life. And just as many human languages have dialects, so do some bird species: in California, the white-crowned sparrow has songs so different from area to area that Californians can supposedly tell where they are in the state by listening to these sparrows.",
                      num1Text: "individual notes are often of little value",
                      num2Text: "rhythmic sounds are important",
                      num3Text: "dialects play a critical role",
                      num4Text: "no sound-system exists",
                      answer: 1),
        QuestionModel(num: 20,
                      questionText: "",
                      reference: "Nobel Prize-winning psychologist Daniel Kahneman changed the way the world thinks about economics, upending the notion that human beings are rational decision-makers. Along the way, his discipline-crossing influence has altered the way physicians make medical decisions and investors evaluate risk on Wall Street. In a paper, Kahneman and his colleagues outline a process for making big strategic decisions. Their suggested approach, labeled as “Mediating Assessments Protocol,” or MAP, has a simple goal: To put off gut-based decision-making until a choice can be informed by a number of separate factors. “One of the essential purposes of MAP is basically to _____________ intuition,” Kahneman said in a recent interview with The Post. The structured process calls for analyzing a decision based on six to seven previously chosen attributes, discussing each of them separately and assigning them a relative percentile score, and finally, using those scores to make a holistic judgment.",
                      num1Text: "improve",
                      num2Text: "delay",
                      num3Text: "possess",
                      num4Text: "facilitate",
                      answer: 2),
        ]
        let exam = ExamModel(id: 201922, year: 2019, examTypeID: "지방직", subjectID: "영어", questions: questions)
        exam2019.append(exam)
    }
    func saveExam201923() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "(가), (나) 국가에 대한 설명으로 옳은 것은?",
                      reference: "(가)그 나라의 혼인풍속에 여자의 나이가 열 살이 되면 서로 혼인을 약속하고, 신랑 집에서는 (그 여자를) 맞이하여 장성하도록 길러 아내로 삼는다. (여자가) 성인이 되면 다시 친정으로 돌아가게 한다. 여자의 친정에서는 돈을 요구하는데, (신랑 집에서) 돈을 지불한 후 다시 신랑 집으로 돌아온다.\n\n(나)은력(殷曆) 정월에 하늘에 제사를 지내며 나라에서 대회를 열어 연일 마시고 먹고 노래하고 춤추는데, 영고(迎鼓)라고 한다. 이때 형옥(刑獄)을 중단하여 죄수를 풀어 주었다.",
                      num1Text: "(가)－무천이라는 제천행사가 있었다.",
                      num2Text: "(가)－계루부집단이 권력을 장악하였다.",
                      num3Text: "(나)－사출도라는 구역이 있었다.",
                      num4Text: "(나)－철이 많이 생산되어 낙랑과 왜에 수출하였다.",
                      answer: 3),
        QuestionModel(num: 2,
                      questionText: "(나) 시기에 발생한 사건으로 옳은 것은?",
                      reference: "(가) 백제왕이 병력 3만 명을 거느리고 평양성을 공격해 왔다. 왕이 출병하여 막다가 날아오는 화살에 맞아 서거하였다.\n    ⬇︎\n   (나)\n    ⬇︎\n(다) 왕이 보병과 기병 5만 명을 보내 신라를 구원하게 하였다. (고구려군이) 남거성을 통해 신라성에 이르렀는데 그곳에 왜가 가득하였다. 관군이 도착하자 왜적이 퇴각하였다.",
                      num1Text: "태학을 설립하고 율령을 반포하였다.",
                      num2Text: "평양으로 도읍을 옮기고 한성을 함락하였다.",
                      num3Text: "관구검이 이끄는 위나라 군대의 침략을 받았다.",
                      num4Text: "왕이 직접 말갈 병사를 거느리고 요서지방을 공격하였다.",
                      answer: 1),
        QuestionModel(num: 3,
                      questionText: "통일신라의 경제상황에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "왕경에 서시전과 남시전이 설치되었다.",
                      num2Text: "어아주, 조하주 등 고급비단을 생산하여 당나라에 보냈다.",
                      num3Text: "촌락의 토지 결수, 인구 수, 소와 말의 수 등을 파악하였다.",
                      num4Text: "시비법과 이앙법 등의 발달로 농민층에서 광작이 성행하였다.",
                      answer: 4),
        QuestionModel(num: 4,
                      questionText: "다음 서적을 편찬된 시기순으로 바르게 나열한 것은?",
                      reference: "ㄱ. 〖의방유취〗\nㄴ. 〖동의보감〗\nㄷ. 〖향약구급방〗\nㄹ. 〖향약집성방〗",
                      num1Text: "ㄱ→ㄴ→ㄷ→ㄹ",
                      num2Text: "ㄱ→ㄷ→ㄴ→ㄹ",
                      num3Text: "ㄷ→ㄱ→ㄹ→ㄴ",
                      num4Text: "ㄷ→ㄹ→ㄱ→ㄴ",
                      answer: 4),
        QuestionModel(num: 5,
                      questionText: "삼국시대 문화에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "선덕여왕 때에 첨성대를 세웠다.",
                      num2Text: "목탑 양식의 미륵사지석탑이 건립되었다.",
                      num3Text: "가야 출신의 우륵에 의해 가야금이 신라에 전파되었다.",
                      num4Text: "사신도가 그려진 강서대묘는 돌무지무덤으로 축조되었다.",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "다음과 같은 글을 남긴 국왕의 업적에 해당하는 것은?",
                      reference: "우리 동방은 옛날부터 중국의 풍속을 흠모하여 문물과 예악이 모두 그 제도를 따랐으나, 지역이 다르고 인성도 각기 다르므로 꼭 같게 할 필요는 없다. 거란은 짐승과 같은 나라로 풍속이 같지 않고 말도 다르니 의관제도를 삼가 본받지 말라.\n\n－〖고려사〗에서－",
                      num1Text: "물가조절을 위해 상평창을 설치하였다.",
                      num2Text: "기인․사심관제와 함께 과거제를 실시하였다.",
                      num3Text: "혼인정책과 사성정책을 통해 호족을 포섭하였다.",
                      num4Text: "광군 30만을 조직하여 거란의 침략에 대비하였다.",
                      answer: 3),
        QuestionModel(num: 7,
                      questionText: "다음 ㉠～㉣에 들어갈 인물을 바르게 연결한 것은?",
                      reference: "○ ( ㉠ )는/은 〖신편제종교장총록〗을 편찬하였다.\n○ ( ㉡ )는/은 원의 불교인 임제종을 들여와서 전파시켰다.\n○ ( ㉢ )는/은 강진에 백련사를 결사하여 법화신앙을 내세웠다.\n○ ( ㉣ )는/은 〖목우자수심결〗을 지어 마음을 닦고자 하였다.",
                      num1Text: "수기 - 보우 - 요세 - 지눌",
                      num2Text: "의천 - 각훈 - 요세 - 수기",
                      num3Text: "의천 - 보우 - 요세 - 지눌",
                      num4Text: "의천 - 요세 - 각훈 - 수기",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "다음 정책을 추진한 국왕 대에 있었던 사실로 옳은 것은?",
                      reference: "옛적에 관가의 노비는 아이를 낳은 지 7일 후에 입역(立役)하였는데, 아이를 두고 입역하면 어린 아이에게 해로울 것이라 걱정하여 100일간의 휴가를 더 주게 하였다. 그러나 출산에 임박하여 일하다가 몸이 지치면 미처 집에 도착하기 전에 아이를 낳는 경우가 있다. 만일 산기에 임하여 1개월간의 일을 면제하여 주면 어떻겠는가. 가령 저들이 속인다 할지라도 1개월까지야 넘길 수 있겠는가. 상정소(詳定所)로 하여금 이에 대한 법을 제정하게 하라.",
                      num1Text: "사형의 판결에는 삼복법을 적용하였다.",
                      num2Text: "주자소를 설치하여 계미자를 주조하였다.",
                      num3Text: "국방력 강화를 위해 진관체제를 실시하였다.",
                      num4Text: "도평의사사를 개편하여 의정부를 설치하였다.",
                      answer: 1),
        QuestionModel(num: 9,
                      questionText: "밑줄 친 ‘그’에 대한 설명으로 옳은 것은?",
                      reference: "그".underLined+"는 중국 유학을 마치고 귀국한 다음, 국왕에게 황룡사에 9층탑을 세울 것을 건의했다. "+"그".underLined+"가 9층탑 건립을 건의한 데에는 주변 나라의 침입을 막고자 하는 호국정신이 담겨 있다.",
                      num1Text: "화랑이 지켜야 할 세속오계를 지었다.",
                      num2Text: "대국통으로 있으면서 계율을 지키는 일에 힘을 보탰다.",
                      num3Text: "통일 이후의 사회갈등을 통합으로 이끄는 화엄사상을 강조하였다.",
                      num4Text: "일심(一心) 사상을 주장하여 불교 교리의 대립을 극복하고자 하였다.",
                      answer: 2),
        QuestionModel(num: 10,
                      questionText: "다음 자료에 나타난 상황과 관련 있는 사건은?",
                      reference: "경성에는 종묘, 사직, 궁궐과 나머지 관청들이 또한 하나도 남아 있는 것이 없으며, 사대부의 집과 민가들도 종루 이북은 모두 불탔고 이남만 다소 남은 것이 있으며, 백골이 수북이 쌓여서 비록 치우고자 해도 다 치울 수 없다. 경성의 수많은 백성들이 도륙을 당했고 남은 이들도 겨우 목숨만 붙어 있다. 굶어 죽은 시체가 길에 가득하고 진제장(賑濟場)에 나아가 얻어먹는 자가 수천 명이며 매일 죽는 자가 60～70명 이상이다.\n\n－성혼, 〖우계집〗에서－",
                      num1Text: "병자호란",
                      num2Text: "임진왜란",
                      num3Text: "삼포왜란",
                      num4Text: "이괄의 난",
                      answer: 2),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 ‘그’에 대한 설명으로 옳지 않은 것은?",
                      reference: "그".underLined+"와 남은이 임금을 뵈옵고 요동을 공격하기를 요청하였고, 그리하여 급하게 ｢진도(陣圖)｣를 익히게 하였다. 이보다 먼저 좌정승 조준이 휴가를 받아 집에 있을 때, "+"그".underLined+"와 남은이 조준을 방문하여, “요동을 공격하는 일은 지금 이미 결정되었으니 공(公)은 다시 말하지 마십시오.”라고 말하였다.",
                      num1Text: "만권당에서 원의 학자들과 교류하였다.",
                      num2Text: "맹자의 역성혁명론을 조선건국에 적용하였다.",
                      num3Text: "한양 도성의 성문과 궁궐 등의 이름을 지었다.",
                      num4Text: "〖경제문감〗을 저술하여 재상 중심의 정치를 주장하였다.",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "조약 (가), (나) 사이 시기의 경제 상황으로 옳은 것은?",
                      reference: "(가)\n○ 조선국 항구에 머무르는 일본은 쌀과 잡곡을 수출․수입할 수 있다.\n○ 일본국 정부에 소속된 모든 선박은 항세(港稅)를 납부하지 않는다.",
                      reference2: "(나)\n○ 입항하거나 출항하는 각 화물이 세관을 통과할 때에는 세칙에 따라 관세를 납부해야 한다.\n○ 조선 정부가 쌀 수출을 금지하고자 할 때에는 반드시 먼저 1개월 전에 지방관이 일본 영사관에게 통고해야 한다.",
                      num1Text: "메가타 재정고문이 화폐정리사업을 시도하였다.",
                      num2Text: "혜상공국의 폐지 등을 주장한 정변이 발생하였다.",
                      num3Text: "양화진에 청국인 상점을 허용하는 조약이 체결되었다.",
                      num4Text: "함경도 방곡령 사건으로 일본과 외교적 마찰이 일어났다.",
                      answer: 3),
        QuestionModel(num: 13,
                      questionText: "대한제국 시기에 추진된 정책으로 옳지 않은 것은?",
                      num1Text: "시위대와 진위대를 증강하였다.",
                      num2Text: "〖독립신문〗의 창간을 지원하였다.",
                      num3Text: "화폐제도의 개혁과 중앙은행의 창립을 추진하였다.",
                      num4Text: "황실 재정을 담당하는 내장원의 기능을 확대하였다.",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "조선후기 서학과 관련한 설명으로 옳지 않은 것은?",
                      num1Text: "이승훈이 북경에서 영세를 받았다.",
                      num2Text: "윤지충 사건을 계기로 하여 기해박해가 일어났다.",
                      num3Text: "안정복이 천주교를 비판하는 〖천학문답〗을 저술하였다.",
                      num4Text: "최초의 한국인 신부 김대건이 귀국하여 포교 중 순교하였다.",
                      answer: 2),
        QuestionModel(num: 15,
                      questionText: "다음과 같은 강령을 발표한 조직의 활동으로 옳은 것은?",
                      reference: "건국 시기의 헌법상 경제체계는 국민 각개의 균등생활 확보 및 민족 전체의 발전 그리고 국가를 건립 보위함과 연환(連環)관계를 가진다. 그러므로 다음에 나오는 기본 원칙에 따라서 경제 정책을 집행하고자 한다.\n\n가. 규모가 큰 생산기관의 공구와 수단 …(중략)… 은행․전신․교통 등과 대규모 농․공․상 기업 및 성시(城市)공업 구역의 주요한 공용 방산(房産)은 국유로 한다.\n\n나. 적이 침략하여 점령 혹은 시설한 일체 사유자본과 부역자의 일체 소유자본 및 부동산은 몰수하여 국유로 한다.",
                      num1Text: "이승만을 대통령, 이시영을 부통령으로 선출하였다.",
                      num2Text: "자유시 참변을 겪고 러시아 적군에 무장해제를 당하였다.",
                      num3Text: "좌우합작위원회를 구성하고 좌우합작 7원칙을 발표하였다.",
                      num4Text: "미군전략정보국(OSS) 지원 아래 국내 진공작전을 준비하였다.",
                      answer: 4),
        QuestionModel(num: 16,
                      questionText: "다음 선언문의 강령에 따라 활동한 단체에 대한 설명으로 옳은 것은?",
                      reference: "민중은 우리 혁명의 대본영(大本營)이다. 폭력은 우리 혁명의 유일한 무기이다. 우리는 민중 속으로 가서 민중과 손을 맞잡아 끊임없는 폭력－암살, 파괴, 폭동－으로써 강도 일본의 통치를 타도하고 우리 생활에 불합리한 일체의 제도를 개조하여 인류로써 인류를 압박하지 못하며, 사회로써 사회를 박탈하지 못하는 이상적 조선을 건설할지니라.",
                      num1Text: "임시정부 활동에 활기를 불어넣고자 결성하였다.",
                      num2Text: "청산리 지역에서 일본군과 접전을 벌여 대승을 거두었다.",
                      num3Text: "한국독립당, 조선혁명당 등과 함께 민족혁명당을 결성하였다.",
                      num4Text: "원산에서 일본인이 한국인 노동자를 구타한 사건을 계기로 총파업을 일으켰다.",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "밑줄 친 ㉠, ㉡에 대한 설명으로 옳은 것은?",
                      reference: "신고산이 우르르 함흥차 가는 소리에\n㉠"+"지원병".underLined+" 보낸 어머니 가슴만 쥐어뜯고요\n…(중략)…\n신고산이 우르르 함흥차 가는 소리에\n㉡"+"정신대".underLined+" 보낸 어머니 딸이 가엾어 울고요",
                      num1Text: "㉠－ 학생들도 모집 대상이었다.",
                      num2Text: "㉠－ 처음에는 징병제에 따라 동원되기 시작하였다.",
                      num3Text: "㉡－ 국민징용령에 근거한 조직이었다.",
                      num4Text: "㉡－ 물자 공출 장려를 목표로 결성하였다.",
                      answer: 1),
        QuestionModel(num: 18,
                      questionText: "밑줄 친 ‘이때’ 재위한 국왕 대에 있었던 사실로 옳은 것은?",
                      reference: "이때".underLined+" 거두어들인 돈을 ‘스스로 내는 돈’이라는 뜻에서 원납전이라 하였다. 그런데 백성들은 입을 삐쭉거리면서 ‘원납전 즉 원망하며 바친 돈이다.’ 라고 하였다.\n\n－〖매천야록〗에서－",
                      num1Text: "세한도가 제작되었다.",
                      num2Text: "삼정이정청이 설치되었다.",
                      num3Text: "삼군부가 부활되고 삼수병이 강화되었다.",
                      num4Text: "비변사 당상들이 중요한 권력을 장악하였다.",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "다음 법령과 관련한 설명으로 옳은 것은?",
                      reference: "제5조 정부는 다음에 의하여 농지를 취득한다.\n1.다음의 농지는 정부에 귀속한다.\n(가)법령 및 조약에 의하여 몰수 또는 국유로 된 토지\n(나)소유권의 명의가 분명하지 않은 농지",
                      num1Text: "농지 이외 임야도 포함되었다.",
                      num2Text: "신한공사가 보유하던 토지를 분배하였다.",
                      num3Text: "중앙토지행정처가 분배 업무를 주무하였다.",
                      num4Text: "분배받은 농민은 평년 생산량의 30%를 5년간 상환하였다.",
                      answer: 4),
        QuestionModel(num: 20,
                      questionText: "다음은 1960년대 어느 일간지에 실린 사설이다. 밑줄 친 ‘파병’에 대한 설명으로 옳은 것만을 모두 고르면?",
                      reference: "우리는 원했든 원하지 안했든 이미 이 전쟁에 직접적인 관계를 맺었고 "+"파병".underLined+"을 찬반(贊反)하던 국민이 이젠 다 힘과 마음을 합해서 "+"파병".underLined+"된 용사들을 성원하고 있거니와 근대 전쟁이 전투하는 사람만의 전쟁이 아니라 온 국민이 참가하는 ‘총력전’이라는 것을 알고 이 전쟁의 승리를 위해 모든 국민의 단합을 호소하는 바이다.",
                      reference2: "ㄱ.발췌개헌안 통과에 영향을 주었다.\nㄴ.브라운 각서를 체결하는 이유가 되었다.\nㄷ.1960년대 경제개발계획의 추진에 기여하였다.\nㄹ.한․미 상호방위원조협정을 체결하는 계기가 되었다.",
                      num1Text: "ㄱ, ㄴ",
                      num2Text: "ㄱ, ㄷ",
                      num3Text: "ㄴ, ㄷ",
                      num4Text: "ㄷ, ㄹ",
                      answer: 3),
        
        ]
        let exam = ExamModel(id: 201923, year: 2019, examTypeID: "지방직", subjectID: "한국사", questions: questions)
        exam2019.append(exam)
    }
}
