//
//  ExamStore2016.swift
//  HandGosi
//
//  Created by Sy Lee on 2022/08/25.
//
//
/*
 QuestionModel(num: <#T##Int#>,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 2,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 3,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 4,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 5,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 6,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 7,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 8,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 9,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 10,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 11,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 12,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 13,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 14,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 15,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 16,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 17,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 18,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 19,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>),
 QuestionModel(num: 20,
               questionText: <#T##AttributedString#>,
               num1Text: <#T##AttributedString#>,
               num2Text: <#T##AttributedString#>,
               num3Text: <#T##AttributedString#>,
               num4Text: <#T##AttributedString#>,
               answer: <#T##Int#>)
*/
import Foundation

class ExamStore2016 {
    
    var exam2016: [ExamModel] = []
    
    
    init() {
        saveExam201611()
        saveExam201612()
        saveExam201613()
        
        
    }
    //국가직
    func saveExam201611() {
     let questions =
        [
    QuestionModel(num: 1,
                  questionText: "외래어 표기가 옳지 않은 것은?",
                  num1Text: "flash － 플래시",
                  num2Text: "shrimp － 쉬림프",
                  num3Text: "presentation － 프레젠테이션",
                  num4Text: "Newton － 뉴턴",
                  answer: 2),
    QuestionModel(num: 2,
                  questionText: "밑줄 친 보조사의 의미를 설명한 것으로 옳지 않은 것은?",
                  num1Text: "그렇게 천천히 가다가"+"는".underLined+" 지각하겠다.\n－는 : 어떤 대상이 다른 것과 대조됨을 나타냄",
                  num2Text: "웃지"+"만".underLined+" 말고 다른 말을 좀 해 보아라.\n－만 : 다른 것으로부터 제한하여 어느 것을 한정함을 나타냄",
                  num3Text: "단추는 단추"+"대로".underLined+" 모아 두어야 한다.\n－대로 : 따로따로 구별됨을 나타냄",
                  num4Text: "비가 오는데 바람"+"조차".underLined+" 부는구나.\n－조차 : 이미 어떤 것이 포함되고 그 위에 더함을 나타",
                  answer: 1),
    QuestionModel(num: 3,
                  questionText: "다음의 상황에 어울리는 한자 성어로 가장 적절한 것은?",
                  reference: "  김만중의 ‘사씨남정기’에서 사씨는 교씨의 모함을 받아 집에서 쫓겨난다. 사악한 교씨는 문객인 동청과 작당하여 남편인 유한림마저 모함한다. 그러나 결국은 교씨의 사악함이 만천하에 드러나고 유한림이 유배지에서 돌아오자 교씨는 처형되고 사씨는 누명을 벗고 다시 집으로 돌아오게 된다.",
                  num1Text: "교언영색(巧言令色)",
                  num2Text: "절치부심(切齒腐心)",
                  num3Text: "만시지탄(晩時之歎",
                  num4Text: "사필귀정(事必歸正",
                  answer: 4),
    QuestionModel(num: 4,
                  questionText: "다음 글을 읽고 추론한 내용으로 가장 적절한 것은?",
                  reference: "  한 연구원이 어떤 실험을 계획하고 참가자들에게 이렇게 설명했다.\n  “여러분은 지금부터 둘씩 조를 지어 함께 일을 하게 됩니다. 여러분의 파트너는 다른 작업장에서 여러분과 똑같은 일을, 똑같은 노력을 기울여 할 것입니다. 이번 실험에 대한 보수는 각 조당 5만 원입니다.”\n  실험 참가자들이 작업을 마치자 연구원은 참가자들을 세 부류로 나누어 각각 2만 원, 2만 5천 원, 3만 원의 보수를 차등 지급하면서, 그들이 다른 작업장에서 파트너가 받은 액수를 제외한 나머지 보수를 받은 것으로 믿게 하였다.\n  그 후 연구원은 실험 참가자들에게 몇 가지 설문을 했다. ‘보수를 받고 난 후에 어떤 기분이 들었는지, 나누어 받은 돈이 공정하다고 생각하는지’를 묻는 것이었다. 연구원은 설문을 하기 전에 3만 원을 받은 참가자가 가장 행복할 것이라고 예상했다. 그런데 결과는 예상과 달랐다. 3만 원을 받은 사람은 2만 5천 원을 받은 사람보다 덜 행복해 했다. 자신이 과도하게 보상을 받아 부담을 느꼈기 때문이다. 2만 원을 받은 사람도 덜 행복해 한 것은 마찬가지였다. 받아야 할 만큼 충분히 받지 못했다고 생각했기 때문이다.",
                  num1Text: "인간은 공평한 대우를 받을 때 더 행복해 한다.",
                  num2Text: "인간은 남보다 능력을 더 인정받을 때 더 행복해 한다.",
                  num3Text: "인간은 타인과 협력할 때 더 행복해 한다.",
                  num4Text: "인간은 상대를 위해 자신의 몫을 양보했을 때 더 행복해 한다.",
                  answer: 1),
    QuestionModel(num: 5,
                  questionText: "다음 글의 필자가 궁극적으로 강조하는 내용으로 가장 적절한 것은?",
                  reference: "  로마는 ‘마지막으로 보아야 하는 도시’라고 합니다. 장대한 로마 유적을 먼저 보고 나면 다른 관광지의 유적들이 상대적으로 왜소하게 느껴지기 때문일 것입니다. 로마의 자부심이 담긴 말입니다. 그러나 나는 당신에게 제일 먼저 로마를 보라고 권하고 싶습니다. 왜냐하면 로마는 문명이란 무엇인가라는 물음에 대해 가장 진지하게 반성할 수 있는 도시이기 때문입니다. 문명관(文明觀)이란 과거 문명에 대한 관점이 아니라 우리의 가치관과 직결되어 있는 것입니다. 그리고 과거 문명을 바라보는 시각은 그대로 새로운 문명에 대한 전망으로 이어지기 때문입니다.",
                  num1Text: "여행할 때는 로마를 가장 먼저 보는 것이 좋다.",
                  num2Text: "문명을 반성적으로 볼 수 있는 가치관이 필요하다.",
                  num3Text: "문화 유적에 대한 로마인의 자부심은 본받을 만하다.",
                  num4Text: "과거 문명에서 벗어나 새로운 문명을 창조해야 한다.",
                  answer: 2),
    QuestionModel(num: 6,
                  questionText: "글의 제목으로 가장 적절한 것은?",
                  reference: "  평화로운 시대에 시인의 존재는 문화의 비싼 장식일 수 있다. 그러나 시인의 조국이 비운에 빠졌거나 통일을 잃었을 때 시인은 장식의 의미를 떠나 민족의 예언가가 될 수 있고, 민족혼을 불러일으키는 선구자적 지위에 놓일 수도 있다. 예를 들면 스스로 군대를 가지지 못한 채 제정 러시아의 가혹한 탄압 아래 있던 폴란드 사람들은 시인의 존재를 민족의 재생을 예언하고 굴욕스러운 현실을 탈피하도록 격려하는 예언자로 여겼다. 또한 통일된 국가를 가지지 못하고 이산되어 있던 이탈리아 사람들은 시성 단테를 유일한 ‘이탈리아’로 숭앙했고, 제1차 세계대전 때 독일군의 잔혹한 압제 하에 있었던 벨기에 사람들은 베르하렌을 조국을 상징하는 시인으로 추앙하였다.",
                  num1Text: "시인의 생명(生命)",
                  num2Text: "시인의 운명(運命)",
                  num3Text: "시인의 사명(使命)",
                  num4Text: "시인의 혁명(革命)",
                  answer: 3),
    QuestionModel(num: 7,
                  questionText: "㉠〜㉣을 시의 흐름에 맞게 설명한 것으로 적절하지 않은 것은?",
                  reference: "열무 삼십 단을 이고\n시장에 간 우리 엄마\n안 오시네, ㉠"+"해는 시든 지 오래".underLined+"\n나는 ㉡"+"찬밥처럼 방에 담겨".underLined+"\n㉢"+"아무리 천천히 숙제를 해도".underLined+"\n엄마 안 오시네, 배춧잎 같은 발소리 타박타박\n안 들리네, 어둡고 무서워\n㉣"+"금 간 창틈으로 고요히 빗소리".underLined+"\n빈방에 혼자 엎드려 훌쩍거리던\n\n아주 먼 옛날\n지금도 내 눈시울을 뜨겁게 하는\n그 시절, 내 유년의 윗목. \n\n－ 기형도, 〖엄마 걱정〗 －",
                  num1Text: "㉠: 해가 지고 밤이 깊어간 시간의 경과가 나타나 있다.",
                  num2Text: "㉡: 관심 받지 못해 외로운 상황이 나타나 있다.",
                  num3Text: "㉢: 공부하기 싫은 어린이의 마음이 나타나 있다.",
                  num4Text: "㉣: 넉넉하지 않은 가정 형편이 나타나 있다.",
                  answer: 3),
    QuestionModel(num: 8,
                  questionText: "밑줄 친 단어가 상징하는 것과 가장 유사한 것은?",
                  reference: "나 하늘로 돌아가리라.\n새벽빛 와 닿으면 스러지는\n"+"이슬".underLined+" 더불어 손에 손을 잡고,\n\n나 하늘로 돌아가리라.\n노을빛 함께 단둘이서\n기슭에서 놀다가 구름 손짓하면은,\n\n나 하늘로 돌아가리라.\n아름다운 이 세상 소풍 끝내는 날,\n가서, 아름다웠더라고 말하리라…….\n\n－ 천상병, 〖귀천(歸天)〗 －",
                  num1Text: "어머니는 "+"눈물".underLined+"로 진주를 만드신다.",
                  num2Text: "반짝이는 "+"나뭇잎".underLined+"은 어린 아이들의 웃음 같다.",
                  num3Text: "잠을 깨고 나니 고된 인생도 한바탕 "+"꿈".underLined+"처럼 여겨졌다.",
                  num4Text: "얽매인 삶보다는 "+"구름".underLined+" 같은 삶이 훨씬 좋을 때가 있다.",
                  answer: 3),
    QuestionModel(num: 9,
                  questionText: "두 한자어의 의미 관계가 나머지 셋과 다른 것은?",
                  num1Text: "광정(匡正) － 확정(廓正)",
                  num2Text: "부상(扶桑) － 함지(咸池)",
                  num3Text: "중상(中傷) － 비방(誹謗)",
                  num4Text: "갈등(葛藤) － 알력(軋轢)",
                  answer: 2),
    QuestionModel(num: 10,
                  questionText: "다음 대담에 대한 설명으로 적절하지 않은 것은?",
                  reference: "  진행자 : 오늘은 우리의 전통 선박에 대해 재미있게 설명한 책인 우리나라 배 에 대해 교수님과 이야기를 나눠보겠습니다. 김 교수님, 우리나라 전통 선박에 담긴 선조들의 지혜를 설명한 책 내용이 참 흥미롭던데요, 구체적인 사례 하나만 소개해 주시겠습니까?\n  김 교수: 판옥선에 담긴 선조들의 지혜를 소개해 드릴까 합니다. 혹시 판옥선에 대해 들어 보셨나요?\n  진행자 : 자세히는 모르지만 임진왜란 때 사용된 선박이라고 들었습니다.\n  김 교수 : 네, 판옥선은 임진왜란 때 활약한 전투함인데, 우리나라 해양 환경에 적합한 평저 구조로 만들어졌습니다.\n  진행자 : 아, 그렇군요. 교수님, 평저 구조가 무엇인지 말씀해 주시겠습니까?\n  김 교수 : 네, 그건 밑 부분이 넓고 평평하게 만든 구조 입니다. 그 때문에 판옥선은 수심이 얕은 바다 에서는 물론, 썰물 때에도 운항이 가능했죠. 또한 방향 전환도 쉽게 할 수 있었습니다.\n  진행자 : 결국 섬이 많고 수심이 얕으면서 조수 간만의 차가 큰 우리나라 바다 환경에 적합한 구조라는 말씀이시군요?\n  김 교수 : 네. 그렇습니다.\n  진행자 : 선조들의 지혜가 참 대단합니다. 이런 특징을 가진 판옥선이 전투 상황에서는 얼마나 위력적이었는지 궁금한데, 더 설명해 주시겠습니까?",
                  num1Text: "진행자는 김 교수에게 추가 설명을 요청하고 있다.",
                  num2Text: "김 교수는 진행자의 의견에 동조하며 자신의 견해를 수정하고 있다.",
                  num3Text: "김 교수는 진행자의 부탁에 따라 소개할 내용을 선정하여 제시하고 있다.",
                  num4Text: "진행자는 김 교수의 설명을 듣고 자신의 이해가 맞는지 질문을 하고 있다.",
                  answer: 2),
    QuestionModel(num: 11,
                  questionText: "띄어쓰기가 옳은 것은?",
                  num1Text: "그는 우리 시대의 스승이라기 보다는 자상한 어버이이다.",
                  num2Text: "그는 황소 같이 일을 했다.",
                  num3Text: "하루 종일 밥은 커녕 물 한 모금도 마시지 못했다.",
                  num4Text: "내 모자는 그것하고 다르다.",
                  answer: 4),
    QuestionModel(num: 12,
                  questionText: "밑줄 친 어휘의 뜻풀이가 옳지 않은 것은?",
                  num1Text: "해미".underLined+" 때문에 한 치 앞도 보이지 않았다.\n－ 해미 : 바다 위에 낀 짙은 안개",
                  num2Text: "이제는 "+"안갚음".underLined+"할 때가 되었다.\n－ 안갚음 : 남에게 해를 받은 만큼 저도 그에게 해를 다시 줌",
                  num3Text: "그 울타리는 오랫동안 살피지 않아 영 "+"볼썽".underLined+"이 아니었다.\n－ 볼썽 : 남에게 보이는 체면이나 태도",
                  num4Text: "상고대".underLined+"가 있는 풍경을 만났다.\n－ 상고대 : 나무나 풀에 내려 눈처럼 된 서",
                  answer: 2),
    QuestionModel(num: 13,
                  questionText: "밑줄 친 어휘 중 표준어가 아닌 것은?",
                  num1Text: "그는 얼금얼금한 얼굴에 "+"콧망울".underLined+"을 벌름거리면서 웃음을 터뜨렸다.",
                  num2Text: "그 사람 "+"눈초리".underLined+"가 아래로 축 처진 것이 순하게 생겼어.",
                  num3Text: "무슨 일인지 "+"귓밥".underLined+"이 훅 달아오르면서 목덜미가 저린다.",
                  num4Text: "등산을 하고 났더니 "+"장딴지".underLined+"가 땅긴다.",
                  answer: 1),
    QuestionModel(num: 14,
                  questionText: "다음 글에 대한 설명으로 옳지 않은 것은?",
                  reference: "  거사는 이렇게 대답했다.\n  “얼굴이 잘생기고 예쁜 사람은 맑고 아른아른한 거울을 좋아하겠지만, 얼굴이 못생겨서 추한 사람은 오히려 맑은 거울을 싫어할 것입니다. 그러나 잘생긴 사람은 적고 못생긴 사람은 많기 때문에, 만일 맑은 거울 속에 비친 추한 얼굴을 보기 싫어할 것인즉 흐려진 그대로 두는 것이 나을 것입니다. 그래서 차라리 깨쳐 버릴 바에야 먼지에 흐려진 그대로 두는 것이 나을 것입니다. 먼지로 흐리게 된 것은 겉뿐이지 거울의 맑은 바탕은 속에 그냥 남아 있는 것입니다. 만약 잘생기고 예쁜 사람을 만난 뒤에 닦고 갈아도 늦지 않습니다. 아! 옛날에 거울을 보는 사람들은 그 맑은 것을 취하기 위함이었지만, 내가 거울을 보는 것은 오히려 흐린 것을 취하는 것인데, 그대는 이를 어찌 이상스럽게 생각합니까？” 하니 나그네는 아무 대답이 없었다.\n\n － 이규보, 〖경설〗중에서 －",
                  num1Text: "잘생긴 사람이 적고 못생긴 사람이 많다는 말에서 거사의 현실인식을 알 수 있다.",
                  num2Text: "용모에 대한 거사의 논의는 도덕성, 지혜, 안목 등을 비유한 것으로 볼 수 있다.",
                  num3Text: "잘생기고 예쁜 사람을 만난 후 거울을 닦겠다는 말에서 거사가 지닌 처세관을 엿볼 수 있다.",
                  num4Text: "이상주의적이고 결백한 자세로 현실에 맞서고자 하는 거사의 높은 의지가 드러나 있다.",
                  answer: 4),
    QuestionModel(num: 15,
                  questionText: "㉠〜 ㉣을 고친 내용으로 적절하지 않은 것은?",
                  reference: "  자본주의 체제에서 모든 계층의 사람이 똑같이 많이 벌고 잘살기를 바랄 수는 없다. 어느 정도의 소득 격차는 경쟁을 유발하는 동기가 될 수 있다는 것을 부인할 수 없다. ㉠"+"따라서".underLined+" 우리와 같은 양극화 현상의 심화 추세를 그대로 방치한 채 자연 치유되도록 기다릴 수만은 없다. 그동안 단편적인 대책이 나오기는 했으나 ㉡"+"떡 먹은 입 쓸어 치듯".underLined+" 개선은 되지 않고 오히려 악화되어 가고 있음이 역력히 드러나고 있다.\n  과거의 실패를 거울삼아 저소득층 소득 향상을 통한 근본적인 빈부 격차 개선책을 제시하여 빈자에게 희망을 불어넣어야 한다. 그렇다고 고소득자와 대기업을 욕하거나 ㉢"+"경원되어서는".underLined+" 안 된다. 무엇보다 기업 투자와 내수 경기를 일으키는 일이 긴요하다. 그래야 일자리가 생기고 서민 소득도 늘어나게 된다. ㉣"+"또한 자본의 원활한 흐름을 위해 고소득층의 해외 소비 활동도 촉진해야 한다.".underLined+" 그리고 세제 개혁을 통한 재분배 정책을 추진할 필요가 있다. 세제만큼 유효한 재분배 정책 수단도 없다. 동시에 장기적인 관점에서 각 부문의 양극화 개선을 위해 경제 체질과 구조 개선을 서두르지 않으면 안 된다.",
                  num1Text: "㉠－ 문맥에 맞도록 ‘그러나’로 수정한다.",
                  num2Text: "㉡－ 의미가 통하도록 ‘아랫돌 빼서 윗돌 괴듯’으로 수정한다.",
                  num3Text: "㉢－ 어법에 맞도록 ‘경원을 사서는’으로 수정한다.",
                  num4Text: "㉣－ 문단의 통일성에 어긋나므로 삭제한다.",
                  answer: 3),
    QuestionModel(num: 16,
                  questionText: "안긴문장이 주성분으로 쓰이지 않은 것은?",
                  num1Text: "그 학교는 교정이 넓다.",
                  num2Text: "농부들은 비가 오기를 학수고대했다.",
                  num3Text: "아이들이 놀다 간 자리는 항상 어지럽다.",
                  num4Text: "대화가 어디로 튈지 아무도 몰랐다.",
                  answer: 3),
    QuestionModel(num: 17,
                  questionText: "㉠～ ㉣의 밑줄 친 어휘의 한자가 옳지 않은 것은?",
                  reference: "○ 그는 적의 ㉠"+"사주".underLined+"를 받아 내부 기밀을 염탐했다.\n○ 남의 일에 지나친 ㉡"+"간섭".underLined+"을 하지 않기 바랍니다.\n○ 그 선박은 ㉢"+"결함".underLined+"을 지닌 채로 출항을 강행하였다.\n○ 비리 ㉣"+"척결".underLined+"이 그가 내세운 가장 중요한 목표였다.",
                  num1Text: "㉠－ 使嗾",
                  num2Text: "㉡－ 間涉",
                  num3Text: "㉢－ 缺陷",
                  num4Text: "㉣－ 剔抉",
                  answer: 2),
    QuestionModel(num: 18,
                  questionText: "다음 글이 독자에게 웃음을 유발하는 이유를 바르게 설명한 것은?",
                  reference: "  개의 몸에 기생하는 진드기가 있다. 미친 듯이 제 몸을 긁어 대는 개를 붙잡아서 털 속을 헤쳐 보라. 진드기는 머리를 개의 연한 살에 박고 피를 빨아 먹고 산다. 머리와 가슴이 붙어 있는데 어디까지가 배인지 꼬리인지도 분명치 않다. 수컷의 몸길이는 2.5밀리미터, 암컷은 7.5밀리미터쯤으로 핀셋으로 살살 집어내지 않으면 몸이 끊어져 버린다.\n  한번 박은 진드기의 머리는 돌아 나올 줄 모른다. 죽어도 안으로 파고들다가 죽는다. 나는 그 광경을 ‘몰두(沒頭)’라고 부르려 한다.\n\n － 성석제, 〖몰두〗 중에서 －",
                  num1Text: "소리는 같지만 뜻은 전혀 다른 두 단어를 의도적으로 혼란스럽게 섞어 사용해서",
                  num2Text: "일반적으로 예상되는 사건 대신 아주 엉뚱한 사건을 전개해서",
                  num3Text: "묘사하는 대상의 우스꽝스러운 생태를 충분한 거리를 유지한 채 객관적으로 전달해서",
                  num4Text: "어떤 단어를 보통 쓰이는 의미 대신 글자 그대로의 의미로 짐짓 받아들여서",
                  answer: 4),
    QuestionModel(num: 19,
                  questionText: "다음 글의 서술자에 대한 설명으로 가장 적절한 것은?",
                  reference: "  그들은 여전히 이야기를 계속하고 있다.\n  “그래 촌에 들어가면 위험하진 않은가요?”\n  조선에 처음 간다는 시골자가 또다시 입을 벌렸다.\n  “뭘요, 어델 가든지 조금도 염려 없쉐다. 생번이라 하여도 요보는 온순한 데다가, 가는 곳마다 순사요 헌병인데 손 하나 꼼짝할 수 있나요. 그걸 보면 데라우치 상이 참 손아귀 힘도 세지만 인물은 인물이야!”\n  매우 감격한 모양이다.\n  “그래 촌에 들어가서 할 게 뭐예요?”\n  “할 것이야 많지요. 어델 가기로 굶어 죽을 염려는 없지만, 요새 돈 몰 것이 똑 하나 있지요. 자본 없이 힘 안 들고 ……. 하하하.”\n  표독한 위인이 충동이는 수작이다.\n   … (중략) … \n  나는 여기까지 듣고 깜짝 놀랐다. 그 불쌍한 조선 노동자 들이 속아서 지상의 지옥 같은 일본 각지의 공장과 광산으로 몸이 팔리어 가는 것이 모두 이런 도적놈 같은 협잡 부랑배의 술중(術中)에 빠져서 속아 넘어가는구나 하는 생각을 하며 나는 다시 한 번 그자의 상판대기를 치어다보지 않을 수 없었다.\n\n － 염상섭, 〖만세전〗 중에서 －",
                  num1Text: "작품 밖의 전지적 서술자가 일어난 사건의 전말을 전달하고 있다.",
                  num2Text: "작품 속에 등장하는 인물이 다른 인물을 관찰하며 평가하고 있다.",
                  num3Text: "작품 밖에 있는 서술자가 관찰자가 되어 등장인물의 행동을 묘사하고 있다.",
                  num4Text: "작품 속의 서술자가 작품 밖의 서술자와 교차하며 사건을 입체적으로 서술하고 있다.",
                  answer: 2),
    QuestionModel(num: 20,
                  questionText: "다음 글을 근거로 할 때, <보기>의 대화에서 ㉡의 대답이 갖는 특징으로 적절하지 않은 것은?",
                  reference: "  그라이스(Grice)는 원활한 대화 진행을 위한 요건으로 네 가지의 ‘협력의 원리’를 제시한 바 있다. 첫째, 주고받는 대화의 목적에 필요한 만큼만 정보를 제공하고 필요 이상의 정보를 제공하지 말라는 양의 격률이다. 둘째, 진실한 정보만을 제공하도록 노력하고 증거가 불충한 것은 말하지 말라는 질의 격률이다. 셋째, 해당 대화 맥락과 관련되는 말을 하라는 관련성의 격률이다. 넷째, 모호하거나 중의적인 표현을 피하고 간결하고 조리 있게 말하라는 태도의 격률 이다. 그러나 모종의 효과를 위해 이 네 가지의 격률을 위배하는 일은 일상 대화에서 빈번하게 이루어지는데, 일반적으로 언중들은 그것을 자연스럽게 받아들일 뿐 아니라 때에 따라서는 협력의 원리를 지키는 것이 예의에 어긋난 경우도 많다.",
                  reference2: "   <보기>\n대화(1)\n㉠: 체중이 얼마나 되니?\n㉡: "+"55 kg인데 키에 비해 가벼운 편입니다.".underLined+"\n\n대화(2)\n㉠: 얼마 전 시민 운동회가 있었다며?\n㉡: "+"응. 백 미터 달리기에서 비행기보다 빠른 사람을 봤어.".underLined+"\n\n대화(3)\n㉠: 너 몇 살이니?\n㉡: "+"형이 열일곱 살이고, 저는 열다섯 살이지요.".underLined+"\n\n대화(4)\n㉠: 점심은 뭐 먹을래?\n㉡: "+"생각해 보고 마음 내키는 대로요.".underLined,
                  num1Text: "대화(1) : 관련성의 격률을 위배하였다.",
                  num2Text: "대화(2) : 질의 격률을 위배하였다.",
                  num3Text: "대화(3) : 양의 격률을 위배하였다.",
                  num4Text: "대화(4) : 태도의 격률을 위배하였다.",
                  answer: 1)
    
        ]
        
     let exam = ExamModel(id: 201611, year: 2016, examTypeID: "국가직", subjectID: "국어", questions: questions)
        exam2016.append(exam)
    }
    func saveExam201612() {
        let questions =
           [
       QuestionModel(num: 1,
                     questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                     reference: "The campaign to eliminate pollution will prove ________ unless it has the understanding and full cooperation of the public.",
                     num1Text: "enticing",
                     num2Text: "enhanced",
                     num3Text: "fertile",
                     num4Text: "futile",
                     answer: 4),
       QuestionModel(num: 2,
                     questionText: "밑줄 친 부분과 의미가 가장 가까운 것은?",
                     reference: "Up to now, newspaper articles have only "+"scratched the surface of".underLined+" this tremendously complex issue.",
                     num1Text: "superficially dealt with",
                     num2Text: "hit the nail on the head of",
                     num3Text: "seized hold of",
                     num4Text: "positively followed up on",
                     answer: 1),
       QuestionModel(num: 3,
                     questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오. [3～4]",
                     reference: "  A : I'd like to get a refund for this tablecloth I bought here yesterday.\n  B : Is there a problem with the tablecloth?\n  A : It doesn't fit our table and I would like to return it. Here is my receipt.\n  B : I'm sorry, but this tablecloth was a final sale item, and it cannot be refunded.\n  A : _______________________________ \n  B : It's written at the bottom of the receipt.",
                     num1Text: "Nobody mentioned that to me.",
                     num2Text: "Where is the price tag?",
                     num3Text: "What's the problem with it?",
                     num4Text: "I got a good deal on it.",
                     answer: 1),
       QuestionModel(num: 4,
                     questionText: "",
                     reference: "  A : Hello? Hi, Stephanie. I'm on my way to the office. Do you need anything?\n  B : Hi, Luke. Can you please pick up extra paper for the printer?\n  A : What did you say? Did you say to pick up ink for the printer? Sorry, ________________________________\n  B : Can you hear me now? I said I need more paper for the printer.\n  A : Can you repeat that, please?\n  B : Never mind. I'll text you.\n  A : Okay. Thanks, Stephanie. See you soon.",
                     num1Text: "My phone has really bad reception here",
                     num2Text: "I couldn't pick up more paper.",
                     num3Text: "I think I've dialed the wrong number.",
                     num4Text: "I'll buy each item separately this time.",
                     answer: 1),
       QuestionModel(num: 5,
                     questionText: "우리말을 영어로 잘못 옮긴 것은?",
                     num1Text: "나의 이모는 파티에서 그녀를 만난 것을 기억하지 못했다.\n→ My aunt didn't remember meeting her at the party.",
                     num2Text: "나의 첫 책을 쓰는 데 40년이 걸렸다.\n→ It took me 40 years to write my first book.",
                     num3Text: "학교에서 집으로 걸어오고 있을 때 강풍에 내 우산이 뒤집혔다.\n→ A strong wind blew my umbrella inside out as I was walking home from school.",
                     num4Text: "끝까지 생존하는 생물은 가장 강한 생물도, 가장 지적인 생물도 아니고, 변화에 가장 잘 반응하는 생물이다.\n→ It is not the strongest of the species, nor the most intelligent, or the one most responsive to change that survives to the end.",
                     answer: 4),
       QuestionModel(num: 6,
                     questionText: "글의 제목으로 가장 적절한 것은?",
                     reference: "After analyzing a mass of data on job interview results, a research team discovered a surprising reality. Did the likelihood of being hired depend on qualifications? Or was it work experience? In fact, it was neither. It was just one important factor: did the candidate appear to be a pleasant person. Those candidates who had managed to ingratiate themselves were very likely to be offered a position; they had charmed their way to success. Some had made a special effort to smile and maintain eye contact. Others had praised the organization. This positivity had convinced the interviewers that such pleasant and socially skilled applicants would fit well into the workplace, and so should be offered a job.",
                     num1Text: "To Get a Job, Be a Pleasant Person",
                     num2Text: "More Qualifications Bring Better Chances",
                     num3Text: "It Is Ability That Counts, Not Personality",
                     num4Text: "Show Yourself As You Are at an Interview",
                     answer: 1),
       QuestionModel(num: 7,
                     questionText: "글의 내용과 일치하지 않는 것은?",
                     reference: "Most writers lead double lives. They earn good money at legitimate professions, and carve out time for their writing as best they can: early in the morning, late at night, weekends, vacations. William Carlos Williams and Louis-Ferdinand Céline were doctors. Wallace Stevens worked for an insurance company. T.S. Elliot was a banker, then a publisher. Don DeLilo, Peter Carey, Salman Rushdie, and Elmore Leonard all worked for long stretches in advertising. Other writers teach. That is probably the most common solution today, and with every major university and college offering so-called creative writing courses, novelists and poets are continually scratching and scrambling to land themselves a spot. Who can blame them? The salaries might not be big, but the work is steady and the hours are good.",
                     num1Text: "Some writers struggle for teaching positions to teach creative writing courses.",
                     num2Text: "As a doctor, William Carlos Williams tried to find the time to write.",
                     num3Text: "Teaching is a common way for writers to make a living today.",
                     num4Text: "Salman Rushdie worked briefly in advertising with great triumph.",
                     answer: 4),
       QuestionModel(num: 8,
                     questionText: "글의 흐름상 가장 어색한 문장은?",
                     reference: "One of the largest celebrations of the passage of young girls into womanhood occurs in Latin American and Hispanic cultures. This event is called La Quinceañera, or the fifteenth year. ①"+"It acknowledges that a young woman is now of marriageable age.".underLined+" The day usually begins with a Mass of Thanksgiving. ②"+"By comparing the rites of passage of one culture with those of another, we can assess differences in class status.".underLined+" The young woman wears a full-length white or pastel-colored dress and is attended by fourteen friends and relatives who serve as maids of honor and male escorts. ③"+"Her parents and godparents surround her at the foot of the altar.".underLined+" When the Mass ends, other young relatives give small gifts to those who attended, while the Quinceañera herself places a bouquet of flowers on the altar of the Virgin. ④"+"Following the Mass is an elaborate party, with dancing, cake, and toasts.".underLined+" Finally, to end the evening, the young woman dances a waltz with her favorite escort.",
                     num1Text: "",
                     num2Text: "",
                     num3Text: "",
                     num4Text: "",
                     answer: 2),
       QuestionModel(num: 9,
                     questionText: "주어진 문장이 들어갈 위치로 가장 적절한 곳은?",
                     reference: "He dismally fails the first two, but redeems himself in the concluding whale episode, where he does indeed demonstrate courage, honesty, and unselfishness.",
                     reference2: "Disney's work draws heavily from fairy tales, myths, and folklore, which are profuse in archetypal elements. ( ① ) Pinocchio is a good example of how these elements can be emphasized rather than submerged beneath a surface realism. ( ② ) Early in the film, the boy/puppet Pinocchio is told that in order to be a “real boy,” he must show that he is “brave, truthful, and unselfish.” ( ③ ) The three principal episodes of the movie represent ritualistic trials, testing the youth's moral fortitude. ( ④ ) As such, like most of Disney's works, the values in Pinocchio are traditional and conservative, an affirmation of the sanctity of the family unit, the importance of a Higher Power in guiding our destinies, and the need to play by society's rules.",
                     num1Text: "",
                     num2Text: "",
                     num3Text: "",
                     num4Text: "",
                     answer: 4),
       QuestionModel(num: 10,
                     questionText: "글의 내용과 일치하지 않는 것은?",
                     reference: "Stanislavski was fortunate in many ways. He was the son of a wealthy man who could give him the advantages of a broad education, the opportunity to see the greatest exponents of theatre art at home and abroad. He acquired a great reputation because he had set high goals and never faltered along the hard road leading to them. His personal integrity and inexhaustible capacity for work contributed to making him a professional artist of the first rank. Stanislavski was also richly endowed by nature with a handsome exterior, fine voice and genuine talent. As an actor, director and teacher, he was destined to influence and inspire the many who worked with him and under him or who had the privilege of seeing him on the stage.",
                     num1Text: "Stanislavski was born with attractive features.",
                     num2Text: "Stanislavski remained uninfluential on his colleagues throughout his life",
                     num3Text: "Stanislavski's father was affluent enough to support his education.",
                     num4Text: "Stanislavski became a top-ranked artist by the aid of his upright character and untiring competence.",
                     answer: 2),
       QuestionModel(num: 11,
                     questionText: "밑줄 친 부분과 의미가 가장 가까운 것을 고르시오. [11～12]",
                     reference: "It was personal. Why did you have to "+"stick your nose in?".underLined,
                     num1Text: "hurry",
                     num2Text: "interfere",
                     num3Text: "sniff",
                     num4Text: "resign",
                     answer: 2),
       QuestionModel(num: 12,
                     questionText: "",
                     reference: "Newton made "+"unprecedented".underLined+" contributions to mathematics, optics, and mechanical physics.",
                     num1Text: "mediocre",
                     num2Text: "suggestive",
                     num3Text: "unsurpassed",
                     num4Text: "provocative",
                     answer: 3),
       QuestionModel(num: 13,
                     questionText: "어법상 옳은 것은?",
                     num1Text: "Jessica is a much careless person who makes little effort to improve her knowledge.",
                     num2Text: "But he will come or not is not certain.",
                     num3Text: "The police demanded that she not leave the country for the time being.",
                     num4Text: "The more a hotel is expensiver, the better its service is.",
                     answer: 3),
       QuestionModel(num: 14,
                     questionText: "글의 제목으로 가장 적절한 것은?",
                     reference: "Character is a respect for human beings and the right to interpret experience differently. Character admits self-interest as a natural trait, but pins its faith on man's hesitant but heartening instinct to cooperate. Character is allergic to tyranny, irritable with ignorance and always open to improvement. Character is, above all, a tremendous humility before the facts ― an automatic alliance with truth even when that truth is bitter medicine.",
                     num1Text: "Character's Resistance to Truth",
                     num2Text: "How to Cooperate with Characters",
                     num3Text: "The Ignorance of Character",
                     num4Text: "What Character Means",
                     answer: 4),
       QuestionModel(num: 15,
                     questionText: "글의 주제로 가장 적절한 것은?",
                     reference: "Children who under-achieve at school may just have poor working memory rather than low intelligence. Researchers from a university surveyed more than 3,000 primary school children of all ages and found that 10 % of them suffer from poor working memory, which seriously impedes their learning. Nationally, this equates to almost 500,000 children in primary education being affected. The researchers also found that teachers rarely identify poor working memory and often describe children with this problem as inattentive or less intelligent.",
                     num1Text: "children's identification with teachers at school",
                     num2Text: "low intelligence of primary school children",
                     num3Text: "influence of poor working memory on primary school children",
                     num4Text: "teachers' efforts to solve children's working-memory problem",
                     answer: 3),
       QuestionModel(num: 16,
                     questionText: "글의 내용과 일치하는 것은?",
                     reference: "A new study by Harvard researchers may provide a compelling reason to remove canned soup and juice from your dining table. People who ate one serving of canned food daily over the course of five days, the study found, had significantly elevated levels ― more than a tenfold increase ― of bisphenol-A, or BPA, a substance that lines most food and drink cans. Public health officials in the United States have come under increasing pressure to regulate it. Some of the research on BPA shows that it is linked to a higher risk of cancer, heart disease, and obesity. Some researchers, though, counter that its reputation as a health threat to people is exaggerated. The new study published in The Journal of the American Medical Association is the first to measure the amounts of BPA that are ingested when people eat food that comes directly out of a can.",
                     num1Text: "하버드의 새로운 연구가 통조림 음식의 안전성을 입증하였다.",
                     num2Text: "비스페놀 A와 암, 심장병, 비만의 연관성이 과장되었다는 데에 모든 학자들이 동의한다.",
                     num3Text: "통조림 음식으로부터 사람의 몸에 유입된 비스페놀 A의 양이 아직 측정되지 않았다.",
                     num4Text: "미국의 보건 관리들은 비스페놀 A를 규제하라는 압력을 점점 더 받고 있다.",
                     answer: 4),
       QuestionModel(num: 17,
                     questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                     reference: "All animals have the same kind of brain activation during sleep as humans. Whether or not they dream is another question, which can be answered only by posing another one: Do animals have consciousness?",
                     reference2: "(A) These are three of the key aspects of consciousness, and they could be experienced whether or not an animal had verbal language as we do. When the animal's brain is activated during sleep, why not assume that the animal has some sort of perceptual, emotional, and memory experience?\n\n(B) Many scientists today feel that animals probably do have a limited form of consciousness, quite different from ours in that it lacks language and the capacity for propositional or symbolic thought.\n\n(C) Animals certainly can't report dreams even if they do have them. But which pet owner would doubt that his or her favourite animal friend has perception, memory, and emotion?",
                     num1Text: "(A)-(B)-(C)",
                     num2Text: "(A)-(C)-(B)",
                     num3Text: "(B)-(C)-(A)",
                     num4Text: "(C)-(B)-(A)",
                     answer: 3),
       QuestionModel(num: 18,
                     questionText: "밑줄 친 부분 중 어법상 옳은 것은?",
                     reference: "①"+"As the old saying go,".underLined+" you are what you eat. The foods you eat ②"+"obvious affect your body's performance.".underLined+" They may also influence how your brain handles tasks. If your brain handles them well, you think more clearly, and you are more emotionally stable. The right food can ③"+"help you being concentrated,".underLined+" keep you motivated, sharpen your memory, speed your reaction time, reduce stress, and perhaps ④"+"even prevent your brain from aging.".underLined,
                     num1Text: "",
                     num2Text: "",
                     num3Text: "",
                     num4Text: "",
                     answer: 4),
       QuestionModel(num: 19,
                     questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오. [19～20]",
                     reference: "There's a knock at your door. Standing in front of you is a young man who needs help. He's injured and is bleeding. You take him in and help him, make him feel comfortable and safe and phone for an ambulance. This is clearly the right thing to do. But if you help him just because you feel sorry for him, according to Immanuel Kant,_________________ _. Your sympathy is irrelevant to the morality of your action. That's part of your character, but nothing to do with right and wrong. Morality for Kant wasn't just about what you do, but about why you do it. Those who do the right thing don't do it simply because of how they feel: the decision has to be based on reason, reason that tells you what your duty is, regardless of how you happen to feel.",
                     num1Text: "that wouldn't be a moral action at all",
                     num2Text: "your action is founded on reason",
                     num3Text: "then you're exhibiting ethical behavior",
                     num4Text: "you're encouraging him to be an honest person",
                     answer: 1),
       QuestionModel(num: 20,
                     questionText: "",
                     reference: "A group of tribes and genera of hopping reptiles, small creatures of the dinosaur type, seem to have been pushed by competition and the pursuit of their enemies towards the alternatives of extinction or adaptation to colder conditions in the higher hills or by the sea. Among these distressed tribes there was developed a new type of scale ― scales that were elongated into quill-like forms and that presently branched into the crude beginnings of feathers. These quill-like scales lay over one another and formed a heat-retaining covering more efficient than any reptilian covering that had hitherto existed. So they permitted an invasion of colder regions that were otherwise uninhabited. Perhaps simultaneously with these changes there arose in these creatures a greater solicitude for their eggs. Most reptiles are apparently quite careless about their eggs, which are left for sun and season to hatch. But some of the varieties upon this new branch of the tree of life were acquiring a habit of guarding their eggs and________________________________ _. With these adaptations to cold, other internal modifications were going on that made these creatures, the primitive birds, warm-blooded and independent of basking.",
                     num1Text: "hatching them unsuccessfully",
                     num2Text: "leaving them under the sun on their own",
                     num3Text: "keeping them warm with the warmth of their bodies",
                     num4Text: "flying them to scaled reptiles",
                     answer: 3)
       
           ]
           
        let exam = ExamModel(id: 201612, year: 2016, examTypeID: "국가직", subjectID: "영어", questions: questions)
           exam2016.append(exam)
    }
    func saveExam201613() {
        let questions =
           [
       QuestionModel(num: 1,
                     questionText: "(가)와 (나)에 들어갈 역사서에 대한 설명으로 옳은 것?",
                     reference: "○  (가)  은(는) 현존하는 우리나라의 가장 오래된 역사서로 고려 인종 때 편찬되었다. 본기 28권, 연표 3권, 지 9권, 열전 10권 등 총 50권으로 구성되어 있다.\n ○  (나)  은(는) 충렬왕 때 한 승려가 일정한 역사 서술 체계에 구애받지 않고 자유로운 형식으로 저술한 역사서이다. 총 5권으로 구성되었으며, 민간 설화와 불교에 관한 내용들이 많이 수록되어 있다.",
                     num1Text: "(가) － 고조선의 역사를 중시하였다.",
                     num2Text: "(가) － 고구려 계승의식을 강조하였다.",
                     num3Text: "(나) － 민족적 자주의식을 고양하였다.",
                     num4Text: "(나) － 도덕적 합리주의를 표방하였다.",
                     answer: 3),
       QuestionModel(num: 2,
                     questionText: "밑줄 친 ‘그’에 대한 설명으로 옳은 것은?",
                     reference: "그".underLined+"는 즉위하여 정방을 폐지하고 사림원을 설치하는 등의 관제 개혁을 추진하는 한편, 권세가들의 농장을 견제하고 소금 전매제를 실시하여 국가 재정을 확충하고자 하였다.",
                     num1Text: "만권당을 통해 고려와 원나라 학자들의 문화 교류에 힘썼다.",
                     num2Text: "도병마사를 도평의사사로 개편하여 국정을 총괄하게 하였다.",
                     num3Text: "철령 이북의 영토 귀속 문제를 계기로 요동 정벌을 단행하였다.",
                     num4Text: "기철을 비롯한 부원 세력을 숙청하고 자주적 반원 개혁을 추진하였다.",
                     answer: 1),
       QuestionModel(num: 3,
                     questionText: "다음 글을 근거로 할 때, 사료를 탐구하는 자세로 옳지 않은 것은?",
                     reference: "역사라는 말은 사람에 따라 다양한 뜻으로 사용되고 있지만, 일반적으로 ‘과거에 있었던 사실’과 ‘조사되어 기록된 과거’ 라는 두 가지 뜻을 지니고 있다. 즉, 역사는 ‘사실로서의 역사’와 ‘기록으로서의 역사’라는 두 측면이 있다. 전자가 객관적 의미의 역사라면, 후자는 주관적 의미의 역사라 할 수 있다. 우리가 역사를 배운다고 할 때, 이것은 역사가들이 선정하여 연구한 ‘기록으로서의 역사’를 배우는 것이다.",
                     num1Text: "사료는 ‘과거에 있었던 사실’이므로 그대로 ‘사실로서의 역사’ 라고 판단한다.",
                     num2Text: "사료를 이해하기 위해 그 사료가 기록된 당시의 전반적인 시대 상황을 살펴본다.",
                     num3Text: "사료 또한 사람에 의해 ‘기록된 과거’이므로, 기록한 역사가의 가치관을 분석한다.",
                     num4Text: "동일한 사건 또는 같은 시대를 다루고 있는 여러 다른 사료와 비교,검토해 본다.",
                     answer: 1),
       QuestionModel(num: 4,
                     questionText: "다음 결정문에 근거하여 실행된 사실로 옳은 것은?",
                     reference: "조선을 독립시키고 민주국가로 발전시키는 동시에, 가혹한 일본의 조선 통치 잔재를 빨리 청산하기 위해 조선에 임시민주주의 정부를 수립한다.",
                     num1Text: "미․소 공동위원회가 개최되었다.",
                     num2Text: "서울에서 건국준비위원회가 조직되었다.",
                     num3Text: "유엔 감시 하에 남한에서 총선거가 실시되었다.",
                     num4Text: "한반도에서 미군과 소련군의 군정이 시작되었다.",
                     answer: 1),
       QuestionModel(num: 5,
                     questionText: "밑줄 친 ‘사건’에 대한 설명으로 옳은 것은?",
                     reference: "4 ～ 5명의 개화당이 "+"사건".underLined+"을 일으켜서 나라를 위태롭게 한 다음 청나라 사람의 억압과 능멸이 대단하였다. …(중략)… 종전에는 개화가 이롭다고 말하면 그다지 싫어하지 않았으나 이 "+"사건".underLined+" 이후 조야(朝野) 모두 ‘개화당은 충의를 모르고 외인과 연결하여 매국배종(賣國背宗)하였다’고 하였다.\n\n - 〖윤치호일기〗 -",
                     num1Text: "정동구락부 세력이 주도하였다.",
                     num2Text: "일본군과 함께 경복궁을 침범하였다.",
                     num3Text: "차관 도입을 위한 수신사 파견의 계기가 되었다.",
                     num4Text: "일본 공사관이 불타고 일본군이 청군에 패퇴하였다.",
                     answer: 4),
       QuestionModel(num: 6,
                     questionText: "개항기 체결된 통상 협약에 대한 설명으로 옳지 않은 것은?",
                     num1Text: "조․일 통상장정(1876) － 곡물 유출을 막는 방곡령 규정이 합의되었다.",
                     num2Text: "조․청 수륙무역장정(1882) － 서울에서 청국 상인의 개점이 허용되었다.",
                     num3Text: "개정 조․일 통상장정(1883) － 일본과 수출입하는 물품에 일정 세율이 부과되었다.",
                     num4Text: "한․청 통상조약(1899) － 대한제국 황제와 청 황제가 대등한 위치에서 조약을 체결하였다.",
                     answer: 1),
       QuestionModel(num: 7,
                     questionText: "(가) ∼ (라)의 시기에 해당하는 백제 역사에 대한 설명으로 옳지 않은 것은?",
                     imgModel: ImageModel(imageString: "201613-7", imgWidth: 330, imgHeight: 100),
                     num1Text: "(가) － 관등제를 정비하고 공복제를 도입하는 등 국가 통치 체제의 근간을 마련하였다.",
                     num2Text: "(나) － 남쪽의 마한 잔여 세력을 정복하고, 수군을 정비하여 요서 지방까지 진출하였다.",
                     num3Text: "(다) － 신라와 연합하여 한강 유역 일부 지역을 수복했으나 얼마 후 신라에게 빼앗겼다.",
                     num4Text: "(라) － 복신과 도침 등이 주류성에서 군사를 일으켜 사비성의 당나라 군대를 공격하였다.",
                     answer: 2),
       QuestionModel(num: 8,
                     questionText: "다음 자료에 나타난 통일신라시대의 신분층과 연관된 설명으로 옳은 것은?",
                     reference: "(그들의) 집에는 녹(祿)이 끊이지 않았다. 노동(奴僮)이 3천 명이며, 비슷한 수의 갑병(甲兵)이 있다. 소, 말, 돼지는 바다 가운데 섬에서 기르다가 필요할 때 활로 쏘아 잡아 먹는다. 곡식을 남에게 빌려 주어 늘리는데, 기간 안에 갚지 못하면 노비로 삼아 부린다.\n\n－ 〖신당서〗 -",
                     num1Text: "관등 승진의 상한은 아찬까지였다.",
                     num2Text: "도당 유학생의 대부분을 차지하였다.",
                     num3Text: "돌무지덧널무덤을 묘제로 사용하였다.",
                     num4Text: "식읍․전장 등을 경제적 기반으로 하였다.",
                     answer: 4),
       QuestionModel(num: 9,
                     questionText: "임진왜란 때의 주요 전투를 벌어진 순서대로 바르게 나열한 것은?",
                     reference: "  ㄱ. 권율 장군이 행주산성에서 왜군을 크게 무찔렀다.\n  ㄴ. 조선과 명나라 군대가 합세하여 평양성을 탈환하였다.\n  ㄷ. 진주목사 김시민이 왜의 대군을 맞아 격전 끝에 진주성을 지켜냈다.\n  ㄹ. 이순신 장군이 한산도 앞바다에서 왜의 수군을 격퇴하고 제해권을 장악하였다.",
                     num1Text: "ㄱ → ㄴ → ㄷ → ㄹ",
                     num2Text: "ㄱ → ㄷ → ㄴ → ㄹ",
                     num3Text: "ㄹ → ㄴ → ㄷ → ㄱ",
                     num4Text: "ㄹ → ㄷ → ㄴ → ㄱ",
                     answer: 4),
       QuestionModel(num: 10,
                     questionText: "밑줄 친 ‘이 법’에 대한 설명으로 옳지 않은 것은?",
                     reference: "현물로 바칠 벌꿀 한 말의 값은 본래 목면 3필이지만, 모리배들은 이를 먼저 대납하고 4필 이상을 거두어 갑니다. 이런 폐단을 없애기 위해 "+"이 법".underLined+"을 시행하면 부유한 양반 지주가 원망하고 시행하지 않으면 가난한 농민이 원망 한다는데, 농민의 원망이 훨씬 더 큽니다. 경기와 강원에서 이미 시행하고 있으니 충청과 호남 지역에도 하루빨리 시행 해야 합니다.",
                     num1Text: "토지 결수를 과세 기준으로 삼았다.",
                     num2Text: "인조 때 처음으로 경기도에서 시행하였다.",
                     num3Text: "이 법이 시행된 후에도 왕실에 대한 진상은 계속되었다.",
                     num4Text: "이 법을 시행하면서 관할 관청으로 선혜청을 설치하였다.",
                     answer: 2),
       QuestionModel(num: 11,
                     questionText: "밑줄 친 ‘왕’ 때의 사실로 옳은 것은?",
                     reference: "○ "+"왕".underLined+" 재위 2년에 전진 국왕 부견이 사신과 승려 순도를 보내며 불상과 경문을 전해왔다. (이에 우리) 왕께서 사신을 보내 사례하며 토산물을 보냈다.\n\n○ "+"왕".underLined+" 재위 5년에 비로소 초문사를 창건하고 순도를 머물게 하였다. 또 이불란사를 창건하고 아도를 머물게 하였다. 이것이 해동 불법(佛法)의 시작이었다.\n\n － 삼국사기",
                     num1Text: "역사서인 〖신집〗을 편찬하였다.",
                     num2Text: "진휼 제도로 진대법을 도입하였다.",
                     num3Text: "유학 교육 기관인 태학을 설치하였다.",
                     num4Text: "왜에 종이와 먹의 제작 방법을 전해 주었다.",
                     answer: 3),
       QuestionModel(num: 12,
                     questionText: "1920년대 만주지역 독립운동에 대한 설명으로 옳지 않은 것은?",
                     num1Text: "대종교 계통 인사들이 신민부를 결성하였다.",
                     num2Text: "독립군 연합부대가 봉오동 전투에서 승리하였다.",
                     num3Text: "민족 유일당운동의 일환으로 국민부를 결성하였다.",
                     num4Text: "한국독립군이 한․중 연합작전으로 동경성에서 승리하였다.",
                     answer: 4),
       QuestionModel(num: 13,
                     questionText: "다음 자료와 같은 현상이 나타난 시기의 사회 모습에 대한 설명 으로 옳지 않은 것은?",
                     reference: "근래 세상의 도리가 점점 썩어가서 돈 있고 힘 있는 백성들이 갖은 방법으로 군역을 회피하고 있다. 간사한 아전과 한통속이 되어 뇌물을 쓰고 호적을 위조하여 유학(幼學)이라 칭하면서 면역하거나 다른 고을로 옮겨 가서 스스로 양반 행세를 하기도 한다. 호적이 밝지 못하고 명분의 문란함이 지금보다 심한 적이 없다.\n\n 〖일성록〗",
                     num1Text: "사족들이 형성한 동족 마을이 증가하였다.",
                     num2Text: "향회가 수령의 부세자문기구로 변질되었다.",
                     num3Text: "유향소를 통제하기 위하여 경재소가 설치되었다.",
                     num4Text: "부농층이 관권과 결탁하여 향임직에 진출하였다.",
                     answer: 3),
       QuestionModel(num: 14,
                     questionText: "밑줄 친 ‘이 사람’에 대한 설명으로 옳은 것은?",
                     reference: "이 사람".underLined+"은 34세에 문과에 급제하여 관직 생활을 시작하였지만 곧 모친상을 당하여 3년간 상복을 입었다. 삼년상이 끝나고 관직에 복귀하였으나 을사사화 등으로 조정이 어지러워지자 이내 관직 생활의 뜻을 접고, 1546년 40대 중반의 나이에 향리로 퇴거하여 학문 연구에 전념하였다. 이후 경상도 풍기군수로 있으면서 주세붕이 창설한 백운동서원에 대한 사액을 청원하여 실현을 보게 되었으니, 이것이 조선 왕조 최초의 사액서원인 ‘소수서원’이다.",
                     num1Text: "서리망국론을 부르짖으며 당시 서리의 폐단을 강력하게 비판 하였다.",
                     num2Text: "아홉 차례의 과거 시험에 모두 장원하여 ‘구도장원공’이라는 별칭을 얻었다.",
                     num3Text: "주희의 성리설을 받아들였으며, 이기철학에서 이(理)의 절대성을 주장하였다.",
                     num4Text: "우주자연은 기(氣)로 구성되어 있으며, 기는 영원불멸하면서 생명을 낳는다고 보았다.",
                     answer: 3),
       QuestionModel(num: 15,
                     questionText: "다음 선언문을 강령으로 했던 단체의 활동으로 옳지 않은 것은?",
                     reference: "우리는 일본 강도 정치 즉 이족 통치가 우리 조선 민족 생존의 적임을 선언하는 동시에, 우리는 혁명 수단으로 우리 생존의 적인 강도 일본을 살벌함이 곧 우리의 정당한 수단임을 선언하노라.",
                     num1Text: "민족혁명당 창당에 가담하였다.",
                     num2Text: "경성 부민관에 폭탄을 투척하였다.",
                     num3Text: "일본 제국의회와 황궁을 공격할 계획을 세웠다.",
                     num4Text: "임시정부 요인과 제휴한 투탄 계획을 추진하였다.",
                     answer: 2),
       QuestionModel(num: 16,
                     questionText: "다음 상황이 나타난 시기에 추진한 정부 정책으로 옳지 않은 것은?",
                     reference: "외국 사람들이 조계지를 지키지 않고 도성의 좋은 곳에 있는 집은 후한 값으로 사고 터를 넓히니 잔폐(殘廢)한 인민의 거주지가 침범을 당한다. 또한 여러 해 동안 도로를 놓고 있기 때문에 집들이 줄어들었다. 탑동(塔洞) 등지에 집을 헐고 공원을 만든다 하니 …(중략)… 결국 집 없는 사람이 태반이 될 것이다.\n\n － 매일신문 －",
                     num1Text: "경운궁을 정궁으로 삼았다.",
                     num2Text: "한성은행, 대한천일은행 등 민족계 은행을 지원하였다.",
                     num3Text: "중추원을 개조하여 우리 옛 법령과 풍속을 연구하였다.",
                     num4Text: "한성전기회사를 통하여 서울에 전차노선을 개통하였다",
                     answer: 3),
       QuestionModel(num: 17,
                     questionText: "밑줄 친 ‘이 사상’에 대한 설명으로 옳지 않은 것은?",
                     reference: "신라 말기에 도선과 같은 선종 승려들이 중국에서 유행한 "+"이 사상".underLined+"을 전하였다. 이는 산세와 수세를 살펴 도읍․주택․ 묘지 등을 선정하는, 경험에 의한 인문 지리적 사상이다. 아울러 지리적 요인을 인간의 길흉 화복과 관련하여 생각하는 자연관 및 세계관을 내포하고 있다.",
                     num1Text: "신라 말기에 안정된 사회를 염원하는 일반 백성의 인식이 반영되었다.",
                     num2Text: "신라 말기에 호족이 자기 지역의 중요성을 자부하는 근거로 이용하였다.",
                     num3Text: "고려시대에 묘청이 서경 천도의 필요성을 주장하는 논리로 활용하였다.",
                     num4Text: "고려시대에 국가와 왕실의 안녕과 번영을 기원하는 초제로 행하여졌다.",
                     answer: 4),
       QuestionModel(num: 18,
                     questionText: "전시과 제도의 변천 과정을 나타낸 것이다. (가) 제도에 대한 <보기>의 설명으로 옳은 것만을 모두 고른 것은?",
                     reference: "  ㄱ. 4색 공복을 기준으로 등급을 나누었다.\n  ㄴ. 산직(散職)이 전시의 지급 대상에서 배제되었다.\n  ㄷ. 등급별 전시의 지급 액수가 전보다 감소하였다.\n  ㄹ. 무반과 일반 군인에 대한 대우가 전반적으로 향상되었다.",
                     imgModel: ImageModel(imageString: "201613-18", imgWidth: 330, imgHeight: 120),
                     num1Text: "ㄱ, ㄴ",
                     num2Text: "ㄷ, ㄹ",
                     num3Text: "ㄱ, ㄴ, ㄷ",
                     num4Text: "ㄴ, ㄷ, ㄹ",
                     answer: 4),
       QuestionModel(num: 19,
                     questionText: "(가)와 (나) 시기 고조선에 대한 <보기>의 설명으로 옳은 것만을 고른 것은?",
                     reference: "  ㄱ. (가) － 왕 아래 대부, 박사 등의 직책이 있었다.\n  ㄴ. (가) － 고조선 지역에 한(漢)의 창해군이 설치되었다.\n  ㄷ. (나) － 철기 문화를 본격적으로 수용하며, 중계 무역의 이득을 취하였다.\n  ㄹ. (나) － 비파형동검과 고인돌의 분포를 통하여 통치 지역을 알 수 있다.",
                     imgModel: ImageModel(imageString: "201613-19", imgWidth: 330, imgHeight: 150),
                     num1Text: "ㄱ, ㄷ",
                     num2Text: "ㄱ, ㄹ",
                     num3Text: "ㄴ, ㄷ",
                     num4Text: "ㄴ, ㄹ",
                     answer: 1),
       QuestionModel(num: 20,
                     questionText: "다음 법령에 대한 설명으로 옳은 것은?",
                     reference: "제17관 임시토지조사국은 토지대장 및 지도를 작성하고, 토지의 조사 및 측량한 것을 사정하여 확정한 사항 또는 재결을 거친 사항을 이에 등록한다.",
                     num1Text: "토지와 임야를 함께 조사하도록 하였다.",
                     num2Text: "토지 등급은 물론 지적, 결수, 지목 등을 신고하도록 하였다.",
                     num3Text: "지역별 지가와 그것의 1.3 %를 지세로 하는 과세 표준을 명시하였다.",
                     num4Text: "본 법령에 따라 토지 소유를 증명하는 토지가옥증명규칙과 시행세칙이 공포되었다.",
                     answer: 2)
       
           ]
        let exam = ExamModel(id: 201613, year: 2016, examTypeID: "국가직", subjectID: "한국사", questions: questions)
           exam2016.append(exam)
    }
}

