//
//  PreviewProviders.swift
//  HandGosi
//
//  Created by Sy Lee on 2022/08/05.
//

import Foundation
import SwiftUI

extension PreviewProvider {
    static var dev: DevPreview {
       return DevPreview.shared
    }
}
class DevPreview {
    static let shared = DevPreview()
    
    let exams: [ExamModel]
    
    = [ ExamModel(id: 202211,
                  year: 2022,
                  examTypeID: "국가직",
                  subjectID: "국어",
                  questions:[
                    QuestionModel(num: 1,
                                  questionText: "밑줄 친 말의 쓰임이 옳지 않은 것은?",
                                  num1Text: "그는 아까운 능력을 " + "썩히고".underLined + " 있다.",
                                  num2Text: "음식물 쓰레기를 " + "썩혀서".underLined + " 거름으로 만들었다.",
                                  num3Text: "나는 이제까지 부모님 속을 " + "썩혀".underLined + "본 적이 없다.",
                                  num4Text: "그들은 새로 구입한 기계를 창고에서 " + "썩히고".underLined + " 있다.",
                                  answer: 3) ,
                    QuestionModel(num: 2,
                                  questionText: "(가)~(라)를 고쳐 쓴 것으로 옳지 않은 것은?",
                                  reference: "(가) 오빠는 생김새가 나하고는 많이 틀려.\n(나) 좋은 결실이 맺어졌으면 하는 바람입니다.\n(다) 내가 오직 바라는 것은 네가 잘됐으면 좋겠어.\n(라) 신은 인간을 사랑하기도 하지만 시련을 주기도 한다.",
                                  num1Text: "(가): 오빠는 생김새가 나하고는 많이 달라.",
                                  num2Text: "(나): 좋은 결실을 맺었으면 하는 바램입니다.",
                                  num3Text: "(다): 내가 오직 바라는 것은 네가 잘됐으면 좋겠다는 거야.",
                                  num4Text: "(라): 신은 인간을 사랑하기도 하지만 인간에게 시련을 주기도 한다.",
                                  answer: 2),
                    QuestionModel(num: 3,
                                  questionText: "사자성어의 쓰임이 적절하지 않은 것은?",
                                  num1Text: "그는 구곡간장(九曲肝腸)이 끊어지는 듯한 슬픔에 빠졌다.",
                                  num2Text: "학문의 정도를 걷지 않고 곡학아세(曲學阿世)하는 이가 있다.",
                                  num3Text: "이유 없이 친절한 사람은 구밀복검(口蜜腹劍)일 수 있으니 조심해야 한다.",
                                  num4Text: "신중한 태도로 문제의 본질에 접근하는 당랑거철(螳螂拒轍)의 자세가 필요하다.",
                                  answer: 4),
                    QuestionModel(num: 4,
                                  questionText: "다음 대화에서 나타난 ‘지민’의 의사소통 방식으로 가장 적절한 것은?",
                                  reference: "정수: 지난번에 너랑 같이 들었던 면접 전략 강의가 정말 유익했어.\n\n지민: 그랬어? 나도 그랬는데.\n\n정수: 특히 아이스크림 회사의 면접 내용이 도움이 많이 됐어.\n\n지민: 맞아. 그중에서도 두괄식으로 답변하라는 첫 번째 내용이 정말 인상적이더라. 핵심 내용을 먼저 말하는 전략이 면접에서 그렇게 효과적일 줄 몰랐어.\n\n정수: 어! 그래? 나는 두 번째 내용이 훨씬 더 인상적이었는데.\n\n지민: 그랬구나. 하긴 아이스크림 매출 증가에 관한 통계 자료를 인용해서 답변한 전략도 설득력이 있었어. 하지만 초두 효과의 효용성도 크지 않을까 해.\n\n정수: 그렇긴 해.",
                                  num1Text: "자신의 면접 경험을 예로 들어 상대방을 설득하고 있다.",
                                  num2Text: "상대방의 약점을 공략하며 상대방의 이견을 반박하고 있다.",
                                  num3Text: "상대방의 견해를 존중하면서 자신의 의견을 제시하고 있다.",
                                  num4Text: "상대방과의 갈등 해소를 위해 자신의 감정을 표현하고 있다.",
                                  answer: 3),
                    QuestionModel(num: 5,
                                  questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                                  reference: " 승상이 말을 마치기도 전에 구름이 걷히더니 노승은 간 곳이 없고 좌우를 돌아보니 팔낭자도 간 곳이 없었다. 승상이 놀라 어찌할 바를 모르는 중에 높은 대와 많은 집들이 한순간에 사라지고 자기의 몸은 작은 암자의 포단 위에 앉아 있었는데, 향로의 불은 이미 꺼져 있었고 지는 달이 창가에 비치고 있었다.\n 자신의 몸을 보니 백팔염주가 걸려 있고 머리를 손으로 만져보니 갓 깎은 머리털이 까칠까칠하더라. 완연한 소화상의 몸이요, 전혀 대승상의 위의가 아니었으니, 이에 제 몸이 인간 세상의 승상 양소유가 아니라 연화도량의 행자 성진임을 비로소 깨달았다.\n 그리고 생각하기를, ‘처음에 스승에게 책망을 듣고 풍도옥으로 가서 인간 세상에 환도하여 양가의 아들이 되었지. 그리고 장원급제를 하여 한림학사가 된 후 출장입상하고 공명신퇴하여 두 공주와 여섯 낭자로 더불어 즐기던 것이 다 하룻밤 꿈이었구나. 이는 필시 사부가 나의 생각이 그릇됨을 알고 나로 하여금 이런 꿈을 꾸게 하시어 인간 부귀와 남녀 정욕이 다 허무한 일임을 알게 하신 것이로다.’\n\n - 김만중, 〖구운몽〗 에서",
                                  num1Text: "‘양소유’는 장원급제를 하여 한림학사가 되었다.",
                                  num2Text: "‘양소유’는 인간 세상에 환멸을 느껴 스스로 ‘성진’의 모습으로 되돌아왔다.",
                                  num3Text: "‘성진’이 있는 곳은 인간 세상이 아니다.",
                                  num4Text: "‘성진’은 자신의 외양을 통해 꿈에서 돌아왔음을 인식한다.",
                                  answer: 2),
                    QuestionModel(num: 6,
                                  questionText: "(가)~(라)의 ㉠~㉣에 대한 설명으로 적절하지 않은 것은?",
                                  reference: "(가) 간밤의 부던 람에 눈서리 치단 말가 " + "㉠낙락장송(落落長松)".underLined + "이 다 기우러 가노ᄆᆡ 믈며 못다 픤 곳이야 닐러 무슴 리오.\n\n(나) 철령 노픈 봉에 쉬여 넘 져 구룸아 고신원루(孤臣寃淚) 비 사마 여다가 " + "㉡님".underLined + " 계신 구중심처(九重深處)에 려 본들 엇리.\n\n(다) 이화우(梨花雨) 흣릴 제 울며 잡고 이별 님 추풍낙엽(秋風落葉)에 " + "㉢저".underLined + "도 날 각가 천리(千里)에 외로온 만 오락가락 노매.\n\n(라) 삼동(三冬)의 뵈옷 닙고 암혈(巖穴)의 눈비 마자 구롬  볏뉘도  적이 업건마 서산의 " + "㉣ ".underLined + "디다 니 그 셜워 노라.",
                                  num1Text: "㉠은 억울하게 해를 입은 충신을 가리킨다.",
                                  num2Text: "㉡은 궁궐에 계신 임금을 가리킨다.",
                                  num3Text: "㉢은 헤어진 연인을 가리킨다.",
                                  num4Text: "㉣은 오랜 세월을 함께한 벗을 가리킨다.",
                                  answer: 4),
                    QuestionModel(num: 7,
                                  questionText: "㉠~㉢에 들어갈 말로 가장 적절한 것은?",
                                  reference: "○ 그들의 끈기가 이 경기의 승패를 [㉠] 했다.\n○ 올해 영화제 시상식은 11개 [㉡]으로 나뉜다.\n○ 그 형제는 너무 닮아서 누가 동생이고 누가 형인지 [㉢]할 수 없다.",
                                  num1Text: "㉠가름 ㉡부문 ㉢구별",
                                  num2Text: "㉠가름 ㉡부분 ㉢구분",
                                  num3Text: "㉠갈음 ㉡부문 ㉢구별",
                                  num4Text: "㉠갈음 ㉡부분 ㉢구분",
                                  answer: 1),
                    QuestionModel(num: 8,
                                  questionText: "다음 글의 ‘동기화단계조직’에 따라 (가)~(마)를 배열한 것으로 가장 적절한 것은?",
                                  reference: " 설득하는 말하기의 메시지를 조직하는 방법으로 ‘동기화 단계 조직’이 있다. 이 방법의 세부 단계는 다음과 같다.\n\n1단계: 주제에 대한 청자의 주의나 관심을 환기한다.\n\n2단계: 특정 문제를 청자와 관련지어 설명함으로써 청자의 요구나 기대를 자극한다.\n\n3단계: 해결 방안을 제시하여 청자의 이해와 만족을 유도한다.\n\n4단계: 해결 방안이 청자에게 어떤 도움이 되는지 구체화한다.\n\n5단계: 구체적인 행동의 내용과 방법을 제시하여 특정 행동을 요구한다.",
                                  reference2: "(가) 지난주 제 친구는 일을 마친 후 자전거를 타고 집으로 돌아오다가 사고를 당해 머리를 다쳤습니다.\n\n(나) 여러분이 자전거를 탈 때 헬멧을 착용하면 머리를 보호할 수 있습니다.\n\n(다) 아마 여러분도 가끔 자전거를 타는 경우가 있을 것입니다. 그런데 매년 2천여 명이 자전거를 타다가 머리를 다쳐 고생한다고 합니다.\n\n(라) 만약 자전거를 타는 모든 사람이 헬멧을 착용한다면 자전거 사고를 당해도 뇌손상을 비롯한 신체 피해를 75 % 줄일 수 있습니다. 또 자전거 타기가 주는 즐거움과 편리함을 안전하게 누릴 수 있습니다.\n\n(마) 자전거를 탈 때는 안전을 위해서 반드시 헬멧을 착용 하시기 바랍니다.",
                                  num1Text: "(가)-(나)-(다)-(라)-(마)",
                                  num2Text: "(가)-(다)-(나)-(라)-(마)",
                                  num3Text: "(가)-(다)-(라)-(나)-(마)",
                                  num4Text: "(가)-(라)-(다)-(나)-(마)",
                                  answer: 2),
                    QuestionModel(num: 9,
                                  questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                                  reference: " 국가정보자원관리원과 ○○시는 빅데이터 기반의 맞춤형 복지 서비스 분석 사업을 수행했다. 국가정보자원관리원은 자체 확보한 공공 데이터와 ○○시로부터 받은 복지 사업 관련 데이터를 활용하여 ‘복지 공감 지도’를 제작하고, 복지 기관 접근성 분석을 통해 취약 지역 지원 방안을 제시했다.\n 복지 공감 지도는 공간 분석 시스템을 활용하여 ○○시에 소재한 복지 기관들의 다양한 지원 항목과 이를 필요로 하는 복지 대상자, 독거노인, 장애인 등의 수급자 현황을 한눈에 확인할 수 있도록 구현한 것이다. 이 지도를 활용하면 복지 혜택이 필요한 지역과 수급자를 빨리 찾아낼 수 있으며, 생필품 지원이나 방문 상담 등 복지 기관의 맞춤형 대응이 가능하고, 최적의 복지 기관 설립 위치를 선정할 수 있다.\n 이 사업을 통해 ○○시는 그동안 복지 기관으로부터 도보로 약 15분 내 위치한 수급자에게 복지 혜택이 집중되고 있는 것도 확인했다. 이에 교통이나 건강 등의 문제로 복지 기관 방문이 어려운 수급자를 위해 맞춤형 복지 서비스가 절실하게 필요한 상황임을 발견하고, 복지 셔틀버스 노선을 4개 증설할 계획을 수립했다.",
                                  num1Text: "빅데이터를 활용하여 복지 사각지대를 줄이는 방안을 마련할 수 있다.",
                                  num2Text: "복지 기관과 수급자 거주지 사이의 거리는 복지 혜택의 정도에 영향을 준다.",
                                  num3Text: "복지 기관 접근성 분석 결과는 복지 셔틀버스 노선 증설의 근거가 된다.",
                                  num4Text: "복지 공감 지도로 복지 혜택에 대한 수급자들의 개별 만족도를 파악할 수 있다.",
                                  answer: 4),
                    QuestionModel(num: 10,
                                  questionText: "㉠~㉣의 사례로 적절하지 않은 것은?",
                                  reference: " 단어의 의미가 변화하는 양상은 다양하다. 첫째, “아침 먹고 또 공부하자.”에서 ‘아침’은 본래의 의미인 ‘하루 중의 이른 시간’을 가리키지 않고 ‘아침에 먹는 밥’이라는 의미로 쓰인다. ‘밥’의 의미가 ‘아침’에 포함되어서 ‘아침’만으로도 ‘아침밥’의 의미를 표현하게 된 것으로, ㉠" + "두 개의 단어가 긴밀한 관계여서 한쪽이 다른 한쪽의 의미까지 포함하는 의미로 변화하게 된 경우".underLined + "이다. 둘째, ‘바가지’는 원래 박의 껍데기를 반으로 갈라 썼던 물건을 가리켰는데, 오늘날에는 흔히 플라스틱 바가지를 가리킨다. 이것은 ㉡" + "언어 표현은 그대로인데 시대의 변화에 따라 지시 대상 자체가 바뀌어서 의미 변화가 발생한 경우".underLined + "이다. 셋째, ‘묘수’는 본래 바둑에서 만들어진 용어이지만 일상적인 언어생활에서도 ‘쉽게 생각해 내기 어려운 좋은 방안’이라는 의미로 사용된다. 이는 ㉢" + "특수한 영역에서 사용되던 말이 일반화되면서 단어의 의미가 변화한 경우".underLined + "에 해당한다. 넷째, 호랑이를 두려워하던 시절에 사람들은 ‘호랑이’라는 이름을 직접 부르기 꺼려서 ‘산신령’이라고 부르기도 했는데, 이는 ㉣" + "심리적인 이유로 특정 표현을 피하려다 보니 그것을 대신하는 단어의 의미에 변화가 생긴 경우".underLined + "이다.",
                                  num1Text: "㉠: ‘아이들의 코 묻은 돈’에서 ‘코’는 ‘콧물’의 의미로 쓰인다.",
                                  num2Text: "㉡: ‘수세미’는 원래 식물의 이름이었지만 오늘날에는 ‘그릇을 씻는 데 쓰는 물건’이라는 의미로 쓰인다.",
                                  num3Text: "㉢: ‘배꼽’은 일반적으로 ‘탯줄이 떨어지면서 배의 한가운데에 생긴 자리’를 가리키지만 바둑에서는 ‘바둑판의 한가운데’ 라는 의미로 쓰인다.",
                                  num4Text: "㉣: 무서운 전염병인 ‘천연두’를 꺼려서 ‘손님’이라고 불렀다.",
                                  answer: 3),
                    QuestionModel(num: 11,
                                  questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                                  reference: " △△시 시장님께\n 안녕하십니까? 저는 △△시에서 농장을 운영하는 ◻︎◻︎◻︎입니다. 이렇게 글을 쓰게 된 것은 우리 농장 근처에 신축된 골프장의 빛 공해 문제에 대해 말씀드리기 위함입니다. 빛이 공해가 될 수 있다는 말이 다소 생소하실 수도 있습니다. 하지만 지나친 야간 조명이 식물의 성장에 부정적인 영향을 끼쳐 작물 수확량을 감소시킬 수 있음은 이미 여러 연구를 통해 입증된 바 있습니다. 좀 늦었지만 △△시에서도 이 문제에 대해 경각심을 가질 필요가 있습니다. 실제로 골프장이 야간 운영을 시작했을 때를 기점으로 우리 농장의 수확률이 현저히 낮아졌음을 제가 확인했습니다. 물론, 이윤을 추구하는 골프장의 야간 운영을 무조건 막는다면 골프장 측에서 반발할 것입니다. 그래서 계절에 따라 야간 운영 시간을 조정하거나 운영 제한에 따른 손실금을 보전해 주는 등의 보완책도 필요합니다. 또한 ○○군에서도 빛 공해 문제를 해결하기 위해 야간 조명의 조도를 조정하는 프로젝트를 진행한 바 있으니 참고해 보시기 바랍니다. 모쪼록 시장님께서 이 문제에 관심을 가지고 농장과 골프장이 상생할 수 있는 정책을 펼쳐 주시기를 부탁드립니다.",
                                  num1Text: "시장에게 빛 공해로 농장이 겪는 어려움에 대해 관심을 촉구하고 있다.",
                                  num2Text: "건의에 대한 신뢰성을 높이기 위해 인용한 자료의 출처를 밝히고 있다.",
                                  num3Text: "다른 지역에서 야간 조명으로 인한 폐해를 해결하기 위해 노력한 사례를 언급하고 있다.",
                                  num4Text: "골프장의 야간 운영을 제한할 때 예상되는 문제점과 그 해결 방안에 대해 제시하고 있다.",
                                  answer: 2),
                    QuestionModel(num: 12,
                                  questionText: "다음 대화의 ㉠~㉣에 대한 설명으로 적절하지 않은 것은?",
                                  reference: "이진: 태민아, ㉠" + "이 책".underLined + " 읽어 봤니?\n\n태민:아니, ㉡" + "그 책".underLined + "은 아직 읽어 보지 못했어.\n\n이진: 그렇구나. 이 책은 작가의 문체가 독특해서 읽어 볼 만해.\n\n태민: 응, 꼭 읽어 볼게. 한 권 더 추천해 줄래?\n\n이진: 그럼 ㉢" + "저 책".underLined + "은 어때? 한국 대중문화를 다양한 시각에서 다룬 재미있는 책이야.\n\n태민:그래, ㉣" + "그 책".underLined + "도 함께 읽어볼게.\n\n이진: (두 책을 들고 계산대로 간다.) 읽어 보겠다고 하니,생일 선물로 ㉤" + "이 책".underLined + " 두 권 사 줄게. \n\n태민: 고마워. 잘 읽을게.",
                                  num1Text: "㉠은 청자보다 화자에게, ㉡은 화자보다 청자에게 가까이 있는 대상을 가리킨다.",
                                  num2Text: "㉢은 화자보다 청자에게 멀리 있는 대상을 가리킨다.",
                                  num3Text: "㉢과 ㉣은 같은 대상을 가리킨다.",
                                  num4Text: "㉤은 ㉡과 ㉢ 모두를 가리킨다.",
                                  answer: 2),
                    QuestionModel(num: 13,
                                  questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                                  reference: " 아동이 부모의 소유물 또는 종족의 유지나 국가의 방위를 위한 수단으로 간주되었던 전근대사회에서는 아동의 권리에 대한 인식이 존재하지 않았다. 산업혁명으로 봉건제도가 붕괴되고 자본주의가 탄생한 근대사회에 이르러 구빈법에 따른 국가 개입과 민간단체의 자발적인 참여로 아동보호가 시작되었다.\n 1922년 잽 여사는 아동권리사상을 담아 아동권리에 대한 내용을 성문화하였다. 이를 기초로 1924년 국제연맹에서는 전문과 5개의 조항으로 된 〖아동권리에 관한 제네바 선언〗을 채택하였다. 여기에는 “아동은 물질적으로나 정신적으로 정상적인 발달을 위해 필요한 조건이 충족되어야 한다.” 라든지 “아동의 재능은 인류를 위해 쓰인다는 자각 속에서 양육되어야 한다.” 등의 내용이 포함되었다.\n 그러나 여기에서도 아동은 보호의 객체로만 인식되었을 뿐 생존, 보호, 발달을 위한 적극적인 권리의 주체로 인식되지는 않았다. 최근에 와서야 국제사회의 노력에 힘입어 아동은 보호되어야 할 수동적인 존재에서 자신의 권리를 주장할 수 있는 능동적인 존재로 자리매김할 수 있게 되었다. 1989년 유엔총회에서 채택된 〖아동권리협약〗이 그것이다.\n 우리나라는 이를 토대로 2016년 〖아동권리헌장〗 9개 항을 만들었다. 이 헌장은 ‘생존과 발달의 권리’, ‘아동이 최선의 이익을 보장 받을 권리’, ‘차별 받지 않을 권리’, ‘자신의 의견이존중될권리’등 유엔의 〖아동권리협약〗의 네 가지 기본 원칙을 포함하고 있다. 또한 전문에는 아동의 권리와 더불어 “부모와 사회, 국가와 지방자치단체는 아동의 이익을 최우선으로 고려해야 하며, 다음과 같은 아동의 권리를 확인하고 실현할 책임이 있다.”라고 명시하여 아동을 둘러싼 사회적 주체들의 책임을 명확히 하였다.",
                                  num1Text: "아동의 권리에 대한 인식은 근대 이후에 형성되었다.",
                                  num2Text: "〖아동권리헌장〗은 〖아동권리협약〗을 토대로 만들어졌다.",
                                  num3Text: "〖아동권리에 관한 제네바 선언〗, 〖아동권리협약〗, 〖아동권리헌장〗에는 모두 아동의 발달에 대한 내용이 들어가 있다.",
                                  num4Text: "〖아동권리에 관한 제네바 선언〗은 아동을 적극적인 권리의 주체로 인식함으로써 아동의 권리에 대한 진전된 성과를 이루었다.",
                                  answer: 4),
                    QuestionModel(num: 14,
                                  questionText: "다음 시에 대한 이해로 적절하지 않은 것은?",
                                  reference: "봄은\n남해에서도 북녘에서도\n오지 않는다.\n\n너그럽고\n빛나는\n봄의 그 눈짓은,\n제주에서 두만까지\n우리가 디딘\n아름다운 논밭에서 움튼다.\n\n겨울은,\n바다와 대륙 밖에서\n그 매운 눈보라 몰고 왔지만\n이제 올\n너그러운 봄은, 삼천리 마을마다\n우리들 가슴속에서\n움트리라.\n\n움터서,\n강산을 덮은 그 미움의 쇠붙이들\n눈 녹이듯 흐물흐물\n녹여버리겠지.\n\n-신동엽, 〖봄은〗-",
                                  num1Text: "현실을 초월한 순수 자연의 세계를 노래하고 있다.",
                                  num2Text: "희망과 신념을 드러내는 단정적 어조로 표현하고 있다.",
                                  num3Text: "시어들의 상징적인 의미를 통해 주제를 형성하고 있다.",
                                  num4Text: "‘봄’과 ‘겨울’의 이원적 대립으로 시상을 전개하고 있다.",
                                  answer: 1),
                    QuestionModel(num: 15,
                                  questionText: "다음 글의 전개 순서로 가장 자연스러운 것은?",
                                  reference: "(가) 이 기관을 잘 수리하여 정련하면 그 작동도 원활하게 될 것이요, 수리하지 아니하여 노둔해지면 그 작동도 막혀 버릴 것이니 이런 기관을 다스리지 아니하고야 어찌 그 사회를 고취하여 발달케 하리오.\n(나) 이러므로 말과 글은 한 사회가 조직되는 근본이요, 사회 경영의 목표와 지향을 발표하여 그 인민을 통합시키고 작동하게 하는 기관과 같다.\n(다) 말과 글이 없으면 어찌 그 뜻을 서로 통할 수 있으며, 그 뜻을 서로 통하지 못하면 어찌 그 인민들이 서로 이어져 번듯한 사회의 모습을 갖출 수 있으리오.\n(라)그뿐 아니라 그 기관은 점점 녹슬고 상하여 필경은 쓸 수 없는 지경에 이를 것이니 그 사회가 어찌 유지될 수 있으리오. 반드시 패망을 면하지 못할지라.\n(마) 사회는 여러사람이 그 뜻을 서로 통하고 그 힘을 서로 이어서 개인의 생활을 경영하고 보존하는 데에 서로 의지하는 인연의 한 단체라.\n\n - 주시경, 〖대한국어문법 발문〗에서 - ",
                                  num1Text: "(마)-(가)-(다)-(나)-(라)",
                                  num2Text: "(마)-(가)-(라)-(다)-(나)",
                                  num3Text: "(마)-(다)-(가)-(라)-(나)",
                                  num4Text: "(마)-(다)-(나)-(가)-(라)",
                                  answer: 4),
                    QuestionModel(num: 16,
                                  questionText: "한자 표기가 옳지 않은 것은?",
                                  num1Text: "오늘 협상에서 만족(滿足)할 만한 성과를 거두었다.",
                                  num2Text: "김 위원의 주장을 듣고 그 의견에 동의하여 재청(再請)했다.",
                                  num3Text: "우리 지자체의 해묵은 문제를 해결(解結)할 방안이 생각났다.",
                                  num4Text: "다수가 그 의견에 동의하지 않았기에 재론(再論)이 필요하다.",
                                  answer: 3),
                    QuestionModel(num: 17,
                                  questionText: "다음 문장이 들어가기에 가장 적절한 곳을 ㉠~㉣에서 고르면?",
                                  reference: " 신분에 따라 문체를 고착화하는 것을 인정하지 않았던 것이다.",
                                  reference2: " 유럽이 교회로부터 정신적으로 해방된 것은 그리스와 로마의 고대 작가들에 대한 재발견을 통해서였다.[ ㉠ ] 그 이후 고대 작가들의 문체는 귀족 중심의 유럽 문화에서 모범으로 여겨졌다. [ ㉡ ] 이러한 상황은 대략 1770년대에 시작되는 낭만주의에서부터 변화하기 시작했다. [ ㉢ ]이 낭만주의 시기에 평등과 민주주의를 꿈꿨던 신흥 시민계급은 문학에서 운문과 영웅적 운명을 귀족에게만 전속시키고 하층민에게는 산문과 우스꽝스러운 상황을 배정하는 전통 시학을 거부했다. [ ㉣ ] 고전 문학은 더 이상 문학의 규범이 아니었으며, 문학을 현실의 모방으로 인식하는 태도도 포기되었다.",
                                  num1Text: "㉠",
                                  num2Text: "㉡",
                                  num3Text: "㉢",
                                  num4Text: "㉣",
                                  answer: 4),
                    QuestionModel(num: 18,
                                  questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                                  reference: " 정거장에 나온 박은 수염도 깎은 지 오래어 터부룩한 데다 버릇처럼 자주 찡그려지는 비웃는 웃음은 전에 못 보던 표정이었다. 그 다니는 학교에서만 지싯지싯* 붙어 있는 것이 아니라 이 시대 전체에서 긴치 않게 여기는, 지싯지싯 붙어 있는 존재 같았다. 현은 박의 그런 지싯지싯함에서 선뜻 자기를 느끼고 또 자기의 작품들을 느끼고 그만 더 울고 싶게 괴로워졌다.\n 한참이나 붙들고 섰던 손목을 놓고, 그들은 우선 대합실로 들어왔다. 할 말은 많은 듯하면서도 지껄여 보고 싶은 말은 골라낼 수가 없었다. 이내 다시 일어나 현은,\n “나 좀 혼자 걸어 보구 싶네.”\n하였다. 그래서 박은 저녁에 김을 만나 가지고 대동강가에 있는 동일관이란 요정으로 나오기로 하고 현만이 모란봉으로 온 것이다.\n 오면서 자동차에서 시가도 가끔 내다보았다. 전에 본 기억이 없는 새 빌딩들이 꽤 많이 늘어섰다. 그중에 한가지 인상이 깊은 것은 어느 큰 거리 한 뿌다귀* 에 벽돌 공장도 아닐테요 감옥도 아닐 터인데 시뻘건 벽돌만으로, 무슨 큰 분묘와 같이 된 건축이 웅크리고 있는 것이다. 현은 운전사에게 물어보니, 경찰서라고 했다.\n\n-이태준, 〖패강랭〗에서-\n\n*지싯지싯: 남이 싫어하는지는 아랑곳하지 아니하고 제가 좋아하는 것만 짓궃게 자꾸 요구하는 모양.\n*뿌다귀: '뿌다구니'의 준말로, 쑥 내밀어 구부러지거나 꺾어져 돌아간 자리.",
                                  num1Text: "‘현’은 예전과 달라진 ‘박’의 태도가 자신의 작품 때문이라고 생각하고 있다.",
                                  num2Text: "‘현’은 자신과 비슷한 처지에 있는 ‘박’을 통해 자신을 연민하고 있다.",
                                  num3Text: "‘현’은 새 빌딩들을 보고 도시가 많이 변화하고 있음을 인지하고 있다.",
                                  num4Text: "‘현’은 시뻘건 벽돌로 만든 경찰서를 보고 암울한 분위기를 느끼고 있다.",
                                  answer: 1),
                    QuestionModel(num: 19,
                                  questionText: "다음 규정에 근거할 때 옳지 않은 것은?",
                                  reference: " 〖한글 맞춤법 제30항〗\n 사이시옷은 다음과 같은 경우에 받치어 적는다.\n(가) 순우리말로 된 합성어로서 앞말이 모음으로 끝나면서 뒷말의 첫소리가 된소리로 나는 것\n(나) 순우리말과 한자어로 된 합성어로서 앞말이 모음으로 끝나면서 뒷말의 첫소리가 된소리로 나는 것",
                                  num1Text: "(가)에 따라 '아래 + 집'은 '아랫집'으로 적는다.",
                                  num2Text: "(가)에 따라 '쇠 + 조각'은 '쇳조각'으로 적는다.",
                                  num3Text: "(나)에 따라 '전세 + 방'은 '전셋방'으로 적는다.",
                                  num4Text: "(나)에 따라 '자리 + 세'는 '자릿세'로 적는다.",
                                  answer: 3),
                    QuestionModel(num: 20,
                                  questionText: "글쓴이의 견해에 부합하는 것은?",
                                  reference: " 문화란 공동체의 구성원들이 공유하는 생각과 행동 양식의 총체라고 할 수 있다. 문화를 연구하는 사람들의 주된 관심사는 특정 생각과 행동 양식이 하나의 공동체 안에서 전파되는 기제이다.\n 이에 대한 견해 중 하나는 문화를 생각의 전염이라는 각도에서 바라보는 것이다. 예컨대, 리처드 도킨스는 ‘밈(meme)’이라는 개념을 통해 생각의 전염 과정을 설명 하고자 했다. 그에 따르면 문화는 복수의 밈으로 이루어져 있는데, 유전자에 저장된 생명체의 주요 정보가 번식을 통해 복제되어 개체군 내에서 확산되듯이, 밈 역시 유전자와 마찬가지로 공동체 내에서 복제를 통해 확산된다.\n 그러나 문화 전파의 기제를 설명하는 이론으로는 밈 이론보다 의사소통 이론이 더 적절해 보인다. 일례로, 요크셔 지역에 내려오는 독특한 푸딩 요리법은 누군가가 푸딩 만드는 것을 지켜본 후 그것을 그대로 따라 하는 방식으로 전파 되었다기보다는 요크셔 푸딩 요리법에 대한 부모와 친척, 친구들의 설명을 통해 입에서 입으로 전파되고 공유되었을 가능성이 크다.\n 생명체의 경우와 달리 문화는 완벽하게 동일한 형태로 전파되지 않는다. 전파된 문화와 그것을 수용한 결과는 큰 틀에서는 비슷하더라도 세부적으로는 다를 수밖에 없다. 다시 말해 요크셔 지방의 푸딩 요리법은 다른 지방의 푸딩 요리법과 변별되는 특색을 지니는 동시에 요크셔 지방 내부에서도 가정이나 개인에 따라 약간씩의 차이를 보인다. 이는 푸딩 요리법의 수신자가 발신자가 전해 준 정보에다 자신의 생각을 덧붙였기 때문인데, 복제의 관점에서 문화의 전파를 설명하는 이론으로는 이와 같은 현상을 설명하기 어렵다. 반면, 의사소통 이론으로는 설명 가능하다. 이에 따르면 사람들은 자신이 들은 이야기를 남에게 전달할 때 들은 이야기에다 자신의 생각을 더해서 그 이야기를 전달하기 때문이다.",
                                  num1Text: "문화의 전파 기제는 밈 이론보다는 의사소통 이론으로 설명하는 것이 적절하다.",
                                  num2Text: "의사소통 이론에 따르면 문화의 수용 과정에는 수용 주체의 주관이 개입하지 않는다.",
                                  num3Text: "의사소통 이론에 따르면 특정 공동체의 문화는 다른 공동체로 복제를 통해 전파될 수 있다.",
                                  num4Text: "요크셔 푸딩 요리법이 요크셔 지방의 가정이나 개인에 따라 세부적인 차이를 보이는 현상은 밈 이론에 의해 설명할 수 있다.",
                                  answer: 1)
        
    ]),
        ExamModel(id: 202212,
                  year: 2022,
                  examTypeID: "국가직",
                  subjectID: "영어",
                  questions: [
            
                    QuestionModel(num: 1,
                                  questionText: "밑줄 친 부분의 의미와 가장 가까운것을 고르시오.",
                                  reference: "For years, detectives have been trying to " + "unravel".underLined + " the mystery of the sudden disappearance of the twin brothers.",
                                  num1Text: "solve",
                                  num2Text: "create",
                                  num3Text: "imitate",
                                  num4Text: "publicize",
                                  answer: 1),
                    QuestionModel(num: 2, questionText: "밑줄친 부분의 의미와 가장 가까운것을 고르시오.", reference: " Before the couple experienced parenthood, their four-bedroom house seemed unnecessarily " + "opulent.".underLined,
                                  num1Text: "hidden",
                                  num2Text: "luxurious",
                                  num3Text: "empty",
                                  num4Text: "solid",
                                  answer: 2),
                    QuestionModel(num: 3,
                                  questionText: "밑줄친 부분의 의미와 가장 가까운것을 고르시오.",
                                  reference: " The boss " + "hit the roof".underLined + " when he saw that we had already spent the entire budget in such a short period of time.",
                                  num1Text: "was very satisfied",
                                  num2Text: "was very surprised",
                                  num3Text: "became extremely calm",
                                  num4Text: "became extremely angry",
                                  answer: 4),
                    QuestionModel(num: 4,
                                  questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한것을 고르시오.",
                                  reference: "A mouse potato is the computer ____________ of television’s couch potato: someone who tends to spend a great deal of leisure time in front of the computer in much the same way the couch potato does in front of the television.",
                                  num1Text: "technician",
                                  num2Text: "equivalent",
                                  num3Text: "network",
                                  num4Text: "simulation",
                                  answer: 2),
                    QuestionModel(num: 5,
                                  questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한것을 고르시오.",
                                  reference: " Mary decided to __________ her Spanish before going to South America.",
                                  num1Text: "brush up on",
                                  num2Text: "hear out",
                                  num3Text: "stick up for",
                                  num4Text: "lay off",
                                  answer: 1),
                    QuestionModel(num: 6,
                                  questionText: "어법상 옳은 것은?",
                                  num1Text: "A horse should be fed according to its individual needs and the nature of its work.",
                                  num2Text: "My hat was blown off by the wind while walking down a narrow street.",
                                  num3Text: "She has known primarily as a political cartoonist throughout her career.",
                                  num4Text: "Even young children like to be complimented for a job done good.",
                                  answer: 1),
                    QuestionModel(num: 7,
                                  questionText: "다음 글의 내용과 일치하지 않는 것은?",
                                  reference: "Umberto Eco was an Italian novelist, cultural critic and philosopher. He is widely known for his 1980 novel The Name of the Rose, a historical mystery combining semiotics in fiction with biblical analysis, medieval studies and literary theory. He later wrote other novels, including Foucault’s Pendulum and The Island of the Day Before. Eco was also a translator: he translated Raymond Queneau’s book Exercices de style into Italian. He was the founder of the Department of Media Studies at the University of the Republic of San Marino. He died at his Milanese home of pancreatic cancer, from which he had been suffering for two years, on the night of February 19, 2016.",
                                  num1Text: "The Name of the Rose is a historical novel.",
                                  num2Text: "Eco translated a book into Italian.",
                                  num3Text: "Eco founded a university department.",
                                  num4Text: "Eco died in a hospital of cancer.",
                                  answer: 4),
                    QuestionModel(num: 8,
                                  questionText: "밑줄 친 부분 중 어법상 옳지 않은 것은?",
                                  reference: "To find a good starting point, one must return to the year 1800 during ①" + "which".underLined + " the first modern electric battery was developed. Italian Alessandro Volta found that a combination of silver, copper, and zinc ②" + "were".underLined + " ideal for producing an electrical current. The enhanced design, ③" + "called".underLined + " a Voltaic pile, was made by stacking some discs made from these metals between discs made of cardboard soaked in sea water. There was ④" + "such".underLined + " talk about Volta’s work that he was requested to conduct a demonstration before the Emperor Napoleon himself.",
                                  num1Text: "which",
                                  num2Text: "were",
                                  num3Text: "called",
                                  num4Text: "such",
                                  answer: 2),
                    QuestionModel(num: 9,
                                  questionText: "다음 글의 제목으로 가장 적절한 것은?",
                                  reference: "Lasers are possible because of the way light interacts with electrons. Electrons exist at specific energy levels or states characteristic of that particular atom or molecule. The energy levels can be imagined as rings or orbits around a nucleus. Electrons in outer rings are at higher energy levels than those in inner rings. Electrons can be bumped up to higher energy levels by the injection of energy for example, by a flash of light. When an electron drops from an outer to an inner level, “excess” energy is given off as light. The wavelength or color of the emitted light is precisely related to the amount of energy released. Depending on the particular lasing material being used, specific wavelengths of light are absorbed (to energize or excite the electrons) and specific wavelengths are emitted (when the electrons fall back to their initial level).",
                                  num1Text: "How Is Laser Produced?",
                                  num2Text: "When Was Laser Invented?",
                                  num3Text: "What Electrons Does Laser Emit?",
                                  num4Text: "Why Do Electrons Reflect Light?",
                                  answer: 1),
                    QuestionModel(num: 10,
                                  questionText: "다음 글의 흐름상 가장 어색한 문장은?",
                                  reference: "Markets in water rights are likely to evolve as a rising population leads to shortages and climate change causes drought and famine. ①" + "But they will be based on regional and ethical trading practices and will differ from the bulk of commodity trade.".underLined + "②" + "Detractors argue trading water is unethical or even a breach of human rights, but already water rights are bought and sold in arid areas of the globe from Oman to Australia.".underLined + "③" + "Drinking distilled water can be beneficial, but may not be the best choice for everyone, especially if the minerals are not supplemented by another source.".underLined + "④" + "“We strongly believe that water is in fact turning into the new gold for this decade and beyond,” said Ziad Abdelnour.".underLined + " “No wonder smart money is aggressively moving in this direction.”",
                                  num1Text: "",
                                  num2Text: "",
                                  num3Text: "",
                                  num4Text: "",
                                  answer: 3),
                    QuestionModel(num: 11,
                                  questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한것을 고르시오.",
                                  reference: "A: I heard that the university cafeteria changed their menu. B: Yeah, I just checked it out.\nA: And they got a new caterer.\nB: Yes. Sam’s Catering.\nA: ______________________________________?\nB: There are more dessert choices. Also, some sandwich choices were removed.",
                                  num1Text: "What is your favorite dessert",
                                  num2Text: "Do you know where their office is",
                                  num3Text: "Do you need my help with the menu",
                                  num4Text: "What’s the difference from the last menu",
                                  answer: 4),
                    QuestionModel(num: 12,
                                  questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한것을 고르시오.",
                                  reference: "A: Hi there. May I help you?\nB: Yes, I’m looking for a sweater.\nA: Well, this one is the latest style from the fall collection.\nWhat do you think?\nB: It’s gorgeous. How much is it?\nA: Let me check the price for you. It’s $120.\nB: _________________________________.\nA: Then how about this sweater? It’s from the last season,\nbut it’s on sale for $50. B: Perfect! Let me try it on.",
                                  num1Text: "I also need a pair of pants to go with it",
                                  num2Text: "That jacket is the perfect gift for me",
                                  num3Text: "It’s a little out of my price range",
                                  num4Text: "We are open until 7 p.m. on Saturdays",
                                  answer: 3),
                    QuestionModel(num: 13,
                                  questionText: "우리말을 영어로 잘못 옮긴 것을 고르시오.[13~14]",
                                  num1Text: "우리가 영어를 단시간에 배우는 것은 결코 쉬운 일이 아니다.\n→ It is by no means easy for us to learn English in a short time.",
                                  num2Text: "우리 인생에서 시간보다 더 소중한 것은 없다.\n→ Nothing is more precious as time in our life.",
                                  num3Text: "아이들은 길을 건널 때 아무리 조심해도 지나치지 않다.\n→ Children cannot be too careful when crossing the street.",
                                  num4Text: "그녀는 남들이 말하는 것을 쉽게 믿는다.\n→ She easily believes what others say.",
                                  answer: 2),
                    QuestionModel(num: 14,
                                  questionText: "",
                                  num1Text: "커피 세 잔을 마셨기 때문에, 그녀는 잠을 이룰 수 없다.\n→ Having drunk three cups of coffee, she can’t fall asleep.",
                                  num2Text: "친절한 사람이어서, 그녀는 모든 이에게 사랑받는다.\n→ Being a kind person, she is loved by everyone.",
                                  num3Text: "모든 점이 고려된다면, 그녀가 그 직위에 가장 적임인 사람이다.\n→ All things considered, she is the best-qualified person for the position.",
                                  num4Text: "다리를 꼰 채로 오랫동안 앉아 있는 것은 혈압을 상승시킬 수 있다.\n→ Sitting with the legs crossing for a long period can raise blood pressure.",
                                  answer: 4),
                    QuestionModel(num: 15,
                                  questionText: "밑줄 친 (A), (B)에 들어갈 말로 가장 적절한 것은?",
                                  reference: "Beliefs about maintaining ties with those who have died vary from culture to culture. For example, maintaining ties with the deceased is accepted and sustained in the religious rituals of Japan. Yet among the Hopi Indians of Arizona, the deceased are forgotten as quickly as possible and life goes on as usual. (A) , the Hopi funeral ritual concludes with a break-off between mortals and spirits. The diversity of grieving is nowhere clearer than in two Muslim societies-one in Egypt, the other in Bali. Among Muslims in Egypt, the bereaved are encouraged to dwell at length on their grief, surrounded by others who relate to similarly tragic accounts and express their sorrow. (B) , in Bali, bereaved Muslims are encouraged to laugh and be joyful rather than be sad",
                                  num1Text: "However - Similarly",
                                  num2Text: "In fact - By contrast",
                                  num3Text: "Therefore - For example",
                                  num4Text: "Likewise - Consequently",
                                  answer: 2),
                    QuestionModel(num: 16,
                                  questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                                  reference: "Scientists have long known that higher air temperatures are contributing to the surface melting on Greenland’s ice sheet. But a new study has found another threat that has begun attacking the ice from below: Warm ocean water moving underneath the vast glaciers is causing them to melt even more quickly. The findings were published in the journal Nature Geoscience by researchers who studied one of the many “ice tongues” of the Nioghalvfjerdsfjorden Glacier in northeast Greenland. An ice tongue is a strip of ice that floats on the water without breaking off from the ice on land. The massive one these scientists studied is nearly 50 miles long. The survey revealed an underwater current more than a mile wide where warm water from the Atlantic Ocean is able to flow directly towards the glacier, bringing large amounts of heat into contact with the ice and ___________ the glacier’s melting.",
                                  num1Text: "separating",
                                  num2Text: "delaying",
                                  num3Text: "preventing",
                                  num4Text: "accelerating",
                                  answer: 4),
                    QuestionModel(num: 17,
                                  questionText: "다음 글의 제목으로 가장 적절한 것은?",
                                  reference: "Do people from different cultures view the world differently? A psychologist presented realistic animated scenes of fish and other underwater objects to Japanese and American students and asked them to report what they had seen. Americans and Japanese made about an equal number of references to the focal fish, but the Japanese made more than 60 percent more references to background elements, including the water, rocks, bubbles, and inert plants and animals. In addition, whereas Japanese and American participants made about equal numbers of references to movement involving active animals, the Japanese participants made almost twice as many references to relationships involving inert, background objects. Perhaps most tellingly, the very first sentence from the Japanese participants was likely to be one referring to the environment, whereas the first sentence from Americans was three times as likely to be one referring to the focal fish.",
                                  num1Text: "Language Barrier Between Japanese and Americans",
                                  num2Text: "Associations of Objects and Backgrounds in the Brain",
                                  num3Text: "Cultural Differences in Perception",
                                  num4Text: "Superiority of Detail-oriented People",
                                  answer: 3),
                    QuestionModel(num: 18, questionText: "주어진 문장이 들어갈 위치로 가장 적절한 곳은?",
                                  reference: "Thus, blood, and life-giving oxygen, are easier for the heart to circulate to the brain.",
                                  reference2: "People can be exposed to gravitational force, or g-force, in different ways. It can be localized, affecting only a portion of the body, as in getting slapped on the back. It can also be momentary, such as hard forces endured in a car crash. A third type of g-force is sustained, or lasting for at least several seconds. ( ① ) Sustained, body- wide g-forces are the most dangerous to people. ( ② ) The body usually withstands localized or momentary g-force better than sustained g-force, which can be deadly because blood is forced into the legs, depriving the rest of the body of oxygen. ( ③ ) Sustained g-force applied while the body is horizontal, or lying down, instead of sitting or standing tends to be more tolerable to people, because blood pools in the back and not the legs. ( ④ ) Some people, such as astronauts and fighter jet pilots, undergo special training exercises to increase their bodies’ resistance to g-force.",
                                  num1Text: "",
                                  num2Text: "",
                                  num3Text: "",
                                  num4Text: "",
                                  answer: 4),
                    QuestionModel(num: 19,
                                  questionText: "다음 글의 요지로 가장 적절한 것은?",
                                  reference: "If someone makes you an offer and you’re legitimately concerned about parts of it, you’re usually better off proposing all your changes at once. Don’t say, “The salary is a bit low. Could you do something about it?” and then, once she’s worked on it, come back with “Thanks. Now here are two other things I’d like...” If you ask for only one thing initially, she may assume that getting it will make you ready to accept the offer (or at least to make a decision). If you keep saying “and one more thing...,” she is unlikely to remain in a generous or understanding mood. Furthermore, if you have more than one request, don’t simply mention all the things you want A, B, C, and D; also signal the relative importance of each to you. Otherwise, she may pick the two things you value least, because they’re pretty easy to give you, and feel she’s met you halfway.",
                                  num1Text: "Negotiate multiple issues simultaneously, not serially.",
                                  num2Text: "Avoid sensitive topics for a successful negotiation.",
                                  num3Text: "Choose the right time for your negotiation.",
                                  num4Text: "Don’t be too direct when negotiating salary.",
                                  answer: 1),
                    QuestionModel(num: 20,
                                  questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                                  reference: "Today, Lamarck is unfairly remembered in large part for his mistaken explanation of how adaptations evolve. He proposed that by using or not using certain body parts, an organism develops certain characteristics.",
                                  reference2: "(A)  There is no evidence that this happens. Still, it is important to note that Lamarck proposed that evolution occurs when organisms adapt to their environments. This idea helped set the stage for Darwin.\n\n(B)  Lamarck thought that these characteristics would be passed on to the offspring. Lamarck called this idea inheritance of acquired characteristics.\n\n(C)  For example, Lamarck might explain that a kangaroo’s powerful hind legs were the result of ancestors strengthening their legs by jumping and then passing that acquired leg strength on to the offspring. However, an acquired characteristic would have to somehow modify the DNA of specific genes in order to be inherited.",
                                  num1Text: "(A) - (C) - (B)",
                                  num2Text: "(B) - (A) - (C)",
                                  num3Text: "(B) - (C) - (A)",
                                  num4Text: "(C) - (A) - (B)",
                                  answer: 3)

        ])
    ]
    
    let questionSample =
    QuestionModel(num: 5,
                  questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                  reference: "승상이 말을 마치기도 전에 구름이 걷히더니 노승은 간 곳이 없고 좌우를 돌아보니 팔낭자도 간 곳이 없었다. 승상이 놀라 어찌할 바를 모르는 중에 높은 대와 많은 집들이 한순간에 사라지고 자기의 몸은 작은 암자의 포단 위에 앉아 있었는데, 향로의 불은 이미 꺼져 있었고 지는 달이 창가에 비치고 있었다.\n자신의 몸을 보니 백팔염주가 걸려 있고 머리를 손으로 만져보니 갓 깎은 머리털이 까칠까칠하더라. 완연한 소화상의 몸이요, 전혀 대승상의 위의가 아니었으니, 이에 제 몸이 인간 세상의 승상 양소유가 아니라 연화도량의 행자 성진임을 비로소 깨달았다.\n그리고 생각하기를, ‘처음에 스승에게 책망을 듣고 풍도옥으로 가서 인간 세상에 환도하여 양가의 아들이 되었지. 그리고 장원급제를 하여 한림학사가 된 후 출장입상하고 공명신퇴하여 두 공주와 여섯 낭자로 더불어 즐기던 것이 다 하룻밤 꿈이었구나. 이는 필시 사부가 나의 생각이 그릇됨을 알고 나로 하여금 이런 꿈을 꾸게 하시어 인간 부귀와 남녀 정욕이 다 허무한 일임을 알게 하신 것이로다.’\n김만중, 구운몽 에서",
                  num1Text: "‘양소유’는 장원급제를 하여 한림학사가 되었다.",
                  num2Text: "‘양소유’는 인간 세상에 환멸을 느껴 스스로 ‘성진’의 모습으로 되돌아왔다.",
                  num3Text: "‘성진’이 있는 곳은 인간 세상이 아니다.",
                  num4Text: "‘성진’은 자신의 외양을 통해 꿈에서 돌아왔음을 인식한다.",
                  answer: 2)
    let examSample = ExamModel(id: 202211, year: 2022, examTypeID: "국가직", subjectID: "국어",
                               questions:
                                [
                                    QuestionModel(num: 1,
                                                  questionText: "밑줄 친 말의 쓰임이 옳지 않은 것은?",
                                                  num1Text: "그는 아까운 능력을 " + "썩히고".underLined + " 있다.",
                                                  num2Text: "음식물 쓰레기를 " + "썩혀서".underLined + " 거름으로 만들었다.",
                                                  num3Text: "나는 이제까지 부모님 속을 " + "썩혀".underLined + "본 적이 없다.",
                                                  num4Text: "그들은 새로 구입한 기계를 창고에서 " + "썩히고".underLined + " 있다.",
                                                  answer: 3) ,
                                    QuestionModel(num: 2,
                                                  questionText: "(가)~(라)를 고쳐 쓴 것으로 옳지 않은 것은?",
                                                  reference: "(가) 오빠는 생김새가 나하고는 많이 틀려.\n(나) 좋은 결실이 맺어졌으면 하는 바람입니다.\n(다) 내가 오직 바라는 것은 네가 잘됐으면 좋겠어.\n(라) 신은 인간을 사랑하기도 하지만 시련을 주기도 한다.",
                                                  num1Text: "(가): 오빠는 생김새가 나하고는 많이 달라.",
                                                  num2Text: "(나): 좋은 결실을 맺었으면 하는 바램입니다.",
                                                  num3Text: "(다): 내가 오직 바라는 것은 네가 잘됐으면 좋겠다는 거야.",
                                                  num4Text: "(라): 신은 인간을 사랑하기도 하지만 인간에게 시련을 주기도 한다.",
                                                  answer: 2),
                                    QuestionModel(num: 3,
                                                  questionText: "사자성어의 쓰임이 적절하지 않은 것은?",
                                                  num1Text: "그는 구곡간장(九曲肝腸)이 끊어지는 듯한 슬픔에 빠졌다.",
                                                  num2Text: "학문의 정도를 걷지 않고 곡학아세(曲學阿世)하는 이가 있다.",
                                                  num3Text: "이유 없이 친절한 사람은 구밀복검(口蜜腹劍)일 수 있으니 조심해야 한다.",
                                                  num4Text: "신중한 태도로 문제의 본질에 접근하는 당랑거철(螳螂拒轍)의 자세가 필요하다.",
                                                  answer: 4),
                                    QuestionModel(num: 4,
                                                  questionText: "다음 대화에서 나타난 ‘지민’의 의사소통 방식으로 가장 적절한 것은?",
                                                  reference: "정수: 지난번에 너랑 같이 들었던 면접 전략 강의가 정말 유익했어.\n\n지민: 그랬어? 나도 그랬는데.\n\n정수: 특히 아이스크림 회사의 면접 내용이 도움이 많이 됐어.\n\n지민: 맞아. 그중에서도 두괄식으로 답변하라는 첫 번째 내용이 정말 인상적이더라. 핵심 내용을 먼저 말하는 전략이 면접에서 그렇게 효과적일 줄 몰랐어.\n\n정수: 어! 그래? 나는 두 번째 내용이 훨씬 더 인상적이었는데.\n\n지민: 그랬구나. 하긴 아이스크림 매출 증가에 관한 통계 자료를 인용해서 답변한 전략도 설득력이 있었어. 하지만 초두 효과의 효용성도 크지 않을까 해.\n\n정수: 그렇긴 해.",
                                                  num1Text: "자신의 면접 경험을 예로 들어 상대방을 설득하고 있다.",
                                                  num2Text: "상대방의 약점을 공략하며 상대방의 이견을 반박하고 있다.",
                                                  num3Text: "상대방의 견해를 존중하면서 자신의 의견을 제시하고 있다.",
                                                  num4Text: "상대방과의 갈등 해소를 위해 자신의 감정을 표현하고 있다.",
                                                  answer: 3),
                                    QuestionModel(num: 5,
                                                  questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                                                  reference: " 승상이 말을 마치기도 전에 구름이 걷히더니 노승은 간 곳이 없고 좌우를 돌아보니 팔낭자도 간 곳이 없었다. 승상이 놀라 어찌할 바를 모르는 중에 높은 대와 많은 집들이 한순간에 사라지고 자기의 몸은 작은 암자의 포단 위에 앉아 있었는데, 향로의 불은 이미 꺼져 있었고 지는 달이 창가에 비치고 있었다.\n 자신의 몸을 보니 백팔염주가 걸려 있고 머리를 손으로 만져보니 갓 깎은 머리털이 까칠까칠하더라. 완연한 소화상의 몸이요, 전혀 대승상의 위의가 아니었으니, 이에 제 몸이 인간 세상의 승상 양소유가 아니라 연화도량의 행자 성진임을 비로소 깨달았다.\n 그리고 생각하기를, ‘처음에 스승에게 책망을 듣고 풍도옥으로 가서 인간 세상에 환도하여 양가의 아들이 되었지. 그리고 장원급제를 하여 한림학사가 된 후 출장입상하고 공명신퇴하여 두 공주와 여섯 낭자로 더불어 즐기던 것이 다 하룻밤 꿈이었구나. 이는 필시 사부가 나의 생각이 그릇됨을 알고 나로 하여금 이런 꿈을 꾸게 하시어 인간 부귀와 남녀 정욕이 다 허무한 일임을 알게 하신 것이로다.’\n\n - 김만중, 〖구운몽〗 에서",
                                                  num1Text: "‘양소유’는 장원급제를 하여 한림학사가 되었다.",
                                                  num2Text: "‘양소유’는 인간 세상에 환멸을 느껴 스스로 ‘성진’의 모습으로 되돌아왔다.",
                                                  num3Text: "‘성진’이 있는 곳은 인간 세상이 아니다.",
                                                  num4Text: "‘성진’은 자신의 외양을 통해 꿈에서 돌아왔음을 인식한다.",
                                                  answer: 2),
                                    QuestionModel(num: 6,
                                                  questionText: "(가)~(라)의 ㉠~㉣에 대한 설명으로 적절하지 않은 것은?",
                                                  reference: "(가) 간밤의 부던 람에 눈서리 치단 말가 " + "㉠낙락장송(落落長松)".underLined + "이 다 기우러 가노ᄆᆡ 믈며 못다 픤 곳이야 닐러 무슴 리오.\n\n(나) 철령 노픈 봉에 쉬여 넘 져 구룸아 고신원루(孤臣寃淚) 비 사마 여다가 " + "㉡님".underLined + " 계신 구중심처(九重深處)에 려 본들 엇리.\n\n(다) 이화우(梨花雨) 흣릴 제 울며 잡고 이별 님 추풍낙엽(秋風落葉)에 " + "㉢저".underLined + "도 날 각가 천리(千里)에 외로온 만 오락가락 노매.\n\n(라) 삼동(三冬)의 뵈옷 닙고 암혈(巖穴)의 눈비 마자 구롬  볏뉘도  적이 업건마 서산의 " + "㉣ ".underLined + "디다 니 그 셜워 노라.",
                                                  num1Text: "㉠은 억울하게 해를 입은 충신을 가리킨다.",
                                                  num2Text: "㉡은 궁궐에 계신 임금을 가리킨다.",
                                                  num3Text: "㉢은 헤어진 연인을 가리킨다.",
                                                  num4Text: "㉣은 오랜 세월을 함께한 벗을 가리킨다.",
                                                  answer: 4),
                                    QuestionModel(num: 7,
                                                  questionText: "㉠~㉢에 들어갈 말로 가장 적절한 것은?",
                                                  reference: "○ 그들의 끈기가 이 경기의 승패를 [㉠] 했다.\n○ 올해 영화제 시상식은 11개 [㉡]으로 나뉜다.\n○ 그 형제는 너무 닮아서 누가 동생이고 누가 형인지 [㉢]할 수 없다.",
                                                  num1Text: "㉠가름 ㉡부문 ㉢구별",
                                                  num2Text: "㉠가름 ㉡부분 ㉢구분",
                                                  num3Text: "㉠갈음 ㉡부문 ㉢구별",
                                                  num4Text: "㉠갈음 ㉡부분 ㉢구분",
                                                  answer: 1),
                                    QuestionModel(num: 8,
                                                  questionText: "다음 글의 ‘동기화단계조직’에 따라 (가)~(마)를 배열한 것으로 가장 적절한 것은?",
                                                  reference: " 설득하는 말하기의 메시지를 조직하는 방법으로 ‘동기화 단계 조직’이 있다. 이 방법의 세부 단계는 다음과 같다.\n\n1단계: 주제에 대한 청자의 주의나 관심을 환기한다.\n\n2단계: 특정 문제를 청자와 관련지어 설명함으로써 청자의 요구나 기대를 자극한다.\n\n3단계: 해결 방안을 제시하여 청자의 이해와 만족을 유도한다.\n\n4단계: 해결 방안이 청자에게 어떤 도움이 되는지 구체화한다.\n\n5단계: 구체적인 행동의 내용과 방법을 제시하여 특정 행동을 요구한다.",
                                                  reference2: "(가) 지난주 제 친구는 일을 마친 후 자전거를 타고 집으로 돌아오다가 사고를 당해 머리를 다쳤습니다.\n\n(나) 여러분이 자전거를 탈 때 헬멧을 착용하면 머리를 보호할 수 있습니다.\n\n(다) 아마 여러분도 가끔 자전거를 타는 경우가 있을 것입니다. 그런데 매년 2천여 명이 자전거를 타다가 머리를 다쳐 고생한다고 합니다.\n\n(라) 만약 자전거를 타는 모든 사람이 헬멧을 착용한다면 자전거 사고를 당해도 뇌손상을 비롯한 신체 피해를 75 % 줄일 수 있습니다. 또 자전거 타기가 주는 즐거움과 편리함을 안전하게 누릴 수 있습니다.\n\n(마) 자전거를 탈 때는 안전을 위해서 반드시 헬멧을 착용 하시기 바랍니다.",
                                                  num1Text: "(가)-(나)-(다)-(라)-(마)",
                                                  num2Text: "(가)-(다)-(나)-(라)-(마)",
                                                  num3Text: "(가)-(다)-(라)-(나)-(마)",
                                                  num4Text: "(가)-(라)-(다)-(나)-(마)",
                                                  answer: 2),
                                    QuestionModel(num: 9,
                                                  questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                                                  reference: " 국가정보자원관리원과 ○○시는 빅데이터 기반의 맞춤형 복지 서비스 분석 사업을 수행했다. 국가정보자원관리원은 자체 확보한 공공 데이터와 ○○시로부터 받은 복지 사업 관련 데이터를 활용하여 ‘복지 공감 지도’를 제작하고, 복지 기관 접근성 분석을 통해 취약 지역 지원 방안을 제시했다.\n 복지 공감 지도는 공간 분석 시스템을 활용하여 ○○시에 소재한 복지 기관들의 다양한 지원 항목과 이를 필요로 하는 복지 대상자, 독거노인, 장애인 등의 수급자 현황을 한눈에 확인할 수 있도록 구현한 것이다. 이 지도를 활용하면 복지 혜택이 필요한 지역과 수급자를 빨리 찾아낼 수 있으며, 생필품 지원이나 방문 상담 등 복지 기관의 맞춤형 대응이 가능하고, 최적의 복지 기관 설립 위치를 선정할 수 있다.\n 이 사업을 통해 ○○시는 그동안 복지 기관으로부터 도보로 약 15분 내 위치한 수급자에게 복지 혜택이 집중되고 있는 것도 확인했다. 이에 교통이나 건강 등의 문제로 복지 기관 방문이 어려운 수급자를 위해 맞춤형 복지 서비스가 절실하게 필요한 상황임을 발견하고, 복지 셔틀버스 노선을 4개 증설할 계획을 수립했다.",
                                                  num1Text: "빅데이터를 활용하여 복지 사각지대를 줄이는 방안을 마련할 수 있다.",
                                                  num2Text: "복지 기관과 수급자 거주지 사이의 거리는 복지 혜택의 정도에 영향을 준다.",
                                                  num3Text: "복지 기관 접근성 분석 결과는 복지 셔틀버스 노선 증설의 근거가 된다.",
                                                  num4Text: "복지 공감 지도로 복지 혜택에 대한 수급자들의 개별 만족도를 파악할 수 있다.",
                                                  answer: 4),
                                    QuestionModel(num: 10,
                                                  questionText: "㉠~㉣의 사례로 적절하지 않은 것은?",
                                                  reference: " 단어의 의미가 변화하는 양상은 다양하다. 첫째, “아침 먹고 또 공부하자.”에서 ‘아침’은 본래의 의미인 ‘하루 중의 이른 시간’을 가리키지 않고 ‘아침에 먹는 밥’이라는 의미로 쓰인다. ‘밥’의 의미가 ‘아침’에 포함되어서 ‘아침’만으로도 ‘아침밥’의 의미를 표현하게 된 것으로, ㉠" + "두 개의 단어가 긴밀한 관계여서 한쪽이 다른 한쪽의 의미까지 포함하는 의미로 변화하게 된 경우".underLined + "이다. 둘째, ‘바가지’는 원래 박의 껍데기를 반으로 갈라 썼던 물건을 가리켰는데, 오늘날에는 흔히 플라스틱 바가지를 가리킨다. 이것은 ㉡" + "언어 표현은 그대로인데 시대의 변화에 따라 지시 대상 자체가 바뀌어서 의미 변화가 발생한 경우".underLined + "이다. 셋째, ‘묘수’는 본래 바둑에서 만들어진 용어이지만 일상적인 언어생활에서도 ‘쉽게 생각해 내기 어려운 좋은 방안’이라는 의미로 사용된다. 이는 ㉢" + "특수한 영역에서 사용되던 말이 일반화되면서 단어의 의미가 변화한 경우".underLined + "에 해당한다. 넷째, 호랑이를 두려워하던 시절에 사람들은 ‘호랑이’라는 이름을 직접 부르기 꺼려서 ‘산신령’이라고 부르기도 했는데, 이는 ㉣" + "심리적인 이유로 특정 표현을 피하려다 보니 그것을 대신하는 단어의 의미에 변화가 생긴 경우".underLined + "이다.",
                                                  num1Text: "㉠: ‘아이들의 코 묻은 돈’에서 ‘코’는 ‘콧물’의 의미로 쓰인다.",
                                                  num2Text: "㉡: ‘수세미’는 원래 식물의 이름이었지만 오늘날에는 ‘그릇을 씻는 데 쓰는 물건’이라는 의미로 쓰인다.",
                                                  num3Text: "㉢: ‘배꼽’은 일반적으로 ‘탯줄이 떨어지면서 배의 한가운데에 생긴 자리’를 가리키지만 바둑에서는 ‘바둑판의 한가운데’ 라는 의미로 쓰인다.",
                                                  num4Text: "㉣: 무서운 전염병인 ‘천연두’를 꺼려서 ‘손님’이라고 불렀다.",
                                                  answer: 3),
                                    QuestionModel(num: 11,
                                                  questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                                                  reference: " △△시 시장님께\n 안녕하십니까? 저는 △△시에서 농장을 운영하는 ◻︎◻︎◻︎입니다. 이렇게 글을 쓰게 된 것은 우리 농장 근처에 신축된 골프장의 빛 공해 문제에 대해 말씀드리기 위함입니다. 빛이 공해가 될 수 있다는 말이 다소 생소하실 수도 있습니다. 하지만 지나친 야간 조명이 식물의 성장에 부정적인 영향을 끼쳐 작물 수확량을 감소시킬 수 있음은 이미 여러 연구를 통해 입증된 바 있습니다. 좀 늦었지만 △△시에서도 이 문제에 대해 경각심을 가질 필요가 있습니다. 실제로 골프장이 야간 운영을 시작했을 때를 기점으로 우리 농장의 수확률이 현저히 낮아졌음을 제가 확인했습니다. 물론, 이윤을 추구하는 골프장의 야간 운영을 무조건 막는다면 골프장 측에서 반발할 것입니다. 그래서 계절에 따라 야간 운영 시간을 조정하거나 운영 제한에 따른 손실금을 보전해 주는 등의 보완책도 필요합니다. 또한 ○○군에서도 빛 공해 문제를 해결하기 위해 야간 조명의 조도를 조정하는 프로젝트를 진행한 바 있으니 참고해 보시기 바랍니다. 모쪼록 시장님께서 이 문제에 관심을 가지고 농장과 골프장이 상생할 수 있는 정책을 펼쳐 주시기를 부탁드립니다.",
                                                  num1Text: "시장에게 빛 공해로 농장이 겪는 어려움에 대해 관심을 촉구하고 있다.",
                                                  num2Text: "건의에 대한 신뢰성을 높이기 위해 인용한 자료의 출처를 밝히고 있다.",
                                                  num3Text: "다른 지역에서 야간 조명으로 인한 폐해를 해결하기 위해 노력한 사례를 언급하고 있다.",
                                                  num4Text: "골프장의 야간 운영을 제한할 때 예상되는 문제점과 그 해결 방안에 대해 제시하고 있다.",
                                                  answer: 2),
                                    QuestionModel(num: 12,
                                                  questionText: "다음 대화의 ㉠~㉣에 대한 설명으로 적절하지 않은 것은?",
                                                  reference: "이진: 태민아, ㉠" + "이 책".underLined + " 읽어 봤니?\n\n태민:아니, ㉡" + "그 책".underLined + "은 아직 읽어 보지 못했어.\n\n이진: 그렇구나. 이 책은 작가의 문체가 독특해서 읽어 볼 만해.\n\n태민: 응, 꼭 읽어 볼게. 한 권 더 추천해 줄래?\n\n이진: 그럼 ㉢" + "저 책".underLined + "은 어때? 한국 대중문화를 다양한 시각에서 다룬 재미있는 책이야.\n\n태민:그래, ㉣" + "그 책".underLined + "도 함께 읽어볼게.\n\n이진: (두 책을 들고 계산대로 간다.) 읽어 보겠다고 하니,생일 선물로 ㉤" + "이 책".underLined + " 두 권 사 줄게. \n\n태민: 고마워. 잘 읽을게.",
                                                  num1Text: "㉠은 청자보다 화자에게, ㉡은 화자보다 청자에게 가까이 있는 대상을 가리킨다.",
                                                  num2Text: "㉢은 화자보다 청자에게 멀리 있는 대상을 가리킨다.",
                                                  num3Text: "㉢과 ㉣은 같은 대상을 가리킨다.",
                                                  num4Text: "㉤은 ㉡과 ㉢ 모두를 가리킨다.",
                                                  answer: 2),
                                    QuestionModel(num: 13,
                                                  questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                                                  reference: " 아동이 부모의 소유물 또는 종족의 유지나 국가의 방위를 위한 수단으로 간주되었던 전근대사회에서는 아동의 권리에 대한 인식이 존재하지 않았다. 산업혁명으로 봉건제도가 붕괴되고 자본주의가 탄생한 근대사회에 이르러 구빈법에 따른 국가 개입과 민간단체의 자발적인 참여로 아동보호가 시작되었다.\n 1922년 잽 여사는 아동권리사상을 담아 아동권리에 대한 내용을 성문화하였다. 이를 기초로 1924년 국제연맹에서는 전문과 5개의 조항으로 된 〖아동권리에 관한 제네바 선언〗을 채택하였다. 여기에는 “아동은 물질적으로나 정신적으로 정상적인 발달을 위해 필요한 조건이 충족되어야 한다.” 라든지 “아동의 재능은 인류를 위해 쓰인다는 자각 속에서 양육되어야 한다.” 등의 내용이 포함되었다.\n 그러나 여기에서도 아동은 보호의 객체로만 인식되었을 뿐 생존, 보호, 발달을 위한 적극적인 권리의 주체로 인식되지는 않았다. 최근에 와서야 국제사회의 노력에 힘입어 아동은 보호되어야 할 수동적인 존재에서 자신의 권리를 주장할 수 있는 능동적인 존재로 자리매김할 수 있게 되었다. 1989년 유엔총회에서 채택된 〖아동권리협약〗이 그것이다.\n 우리나라는 이를 토대로 2016년 〖아동권리헌장〗 9개 항을 만들었다. 이 헌장은 ‘생존과 발달의 권리’, ‘아동이 최선의 이익을 보장 받을 권리’, ‘차별 받지 않을 권리’, ‘자신의 의견이존중될권리’등 유엔의 〖아동권리협약〗의 네 가지 기본 원칙을 포함하고 있다. 또한 전문에는 아동의 권리와 더불어 “부모와 사회, 국가와 지방자치단체는 아동의 이익을 최우선으로 고려해야 하며, 다음과 같은 아동의 권리를 확인하고 실현할 책임이 있다.”라고 명시하여 아동을 둘러싼 사회적 주체들의 책임을 명확히 하였다.",
                                                  num1Text: "아동의 권리에 대한 인식은 근대 이후에 형성되었다.",
                                                  num2Text: "〖아동권리헌장〗은 〖아동권리협약〗을 토대로 만들어졌다.",
                                                  num3Text: "〖아동권리에 관한 제네바 선언〗, 〖아동권리협약〗, 〖아동권리헌장〗에는 모두 아동의 발달에 대한 내용이 들어가 있다.",
                                                  num4Text: "〖아동권리에 관한 제네바 선언〗은 아동을 적극적인 권리의 주체로 인식함으로써 아동의 권리에 대한 진전된 성과를 이루었다.",
                                                  answer: 4),
                                    QuestionModel(num: 14,
                                                  questionText: "다음 시에 대한 이해로 적절하지 않은 것은?",
                                                  reference: "봄은\n남해에서도 북녘에서도\n오지 않는다.\n\n너그럽고\n빛나는\n봄의 그 눈짓은,\n제주에서 두만까지\n우리가 디딘\n아름다운 논밭에서 움튼다.\n\n겨울은,\n바다와 대륙 밖에서\n그 매운 눈보라 몰고 왔지만\n이제 올\n너그러운 봄은, 삼천리 마을마다\n우리들 가슴속에서\n움트리라.\n\n움터서,\n강산을 덮은 그 미움의 쇠붙이들\n눈 녹이듯 흐물흐물\n녹여버리겠지.\n\n-신동엽, 〖봄은〗-",
                                                  num1Text: "현실을 초월한 순수 자연의 세계를 노래하고 있다.",
                                                  num2Text: "희망과 신념을 드러내는 단정적 어조로 표현하고 있다.",
                                                  num3Text: "시어들의 상징적인 의미를 통해 주제를 형성하고 있다.",
                                                  num4Text: "‘봄’과 ‘겨울’의 이원적 대립으로 시상을 전개하고 있다.",
                                                  answer: 1),
                                    QuestionModel(num: 15,
                                                  questionText: "다음 글의 전개 순서로 가장 자연스러운 것은?",
                                                  reference: "(가) 이 기관을 잘 수리하여 정련하면 그 작동도 원활하게 될 것이요, 수리하지 아니하여 노둔해지면 그 작동도 막혀 버릴 것이니 이런 기관을 다스리지 아니하고야 어찌 그 사회를 고취하여 발달케 하리오.\n(나) 이러므로 말과 글은 한 사회가 조직되는 근본이요, 사회 경영의 목표와 지향을 발표하여 그 인민을 통합시키고 작동하게 하는 기관과 같다.\n(다) 말과 글이 없으면 어찌 그 뜻을 서로 통할 수 있으며, 그 뜻을 서로 통하지 못하면 어찌 그 인민들이 서로 이어져 번듯한 사회의 모습을 갖출 수 있으리오.\n(라)그뿐 아니라 그 기관은 점점 녹슬고 상하여 필경은 쓸 수 없는 지경에 이를 것이니 그 사회가 어찌 유지될 수 있으리오. 반드시 패망을 면하지 못할지라.\n(마) 사회는 여러사람이 그 뜻을 서로 통하고 그 힘을 서로 이어서 개인의 생활을 경영하고 보존하는 데에 서로 의지하는 인연의 한 단체라.\n\n - 주시경, 〖대한국어문법 발문〗에서 - ",
                                                  num1Text: "(마)-(가)-(다)-(나)-(라)",
                                                  num2Text: "(마)-(가)-(라)-(다)-(나)",
                                                  num3Text: "(마)-(다)-(가)-(라)-(나)",
                                                  num4Text: "(마)-(다)-(나)-(가)-(라)",
                                                  answer: 4),
                                    QuestionModel(num: 16,
                                                  questionText: "한자 표기가 옳지 않은 것은?",
                                                  num1Text: "오늘 협상에서 만족(滿足)할 만한 성과를 거두었다.",
                                                  num2Text: "김 위원의 주장을 듣고 그 의견에 동의하여 재청(再請)했다.",
                                                  num3Text: "우리 지자체의 해묵은 문제를 해결(解結)할 방안이 생각났다.",
                                                  num4Text: "다수가 그 의견에 동의하지 않았기에 재론(再論)이 필요하다.",
                                                  answer: 3),
                                    QuestionModel(num: 17,
                                                  questionText: "다음 문장이 들어가기에 가장 적절한 곳을 ㉠~㉣에서 고르면?",
                                                  reference: " 신분에 따라 문체를 고착화하는 것을 인정하지 않았던 것이다.",
                                                  reference2: " 유럽이 교회로부터 정신적으로 해방된 것은 그리스와 로마의 고대 작가들에 대한 재발견을 통해서였다.[ ㉠ ] 그 이후 고대 작가들의 문체는 귀족 중심의 유럽 문화에서 모범으로 여겨졌다. [ ㉡ ] 이러한 상황은 대략 1770년대에 시작되는 낭만주의에서부터 변화하기 시작했다. [ ㉢ ]이 낭만주의 시기에 평등과 민주주의를 꿈꿨던 신흥 시민계급은 문학에서 운문과 영웅적 운명을 귀족에게만 전속시키고 하층민에게는 산문과 우스꽝스러운 상황을 배정하는 전통 시학을 거부했다. [ ㉣ ] 고전 문학은 더 이상 문학의 규범이 아니었으며, 문학을 현실의 모방으로 인식하는 태도도 포기되었다.",
                                                  num1Text: "㉠",
                                                  num2Text: "㉡",
                                                  num3Text: "㉢",
                                                  num4Text: "㉣",
                                                  answer: 4),
                                    QuestionModel(num: 18,
                                                  questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                                                  reference: " 정거장에 나온 박은 수염도 깎은 지 오래어 터부룩한 데다 버릇처럼 자주 찡그려지는 비웃는 웃음은 전에 못 보던 표정이었다. 그 다니는 학교에서만 지싯지싯* 붙어 있는 것이 아니라 이 시대 전체에서 긴치 않게 여기는, 지싯지싯 붙어 있는 존재 같았다. 현은 박의 그런 지싯지싯함에서 선뜻 자기를 느끼고 또 자기의 작품들을 느끼고 그만 더 울고 싶게 괴로워졌다.\n 한참이나 붙들고 섰던 손목을 놓고, 그들은 우선 대합실로 들어왔다. 할 말은 많은 듯하면서도 지껄여 보고 싶은 말은 골라낼 수가 없었다. 이내 다시 일어나 현은,\n “나 좀 혼자 걸어 보구 싶네.”\n하였다. 그래서 박은 저녁에 김을 만나 가지고 대동강가에 있는 동일관이란 요정으로 나오기로 하고 현만이 모란봉으로 온 것이다.\n 오면서 자동차에서 시가도 가끔 내다보았다. 전에 본 기억이 없는 새 빌딩들이 꽤 많이 늘어섰다. 그중에 한가지 인상이 깊은 것은 어느 큰 거리 한 뿌다귀* 에 벽돌 공장도 아닐테요 감옥도 아닐 터인데 시뻘건 벽돌만으로, 무슨 큰 분묘와 같이 된 건축이 웅크리고 있는 것이다. 현은 운전사에게 물어보니, 경찰서라고 했다.\n\n-이태준, 〖패강랭〗에서-\n\n*지싯지싯: 남이 싫어하는지는 아랑곳하지 아니하고 제가 좋아하는 것만 짓궃게 자꾸 요구하는 모양.\n*뿌다귀: '뿌다구니'의 준말로, 쑥 내밀어 구부러지거나 꺾어져 돌아간 자리.",
                                                  num1Text: "‘현’은 예전과 달라진 ‘박’의 태도가 자신의 작품 때문이라고 생각하고 있다.",
                                                  num2Text: "‘현’은 자신과 비슷한 처지에 있는 ‘박’을 통해 자신을 연민하고 있다.",
                                                  num3Text: "‘현’은 새 빌딩들을 보고 도시가 많이 변화하고 있음을 인지하고 있다.",
                                                  num4Text: "‘현’은 시뻘건 벽돌로 만든 경찰서를 보고 암울한 분위기를 느끼고 있다.",
                                                  answer: 1),
                                    QuestionModel(num: 19,
                                                  questionText: "다음 규정에 근거할 때 옳지 않은 것은?",
                                                  reference: " 〖한글 맞춤법 제30항〗\n 사이시옷은 다음과 같은 경우에 받치어 적는다.\n(가) 순우리말로 된 합성어로서 앞말이 모음으로 끝나면서 뒷말의 첫소리가 된소리로 나는 것\n(나) 순우리말과 한자어로 된 합성어로서 앞말이 모음으로 끝나면서 뒷말의 첫소리가 된소리로 나는 것",
                                                  num1Text: "(가)에 따라 '아래 + 집'은 '아랫집'으로 적는다.",
                                                  num2Text: "(가)에 따라 '쇠 + 조각'은 '쇳조각'으로 적는다.",
                                                  num3Text: "(나)에 따라 '전세 + 방'은 '전셋방'으로 적는다.",
                                                  num4Text: "(나)에 따라 '자리 + 세'는 '자릿세'로 적는다.",
                                                  answer: 3),
                                    QuestionModel(num: 20,
                                                  questionText: "글쓴이의 견해에 부합하는 것은?",
                                                  reference: " 문화란 공동체의 구성원들이 공유하는 생각과 행동 양식의 총체라고 할 수 있다. 문화를 연구하는 사람들의 주된 관심사는 특정 생각과 행동 양식이 하나의 공동체 안에서 전파되는 기제이다.\n 이에 대한 견해 중 하나는 문화를 생각의 전염이라는 각도에서 바라보는 것이다. 예컨대, 리처드 도킨스는 ‘밈(meme)’이라는 개념을 통해 생각의 전염 과정을 설명 하고자 했다. 그에 따르면 문화는 복수의 밈으로 이루어져 있는데, 유전자에 저장된 생명체의 주요 정보가 번식을 통해 복제되어 개체군 내에서 확산되듯이, 밈 역시 유전자와 마찬가지로 공동체 내에서 복제를 통해 확산된다.\n 그러나 문화 전파의 기제를 설명하는 이론으로는 밈 이론보다 의사소통 이론이 더 적절해 보인다. 일례로, 요크셔 지역에 내려오는 독특한 푸딩 요리법은 누군가가 푸딩 만드는 것을 지켜본 후 그것을 그대로 따라 하는 방식으로 전파 되었다기보다는 요크셔 푸딩 요리법에 대한 부모와 친척, 친구들의 설명을 통해 입에서 입으로 전파되고 공유되었을 가능성이 크다.\n 생명체의 경우와 달리 문화는 완벽하게 동일한 형태로 전파되지 않는다. 전파된 문화와 그것을 수용한 결과는 큰 틀에서는 비슷하더라도 세부적으로는 다를 수밖에 없다. 다시 말해 요크셔 지방의 푸딩 요리법은 다른 지방의 푸딩 요리법과 변별되는 특색을 지니는 동시에 요크셔 지방 내부에서도 가정이나 개인에 따라 약간씩의 차이를 보인다. 이는 푸딩 요리법의 수신자가 발신자가 전해 준 정보에다 자신의 생각을 덧붙였기 때문인데, 복제의 관점에서 문화의 전파를 설명하는 이론으로는 이와 같은 현상을 설명하기 어렵다. 반면, 의사소통 이론으로는 설명 가능하다. 이에 따르면 사람들은 자신이 들은 이야기를 남에게 전달할 때 들은 이야기에다 자신의 생각을 더해서 그 이야기를 전달하기 때문이다.",
                                                  num1Text: "문화의 전파 기제는 밈 이론보다는 의사소통 이론으로 설명하는 것이 적절하다.",
                                                  num2Text: "의사소통 이론에 따르면 문화의 수용 과정에는 수용 주체의 주관이 개입하지 않는다.",
                                                  num3Text: "의사소통 이론에 따르면 특정 공동체의 문화는 다른 공동체로 복제를 통해 전파될 수 있다.",
                                                  num4Text: "요크셔 푸딩 요리법이 요크셔 지방의 가정이나 개인에 따라 세부적인 차이를 보이는 현상은 밈 이론에 의해 설명할 수 있다.",
                                                  answer: 1)
                      
                  ]
    
    )
    
    let myNoteQuestionSample =
    MyNoteQuestion(year: 2022,
                   type: "국가직",
                   subject: "국어",
                   question: QuestionModel(num: 5,
                                           questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                                           reference: "승상이 말을 마치기도 전에 구름이 걷히더니 노승은 간 곳이 없고 좌우를 돌아보니 팔낭자도 간 곳이 없었다. 승상이 놀라 어찌할 바를 모르는 중에 높은 대와 많은 집들이 한순간에 사라지고 자기의 몸은 작은 암자의 포단 위에 앉아 있었는데, 향로의 불은 이미 꺼져 있었고 지는 달이 창가에 비치고 있었다.\n자신의 몸을 보니 백팔염주가 걸려 있고 머리를 손으로 만져보니 갓 깎은 머리털이 까칠까칠하더라. 완연한 소화상의 몸이요, 전혀 대승상의 위의가 아니었으니, 이에 제 몸이 인간 세상의 승상 양소유가 아니라 연화도량의 행자 성진임을 비로소 깨달았다.\n그리고 생각하기를, ‘처음에 스승에게 책망을 듣고 풍도옥으로 가서 인간 세상에 환도하여 양가의 아들이 되었지. 그리고 장원급제를 하여 한림학사가 된 후 출장입상하고 공명신퇴하여 두 공주와 여섯 낭자로 더불어 즐기던 것이 다 하룻밤 꿈이었구나. 이는 필시 사부가 나의 생각이 그릇됨을 알고 나로 하여금 이런 꿈을 꾸게 하시어 인간 부귀와 남녀 정욕이 다 허무한 일임을 알게 하신 것이로다.’\n김만중, 구운몽 에서",
                                           num1Text: "‘양소유’는 장원급제를 하여 한림학사가 되었다.",
                                           num2Text: "‘양소유’는 인간 세상에 환멸을 느껴 스스로 ‘성진’의 모습으로 되돌아왔다.",
                                           num3Text: "‘성진’이 있는 곳은 인간 세상이 아니다.",
                                           num4Text: "‘성진’은 자신의 외양을 통해 꿈에서 돌아왔음을 인식한다.",
                                           answer: 2))
}
