//
//  ExamStore2023.swift
//  HandGosi
//
//  Created by Sy Lee on 2023/05/16.
//

import Foundation

class ExamStore2023 {
    var exams2023: [ExamModel] = []
    
    init() {
        saveExam202311()
        saveExam202312()
        saveExam202313()

        saveExam202321()
        saveExam202322()
        saveExam202323()
    }
    
    func saveExam202311() {
        let questions =
        [
            QuestionModel(num: 1,
                          questionText: "‘해양 오염’을 주제로 연설을 한다고 할 때, 다음에 제시된 조건을 모두 충족한 것은?",
                          reference: "○ 해양 오염을 줄일 수 있는 생활 속 실천 방법을 포함할 것.\n○ 설의적 표현과 비유적 표현을 활용할 것.",
                          num1Text: "바다는 쓰레기 없는 푸른 날을 꿈꾸고 있습니다. 미세 플라스틱은 바다를 서서히 죽이는 보이지 않는 독입니다. 우리의 관심만이 다시 바다를 살릴 수 있을 것입니다.",
                          num2Text: "우리가 버린 쓰레기는 바다로 흘러갔다가 해양 생물의 몸에 축적이 되어 해산물을 섭취하면 결국 다시 우리에게 돌아오게 됩니다. 분리수거를 철저히 하고 일회용품을 줄이는 것이 바다도 살리고 우리 자신도 살리는 길입니다.",
                          num3Text: "여름만 되면 피서객들이 마구 버린 쓰레기로 바다가 몸살을 앓는다고 합니다. 자기 집이라면 이렇게 함부로 쓰레기를 버렸을까요? 피서객들의 양심이 모래밭 위를 뒹굴고 있습니다. 자기 쓰레기는 자기가 집으로 되가져가도록 합시다.",
                          num4Text: "산업 폐기물이 바다로 흘러가 고래가 죽어 가는 장면을 다큐멘터리 에서 본 적이 있습니다. 이대로 가다간 인간도 고통받게 되지 않을까요? 정부에서 산업 폐기물 관리 지침을 만들고 감독을 강화하지 않는다면 바다는 쓰레기 무덤이 되고 말 것입니다.",
                          answer: 3) ,
            QuestionModel(num: 2,
                          questionText: "다음 대화에 나타난 말하기 방식을 설명한 것으로 적절하지 않은 것은?",
                          reference: "백 팀장: 이번 워크숍 장면을 사내 게시판에 올리는 게 좋겠어요. 워크숍 내용을 공유하면 좋을 것 같아서요.\n\n고 대리: 전 반대합니다. 사내 게시판에 영상을 공개하는 것은 부담스러워요. 타 부서와 비교될 것 같기도 하고요.\n\n임 대리: 저도 팀장님 말씀대로 정보를 공유한다는 취지는 좋다고 생각해요. 다만 다른 팀원들의 동의도 구해야 할 것 같고, 여러 면에서 우려되긴 하네요. 팀원들 의견을 먼저 들어 보고, 잘된 것만 시범적으로 한두 개 올리는 것이 어떨까요?",
                          num1Text: "백 팀장은 팀원들에 대한 유대감을 드러내는 표현을 사용하며 자신의 바람을 전달하고 있다.",
                          num2Text: "고 대리는 백 팀장의 제안에 반대하는 이유를 명시적으로 밝히며 백 팀장의 요청을 거절하고 있다.",
                          num3Text: "임 대리는 발언 초반에 백 팀장 발언의 취지에 공감하여 백 팀장의 체면을 세워 주고 있다.",
                          num4Text: "임 대리는 대화 참여자의 의견을 묻는 의문문을 사용하여 자신의 의견을 간접적으로 드러내고 있다.",
                          answer: 1),
            QuestionModel(num: 3,
                          questionText: "관용 표현 ᄀ~ᄅ의 의미를 풀이한 것으로 적절하지 않은 것은?",
                          reference: "○ 그의 회사는 작년에 노사 갈등으로 ㄱ"+"홍역을 치렀다.".underLined+"\n\n○ 우리 교장 선생님은 교육계에서 ㄴ"+"잔뼈가 굵은".underLined+" 분이십니다.\n\n○ 유원지로 이어지는 국도에는 차가 밀려 ㄷ"+"입추의 여지가 없었다.".underLined+"\n\n○ 그분은 세계 유수의 연구자들과 ㄹ"+"어깨를 나란히 하는".underLined+" 물리학자이다.",
                          num1Text: "ㄱ: 심한 어려움을 겪었다",
                          num2Text: "ㄴ: 오랫동안 일을 하여 그 일에 익숙한",
                          num3Text: "ㄷ: 돌아서 갈 수 있는 방법이 없었다",
                          num4Text: "ㄹ: 비슷한 지위나 힘을 가지는",
                          answer: 3),
            QuestionModel(num: 4,
                          questionText: "다음 글에서 (가) ~ (다)의 순서를 자연스럽게 배열한 것은?",
                          reference: "  빅데이터가 부각된다는 것은 기업들이 빅데이터의 가치를 받아들이기 시작했다는 뜻이다. 여기에는 기업들이 데이터를 바라보는 시각이 변한 측면도 있다.\n(가) 기업들은 고객이 판촉 활동에 어떻게 반응하고 평소에 어떻게 행동하며 사물에 대해 어떤 태도를 보이는지 알기 위해 많은 돈을 투자해 마케팅 조사를 해 왔다.\n\n(나) 그런 상황에서 기업들은 SNS나 스마트폰 등 새로운 데이터 소스로부터 그러한 궁금증과 답답함을 해결할 수 있다는 것을 알게 되었다. 페이스북에 올리는 광고에 친구가 ‘좋아요’를한 것에서 기업들은 궁금증과 답답함을 해결할 수 있다.\n\n(다) 그런데 기업들의 그런 노력이 효과가 있는 경우도 있었으나 아쉬운 점도 많았다. 쉬운 예로, 기업들은 많은 광고비를 쓰지만 그 돈이 구체적으로 어느 부분에서 효과를 내는지는 알지 못했다.\n\n  결국 데이터가 있는 곳에서 기업들은 점점 더 고객의 취향에 집중할 수 있게 되었으며, 이에 따라 기업들은 소셜 미디어의 빅데이터를 중요한 경영 수단으로 수용하기 시작한 것이다.",
                          num1Text: "(가)-(나)-(다)",
                          num2Text: "(가)-(다)-(나)",
                          num3Text: "(나)-(가)-(다)",
                          num4Text: "(다)-(나)-(가)",
                          answer: 2),
            QuestionModel(num: 5,
                          questionText: "ㄱ을 이해한 내용으로 적절하지 않은 것은?",
                          reference: "  "+"“ᄀ무진(霧津)".underLined+"엔 명산물이......뭐 별로 없지요?” 그들은 대화를 계속하고 있었다. “별게 없지요. 그러면서도 그렇게 많은 사람들이 살고 있다는 건 좀 이상스럽거든요.” “바다가 가까이 있으니 항구로 발전할 수도 있었을 텐데요?” “가 보시면 아시겠지만 그럴 조건이 되어 있는 것도 아닙니다. 수심(水深)이 얕은 데다가 그런 얕은 바다를 몇백 리나 밖으로 나가야만 비로소 수평선이 보이는 진짜 바다다운 바다가 나오는 곳이니까요.” “그럼 역시 농촌이군요?” “그렇지만 이렇다 할 평야가 있는 것도 아닙니다.” “그럼 그 오륙만이 되는 인구가 어떻게들 살아가나요?” “그러니까 그럭저럭이란 말이 있는 게 아닙니까!” 그들은 점잖게 소리 내어 웃었다. “원, 아무리 그렇지만 한 고장에 명산물 하나쯤은 있어야지.” 웃음 끝에 한 사람이 말하고 있었다.\n  무진에 명산물이 없는 게 아니다. 나는 그것이 무엇인지 알고 있다. 그것은 안개다. 아침에 잠자리에서 일어나서 밖으로 나오면, 밤사이에 진주해 온 적군들처럼 안개가 무진을 삥 둘러싸고 있는 것이었다. 무진을 둘러싸고 있는 산들도 안개에 의하여 보이지 않는 먼 곳으로 유배당해 버리고 없었다.\n\n - 김승옥, 〖무진기행〗 에서",
                          num1Text: "수심이 얕아서 항구로 개발하기 어려운 공간이다.",
                          num2Text: "산으로 둘러싸여 있고 평야가 발달하지 않은 공간이다.",
                          num3Text: "지역의 경제적 여건에 비해 인구가 적지 않은 공간이다.",
                          num4Text: "누구나 인정할 만한 지역의 명산물로 안개가 유명한 공간이다.",
                          answer: 4),
            QuestionModel(num: 6,
                          questionText: "다음 글의 빈칸에 들어갈 사자성어로 적절한 것은?",
                          reference: "세상에는 어려운 일들이 많지만 외국 여행 다녀온 사람의 입을 막는 것도 그중 하나이다. 특히 그것이 그 사람의 첫외국 여행이었다면, 입 막기는 포기하고 미주알고주알 늘어놓는 여행 경험을 들어 주는 편이 정신 건강에좋다. 그사람이별것아닌 사실을 [    ]하거나 특수한 경험을 지나치게 일반화한들, 그런 수다로 큰 피해를 입는 것도 아니지 않은가?",
                          num1Text: "刻舟求劍",
                          num2Text: "捲土重來",
                          num3Text: "臥薪嘗膽",
                          num4Text: "針小棒大",
                          answer: 4),
            QuestionModel(num: 7,
                          questionText: "다음 글을 감상한 내용으로 가장 적절한 것은?",
                          reference: " 어이 못 오던가 무 일로 못 오던가\n 너 오 길 위에 무쇠로 성(城)을 고 성안에 담 고 담 안에란 집을 짓고 집 안에란 뒤주 노코 뒤주 안에 궤를 노코 궤 안에 너를 결박(結縛)여 너코 쌍(雙)목 외걸쇠에 용(龍)거북 믈쇠로 수기수기 갓더냐 네 어이 그리 아니 오던가\n  이 서른 날이여니 날 보라 올 하루 업스랴\n\n - 작자 미상, 어이 못 오던가 -",
                          num1Text: "동일 구절을 반복하여 ‘너’에 대한 섭섭한 감정을 표출하고 있다.",
                          num2Text: "날짜 수를 대조하여 헤어진 기간이 길다는 것을 강조하고 있다.",
                          num3Text: "동일한 어휘를 연쇄적으로 나열하여 감정의 기복을 표현하고 있다.",
                          num4Text: "단계적으로 공간을 축소하여 ‘너’를 만날 수 있다는 희망을 표현하고 있다.",
                          answer: 1),
            QuestionModel(num: 8,
                          questionText: "(가)와 (나)에 들어갈 말로 가장 적절한 것은?",
                          reference: "  특정한 작업을 수행하기 위해 신체 근육의 특정 움직임을 조작하는 능력을 운동 능력이라고 한다. 언어에 관한 운동 능력은 ‘발음 능력’과 ‘필기 능력’ 두 가지인데 모두 표현을 위한 능력이다.\n  말로 표현하기 위해서는 발음 능력이 필요한데, 이는 음성 기관을 움직여 원하는 음성을 만들어 내는 능력이다. 이 능력은 영ᆞ유아기에 수많은 시행착오와 꾸준한 훈련을 통해 습득된다. 이렇게 발음 능력을 습득하면 음성 기관의 움직임은 자동화되어 음성 기관의 어느 부분을 언제 어떻게 움직일지를 화자가 거의 의식하지 않는다. 우리가 모어에 없는 외국어 음성을 발음하기 어려운 이유는 [ (가) ] 있기 때문이다.\n  글로 표현하기 위해서는 필기 능력이 필요하다. 필기에서는 글자의 모양을 서로 구별되게 쓰는 것은 기본이고 그 수준을 넘어서서 쉽게 알아볼 수 있는 모양으로 잘 쓰는 것도 필요하다. 글씨를 쓰기 위해 손을 놀리는 것은 발음을 하기 위해 음성 기관을 움직이는 것에 비해 상당히 의식적이라 할 수 있다. 그렇지만 개인의 의지와 관계없이 필체가 꽤 일정하다는 사실은 손을 놀리는 데에 [ (나) ] 의미한다.",
                          num1Text: "(가): 음성 기관의 움직임이 모어의 음성에 맞게 자동화되어\n(나): 무의식적이고 자동적인 면이 있음을",
                          num2Text: "(가): 낯선 음성은 무의식적으로 발음하도록 훈련되어\n(나): 유아기에 수행한 훈련이 효과적이지 않음을",
                          num3Text: "(가): 음성 기관의 움직임이 모어의 음성에 맞게 자동화되어\n(나): 유아기에 수행한 훈련이 효과적이지 않음을",
                          num4Text: "(가): 낯선 음성은 무의식적으로 발음하도록 훈련되어\n(나): 무의식적이고 자동적인 면이 있음을",
                          answer: 1),
            QuestionModel(num: 9,
                          questionText: "ㄱ~ㄹ중 한글 맞춤법에 맞게 쓰인 것만을 모두 고르면?",
                          reference: "○ 혜인 씨에게 "+"ᄀ무정타".underLined+" 말하지 마세요.\n○ 재아에게는 "+"ᄂ섭섭치".underLined+" 않게 사례해 주자.\n○ 규정에 따라 딱 세 명만 "+"ᄃ선발토록".underLined+" 했다.\n○ "+"ᄅ생각컨대".underLined+" 그의 보고서는 공정하지 못했다.",
                          num1Text: "ㄱ, ㄴ",
                          num2Text: "ㄱ, ㄷ",
                          num3Text: "ㄴ, ㄹ",
                          num4Text: "ㄷ, ㄹ",
                          answer: 2),
            QuestionModel(num: 10,
                          questionText: "ㄱ~ㄹ의 한자로 적절하지 않은 것은?",
                          reference: "  예정보다 지연되긴 했으나 열 시쯤에는 마애불에 "+"ᄀ도착".underLined+"할 수가 있었다. 맑은 날씨에 빛나는 햇살이 환히 비춰 "+"ᄂ불상".underLined+"들은 불그레 물들어 있었다. 만일 신비로운 "+"ᄃ경지".underLined+"라는 말을 할 수 있다면 바로 이런 경우가 아닐지 모르겠다. 꼭 보고 싶다는 숙원이 이루어진 기쁨에 가슴이 벅차 왔다. 아마 잊을 수 없는 "+"ᄅ추억".underLined+"의 한 토막으로 남을 것 같다.",
                          num1Text: "ᄀ: 到着",
                          num2Text: "ᄂ: 佛像",
                          num3Text: "ᄃ: 境地",
                          num4Text: "ᄅ: 記憶",
                          answer: 4),
            QuestionModel(num: 11,
                          questionText: "다음 글을 이해한 내용으로 적절하지 않은 것은?",
                          reference: "  사람의‘지각과 생각’은 항상 어떤 맥락, 관점 혹은 어떤 평가 기준이나 가정하에서 일어난다. 이러한 맥락, 관점, 평가 기준, 가정을 프레임이라고 한다. 지각과 생각은 인간의 모든 정신 활동을 뜻한다. 따라서 우리의 모든 정신 활동은 진공 상태에서 일어나는 것이 아니라, 어떤 맥락이나 가정하에서 일어난다. 한마디로 우리가 프레임이라는 안경을 쓰고 세상을 보고 있음을 의미한다. 간혹 어떤 사람이 자신은 어떤 프레임의 지배도 받지 않고 세상을 있는 그대로, 객관적으로 본다고 주장한다면, 그 주장은 진실이 아닐 것이다.",
                          num1Text: "인간의 정신 활동은 프레임 없이 일어나지 않는다.",
                          num2Text: "프레임은 인간이 세상을 바라볼 때 어떤 편향성을 가지게 한다.",
                          num3Text: "인간의 지각과 사고를 확장하는 과정에서 프레임은 극복해야 할 대상이다.",
                          num4Text: "프레임은 인간의 정신 활동에 영향을 미치는 어떤 맥락이나 평가 기준이다.",
                          answer: 3),
            QuestionModel(num: 12,
                          questionText: "다음 글을 이해한 내용으로 가장 적절한 것은?",
                          reference: "  전 세계를 대표하는 항공기인 보잉과 에어버스의 중요한 차이점은 자동조종시스템의 활용 정도에 있다. 보잉의 경우, 조종사가 대개 항공기를 조종간으로 직접 통제한다. 조종간은 비행기의 날개와 물리적으로 연결되어 있어서 어떤 상황에서도 조종사가 조작한 대로 반응한다. 이와 다르게 에어버스는 조종간 대신 사이드스틱을 설치하여 컴퓨터가 조종사의 행동을 제한 하거나 조종에 개입할 수 있게 설계되었다. 보잉에서는 조종사가 항공기를 통제할 수 있는 전권을 가지지만 에어버스에서는 컴퓨터가 조종사의 조작을 감시하고 제한한다.\n  보잉과 에어버스의 이러한 차이는 기계를 다루는 인간을 바라보는 관점이 서로 다른 데서 비롯된다. 보잉사를 창립한 윌리엄 보잉의 철학은 “비행기를 통제하는 최종 권한은 언제나 조종사에게 있다.”이다. 시스템은 불안정하고 완벽하지 않기 때문에 컴퓨터가 조종사의 판단보다 우선시될 수 없다는 것이다. 반면 에어버스의 아버지라고 불리는 베테유는 “인간은 실수할 수 있는 존재”라고 전제한다. 베테유는 이런 자신의 신념을 토대로 에어버스를 설계함으로써 조종사의 모든 조작을 컴퓨터가 모니터링하고 제한하게 만든 것이다.",
                          num1Text: "보잉은 시스템의 불완전성을, 에어버스는 인간의 실수 가능성을 고려하여 설계되었다.",
                          num2Text: "베테유는 인간이 실수할 수 있는 존재라고 보지만 윌리엄 보잉은 그렇지 않다고 본다.",
                          num3Text: "에어버스의 조종사는 항공기 운항에서 자동조종시스템을 통제하고 조작한다.",
                          num4Text: "보잉의 조종사는 자동조종시스템을 사용하지 않고 항공기를 조종한다.",
                          answer: 1),
            QuestionModel(num: 13,
                          questionText: "다음 글에서 추론한 내용으로 가장 적절한 것은?",
                          reference: "  공포의 상태와 불안의 상태를 구분하는 것은 쉽지 않다. 왜냐하면 두 감정을 함께 느끼거나 한 감정이 다른 감정을 유발할 때가 많기 때문이다. 가령, 무시무시한 전염병을 목도하고 공포에 빠진 사람은 자신도 언젠가 그 병에 걸릴지 모른다는 불안 상태에 빠지게 된다. 이처럼 두 감정은 서로 밀접하게 얽혀 있다는 점에서 혼동하기 쉽다. 하지만 두 감정을 야기한 원인을 따져 보면 두 감정을 명확하게 구분할 수 있다. 공포는 실재하는 객관적 위협에 의해 야기된 상태를 의미하고, 불안은 현재 발생하지 않았으며 미래에 일어날지 모르는 불명확한 위협에 의해 야기된 상태를 의미한다. 공포와 불안의 감정은 둘 다 자아와 관련되어 있지만 여기에서도 차이를 찾을 수 있다. 공포를 느끼는 것은 ‘나 자신’이 위험한 상황에 놓여 있다는 사실을 아는 것이고, 불안의 경험은 ‘나 자신’이 위해를 입을까 봐 걱정하는 것이다.",
                          num1Text: "자신이 처한 위험한 상황을 정확히 인식하는 경우에는 공포감에 비해 불안감이 더 크다.",
                          num2Text: "전기ᆞ가스 사고가 날까 두려워 외출하지 못하는 사람은 불안한 상태에 있는 것이다.",
                          num3Text: "시험에 불합격할 수 있다는 생각에 사로잡힌 사람은 공포감에 빠져 있는 것이다.",
                          num4Text: "과거에 큰 교통사고를 경험한 사람은 공포감은 크지만 불안감은 작다.",
                          answer: 2),
            QuestionModel(num: 14,
                          questionText: "다음 글의 내용과 부합하지 않는 것은?",
                          reference: "  과학 혁명 이전 아리스토텔레스 철학은 로마 가톨릭교의 정통 교리와 결합되어 있었기 때문에 오랜 시간 동안 지배적인 영향력을 발휘하였다. 천문 분야 또한 예외는 아니었다. 아리스토텔레스의 세계관을 따라 우주의 중심은 지구이며, 모든 천체는 원운동을 하면서 지구의 주위를 공전한다는 천동설이 정설로 자리 잡고 있었다. 프톨레마이오스가 천체들의 공전 궤도를 관찰하던 도중, 행성들이 주기적으로 종전의 운동과는 반대 방향으로 움직인다는 관찰 결과를 얻었을 때도 그는 이를 행성의 역행 운동을 허용하지 않는 천동설로 설명하고자 하였다. 그래서 지구를 중심으로 공전하는 원 궤도에 중심을 두고 있는 원, 즉 주전원(周轉圓)을 따라 공전 궤도를 그리면서 행성들이 운동한다고 주장하였다.\n  과학과 아리스토텔레스 철학의 결별은 서서히 일어났다. 그 과정에서 일어난 가장 중요한 사건은 1543년 코페르니쿠스가 행성들의 운동 이론에 관한 책을 발간한 일이다. 코페르니쿠스는 천체의 중심에 지구 대신 태양을 놓고 지구가 태양의 주위를 공전한다고 주장하였다. 태양을 우주의 중심에 둔 코페르니쿠스의 지동설은 행성들의 운동에 대해 프톨레마이오스보다 수학적으로 단순하게 설명하였다.",
                          num1Text: "과학 혁명 이전 시기에는 천동설이 정설로 받아들여졌다.",
                          num2Text: "프톨레마이오스의 주전원은 지동설을 지지하고자 만든 개념이다.",
                          num3Text: "천동설과 지동설은 우주의 중심을 어디에 두느냐에 따라 구분된다.",
                          num4Text: "행성의 공전에 대한 프톨레마이오스의 설명은 코페르니쿠스의 설명보다 수학적으로 복잡하였다.",
                          answer: 2),
            QuestionModel(num: 15,
                          questionText: "밑줄 친 단어가 표준어 규정에 맞게 쓰인 것은?",
                          num1Text: "저기 보이는 게 암염소인가, "+"수염소".underLined+"인가?",
                          num2Text: "오늘 "+"윗층".underLined+"에 사시는 분이 이사를 가신대요.",
                          num3Text: "봄에는 여기저기에서 "+"아지랭이".underLined+"가 피어오른다.",
                          num4Text: "그는 수업을 마치면 "+"으레".underLined+" 친구들과 운동을 한다.",
                          answer: 4),
            QuestionModel(num: 16,
                          questionText: "ㄱ~ㄹ을 문맥에 맞게 수정하는 방안으로 적절한 것은?",
                          reference: "난독(難讀)을 해결하려면 정독을 해야 한다. 여기서 말하는 정독은 ‘뜻을 새겨 가며 자세히 읽음’, 즉 ‘정교한 독서’라는 뜻으로 한자로는 ‘精讀’이다. ‘精讀’은 ‘바른 독서’를 의미하는 ‘正讀’과 "+"ᄀ소리는 같지만 뜻이 다르다.".underLined+" 무엇이 정교한 것일까? 모든 단어에 눈을 마주치면서 제대로 인식하는 것이다. 이와 같은 "+"ᄂ정독(精讀)".underLined+"의 결과로 생기는 어문 실력이 문해력이다. 문해력이 발달하면 결국 독서 속도가 빨라져, ‘빨리 읽기’인 속독(速讀)이 가능해진다. 빨리 읽기는 정독을 전제로 할 때 빛을 발한다. 짧은 시간에 같은 책을 제대로 여러 번 읽을 수 있기 때문이다. 그래서 문해력의 증가는 ‘정교하고 빠르게 읽기’, 즉 "+"ᄃ정속독(正速讀)".underLined+"에서 일어나게 되어 있다. 정독이 생활화되면 자기도 모르게 정속독의 경지에 오르게 된다. 그런 경지에 오른 사람들은 뭐든지 확실히 읽고 빨리 이해한다. 자연스레 집중하고 여러 번 읽어도 빠르게 읽으므로 시간이 여유롭다. "+"ᄅ 정독이 빠진 속독".underLined+"은 곧 빼먹고 읽는 습관, 즉 난독의 일종임을 잊지 말아야 한다.",
                          num1Text: "ᄀ을 ‘다르게 읽지만 뜻이 같다’로 수정한다.",
                          num2Text: "ᄂ을 ‘정독(正讀)’으로 수정한다.",
                          num3Text: "ᄃ을 ‘정속독(精速讀)’으로 수정한다.",
                          num4Text: "ᄅ을 ‘속독이 빠진 정독’으로 수정한다.",
                          answer: 3),
            QuestionModel(num: 17,
                          questionText: "다음 글을 감상한 내용으로 적절하지 않은 것은?",
                          reference: "막바지 뙤약볕 속\n한창 매미 울음은\n한여름 무더위를 그 절정까지 올려놓고는 이렇게 다시 조용할 수 있는가.\n지금은 아무 기척도 없이\n정적의 소리인 듯 쟁쟁쟁\n천지(天地)가 하는 별의별\n희한한 그늘의 소리에\n멍청히 빨려 들게 하구나.\n사랑도 어쩌면\n그와 같은 것인가.\n소나기처럼 숨이 차게 정수리부터 목물로 들이붓더니 얼마 후에는\n그것이 아무 일도 없었던 양 맑은 구름만 눈이 부시게 하늘 위에 펼치기만 하노니.\n\n - 박재삼, '매미 울음 끝에' -",
                          num1Text: "갑작스럽게 변화한 자연 현상을 감각적으로 제시하고 있다.",
                          num2Text: "청각적 이미지와 시각적 이미지를 활용하여 시상을 전개하고 있다.",
                          num3Text: "소나기가 그치고 맑은 구름이 펼쳐진 것을 통해 사랑의 속성을 드러내고 있다.",
                          num4Text: "매미 울음소리가 절정에 이르렀다가 사라진 직후의 상황을 반어법으로 표현하고 있다.",
                          answer: 4),
            QuestionModel(num: 18,
                          questionText: "다음 글을 이해한 내용으로 가장 적절한 것은?",
                          reference: "  루카치는 그리스 세계를 신과 인간의 결합 정도를 가리키는 ‘총체성’ 개념을 기준으로 세 시대로 구분하였다. 첫 번째 시대에서 후대로 갈수록 총체성의 정도는 낮아진다. 첫째는 총체성이 완전히 구현되어 있는 ‘서사시의 시대’이다. 호메로스의 '일리아드'와 '오디세이아'에서는 신과 인간의 세계가 하나로 얽혀 있다. 인간들이 그리스와 트로이 두 패로 나뉘어 전쟁을 벌일 때 신들도 인간의 모습을 하고 두 패로 나뉘어 전쟁에 참여했다. 둘째는 ‘비극의 시대’이다. 소포클레스나 에우리피데스의 비극에서는 총체성이 흔들려 신과 인간의 세계가 분리된다. 하지만 두 세계가 완전히 분리되지는 않고 신탁이라는 약한 통로로 이어져 있다. 비극에서 신은 인간의 행위에 직접 개입하지 않고 신탁을 통해서 자신의 뜻을 그저 전달하는 존재로 바뀐다. 셋째는 플라톤으로 대표되는 ‘철학의 시대’이다. 이 시대는 이미 계몽된 세계여서 신탁 같은 것은 신뢰할 수 없게 되었다. 신과 인간의 세계가 완전히 분리됨으로써 신의 세계는 인격적 성격을 상실하여 ‘이데아’라는 추상성의 세계로 바뀐다. 신의 세계와 인간의 세계는 그 사이에 어떤 통로도 존재할 수 없는, 절대적으로 분리된 세계가 되었다.",
                          num1Text: "계몽사상은 서사시의 시대에서 철학의 시대로의 전환을 이끌었다.",
                          num2Text: "플라톤의 이데아는 신탁이 사라진 시대의 비극적 세계를 표현한다.",
                          num3Text: " 루카치는 각기 다른 기준에 따라 그리스 세계를 세 시대로 구분하였다.",
                          num4Text: "에우리피데스의 비극에 비해 '오디세이아'에서는 신과 인간의 결합 정도가 높다.",
                          answer: 4),
            QuestionModel(num: 19,
                          questionText: "다음 글의 내용과 부합하지 않는 것은?",
                          reference: "  몽유록(夢遊錄)은 ‘꿈에서 놀다 온 기록’이라는 뜻으로, 어떤 인물이 꿈에서 과거의 역사적 인물을 만나 특정 사건에 대한 견해를 듣고 현실로 돌아온다는 특징이 있다. 이때 꿈을 꾼 인물인 몽유자의 역할에 따라 몽유록을 참여자형과 방관자형으로 구분할 수 있다. 참여자형에서는 몽유자가 꿈에서 만난 인물들의 모임에 초대를 받고 토론과 시연에 직접 참여한다. 방관자형 에서는 몽유자가 인물들의 모임을 엿볼 뿐 직접 그 모임에 참여하지는 않는다. 16~17세기에 창작되었던 몽유록에는 참여자형이 많다. 참여자형에서는 몽유자와 꿈속 인물들이 동질적인 이념을 공유하고 현실의 고통스러운 문제에 대해 의견을 나누며 비판적 목소리를 낸다. 그러나 주로 17세기 이후에 창작된 방관자형에서는 몽유자가 꿈속 인물들과 함께 현실을 비판하는 것이 아니라 구경꾼의 위치에 서 있다. 이 시기의 몽유록이 통속적이고 허구적인 성격으로 변모하는 것은 몽유자의 역할 변화와 무관하지 않다.",
                          num1Text: "몽유자가 꿈속 인물들의 모임에 직접 참여하는지, 참여하지 않는지에 따라 몽유록의 유형을 나눌 수 있다.",
                          num2Text: "17세기보다 나중 시기의 몽유록에서는 몽유자가 현실을 비판하는 경향이 강하게 나타난다.",
                          num3Text: "몽유자가 모임의 구경꾼 역할을 하는 몽유록은 통속적이고 허구적인 성격이 강하다.",
                          num4Text: "몽유자가 꿈속 인물들과 함께 현실을 비판하는 몽유록은 참여자형에 해당한다.",
                          answer: 2),
            QuestionModel(num: 20,
                          questionText: "다음 글을 이해한 내용으로 적절한 것은?",
                          reference: "  디지털 트윈은 현실 세계와 똑같은 가상의 세계이다. 최근 주목받고 있는 메타버스와 개념은 유사하지만 활용 목적의 측면에서 구별된다. 메타버스는 가상 세계와 현실 세계가 융합된 플랫폼으로 이용자들에게 새로운 경제ᆞ사회ᆞ문화적 경험을 제공하는 데 목적을 둔다. 반면 디지털 트윈은 현실 세계에 존재하는 사물, 공간, 환경, 공정 등을 컴퓨터상에 디지털 데이터 모델로 표현하여 똑같이 복제하고 실시간으로 서로 반응할 수 있도록 한다. 그래서 디지털 트윈의 이용자는 가상 세계에서의 시뮬레이션을 통해 미래 상황을 예측할 수 있게 된다. 디지털 트윈에 대한 수요가 증가하면서 관련 시장도 확대되고 있으며, 국내외의 글로벌 기업들은 여러 산업 분야에서 디지털 트윈을 도입하여 사전에 위험 요소를 제거하고 수익 모델의 효율성을 높이고 있다. 디지털 트윈이 이렇게 주목받는 이유는 안정성과 경제성 때문인데 현실 세계를 그대로 옮겨 놓은 가상 세계에 데이터를 전송, 취합, 분석, 이해, 실행하는 과정은 실제 실험보다 매우 빠르고 정밀하며 안전할 뿐 아니라 비용도 적게 든다.",
                          num1Text: "디지털 트윈을 활용함에 따라 글로벌 기업들의 고용률이 향상되었다.",
                          num2Text: "디지털 트윈의 데이터 모델은 현실 세계의 각종 실험 모델보다 경제성이 낮다.",
                          num3Text: "디지털 트윈에서의 시뮬레이션으로 현실 세계의 위험 요소를 찾아내고 방지할 수 있다.",
                          num4Text: "디지털 트윈은 현실 세계의 이용자에게 새로운 문화적 경험을 제공하는 데 목적이 있다.",
                          answer: 3)
            
        ]
        let exam = ExamModel(id: 202311, year: 2023, examTypeID: "국가직", subjectID: "국어", questions: questions)
        exams2023.append(exam)
    }
    
    func saveExam202312() {
        let questions = [
            
            QuestionModel(num: 1,
                          questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오.",
                          reference: "Jane wanted to have a small wedding rather than a fancy one. Thus, she planned to invite her family and a few of her "+"intimate".underLined+" friends to eat delicious food and have some pleasant moments.",
                          num1Text: "nosy",
                          num2Text: "close",
                          num3Text: "outgoing",
                          num4Text: "considerate",
                          answer: 2),
            QuestionModel(num: 2, questionText: "밑줄친 부분의 의미와 가장 가까운것을 고르시오.", reference: "The "+"incessant".underLined+" public curiosity and consumer demand due to the health benefits with lesser cost has increased the interest in functional foods.",
                          num1Text: "rapid",
                          num2Text: "constant",
                          num3Text: "significant",
                          num4Text: "intermittent",
                          answer: 2),
            QuestionModel(num: 3,
                          questionText: "밑줄친 부분의 의미와 가장 가까운것을 고르시오.",
                          reference: "Because of the pandemic, the company had to "+"hold off".underLined+" the plan to provide the workers with various training programs.",
                          num1Text: "elaborate",
                          num2Text: "release",
                          num3Text: "modify",
                          num4Text: "suspend",
                          answer: 4),
            QuestionModel(num: 4,
                          questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한것을 고르시오.",
                          reference: "The new Regional Governor said he would "+"abide by".underLined+" the decision of the High Court to release the prisoner.",
                          num1Text: "accept",
                          num2Text: "report",
                          num3Text: "postpone",
                          num4Text: "announce",
                          answer: 1),
            QuestionModel(num: 5,
                          questionText: "밑줄 친 부분 중 어법상 옳지 않은 것은?",
                          reference: "While advances in transplant technology have made "+"1)it".underLined+" possible to extend the life of individuals with end-stage organ disease, it is argued "+"2)that".underLined+" the biomedical view of organ transplantation as a bounded event, which ends once a heart or kidney is successfully replaced, "+"3)conceal".underLined+" the complex and dynamic process that more "+"4)accurately".underLined+" represents the experience of receiving an organ.",
                          num1Text: "",
                          num2Text: "",
                          num3Text: "",
                          num4Text: "",
                          answer: 3),
            QuestionModel(num: 6,
                          questionText: "어법상 옳지 않은 것은?",
                          num1Text: "All assignments are expected to be turned in on time.",
                          num2Text: "Hardly had I closed my eyes when I began to think of her.",
                          num3Text: "The broker recommended that she buy the stocks immediately.",
                          num4Text: "A woman with the tip of a pencil stuck in her head has finally had it remove.",
                          answer: 4),
            QuestionModel(num: 7,
                          questionText: "우리말을 영어로 잘못 옮긴 것은?",
                          num1Text: "내 고양이 나이는 그의 고양이 나이의 세 배이다.\n→My cat is three times as old as his.",
                          num2Text: "우리는 그 일을 이번 달 말까지 끝내야 한다.\n→We have to finish the work until the end of this month.",
                          num3Text: "그녀는 이틀에 한 번 머리를 감는다.\n→She washes her hair every other day.",
                          num4Text: "너는 비가 올 경우에 대비하여 우산을 갖고 가는 게 낫겠다.\n→You had better take an umbrella in case it rains.",
                          answer: 2),
            QuestionModel(num: 8,
                          questionText: "다음 글의 내용과 일치하지 않는 것은?",
                          reference: "Are you getting enough choline? Chances are, this nutrient isn’t even on your radar. It’s time choline gets the attention it deserves. A shocking 90 percent of Americans aren’t getting enough choline, according to a recent study. Choline is essential to health at all ages and stages, and is especially critical for brain development. Why aren’t we getting enough? Choline is found in many different foods but in small amounts. Plus, the foods that are rich in choline aren’t the most popular: think liver, egg yolks and lima beans. Taylor Wallace, who worked on a recent analysis of choline intake in the United States, says, “There isn’t enough awareness about choline even among health-care professionals because our government hasn’t reviewed the data or set policies around choline since the late ’90s.”",
                          num1Text: "A majority of Americans are not getting enough choline.",
                          num2Text: "Choline is an essential nutrient required for brain development.",
                          num3Text: "Foods such as liver and lima beans are good sources of choline.",
                          num4Text: "The importance of choline has been stressed since the late ’90s in the U.S.",
                          answer: 4),
            QuestionModel(num: 9,
                          questionText: "다음 글의 내용과 일치하는 것은?",
                          reference: "Around 1700 there were, by some accounts, more than 2,000 London coffeehouses, occupying more premises and paying more rent than any other trade. They came to be known as penny universities, because for that price one could purchase a cup of coffee and sit for hours listening to extraordinary conversations. Each coffeehouse specialized in a different type of clientele. In one, physicians could be consulted. Others served Protestants, Puritans, Catholics, Jews, literati, merchants, traders, Whigs, Tories, army officers, actors, lawyers, or clergy. The coffeehouses provided England’s first egalitarian meeting place, where a man chatted with his tablemates whether he knew them or not.",
                          num1Text: "The number of coffeehouses was smaller than that of any other business.",
                          num2Text: "Customers were not allowed to stay for more than an hour in a coffeehouse.",
                          num3Text: "Religious people didn’t get together in a coffeehouse to chat.",
                          num4Text: "One could converse even with unknown tablemates in a coffeehouse",
                          answer: 4),
            QuestionModel(num: 10,
                          questionText: "밑줄 친 부분에 들어갈 말로 알맞은 것을 고르시오.",
                          reference: "A: I got this new skin cream from a drugstore yesterday. It is supposed to remove all wrinkles and make your skin look much younger.\n\nB: __________________________\n\nA: Why don’t you believe it? I’ve read in a few blogs that the cream really works.\n\nB: I assume that the cream is good for your skin, but I don’tthink that it is possible to get rid of wrinkles or magically look younger by using a cream.\n\nA: You are so pessimistic.\n\nB: No, I’m just being realistic. I think you are being gullible.",
                          num1Text: "I don’t buy it.",
                          num2Text: "It’s too pricey.",
                          num3Text: "I can’t help you out.",
                          num4Text: "Believe it or not, it’s true.",
                          answer: 1),
            QuestionModel(num: 11,
                          questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한것을 고르시오.",
                          reference: "A: I’d like to go sightseeing downtown. Where do you think I should go?\n\nB: I strongly suggest you visit the national art gallery.\n\nA: Oh, that’s a great idea. What else should I check out?\n\nB: _____________________________________________\n\nA: I don’t have time for that. I need to meet a client at three. B: Oh, I see. Why don’t you visit the national park, then? A: That sounds good. Thank you!",
                          num1Text: "This is the map that your client needs. Here you go.",
                          num2Text: "A guided tour to the river park. It takes all afternoon.",
                          num3Text: "You should check it out as soon as possible.",
                          num4Text: "The checkout time is three o’clock.",
                          answer: 2),
            QuestionModel(num: 12,
                          questionText: "두 사람의 대화 중 자연스럽지 않은 것은?",
                          num1Text: "A: He’s finally in a hit movie!\nB: Well, he’s got it made.",
                          num2Text: "A: I’m getting a little tired now.\nB: Let’s call it a day.",
                          num3Text: "A: The kids are going to a birthday party.\nB: So, it was a piece of cake.",
                          num4Text: "A: I wonder why he went home early yesterday.\nB: I think he was under the weather.",
                          answer: 3),
            QuestionModel(num: 13,
                          questionText: "다음 글의 제목으로 알맞은 것은?",
                          reference: "The feeling of being loved and the biological response it stimulates is triggered by nonverbal cues: the tone in a voice, the expression on a face, or the touch that feels just right. Nonverbal cues ―rather than spoken words ―make us feel that the person we are with is interested in, understands, and values us. When we’re with them, we feel safe. We even see the power of nonverbal cues in the wild. After evading the chase of predators, animals often nuzzle each other as a means of stress relief. This bodily contact provides reassurance of safety and relieves stress.",
                          num1Text: "How Do Wild Animals Think and Feel?",
                          num2Text: "Communicating Effectively Is the Secret to Success",
                          num3Text: "Nonverbal Communication Speaks Louder than Words",
                          num4Text: "Verbal Cues: The Primary Tools for Expressing Feelings",
                          answer: 3),
            QuestionModel(num: 14,
                          questionText: "다음 글의 주제로 알맞은 것은?",
                          reference: "There are times, like holidays and birthdays, when toys and gifts accumulate in a child’s life. You can use these times to teach a healthy nondependency on things. Don’t surround your child with toys. Instead, arrange them in baskets, have one basket out at a time, and rotate baskets occasionally. If a cherished object is put away for a time, bringing it out creates a delightful remembering and freshness of outlook. Suppose your child asks for a toy that has been put away for a while. You can direct attention toward an object or experience that is already in the environment. If you lose or break a possession, try to model a good attitude (“I appreciated it while I had it!”) so that your child can begin to develop an attitude of nonattachment. If a toy of hers is broken or lost, help her to say, “I had fun with that.”",
                          num1Text: "building a healthy attitude toward possessions",
                          num2Text: "learning the value of sharing toys with others",
                          num3Text: "teaching how to arrange toys in an orderly manner",
                          num4Text: "accepting responsibility for behaving in undesirable ways",
                          answer: 1),
            QuestionModel(num: 15,
                          questionText: "다음 글의 요지로 알맞은 것은?",
                          reference: "Many parents have been misguided by the “self-esteem movement,” which has told them that the way to build their children’s self-esteem is to tell them how good they are at things. Unfortunately, trying to convince your children of their competence will likely fail because life has a way of telling them unequivocally how capable or incapable they really are through success and failure. Research has shown that how you praise your children has a powerful influence on their development. Some researchers found that children who were praised for their intelligence, as compared to their effort, became overly focused on results. Following a failure, these same children persisted less, showed less enjoyment, attributed their failure to a lack of ability, and performed poorly in future achievement efforts. Praising children for intelligence made them fear difficulty because they began to equate failure with stupidity.",
                          num1Text: "Frequent praises increase self-esteem of children.",
                          num2Text: "Compliments on intelligence bring about negative effect.",
                          num3Text: "A child should overcome fear of failure through success.",
                          num4Text: "Parents should focus on the outcome rather than the process.",
                          answer: 2),
            QuestionModel(num: 16,
                          questionText: "밑줄 친 부분에 들어갈 말로 알맞은 것은?",
                          reference: "In recent years, the increased popularity of online marketing and social media sharing has boosted the need for advertising standardization for global brands. Most big marketing and advertising campaigns include a large online presence. Connected consumers can now zip easily across borders via the internet and social media, making it difficult for advertisers to roll out adapted campaigns in a controlled, orderly fashion. As a result, most global consumer brands coordinate their digital sites internationally. For example, Coca-Cola web and social media sites around the world, from Australia and Argentina to France, Romania, and Russia, are surprisingly __________. All feature splashes of familiar Coke red, iconic Coke bottle shapes, and Coca-Cola’s music and “Taste the Feeling” themes.",
                          num1Text: "experimental",
                          num2Text: "uniform",
                          num3Text: "localized",
                          num4Text: "diverse",
                          answer: 2),
            QuestionModel(num: 17,
                          questionText: "다음 글의 흐름상 어색한 문장은?",
                          reference: "In our monthly surveys of 5,000 American workers and 500 U.S. employers, a huge shift to hybrid work is abundantly clear for office and knowledge workers. "+"1)An emerging norm is three days a week in the office and two at home, cutting days on site by 30 % or more.".underLined+" You might think this cutback would bring a huge drop in the demand for office space. "+"2)But our survey data suggests cuts in office space of 1% to 2% on average, implying big reductions in density not space.".underLined+" We can understand why. High density at the office is uncomfortable and many workers dislike crowds around their desks. "+"3)Most employees want to work from home on Mondays and Fridays.".underLined+" Discomfort with density extends to lobbies, kitchens, and especially elevators. "+"4)The only sure-fire way to reduce density is to cut days on site without cutting square footage as much.".underLined+" Discomfort with density is here to stay according to our survey evidence.",
                          num1Text: "",
                          num2Text: "",
                          num3Text: "",
                          num4Text: "",
                          answer: 3),
            QuestionModel(num: 18, questionText: "주어진 문장이 들어갈 위치로 알맞은 것은?",
                          reference: "They installed video cameras at places known for illegal crossings, and put live video feeds from the cameras on a Web site.",
                          reference2: "Immigration reform is a political minefield. ( 1 ) About the only aspect of immigration policy that commands broad political support is the resolve to secure the U.S. border with Mexico to limit the flow of illegal immigrants. ( 2 ) Texas sheriffs recently developed a novel use of the Internet to help them keep watch on the border. ( 3 ) Citizens who want to help monitor the border can go online and serve as “virtual Texas deputies.” ( 4 ) If they see anyone trying to cross the border, they send a report to the sheriff’s office, which follows up, sometimes with the help of the U.S. Border Patrol.",
                          num1Text: "",
                          num2Text: "",
                          num3Text: "",
                          num4Text: "",
                          answer: 3),
            QuestionModel(num: 19,
                          questionText: "주어진 글 다음에 이어질 글의 순서로 알맞은 것은?",
                          reference: "All civilizations rely on government administration. Perhaps no civilization better exemplifies this than ancient Rome.",
                          reference2: "(A) To rule an area that large, the Romans, based in what is now central Italy, needed an effective system of government administration.\n\n(B) Actually, the word “civilization” itself comes from the Latin word civis, meaning “citizen.”\n\n(C) Latin was the language of ancient Rome, whose territory stretched from the Mediterranean basin all the way to parts of Great Britain in the north and the Black Sea to the east.",
                          num1Text: "(A) -(B) -(C)",
                          num2Text: "(B) -(A) -(C)",
                          num3Text: "(B) -(C) -(A)",
                          num4Text: "(C) -(A) -(B)",
                          answer: 3),
            QuestionModel(num: 20,
                          questionText: "밑줄 친 부분에 들어갈 말로 알맞은 것은?",
                          reference: "Over the last fifty years, all major subdisciplines in psychology have become more and more isolated from each other as training becomes increasingly specialized and narrow in focus. As some psychologists have long argued, if the field of psychology is to mature and advance scientifically, its disparate parts (for example, neuroscience, developmental, cognitive, personality, and social) must become whole and integrated again. Science advances when distinct topics become theoretically and empirically integrated under simplifying theoretical frameworks. Psychology of science will encourage collaboration among psychologists from various sub-areas, helping the field achieve coherence rather than continued fragmentation. In this way, psychology of science might act as a template for psychology as a whole by integrating under one discipline all of the major fractions/factions within the field. It would be no small feat and of no small import if the psychology of science could become a model for the parent discipline on how to combine resources and study science ______________________.",
                          num1Text: "from a unified perspective",
                          num2Text: "in dynamic aspects",
                          num3Text: "throughout history",
                          num4Text: "with accurate evidence",
                          answer: 1)
            
        ]
        let exam = ExamModel(id: 202312, year: 2023, examTypeID: "국가직", subjectID: "영어", questions: questions)
        exams2023.append(exam)
    }
    
    func saveExam202313() {
        let questions
        = [
            QuestionModel(num: 1,
                          questionText: "다음 유물이 사용된 시대에 대한 설명으로 옳은 것은?",
                          reference: "미송리식 토기, 팽이형 토기, 붉은 간 토기",
                          num1Text: "비파형 동검이 사용되었다.",
                          num2Text: "오수전 등의 화폐가 사용되었다.",
                          num3Text: "아슐리안형 주먹도끼가 사용되었다.",
                          num4Text: "철이 많이 생산되어 낙랑과 왜에 수출되었다.",
                          answer: 1),
            QuestionModel(num: 2,
                          questionText: "밑줄 친 ‘왕’에 대한 설명으로 옳은 것은?",
                          reference: "16년 겨울 10월, "+"왕".underLined+"이 질양(質陽)으로 사냥을 갔다가 길에 앉아 우는 자를 보았다. "+"왕".underLined+"이 말하기를 “아! 내가 백성의 부모가 되어 백성들이 이 지경에 이르게 하였으니 나의 죄로다.” ...(중략)... 그리고 관리들에게 명하여 매년 봄 3월부터 가을 7월까지 관청의 곡식을 내어 백성들의 식구 수에 따라 차등 있게 빌려주었다가, 10월에 이르러 상환하게 하는 것을 법규로 정하였다.\n\n - 삼국사기 -",
                          num1Text: "낙랑군을 축출하였다.",
                          num2Text: "'진대법'을 시행하였다",
                          num3Text: "백제의 침입으로 전사하였다.",
                          num4Text: "영락이라는 독자적인 연호를 사용하였다.",
                          answer: 2),
            QuestionModel(num: 3,
                          questionText: "(가)에 대한 설명으로 옳은 것은?",
                          reference: "신돈이 (가) 을/를 설치하자고 요청하자, ...(중략) ... 이제 도감이 설치되었다. ...(중략)... 명령이 나가자 권세가 중에 전민을 빼앗은 자들이 그 주인에게 많이 돌려주었으며, 전국에서 기뻐하였다.\n\n -고려사-",
                          num1Text: "시전의 물가를 감독하는 임무를 담당하였다.",
                          num2Text: "국가재정의 출납과 회계 업무를 총괄하였다.",
                          num3Text: "불법적으로 점유된 토지와 노비를 조사하였다.",
                          num4Text: "부족한 녹봉을 보충하고자 관료에게 녹과전을 지급하였다.",
                          answer: 3),
            QuestionModel(num: 4,
                          questionText: "다음과 같이 말한 인물에 대한 설명으로 옳은 것은?",
                          reference: "우리나라가 곧 고구려의 옛 땅이다. 그리고 압록강의 안팎 또한 우리의 지역인데 지금 여진이 그 사이에 몰래 점거하여 저항하고 교활하게 대처하고 있어서 ...(중략)... 만일 여진을 내쫓고 우리 옛 땅을 되찾아서 성보(城堡)를 쌓고 도로를 통하도록 하면 우리가 어찌 사신을 보내지 않겠는가?\n\n - 고려사 -",
                          num1Text: "목종을 폐위하였다.",
                          num2Text: "귀주에서 거란군을 물리쳤다.",
                          num3Text: "여진을 몰아내고 동북 9성을 쌓았다.",
                          num4Text: "소손녕과 담판하여 강동 6주를 획득하였다.",
                          answer: 4),
            QuestionModel(num: 5,
                          questionText: "밑줄 친 ‘이곳’에 대한 설명으로 옳은 것은?",
                          reference: "○ 장수왕은 남진정책의 일환으로 수도를 "+"이곳".underLined+"으로 천도하였다.\n○ 묘청은 "+"이곳".underLined+"으로 수도를 옮길 것을 주장하였다.",
                          num1Text: "쌍성총관부가 설치되었다.",
                          num2Text: "망이ᆞ망소이가 반란을 일으켰다.",
                          num3Text: "제너럴 셔먼호 사건이 발생하였다.",
                          num4Text: "1923년 조선 형평사가 결성되었다.",
                          answer: 3),
            QuestionModel(num: 6,
                          questionText: "다음 전투 이후에 일어난 사건으로 옳은 것만을 모두 고르면?",
                          reference: "이근행이 군사 20만 명의 대군을 이끌고 매소성(買肖城)에 머물렀다. 우리 군사가 공격하여 달아나게 하고 전마 30,380필을 얻었는데, 남겨놓은 병장기도 그 정도 되었다.\n\n- 삼국사기 -",
                          reference2: "ᄀ. 웅진도독부가 설치되었다.\nᄂ. 김흠돌이 반란을 일으켰다.\nᄃ. 교육 기관인 국학이 설립되었다.\nᄅ. 복신과 도침이 부여풍과 함께 백제 부흥 운동을 일으켰다.",
                          num1Text: "ㄱ,ㄴ",
                          num2Text: "ㄱ,ㄹ",
                          num3Text: "ㄴ,ㄷ",
                          num4Text: "ㄷ,ㄹ",
                          answer: 3),
            QuestionModel(num: 7,
                          questionText: "다음 사건을 시기순으로 바르게 나열한 것은?",
                          reference: "(가) 신라의 우산국 복속\n(나) 고구려의 서안평 점령\n(다) 백제의 대야성 점령\n(라) 신라의 금관가야 병합",
                          num1Text: "(가)→(나)→(다)→(라)",
                          num2Text: "(가)→(라)→(나)→(다)",
                          num3Text: "(나)→(가)→(라)→(다)",
                          num4Text: "(나)→(다)→(가)→(라)",
                          answer: 3),
            //MARK: - 2 answers
            QuestionModel(num: 8,
                          questionText: "고려시대 문화유산에 대한 설명으로 옳지 않은 것은?",
                          num1Text: "황해도 사리원 성불사 웅진전은 다포 양식의 건물이다.",
                          num2Text: "월정사 팔각 9층 석탑은 원의 석탑을 모방하여 제작하였다.",
                          num3Text: "여주 고달사지 승탑은 통일 신라의 팔각원당형 양식을 계승하였다.",
                          num4Text: "직지심체요절은 세계기록유산으로 등재된 현존하는 가장 오래된 금속활자본이다.",
                          answer: 1,
                          exception: "복수정답 (1,2)"), // 1,2
            QuestionModel(num: 9,
                          questionText: "조선시대 지도와 천문도에 대한 설명으로 옳지 않은 것은?",
                          num1Text: "대동여지도는 거리를 알 수 있도록 10리마다 눈금을 표시하였다.",
                          num2Text: "혼일강리역대국도지도는 중국에서 들여온 곤여만국전도를 참고하였다.",
                          num3Text: "천상열차분야지도는 하늘을 여러 구역으로 나누고 별자리를 표시한 그림이다.",
                          num4Text: "동국지도는 정상기가 실제 거리 100리를 1척으로 줄인 백리척을 적용하여 제작하였다.",
                          answer: 3),
            QuestionModel(num: 10,
                          questionText: "(가)에 대한 설명으로 옳지 않은 것은?",
                          reference: "임진왜란 이후에 우의정 유성룡도 역시 미곡을 거두는 것이 편리하다고 주장하였으나, 일이 성취되지 못하였다. 1608년에 이르러 좌의정 이원익의 건의로 (가) 을/를 비로소 시행하여, 민결(民結)에서 미곡을 거두어 서울로 옮기게 하였다.\n\n - 만기요람 -",
                          num1Text: "장시의 확대에 기여하였다.",
                          num2Text: "지주에게 결작을 부과하였다.",
                          num3Text: "공납의 폐단을 막기 위해 실시하였다.",
                          num4Text: "공인에게 비용을 지급하고 필요 물품을 조달하였다.",
                          answer: 2),
            QuestionModel(num: 11,
                          questionText: "(가) 인물이 추진한 정책으로 옳지 않은 것은?",
                          reference: "선비들 수만 명이 대궐 앞에 모여 만동묘와 서원을 다시 설립할 것을 청하니, (가) 이/가 크게 노하여 한성부의 조례(皂隷)와 병졸로 하여금 한강 밖으로 몰아내게 하고 드디어 천여 곳의 서원을 철폐하고 그 토지를 몰수하여 관에 속하게 하였다.\n\n - 대한계년사 -",
                          num1Text: "사창제를 실시하였다.",
                          num2Text: "'대전회통'을 편찬하였다.",
                          num3Text: "비변사의 기능을 강화하였다.",
                          num4Text: "통상 수교 거부 정책을 추진하였다.",
                          answer: 3),
            QuestionModel(num: 12,
                          questionText: "다음과 같은 선포문을 발표하면서 성립한 정부의 정책으로 옳지 않은 것은?",
                          reference: "제1조 대한민국은 민주공화제로 함\n... (중략) ...\n민국 원년 3월 1일 우리 대한민족이 독립을 선언한 뒤 ...(중략) ... 이제 본 정부가 전 국민의 위임을 받아 조직되었으니 전 국민과 더불어 전심(專心)으로 힘을 모아 국토 광복의 대사명을 이룰 것을 선서한다.",
                          num1Text: "독립 공채를 발행하였다.",
                          num2Text: "기관지로 '독립신문'을 발간하였다.",
                          num3Text: "비밀 행정 조직인 연통부를 설치하였다.",
                          num4Text: "재정 확보를 위하여 전환국을 설립하였다.",
                          answer: 4),
            QuestionModel(num: 13,
                          questionText: "밑줄 친 ‘나’가 집권하여 추진한 사실로 옳은 것은?",
                          reference: "나".underLined+"는 우리 국민이 선천적으로 타고난 재질을 최대한으로 활용하여 다각적인 생산 활동을 더욱 활발하게 하고, ...(중략)... 공산품 수출을 진흥시키는 데 가일층 노력할 것을 요망합니다. 끝으로 "+"나".underLined+"는 오늘 제1회 수출의 날 기념식에 즈음하여 ...(중략)... 이 뜻깊은 날이 자립경제를 앞당기는 또 하나의 계기가 될 것을 기원합니다.",
                          num1Text: "대통령 직선제 개헌을 추진하였다.",
                          num2Text: "3ᆞ1 민주 구국 선언을 발표하였다.",
                          num3Text: "반민족 행위 특별 조사 위원회를 구성하였다.",
                          num4Text: "베트남 파병에 필요한 조건을 명시한 브라운 각서를 체결하였다.",
                          answer: 4),
            QuestionModel(num: 14,
                          questionText: "다음과 같이 상소한 인물이 속한 붕당에 대한 설명으로 옳은 것만을 모두 고르면?",
                          reference: "상소하여 아뢰기를, “신이 좌참찬 송준길이 올린 차자를 보았는데, 상복(喪服) 절차에 대하여 논한 것이 신과는 큰 차이가 있었습니다. 장자를 위하여 3년을 입는 까닭은 위로 ‘정체(正體)’가 되기 때문이고 또 전중(傳重: 조상의 제사나 가문의 법통을 전함)하기 때문입니다. ...(중략)... 무엇보다 중요한 것은 할아버지와 아버지의 뒤를 이은 ‘정체’이지, 꼭 첫째이기 때문에 참최 3년복을 입는 것은 아닙니다.”라고 하였다.\n\n- 현종실록 -",
                          reference2: "ᄀ. 기사환국으로 정권을 장악하였다.\nᄂ. 인조반정을 주도하여 집권세력이 되었다.\nᄃ. 정조 시기에 탕평정치의 한 축을 이루었다.\nᄅ. 이이와 성혼의 문인을 중심으로 형성되었다.",
                          num1Text: "ㄱ,ㄴ",
                          num2Text: "ㄱ,ㄷ",
                          num3Text: "ㄴ,ㄹ",
                          num4Text: "ㄷ,ㄹ",
                          answer: 2),
            QuestionModel(num: 15,
                          questionText: "(나) 시기에 일어난 사실로 옳은 것은?",
                          reference: "(가) 삼포왜란이 발발하였다.\n-> (나)\n->(다) 임진왜란이 발발하였다.",
                          num1Text: "을사사화가 일어났다.",
                          num2Text: "'경국대전'이 반포되었다.",
                          num3Text: "'향약집성방'이 편찬되었다.",
                          num4Text: "금속활자인 갑인자가 주조되었다.",
                          answer: 1),
            QuestionModel(num: 16,
                          questionText: "다음 법령이 시행된 시기에 있었던 사실로 옳은 것은?",
                          reference: "제1조 회사의 설립은 조선 총독의 허가를 받아야 한다.\n\n제5조 회사가 본령이나 본령에 따라 나오는 명령과 허가 조건을 위반하거나 공공질서와 선량한 풍속에 반하는 행위를 할 때 조선 총독은 사업의 정지, 지점의 폐쇄, 또는 회사의 해산을 명할 수 있다.",
                          num1Text: "산미 증식 계획이 폐지되었다.",
                          num2Text: "'국가 총동원법'이 제정되었다.",
                          num3Text: "원료 확보를 위한 남면북양 정책이 추진되었다.",
                          num4Text: "보통학교 수업 연한을 4년으로 정한 '조선교육령'이 공포되었다.",
                          answer: 4),
            QuestionModel(num: 17,
                          questionText: "다음과 같은 결의문에 근거하여 시행된 조치로 옳은 것은?",
                          reference: "소총회는 ...(중략)... 한국 인민의 대표가 국회를 구성하여 중앙정부를 수립할 수 있도록 선거를 시행함이 긴요하다고 여기며, 총회의 의결에 따라 국제연합 한국 임시위원단이 접근할 수 있는 지역에서 결의문 제2호에 기술된 계획을 시행함이 동 위원단에 부과된 임무임을 결의한다.",
                          num1Text: "미 군정청이 설치되었다.",
                          num2Text: "5ᆞ10 총선거가 실시되었다.",
                          num3Text: "좌우 합작 위원회가 구성되었다.",
                          num4Text: "미ᆞ소 공동 위원회가 개최되었다.",
                          answer: 2),
            QuestionModel(num: 18,
                          questionText: "(가), (나) 조약 사이의 시기에 있었던 사실로 옳은 것은?",
                          reference: "(가) 제10관 일본국 인민이 조선국 지정의 각 항구에 머무는 동안에 죄를 범한 것이 조선국 인민에 관계되는 사건일 때에는 일본국 관원이 재판한다.\n\n(나) 제4관 중국 상인이 조선의 양화진 및 한성에 영업소를 개설할 경우를 제외하고，각종 화물을 내륙으로 운반하여 상점을 차리고 파는 것을 허가하지 않는다. 단, 내륙행상이 필요한 경우 지방관의 허가서를 받아야 한다.",
                          num1Text: "개항장에서는 일본 화폐가 통용되었다.",
                          num2Text: "러시아가 압록강 유역의 산림 채벌권을 획득하였다.",
                          num3Text: "황국 중앙 총상회가 조직되어 상권 수호 운동을 전개하였다.",
                          num4Text: "함경도의 방곡령에 불복하여 일본 상인이 손해 배상을 요구하였다.",
                          answer: 1),
            QuestionModel(num: 19,
                          questionText: "밑줄 친 ‘14개 조목’에 해당하는 것만을 모두 고르면?",
                          reference: "이제부터는 다른 나라를 의지하지 않으며 융성하도록 나라의 발걸음을 넓히고 백성의 복리를 증진하여 자주독립의 터전을 공고하게 할 것입니다. ...(중략) ... 이에 저 소자는 "+"14개 조목".underLined+"의 홍범(洪範)을 하늘에 계신 우리 조종의 신령 앞에 맹세하노니, 우러러 조종이 남긴 업적을 잘 이어서 감히 어기지 않을 것입니다.",
                          reference2: "ᄀ. 탁지아문에서 조세 부과\nᄂ. 왕실과 국정 사무의 분리\nᄃ. 지계 발급을 위한 지계아문 설치\nᄅ. 대한 천일 은행 등 금융기관 설립",
                          num1Text: "ᄀ,ㄴ",
                          num2Text: "ㄱ,ㄹ",
                          num3Text: "ㄴ,ㄷ",
                          num4Text: "ㄷ,ㄹ",
                          answer: 1),
            QuestionModel(num: 20,
                          questionText: "(가) 시기에 볼 수 있었던 모습으로 옳지 않은 것은?",
                          reference: "민주사변 발생 - [ (가) ] - 태평양전쟁 발발",
                          num1Text: "을사늑약 체결",
                          num2Text: "정미 의병 발생",
                          num3Text: "오페르트 도굴 미수 사건",
                          num4Text: "조.미 수호 통상 조약 체결",
                          answer: 3)
        ]
        let exam = ExamModel(id: 202313, year: 2023, examTypeID: "국가직", subjectID: "한국사", questions: questions)
        exams2023.append(exam)
    }
    
    
    func saveExam202321() {
        let questions =
        [
            QuestionModel(num: 1,
                          questionText: "ᄀ~ᄅ의 말하기 방식을 설명한 내용으로 가장 적절한 것은?",
                          reference: "김 주무관: AI에 대한 국민 이해도를 높이기 위해 설명회를 개최할 필요가 있다고 생각해요.\n\n최 주무관: "+"ᄀ저도 요즘 그 필요성을 절감하고 있어요.".underLined + "\n\n김 주무관: "+"ᄂ 그런데 어떻게 준비해야 효과적으로 전달할 수 있을지 고민이에요.".underLined+"\n\n최 주무관: 설명회에 참여할 청중 분석이 먼저 되어야겠지요.\n\n김주무관: 청중이 주로 어떤 분야에 관심이 있는지 알면 준비할 때 유용하겠네요.\n\n최 주무관: "+"ᄃ그럼 청중의 관심 분야를 파악하려면 청중의 특성 중에서 어떤 것들을 조사하면 좋을까요?".underLined+"\n\n김 주무관: "+"ᄅ 나이, 성별, 직업 등을 조사할까요?".underLined,
                          num1Text: "ᄀ: 상대의 의견에 대해 공감을 표현하고 있다.",
                          num2Text: "ᄂ: 정중한 표현을 사용하여 직접 질문하고 있다.",
                          num3Text: "ᄃ: 자신의 반대 의사를 우회적으로 드러내고 있다.",
                          num4Text: "ᄅ: 의문문을 통해 상대의 의견을 반박하고 있다.",
                          answer: 1),
            QuestionModel(num: 2,
                          questionText: "(가)~(다)를 맥락에 따라 가장 자연스럽게 배열한 것은?",
                          reference: " 독서는 아이들의 전반적인 뇌 발달에 큰 영향을 미친다. (가) 그에 따르면 뇌의 전두엽은 상상력을 관장하는데, 책을 읽으면 상상력이 자극되어 전두엽을 많이 사용하게 된다.\n\n(나) A교수는 책을 읽을 때와 읽지 않을 때의 뇌 변화를 연구해서 세계적인 명성을 얻었다.\n\n(다) 이처럼 책을 많이 읽으면 전두엽이 훈련되어 전반적인 뇌 발달의 가능성이 높아지는데, 그 결과는 교육 현장에서 실증된 바 있다.\n\n독서를 많이 한 아이는 학교에서 더 좋은 성적을 낼 뿐 아니라 언어 능력도 발달한다는 사실이 밝혀진 것이다.",
                          num1Text: "(나)-(가)-(다)",
                          num2Text: "(나)-(다)-(가)",
                          num3Text: "(다)-(가)-(나)",
                          num4Text: "(다)-(나)-(가)",
                          answer: 1),
            QuestionModel(num: 3,
                          questionText: " ᄀ~ᄅ을 설명한 내용으로 적절하지 않은 것은?",
                          reference: "○ "+"ᄀ지원".underLined+"은 자는 동생을 깨웠다.\n○ 유선은 도자기를 "+"ᄂ만들었다.".underLined+"\n○ 물이 "+"ᄃ얼음".underLined+"이 되었다.\n○ "+"ᄅ어머나".underLined+", 현지가 언제 이렇게 컸지?",
                          num1Text: "ᄀ: 동작의 주체를 나타내는 주어이다.",
                          num2Text: "ᄂ: 주어와 목적어를 요구하는 서술어이다.",
                          num3Text: "ᄃ: 서술어를 꾸며주는 부사어이다.",
                          num4Text: "ᄅ: 문장의 다른 성분과 직접적으로 관련을 맺지 않는 독립어이다.",
                          answer: 3),
            QuestionModel(num: 4,
                          questionText: "ᄀ~ᄅ과 바꿔 쓸 수 있는 유사한 표현으로 적절하지 않은 것은?",
                          reference: "○ 서구의 문화를 "+"ᄀ맹종하는".underLined+" 이들이 많다.\n○ 안일한 생활에서 "+"ᄂ 탈피하여".underLined+" 어려운 일에 도전하고 싶다.\n○ 회사의 생산성을 "+"ᄃ제고하기".underLined+" 위해 노력하자.\n○ 연못 위를 "+"ᄅ부유하는".underLined+" 연잎을 바라보며 여유를 즐겼다.",
                          num1Text: "ᄀ: 무분별하게 따르는",
                          num2Text: "ᄂ: 벗어나",
                          num3Text: "ᄃ: 끌어올리기",
                          num4Text: "ᄅ: 헤엄치는",
                          answer: 4),
            QuestionModel(num: 5,
                          questionText: "(가)와 (나)를 이해한 내용으로 적절하지 않은 것은?",
                          reference: "(가)\n청산(靑山)은 내 이오 녹수(綠水) 님의 정(情)이\n녹수(綠水)ᅵ 흘너간들 청산(靑山)이야 변(變)손가\n녹수(綠水)도 청산(靑山)을 못 니저 우러 녜여 가고.\n\n(나)\n청산(靑山) 엇뎨야 만고(萬古)애 프르르며\n유수(流水) 엇뎨야 주야(晝夜)애 긋디 아니고\n우리도 그치디 마라 만고상청(萬古常靑)호리라.",
                          num1Text: "(가)는 ‘청산’과 ‘녹수’의 대조를 활용하여 화자가 처한 상황을 제시하고 있다.",
                          num2Text: "(나)는 시각적 심상과 청각적 심상을 활용하여 주제를 강조하고 있다.",
                          num3Text: "(가)와 (나) 모두 대구를 활용하여 시상을 전개하고 있다.",
                          num4Text: "(가)와 (나) 모두 설의적 표현을 활용하여 화자의 정서를 드러내고 있다.",
                          answer: 2),
            QuestionModel(num: 6,
                          questionText: "다음 글의 중심내용으로 가장 적절한 것은?",
                          reference: " 교환가치는 거래를 통해 발생하는 가치이며, 사용가치는 어떤 상품을 사용할 때 느끼는 가치이다. 전자가 시장에서 결정된다는 점에서 객관적이라면, 후자는 개인에 따라 다르다는 점에서 주관적이다. 상품에는 사용가치와 교환가치가 섞여 있는데, 교환가치가 아무리 높아도 ‘나’에게 사용가치가 없다면 해당 상품을 구매하지 않을 것이다.\n 하지만 이 같은 상식이 통하지 않는 경우를 종종 볼 수 있다. 예를 들어 보자. 인터넷 커뮤니티에서 백만 원짜리 공연 티켓을 판매하는데, 어떤 사람이 “이 공연의 가치는 돈으로 환산할 수 없어요.” 등의 댓글들을 보고서 애초에 관심도 없던 이 공연의 티켓을 샀다. 그에게 그 공연의 사용가치는 처음에는 없었으나 많은 댓글로 인해 사용가치가 있을 것으로 잘못 판단한 것이다. 안타깝게도, 그는 그 공연에서 조금도 만족하지 못했다.\n 이 사례에서 볼 때 건강한 소비를 위해서는 구매하려는 상품의 사용가치가 어떤 과정을 거쳐 결정된 것인지 곰곰이 생각해봐야 한다. ‘나’에게 얼마나 필요한가에 대한 고민 없이 다른 사람들의 말에 휩쓸려 어떤 상품의 사용가치가 결정될 때, 그 상품은 ‘나’에게 쓸모없는 골칫덩이가 될 수 있다.",
                          num1Text: "사용가치보다 교환가치가 큰 상품을 구매해야 한다.",
                          num2Text: "상품을 구매할 때 사용가치와 교환가치를 두루 고려해야 한다.",
                          num3Text: "상품에 대한 다른 사람들의 평가를 반영해서 상품을 구매해야 한다.",
                          num4Text: "상품을 구매할 때 사용가치가 자신의 필요에 의해 결정된 것인지 신중하게 따져야 한다.",
                          answer: 4),
            QuestionModel(num: 7,
                          questionText: "ᄀ~ ᄅ중 어색한 곳을 찾아 수정하는 방안으로 가장 적절한 것은?",
                          reference: "조선 후기에 서학으로 불린 천주학은 ‘학(學)’이라는 말에서도 짐작할 수 있듯이 "+"ᄀ종교적인 관점에서보다 학문적인 관점에서".underLined+" 받아들여졌다. 당시의 유학자 중 서학 수용에 적극적인 이들까지도 서학을 무조건 따르자고 "+"ᄂ주장하지는 않았는데,".underLined+" 서학은 신봉의 대상이 아니라 분석의 대상이었기 때문이다. 그들은 조선 사회를 바로잡고 발전시키기 위해 새로운 학문과 지식이 필요하다고 생각했지만, 외부에서 유입된 사유 체계에는 양명학이나 고증학 등도 있어서 서학이 "+"ᄃ유일한 대안은 아니었다.".underLined+" 그들은 서학을 검토하며 어떤 부분은 수용했지만, 반대로 어떤 부분은 "+"ᄅ지향했다.".underLined,
                          num1Text: "ᄀ: ‘학문적인 관점에서보다 종교적인 관점에서’로 수정한다.",
                          num2Text: "ᄂ: ‘주장하였는데’로 수정한다.",
                          num3Text: "ᄃ: ‘유일한 대안이었다’로 수정한다.",
                          num4Text: "ᄅ: ‘지양했다’로 수정한다.",
                          answer: 4),
            QuestionModel(num: 8,
                          questionText: "다음 글의 맥락을 고려할 때 빈칸에 들어갈 말로 가장 적절한 것은?",
                          reference: " 능숙한 필자와 미숙한 필자는 글쓰기 과정 중 ‘계획하기’에서 뚜렷한차이를보인다. 전자는이과정에오랜시간공을들이는 반면, 후자는 그렇지 않다. 글쓰기에서 계획하기는 글쓰기의 목적 수립, 주제 선정, 예상 독자 분석 등을 포함한다. 이 중 예상 독자 분석이 중요한 이유는 [   ] 때문이다. 글을 쓸 때 독자의 수준에 비해 너무 어려운 개념과 전문용어를 사용한다면 독자가 글을 이해하기 어렵게 된다. 글쓰기는 필자가 글을 통해 자신의 메시지를 독자에게 전달하는 행위라는 점을 고려하면 계획하기 단계에서 반드시 예상 독자를 분석해야 한다.",
                          num1Text: "계획하기 과정이 글쓰기 전체 과정의 첫 단계이기",
                          num2Text: "글에 어려운 개념이나 전문용어를 어느 정도 포함해야 하기",
                          num3Text: "필자의 메시지를 독자에게 효과적으로 전달하는 데 도움이 되기",
                          num4Text: "독자의 배경지식 수준을 고려해야 글의 목적과 주제가 결정되기",
                          answer: 3),
            QuestionModel(num: 9,
                          questionText: "다음 시를 이해한 내용으로 적절하지 않은 것은?",
                          reference: "사랑을 잃고 나는 쓰네\n\n잘 있거라, 짧았던 밤들아\n창밖을 떠돌던 겨울 안개들아\n아무것도 모르던 촛불들아, 잘 있거라\n공포를 기다리던 흰 종이들아\n망설임을 대신하던 눈물들아\n잘있거라, 더 이상 내 것이 아닌 열망들아\n\n장님처럼 나 이제 더듬거리며 문을 잠그네\n가엾은 내 사랑 빈집에 갇혔네\n\n- 기형도, 빈집 -",
                          num1Text: "대상들을 호명하며 안타까운 심정을 표현하고 있다.",
                          num2Text: "‘빈집’은 상실감으로 공허해진 내면을 상징하고 있다.",
                          num3Text: "영탄형 어조를 활용해 이별에 따른 정서를 부각하고 있다.",
                          num4Text: "글 쓰는 행위를 통해 잃어버린 사랑의회복을 열망하고 있다.",
                          answer: 4),
            QuestionModel(num: 10,
                          questionText: "다음 글을 이해한 내용으로 가장 적절한 것은?",
                          reference: " 반드시 갚는 조건임을 강조하면서 그는 마치 성경책 위에다 오른손을 얹고 말하듯이 엄숙한 표정을 했다. 하마터면 나는 잊을 뻔했다. 그가 적시에 일깨워 주었기 망정이지 안 그랬더라면 빌려주는 어려움에만 골똘한 나머지 빌려줬다 나중에 돌려받는 어려움이 더 클 거라는 사실은 생각도 못 할 뻔했다. 그렇다. 끼니조차 감당 못 하는 주제에 막벌이 아니면 어쩌다 간간이 얻어걸리는 출판사 싸구려 번역 일 가지고 어느 해가※에 빚을 갚을 것인가. 책임이 따르는 동정은 피하는 게 상책이었다. 그리고 기왕 피할 바엔 저쪽에서 감히 두말을 못 하도록 야멸치게 굴 필요가 있었다.\n “병원 이름이 뭐죠?” “원 산부인괍니다.” “지금 내 형편에 현금은 어렵군요. 원장한테 바로 전화 걸어서 내가 보증을 서마고 약속할 테니까 권 선생도 다시 한번 매달려 보세요. 의사도 사람인데 설마 사람을 생으로 죽게야 하겠습니까. 달리 변통할 구멍이 없으시다면 그렇게 해 보세요.”\n 내 대답이 지나치게 더디 나올 때 이미 눈치를 챈 모양이었다. 도전적이던 기색이 슬그머니 죽으면서 그의 착하디착한 눈에 다시 수줍음이 돌아왔다. 그는 고개를 좌우로 흔들어 보였다.\n “원장이 어리석은 사람이길 바라고 거기다 희망을 걸기엔 너무 늦었습니다. 그 사람은 나한테서 수술 비용을 받아 내기가 수월치 않다는 걸 입원시키는 그 순간에 벌써 알아차렸어요.”\n\n-윤흥길, 아홉 켤레의 구두로 남은 사내에서 -",
                          num1Text: "서술자가 등장인물의 심리를 전지적 위치에서 전달하고 있다.",
                          num2Text: "서술자가 등장인물이 되어 다른 등장인물의 행동을 진술하고 있다.",
                          num3Text: "서술자가 주인공으로서 유년 시절을 회상하며 갈등 원인을 해명하고 있다.",
                          num4Text: "서술자가 주관을 배제하고 외부 관찰자의 시선으로 사건을 이야기하고 있다.",
                          answer: 2),
            QuestionModel(num: 11,
                          questionText: "다음 대화를 분석한 내용으로 적절하지 않은 것은?",
                          reference: "은지: 최근 국민 건강 문제와 관련해 ‘설탕세’ 부과 여부가 논란인데, 나는 설탕세를 부과해야 한다고 생각해. 그러면 당 함유 식품의 소비가 감소하게 되고, 비만이나 당뇨병 등의 질병이 예방되니까 국민 건강 증진에 도움이 되기 때문이야.\n\n운용: 설탕세를 부과하면 당 소비가 감소한다고 믿을 만한 근거가 있니?\n\n은지: 세계보건기구 보고서를 보면 당이 포함된 음료에 설탕세를 부과하면 이에 비례해 소비가 감소한다고 나와 있어.\n\n재윤: 그건 나도 알아. 그런데 설탕세 부과가 질병을 예방한다는 것은 타당하지 않아. 여러 연구 결과를 보면 당 섭취와 질병 발생은 유의미한 상관관계가 없어.",
                          num1Text: "은지는 첫 번째 발언에서 화제를 제시하고 있다.",
                          num2Text: "운용은 은지의 주장에 반대하고 있다.",
                          num3Text: "은지는 두 번째 발언에서 자신의 주장에 대한 근거를 제시하고 있다.",
                          num4Text: "재윤은 은지가 제시한 주장의 근거를 부정하고 있다.",
                          answer: 2),
            QuestionModel(num: 12,
                          questionText: "ᄀ∼ᄅ에 들어갈 단어로 적절하지 않은 것은?",
                          reference: "○우리회사는 올해 최고 수익을 창출해서 전성기를 ᄀ하고 있다.\n○그는 오래 살아온 자기명의 의 집을 ᄂ 하려했는데 사려는 사람이 없다.\n○ 그들 사이에 ᄃ 이 심해서 중재자가 필요하다.\n○ 제가 부족하니 앞으로 많은 ᄅ 을 부탁드립니다.",
                          num1Text: "ᄀ: 구가(謳歌)",
                          num2Text: "ᄂ: 매수(買受)",
                          num3Text: "ᄃ: 알력(軋轢)",
                          num4Text: "ᄅ: 편달(鞭撻)",
                          answer: 2),
            QuestionModel(num: 13,
                          questionText: "밑줄 친 단어의 쓰임이 올바르지 않은 것은?",
                          num1Text: "이 일은 정말 힘에 "+"부치는".underLined+" 일이다.",
                          num2Text: "그와 나는 전부터 "+"알음".underLined+"이 있던 사이였다.",
                          num3Text: "대문 앞에서 있는데 대문이 저절로 "+"닫혔다.".underLined,
                          num4Text: "경기장에는 "+"걷잡아서".underLined+" 천 명이 넘게 온 듯하다.",
                          answer: 4),
            QuestionModel(num: 14,
                          questionText: "ᄀ~ᄃ의 한자 표기로 올바른 것은?",
                          reference: "○ 복지부 "+"ᄀ 장관".underLined+"은 의료시설이 대도시에 편중된 문제에 대해 대책을 마련하라고 지시하였다.\n○ 박 주무관은 사유지의 국유지 편입으로 발생한 주민들의 피해를 "+"ᄂ보상".underLined+"하는 업무를 맡고 있다.\n○ 김 주무관은 이 팀장에게 부서 운영비와 관련된 "+"ᄃ결재".underLined+"를 올렸다.",
                          num1Text: "長官 - 補償 - 決裁",
                          num2Text: "將官 - 報償 - 決裁",
                          num3Text: "長官 - 報償 - 決濟",
                          num4Text: "將官 - 補償 - 決濟",
                          answer: 1),
            QuestionModel(num: 15,
                          questionText: "다음 글에서 추론한 내용으로 적절하지 않은 것은?",
                          reference: " 우리는 개별적으로 고립된 채 살아가는 존재일 수 없다. 사회 속에서 여럿이 모여 ‘복수(複數)’의 상태로 살아갈 수밖에 없는 존재라는 것이다. 복수의 상태로 살아가는 우리는 종(種)적인 차원에서 보면 보편적이고 동등한 존재이다. 그러나 우리는 각각 유일무이성을 지닌 ‘단수(單數)’이기도 하다. 즉 모든 인간은 개인으로서 고유한 인격체라는 특수성을 지닌다. 사회 속에서 우리는 보편적 복수성과 특수한 단수성을 겸비한 채 살아가고 있는 셈이다. 바로 이러한 이유로 우리는 다원적 존재이다. 이러한 존재들로 구성된 다원적 사회에서는 어떠한 획일화도 시도되어서는 안 된다. 우리가 이 같은 사회에서 살아가기 위해서는 타인을 포용하는 공존의 태도가 필요하다. 공동체 정화 등을 목적으로 개별적 유일무이성을 제거하는 것은 우리가 살아가는 사회의 다원성을 파괴하는 일이다.",
                          num1Text: "우리는 고립된 상태에서 ‘단수’로 살아가는 존재가 아니다.",
                          num2Text: "우리는 다원성을 지닌 존재로서 포용적으로 공존해야 한다.",
                          num3Text: "개인의 유일무이성을 보존하려는 제도는 개인의 보편적 복수성을 침해한다.",
                          num4Text: "개인의 특수한 단수성을 제거하려는 시도는 사회의 다원성을 파괴하는 결과로 이어질 수 있다.",
                          answer: 3),
            QuestionModel(num: 16,
                          questionText: "다음 글을 이해한 내용으로 적절하지 않은 것은?",
                          reference: " 매우 치라 소리 맞춰, 넓은 골에 벼락치듯 후리쳐 딱 붙이니, 춘향이 정신이 아득하여, “애고 이것이 웬일인가?” 일자(一字)로 운을 달아 우는 말이, “일편단심 춘향이 일정지심 먹은 마음 일부종사 하쟀더니 일신난처 이 몸인들 일각인들 변하리까? 일월 같은 맑은 절개 이리 힘들게 말으시오.”\n “매우 치라.” “꽤 때리오.” 또 하나 딱 부치니, “애고.” 이자(二字)로 우는구나. “이부불경 이내 마음 이군불사와 무엇이 다르리까? 이 몸이 죽더라도 이도령은 못 잊겠소. 이 몸이 이러한들 이 소식을 누가 전할까? 이왕 이리 되었으니 이 자리에서 죽여 주오.”\n “매우 치라.” “꽤 때리오.” 또 하나 딱 부치니, “애고.” 삼자(三字)로 우는구나. “삼청동 도련님과 삼생연분 맺었는데 삼강을 버리라 하소? 삼척동자 아는 일을 이내 몸이 조각조각 찢겨져도 삼종지도 중한 법을 삼생에 버리리까? 삼월삼일 제비같이 훨훨 날아 삼십삼천 올라가서 삼태성께 하소연할까? 애고애고 서러운지고.”\n\n- 춘향전에서 -",
                          num1Text: "동일한 글자를 반복함으로써 리듬감을 조성하고 있다.",
                          num2Text: "숫자를 활용하여 주인공이 처한 상황을 제시하고 있다.",
                          num3Text: "등장인물 간의 대화를 통해 주인공의 내적 갈등이 해결되고 있다.",
                          num4Text: "유교적 가치를 담고 있는 말을 활용하여 주인공의 의지를 드러내고 있다.",
                          answer: 3),
            QuestionModel(num: 17,
                          questionText: "다음 글을 이해한 내용으로 적절하지 않은 것은?",
                          reference: " 고소설의 유통 방식은 ‘구연에 의한 유통’과 ‘문헌에 의한 유통’으로 나눌 수 있다. 구연에 의한 유통은 구연자가 소설을 사람들에게 읽어 주는 방식으로, 글을 모르는 사람들과 글을 읽을 수 있지만 남이 읽어 주는 것을 선호하는 이들을 대상으로 이루어졌다. 구연자는 ‘전기수’로 불렸으며, 소설 구연을 통해 돈을 벌던 전문적 직업인이었다. 하지만 이 방식은 문헌에 의한 유통에 비해 시간과 공간의 제약이 많아서 유통 범위를 넓히는 데 뚜렷한 한계가 있었다.\n 문헌에 의한 유통은 차람, 구매, 상업적 대여로 나눌 수 있다. 차람은 소설을 소유하고 있는 사람에게 직접 빌려서 보는 것으로, 알고 지내던 개인들 사이에서 이루어졌다. 구매는 서적 중개인에게 돈을 지불하고 책을 사는 것인데, 책값이 상당히 비쌌기 때문에 소설을 구매할 수 있는 사람은 그리 많지 않았다. 상업적 대여는 세책가에 돈을 지불하고 일정 기간 동안 소설을 빌려 보는 것이다. 세책가에서는 소설을 구매하는 것보다 훨씬 적은 비용으로 빌려 볼 수 있었기 때문에 경제적으로 넉넉하지 않은 사람도 소설을 쉽게 접할 수 있었다. 이로 인해 조선 후기 사회에서 세책가가 성행하게 되었다.",
                          num1Text: "전기수는 글을 모르는 사람들에게 소설을 구연하였다.",
                          num2Text: "차람은 알고 지내던 사람에게 대가를 지불하고 책을 빌려 보는 방식이다.",
                          num3Text: "문헌에 의한 유통은 구연에 의한 유통에 비해 시간과 공간의 제약이 적었다.",
                          num4Text: "조선 후기에 세책가가 성행한 원인은 소설을 구매하는 비용보다 세책가에서 빌리는 비용이 적다는 데 있다.",
                          answer: 2),
            QuestionModel(num: 18,
                          questionText: "다음 글을 이해한 내용으로 가장 적절한 것은?",
                          reference: " 삼국사기는 본기 28권, 지 9권, 표 3권, 열전 10권의 체제로 되어 있다. 이 중 열전은 전체 분량의 5분의 1을 차지하며, 수록된 인물은 86명으로, 신라인이 가장 많고, 백제인이 가장 적다. 수록 인물의 배치에는 원칙이 있는데, 앞부분에는 명장, 명신, 학자 등을 수록했고, 다음으로 관직에 있지는 않았으나 기릴 만한 사람을 실었다.\n 반신(叛臣)의 경우 열전의 끝부분에 배치되어 있다. 이들을 수록한 까닭은 왕을 죽인 부정적 행적을 드러내어 반면교사로 삼는 데에 있었으나, 그 목적에 부합하지 않는 내용이 있어 흥미롭다. 가령 고구려의 연개소문은 반신이지만, 당나라에 당당히 대적한 민족적 영웅의 모습도 포함되어 있다. 흔히 삼국사기에 대해, 신라 정통론에 기반해 있으며, 유교적 사관에 따라 당시의 지배 질서를 공고히 하고자 했다고 평가한다. 하지만 연개소문의 사례에서 볼 수 있듯 삼국사기는 기존 평가와 달리 다면적이고 중층적인 역사 텍스트라고 할 수 있다.",
                          num1Text: "[삼국사기] 열전에 고구려인과 백제인도 수록되었다는 점은 이 책이 신라 정통론을 계승하지 않았다는 것을 보여준다.",
                          num2Text: "[삼국사기] 열전에 수록된 반신 중에는 이 책에 대한 기존 평가를 다르게 할 수 있는 사례가 있다. ﻿",
                          num3Text: "[삼국사기] 열전에는 기릴 만한 업적이 있더라도 관직에 오르지 못한 사람은 수록되지 않았다.",
                          num4Text: "[삼국사기]의 체제 중에서 열전이 가장 많은 권수를 차지한다.",
                          answer: 2),
            QuestionModel(num: 19,
                          questionText: "다음 글에서 추론한 내용으로 적절하지 않은 것은?",
                          reference: " 프랑스에서 의무교육 제도를 실시하면서 정규학교에 입학하기 어려운 지적장애아, 학습부진아를 가려내고자 하였다. 이에 기초 학습 능력 평가를 목적으로, 1905년 최초의 IQ 검사가 이루어졌다. 이 검사를 통해 비로소 인간의 지능을 구체적으로 수치화하고 객관적으로 비교할 수 있게 되었다.\n 이후 오랫동안 IQ가 높으면 똑똑한 사람, 그렇지 않으면 머리가 좋지 않고 학습에도 부진한 사람으로 판단했다. 물론 IQ가 높은 아이는 그렇지 않은 아이에 비해 읽기나 계산 등 사고 기능과 관련된 과목에서 높은 성취도를 보이는 경우가 많다. 이는 IQ 검사가 기초 학습에 필요한 최소 능력인 언어 이해력, 어휘력, 수리력 등을 측정하기 때문이다. 학습의 기초 능력을 측정하는 IQ 검사에서 높은 점수를 받은 아이는 동일한 능력을 측정하는 학업 평가에서도 높은 점수를 받을 가능성이 크다. 하지만 문제는 IQ 검사가 인간의 지능 중 일부만을 측정한다는 점이다.",
                          num1Text: "최초의 IQ 검사는 학습 능력이 우수한 아이를 고르기 위해 시행되었다.",
                          num2Text: "IQ 검사가 만들어지기 전에는 인간의 지능을 수치로 비교할 수 없었다.",
                          num3Text: "IQ가 높은 아이라도 전체 지능은 높지 않을 수 있다.",
                          num4Text: "IQ가 높은 아이가 읽기 능력이 좋을 확률이 높다.",
                          answer: 1),
            QuestionModel(num: 20,
                          questionText: "다음 글에서 추론한 내용으로 적절하지 않은 것은?",
                          reference: " 한글은 소리를 나타내는 표음문자여서 한국어 문장을 읽는 데 학습해야 할 글자가 적지만, 한자는 음과 상관없이 일정한 뜻을 나타내는 표의문자여서 한문을 읽는 데 익혀야 할 글자 수가 훨씬 많다. 이러한 번거로움에도 한글과 달리 한자가 갖는 장점이 있다. 한글에서는 동음이의어, 즉 형태와 음이 같은데 뜻이 다른 단어가 많아 글자만으로 의미를 파악하지 못하는 경우가 많다. 하지만 한자는 그렇지 않다. 예컨대, 한글로 ‘사고’라고만 쓰면 ‘뜻밖에 발생한 사건’인지 ‘생각하고 궁리함’ 인지 구별할 수 없다. 한자로 전자는 ‘事故’, 후자는 ‘思考’로 표기한다. 그런데 한자는 문맥에 따라 같은 글자가 다른 뜻으로 쓰이지는 않지만 다른 문장성분으로 사용되기도 해 혼란을 야기한다. 가령 ‘愛人’은 문맥에 따라 ‘愛’가 ‘人’을 수식하는 관형어일 때도, ‘人’을 목적어로 삼는 서술어일 때도 있는 것이다.",
                          num1Text: "한문은 한국어 문장보다 문장성분이 복잡하다.",
                          num2Text: "‘淨水’가 문맥상 ‘깨끗하게 한 물’일 때 ‘淨’은 ‘水’를 수식한다.",
                          num3Text: "‘愛人’에서 ‘愛’의 문장성분이 바뀌더라도 ‘愛’는 동음이의어가 아니다.",
                          num4Text: "‘의사’만으로는 ‘병을 고치는 사람’인지 ‘의로운 지사’인지 구별할 수 없다.",
                          answer: 1)
            
        ]
        let exam = ExamModel(id: 202321, year: 2023, examTypeID: "지방직", subjectID: "국어", questions: questions)
        exams2023.append(exam)
    }
    
    func saveExam202322() {
        let questions = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운것을 고르시오.",
                      reference: "Further explanations on our project will be given in "+"subsequent".underLined+" presentations.",
                      num1Text: "required",
                      num2Text: "following",
                      num3Text: "advanced",
                      num4Text: "supplementary",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오.",
                      reference: "Folkways are customs that members of a group are expected to follow to show "+"courtesy".underLined+" to others. For example, saying “excuse me” when you sneeze is an American folkway.",
                      num1Text: "charity",
                      num2Text: "humility",
                      num3Text: "boldness",
                      num4Text: "politeness",
                      answer: 4),
        QuestionModel(num: 3,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오.",
                      reference: "These children have been "+"brought up".underLined+" on a diet of healthy food.",
                      num1Text: "raised",
                      num2Text: "advised",
                      num3Text: "observed",
                      num4Text: "controlled",
                      answer: 1),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "Slavery was not "+"done away with".underLined+" until the nineteenth century in the U.S.",
                      num1Text: "abolished",
                      num2Text: "consented",
                      num3Text: "criticized",
                      num4Text: "justified",
                      answer: 1),
        QuestionModel(num: 5,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "Voters demanded that there should be greater _________ in the election process so that they could see and understand it clearly.",
                      num1Text: "deception",
                      num2Text: "flexibility",
                      num3Text: "competition",
                      num4Text: "transparency",
                      answer: 4),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 부분 중 어법상 옳지 않은 것은?",
                      reference: "One reason for upsets in sports—(1)"+"in which".underLined+" the team (2)"+"predicted".underLined+" to win and supposedly superior to their opponents surprisingly loses the contest—is (3)"+"what".underLined+" the superior team may not have perceived their opponents as (4)"+"threatening".underLined+" to their continued success.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 3),
        QuestionModel(num: 7,
                      questionText: "밑줄 친 부분이 어법상 옳지 않은 것은?",
                      num1Text: "I "+"should have gone".underLined+" this morning, but I was feeling a bit ill.",
                      num2Text: "These days we do not save as much money "+"as we used to.".underLined,
                      num3Text: "The rescue squad was happy to discover "+"an alive man.".underLined,
                      num4Text: "The picture "+"was looked at".underLined+" carefully by the art critic.",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "우리말을 영어로 잘못 옮긴 것은?",
                      num1Text: "우리는 그의 연설에 감동하게 되었다.\n->We were made touching with his speech.",
                      num2Text: "비용은 차치하고 그 계획은 훌륭한 것이었다.\n->Apart from its cost, the plan was a good one.",
                      num3Text: "그들은 뜨거운 차를 마시는 동안에 일몰을 보았다.\n->They watched the sunset while drinking hot tea.",
                      num4Text: "과거 경력 덕분에 그는 그 프로젝트에 적합하였다.\n->His past experience made him suited for the project.",
                      answer: 1),
        QuestionModel(num: 9,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오.",
                      reference: "A: Pardon me, but could you give me a hand, please?\nB: ________________________________________________\nA: I’m trying to find the Personnel Department. I have an appointment at 10.\nB: It’s on the third floor.\nA: How can I get up there?\nB: Take the elevator around the corner.",
                      num1Text: "We have no idea how to handle this situation.",
                      num2Text: "Would you mind telling us who is in charge?",
                      num3Text: "Yes. I could use some help around here.",
                      num4Text: "Sure. Can I help you with anything?",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오.",
                      reference: "A: You were the last one who left the office, weren’t you?\nB: Yes. Is there any problem?\nA: I found the office lights and air conditioners on this morning.\nB: Really? Oh, no. Maybe I forgot to turn them off last night.\nA: Probably they were on all night.\nB: ________________________________________________",
                      num1Text: "Don’t worry. This machine is working fine.",
                      num2Text: "That’s right. Everyone likes to work with you.",
                      num3Text: "I’m sorry. I promise I’ll be more careful from now on.",
                      num4Text: "Too bad. You must be tired because you get off work too late.",
                      answer: 3),
        QuestionModel(num: 11,
                      questionText: "두 사람의 대화 중 자연스럽지 않은 것은?",
                      num1Text: "A: How would you like your hair done?\nB: I’m a little tired of my hair color. I’d like to dye it.",
                      num2Text: "A: What can we do to slow down global warming?\nB: First of all, we can use more public transportation.",
                      num3Text: "A: Anna, is that you? Long time no see! How long has it been?\nB: It took me about an hour and a half by car.",
                      num4Text: "A: I’m worried about Paul. He looks unhappy. What should I do?\nB: If I were you, I’d wait until he talks about his troubles.",
                      answer: 3),
        QuestionModel(num: 12,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "Well-known author Daniel Goleman has dedicated his life to the science of human relationships. In his book Social Intelligence he discusses results from neuro-sociology to explain how sociable our brains are. According to Goleman, we are drawn to other people’s brains whenever we engage with another person. The human need for meaningful connectivity with others, in order to deepen our relationships, is what we all crave, and yet there are countless articles and studies suggesting that we are lonelier than we ever have been and loneliness is now a world health epidemic. Specifically, in Australia, according to a national Lifeline survey, more than 80 % of those surveyed believe our society is becoming a lonelier place. Yet, our brains crave human interaction.",
                      num1Text: "Lonely People",
                      num2Text: "Sociable Brains",
                      num3Text: "Need for Mental Health Survey",
                      num4Text: "Dangers of Human Connectivity",
                      answer: 2),
        QuestionModel(num: 13,
                      questionText: "다음 글의 주제로 가장 적절한 것은?",
                      reference: "Certainly some people are born with advantages (e.g., physical size for jockeys, height for basketball players, an “ear” for music for musicians). Yet only dedication to mindful, deliberate practice over many years can turn those advantages into talents and those talents into successes. Through the same kind of dedicated practice, people who are not born with such advantages can develop talents that nature put a little farther from their reach. For example, even though you may feel that you weren’t born with a talent for math, you can significantly increase your mathematical abilities through mindful, deliberate practice. Or, if you consider yourself “naturally” shy, putting in the time and effort to develop your social skills can enable you to interact with people at social occasions with energy, grace, and ease.",
                      num1Text: "advantages some people have over others",
                      num2Text: "importance of constant efforts to cultivate talents",
                      num3Text: "difficulties shy people have in social interactions",
                      num4Text: "need to understand one’s own strengths and weaknesses",
                      answer: 2),
        QuestionModel(num: 14,
                      questionText: "다음 글의 요지로 가장 적절한 것은?",
                      reference: "Dr. Roossinck and her colleagues found by chance that a virus increased resistance to drought on a plant that is widely used in botanical experiments. Their further experiments with a related virus showed that was true of 15 other plant species, too. Dr. Roossinck is now doing experiments to study another type of virus that increases heat tolerance in a range of plants. She hopes to extend her research to have a deeper understanding of the advantages that different sorts of viruses give to their hosts. That would help to support a view which is held by an increasing number of biologists, that many creatures rely on symbiosis, rather than being self-sufficient.",
                      num1Text: "Viruses demonstrate self-sufficiency of biological beings.",
                      num2Text: "Biologists should do everything to keep plants virus-free.",
                      num3Text: "The principle of symbiosis cannot be applied to infected plants.",
                      num4Text: "Viruses sometimes do their hosts good, rather than harming them.",
                      answer: 4),
        QuestionModel(num: 15,
                      questionText: "다음 글의 내용과 일치하지 않는 것은?",
                      reference: "The traditional way of making maple syrup is interesting. A sugar maple tree produces a watery sap each spring, when there is still lots of snow on the ground. To take the sap out of the sugar maple tree, a farmer makes a slit in the bark with a special knife, and puts a “tap” on the tree. Then the farmer hangs a bucket from the tap, and the sap drips into it. That sap is collected and boiled until a sweet syrup remains—forty gallons of sugar maple tree “water” make one gallon of syrup. That’s a lot of buckets, a lot of steam, and a lot of work. Even so, most of maple syrup producers are family farmers who collect the buckets by hand and boil the sap into syrup themselves.",
                      num1Text: "사탕단풍나무에서는 매년 봄에 수액이 생긴다.",
                      num2Text: "사탕단풍나무의 수액을 얻기 위해 나무껍질에 틈새를 만든다.",
                      num3Text: "단풍나무시럽 1갤론을 만들려면 수액 40갤론이 필요하다.",
                      num4Text: "단풍나무시럽을 만들기 위해 기계로 수액 통을 수거한다.",
                      answer: 4),
        QuestionModel(num: 16,
                      questionText: "다음 글의 흐름상 어색한 문장은?",
                      reference: "I once took a course in short-story writing and during that course a renowned editor of a leading magazine talked to our class. (1)"+"He said he could pick up any one of the dozens of stories that came to his desk every day and after reading a few paragraphs he could feel whether or not the author liked people.".underLined+" (2)"+"“If the author doesn’t like people,” he said, “people won’t like his or her stories.”".underLined+" (3)"+"The editor kept stressing the importance of being interested in people during his talk on fiction writing.".underLined+" (4)"+"Thurston, a great magician, said that every time he went on stage he said to himself, “I am grateful because I’m successful.”".underLined+" At the end of the talk, he concluded, “Let me tell you again. You have to be interested in people if you want to be a successful writer of stories.”",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 4),
        QuestionModel(num: 17,
                      questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "Just a few years ago, every conversation about artificial intelligence (AI) seemed to end with an apocalyptic prediction.",
                      reference2: "(A) More recently, however, things have begun to change. AI has gone from being a scary black box to something people can use for a variety of use cases.\n\n(B) In 2014, an expert in the field said that, with AI, we are summoning the demon, while a Nobel Prize winning physicist said that AI could spell the end of the human race.\n\n(C) This shift is because these technologies are finally being explored at scale in the industry, particularly for market opportunities.",
                      num1Text: "(A) -(B) -(C)",
                      num2Text: "(B) -(A) -(C)",
                      num3Text: "(B) -(C) -(A)",
                      num4Text: "(C) -(A) -(B)",
                      answer: 2),
        QuestionModel(num: 18,
                      questionText: "주어진 문장이 들어갈 위치로 가장 적절한 것은?",
                      reference: "Yet, requests for such self-assessments are pervasive throughout one’s career.",
                      reference2: "The fiscal quarter just ended. Your boss comes by to ask you how well you performed in terms of sales this quarter. How do you describe your performance? As excellent? Good? Terrible? ( 1 ) Unlike when someone asks you about an objective performance metric (e.g., how many dollars in sales you brought in this quarter), how to subjectively describe your performance is often unclear. There is no right answer. ( 2 ) You are asked to subjectively describe your own performance in school applications, in job applications, in interviews, in performance reviews, in meetings—the list goes on. ( 3 ) How you describe your performance is what we call your level of self-promotion. ( 4 ) Since self-promotion is a pervasive part of work, people who do more self-promotion may have better chances of being hired, being promoted, and getting a raise or a bonus.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 2),
        QuestionModel(num: 19,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오.",
                      reference: "We live in the age of anxiety. Because being anxious can be an uncomfortable and scary experience, we resort to conscious or unconscious strategies that help reduce anxiety in the moment—watching a movie or TV show, eating, video-game playing, and overworking. In addition, smartphones also provide a distraction any time of the day or night. Psychological research has shown that distractions serve as a common anxiety avoidance strategy. _________, however, these avoidance strategies make anxiety worse in the long run. Being anxious is like getting into quicksand—the more you fight it, the deeper you sink. Indeed, research strongly supports a well-known phrase that “What you resist, persists.”",
                      num1Text: "Paradoxically",
                      num2Text: "Fortunately",
                      num3Text: "Neutrally",
                      num4Text: "Creatively",
                      answer: 1),
        QuestionModel(num: 20,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오.",
                      reference: "How many different ways do you get information? Some people might have six different kinds of communications to answer—text messages, voice mails, paper documents, regular mail, blog posts, messages on different online services. Each of these is a type of in-box, and each must be processed on a continuous basis. It’s an endless process, but it doesn’t have to be exhausting or stressful. Getting your information management down to a more manageable level and into a productive zone starts by ____________________________. Every place you have to go to check your messages or to read your incoming information is an in-box, and the more you have, the harder it is to manage everything. Cut the number of in-boxes you have down to the smallest number possible for you still to function in the ways you need to.",
                      num1Text: "setting several goals at once",
                      num2Text: "immersing yourself in incoming information",
                      num3Text: "minimizing the number of in-boxes you have",
                      num4Text: "choosing information you are passionate about",
                      answer: 3)
        
        ]
        let exam = ExamModel(id: 202322, year: 2023, examTypeID: "지방직", subjectID: "영어", questions: questions)
        exams2023.append(exam)
    }
    
    func saveExam202323() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 ‘주먹도끼’가 사용된 시대에 대한 설명으로 옳은 것은?",
                      reference: "이 유적은 경기도 연천군 한탄강 언저리에 넓게 위치하고 있다. 이곳에서 아슐리안 계통의 "+"주먹도끼".underLined+"가 다량으로 출토되어 더욱 많은 관심이 집중되었다. 이곳에서 발견된 "+"주먹도끼".underLined+"는 그 존재 유무로 유럽과 동아시아 문화가 나뉘어진다고 한 모비우스의 학설을 무너뜨리는 결정적 증거가 되었다.",
                      num1Text: "동굴이나 바위 그늘, 강가의 막집 등에서 살았다.",
                      num2Text: "내부에 화덕이 있는 움집이 일반적인 주거 형태였다.",
                      num3Text: "토기를 만들어 음식을 조리하거나 식량을 저장하였다.",
                      num4Text: "구릉에 마을을 형성하고 그 주변에 도랑을 파고 목책을 둘렀다.",
                      answer: 1),
        QuestionModel(num: 2,
                      questionText: "(가) 군사 조직에 대한 설명으로 옳은 것은?",
                      reference: "고려 정부는 몽골과 강화를 맺고 개경으로 환도하였다. 대몽 항전에 적극적이었던 (가) 은/는 개경 환도를 반대하고 반란을 일으켰다. 이어 진도로 근거지를 옮기면서 항쟁을 전개하였다.",
                      num1Text: "포수, 사수, 살수의 삼수병으로 편제되었다.",
                      num2Text: "윤관의 건의로 편성된 기병 중심의 부대였다.",
                      num3Text: "도적을 잡기 위해 설치한 야별초에서 시작되었다.",
                      num4Text: "양계 지방에서 국경 지역 방어를 맡았던 상비적인 전투부대였다.",
                      answer: 3),
        QuestionModel(num: 3,
                      questionText: "다음과 같은 주장을 한 인물은?",
                      reference: "일단 강화를 맺고 나면 저 적들의 욕심은 물화를 교역하는 데 있습니다. ...(중략)... 저들이 비록 왜인이라고 하나 실은 양적(洋賊)입니다. 강화의 일이 한번 이루어지면 사학(邪學)의 서적과 천주의 상(像)이 교역하는 가운데 섞여 들어갈 것입니다.",
                      num1Text: "박규수",
                      num2Text: "최익현",
                      num3Text: "김홍집",
                      num4Text: "김윤식",
                      answer: 2),
        QuestionModel(num: 4,
                      questionText: "다음에서 설명하는 신문은?",
                      reference: "○ 서재필이 정부 지원을 받아 창간하였다.\n○ 한글판을 발행하여 서양의 문물과 제도를 소개하였다.\n○ 영문판을 발행하여 국내 사정을 외국인에게도 전달하였다.",
                      num1Text: "제국신문",
                      num2Text: "독립신문",
                      num3Text: "한성순보",
                      num4Text: "황성신문",
                      answer: 2),
        QuestionModel(num: 5,
                      questionText: "(가), (나)에 들어갈 왕의 업적으로 옳은 것은?",
                      reference: "삼국의 역사서로는 고구려에 [유기]가 있었는데, 영양왕 때 이문진이 이를 간추려 [신집] 5권을 편찬하였다. 백제에서는 (가) 시기에 고흥이 [서기]를, 신라에서는 (나) 시기에 거칠부가 [국사]를 편찬하였다.",
                      num1Text: "(가)-국호를 남부여로 바꾸었다.",
                      num2Text: "(가)-동진으로부터 불교를 받아들여 공인하였다.",
                      num3Text: "(나)-화랑도를 국가적 조직으로 개편하였다.",
                      num4Text: "(나)-병부를 처음으로 설치하여 군권을 장악하였다.",
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "다음 문화재와 이를 통해 알 수 있는 내용의 연결이 옳지 않은 것은?",
                      num1Text: "사택지적비 - 백제가 영산강 유역까지 영역을 확장하였다.",
                      num2Text: "임신서기석-신라에서 청년들이 유교 경전을 공부하였다.",
                      num3Text: "충주 고구려비-고구려가 5세기에 남한강 유역까지 진출하였다.",
                      num4Text: "호우명 그릇-5세기 초 고구려와 신라가 밀접한 관계를 맺고 있었다.",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "밑줄 친 ‘곽재우’에 대한 설명으로 옳지 않은 것은?",
                      reference: "여러 도에서 의병이 일어났다. ...(중략) ... 도내의 거족(巨族)으로 명망 있는 사람과 유생 등이 조정의 명을 받들어 의(義)를 부르짖고 일어나니 소문을 들은 자들은 격동하여 원근에서 이에 응모하였다. ...(중략)... 호남의 고경명ᆞ김천일, 영남의 곽재우ᆞ정인홍, 호서의 조헌이 가장 먼저 일어났다.\n\n- 선조수정실록 -",
                      num1Text: "홍의장군이라 칭하였다.",
                      num2Text: "의령을 거점으로 봉기하였다.",
                      num3Text: "행주산성에서 일본군을 크게 무찔렀다.",
                      num4Text: "익숙한 지리를 활용한 기습 작전으로 일본군에 타격을 주었다.",
                      answer: 3),
        QuestionModel(num: 8,
                      questionText: "다음과 같은 취지로 전개된 운동에 대한 설명으로 옳은 것은?",
                      reference: "지금 우리들은 정신을 새로이 하고 충의를 떨칠 때이니, 국채 1,300만 원은 우리 대한 제국의 존망에 직결된 것입니다. 이것을 갚으면 나라가 보존되고 이것을 갚지 못하면 나라가 망할 것은 필연적인 사실이나, 지금 국고에서는 도저히 갚을 능력이 없으며, 만일 나라에서 갚지 못한다면 그때는 이미 삼천리 강토는 내 나라 내 민족의 소유가 못 될 것입니다.\n\n- 대한매일신보 -",
                      num1Text: "조선 형평사를 조직하였다.",
                      num2Text: "조선 물산 장려회를 조직하였다.",
                      num3Text: "신사 참배 거부 운동을 전개하였다.",
                      num4Text: "1907년 대구에서 시작되어 전국으로 확산되었다.",
                      answer: 4),
        QuestionModel(num: 9,
                      questionText: "(가), (나)에 들어갈 말을 바르게 연결한 것은?",
                      reference: "조선시대 과거 제도에는 문과ᆞ무과ᆞ잡과가 있었는데, 이 가운데 문과를 가장 중시하였다. [경국대전]에 따르면 문과 시험 업무는 (가) 에서 주관하고, 정기 시험인 식년시는 (나) 마다 실시하는 것이 원칙이었다.",
                      num1Text: "이조 - 2년",
                      num2Text: "이조 - 3년",
                      num3Text: "예조 - 2년",
                      num4Text: "예조 - 3년",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "다음 원칙이 발표된 이후에 있었던 사실로 옳지 않은 것은?",
                      reference: "○ 조선의 민주 독립을 보장한 삼상 회의 결정에 의하여 남북을 통한 좌우 합작으로 민주주의 임시 정부를 수립할 것\n○ 토지 개혁에 있어서 몰수, 유조건 몰수, 체감매상 등으로 토지를 농민에게 무상으로 나누어 주며, ...(중략)... 민주주의 건국 과업 완수에 매진할 것\n○ 입법 기구에 있어서는 일체 그 권능과 구성 방법 운영에 관한 대안을 본 합작 위원회에서 작성하여 적극적으로 실행을 기도할 것",
                      num1Text: "3ᆞ15 부정선거에 대항하여 4ᆞ19 혁명이 일어났다.",
                      num2Text: "친일파를 청산하기 위한 [반민족행위처벌법] 이 공포되었다.",
                      num3Text: "제헌 국회에서 대통령에 이승만, 부통령에 이시영을 선출하였다.",
                      num4Text: "임시 민주 정부 수립을 논의하기 위해 제1차 미ᆞ소 공동 위원회가 개최되었다.",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "밑줄 친 ‘그’에 대한 설명으로 옳은 것은?",
                      reference: "그".underLined+"는 화엄종을 중심으로 교종을 통합하고 해동 천태종을 창시하여 선종까지 포섭하려 하였다. 그러나 "+"그".underLined+"의 사후에 교단은 다시 분열되었고, 권력층과 밀착되어 타락하는 양상까지 나타났다.",
                      num1Text: "이론적인 교리 공부와 실천적인 수행을 아우를 것을 주장하였다.",
                      num2Text: "참선과 독경은 물론 노동에도 힘을 쓰자고 하면서 결사를 제창하였다.",
                      num3Text: "삼국시대 이래 고승들의 전기를 정리하여 [해동고승전]을 편찬하였다.",
                      num4Text: "백련사를 결성하여 극락왕생을 기원하는 참회와 염불 수행을 강조하였다.",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "(가) 시기에 있었던 사실로 옳지 않은 것은?",
                      reference: "임진왜란 - (가) - 병자호란",
                      num1Text: "인조반정이 발생하였다.",
                      num2Text: "영창 대군이 사망하였다.",
                      num3Text: "강홍립이 후금에 항복하였다.",
                      num4Text: "청에 인질로 끌려갔던 봉림 대군이 귀국하였다.",
                      answer: 4),
        QuestionModel(num: 13,
                      questionText: "여름 휴가를 맞아 강화도로 답사 여행을 떠나고자 한다. 다음 중 유적(지)과 주제의 연결이 옳지 않은 것은?",
                      num1Text: "외규장각 - 동학 농민 운동",
                      num2Text: "고려궁지 - 대몽 항쟁",
                      num3Text: "고인돌 - 청동기 문화",
                      num4Text: "광성보 - 신미양요",
                      answer: 1),
        QuestionModel(num: 14,
                      questionText: "조선시대 붕당의 상황에 대한 설명으로 옳지 않은 것은?",
                      num1Text: "선조 대-사림이 동인과 서인으로 분열하였다.",
                      num2Text: "광해군 대-북인이 집권하였다.",
                      num3Text: "인조 대-남인이 정권을 독점하였다.",
                      num4Text: "숙종 대-서인이 노론과 소론으로 갈라졌다.",
                      answer: 3),
        QuestionModel(num: 15,
                      questionText: "조선 세종 대에 있었던 사실로 옳지 않은 것은?",
                      num1Text: "갑인자를 주조하였다.",
                      num2Text: "화통도감을 설치하였다.",
                      num3Text: "역법서인 [칠정산]을 편찬하였다.",
                      num4Text: "간의를 만들어 천체를 관측하였다.",
                      answer: 2),
        QuestionModel(num: 16,
                      questionText: "다음과 같은 강령을 발표한 단체의 활동으로 옳은 것은?",
                      reference: "一. 우리는 정치적, 경제적 각성을 촉진함\n一. 우리는 단결을 공고히 함\n一. 우리는 기회주의를 일체 부인함",
                      num1Text: "조선 민립 대학 기성회를 창립하였다.",
                      num2Text: "파리 강화 회의에 대표를 파견하였다.",
                      num3Text: "6ᆞ10 만세 운동을 사전에 계획하였다.",
                      num4Text: "광주 학생 항일 운동이 일어나자 조사단을 파견하였다.",
                      answer: 4),
        QuestionModel(num: 17,
                      questionText: "다음 글을 쓴 인물에 대한 설명으로 옳은 것은?",
                      reference: "세상에서 동명왕의 신이(神異)한 일을 많이 말한다. ...(중략) ...지난 계축년 4월에 [구삼국사]를 얻어 동명왕 본기 그 신기한 사적이 세상에서 얘기하는 것보다 더하였다. 그러나 처음에는 믿지 못하고 귀신이나 환상이라고만 생각하였는데, 두세 번 반복하여 읽어서 점점 그 근원에 들어가니 환상이 아닌 성스러움이며, 귀신이 아닌 신성한 이야기였다.",
                      num1Text: "사실의 기록보다 평가를 강조한 강목체 사서를 편찬하였다.",
                      num2Text: "단군부터 고려 충렬왕 때까지의 역사를 서사시로 기록하였다.",
                      num3Text: "단군신화와 전설 등 민간에서 전승되는 자료를 광범위하게 수록하였다.",
                      num4Text: "김부식의 [삼국사기]에 동명왕의 신이한 사적이 생략되어 있다고 평하였다.",
                      answer: 4),
        QuestionModel(num: 18,
                      questionText: "1910년대에 있었던 사실로 옳은 것은?",
                      num1Text: "중국 화북 지방에서 조선 독립 동맹이 결성되었다.",
                      num2Text: "만주에서 참의부, 정의부, 신민부 등 3부가 조직되었다.",
                      num3Text: "임병찬이 주도한 독립 의군부는 항일 운동을 전개하였다.",
                      num4Text: "조선 혁명군이 양세봉의 지휘 아래 영릉가에서 일본군을 격파하였다.",
                      answer: 3),
        QuestionModel(num: 19,
                      questionText: "다음 주장을 한 인물에 대한 설명으로 옳은 것은?",
                      reference: "우리 조선의 역사적 발전의 전 과정은 가령 지리적 조건, 인종학적 골상, 문화 형태의 외형적 특징 등 다소의 차이는 인정되더라도, 다른 문화 민족의 역사적 발전 법칙과 구별되어야 하는 독자적인 것이 아니다. 세계사적인 일원론적 역사 법칙에 의해 다른 민족과 거의 같은 궤도로 발전 과정을 거쳐왔다.",
                      num1Text: "민족정신으로서 조선 국혼을 강조하였다.",
                      num2Text: "민족주의 사학을 계승하여 조선의 얼을 강조하였다.",
                      num3Text: "마르크스 유물 사관을 바탕으로 한국사를 연구하였다.",
                      num4Text: "진단 학회를 조직하여 문헌 고증을 중시하는 실증주의 사학을 정립하였다.",
                      answer: 3),
        QuestionModel(num: 20,
                      questionText: "6ᆞ25 전쟁 중 있었던 사실로 옳지 않은 것은?",
                      num1Text: "국군과 유엔군이 인천 상륙 작전을 감행하였다.",
                      num2Text: "대통령 직선제를 포함한 발췌 개헌안이 국회에서 통과되었다.",
                      num3Text: "이승만 정부가 북한 송환을 거부하는 반공 포로를 석방하였다.",
                      num4Text: "미국이 한반도를 미국의 태평양 지역 방위선에서 제외한다는 에치슨 선언을 발표하였다.",
                      answer: 4)
        
        
        ]
        let exam = ExamModel(id: 202323, year: 2023, examTypeID: "지방직", subjectID: "한국사", questions: questions)
        exams2023.append(exam)
    }
    
    
    
}
