//
//  ExamStore2023.swift
//  HandGosi
//
//  Created by Sy Lee on 2023/05/16.
//

import Foundation

class ExamStore2023 {
    var exams2023: [ExamModel] = []
    
    init() {
        saveExam202311()
        saveExam202312()
        saveExam202313()
//
//        saveExam202321()
//        saveExam202322()
//        saveExam202323()
    }
    
    func saveExam202311() {
        let questions =
        [
            QuestionModel(num: 1,
                          questionText: "‘해양 오염’을 주제로 연설을 한다고 할 때, 다음에 제시된 조건을 모두 충족한 것은?",
                          reference: "○ 해양 오염을 줄일 수 있는 생활 속 실천 방법을 포함할 것.\n○ 설의적 표현과 비유적 표현을 활용할 것.",
                          num1Text: "바다는 쓰레기 없는 푸른 날을 꿈꾸고 있습니다. 미세 플라스틱은 바다를 서서히 죽이는 보이지 않는 독입니다. 우리의 관심만이 다시 바다를 살릴 수 있을 것입니다.",
                          num2Text: "우리가 버린 쓰레기는 바다로 흘러갔다가 해양 생물의 몸에 축적이 되어 해산물을 섭취하면 결국 다시 우리에게 돌아오게 됩니다. 분리수거를 철저히 하고 일회용품을 줄이는 것이 바다도 살리고 우리 자신도 살리는 길입니다.",
                          num3Text: "여름만 되면 피서객들이 마구 버린 쓰레기로 바다가 몸살을 앓는다고 합니다. 자기 집이라면 이렇게 함부로 쓰레기를 버렸을까요? 피서객들의 양심이 모래밭 위를 뒹굴고 있습니다. 자기 쓰레기는 자기가 집으로 되가져가도록 합시다.",
                          num4Text: "산업 폐기물이 바다로 흘러가 고래가 죽어 가는 장면을 다큐멘터리 에서 본 적이 있습니다. 이대로 가다간 인간도 고통받게 되지 않을까요? 정부에서 산업 폐기물 관리 지침을 만들고 감독을 강화하지 않는다면 바다는 쓰레기 무덤이 되고 말 것입니다.",
                          answer: 3) ,
            QuestionModel(num: 2,
                          questionText: "다음 대화에 나타난 말하기 방식을 설명한 것으로 적절하지 않은 것은?",
                          reference: "백 팀장: 이번 워크숍 장면을 사내 게시판에 올리는 게 좋겠어요. 워크숍 내용을 공유하면 좋을 것 같아서요.\n\n고 대리: 전 반대합니다. 사내 게시판에 영상을 공개하는 것은 부담스러워요. 타 부서와 비교될 것 같기도 하고요.\n\n임 대리: 저도 팀장님 말씀대로 정보를 공유한다는 취지는 좋다고 생각해요. 다만 다른 팀원들의 동의도 구해야 할 것 같고, 여러 면에서 우려되긴 하네요. 팀원들 의견을 먼저 들어 보고, 잘된 것만 시범적으로 한두 개 올리는 것이 어떨까요?",
                          num1Text: "백 팀장은 팀원들에 대한 유대감을 드러내는 표현을 사용하며 자신의 바람을 전달하고 있다.",
                          num2Text: "고 대리는 백 팀장의 제안에 반대하는 이유를 명시적으로 밝히며 백 팀장의 요청을 거절하고 있다.",
                          num3Text: "임 대리는 발언 초반에 백 팀장 발언의 취지에 공감하여 백 팀장의 체면을 세워 주고 있다.",
                          num4Text: "임 대리는 대화 참여자의 의견을 묻는 의문문을 사용하여 자신의 의견을 간접적으로 드러내고 있다.",
                          answer: 1),
            QuestionModel(num: 3,
                          questionText: "관용 표현 ᄀ~ᄅ의 의미를 풀이한 것으로 적절하지 않은 것은?",
                          reference: "○ 그의 회사는 작년에 노사 갈등으로 ㄱ"+"홍역을 치렀다.".underLined+"\n\n○ 우리 교장 선생님은 교육계에서 ㄴ"+"잔뼈가 굵은".underLined+" 분이십니다.\n\n○ 유원지로 이어지는 국도에는 차가 밀려 ㄷ"+"입추의 여지가 없었다.".underLined+"\n\n○ 그분은 세계 유수의 연구자들과 ㄹ"+"어깨를 나란히 하는".underLined+" 물리학자이다.",
                          num1Text: "ㄱ: 심한 어려움을 겪었다",
                          num2Text: "ㄴ: 오랫동안 일을 하여 그 일에 익숙한",
                          num3Text: "ㄷ: 돌아서 갈 수 있는 방법이 없었다",
                          num4Text: "ㄹ: 비슷한 지위나 힘을 가지는",
                          answer: 3),
            QuestionModel(num: 4,
                          questionText: "다음 글에서 (가) ~ (다)의 순서를 자연스럽게 배열한 것은?",
                          reference: "  빅데이터가 부각된다는 것은 기업들이 빅데이터의 가치를 받아들이기 시작했다는 뜻이다. 여기에는 기업들이 데이터를 바라보는 시각이 변한 측면도 있다.\n(가) 기업들은 고객이 판촉 활동에 어떻게 반응하고 평소에 어떻게 행동하며 사물에 대해 어떤 태도를 보이는지 알기 위해 많은 돈을 투자해 마케팅 조사를 해 왔다.\n\n(나) 그런 상황에서 기업들은 SNS나 스마트폰 등 새로운 데이터 소스로부터 그러한 궁금증과 답답함을 해결할 수 있다는 것을 알게 되었다. 페이스북에 올리는 광고에 친구가 ‘좋아요’를한 것에서 기업들은 궁금증과 답답함을 해결할 수 있다.\n\n(다) 그런데 기업들의 그런 노력이 효과가 있는 경우도 있었으나 아쉬운 점도 많았다. 쉬운 예로, 기업들은 많은 광고비를 쓰지만 그 돈이 구체적으로 어느 부분에서 효과를 내는지는 알지 못했다.\n  결국 데이터가 있는 곳에서 기업들은 점점 더 고객의 취향에 집중할 수 있게 되었으며, 이에 따라 기업들은 소셜 미디어의 빅데이터를 중요한 경영 수단으로 수용하기 시작한 것이다.",
                          num1Text: "(가)-(나)-(다)",
                          num2Text: "(가)-(다)-(나)",
                          num3Text: "(나)-(가)-(다)",
                          num4Text: "(다)-(나)-(가)",
                          answer: 2),
            QuestionModel(num: 5,
                          questionText: "ㄱ을 이해한 내용으로 적절하지 않은 것은?",
                          reference: "  "+"“ᄀ무진(霧津)".underLined+"엔 명산물이......뭐 별로 없지요?” 그들은 대화를 계속하고 있었다. “별게 없지요. 그러면서도 그렇게 많은 사람들이 살고 있다는 건 좀 이상스럽거든요.” “바다가 가까이 있으니 항구로 발전할 수도 있었을 텐데요?” “가 보시면 아시겠지만 그럴 조건이 되어 있는 것도 아닙니다. 수심(水深)이 얕은 데다가 그런 얕은 바다를 몇백 리나 밖으로 나가야만 비로소 수평선이 보이는 진짜 바다다운 바다가 나오는 곳이니까요.” “그럼 역시 농촌이군요?” “그렇지만 이렇다 할 평야가 있는 것도 아닙니다.” “그럼 그 오륙만이 되는 인구가 어떻게들 살아가나요?” “그러니까 그럭저럭이란 말이 있는 게 아닙니까!” 그들은 점잖게 소리 내어 웃었다. “원, 아무리 그렇지만 한 고장에 명산물 하나쯤은 있어야지.” 웃음 끝에 한 사람이 말하고 있었다.\n  무진에 명산물이 없는 게 아니다. 나는 그것이 무엇인지 알고 있다. 그것은 안개다. 아침에 잠자리에서 일어나서 밖으로 나오면, 밤사이에 진주해 온 적군들처럼 안개가 무진을 삥 둘러싸고 있는 것이었다. 무진을 둘러싸고 있는 산들도 안개에 의하여 보이지 않는 먼 곳으로 유배당해 버리고 없었다.\n\n - 김승옥, 〖무진기행〗 에서",
                          num1Text: "수심이 얕아서 항구로 개발하기 어려운 공간이다.",
                          num2Text: "산으로 둘러싸여 있고 평야가 발달하지 않은 공간이다.",
                          num3Text: "지역의 경제적 여건에 비해 인구가 적지 않은 공간이다.",
                          num4Text: "누구나 인정할 만한 지역의 명산물로 안개가 유명한 공간이다.",
                          answer: 4),
            QuestionModel(num: 6,
                          questionText: "다음 글의 빈칸에 들어갈 사자성어로 적절한 것은?",
                          reference: "세상에는 어려운 일들이 많지만 외국 여행 다녀온 사람의 입을 막는 것도 그중 하나이다. 특히 그것이 그 사람의 첫외국 여행이었다면, 입 막기는 포기하고 미주알고주알 늘어놓는 여행 경험을 들어 주는 편이 정신 건강에좋다. 그사람이별것아닌 사실을 [    ]하거나 특수한 경험을 지나치게 일반화한들, 그런 수다로 큰 피해를 입는 것도 아니지 않은가?",
                          num1Text: "刻舟求劍",
                          num2Text: "捲土重來",
                          num3Text: "臥薪嘗膽",
                          num4Text: "針小棒大",
                          answer: 4),
            QuestionModel(num: 7,
                          questionText: "다음 글을 감상한 내용으로 가장 적절한 것은?",
                          reference: " 어이 못 오던가 무 일로 못 오던가\n 너 오 길 위에 무쇠로 성(城)을 고 성안에 담 고 담 안에란 집을 짓고 집 안에란 뒤주 노코 뒤주 안에 궤를 노코 궤 안에 너를 결박(結縛)여 너코 쌍(雙)목 외걸쇠에 용(龍)거북 믈쇠로 수기수기 갓더냐 네 어이 그리 아니 오던가\n  이 서른 날이여니 날 보라 올 하루 업스랴\n\n - 작자 미상, 어이 못 오던가 -",
                          num1Text: "동일 구절을 반복하여 ‘너’에 대한 섭섭한 감정을 표출하고 있다.",
                          num2Text: "날짜 수를 대조하여 헤어진 기간이 길다는 것을 강조하고 있다.",
                          num3Text: "동일한 어휘를 연쇄적으로 나열하여 감정의 기복을 표현하고 있다.",
                          num4Text: "단계적으로 공간을 축소하여 ‘너’를 만날 수 있다는 희망을 표현하고 있다.",
                          answer: 1),
            QuestionModel(num: 8,
                          questionText: "(가)와 (나)에 들어갈 말로 가장 적절한 것은?",
                          reference: "  특정한 작업을 수행하기 위해 신체 근육의 특정 움직임을 조작하는 능력을 운동 능력이라고 한다. 언어에 관한 운동 능력은 ‘발음 능력’과 ‘필기 능력’ 두 가지인데 모두 표현을 위한 능력이다.\n  말로 표현하기 위해서는 발음 능력이 필요한데, 이는 음성 기관을 움직여 원하는 음성을 만들어 내는 능력이다. 이 능력은 영ᆞ유아기에 수많은 시행착오와 꾸준한 훈련을 통해 습득된다. 이렇게 발음 능력을 습득하면 음성 기관의 움직임은 자동화되어 음성 기관의 어느 부분을 언제 어떻게 움직일지를 화자가 거의 의식하지 않는다. 우리가 모어에 없는 외국어 음성을 발음하기 어려운 이유는 [ (가) ] 있기 때문이다.\n  글로 표현하기 위해서는 필기 능력이 필요하다. 필기에서는 글자의 모양을 서로 구별되게 쓰는 것은 기본이고 그 수준을 넘어서서 쉽게 알아볼 수 있는 모양으로 잘 쓰는 것도 필요하다. 글씨를 쓰기 위해 손을 놀리는 것은 발음을 하기 위해 음성 기관을 움직이는 것에 비해 상당히 의식적이라 할 수 있다. 그렇지만 개인의 의지와 관계없이 필체가 꽤 일정하다는 사실은 손을 놀리는 데에 [ (나) ] 의미한다.",
                          num1Text: "(가): 음성 기관의 움직임이 모어의 음성에 맞게 자동화되어\n(나): 무의식적이고 자동적인 면이 있음을",
                          num2Text: "(가): 낯선 음성은 무의식적으로 발음하도록 훈련되어\n(나): 유아기에 수행한 훈련이 효과적이지 않음을",
                          num3Text: "(가): 음성 기관의 움직임이 모어의 음성에 맞게 자동화되어\n(나): 유아기에 수행한 훈련이 효과적이지 않음을",
                          num4Text: "(가): 낯선 음성은 무의식적으로 발음하도록 훈련되어\n(나): 무의식적이고 자동적인 면이 있음을",
                          answer: 1),
            QuestionModel(num: 9,
                          questionText: "ㄱ~ㄹ중 한글 맞춤법에 맞게 쓰인 것만을 모두 고르면?",
                          reference: "○ 혜인 씨에게 "+"ᄀ무정타".underLined+" 말하지 마세요.\n○ 재아에게는 "+"ᄂ섭섭치".underLined+" 않게 사례해 주자.\n○ 규정에 따라 딱 세 명만 "+"ᄃ선발토록".underLined+" 했다.\n○ "+"ᄅ생각컨대".underLined+" 그의 보고서는 공정하지 못했다.",
                          num1Text: "ㄱ, ㄴ",
                          num2Text: "ㄱ, ㄷ",
                          num3Text: "ㄴ, ㄹ",
                          num4Text: "ㄷ, ㄹ",
                          answer: 2),
            QuestionModel(num: 10,
                          questionText: "ㄱ~ㄹ의 한자로 적절하지 않은 것은?",
                          reference: "  예정보다 지연되긴 했으나 열 시쯤에는 마애불에 "+"ᄀ도착".underLined+"할 수가 있었다. 맑은 날씨에 빛나는 햇살이 환히 비춰 "+"ᄂ불상".underLined+"들은 불그레 물들어 있었다. 만일 신비로운 "+"ᄃ경지".underLined+"라는 말을 할 수 있다면 바로 이런 경우가 아닐지 모르겠다. 꼭 보고 싶다는 숙원이 이루어진 기쁨에 가슴이 벅차 왔다. 아마 잊을 수 없는 "+"ᄅ추억".underLined+"의 한 토막으로 남을 것 같다.",
                          num1Text: "ᄀ: 到着",
                          num2Text: "ᄂ: 佛像",
                          num3Text: "ᄃ: 境地",
                          num4Text: "ᄅ: 記憶",
                          answer: 4),
            QuestionModel(num: 11,
                          questionText: "다음 글을 이해한 내용으로 적절하지 않은 것은?",
                          reference: "  사람의‘지각과 생각’은 항상 어떤 맥락, 관점 혹은 어떤 평가 기준이나 가정하에서 일어난다. 이러한 맥락, 관점, 평가 기준, 가정을 프레임이라고 한다. 지각과 생각은 인간의 모든 정신 활동을 뜻한다. 따라서 우리의 모든 정신 활동은 진공 상태에서 일어나는 것이 아니라, 어떤 맥락이나 가정하에서 일어난다. 한마디로 우리가 프레임이라는 안경을 쓰고 세상을 보고 있음을 의미한다. 간혹 어떤 사람이 자신은 어떤 프레임의 지배도 받지 않고 세상을 있는 그대로, 객관적으로 본다고 주장한다면, 그 주장은 진실이 아닐 것이다.",
                          num1Text: "인간의 정신 활동은 프레임 없이 일어나지 않는다.",
                          num2Text: "프레임은 인간이 세상을 바라볼 때 어떤 편향성을 가지게 한다.",
                          num3Text: "인간의 지각과 사고를 확장하는 과정에서 프레임은 극복해야 할 대상이다.",
                          num4Text: "프레임은 인간의 정신 활동에 영향을 미치는 어떤 맥락이나 평가 기준이다.",
                          answer: 3),
            QuestionModel(num: 12,
                          questionText: "다음 글을 이해한 내용으로 가장 적절한 것은?",
                          reference: "  전 세계를 대표하는 항공기인 보잉과 에어버스의 중요한 차이점은 자동조종시스템의 활용 정도에 있다. 보잉의 경우, 조종사가 대개 항공기를 조종간으로 직접 통제한다. 조종간은 비행기의 날개와 물리적으로 연결되어 있어서 어떤 상황에서도 조종사가 조작한 대로 반응한다. 이와 다르게 에어버스는 조종간 대신 사이드스틱을 설치하여 컴퓨터가 조종사의 행동을 제한 하거나 조종에 개입할 수 있게 설계되었다. 보잉에서는 조종사가 항공기를 통제할 수 있는 전권을 가지지만 에어버스에서는 컴퓨터가 조종사의 조작을 감시하고 제한한다.\n  보잉과 에어버스의 이러한 차이는 기계를 다루는 인간을 바라보는 관점이 서로 다른 데서 비롯된다. 보잉사를 창립한 윌리엄 보잉의 철학은 “비행기를 통제하는 최종 권한은 언제나 조종사에게 있다.”이다. 시스템은 불안정하고 완벽하지 않기 때문에 컴퓨터가 조종사의 판단보다 우선시될 수 없다는 것이다. 반면 에어버스의 아버지라고 불리는 베테유는 “인간은 실수할 수 있는 존재”라고 전제한다. 베테유는 이런 자신의 신념을 토대로 에어버스를 설계함으로써 조종사의 모든 조작을 컴퓨터가 모니터링하고 제한하게 만든 것이다.",
                          num1Text: "보잉은 시스템의 불완전성을, 에어버스는 인간의 실수 가능성을 고려하여 설계되었다.",
                          num2Text: "베테유는 인간이 실수할 수 있는 존재라고 보지만 윌리엄 보잉은 그렇지 않다고 본다.",
                          num3Text: "에어버스의 조종사는 항공기 운항에서 자동조종시스템을 통제하고 조작한다.",
                          num4Text: "보잉의 조종사는 자동조종시스템을 사용하지 않고 항공기를 조종한다.",
                          answer: 1),
            QuestionModel(num: 13,
                          questionText: "다음 글에서 추론한 내용으로 가장 적절한 것은?",
                          reference: "  공포의 상태와 불안의 상태를 구분하는 것은 쉽지 않다. 왜냐하면 두 감정을 함께 느끼거나 한 감정이 다른 감정을 유발할 때가 많기 때문이다. 가령, 무시무시한 전염병을 목도하고 공포에 빠진 사람은 자신도 언젠가 그 병에 걸릴지 모른다는 불안 상태에 빠지게 된다. 이처럼 두 감정은 서로 밀접하게 얽혀 있다는 점에서 혼동하기 쉽다. 하지만 두 감정을 야기한 원인을 따져 보면 두 감정을 명확하게 구분할 수 있다. 공포는 실재하는 객관적 위협에 의해 야기된 상태를 의미하고, 불안은 현재 발생하지 않았으며 미래에 일어날지 모르는 불명확한 위협에 의해 야기된 상태를 의미한다. 공포와 불안의 감정은 둘 다 자아와 관련되어 있지만 여기에서도 차이를 찾을 수 있다. 공포를 느끼는 것은 ‘나 자신’이 위험한 상황에 놓여 있다는 사실을 아는 것이고, 불안의 경험은 ‘나 자신’이 위해를 입을까 봐 걱정하는 것이다.",
                          num1Text: "자신이 처한 위험한 상황을 정확히 인식하는 경우에는 공포감에 비해 불안감이 더 크다.",
                          num2Text: "전기ᆞ가스 사고가 날까 두려워 외출하지 못하는 사람은 불안한 상태에 있는 것이다.",
                          num3Text: "시험에 불합격할 수 있다는 생각에 사로잡힌 사람은 공포감에 빠져 있는 것이다.",
                          num4Text: "과거에 큰 교통사고를 경험한 사람은 공포감은 크지만 불안감은 작다.",
                          answer: 2),
            QuestionModel(num: 14,
                          questionText: "다음 글의 내용과 부합하지 않는 것은?",
                          reference: "  과학 혁명 이전 아리스토텔레스 철학은 로마 가톨릭교의 정통 교리와 결합되어 있었기 때문에 오랜 시간 동안 지배적인 영향력을 발휘하였다. 천문 분야 또한 예외는 아니었다. 아리스토텔레스의 세계관을 따라 우주의 중심은 지구이며, 모든 천체는 원운동을 하면서 지구의 주위를 공전한다는 천동설이 정설로 자리 잡고 있었다. 프톨레마이오스가 천체들의 공전 궤도를 관찰하던 도중, 행성들이 주기적으로 종전의 운동과는 반대 방향으로 움직인다는 관찰 결과를 얻었을 때도 그는 이를 행성의 역행 운동을 허용하지 않는 천동설로 설명하고자 하였다. 그래서 지구를 중심으로 공전하는 원 궤도에 중심을 두고 있는 원, 즉 주전원(周轉圓)을 따라 공전 궤도를 그리면서 행성들이 운동한다고 주장하였다.\n  과학과 아리스토텔레스 철학의 결별은 서서히 일어났다. 그 과정에서 일어난 가장 중요한 사건은 1543년 코페르니쿠스가 행성들의 운동 이론에 관한 책을 발간한 일이다. 코페르니쿠스는 천체의 중심에 지구 대신 태양을 놓고 지구가 태양의 주위를 공전한다고 주장하였다. 태양을 우주의 중심에 둔 코페르니쿠스의 지동설은 행성들의 운동에 대해 프톨레마이오스보다 수학적으로 단순하게 설명하였다.",
                          num1Text: "과학 혁명 이전 시기에는 천동설이 정설로 받아들여졌다.",
                          num2Text: "프톨레마이오스의 주전원은 지동설을 지지하고자 만든 개념이다.",
                          num3Text: "천동설과 지동설은 우주의 중심을 어디에 두느냐에 따라 구분된다.",
                          num4Text: "행성의 공전에 대한 프톨레마이오스의 설명은 코페르니쿠스의 설명보다 수학적으로 복잡하였다.",
                          answer: 2),
            QuestionModel(num: 15,
                          questionText: "밑줄 친 단어가 표준어 규정에 맞게 쓰인 것은?",
                          num1Text: "저기 보이는 게 암염소인가, "+"수염소".underLined+"인가?",
                          num2Text: "오늘 "+"윗층".underLined+"에 사시는 분이 이사를 가신대요.",
                          num3Text: "봄에는 여기저기에서 "+"아지랭이"+"가 피어오른다.",
                          num4Text: "그는 수업을 마치면 "+"으레".underLined+" 친구들과 운동을 한다.",
                          answer: 4),
            QuestionModel(num: 16,
                          questionText: "ㄱ~ㄹ을 문맥에 맞게 수정하는 방안으로 적절한 것은?",
                          reference: "난독(難讀)을 해결하려면 정독을 해야 한다. 여기서 말하는 정독은 ‘뜻을 새겨 가며 자세히 읽음’, 즉 ‘정교한 독서’라는 뜻으로 한자로는 ‘精讀’이다. ‘精讀’은 ‘바른 독서’를 의미하는 ‘正讀’과 "+"ᄀ소리는 같지만 뜻이 다르다.".underLined+" 무엇이 정교한 것일까? 모든 단어에 눈을 마주치면서 제대로 인식하는 것이다. 이와 같은 "+"ᄂ정독(精讀)".underLined+"의 결과로 생기는 어문 실력이 문해력이다. 문해력이 발달하면 결국 독서 속도가 빨라져, ‘빨리 읽기’인 속독(速讀)이 가능해진다. 빨리 읽기는 정독을 전제로 할 때 빛을 발한다. 짧은 시간에 같은 책을 제대로 여러 번 읽을 수 있기 때문이다. 그래서 문해력의 증가는 ‘정교하고 빠르게 읽기’, 즉 "+"ᄃ정속독(正速讀)".underLined+"에서 일어나게 되어 있다. 정독이 생활화되면 자기도 모르게 정속독의 경지에 오르게 된다. 그런 경지에 오른 사람들은 뭐든지 확실히 읽고 빨리 이해한다. 자연스레 집중하고 여러 번 읽어도 빠르게 읽으므로 시간이 여유롭다. "+"ᄅ 정독이 빠진 속독".underLined+"은 곧 빼먹고 읽는 습관, 즉 난독의 일종임을 잊지 말아야 한다.",
                          num1Text: "ᄀ을 ‘다르게 읽지만 뜻이 같다’로 수정한다.",
                          num2Text: "ᄂ을 ‘정독(正讀)’으로 수정한다.",
                          num3Text: "ᄃ을 ‘정속독(精速讀)’으로 수정한다.",
                          num4Text: "ᄅ을 ‘속독이 빠진 정독’으로 수정한다.",
                          answer: 3),
            QuestionModel(num: 17,
                          questionText: "다음 글을 감상한 내용으로 적절하지 않은 것은?",
                          reference: "막바지 뙤약볕 속\n한창 매미 울음은\n한여름 무더위를 그 절정까지 올려놓고는 이렇게 다시 조용할 수 있는가.\n지금은 아무 기척도 없이\n정적의 소리인 듯 쟁쟁쟁\n천지(天地)가 하는 별의별\n희한한 그늘의 소리에\n멍청히 빨려 들게 하구나.\n사랑도 어쩌면\n그와 같은 것인가.\n소나기처럼 숨이 차게 정수리부터 목물로 들이붓더니 얼마 후에는\n그것이 아무 일도 없었던 양 맑은 구름만 눈이 부시게 하늘 위에 펼치기만 하노니.\n\n - 박재삼, '매미 울음 끝에' -",
                          num1Text: "갑작스럽게 변화한 자연 현상을 감각적으로 제시하고 있다.",
                          num2Text: "청각적 이미지와 시각적 이미지를 활용하여 시상을 전개하고 있다.",
                          num3Text: "소나기가 그치고 맑은 구름이 펼쳐진 것을 통해 사랑의 속성을 드러내고 있다.",
                          num4Text: "매미 울음소리가 절정에 이르렀다가 사라진 직후의 상황을 반어법으로 표현하고 있다.",
                          answer: 4),
            QuestionModel(num: 18,
                          questionText: "다음 글을 이해한 내용으로 가장 적절한 것은?",
                          reference: ". 루카치는 그리스 세계를 신과 인간의 결합 정도를 가리키는 ‘총체성’ 개념을 기준으로 세 시대로 구분하였다. 첫 번째 시대에서 후대로 갈수록 총체성의 정도는 낮아진다. 첫째는 총체성이 완전히 구현되어 있는 ‘서사시의 시대’이다. 호메로스의 일리아드와 오디세이아에서는 신과 인간의 세계가 하나로 얽혀 있다. 인간들이 그리스와 트로이 두 패로 나뉘어 전쟁을 벌일 때 신들도 인간의 모습을 하고 두 패로 나뉘어 전쟁에 참여했다. 둘째는 ‘비극의 시대’이다. 소포클레스나 에우리피데스의 비극에서는 총체성이 흔들려 신과 인간의 세계가 분리된다. 하지만 두 세계가 완전히 분리되지는 않고 신탁이라는 약한 통로로 이어져 있다. 비극에서 신은 인간의 행위에 직접 개입하지 않고 신탁을 통해서 자신의 뜻을 그저 전달하는 존재로 바뀐다. 셋째는 플라톤으로 대표되는 ‘철학의 시대’이다. 이 시대는 이미 계몽된 세계여서 신탁 같은 것은 신뢰할 수 없게 되었다. 신과 인간의 세계가 완전히 분리됨으로써 신의 세계는 인격적 성격을 상실하여 ‘이데아’라는 추상성의 세계로 바뀐다. 신의 세계와 인간의 세계는 그 사이에 어떤 통로도 존재할 수 없는, 절대적으로 분리된 세계가 되었다.",
                          num1Text: "계몽사상은 서사시의 시대에서 철학의 시대로의 전환을 이끌었다.",
                          num2Text: "플라톤의 이데아는 신탁이 사라진 시대의 비극적 세계를 표현한다.",
                          num3Text: " 루카치는 각기 다른 기준에 따라 그리스 세계를 세 시대로 구분하였다.",
                          num4Text: "에우리피데스의 비극에 비해 오디세이아에서는 신과 인간의 결합 정도가 높다.",
                          answer: 4),
            QuestionModel(num: 19,
                          questionText: "다음 글의 내용과 부합하지 않는 것은?",
                          reference: ". 몽유록(夢遊錄)은 ‘꿈에서 놀다 온 기록’이라는 뜻으로, 어떤 인물이 꿈에서 과거의 역사적 인물을 만나 특정 사건에 대한 견해를 듣고 현실로 돌아온다는 특징이 있다. 이때 꿈을 꾼 인물인 몽유자의 역할에 따라 몽유록을 참여자형과 방관자형으로 구분할 수 있다. 참여자형에서는 몽유자가 꿈에서 만난 인물들의 모임에 초대를 받고 토론과 시연에 직접 참여한다. 방관자형 에서는 몽유자가 인물들의 모임을 엿볼 뿐 직접 그 모임에 참여하지는 않는다. 16~17세기에 창작되었던 몽유록에는 참여자형이 많다. 참여자형에서는 몽유자와 꿈속 인물들이 동질적인 이념을 공유하고 현실의 고통스러운 문제에 대해 의견을 나누며 비판적 목소리를 낸다. 그러나 주로 17세기 이후에 창작된 방관자형에서는 몽유자가 꿈속 인물들과 함께 현실을 비판하는 것이 아니라 구경꾼의 위치에 서 있다. 이 시기의 몽유록이 통속적이고 허구적인 성격으로 변모하는 것은 몽유자의 역할 변화와 무관하지 않다.",
                          num1Text: "몽유자가 꿈속 인물들의 모임에 직접 참여하는지, 참여하지 않는지에 따라 몽유록의 유형을 나눌 수 있다.",
                          num2Text: "17세기보다 나중 시기의 몽유록에서는 몽유자가 현실을 비판하는 경향이 강하게 나타난다.",
                          num3Text: "몽유자가 모임의 구경꾼 역할을 하는 몽유록은 통속적이고 허구적인 성격이 강하다.",
                          num4Text: "몽유자가 꿈속 인물들과 함께 현실을 비판하는 몽유록은 참여자형에 해당한다.",
                          answer: 2),
            QuestionModel(num: 20,
                          questionText: "다음 글을 이해한 내용으로 적절한 것은?",
                          reference: ". 디지털 트윈은 현실 세계와 똑같은 가상의 세계이다. 최근 주목받고 있는 메타버스와 개념은 유사하지만 활용 목적의 측면에서 구별된다. 메타버스는 가상 세계와 현실 세계가 융합된 플랫폼으로 이용자들에게 새로운 경제ᆞ사회ᆞ문화적 경험을 제공하는 데 목적을 둔다. 반면 디지털 트윈은 현실 세계에 존재하는 사물, 공간, 환경, 공정 등을 컴퓨터상에 디지털 데이터 모델로 표현하여 똑같이 복제하고 실시간으로 서로 반응할 수 있도록 한다. 그래서 디지털 트윈의 이용자는 가상 세계에서의 시뮬레이션을 통해 미래 상황을 예측할 수 있게 된다. 디지털 트윈에 대한 수요가 증가하면서 관련 시장도 확대되고 있으며, 국내외의 글로벌 기업들은 여러 산업 분야에서 디지털 트윈을 도입하여 사전에 위험 요소를 제거하고 수익 모델의 효율성을 높이고 있다. 디지털 트윈이 이렇게 주목받는 이유는 안정성과 경제성 때문인데 현실 세계를 그대로 옮겨 놓은 가상 세계에 데이터를 전송, 취합, 분석, 이해, 실행하는 과정은 실제 실험보다 매우 빠르고 정밀하며 안전할 뿐 아니라 비용도 적게 든다.",
                          num1Text: "디지털 트윈을 활용함에 따라 글로벌 기업들의 고용률이 향상되었다.",
                          num2Text: "디지털 트윈의 데이터 모델은 현실 세계의 각종 실험 모델보다 경제성이 낮다.",
                          num3Text: "디지털 트윈에서의 시뮬레이션으로 현실 세계의 위험 요소를 찾아내고 방지할 수 있다.",
                          num4Text: "디지털 트윈은 현실 세계의 이용자에게 새로운 문화적 경험을 제공하는 데 목적이 있다.",
                          answer: 3)
            
        ]
        let exam = ExamModel(id: 202311, year: 2023, examTypeID: "국가직", subjectID: "국어", questions: questions)
        exams2023.append(exam)
    }
    
    func saveExam202312() {
        let questions = [
            
            QuestionModel(num: 1,
                          questionText: "밑줄 친 부분의 의미와 가장 가까운 것을 고르시오.",
                          reference: "Jane wanted to have a small wedding rather than a fancy one. Thus, she planned to invite her family and a few of her "+"intimate".underLined+" friends to eat delicious food and have some pleasant moments.",
                          num1Text: "nosy",
                          num2Text: "close",
                          num3Text: "outgoing",
                          num4Text: "considerate",
                          answer: 2),
            QuestionModel(num: 2, questionText: "밑줄친 부분의 의미와 가장 가까운것을 고르시오.", reference: "The "+"incessant".underLined+" public curiosity and consumer demand due to the health benefits with lesser cost has increased the interest in functional foods.",
                          num1Text: "rapid",
                          num2Text: "constant",
                          num3Text: "significant",
                          num4Text: "intermittent",
                          answer: 2),
            QuestionModel(num: 3,
                          questionText: "밑줄친 부분의 의미와 가장 가까운것을 고르시오.",
                          reference: "Because of the pandemic, the company had to "+"hold off".underLined+" the plan to provide the workers with various training programs.",
                          num1Text: "elaborate",
                          num2Text: "release",
                          num3Text: "modify",
                          num4Text: "suspend",
                          answer: 4),
            QuestionModel(num: 4,
                          questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한것을 고르시오.",
                          reference: "The new Regional Governor said he would "+"abide by".underLined+" the decision of the High Court to release the prisoner.",
                          num1Text: "accept",
                          num2Text: "report",
                          num3Text: "postpone",
                          num4Text: "announce",
                          answer: 1),
            QuestionModel(num: 5,
                          questionText: "밑줄 친 부분 중 어법상 옳지 않은 것은?",
                          reference: "While advances in transplant technology have made "+"1)it".underLined+" possible to extend the life of individuals with end-stage organ disease, it is argued "+"2)that".underLined+" the biomedical view of organ transplantation as a bounded event, which ends once a heart or kidney is successfully replaced, "+"3)conceal".underLined+" the complex and dynamic process that more "+"4)accurately".underLined+" represents the experience of receiving an organ.",
                          num1Text: "",
                          num2Text: "",
                          num3Text: "",
                          num4Text: "",
                          answer: 3),
            QuestionModel(num: 6,
                          questionText: "어법상 옳지 않은 것은?",
                          num1Text: "All assignments are expected to be turned in on time.",
                          num2Text: "Hardly had I closed my eyes when I began to think of her.",
                          num3Text: "The broker recommended that she buy the stocks immediately.",
                          num4Text: "A woman with the tip of a pencil stuck in her head has finally had it remove.",
                          answer: 4),
            QuestionModel(num: 7,
                          questionText: "우리말을 영어로 잘못 옮긴 것은?",
                          num1Text: "내 고양이 나이는 그의 고양이 나이의 세 배이다.\n→My cat is three times as old as his.",
                          num2Text: "우리는 그 일을 이번 달 말까지 끝내야 한다.\n→We have to finish the work until the end of this month.",
                          num3Text: "그녀는 이틀에 한 번 머리를 감는다.\n→She washes her hair every other day.",
                          num4Text: "너는 비가 올 경우에 대비하여 우산을 갖고 가는 게 낫겠다.\n→You had better take an umbrella in case it rains.",
                          answer: 2),
            QuestionModel(num: 8,
                          questionText: "다음 글의 내용과 일치하지 않는 것은?",
                          reference: "Are you getting enough choline? Chances are, this nutrient isn’t even on your radar. It’s time choline gets the attention it deserves. A shocking 90 percent of Americans aren’t getting enough choline, according to a recent study. Choline is essential to health at all ages and stages, and is especially critical for brain development. Why aren’t we getting enough? Choline is found in many different foods but in small amounts. Plus, the foods that are rich in choline aren’t the most popular: think liver, egg yolks and lima beans. Taylor Wallace, who worked on a recent analysis of choline intake in the United States, says, “There isn’t enough awareness about choline even among health-care professionals because our government hasn’t reviewed the data or set policies around choline since the late ’90s.”",
                          num1Text: "A majority of Americans are not getting enough choline.",
                          num2Text: "Choline is an essential nutrient required for brain development.",
                          num3Text: "Foods such as liver and lima beans are good sources of choline.",
                          num4Text: "The importance of choline has been stressed since the late ’90s in the U.S.",
                          answer: 4),
            QuestionModel(num: 9,
                          questionText: "다음 글의 내용과 일치하는 것은?",
                          reference: "Around 1700 there were, by some accounts, more than 2,000 London coffeehouses, occupying more premises and paying more rent than any other trade. They came to be known as penny universities, because for that price one could purchase a cup of coffee and sit for hours listening to extraordinary conversations. Each coffeehouse specialized in a different type of clientele. In one, physicians could be consulted. Others served Protestants, Puritans, Catholics, Jews, literati, merchants, traders, Whigs, Tories, army officers, actors, lawyers, or clergy. The coffeehouses provided England’s first egalitarian meeting place, where a man chatted with his tablemates whether he knew them or not.",
                          num1Text: "The number of coffeehouses was smaller than that of any other business.",
                          num2Text: "Customers were not allowed to stay for more than an hour in a coffeehouse.",
                          num3Text: "Religious people didn’t get together in a coffeehouse to chat.",
                          num4Text: "One could converse even with unknown tablemates in a coffeehouse",
                          answer: 4),
            QuestionModel(num: 10,
                          questionText: "밑줄 친 부분에 들어갈 말로 알맞은 것을 고르시오.",
                          reference: "A: I got this new skin cream from a drugstore yesterday. It is supposed to remove all wrinkles and make your skin look much younger.\n\nB: __________________________\n\nA: Why don’t you believe it? I’ve read in a few blogs that the cream really works.\n\nB: I assume that the cream is good for your skin, but I don’tthink that it is possible to get rid of wrinkles or magically look younger by using a cream.\n\nA: You are so pessimistic.\n\nB: No, I’m just being realistic. I think you are being gullible.",
                          num1Text: "I don’t buy it.",
                          num2Text: "It’s too pricey.",
                          num3Text: "I can’t help you out.",
                          num4Text: "Believe it or not, it’s true.",
                          answer: 1),
            QuestionModel(num: 11,
                          questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한것을 고르시오.",
                          reference: "A: I’d like to go sightseeing downtown. Where do you think I should go?\n\nB: I strongly suggest you visit the national art gallery.\n\nA: Oh, that’s a great idea. What else should I check out?\n\nB: _____________________________________________\n\nA: I don’t have time for that. I need to meet a client at three. B: Oh, I see. Why don’t you visit the national park, then? A: That sounds good. Thank you!",
                          num1Text: "This is the map that your client needs. Here you go.",
                          num2Text: "A guided tour to the river park. It takes all afternoon.",
                          num3Text: "You should check it out as soon as possible.",
                          num4Text: "The checkout time is three o’clock.",
                          answer: 2),
            QuestionModel(num: 12,
                          questionText: "두 사람의 대화 중 자연스럽지 않은 것은?",
                          num1Text: "A: He’s finally in a hit movie!\nB: Well, he’s got it made.",
                          num2Text: "A: I’m getting a little tired now.\nB: Let’s call it a day.",
                          num3Text: "A: The kids are going to a birthday party.\nB: So, it was a piece of cake.",
                          num4Text: "A: I wonder why he went home early yesterday.\nB: I think he was under the weather.",
                          answer: 3),
            QuestionModel(num: 13,
                          questionText: "다음 글의 제목으로 알맞은 것은?",
                          reference: "The feeling of being loved and the biological response it stimulates is triggered by nonverbal cues: the tone in a voice, the expression on a face, or the touch that feels just right. Nonverbal cues ―rather than spoken words ―make us feel that the person we are with is interested in, understands, and values us. When we’re with them, we feel safe. We even see the power of nonverbal cues in the wild. After evading the chase of predators, animals often nuzzle each other as a means of stress relief. This bodily contact provides reassurance of safety and relieves stress.",
                          num1Text: "How Do Wild Animals Think and Feel?",
                          num2Text: "Communicating Effectively Is the Secret to Success",
                          num3Text: "Nonverbal Communication Speaks Louder than Words",
                          num4Text: "Verbal Cues: The Primary Tools for Expressing Feelings",
                          answer: 3),
            QuestionModel(num: 14,
                          questionText: "다음 글의 주제로 알맞은 것은?",
                          reference: "There are times, like holidays and birthdays, when toys and gifts accumulate in a child’s life. You can use these times to teach a healthy nondependency on things. Don’t surround your child with toys. Instead, arrange them in baskets, have one basket out at a time, and rotate baskets occasionally. If a cherished object is put away for a time, bringing it out creates a delightful remembering and freshness of outlook. Suppose your child asks for a toy that has been put away for a while. You can direct attention toward an object or experience that is already in the environment. If you lose or break a possession, try to model a good attitude (“I appreciated it while I had it!”) so that your child can begin to develop an attitude of nonattachment. If a toy of hers is broken or lost, help her to say, “I had fun with that.”",
                          num1Text: "building a healthy attitude toward possessions",
                          num2Text: "learning the value of sharing toys with others",
                          num3Text: "teaching how to arrange toys in an orderly manner",
                          num4Text: "accepting responsibility for behaving in undesirable ways",
                          answer: 1),
            QuestionModel(num: 15,
                          questionText: "다음 글의 요지로 알맞은 것은?",
                          reference: "Many parents have been misguided by the “self-esteem movement,” which has told them that the way to build their children’s self-esteem is to tell them how good they are at things. Unfortunately, trying to convince your children of their competence will likely fail because life has a way of telling them unequivocally how capable or incapable they really are through success and failure. Research has shown that how you praise your children has a powerful influence on their development. Some researchers found that children who were praised for their intelligence, as compared to their effort, became overly focused on results. Following a failure, these same children persisted less, showed less enjoyment, attributed their failure to a lack of ability, and performed poorly in future achievement efforts. Praising children for intelligence made them fear difficulty because they began to equate failure with stupidity.",
                          num1Text: "Frequent praises increase self-esteem of children.",
                          num2Text: "Compliments on intelligence bring about negative effect.",
                          num3Text: "A child should overcome fear of failure through success.",
                          num4Text: "Parents should focus on the outcome rather than the process.",
                          answer: 2),
            QuestionModel(num: 16,
                          questionText: "밑줄 친 부분에 들어갈 말로 알맞은 것은?",
                          reference: "In recent years, the increased popularity of online marketing and social media sharing has boosted the need for advertising standardization for global brands. Most big marketing and advertising campaigns include a large online presence. Connected consumers can now zip easily across borders via the internet and social media, making it difficult for advertisers to roll out adapted campaigns in a controlled, orderly fashion. As a result, most global consumer brands coordinate their digital sites internationally. For example, Coca-Cola web and social media sites around the world, from Australia and Argentina to France, Romania, and Russia, are surprisingly __________. All feature splashes of familiar Coke red, iconic Coke bottle shapes, and Coca-Cola’s music and “Taste the Feeling” themes.",
                          num1Text: "experimental",
                          num2Text: "uniform",
                          num3Text: "localized",
                          num4Text: "diverse",
                          answer: 2),
            QuestionModel(num: 17,
                          questionText: "다음 글의 흐름상 어색한 문장은?",
                          reference: "In our monthly surveys of 5,000 American workers and 500 U.S. employers, a huge shift to hybrid work is abundantly clear for office and knowledge workers. "+"1)An emerging norm is three days a week in the office and two at home, cutting days on site by 30 % or more.".underLined+" You might think this cutback would bring a huge drop in the demand for office space. "+"2)But our survey data suggests cuts in office space of 1% to 2% on average, implying big reductions in density not space.".underLined+" We can understand why. High density at the office is uncomfortable and many workers dislike crowds around their desks. "+"3)Most employees want to work from home on Mondays and Fridays.".underLined+" Discomfort with density extends to lobbies, kitchens, and especially elevators. "+"4)The only sure-fire way to reduce density is to cut days on site without cutting square footage as much.".underLined+" Discomfort with density is here to stay according to our survey evidence.",
                          num1Text: "",
                          num2Text: "",
                          num3Text: "",
                          num4Text: "",
                          answer: 3),
            QuestionModel(num: 18, questionText: "주어진 문장이 들어갈 위치로 알맞은 것은?",
                          reference: "They installed video cameras at places known for illegal crossings, and put live video feeds from the cameras on a Web site.",
                          reference2: "Immigration reform is a political minefield. ( 1 ) About the only aspect of immigration policy that commands broad political support is the resolve to secure the U.S. border with Mexico to limit the flow of illegal immigrants. ( 2 ) Texas sheriffs recently developed a novel use of the Internet to help them keep watch on the border. ( 3 ) Citizens who want to help monitor the border can go online and serve as “virtual Texas deputies.” ( 4 ) If they see anyone trying to cross the border, they send a report to the sheriff’s office, which follows up, sometimes with the help of the U.S. Border Patrol.",
                          num1Text: "",
                          num2Text: "",
                          num3Text: "",
                          num4Text: "",
                          answer: 3),
            QuestionModel(num: 19,
                          questionText: "주어진 글 다음에 이어질 글의 순서로 알맞은 것은?",
                          reference: "All civilizations rely on government administration. Perhaps no civilization better exemplifies this than ancient Rome.",
                          reference2: "(A) To rule an area that large, the Romans, based in what is now central Italy, needed an effective system of government administration.\n\n(B) Actually, the word “civilization” itself comes from the Latin word civis, meaning “citizen.”\n\n(C) Latin was the language of ancient Rome, whose territory stretched from the Mediterranean basin all the way to parts of Great Britain in the north and the Black Sea to the east.",
                          num1Text: "(A) -(B) -(C)",
                          num2Text: "(B) -(A) -(C)",
                          num3Text: "(B) -(C) -(A)",
                          num4Text: "(C) -(A) -(B)",
                          answer: 3),
            QuestionModel(num: 20,
                          questionText: "밑줄 친 부분에 들어갈 말로 알맞은 것은?",
                          reference: "Over the last fifty years, all major subdisciplines in psychology have become more and more isolated from each other as training becomes increasingly specialized and narrow in focus. As some psychologists have long argued, if the field of psychology is to mature and advance scientifically, its disparate parts (for example, neuroscience, developmental, cognitive, personality, and social) must become whole and integrated again. Science advances when distinct topics become theoretically and empirically integrated under simplifying theoretical frameworks. Psychology of science will encourage collaboration among psychologists from various sub-areas, helping the field achieve coherence rather than continued fragmentation. In this way, psychology of science might act as a template for psychology as a whole by integrating under one discipline all of the major fractions/factions within the field. It would be no small feat and of no small import if the psychology of science could become a model for the parent discipline on how to combine resources and study science ______________________.",
                          num1Text: "from a unified perspective",
                          num2Text: "in dynamic aspects",
                          num3Text: "throughout history",
                          num4Text: "with accurate evidence",
                          answer: 1)
            
        ]
        let exam = ExamModel(id: 202312, year: 2023, examTypeID: "국가직", subjectID: "영어", questions: questions)
        exams2023.append(exam)
    }
    
    func saveExam202313() {
        let questions
        = [
            QuestionModel(num: 1,
                          questionText: "다음 유물이 사용된 시대에 대한 설명으로 옳은 것은?",
                          reference: "미송리식 토기, 팽이형 토기, 붉은 간 토기",
                          num1Text: "비파형 동검이 사용되었다.",
                          num2Text: "오수전 등의 화폐가 사용되었다.",
                          num3Text: "아슐리안형 주먹도끼가 사용되었다.",
                          num4Text: "철이 많이 생산되어 낙랑과 왜에 수출되었다.",
                          answer: 1),
            QuestionModel(num: 2,
                          questionText: "밑줄 친 ‘왕’에 대한 설명으로 옳은 것은?",
                          reference: "16년 겨울 10월, "+"왕".underLined+"이 질양(質陽)으로 사냥을 갔다가 길에 앉아 우는 자를 보았다. "+"왕".underLined+"이 말하기를 “아! 내가 백성의 부모가 되어 백성들이 이 지경에 이르게 하였으니 나의 죄로다.” ...(중략)... 그리고 관리들에게 명하여 매년 봄 3월부터 가을 7월까지 관청의 곡식을 내어 백성들의 식구 수에 따라 차등 있게 빌려주었다가, 10월에 이르러 상환하게 하는 것을 법규로 정하였다.\n\n - 삼국사기 -",
                          num1Text: "낙랑군을 축출하였다.",
                          num2Text: "'진대법'을 시행하였다",
                          num3Text: "백제의 침입으로 전사하였다.",
                          num4Text: "영락이라는 독자적인 연호를 사용하였다.",
                          answer: 2),
            QuestionModel(num: 3,
                          questionText: "(가)에 대한 설명으로 옳은 것은?",
                          reference: "신돈이 (가) 을/를 설치하자고 요청하자, ...(중략) ... 이제 도감이 설치되었다. ...(중략)... 명령이 나가자 권세가 중에 전민을 빼앗은 자들이 그 주인에게 많이 돌려주었으며, 전국에서 기뻐하였다.\n\n -고려사-",
                          num1Text: "시전의 물가를 감독하는 임무를 담당하였다.",
                          num2Text: "국가재정의 출납과 회계 업무를 총괄하였다.",
                          num3Text: "불법적으로 점유된 토지와 노비를 조사하였다.",
                          num4Text: "부족한 녹봉을 보충하고자 관료에게 녹과전을 지급하였다.",
                          answer: 3),
            QuestionModel(num: 4,
                          questionText: "다음과 같이 말한 인물에 대한 설명으로 옳은 것은?",
                          reference: "우리나라가 곧 고구려의 옛 땅이다. 그리고 압록강의 안팎 또한 우리의 지역인데 지금 여진이 그 사이에 몰래 점거하여 저항하고 교활하게 대처하고 있어서 ...(중략)... 만일 여진을 내쫓고 우리 옛 땅을 되찾아서 성보(城堡)를 쌓고 도로를 통하도록 하면 우리가 어찌 사신을 보내지 않겠는가?\n\n - 고려사 -",
                          num1Text: "목종을 폐위하였다.",
                          num2Text: "귀주에서 거란군을 물리쳤다.",
                          num3Text: "여진을 몰아내고 동북 9성을 쌓았다.",
                          num4Text: "소손녕과 담판하여 강동 6주를 획득하였다.",
                          answer: 4),
            QuestionModel(num: 5,
                          questionText: "밑줄 친 ‘이곳’에 대한 설명으로 옳은 것은?",
                          reference: "○ 장수왕은 남진정책의 일환으로 수도를 "+"이곳".underLined+"으로 천도하였다.\n○ 묘청은 "+"이곳".underLined+"으로 수도를 옮길 것을 주장하였다.",
                          num1Text: "쌍성총관부가 설치되었다.",
                          num2Text: "망이ᆞ망소이가 반란을 일으켰다.",
                          num3Text: "제너럴 셔먼호 사건이 발생하였다.",
                          num4Text: "1923년 조선 형평사가 결성되었다.",
                          answer: 3),
            QuestionModel(num: 6,
                          questionText: "다음 전투 이후에 일어난 사건으로 옳은 것만을 모두 고르면?",
                          reference: "이근행이 군사 20만 명의 대군을 이끌고 매소성(買肖城)에 머물렀다. 우리 군사가 공격하여 달아나게 하고 전마 30,380필을 얻었는데, 남겨놓은 병장기도 그 정도 되었다.\n\n- 삼국사기 -",
                          reference2: "ᄀ. 웅진도독부가 설치되었다.\nᄂ. 김흠돌이 반란을 일으켰다.\nᄃ. 교육 기관인 국학이 설립되었다.\nᄅ. 복신과 도침이 부여풍과 함께 백제 부흥 운동을 일으켰다.",
                          num1Text: "ㄱ,ㄴ",
                          num2Text: "ㄱ,ㄹ",
                          num3Text: "ㄴ,ㄷ",
                          num4Text: "ㄷ,ㄹ",
                          answer: 3),
            QuestionModel(num: 7,
                          questionText: "다음 사건을 시기순으로 바르게 나열한 것은?",
                          reference: "(가) 신라의 우산국 복속\n(나) 고구려의 서안평 점령\n(다) 백제의 대야성 점령\n(라) 신라의 금관가야 병합",
                          num1Text: "(가)→(나)→(다)→(라)",
                          num2Text: "(가)→(라)→(나)→(다)",
                          num3Text: "(나)→(가)→(라)→(다)",
                          num4Text: "(나)→(다)→(가)→(라)",
                          answer: 3),
            //MARK: - 2 answers
            QuestionModel(num: 8,
                          questionText: "고려시대 문화유산에 대한 설명으로 옳지 않은 것은?",
                          num1Text: "황해도 사리원 성불사 웅진전은 다포 양식의 건물이다.",
                          num2Text: "월정사 팔각 9층 석탑은 원의 석탑을 모방하여 제작하였다.",
                          num3Text: "여주 고달사지 승탑은 통일 신라의 팔각원당형 양식을 계승하였다.",
                          num4Text: "직지심체요절은 세계기록유산으로 등재된 현존하는 가장 오래된 금속활자본이다.",
                          answer: 1), // 1,2
            QuestionModel(num: 9,
                          questionText: "조선시대 지도와 천문도에 대한 설명으로 옳지 않은 것은?",
                          num1Text: "대동여지도는 거리를 알 수 있도록 10리마다 눈금을 표시하였다.",
                          num2Text: "혼일강리역대국도지도는 중국에서 들여온 곤여만국전도를 참고하였다.",
                          num3Text: "천상열차분야지도는 하늘을 여러 구역으로 나누고 별자리를 표시한 그림이다.",
                          num4Text: "동국지도는 정상기가 실제 거리 100리를 1척으로 줄인 백리척을 적용하여 제작하였다.",
                          answer: 3),
            QuestionModel(num: 10,
                          questionText: "(가)에 대한 설명으로 옳지 않은 것은?",
                          reference: "임진왜란 이후에 우의정 유성룡도 역시 미곡을 거두는 것이 편리하다고 주장하였으나, 일이 성취되지 못하였다. 1608년에 이르러 좌의정 이원익의 건의로 (가) 을/를 비로소 시행하여, 민결(民結)에서 미곡을 거두어 서울로 옮기게 하였다.\n\n - 만기요람 -",
                          num1Text: "장시의 확대에 기여하였다.",
                          num2Text: "지주에게 결작을 부과하였다.",
                          num3Text: "공납의 폐단을 막기 위해 실시하였다.",
                          num4Text: "공인에게 비용을 지급하고 필요 물품을 조달하였다.",
                          answer: 2),
            QuestionModel(num: 11,
                          questionText: "(가) 인물이 추진한 정책으로 옳지 않은 것은?",
                          reference: "선비들 수만 명이 대궐 앞에 모여 만동묘와 서원을 다시 설립할 것을 청하니, (가) 이/가 크게 노하여 한성부의 조례(皂隷)와 병졸로 하여금 한강 밖으로 몰아내게 하고 드디어 천여 곳의 서원을 철폐하고 그 토지를 몰수하여 관에 속하게 하였다.\n\n - 대한계년사 -",
                          num1Text: "사창제를 실시하였다.",
                          num2Text: "'대전회통'을 편찬하였다.",
                          num3Text: "비변사의 기능을 강화하였다.",
                          num4Text: "통상 수교 거부 정책을 추진하였다.",
                          answer: 3),
            QuestionModel(num: 12,
                          questionText: "다음과 같은 선포문을 발표하면서 성립한 정부의 정책으로 옳지 않은 것은?",
                          reference: "제1조 대한민국은 민주공화제로 함\n... (중략) ...\n민국 원년 3월 1일 우리 대한민족이 독립을 선언한 뒤 ...(중략) ... 이제 본 정부가 전 국민의 위임을 받아 조직되었으니 전 국민과 더불어 전심(專心)으로 힘을 모아 국토 광복의 대사명을 이룰 것을 선서한다.",
                          num1Text: "독립 공채를 발행하였다.",
                          num2Text: "기관지로 '독립신문'을 발간하였다.",
                          num3Text: "비밀 행정 조직인 연통부를 설치하였다.",
                          num4Text: "재정 확보를 위하여 전환국을 설립하였다.",
                          answer: 4),
            QuestionModel(num: 13,
                          questionText: "밑줄 친 ‘나’가 집권하여 추진한 사실로 옳은 것은?",
                          reference: "나".underLined+"는 우리 국민이 선천적으로 타고난 재질을 최대한으로 활용하여 다각적인 생산 활동을 더욱 활발하게 하고, ...(중략)... 공산품 수출을 진흥시키는 데 가일층 노력할 것을 요망합니다. 끝으로 "+"나".underLined+"는 오늘 제1회 수출의 날 기념식에 즈음하여 ...(중략)... 이 뜻깊은 날이 자립경제를 앞당기는 또 하나의 계기가 될 것을 기원합니다.",
                          num1Text: "대통령 직선제 개헌을 추진하였다.",
                          num2Text: "3ᆞ1 민주 구국 선언을 발표하였다.",
                          num3Text: "반민족 행위 특별 조사 위원회를 구성하였다.",
                          num4Text: "베트남 파병에 필요한 조건을 명시한 브라운 각서를 체결하였다.",
                          answer: 4),
            QuestionModel(num: 14,
                          questionText: "다음과 같이 상소한 인물이 속한 붕당에 대한 설명으로 옳은 것만을 모두 고르면?",
                          reference: "상소하여 아뢰기를, “신이 좌참찬 송준길이 올린 차자를 보았는데, 상복(喪服) 절차에 대하여 논한 것이 신과는 큰 차이가 있었습니다. 장자를 위하여 3년을 입는 까닭은 위로 ‘정체(正體)’가 되기 때문이고 또 전중(傳重: 조상의 제사나 가문의 법통을 전함)하기 때문입니다. ...(중략)... 무엇보다 중요한 것은 할아버지와 아버지의 뒤를 이은 ‘정체’이지, 꼭 첫째이기 때문에 참최 3년복을 입는 것은 아닙니다.”라고 하였다.\n\n- 현종실록 -",
                          reference2: "ᄀ. 기사환국으로 정권을 장악하였다.\nᄂ. 인조반정을 주도하여 집권세력이 되었다.\nᄃ. 정조 시기에 탕평정치의 한 축을 이루었다.\nᄅ. 이이와 성혼의 문인을 중심으로 형성되었다.",
                          num1Text: "ㄱ,ㄴ",
                          num2Text: "ㄱ,ㄷ",
                          num3Text: "ㄴ,ㄹ",
                          num4Text: "ㄷ,ㄹ",
                          answer: 2),
            QuestionModel(num: 15,
                          questionText: "(나) 시기에 일어난 사실로 옳은 것은?",
                          reference: "(가) 삼포왜란이 발발하였다.\n-> (나)\n->(다) 임진왜란이 발발하였다.",
                          num1Text: "을사사화가 일어났다.",
                          num2Text: "'경국대전'이 반포되었다.",
                          num3Text: "'향약집성방'이 편찬되었다.",
                          num4Text: "금속활자인 갑인자가 주조되었다.",
                          answer: 1),
            QuestionModel(num: 16,
                          questionText: "다음 법령이 시행된 시기에 있었던 사실로 옳은 것은?",
                          reference: "제1조 회사의 설립은 조선 총독의 허가를 받아야 한다.\n\n제5조 회사가 본령이나 본령에 따라 나오는 명령과 허가 조건을 위반하거나 공공질서와 선량한 풍속에 반하는 행위를 할 때 조선 총독은 사업의 정지, 지점의 폐쇄, 또는 회사의 해산을 명할 수 있다.",
                          num1Text: "산미 증식 계획이 폐지되었다.",
                          num2Text: "'국가 총동원법'이 제정되었다.",
                          num3Text: "원료 확보를 위한 남면북양 정책이 추진되었다.",
                          num4Text: "보통학교 수업 연한을 4년으로 정한 '조선교육령'이 공포되었다.",
                          answer: 4),
            QuestionModel(num: 17,
                          questionText: "다음과 같은 결의문에 근거하여 시행된 조치로 옳은 것은?",
                          reference: "소총회는 ...(중략)... 한국 인민의 대표가 국회를 구성하여 중앙정부를 수립할 수 있도록 선거를 시행함이 긴요하다고 여기며, 총회의 의결에 따라 국제연합 한국 임시위원단이 접근할 수 있는 지역에서 결의문 제2호에 기술된 계획을 시행함이 동 위원단에 부과된 임무임을 결의한다.",
                          num1Text: "미 군정청이 설치되었다.",
                          num2Text: "5ᆞ10 총선거가 실시되었다.",
                          num3Text: "좌우 합작 위원회가 구성되었다.",
                          num4Text: "미ᆞ소 공동 위원회가 개최되었다.",
                          answer: 2),
            QuestionModel(num: 18,
                          questionText: "(가), (나) 조약 사이의 시기에 있었던 사실로 옳은 것은?",
                          reference: "(가) 제10관 일본국 인민이 조선국 지정의 각 항구에 머무는 동안에 죄를 범한 것이 조선국 인민에 관계되는 사건일 때에는 일본국 관원이 재판한다.\n\n(나) 제4관 중국 상인이 조선의 양화진 및 한성에 영업소를 개설할 경우를 제외하고，각종 화물을 내륙으로 운반하여 상점을 차리고 파는 것을 허가하지 않는다. 단, 내륙행상이 필요한 경우 지방관의 허가서를 받아야 한다.",
                          num1Text: "개항장에서는 일본 화폐가 통용되었다.",
                          num2Text: "러시아가 압록강 유역의 산림 채벌권을 획득하였다.",
                          num3Text: "황국 중앙 총상회가 조직되어 상권 수호 운동을 전개하였다.",
                          num4Text: "함경도의 방곡령에 불복하여 일본 상인이 손해 배상을 요구하였다.",
                          answer: 1),
            QuestionModel(num: 19,
                          questionText: "밑줄 친 ‘14개 조목’에 해당하는 것만을 모두 고르면?",
                          reference: "이제부터는 다른 나라를 의지하지 않으며 융성하도록 나라의 발걸음을 넓히고 백성의 복리를 증진하여 자주독립의 터전을 공고하게 할 것입니다. ...(중략) ... 이에 저 소자는 "+"14개 조목".underLined+"의 홍범(洪範)을 하늘에 계신 우리 조종의 신령 앞에 맹세하노니, 우러러 조종이 남긴 업적을 잘 이어서 감히 어기지 않을 것입니다.",
                          reference2: "ᄀ. 탁지아문에서 조세 부과\nᄂ. 왕실과 국정 사무의 분리\nᄃ. 지계 발급을 위한 지계아문 설치\nᄅ. 대한 천일 은행 등 금융기관 설립",
                          num1Text: "ᄀ,ㄴ",
                          num2Text: "ㄱ,ㄹ",
                          num3Text: "ㄴ,ㄷ",
                          num4Text: "ㄷ,ㄹ",
                          answer: 1),
            QuestionModel(num: 20,
                          questionText: "(가) 시기에 볼 수 있었던 모습으로 옳지 않은 것은?",
                          reference: "민주사변 발생 - [ (가) ] - 태평양전쟁 발발",
                          num1Text: "을사늑약 체결",
                          num2Text: "정미 의병 발생",
                          num3Text: "오페르트 도굴 미수 사건",
                          num4Text: "조.미 수호 통상 조약 체결",
                          answer: 3)
        ]
        let exam = ExamModel(id: 202313, year: 2023, examTypeID: "국가직", subjectID: "한국사", questions: questions)
        exams2023.append(exam)
    }
    
    
    func saveExam202321() {
        let questions =
        [
            QuestionModel(num: 1,
                          questionText: "언어 예절로 가장 적절한 것은?",
                          num1Text: "지금부터 회장님의 말씀이 계시겠습니다.",
                          num2Text: "(시누이에게) 고모, 오늘 참 예쁘게 차려 입으셨네요?",
                          num3Text: "(처음 자신을 소개하면서) 처음 뵙겠습니다. 박혜정입니다.",
                          num4Text: "(다른 사람에게 자기 아내를 가리키며) 이쪽은 제 부인입니다.",
                          answer: 3),
            QuestionModel(num: 2,
                          questionText: "다음 글의 주된 서술 방식은?",
                          reference: " 이지러는 졌으나 보름을 가제 지난 달은 부드러운 빛을 흐붓이 흘리고 있다. 대화까지는 칠십 리의 밤길. 고개를 둘이나 넘고 개울을 하나 건너고, 벌판과 산길을 걸어야 된다. 길은 지금 긴 산허리에 걸려 있다. 밤중을 지난 무렵인지 죽은 듯이 고요한 속에서 짐승 같은 달의 숨소리가 손에 잡힐 듯이 들리며, 콩 포기와 옥수수 잎새가 한층 달에 푸르게 젖었다.",
                          num1Text: "묘사",
                          num2Text: "설명",
                          num3Text: "유추",
                          num4Text: "분석",
                          answer: 1),
            QuestionModel(num: 3,
                          questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                          reference: "연출자가 자신의 저작권을 침해당했다고 주장하기 위해서는 우선 그가 유효한 저작권을 소유하고 있어야 한다. 즉 저작권 보호 가능성이 있는 창작물이 필요하다. 다음으로 창작적인 표현을 도용당했는지 밝혀야 하는데, 이것이 쉽지 않다. 왜냐하면 연출자가 주관적으로 창작성이 있다고 느끼는 부분일지라도 객관적인 시각에서는 이미 공연 예술 무대에서 흔히 사용되는 표현 기법일 수 있고, 저작권법상 보호 대상이 아닌 아이디어의 요소와 보호 가능한 요소인 표현이 얽혀 있는 경우가 있기 때문이다. 쉬운 예로 셰익스피어를 보자. 그의 명작 중에 선대에 있었던 작품에 의거하지 않고 탄생한 작품이 있는가. 대부분의 연출자는 선행 예술가로부터 영향을 받아 창작에 임하는 것이 너무도 당연하고 자연스럽다. 따라서 무대연출 작업 중에서 독보적인 창작을 걸러내서 배타적인 권한인 저작권을 부여하는 것은 매우 흔치 않은 경우이고, 후발 창작을 방해하는 요소로 작용할 수도 있다. 저작권법은 창작자에게 개인적인 인센티브를 제공하여 창작을 장려함과 동시에 일반 공중이 저작물을 원활하게 이용할 수 있도록 해야 하는 두 가지 가치의 균형을 이루는 것이 목표다.",
                          num1Text: "무대연출의 창작적인 표현의 도용 여부를 밝히기는 쉽지 않다.",
                          num2Text: "저작권 침해를 당했다고 주장하려면 유효한 저작권을 소유하고 있어야 한다.",
                          num3Text: "독보적인 무대연출 작업에 저작권을 부여한다고 해서 후발 창작에 방해가 되지는 않는다.",
                          num4Text: "저작권법의 목표는 창작자의 창작을 장려하고 일반 공중의 저작물 이용을 원활하게 하는 것이다.",
                          answer: 3),
            QuestionModel(num: 4,
                          questionText: "㉠~㉣의 고쳐쓰기로 적절하지 않은 것은?",
                          reference: " 파놉티콘(panopticon)은 원형 평면의 중심에 감시탑을 설치해 놓고, 주변으로 빙 둘러서 죄수들의 방이 배치된 감시 시스템이다. 감시탑의 내부는 어둡게 되어 있는 반면 죄수들의 방은 밝아 교도관은 죄수를 볼 수 있지만, 죄수는 교도관을 바라볼 수 없다. 죄수가 잘못했을 때 교도관은 잘 보이는 곳에서 처벌을 가한다. 그렇게 수차례의 처벌이 있게 되면 죄수들은 실제로 교도관이 자리에 ㉠" + "있을".underLined + " 때조차도 언제 처벌을 받을지 모르는 공포감에 의해서 스스로를 감시하게 된다. 이렇게 권력자에 의한 정보 독점 아래 ㉡" + "다수".underLined + "가 통제된다는 점에서 파놉티콘의 디자인은 과거 사회 구조와 본질적으로 같았다.\n 현대사회는 다수가 소수의 권력자를 동시에 감시할 수 있는 시놉티콘(synopticon)의 시대가 되었다. 시놉티콘에 가장 크게 기여한 것은 인터넷의 ㉢" + "동시성".underLined + "이다. 권력자에 대한 비판을 신변 노출 없이 자유롭게 표현할 수 있게 되었기 때문이다. 정보화 시대가 오면서 언론과 통신이 발달했고, ㉣" + "특정인이".underLined + " 정보를 수용하고 생산하게 되었다. 그로 인해 사회에서 일어나는 일에 대한 비판적 인식 교류와 부정적 현실 고발 등 네티즌의 활동으로 권력자들을 감시하는 전환이 일어났다.",
                          num1Text: "㉠을 ‘없을’로 고친다.",
                          num2Text: "㉡을 ‘소수’로 고친다.",
                          num3Text: "㉢을 ‘익명성’으로 고친다.",
                          num4Text: "㉣을 ‘누구나가’로 고친다.",
                          answer: 2),
            QuestionModel(num: 5,
                          questionText: "㉠~㉣에 대한 이해로 가장 적절한 것은?",
                          reference: "㉠" + "산(山)새".underLined + "도 오리나무\n위에서 운다\n산새는 왜 우노, 시메산골\n영(嶺) 넘어가려고 그래서 울지\n\n눈은 내리네, 와서 덮이네\n오늘도 하룻길은\n㉡" + "칠팔십리(七八十里)".underLined + "\n돌아서서 육십 리는 가기도 했소\n\n㉢" + "불귀(不歸), 불귀, 다시 불귀".underLined + "\n삼수갑산에 다시 불귀\n사나이 속이라 잊으련만\n십오 년 정분을 못 잊겠네\n\n산에는 오는 눈, 들에는 녹는 눈\n\n산새도 오리나무\n㉣" + "위에서 운다".underLined + "\n삼수갑산 가는 길은 고개의 길\n\n-김소월, 〖산〗-",
                          num1Text: "㉠은 시적 화자와 상반되는 처지에 놓여 있다.",
                          num2Text: "㉡은 시적 화자에게 놓인 방랑길을 비유한다.",
                          num3Text: "㉢은 시적 화자의 이국 지향 의식을 강조한다.",
                          num4Text: "㉣은 시적 화자가 지닌 분노의 정서를 대변한다.",
                          answer: 2),
            QuestionModel(num: 6,
                          questionText: "다음 글에 대한 감상으로 적절하지 않은 것은?",
                          reference: " “같이 가시지. 내 보기엔 좋은 여자 같군.”\n “그런 거 같아요.”\n “또 알우? 인연이 닿아서 말뚝 박구 살게 될지. 이런 때 아주 뜨내기 신셀 청산해야지.”\n 영달이는 시무룩해져서 역사 밖을 멍하니 내다보았다. 백화는 뭔가 쑤군대고 있는 두 사내를 불안한 듯이 지켜보고 있었다. 영달이가 말했다.\n “어디 능력이 있어야죠.”\n “삼포엘 같이 가실라우?”\n “어쨌든.......”\n 영달이가 뒷주머니에서 꼬깃꼬깃한 오백 원짜리 두 장을 꺼냈다.\n “저 여잘 보냅시다.”\n 영달이는 표를 사고 삼립빵 두 개와 찐 달걀을 샀다. 백화에게 그는 말했다.\n “우린 뒤차를 탈 텐데....... 잘 가슈.”\n 영달이가 내민 것들을 받아 쥔 백화의 눈이 붉게 충혈되었다. 그 여자는 더듬거리며 물었다.\n “아무도...... 안 가나요?”\n “우린 삼포루 갑니다. 거긴 내 고향이오.”\n 영달이 대신 정 씨가 말했다. 사람들이 개찰구로 나가고 있었다. 백화가 보퉁이를 들고 일어섰다.\n “정말, 잊어버리지...... 않을게요.”\n 백화는 개찰구로 가다가 다시 돌아왔다. 돌아온 백화는 눈이 젖은 채로 웃고 있었다.\n “내 이름 백화가 아니에요. 본명은요...... 이점례예요.”\n 여자는 개찰구로 뛰어나갔다. 잠시 후에 기차가 떠났다.\n\n -황석영, 〖삼포가는길〗에서-",
                          num1Text: "정 씨는 영달이 백화와 함께 떠날것을 권유했군.",
                          num2Text: "백화는 영달의 선택이 어떤 것일지 몰라 불안했군.",
                          num3Text: "영달은 백화를 신뢰할 수 없었기 때문에 같이 떠나지 않았군.",
                          num4Text: "백화가 자신의 본명을 말한 것은 정 씨와 영달에 대한 고마움의 표현이었군.",
                          answer: 3),
            QuestionModel(num: 7,
                          questionText: "다음 글의 전개순서로 가장 자연스러운 것은?",
                          reference: "(가) 과거에는 고통만을 안겨 주었던 지정학적 조건이 이제는 희망의 조건이 되고 있습니다. 이제 한반도는 사람과 물자가 모여드는 동북아 물류와 금융, 비즈니스의 중심지가 될 것입니다. 우리가 주도해서 평화와 번영의 동북아 시대를 열어 나가야 합니다.\n\n(나) 100년 전 우리는 수난과 비극의 역사를 겪었습니다. 해양으로 나가려는 세력과 대륙으로 진출하려는 세력이 한반도를 가운데 놓고 싸움을 벌였습니다. 마침내 우리는 국권을 상실하는 아픔을 감수해야 했습니다.\n\n(다) 지금은 무력이 아니라 경제력이 국력을 좌우하는 시대입니다. 우리나라는 전쟁의 폐허를 극복하고 세계적인 경제 강국을 건설하고 있습니다. 우수한 인력과 세계 선두권의 정보화 기반을 갖추고 있습니다. 바다와 하늘과 땅을 연결하는 물류 기반도 손색이 없습니다.\n\n(라) 그 아픔은 분단으로 이어져서 오늘에 이르고 있습니다. 그 과정에서는 정의가 패배하고 기회주의가 득세하는 불행한 역사를 겪었습니다. 그러나 이제 우리에게도 새로운 희망의 시대가 열리고 있습니다. 세계의 변방으로 머물러 왔던 동북아시아가 북미.유럽 지역과 함께 세계 경제의 3대 축으로 떠오르고 있습니다.",
                          num1Text: "(가)-(나)-(다)-(라)",
                          num2Text: "(가)-(라)-(나)-(다)",
                          num3Text: "(나)-(가)-(라)-(다)",
                          num4Text: "(나)-(라)-(다)-(가)",
                          answer: 4),
            QuestionModel(num: 8,
                          questionText: "다음 대화에 대한 설명으로 가장 적절한 것은?",
                          reference: "A: 예은 씨. 오늘 회의 내용을 팀원들에게 공유해 주시면 좋겠네요.\n\nB: 네. 알겠습니다. 팀장님, 오늘 회의 내용을 요약 정리해서 메일로 공유하면 되겠지요?\n\nA: (고개를 끄덕이며) 맞습니다.\n\nB: 네. 그럼 회의 내용은 개조식으로 요약하고, 팀장님을 포함해서 전체 팀원에게 메일로 보내도록 하겠습니다.\n\nA: 예은 씨. 그런데 개조식으로 회의 내용을 요약하는 방식에는 문제가 있지 않을까요?\n\nB: (고개를 끄덕이며) 그렇겠네요. 개조식으로 요약할 경우 회의 내용이 과도하게 생략되어 이해가 어려울 수 있겠네요.",
                          num1Text: "A는 B에게 내용 요약 방식을 제안하고 있다.",
                          num2Text: "A와 B는 대화 중에 공감의 표지를 드러내며 상대방의 말을 듣고 있다.",
                          num3Text: "B는 회의 내용 요약 방식에 대한 A의 문제 제기에 대해 자신이 다른 입장임을 드러내고 있다.",
                          num4Text: "A는 개조식 요약 방식이 회의 내용을 과도하게 생략하여 이해에 어려움을 줄 수 있다고 명시하고 있다.",
                          answer: 2),
            QuestionModel(num: 9,
                          questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                          reference: "  올해 A시는 ‘청소년 의회 교실’ 운영에 관한 조례를 발표함 으로써 청소년들이 지방의회의 역할과 기능을 이해하고 민주 시민으로서의 소양과 자질을 함양할 수 있는 근거를 마련하였다. 청소년 의회 교실이란 청소년을 대상으로 실시하는 의회 체험 프로그램을 의미한다. 여기에 참여할 수 있는 대상은 A시에 있는 학교에 재학 중인 만 19세 미만의 청소년이다. 이 조례에 따르면 시의회 의장은 의회 교실의 참가자 선정 및 운영 방안을 결정할 수 있다. 운영방안에는 지방자치 및 의회의 기능과 역할, 민주 시민의 소양과 자질 등에 관한 교육 내용이 포함된다. 또한 시의회 의장은 고유 권한으로 본회의장 시설 사용이 가능하도록 지원할 수있다. 최근A시는‘수업시간 스마트폰 사용 제한에 관한 조례안’을 주제로 본회의장에서 첫 번째 의회 교실을 운영 하였다. 참석 학생들은 1일 시의원이 되어 의원 선서를 한 후 주제에 관한 자유 발언 시간을 가졌다. 이어서 관련 조례안을 상정한 후 찬반 토론을 거쳐 전자 투표로 표결 처리하였다. 학생들이 의회 과정 전반에 대해 체험할 수 있었던 뜻깊은 시간이었다.",
                          num1Text: "A시에 있는 학교의 만 19세 미만 재학생은 청소년 의회 교실에 참여할 수 있는 대상이다.",
                          num2Text: "A시의 시의회 의장은 청소년 의회 교실의 민주 시민 소양과 관련된 교육 내용을 결정할 수 있다.",
                          num3Text: "A시에서 시행된 청소년 의회 교실에서 시의회 의장은 본회 의장 시설을 사용하도록 지원해 주었다.",
                          num4Text: "A시의 올해 청소년 의회 교실은 의원선서, 조례안상정, 자유 발언, 찬반 토론, 전자 투표의 순서로 진행되었다.",
                          answer: 4),
            QuestionModel(num: 10,
                          questionText: "단어에 대한 설명으로 적절하지 않은 것은?",
                          num1Text: "가난: 한자어 ‘간난’에서 ‘ᄂ’이 탈락하면서 된 말이다.",
                          num2Text: "어리다: ‘어리석다’는 뜻에서 ‘나이가 적다’는 뜻으로 바뀐 말이다.",
                          num3Text: "수탉: ‘ᄒ’을 종성으로 갖고 있던 ‘숳’에 ‘’이 합쳐져 이루어진 말이다.",
                          num4Text: "점잖다: ‘의젓함’을 나타내는 ‘점잖이’에 ‘하다’가 붙어 형성된 말이다.",
                          answer: 4),
            QuestionModel(num: 11,
                          questionText: "다음 글의 주제로 가장 적절한 것은?",
                          reference: " 예전에 ‘혐오’는 대중에게 관심을 끄는 말이 아니었지만, 요즘에는 익숙하게 듣는 말이 되었다. 이는 과거에 혐오가 존재하지 않았다는 말이 아니다. 단지 최근 몇 년 사이에 이 문제가 폭발하듯 가시화되었다는 뜻이다. 혐오 현상은 외계에서 뚝 떨어진 괴물이 만들어 낸 것이 아니라, 거기엔 자체의 역사와 사회적 배경이 반드시 선행한다.\n 이 문제를 바라볼 때 주의 사항이 있다. 혐오나 증오라는 특정 감정에 집착해선 안 된다는 것이다. 혐오가 주제인데 거기에 집중하지 말라니, 얼핏 이율배반처럼 들리지만 이는 매우 중요한 포인트다. 왜 혐오가 나쁘냐고 물어보면 많은 사람들은 이렇게 답한다. “나쁜 감정이니까 나쁘다.”, “약자와 소수자를 차별하게 만드니까 나쁘다.” 이 대답들은 분명 선량한 마음에서 나온 것이다. 하지만 문제의 성격을 오인하게 만들 수 있다. 혐오나 증오라는 감정에 집중할수록 우린 ‘달을 가리키는 손가락만 바라보는’ 잘못을 범하기 쉬워진다.\n 인과관계를 혼동하면 곤란하다. 우리가 문제시하고 있는 각종 혐오는 자연 발생한 게 아니라 사회적으로 형성된 감정이다. 사회문제의 기원이나 원인이 아니라, 발현이며 결과다. 더 정확히 말하자면 혐오는 증상이다. 증상을 관찰하는 일은 중요하지만 거기에만 매몰되면 곤란하다. 우리는 혐오나 증오 그 자체를 사회악으로 지목해 도덕적으로 지탄하는 데서 그치지 말아야 한다.",
                          num1Text: "혐오 현상에는 인과관계가 존재하지 않는다.",
                          num2Text: "혐오 현상은 선량한 마음으로 바라보아야 한다.",
                          num3Text: "혐오 현상을 만들어 내는 근본원인을 찾아야한다.",
                          num4Text: "혐오라는 감정에 집중할수록 사회문제는 잘 보인다.",
                          answer: 3),
            QuestionModel(num: 12,
                          questionText: "㉠~㉣에 대한 이해로 적절하지 않은 것은?",
                          reference: "有此茅亭好 이 멋진 ㉠" + "초가 정자".underLined + " 있고 \n綠林細徑通 수풀 사이로 오솔길 나 있네\n微吟一杯後 술 한 잔 하고 시를 읊조리면서\n高座百花中 온갖 꽃 속에서 ㉡" + "높다랗게".underLined + " 앉아 있네\n丘壑長看在 산과 계곡은 언제 봐도 그대로건만\n樓臺盡覺空 ㉢누대는 하나같이 비어 있구나\n莫吹紅一點 붉은 꽃잎 하나라도 흔들지 마라\n老去惜春風 늙어갈수록 ㉣" + "봄바람".underLined + "이 안타깝구나\n\n-심환지, 〖육각지하화원소정염운(六閣之下花園小亭拈韻)〗-",
                          num1Text: "㉠: 시간적 흐름에 따른 시상전개를 매개하고 있다.",
                          num2Text: "㉡: 시적 화자의 초연한 태도를 드러내고 있다.",
                          num3Text: "㉢: 자연에 대비되는 쇠락한 인간사를 암시하고 있다.",
                          num4Text: "㉣: 꽃잎을 흔드는 부정적 이미지로 기능하고 있다.",
                          answer: 1),
            QuestionModel(num: 13,
                          questionText: "밑줄 친 단어 중 사람의 몸을 지시하는 말이 포함되지 않은 것은?",
                          num1Text: "선생님께서는 " + "슬하".underLined + "에 세 명의 자녀를 두셨다고 한다.",
                          num2Text: "그는 " + "수완".underLined + "이 좋아서 사람들에게 인정을 받는다.",
                          num3Text: "여러 팀이 우승을 위해 긴 시간 동안 " + "각축".underLined + "을 벌였다.",
                          num4Text: "사업단의 " + "발족".underLined + "으로 미뤄 뒀던 일들이 진행되기 시작했다.",
                          answer: 3),
            QuestionModel(num: 14,
                          questionText: "㉠과 ㉡에 대한 설명으로 가장 적절한 것은?",
                          reference: "(가) ㉠" + "계월".underLined + "이 여자 옷을 벗고 갑옷과 투구를 갖춘 후 용봉황월(龍鳳黃鉞)과 수기를 잡아 행군해 별궁에 자리를 잡았다. 그리고 군사를 시켜 보국에게 명령을 전하니 보국이 전해져 온 명령을 보고 화가 머리끝까지 났다. 그러나 보국은 예전에 계월의 위엄을 보았으므로 명령을 거역하지 못해 갑옷과 투구를 갖추고 군문에 대령했다.\n 이때 계월이 좌우를 돌아보며 말했다.\n “보국이 어찌 이다지도 거만한가? 어서 예를 갖추어 보이라.”\n 호령이 추상과 같으니 군졸의 대답 소리로 장안이 울릴 정도였다. 보국이 그 위엄을 보고 겁을 내어 갑옷과 투구를 끌고 몸을 굽히고 들어가니 얼굴에서 땀이 줄줄 흘러내렸다.\n\n -작자 미상, 〖홍계월천〗에서-\n\n(나) 장끼 고집 끝끝내 굽히지 아니하여 ㉡" + "까투리".underLined + " 홀로 경황없이 물러서니, 장끼란 놈 거동 보소. 콩 먹으러 들어갈 제 열두 장목 펼쳐 들고 꾸벅꾸벅 고개 조아 조츰조츰 들어가서 반달 같은 혀뿌리로 들입다 꽉 찍으니, 두 고패 둥그레지며 ...(중략)... 까투리 하는 말이\n “저런 광경 당할 줄 몰랐던가. 남자라고 여자의 말 잘 들어도 패가하고, 계집의 말 안 들어도 망신하네.”\n 까투리 거동 볼작시면, 상하평전 자갈밭에 자락머리 풀어 놓고 당굴당굴 뒹굴면서 가슴치고 일어앉아 잔디풀을 쥐어뜯어 애통하며, 두 발로 땅땅 구르면서 붕성지통(崩城之痛) 극진하니, 아홉 아들 열두 딸과 친구 벗님네들도 불쌍타 의논하며 조문 애곡하니 가련 공산 낙망천에 울음소리뿐이로다.\n\n -작자미상, 〖장끼전〗에서-",
                          num1Text: "㉠과 ㉡은 모두 상대에 비해 우월한 지위를 가지고있다.",
                          num2Text: "㉠이 상대의 행동을 비판하는 반면, ㉡은 옹호하고 있다.",
                          num3Text: "㉠이 갈등 상황을 타개하는 데 적극적인 반면, ㉡은 소극적이다.",
                          num4Text: "㉠이 주변으로부터 호의적인 반응을 얻은 반면, ㉡은 적대적인 반응을 얻는다.",
                          answer: 3),
            QuestionModel(num: 15,
                          questionText: "밑줄 친 말의 쓰임이 올바른 것은?",
                          num1Text: "습관처럼 중요한 말을 " + "되뇌이는".underLined + " 버릇이 있다.",
                          num2Text: "나는 친구 집을 찾아 골목을 " + "헤매이고".underLined + " 다녔다.",
                          num3Text: "너무 급하게 밥을 먹으면 목이 " + "메이기".underLined + " 마련이다.",
                          num4Text: "그는 어린 시절 기계에 손가락이 " + "끼이는".underLined + " 사고를 당했다.",
                          answer: 4),
            QuestionModel(num: 16,
                          questionText: "밑줄 친 부분의 한자 표기가 옳지 않은 것은?",
                          num1Text: "우리 시대 영웅으로 " + "소방관(消防官)".underLined + "이 있다.",
                          num2Text: "과학자(科學者)".underLined + "는 청소년들이 선망하는 직업이다.",
                          num3Text: "그는 인공지능 연구소의 " + "연구원(硏究員)".underLined + "이 되었다.",
                          num4Text: "그는 법원의 명령에 따라 " + "변호사(辯護事)".underLined + "로 선임되었다.",
                          answer: 4),
            QuestionModel(num: 17,
                          questionText: "다음 글에 대한 이해로 적절하지 않은 것은?",
                          reference: " 르네상스가 일어나게 된 요인으로 많은 것들이 거론되어 왔지만, 의학사의 관점에서 볼 때 흥미롭고 논쟁적인 원인은 페스트이다. 페스트가 유럽의 인구를 격감시킴으로써 사회 경제 구조가 급변하게 되었고, 사람들은 재래의 전통이 지니고 있던 강력한 권위에 의문을 품기 시작했다. 예컨대 사람들은 이 무시무시한 질병을 예측하지 못한 기존의 의학적 전통을 불신하게 되었으며, 페스트로 인해 ‘사악한 자’ 들만이 아니라 ‘선량한 자’들까지 무차별적으로 죽는 것을 보고 이전까지 의심하지 않았던 신과 교회의 막강한 권위에 대해서도 회의하게 되었다.\n 속수무책으로 당할 수밖에 없었던 죽음에 대한 경험은 사람들을 여러 방향에서 변화시켰다. 사람들은 거리에 시체가 널려 있는 광경에 익숙해졌고, 인간의 유해에 대한 두려움 또한 점차 옅어졌다. 교회에서 제시한 세계관 및 사후관에 대한 신뢰가 떨어지고, 삶과 죽음 같은 인간의 본질적인 문제에 대해 새롭게 사유하기 시작했다. 중세의 지적 전통에 대한 의구심은 고대의 학문과 예술, 언어에 대한 재평가로 이어졌으며, 이에 따라 신에 대한 무조건적 찬양과 복종 대신 인간에 대한 새로운 관심과 사유가 활발해졌다.\n 이러한 움직임은 미술사에서 두드러지게 포착된다. 인간에 대한 관심의 증대에 따라 인체의 아름다움이 재발견되었고, 인체를 묘사하는 다양한 화법도 등장했다. 인체에 대한 관심은 보이는 부분뿐만 아니라 보이지 않는 부분에 대한 관심으로 이어졌다. 기존의 의학적 전통을 여전히 신봉하던 의사들에게 해부학적 지식은 불필요한 것으로 인식되었던 반면, 당시의 미술가들은 예술가이면서 동시에 해부학자이기도 할 만큼 인체의 내부 구조를 탐색하는 데 골몰했다.",
                          num1Text: "전염병의 창궐은 르네상스의 발생을 설명하는 다양한 요인 가운데 하나이다.",
                          num2Text: "페스트로 인한 선인과 악인의 무차별적인 죽음은 교회가 유지하던 막강한 권위를 약화시켰다.",
                          num3Text: "예술가들이 인체의 아름다움을 재발견함으로써 고대의 학문과 언어에 대한 재평가도 이루어졌다.",
                          num4Text: "르네상스 시기에 해부학은 의사들보다도 미술가들의 관심을 끌었다.",
                          answer: 3),
            QuestionModel(num: 18,
                          questionText: "밑줄 친 부분에 어울리는 한자 성어로 가장 적절한 것은?",
                          reference: "추사 김정희의 ‘세한도’는 글씨를 쓰다 남은 먹을 버리기 아까워 그린 듯이 갈필(渴筆)의 거친 선 몇 개로 이루어져 있다. 정말 큰 기교는 겉으로 보기에는 언제나 서툴러 보이는 법이다. 그러나 대가의 덤덤한 듯, " + "툭 던지는 한마디는 예리한 비수가 되어 독자의 의식을 헤집는다.".underLined,
                          num1Text: "巧言令色",
                          num2Text: "寸鐵殺人",
                          num3Text: "言行一致",
                          num4Text: "街談巷說",
                          answer: 2),
            QuestionModel(num: 19,
                          questionText: "다음 글에서 추론한 내용으로 가장 적절한 것은?",
                          reference: " 논리실증주의자들에 따르면, 만약 어떤 것이 과학일 경우 거기에서 사용되는 문장은 유의미하다. 그들은 유의미한 문장의 기준으로 소위 ‘검증 원리’라고 불리는 것을 제안했다. 검증 원리란, 경험을 통해 참이나 거짓을 검증할 수 있는 문장은 유의미하고 그렇지 않은 문장은 유의미하지 않다는 것이다. 다음 두 문장을 예로 생각해 보자.\n(가) 달의 다른 쪽 표면에 산이 있다.\n  (나)  절대자는 진화와 진보에 관계하지만, 그 자체는 진화하거나 진보하지 않는다.\n위 두 문장 중 경험을 통해 검증할 수 있는 것은 무엇인가? 비록 현실적으로 큰 비용이 들기는 하지만 (가)는 분명히 경험을 통해 진위를 밝힐 수 있다. 즉 우리는   (가)  의 진위를 확정하기 위해서 무엇을 경험해야 하는지 알고 있다는 것이다. 이런 점에 근거하여 논리실증주의자들은  (가)  는 검증할 수 있고, 유의미한 문장이라고 판단한다. 그럼  (나)  는 어떠한가? 우리는 무엇을 경험해야  (나)  의 진위를 확정할 수 있는가? 논리실증주의자들은 그런 것은 없다고 주장하고, 이에 (나)는 검증할 수 없고 과학에서 사용될 수 없는 무의미한 문장이라고 말한다.",
                          num1Text: "논리실증주의자들에 따르면 무의미한 문장을 사용하는 것은 과학이 아니다.",
                          num2Text: "논리실증주의자들에 따르면 과학의 문장들만이 유의미하다.",
                          num3Text: "검증 원리에 따르면 아직까지 경험되지 않은 것을 언급한 문장은 무의미하다.",
                          num4Text: "검증 원리에 따르면 거짓인 문장은 무의미하다.",
                          answer: 1),
            QuestionModel(num: 20,
                          questionText: "다음 글에서 추론할 수 있는 것만을 <보기>에서 모두 고르면?",
                          reference: " 컴퓨터에는 자유의지가 있을까? 나아가 컴퓨터에 도덕적 의무를 귀속시킬 수 있을까? 컴퓨터는 다양한 전기회로로 구성되어 있고, 물리법칙, 프로그래밍 방식, 하드웨어의 속성 등에 따라 필연적으로 특정한 초기 상태로부터 다음 상태로 넘어간다. 마찬가지로 두 번째 상태에서 세 번째 상태로 이동하고, 이러한 과정이 계속해서 이어진다. 즉 컴퓨터는 결정론적 법칙의 지배를 받는 시스템이라는 것이다. 그럼 이러한 시스템에는 자유의지가 있을까?\n 결정론적 법칙의 지배를 받는 시스템의 중요한 특징은 주어진 조건에 따라 결과가 하나로 고정된다는 점이다. 다시 말해, 이러한 시스템에는 항상 하나의 선택지만 있을 뿐이다. 그런 뜻에서 결정론적 지배를 받는다는 것과 자유의지를 가진다는 것은 양립할 수 없음이 분명하다. 어떤 선택을 할 때 그것과 다른 선택을 할 수도 있다는 것은 자유의지의 필요조건이기 때문이다. 결국 결정론적 법칙의 지배를 받는 시스템은 자유의지를 가지지 않는다. 또한 자유의지를 가지지 않는 시스템에 도덕적 의무를 귀속시킬 수 없음은 당연하다.",
                          reference2: "ᄀ. 컴퓨터는 자유의지를 가지지 않으며 도덕적 의무의 귀속 대상일 수도 없다.\n\nᄂ. 도덕적 의무를 귀속시킬 수 있는 시스템은 결정론적 법칙의 지배를 받지 않는다.\n\nᄃ. 어떤 선택을 할 때 그것과 다른 선택을 할 수 없는 시스템은 자유의지를 가지지 않는다.",
                          num1Text: "ᄀ,ᄂ",
                          num2Text: "ᄀ,ᄃ",
                          num3Text: "ᄂ,ᄃ",
                          num4Text: "ᄀ,ᄂ,ᄃ",
                          answer: 4)
            
        ]
        let exam = ExamModel(id: 202321, year: 2023, examTypeID: "지방직", subjectID: "국어", questions: questions)
        exams2023.append(exam)
    }
    
    func saveExam202322() {
        let questions = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 부분의 의미와 가장 가까운것을 고르시오. [1~3]",
                      reference: "School teachers have to be " + "flexible".underLined + " to cope with different ability levels of the students.",
                      num1Text: "strong",
                      num2Text: "adaptable",
                      num3Text: "honest",
                      num4Text: "passionate",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "",
                      reference: "Crop yields " + "vary,".underLined + " improving in some areas and falling in others.",
                      num1Text: "change",
                      num2Text: "decline",
                      num3Text: "expand",
                      num4Text: "include",
                      answer: 1),
        QuestionModel(num: 3,
                      questionText: "",
                      reference: "I don’t feel inferior to anyone " + "with respect to".underLined + " my education.",
                      num1Text: "in danger of",
                      num2Text: "in spite of",
                      num3Text: "in favor of",
                      num4Text: "in terms of",
                      answer: 4),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "Sometimes we ______ money long before the next payday.",
                      num1Text: "turn into",
                      num2Text: "start over",
                      num3Text: "put up with",
                      num4Text: "run out of",
                      answer: 4),
        QuestionModel(num: 5,
                      questionText: "어법상 옳지 않은 것을 고르시오.[5~6]",
                      num1Text: "He asked me why I kept coming back day after day.",
                      num2Text: "Toys children wanted all year long has recently discarded.",
                      num3Text: "She is someone who is always ready to lend a helping hand.",
                      num4Text: "Insects are often attracted by scents that aren’t obvious to us.",
                      answer: 2),
        QuestionModel(num: 6,
                      questionText: "",
                      num1Text: "You can write on both sides of the paper.",
                      num2Text: "My home offers me a feeling of security, warm, and love.",
                      num3Text: "The number of car accidents is on the rise.",
                      num4Text: "Had I realized what you were intending to do, I would have stopped you.",
                      answer: 2),
        QuestionModel(num: 7,
                      questionText: "우리말을 영어로 잘못 옮긴 것을 고르시오.[7~8]",
                      num1Text: "나는 단 한푼의 돈도 낭비할 수 없다.\n→I can afford to waste even one cent.",
                      num2Text: "그녀의 얼굴에서 미소가 곧 사라졌다.\n→The smile soon faded from her face.",
                      num3Text: "그녀는 사임하는 것 외에는 대안이 없었다.\n→ She had no alternative but to resign.",
                      num4Text: "나는 5년 후에 내 사업을 시작할 작정이다.\n→ I’m aiming to start my own business in five years.",
                      answer: 1),
        QuestionModel(num: 8,
                      questionText: "",
                      num1Text: "식사를 마치자마자 나는 다시 배고프기 시작했다.\n→No sooner I have finishing the meal than I started feeling hungry again.",
                      num2Text: "그녀는 조만간 요금을 내야만 할 것이다.\n→She will have to pay the bill sooner or later.",
                      num3Text: "독서와 정신의 관계는 운동과 신체의 관계와 같다.\n→Reading is to the mind what exercise is to the body.",
                      num4Text: "그는 대학에서 의학을 공부했으나 결국 회계 회사에서 일하게 되었다.\n→He studied medicine at university but ended up working for an accounting firm.",
                      answer: 1),
        QuestionModel(num: 9,
                      questionText: "두 사람의 대화 중 가장 어색한 것은?",
                      num1Text: "A: I like this newspaper because it’s not opinionated.\nB: That’s why it has the largest circulation.",
                      num2Text: "A: Do you have a good reason for being all dressed up?\nB: Yeah, I have an important job interview today.",
                      num3Text: "A: I can hit the ball straight during the practice but not during the game.\nB: That happens to me all the time, too.",
                      num4Text: "A: Is there any particular subject you want to paint on canvas?\nB: I didn’t do good in history when I was in high school.",
                      answer: 4),
        QuestionModel(num: 10,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것은?",
                      reference: "A: Hey! How did your geography test go?\n\nB: Not bad, thanks. I’m just glad that it’s over! How about you? How did your science exam go?\n\nA: Oh, it went really well. ____________________. I owe you a treat for that.\n\nB: It’s my pleasure. So, do you feel like preparing for the math exam scheduled for next week?\n\nA: Sure. Let’s study together.\n\nB: It sounds good. See you later.",
                      num1Text: "There’s no sense in beating yourself up over this",
                      num2Text: "I never thought I would see you here",
                      num3Text: "Actually, we were very disappointed",
                      num4Text: "I can’t thank you enough for helping me with it",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "주어진 글 다음에 이어질 글의 순서로 가장 적절한 것은?",
                      reference: "For people who are blind, everyday tasks such as sorting through the mail or doing a load of laundry present a challenge.",
                      reference2: "(A) That’s the thinking behind Aira, a new service that enables its thousands of users to stream live video of their surroundings to an on-demand agent, using either a smartphone or Aira’s proprietary glasses.\n\n(B) But what if they could “borrow” the eyes of someone who could see?\n\n(C) The Aira agents, who are available 24/7, can then answer questions, describe objects or guide users through a location.",
                      num1Text: "(A)-(B)-(C)",
                      num2Text: "(A)-(C)-(B)",
                      num3Text: "(B)-(A)-(C)",
                      num4Text: "(C)-(A)-(B)",
                      answer: 3),
        QuestionModel(num: 12,
                      questionText: "주어진 문장이 들어갈 위치로 가장 적절한 곳은?",
                      reference: "The comparison of the heart to a pump, however, is a genuine analogy.",
                      reference2: "An analogy is a figure of speech in which two things are asserted to be alike in many respects that are quite fundamental. Their structure, the relationships of their parts, or the essential purposes they serve are similar, although the two things are also greatly dissimilar. Roses and carnations are not analogous. ( 1 ) They both have stems and leaves and may both be red in color. ( 2 ) But they exhibit these qualities in the same way; they are of the same genus. ( 3 ) These are disparate things, but they share important qualities: mechanical apparatus, possession of valves, ability to increase and decrease pressures, and capacity to move fluids. ( 4 ) And the heart and the pump exhibit these qualities in different ways and in different contexts.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 3),
        QuestionModel(num: 13,
                      questionText: "다음 글의 제목으로 가장 적절한 것은?",
                      reference: "One of the areas where efficiency can be optimized is the work force, through increasing individual productivity ―defined as the amount of work (products produced, customers served) an employee handles in a given time. In addition to making sure you have invested in the right equipment, environment, and training to ensure optimal performance, you can increase productivity by encouraging staffers to put an end to a modern-day energy drain: multitasking. Studies show it takes 25 to 40 percent longer to get a job done when you’re simultaneously trying to work on other projects. To be more productive, says Andrew Deutscher, vice president of business development at consulting firm The Energy Project, “do one thing, uninterrupted, for a sustained period of time.”",
                      num1Text: "How to Create More Options in Life",
                      num2Text: "How to Enhance Daily Physical Performance",
                      num3Text: "Multitasking is the Answer for Better Efficiency",
                      num4Text: "Do One Thing at a Time for Greater Efficiency",
                      answer: 4),
        QuestionModel(num: 14,
                      questionText: "글의 흐름상 가장 어색한 문장은?",
                      reference: "The skill to have a good argument is critical in life. But it’s one that few parents teach to their children. ①" + "We want to give kids a stable home, so we stop siblings from quarreling and we have our own arguments behind closed doors.".underLined + " ②" + "Yet if kids never get exposed to disagreement, we may eventually limit their creativity.".underLined + " ③" + "Children are most creative when they are free to brainstorm with lots of praise and encouragement in a peaceful environment.".underLined + " ④" + "It turns out that highly creative people often grow up in families full of tension.".underLined + " They are not surrounded by fistfights or personal insults, but real disagreements. When adults in their early 30s were asked to write imaginative stories, the most creative ones came from those whose parents had the most conflict a quarter-century earlier.",
                      num1Text: "",
                      num2Text: "",
                      num3Text: "",
                      num4Text: "",
                      answer: 3),
        QuestionModel(num: 15,
                      questionText: "다음 글의 내용과 일치하지 않는 것을 고르시오.[15~16]",
                      reference: "Christopher Nolan is an Irish writer of some renown in the English language. Brain damaged since birth, Nolan has had little control over the muscles of his body, even to the extent of having difficulty in swallowing food. He must be strapped to his wheelchair because he cannot sit up by himself. Nolan cannot utter recognizable speech sounds. Fortunately, though, his brain damage was such that Nolan’s intelligence was undamaged and his hearing was normal; as a result, he learned to understand speech as a young child. It was only many years later, though, after he had reached 10 years, and after he had learned to read, that he was given a means to express his first words. He did this by using a stick which was attached to his head to point to letters. It was in this ‘unicorn’ manner, letter-by-letter, that he produced an entire book of poems and short stories, Dam-Burst of Dreams, while still a teenager.",
                      num1Text: "Christopher Nolan은 뇌 손상을 갖고 태어났다.",
                      num2Text: "Christopher Nolan은 음식을 삼키는 것도 어려웠다.",
                      num3Text: "Christopher Nolan은 청각 장애로 인해 들을 수 없었다.",
                      num4Text: "Christopher Nolan은 10대일 때 책을 썼다.",
                      answer: 3),
        QuestionModel(num: 16,
                      questionText: "",
                      reference: "In many Catholic countries, children are often named after saints; in fact, some priests will not allow parents to name their children after soap opera stars or football players. Protestant countries tend to be more free about this; however, in Norway, certain names such as Adolf are banned completely. In countries where infant mortality is very high, such as in Africa, tribes only name their children when they reach five years old, the age in which their chances of survival begin to increase. Until that time, they are referred to by the number of years they are. Many nations in the Far East give their children a unique name which in some way describes the circumstances of the child’s birth or the parents’ expectations and hopes for the child. Some Australian aborigines can keep changing their name throughout their life as the result of some important experience which has in some way proved their wisdom, creativity or determination. For example, if one day, one of them dances extremely well, he or she may decide to re-name him/herself ‘supreme dancer’ or ‘light feet’.",
                      num1Text: "Children are frequently named after saints in many Catholic countries.",
                      num2Text: "Some African children are not named until they turn five years old.",
                      num3Text: "Changing one’s name is totally unacceptable in the culture of Australian aborigines.",
                      num4Text: "Various cultures name their children in different ways.",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "다음 글의 요지로 가장 적절한 것은?",
                      reference: "In one study, done in the early 1970s when young people tended to dress in either “hippie” or “straight” fashion, experimenters donned hippie or straight attire and asked college students on campus for a dime to make a phone call. When the experimenter was dressed in the same way as the student, the request was granted in more than two-thirds of the instances; when the student and requester were dissimilarly dressed, the dime was provided less than half the time. Another experiment showed how automatic our positive response to similar others can be. Marchers in an antiwar demonstration were found to be more likely to sign the petition of a similarly dressed requester and to do so without bothering to read it first.",
                      num1Text: "People are more likely to help those who dress like themselves.",
                      num2Text: "Dressing up formally increases the chance of signing the petition.",
                      num3Text: "Making a phone call is an efficient way to socialize with other students.",
                      num4Text: "Some college students in the early 1970s were admired for their unique fashion.",
                      answer: 1),
        QuestionModel(num: 18,
                      questionText: "(A)와 (B)에 들어갈 말로 가장 적절한 것은?",
                      reference: "Duration shares an inverse relationship with frequency. If you see a friend frequently, then the duration of the encounter will be shorter. Conversely, if you don’t see your friend very often, the duration of your visit will typically increase significantly.[ (A) ], if you see a friend every day, the duration of your visits can be low because you can keep up with what’s going on as events unfold. If, however, you only see your friend twice a year, the duration of your visits will be greater. Think back to a time when you had dinner in a restaurant with a friend you hadn’t seen for a long period of time. You probably spent several hours catching up on each other’s lives. The duration of the same dinner would be considerably shorter if you saw the person on a regular basis.[ (B) ], in romantic relationships the frequency and duration are very high because couples, especially newly minted ones, want to spend as much time with each other as possible. The intensity of the relationship will also be very high.",
                      num1Text: "For example - Conversely",
                      num2Text: "Nonetheless - Furthermore",
                      num3Text: "Therefore - As a result",
                      num4Text: "In the same way - Thus",
                      answer: 1),
        QuestionModel(num: 19,
                      questionText: "밑줄 친 부분에 들어갈 말로 가장 적절한 것을 고르시오.[19~20]",
                      reference: "One of the most frequently used propaganda techniques is to convince the public that the propagandist’s views reflect those of the common person and that he or she is working in their best interests. A politician speaking to a blue-collar audience may roll up his sleeves, undo his tie, and attempt to use the specific idioms of the crowd. He may even use language incorrectly on purpose to give the impression that he is “just one of the folks.” This technique usually also employs the use of glittering generalities to give the impression that the politician’s views are the same as those of the crowd being addressed. Labor leaders, businesspeople, ministers, educators, and advertisers have used this technique to win our confidence by appearing to be __________________________.",
                      num1Text: "beyond glittering generalities",
                      num2Text: "just plain folks like ourselves",
                      num3Text: "something different from others",
                      num4Text: "better educated than the crowd",
                      answer: 2),
        QuestionModel(num: 20,
                      questionText: "",
                      reference: "As a roller coaster climbs the first lift hill of its track, it is building potential energy—the higher it gets above the earth, the stronger the pull of gravity will be. When the coaster crests the lift hill and begins its descent, its potential energy becomes kinetic energy, or the energy of movement. A common misperception is that a coaster loses energy along the track. An important law of physics, however, called the law of conservation of energy, is that energy can never be created nor destroyed. It simply changes from one form to another. Whenever a track rises back uphill, the cars’ momentum—their kinetic energy—will carry them upward, which builds potential energy, and roller coasters repeatedly convert potential energy to kinetic energy and back again. At the end of a ride, coaster cars are slowed down by brake mechanisms that create __________ between two surfaces. This motion makes them hot, meaning kinetic energy is changed to heat energy during braking. Riders may mistakenly think coasters lose energy at the end of the track, but the energy just changes to and from different forms.",
                      num1Text: "gravity",
                      num2Text: "friction",
                      num3Text: "vacuum",
                      num4Text: "acceleration",
                      answer: 2)
        
        ]
        let exam = ExamModel(id: 202322, year: 2023, examTypeID: "지방직", subjectID: "영어", questions: questions)
        exams2023.append(exam)
    }
    
    func saveExam202323() {
        let questions
        = [
        QuestionModel(num: 1,
                      questionText: "밑줄 친 ‘그’에 대한 설명으로 옳은 것은?",
                      reference: "이날 소정방이 부총관 김인문 등과 함께 기벌포에 도착하여 백제 군사와 마주쳤다. ...(중략) ... 소정방이 신라군이 늦게 왔다는 이유로 군문에서 신라 독군 김문영의 목을 베고자 하니, "+"그".underLined+"가 군사들 앞에 나아가 “황산 전투를 보지도 않고 늦게 온 것을 이유로 우리를 죄주려 하는구나. 죄도 없이 치욕을 당할 수는 없으니, 결단코 먼저 당나라 군사와 결전을 한 후에 백제를 쳐야겠다.”라고 말하였다.",
                      num1Text: "살수에서 수의 군대를 물리쳤다.",
                      num2Text: "김춘추의 신라 왕위 계승을 지원하였다.",
                      num3Text: "청해진을 설치하고 해상 무역을 전개하였다.",
                      num4Text: "대가야를 정벌하여 낙동강 유역을 확보하였다.",
                      answer: 2),
        QuestionModel(num: 2,
                      questionText: "다음 사건이 있었던 시기의 신라 국왕에 대한 설명으로 옳은 것은?",
                      reference: "이찬 이사부가 하슬라주 군주가 되어, ‘우산국 사람이 우매하고 사나워서 위엄으로 복종시키기는 어려우니 계책을 써서 굴복시키는 것이 좋겠다.’라고 생각하였다. 이에 나무로 사자 모형을 많이 만들어 배에 나누어 싣고 우산국 해안에 이르러, 속임수로 통고하기를 “만약에 너희가 항복하지 않는다면 곧바로 이 맹수들을 풀어 너희를 짓밟아 죽이겠다.” 라고 하였다. 그 나라 사람이 두려워 즉시 항복하였다.",
                      num1Text: "독서삼품과를 실시하였다.",
                      num2Text: "국호를 ‘신라’로 확정하였다.",
                      num3Text: "관료전을 지급하고 녹읍을 폐지하였다.",
                      num4Text: "장문휴를 보내 당의 등주를 공격하였다.",
                      answer: 2),
        QuestionModel(num: 3,
                      questionText: "밑줄 친 ‘이나라’에 대한 설명으로 옳은 것은?",
                      reference: "○ " + "이 나라".underLined + "에서 귀하게 여기는 것에는 태백산의 토끼, 남해부의 다시마, 책성부의 된장, 부여부의 사슴, 막힐부의 돼지, 솔빈부의 말, 현주의 베, 옥주의 면, 용주의 명주, 위성의 철, 노성의 쌀 등이 있다.\n\n-〖신당서〗-",
                      reference2: "○ " + "이 나라".underLined + "의 땅은 영주(營州)의 동쪽 2천 리에 있으며, 남으로는 신라와 서로 접한다. 월희말갈에서 동북으로 흑수말갈에 이르는데, 사방 2천 리, 호는 십여 만, 병사는 수만 명이다.\n\n-〖구당서〗-",
                      num1Text: "중앙에 6좌평의 관제를 마련하였다.",
                      num2Text: "9서당 10정의 군사 조직을 갖추었다.",
                      num3Text: "지방을 5경 15부 62주로 편성하였다.",
                      num4Text: "제가회의에서 국가의 중대사를 결정하였다.",
                      answer: 3),
        QuestionModel(num: 4,
                      questionText: "밑줄 친 ‘왕’의 업적으로 옳은 것은?",
                      reference: "풍토에 따라 곡식을 심고 가꾸는 법이 다르니, 고을의 경험 많은 농부를 각 도의 감사가 방문하여 농사짓는 방법을 알아본 후 아뢰라고 왕께서 명령하셨다. 이어 왕께서 정초와 변효문 등을 시켜 감사가 아뢴 바 중에서 꼭 필요하고 중요한 것만을 뽑아 〖농사직설〗을 편찬하게 하셨다.",
                      num1Text: "공법을 제정하였다.",
                      num2Text: "한양으로 도읍을 옮겼다.",
                      num3Text: "〖경국대전〗을 완성하였다.",
                      num4Text: "조광조를 등용하여 개혁 정치를 실시하였다.",
                      answer: 1),
        QuestionModel(num: 5,
                      questionText: "밑줄 친 ‘이들’에 해당하는 것은?",
                      reference: "이들".underLined + "의 과거 응시와 벼슬을 제한한 것은 우리나라의 옛 법이 아니다. 그런데 〖경국대전〗을 편찬한 뒤부터 " + "이들".underLined + "을 금고(禁錮)하였으니, 아직 백 년이 채 되지 않았다. 또한 다른 나라에 이러한 법이 있다는 말은 듣지 못했다. 경대부(卿大夫)의 자식인데 오직 어머니가 첩이라는 이유만으로 대대로 " + "이들".underLined + "의 벼슬길을 막아, 비록 훌륭한 재주와 쓸만한 자질이 있어도 이를 발휘할 수 없게 하였으니, 참으로 안타깝다.",
                      num1Text: "향리",
                      num2Text: "노비",
                      num3Text: "서얼",
                      num4Text: "백정",
                      answer: 3),
        QuestionModel(num: 6,
                      questionText: "밑줄 친 ‘왕’의 재위 기간에 있었던 일로 옳은 것은?",
                      reference: "○ 평농서사 권신(權信)이 대상(大相) 준홍(俊弘)과 좌승 (佐丞) 왕동(王同) 등이 반역을 꾀한다고 참소하자 왕이 이들을 내쫓았다.\n\n○ 왕이 쌍기의 건의를 받아 처음으로 과거를 실시하였다. 시(詩).부(賦).송(頌) 및 시무책을 시험하여 진사를 뽑았으며, 더불어 명경업.의업.복업 등도 뽑았다.",
                      num1Text: "노비안검법을 제정하였다.",
                      num2Text: "전민변정도감을 설치하였다.",
                      num3Text: "토지제도로서 전시과를 시행하였다.",
                      num4Text: "12목을 설치하고 지방관을 파견하였다.",
                      answer: 1),
        QuestionModel(num: 7,
                      questionText: "다음 글은 어떤 사건이 일어났을 때 발표되었는가?",
                      reference: "1. 마산, 서울 기타 각지의 데모는 주권을 빼앗긴 국민의 울분을 대신하여 궐기한 학생들의 순수한 정의감의 발로이며 부정과 불의에는 언제나 항거하는 민족정기의 표현이다.\n... (중략) ...\n3. 합법적이고 평화적인 데모 학생에게 총탄과 폭력을 거리낌 없이 남용하여 참극을 빚어낸 경찰은 자유와 민주를 기본으로 한 대한민국의 국립 경찰이 아니라 불법과 폭력으로 권력을 유지하려는 일부 정부 집단의 사병이다.\n\n-〖대학 교수단 4.25 선언문〗-",
                      num1Text: "4.19 혁명",
                      num2Text: "5.18 민주화 운동",
                      num3Text: "6.3 시위",
                      num4Text: "6.29 민주화 선언",
                      answer: 1),
        QuestionModel(num: 8,
                      questionText: "밑줄 친 ‘이시기’에 있었던 사실로 옳은 것은?",
                      reference: "이 시기".underLined + "의 불교 조각은 지역에 따라 다양하게 제작되었다. 처음에는 하남 하사창동의 철조 석가여래 좌상과 같은 대형 철불이 많이 제작되었다. 또한 덩치가 큰 석불이 유행하였는데, 논산 관촉사 석조 미륵보살 입상이 대표적이다. 이 불상은 큰 규모에 비해 조형미는 다소 떨어지지만, 소박한 지방 문화의 모습을 잘 보여 준다.",
                      num1Text: "성골 출신의 국왕이 재위하였다.",
                      num2Text: "지방 세력으로 호족이 존재하였다.",
                      num3Text: "풍양 조씨 등 특정 가문이 정권을 장악하였다.",
                      num4Text: "성리학에 투철한 사림 세력이 정국을 주도하였다.",
                      answer: 2),
        QuestionModel(num: 9,
                      questionText: "역사서에 대한 설명으로 옳은 것만을 모두 고르면?",
                      reference: "ᄀ. 김부식의 〖삼국사기〗에는 단군 신화가 수록되어 있다.\nᄂ. 이규보의 〖동명왕편〗은 고구려 계승 의식을 강조하였다.\nᄃ. 안정복의 〖동사강목〗은 기사 본말체로 역사를 서술하였다.\nᄅ. 유득공의 〖발해고〗에는 남북국이라는 용어가 사용되었다.",
                      num1Text: "ᄀ, ᄂ",
                      num2Text: "ᄀ, ᄃ",
                      num3Text: "ᄂ, ᄅ",
                      num4Text: "ᄃ, ᄅ",
                      answer: 3),
        QuestionModel(num: 10,
                      questionText: "밑줄 친 ‘나’가 국왕으로 재위하던 기간에 있었던 일은?",
                      reference: "팔순 동안 내가 한 일을 만약 나 자신에게 묻는다면\n첫째는 탕평책인데, 스스로 ‘탕평’이란 두 글자가 부끄럽다.\n둘째는 균역법인데, 그 효과가 승려에게까지 미쳤다.\n셋째는 청계천 준설인데, 만세에 이어질 업적이다.\n  ... (하략) ...\n\n-〖어제문업(御製問業)〗-",
                      num1Text: "장용영이 창설되었다.",
                      num2Text: "나선정벌이 단행되었다.",
                      num3Text: "홍경래의 난이 발생하였다.",
                      num4Text: "〖동국문헌비고〗가 편찬되었다.",
                      answer: 4),
        QuestionModel(num: 11,
                      questionText: "(가) 시기에 있었던 사실로 옳은 것은?",
                      reference: " [ 을미사변 ] \n   ⇩   \n [ (가) ]\n   ⇩   \n [ 러일전쟁 ]",
                      num1Text: "독립문이 건립되었다.",
                      num2Text: "통감부가 설치되었다.",
                      num3Text: "동양 척식 주식회사가 설립되었다.",
                      num4Text: "임진왜란 때 소실된 경복궁이 중건되었다.",
                      answer: 1),
        QuestionModel(num: 12,
                      questionText: "밑줄 친 ‘왕’의 재위기간에 있었던 일로 옳은 것은?",
                      reference: "왕".underLined + "의 어릴 때 이름은 모니노이며, 신돈의 여종 반야의 소생이었다. 어떤 사람은 “반야가 낳은 아이가 죽어서 다른 아이를 훔쳐서 길렀는데, 공민왕이 자신의 아들이라고 칭하였다.”라고 하였다. " + "왕".underLined + "은 공민왕이 죽은 뒤 이인임의 추대로 왕위에 올랐다. 이후 이인임, 염흥방, 임견미 등이 권력을 잡아 극심하게 횡포를 부렸다.",
                      num1Text: "이종무가 왜구의 소굴인 대마도를 정벌하였다.",
                      num2Text: "삼별초가 반란을 일으켜 대몽 항쟁을 계속하였다.",
                      num3Text: "쌍성총관부를 공격해 철령 이북 지역을 수복하였다.",
                      num4Text: "요동 정벌을 위해 출병한 이성계가 위화도에서 회군하였다.",
                      answer: 4),
        QuestionModel(num: 13,
                      questionText: "다음과 관련된 운동에 대한 설명으로 옳은 것은?",
                      imgModel: ImageModel(imageString: "ChosunMoolSan", imgWidth: 150, imgHeight: 200),
                      num1Text: "가뭄과 홍수로 인해 중단되었다.",
                      num2Text: "조선총독부의 〖회사령〗에 맞서기 위해 전개되었다.",
                      num3Text: "일부 사회주의자는 자본가 계급을 위한 운동이라고 비판하였다.",
                      num4Text: "조선에 사는 일본인이 일본 자본에 대항하기 위해 일으켰다.",
                      answer: 3),
        QuestionModel(num: 14,
                      questionText: "다음과 같은 대통령 선출 방식이 포함된 헌법의 내용으로 옳지 않은 것은?",
                      reference: "제39조 ① 대통령은 통일주체국민회의에서 토론없이 무기명 투표로 선거한다.\n② 통일주체국민회의에서 재적 대의원 과반수의 찬성을 얻은 자를 대통령당선자로 한다.",
                      num1Text: "대통령은 국회를 해산할 수 있다.",
                      num2Text: "대통령의 임기는 7년으로 하며, 중임할 수 없다.",
                      num3Text: "대법원장은 대통령이 국회의 동의를 얻어 임명한다.",
                      num4Text: "대통령은 국정 전반에 걸쳐 필요한 긴급조치를 할 수 있다.",
                      answer: 2),
        QuestionModel(num: 15,
                      questionText: "다음 사건을 시기순으로 바르게 나열한 것은?",
                      reference: "(가) 신라의 한강 유역 확보\n(나) 관산성 전투\n(다) 백제의 웅진 천도\n(라) 고구려의 평양 천도",
                      num1Text: "(가)→(라)→(나)→(다)",
                      num2Text: "(나)→(다)→(가)→(라)",
                      num3Text: "(다)→(나)→(가)→(라)",
                      num4Text: "(라)→(다)→(가)→(나)",
                      answer: 4),
        QuestionModel(num: 16,
                      questionText: "(가) 인물에 대한 설명으로 옳은 것은?",
                      reference: "군대를 이끌고 통주성 남쪽으로 나가 진을 친 [ (가) ]은/는 거란군에게 여러 번 승리를 거두었다. 하지만 자만하게 된 그는 결국 패해 거란군의 포로가 되었다. 거란의 임금이 그의 결박을 풀어 주며 “내 신하가 되겠느냐?”라고 물으니, [ (가) ]은/는 “나는 고려 사람인데 어찌 너의 신하가 되겠느냐?”라고 대답하였다. 재차 물었으나 같은 대답이었으며, 칼로 살을 도려내며 물어도 대답은 같았다. 거란은 마침내 그를 처형하였다.",
                      num1Text: "묘청의 난을 진압하였다.",
                      num2Text: "별무반의 편성을 건의하였다.",
                      num3Text: "목종을 폐위하고 현종을 옹립하였다.",
                      num4Text: "거란과 협상하여 강동 6주 지역을 고려 영토로 확보하였다.",
                      answer: 3),
        QuestionModel(num: 17,
                      questionText: "밑줄 친 ‘저’에 대한 설명으로 옳은 것은?",
                      reference: "올해 초가을에 비로소 " + "저".underLined + "는 책을 완성하여 그 이름을 〖성학집요〗라고 하였습니다. 이 책에는 임금이 공부해야 할 내용과 방법, 정치하는 방법, 덕을 쌓아 실천하는 방법과 백성을 새롭게 하는 방법이 실려 있습니다. 또한 작은 것을 미루어 큰 것을 알게 하고 이것을 미루어 저것을 밝혔으니, 천하의 이치가 여기에서 벗어나지 않을 것입니다. 따라서 이것은 " + "저".underLined + "의 글이 아니라 성현의 글이옵니다.",
                      num1Text: "예안향약을 만들었다.",
                      num2Text: "〖동호문답〗을 저술하였다.",
                      num3Text: "백운동서원을 건립하였다.",
                      num4Text: "왕자의 난 때 죽임을 당했다.",
                      answer: 2),
        QuestionModel(num: 18,
                      questionText: "밑줄 친 ‘나’에 대한 설명으로 옳은 것만을 모두 고르면?",
                      reference: "오늘날 사람은 모두 법에 의하여 생활하고 있는데 실제로 사람을 죽인 자가 벌을 받지 않고 생존할 도리는 없는 것이다. ...(중략)... " + "나".underLined + "는 한국의 의병이며 지금 적군의 포로가 되어 와 있으므로 마땅히 만국공법에 의해 처단 되어야 할 것으로 생각한다.",
                      reference2: "ᄀ. 일본에서 순국하였다.\nᄂ. 한인 애국단 소속이었다.\nᄃ.〖동양평화론〗을 집필하였다.\nᄅ. 연해주에서 의병 투쟁을 전개하였다.",
                      num1Text: "ᄀ, ᄂ",
                      num2Text: "ᄀ, ᄅ",
                      num3Text: "ᄂ, ᄃ",
                      num4Text: "ᄃ, ᄅ",
                      answer: 4),
        QuestionModel(num: 19,
                      questionText: "다음 조항을 포함한 법률에 대한 설명으로 옳지 않은 것은?",
                      reference: "제1조 일본 정부와 통모하여 한일 합병에 적극 협력한 자, 한국의 주권을 침해하는 조약 또는 문서에 조인한 자와 이를 모의한 자는 사형 또는 무기 징역에 처하고, 그 재산과 유산의 전부 혹은 2분의 1 이상을 몰수한다.",
                      num1Text: "이 법률은 제헌국회에서 제정되었다.",
                      num2Text: "이 법률은 농지개혁법이 제정된 후 제정되었다.",
                      num3Text: "이 법률에 의해 반민특위와 특별 재판부가 구성되었다.",
                      num4Text: "이 법률에 의해 친일 경력을 지닌 고위 경찰 간부가 체포되었다.",
                      answer: 2),
        QuestionModel(num: 20,
                      questionText: "다음 글은 (가)의 부탁을 받고 (나)가 지은 것이다. (가)와 (나)에 대한 설명으로 옳은 것은?",
                      reference: "우리는 ‘외교’, ‘준비’ 등의 미련한 꿈을 버리고 민중 직접 혁명의 수단을 취함을 선언하노라. 조선 민족의 생존을 유지 하자면 강도 일본을 쫓아내야 하고, 강도 일본을 쫓아내려면 오직 혁명으로써만 가능하니, 혁명이 아니고는 강도 일본을 쫓아낼 방법이 없는 바이다.",
                      num1Text: "(가)는 조선 의용대를 결성하였고, (나)는 ‘국혼’을 강조하였다.",
                      num2Text: "(가)는 신흥 무관 학교를 세웠고, (나)는 형평사를 창립하였다.",
                      num3Text: "(가)는 조선 건국 동맹을 조직하였고, (나)는 식민 사학의 한국사 정체성론을 반박하였다.",
                      num4Text: "(가)는 황포 군관 학교에서 훈련받았고, (나)는 민족주의 역사 서술의 기본 틀을 제시하였다.",
                      answer: 4)
        
        
        ]
        let exam = ExamModel(id: 202323, year: 2023, examTypeID: "지방직", subjectID: "한국사", questions: questions)
        exams2023.append(exam)
    }
    
    
    
}
